### ISSUE TITLE
AutoFishing does not work on 1.14.4

### ISSUE THREAD

**Issue by Frog-Lover-Antony** [ORelio/Minecraft-Console-Client#1001]
Straight from #999 
* Lastest Build 1.9.0

<del>If` `terrainmovements=true` in config `AutoFishing` will not work and will not indicate any errors.
This might also cause `AutoAttack` to not work (not tested)
</del>

It turned out that `terrainmovements` does not affect AutoFishing. It just does not function on 1.14.4 (tested spigot, paperspigot, bukkit)

**Comment by ReinforceZwei** [comment]
Okay, I figured out what caused the issue. The ID of fishing hook is different in each MC version, but I just hard-coded the ID so it cause MCC not detecting fishing hook. This take some time to fix.
We need a "entity type generator" like the one for `itemType`.
@ORelio could you help me with this?

**Comment by ORelio** [comment]
Implemented entity type handling. May break things due to the large amount of changes.

**Comment by ReinforceZwei** [comment]
I have tested AutoAttack and AutoFishing on 1.15.2 and it is working nicely.
Will be tested on other version later.

**Comment by ORelio** [comment]
Thanks. Feel free to reopen if anything wrong appears later.
