### ISSUE TITLE
Linux mono compiling

### ISSUE THREAD

**Issue by Frog-Lover-Antony** [ORelio/Minecraft-Console-Client#1002]
Trying to setup MCC on a raspberry pi 0W.
Downloaded source, unpacked, installed mono-dev, trying to compile MinecraftClient.csproj with `mcs MinecraftClient.csproj` and I get an `Unrecognized escape sequence` error on every line, such as:
`
MinecraftClient.csproj(1,0): error CS1525: Unexpected symbol <'
MinecraftClient.csproj(16,17): error CS1009: Unrecognized escape sequence \<'
MinecraftClient.csproj(16,17): error CS1056: Unexpected character \003c'
MinecraftClient.csproj(37,17): error CS1009: Unrecognized escape sequence \D'
MinecraftClient.csproj(37,17): error CS1009: Unrecognized escape sequence \D'
MinecraftClient.csproj(46,17): error CS1009: Unrecognized escape sequence \R'
MinecraftClient.csproj(166,31): error CS1009: Unrecognized escape sequence \L'`
and so on.
Am I missing something or doing something wrong?

**Comment by Frog-Lover-Antony** [comment]
Ok so basicaly I got tired of searching and wgo't the executable without hoping it will work
And it runs on ARM without recompiling (`mono MCC.exe`)

**Comment by ORelio** [comment]
Building should work using msbuild (https://github.com/mono/msbuild)
But yeah, the executable contains bytecode like Java jar files, so it can run on different CPUs.
