### ISSUE TITLE
How works autorelog

### ISSUE THREAD

**Issue by slaapkopamy** [ORelio/Minecraft-Console-Client#1003]
**Prerequisites**
 - [ x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Hi I have a question about the autorelog function, I have most times problems with the autorelog that if one of my console clients disconnect that is going autorelog most of the time at the same time of multiple clients. I tried to work with extra delay but no success. Today it was one of the days that i got blacklisted again by mojang for too many logins so my question is:

Is the autorelog function working via the proxy or the main ip address of my server?
^same thing with the /reco command.
I have my proxy installed to only login via the proxy and then the main ip just to join the server etc.. 

Config example:
`#Minecraft Console Client v1.9.0
#Startup Config File

[Main]

#General settings
#leave blank to prompt user on startup
#Use "-" as password for offline mode

login=
password=
serverip=[removed]

#Advanced settings

language=en_GB
botowners=[removed]
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash #use 'none', 'slash' or 'backslash'
splitmessagedelay=20 #seconds between each part of a long message
botmessagedelay=20 #seconds to delay between message a bot makes to avoid accidental spam
mcversion=1.8.9 #use 'auto' or '1.X.X' values
brandinfo=mcc #use 'mcc','vanilla', or 'none'
chatbotlogfile= #leave empty for no logfile
privatemsgscmdname=tell #used by RemoteControl bot
showsystemmessages=true #system messages for server ops
showxpbarmessages=true #messages displayed above xp bar
terrainandmovements=true #uses more ram, cpu, bandwidth
sessioncache=disk #use 'none', 'memory' or 'disk'
accountlist=accounts.txt
serverlist=servers.txt
playerheadicon=true
exitonfailure=false
debugmessages=false
scriptcache=true
timestamps=true

[AppVars]
#yourvar=yourvalue
#can be used in some other fields as %yourvar%
#%username% and %serverip% are reserved variables.

[Proxy]
enabled=login #use 'false', 'true', or 'login' for login only
type=HTTP #Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=[removed]
username=[removed]
password=[removed]

[ChatFormat]
builtins=true #support for handling vanilla and common message formats
public=^<([a-zA-Z0-9_]+)> (.+)$
private=^([a-zA-Z0-9_]+) whispers to you: (.+)$
#tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

#Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=false
delay=1800 #10 = 1s
command=/baltop

[AutoRelog]
enabled=true
delay=60
retries=3 #-1 = unlimited
kickmessagesfile=kickmessages.txt

[ChatLog]
enabled=false
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=false
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=true
tasksfile=tasks.ini

[RemoteControl]
enabled=true
autotpaccept=true
tpaccepteveryone=false

[AutoRespond]
enabled=false
matchesfile=Matches.ini
`
In my situtation i use connect.bat with 6 accounts in it with a delay of 20 seconds. but thats only when i use start it up by server reboot of my own server, then its just going fine through the proxy...
(everything with [removed] have a normal value)

**Comment by ORelio** [comment]
Hi @slaapkopamy,

Indeed, when you have many accounts, it can be hard to relog on server restart because login is rate-limited. You can set many attempts, some clients should be able to relog while others would be rejected, wait and retry a couple more times until all clients are logged back in.

retries=10
kickmessagesfile=kickmessages.txt
kickmessages.txt => put the message shown when a client relog is rejected

There is a planned feature to make clients communicate so that they do not attempt to relog at the same time (#975) but we're lacking contributors at the moment so I cannot provide an ETA for it.

**Comment by ORelio** [comment]
Also as shown in your config `Minecraft Console Client v1.9.0` you are likely running a very old build.

**Comment by slaapkopamy** [comment]
> Also as shown in your config `Minecraft Console Client v1.9.0` you are likely running a very old build. I'd suggest to upgrade to the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

Im running atm not a old build or atleast not very old. I normally update once a month to a new build if it have an important update in it, since for that i need to restart every console client..

About the autorelog im still nog sure if is using my proxy to retry or just go retro back on the main ip address..

Im looking forward to #975 too bad my c# is not good enough to help :(

btw im using sessioncache via disk but every time i do reco or going to autorelog it says cache is expired or invalid. Even if i restart complete the console client its saying that and im only log in with 6 accounts per folder.. currently i have 7 folders.. Is this a bug or just a thing on my server only?

**Comment by ORelio** [comment]
That is why you should always update before opening issues. That was fixed 1 month ago in #952.

**Comment by slaapkopamy** [comment]
> That is why you should always update before opening issues. That was fixed 1 month ago in #952.

Im currently using that build, since if i update to a new build then i dont going generate a new config over and over, i have downloaded the minecraftclient.exe on 21/04/2020 22:36 that was my last updated file, (file is 1.866kb) 
![XGJDLKEBZgQg](https://user-images.githubusercontent.com/32595704/82222724-f6189c80-9921-11ea-83b8-6480d26d5d8f.png)

**Comment by ORelio** [comment]
Sorry, that issue seems very similar to the previously fixed bug. 🙏
In that case, I'd advise to set `debugmessages=true` in config and see what happens when session check fails. Beware to redact any password/session token/random strings when posting anything here.
