### ISSUE TITLE
I can't connect a 1.12.2 forge server

### ISSUE THREAD

**Issue by jiajiaxd** [ORelio/Minecraft-Console-Client#1004]
This is the log
Retrieving Server Info...
Server is running Forge. Mod list:
  minecraft v1.12.2
  mcp v9.42
  FML v8.0.99.99
  forge v14.23.5.2854
  bdlib v1.14.3.12
  appliedenergistics2 vrv6-stable-6
  ae2stuff v0.7.0.4
  jei v4.15.0.281
  customnpcs v1.12
  touhou_little_maid v1.1.10
  variedcommodities v1.12.2
  journeymap v1.12.2-5.5.4
  ic2 v2.8.187-ex112
  armourers_workshop v1.12.2-0.49.1
  ironchest v1.12.2-7.0.67.844
  endercore v1.12.2-0.5.73
  enderio v5.1.55
  enderiointegrationtic v5.1.55
  enderiobase v5.1.55
  enderioconduits v5.1.55
  enderioconduitsappliedenergistics v5.1.55
  enderioconduitsopencomputers v5.1.55
  enderioconduitsrefinedstorage v5.1.55
  enderiointegrationforestry v5.1.55
  enderiointegrationticlate v5.1.55
  enderiomachines v5.1.55
  enderiopowertools v5.1.55
  enderioendergy v5.1.55
  nuclearcraft v2.18o
  healthbar v1.0.7
  mekanism v1.12.2-9.8.3.390
  mekanismgenerators v1.12.2-9.8.3.390
  gravisuite v3.1.1
  advanced_solar_panels v4.3.0
Server version : Stove (protocol v1, with Forge).
Cannot connect to the server : This version is not supported !
Server version :

**Comment by ORelio** [comment]
`protocol v1` - the server is incorrectly stating which Minecraft version it is running.
Try ` mcversion=1.12.2` in config to force Minecraft v1.12.2

**Comment by jiajiaxd** [comment]
It doesn't work.
Log:
Version is supported.
Logging in...
Login failed :
This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.

**Comment by Frog-Lover-Antony** [comment]
Try setting your `brandinfo` to Forge.
Also, the server probably checks your mods. Right now you probably will not be able to fake/send your mod list... If, of course, someone won't make this possible in the next build.

**Comment by ORelio** [comment]
MCC already retrieves the mod list from server and sends it back to the server as installed mod list.
I think the issue here is either :
 - version = auto : MCC detects Forge but not the Minecraft version (not reported by server)
 - version = 1.X.X : MCC does not detect Forge and tries to login as Vanilla

The version setting in config needs improvement to allow enabling Forge support.

**Comment by ORelio** [comment]
Now you can have `mcversion=1.X.X` and `mcforge=auto` in config, this should solve your issue.
