### ISSUE TITLE
we need mcc be easy

### ISSUE THREAD

**Issue by ElementClock** [ORelio/Minecraft-Console-Client#1005]
It needs to be similar to the type of integration package on mcbbs, because for an ordinary player, the cost is too high (in fact, I'm lazy) if he needs to learn how to use C. if there is an integration package, it has all the required functions, and the user only needs to modify a part of the content to use more functions, which is very good. I only use the server to hang up and chat for your project, and I can't even reply automatically.

My advice is to hope that auto fishing, auto attack and auto reply messages are as easy to use as fools.

or more detailed tutorial

**Comment by ReinforceZwei** [comment]
Have you read the README inside the configs folder? It contains the guidelines of how to use those automation and writing simple scripts. It might answer your questions.

**Comment by ElementClock** [comment]
as i sad.i am foolish.i need more fool way to use.In fact, I have looked at it many times, but my technology is not enough to support me. To be exact, I need to enable the auto reply function, but I will not start it.

**Comment by ElementClock** [comment]
> 您是否已阅读configs文件夹中的自述文件？它包含有关如何使用这些自动化和编写简单脚本的指南。它可能会回答您的问题。

What I imagine is that when I first run MCC, the software can automatically download and configure auto reply, phishing and other files.

**Comment by Frog-Lover-Antony** [comment]
Download the main package with `sample-scripts` and read some examples. Everything is made as easy as it possibly could be. To make your first chat bot all you need is nothing but a `txt` file and five lines of human-code. Not even C or C#.

**Comment by ORelio** [comment]
All features in this program are disabled by default. All you need to enable them is open the configuration file and set `enabled=true`. If you are too lazy to read a manual and enable a feature, you are looking for a commercial product with professional support, not a free open source project.
