### ISSUE TITLE
Fishing hook disappearing while fishing

### ISSUE THREAD

**Issue by Frog-Lover-Antony** [ORelio/Minecraft-Console-Client#1006]
Hey, It's me again. Now the question is:
The server I'm playing sometimes removes "trash" altogether with the hook entity and AutoFishing does not notice this, continuing to wait before a fish gets caught. Time before this happens depends on the amount of players and entities. Right now I'm trying just to blindly resume fishing with a `/useitem` task running every couple minutes, which is more of problem-making rather problem-solving because it most of the time stops the process while its still running. Any idea on how to keep AutoFishing running?

**Comment by ReinforceZwei** [comment]
Unfortunately, AutoFish need the fishing hook for detecting fish. Some other’s AutoFishing “listen” on the sound effect for detecting fish but that’s not how I implemented AutoFish 😢
Maybe adding a timeout could solve your issue. 
eg. If no fish was caught within 30 seconds, then throw the fishing rod again

**Comment by Frog-Lover-Antony** [comment]
@ReinforceZwei 
> Maybe adding a timeout could solve your issue.

I have thought about it but could not impliment. I wanted to make a timer reset by _[MCC] [AutoFish] Threw a fishing rod_, so if the message did not appear in 5 minutes >> `/useitem` and if it did, the timer resets and starts counting down again.
I could not impliment this due to the lack of C knowledge. Maybe you can help me out with making it?

**Comment by Frog-Lover-Antony** [comment]
@ReinforceZwei 
It looks like there is a `OnEntityDespawn` function inside of [AutoFishing.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/AutoFishing.cs).
I get that this function is supposed to stop the bot after a `/useitem` command, but what if you add a bot parameter which would do `useitem` again instead of `fishing=false`?
This could be configurable in `MinecraftConfiguration.ini` file as
`[AutoFishing] enabled=true antidespawn=true`
to make a fishing-only bot or to be able to use Autofishing the way it is now

**Comment by ReinforceZwei** [comment]
Seems like a good idea. I will do it when free.

**Comment by ReinforceZwei** [comment]
The fix was applied in my [forked repo](https://github.com/ReinforceZwei/Minecraft-Console-Client).
It will be great if you could test it for us before we merge the [PR](https://github.com/ORelio/Minecraft-Console-Client/pull/1009)

**Comment by Frog-Lover-Antony** [comment]
@ReinforceZwei Give me a minute to build...
First time I've managed to cure my stupidity and found out how to build this... Running for last 4 minutes stable. 
Next 30 mins will tell us...

**Comment by Frog-Lover-Antony** [comment]
Wow this actually fixes everything. Still running (1:09 - 1:40) for half an hour!
Thank you so much for the fix. No other problems detected so @ORelio can push it to master safely :)

**Comment by ReinforceZwei** [comment]
Nice to hear that 😄

Just my thought, I think the server shouldn’t de-spawn the fishing hook as fishing is a part of the game. You may want to report this bug to the server administrator.

**Comment by Frog-Lover-Antony** [comment]
> Just my thought, I think the server shouldn’t de-spawn the fishing hook as fishing is a part of the game. You may want to report this bug to the server administrator.
Well, the server is nearly dying because of entities.

But I've just discvered a bug: at 1:55:57 console says `Caught fish!`, but no `Threw a fishing rod` after it. Might be a hardware problem on raspberry but it anyway stopped working and was waiting for me to `/useitem` again

**Comment by ReinforceZwei** [comment]
`useItemCounter` is for thread-safe delay that uses `Update()` method which called 10 times a second.

> Well, the server is nearly dying because of entities.
Even though, the server shouldn't do that. The better way to deal with it is limit the number of passive mobs. Despawning a fishing hook doesn't help much.

Anyway, could you test it again? It sounds like a server-side problem (maybe due to the lag?)

**Comment by ORelio** [comment]
(Issue auto-closed due to merging #1009. Feel free to reopen if fixes are still needed.
