### ISSUE TITLE
Failed to login 

### ISSUE THREAD

**Issue by Vinzi1** [ORelio/Minecraft-Console-Client#1008]
Yea Hi so I get that blacklisted IP shit a lot lately after like 8 accounts logged on the IP is already blocked and I have set Sessioncache=disk. Is there anything else I could try?

**Comment by ORelio** [comment]
Mojang limits how many logins you can perform in a time span. The session cache will hold session to avoid re-performing a full login, but that will not help when you start from scratch with lots of accounts. You'll need to wait before logging in more accounts. Then, once all accounts are present in the session cache on disk, you'll have less strict limits (but still present!). There is nothing we can do on our side.

**Comment by Vinzi1** [comment]
alright thanks anyways
