### ISSUE TITLE
Implements right click and middle click

### ISSUE THREAD

**Issue by Stymix** [ORelio/Minecraft-Console-Client#1010]
Hi, someone can help me by implementing middle click (knurl) and right click when I pressed the E button ?

Because we can only left click for the moment.

Thanks !

**Comment by ReinforceZwei** [comment]
After checking the [protocol](https://wiki.vg/Protocol#Click_Window) document, there is no middle click action for survival mode. Not sure why you need the middle click.

For right click, it is easy to implement. I will do it when free.

**Comment by Stymix** [comment]
I need middle click for use it in a plugin who opened a gui

**Comment by Stymix** [comment]
And thanks for the right click :smile:

**Comment by ReinforceZwei** [comment]
> I need middle click for use it in a plugin who opened a gui

I don't know how vanilla game will send the middle clicking packet when in survival mode so I m not sure how to implement it correctly.

BTW, the implementation of right clicking have been done.

**Comment by Stymix** [comment]
In faction when u want to sell your items in a gui shop, u can use the middle click

**Comment by Stymix** [comment]
and thanks for the right clicking

**Comment by ReinforceZwei** [comment]
Okay, I will try to implement it.
You may need to test it for me when I finished.

**Comment by ReinforceZwei** [comment]
Middle click was done. Please see my [repo](https://github.com/ReinforceZwei/Minecraft-Console-Client/tree/click).
It would be nice if you could test it for me before merging into master branch.

**Comment by ORelio** [comment]
Should be implemented now.
