### ISSUE TITLE
Inventory item drop

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1016]
**Feature description**
Add the function of throwing items out of inventory and so that you can take things from creative

**Comment by ReinforceZwei** [comment]
Dropping item from inventory isn’t very hard to make. I will do it later.

**Comment by ReinforceZwei** [comment]
Please note that you cannot "take" items from creative mode inventory with this feature. You should use in-game command `/give` instead.

**Comment by Nekiplay** [comment]
I do not have access to /give on the server but have access to / amemode 1

**Comment by ORelio** [comment]
Should be implemented now in the `/inventory` command.
