### ISSUE TITLE
AutoAttack

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1017]
AutoAttack players?

**Comment by ORelio** [comment]
Seems like a risky feature to add.

**Comment by ReinforceZwei** [comment]
Not a nice feature to add. 100% you will got banned by using this feature.

**Comment by Nekiplay** [comment]
I know I need this for a local server

**Comment by ReinforceZwei** [comment]
We don't know how people will use the feature if we added it. I don't want to see any complains about people they didn't read the instruction and got banned by server.

If you really need this feature, maybe you could implement it yourself. It should be quite easy to do.

**Comment by Nekiplay** [comment]
You can add non-safe mode to MinecraftClient.ini

**Comment by ORelio** [comment]
I think such feature would be abused by cheaters. I know that even TaskScheduler or AntiAFK are abused for spamming messages in chat while they are designed to perform routine tasks and/or stay active on the server. I fear that it would do more harm than anything else to automatically attack players. We can't add this to the main MCC codebase, sorry.
