### ISSUE TITLE
Console Client mod support

### ISSUE THREAD

**Issue by BlexMC** [ORelio/Minecraft-Console-Client#1019]
**Feature description**
Probably add an option to run the Client with mods (maybe Forge mods)? I don't know if it's too complicated or even possible but it would add many opportunities.

**Comment by ReinforceZwei** [comment]
MCC is written in C# while mods for Minecraft are written in Java. It is not possible to put them together.

**Comment by ORelio** [comment]
In MCC you can run MCC ChatBots but not Forge mods. MCC is totally not compatible with Java Forge mods because Forge is based on Minecraft while MCC is implemented from scratch.
