### ISSUE TITLE
AutoRelog

### ISSUE THREAD

**Issue by WilliamEpsilon** [ORelio/Minecraft-Console-Client#102]
Not really a confirmed issue but whenever the server restarts I'm moved to the hub server. Is there any way to make me launch a command from hub?

If not, can you design a module for this or edit the scripting so that I can do this? In example, I can set a watch command that watches for a certain message or waits until I'm moved to hub and it'll launch a command after 5 seconds.

**Comment by ORelio** [comment]
Hello,
You can use the `AutoRespond` bot from the development builds
Use it to detect `You have been moved to the hub` and send `/server myserver` after a delay.
Some files that should help you: [dev README](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/README.txt), [sample-matches](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-matches.ini) and [sample-script](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-script.txt) ;)

**Comment by ORelio** [comment]
Your issue should be resolved, but feel free to reopen if needed ;)
