### ISSUE TITLE
Missing items in /inventory

### ISSUE THREAD

**Issue by vaposhop123** [ORelio/Minecraft-Console-Client#1022]
A few days ago, all the items stop showing up in the /inventory # The first screenshot was taken using minecraft vanilla. The second capture was taken using the minecraft console client. I was using the latest build. Tested it on Windows, Ubuntu, different accounts, different IP, different Minecraft versions ins the config file. It's always the same result.
![image](https://user-images.githubusercontent.com/38889039/82772660-cc71e080-9e0d-11ea-9c60-a7b3bcf262d9.png)

![image](https://user-images.githubusercontent.com/38889039/82772692-e01d4700-9e0d-11ea-98e2-5c57e9e5e655.png)

You can check it out for yourself on this server : play.hadaria.fr in the Investment world at the login.

Is it possible that they hid the buttons when they detect a console client?

Thanks for the help

**Comment by Nekiplay** [comment]
use mcc version auto 1.12 - 1.12.2 Missing items in /inventory :)

**Comment by vaposhop123** [comment]
> use mcc version auto 1.12 - 1.12.2 Missing items in /inventory :)

I was already using mcc version auto 
![image](https://user-images.githubusercontent.com/38889039/82776200-18c21e00-9e18-11ea-84fc-2158323026c8.png)

![image](https://user-images.githubusercontent.com/38889039/82776109-d4368280-9e17-11ea-9cf3-20155391cb31.png)

**Comment by ORelio** [comment]
Seems like it displays contents of player inventory, not container inventory.
 * Please try out the latest dev build which is build 294, not 284 (just in case)
 * What happens when using `/inventory container`?

**Comment by vaposhop123** [comment]
Tried it on build 297 
<img width="743" alt="Capture d’écran, le 2020-05-25 à 22 35 53" src="https://user-images.githubusercontent.com/38889039/82855349-11167e00-9ed9-11ea-8665-bac5621a48f0.png">
Still the same result
<img width="516" alt="Capture d’écran, le 2020-05-25 à 22 38 40" src="https://user-images.githubusercontent.com/38889039/82855369-225f8a80-9ed9-11ea-9b10-b1d989693a57.png">
And for /inventory container :
<img width="462" alt="Capture d’écran, le 2020-05-25 à 22 41 41" src="https://user-images.githubusercontent.com/38889039/82855405-399e7800-9ed9-11ea-916e-53f6b8a97c95.png">

**Comment by vaposhop123** [comment]
> Seems like it displays contents of player inventory, not container inventory.
> 
> * Please try out the latest dev build which is build 294, not 284 (just in case)
> * What happens when using `/inventory container`?

Tried it on build 297 
![image](https://user-images.githubusercontent.com/38889039/82855647-da8d3300-9ed9-11ea-853d-ae15d7c019b8.png)
Still the same result
<img width="516" alt="Capture d’écran, le 2020-05-25 à 22 38 40" src="https://user-images.githubusercontent.com/38889039/82855369-225f8a80-9ed9-11ea-9b10-b1d989693a57.png">
And for /inventory container :
<img width="462" alt="Capture d’écran, le 2020-05-25 à 22 41 41" src="https://user-images.githubusercontent.com/38889039/82855405-399e7800-9ed9-11ea-916e-53f6b8a97c95.png">

**Comment by ORelio** [comment]
Still unsure what is causing this, but that's definitely a bug. Might be related to #1022

**Comment by vaposhop123** [comment]
> Still unsure what is causing this, but that's definitely a bug. Might be related to #1022

But everything was working fine like a week ago. They changed something on the server side that caused that.

**Comment by Nekiplay** [comment]
![image](https://user-images.githubusercontent.com/35975332/82972338-3ba62b00-9fee-11ea-8c1f-979f0f0a9c5b.png)

**Comment by vaposhop123** [comment]
After downloading the latest build, the issue is still there for me :/

**Comment by ORelio** [comment]
@vaposhop123 As stated above:
> Still unsure what is causing this, but that's definitely a bug. Might be related to #1022

So not fixed yet.
