### ISSUE TITLE
Custom Commands not Enabled

### ISSUE THREAD

**Issue by VerifiedNub** [ORelio/Minecraft-Console-Client#103]
Hi, CreateYourOwnMenus is a AWESOME plugin. Just one problem that I found, I link a command to a item, put it in a menu then test it. When I tested it said "Console commands are disabled. Enable them in config file". I go to the config file, it mentions nothing about console commands. PLEASE HELP!!

**Comment by ORelio** [comment]
Well, I'm not the author of CreateYourOwnMenus ans this error message does not seems to be generated by Minecraft Console Client. Maybe you tried to put a server command such as /stop and your plugin is telling you that you need to change some setting in the plugin's `config.yml` file.

**Comment by VerifiedNub** [comment]
No, I'm using a plugin called BlockDoors I wanted a menu that would trigger different things

**Comment by ORelio** [comment]
Well, I'm neither the author of `CreateYourOwnMenus` nor `BlockDoor` so I quite don't understand what you are expecting from me. I can only provide support for `Minecraft Console Client`.

**Comment by VerifiedNub** [comment]
It's alright I'm just asking the creators for help.

**Comment by ORelio** [comment]
They will most likely don't see your question here as this is the issue section for the `Minecraft Console Client` project, nothing more. You might want to read or ask on their respective project pages:
 - [CreateYourOwnMenus](http://dev.bukkit.org/bukkit-plugins/createyourownmenus/)
 - [BlockDoor](http://dev.bukkit.org/bukkit-plugins/blockdoor/)

**Comment by ORelio** [comment]
Closing as this issue is not related to Minecraft Console Client.
