### ISSUE TITLE
SendPluginChannelMessage

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1030]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
How to send 2 lines?

I need to get online on bungeecord server
![image](https://user-images.githubusercontent.com/35975332/83004788-83967380-a029-11ea-805a-02ff80cca4be.png)

**Comment by ORelio** [comment]
There is a SendPluginMessage API method, you need to set the desired channel, then encode your string eg Encoding.UTF8.GetBytes("PlayerList").

**Comment by Nekiplay** [comment]
Example?
![image](https://user-images.githubusercontent.com/35975332/83150478-bec1a100-a114-11ea-9014-049af8fe3218.png)

**Comment by Nekiplay** [comment]
> There is a SendPluginMessage API method, you need to set the desired channel, then encode your string eg Encoding.UTF8.GetBytes("PlayerList").
