### ISSUE TITLE
Incorrect password whatever i do

### ISSUE THREAD

**Issue by vanko13** [ORelio/Minecraft-Console-Client#1033]
every time i try to change something and its show ?? i read smth for dev build but dont have idea what is this for 
Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.

or i need to be premium to use it ?

**Comment by ORelio** [comment]
Yes, you need a valid Minecraft account. You can connect to offline-mode servers (ie non-premium servers) by using a blank password and any username as login.
