### ISSUE TITLE
Extra semicolon in Protocol18.cs

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1034]
Extra semicolon in [`Protocol18.cs` at line 1430](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#L1430), after the `else` statement.

**Comment by ORelio** [comment]
I think @Nekiplay fixed it in #1027, thanks for pointing out.
