### ISSUE TITLE
Explosion packet error in MC 1.8.X

### ISSUE THREAD

**Issue by Stymix** [ORelio/Minecraft-Console-Client#1037]
Hi, I have this error when I try to launch my console client (after typing the IP)

https://gyazo.com/30a819f3aca02272d89e674256259c86

![image](https://user-images.githubusercontent.com/1128206/83325102-20dfea80-a26a-11ea-9afe-5cbd4786c0a6.png)

**Comment by ORelio** [comment]
@Nekiplay : Seems like the new Explosion packet from #1027 is incorrectly processed in 1.8.X.

**Comment by ORelio** [comment]
OK, found out the issue: Packet ID was incorrect for MC 1.8 so a smaller packet was being incorrectly handled as Explosion packet. Should be resolved now, thanks for reporting the issue 🙂
