### ISSUE TITLE
About posting to other forums

### ISSUE THREAD

**Issue by jiajiaxd** [ORelio/Minecraft-Console-Client#1039]
MCC is great! Can I post MCC on MCBBS (China's biggest Minecraft Forum)?I promise I won't leak .exe file!

**Comment by ORelio** [comment]
Leak? You can't leak something that's publicly available 😋
https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts
Feel free to share MCC with anyone you want, please link to the repository as source 😉

**Comment by jiajiaxd** [comment]
Thank you
