### ISSUE TITLE
MCC error

### ISSUE THREAD

**Issue by GhettoSquid** [ORelio/Minecraft-Console-Client#1040]
Ive recently downloaded the MCC and it worked great on my main account for a couple days. The issue occurred when I attempted to use the MCC with my alt account. "Minecraft Login failed : Incorrect password, blacklisted IP or too many logins." is the error msg I keep getting. I know for a fact login information is correct,I've waited several hours between logins and I'm able to login in with my alt and my main at the same time using the normal Minecraft launcher. I would really appreciate some help on this thanks.

**Comment by ORelio** [comment]
Try `debugmessages=true` in config. Redact any password and session tokens (anything that looks like a random string) posting any screenshot or output here.

**Comment by MasterNKdog** [comment]
I am having a similar issue. I have used this config on a different server and it works without issue. I think it might just be something simple that I am overlooking. Any help would be appreciated. 

Console Client for MC 1.4.6 to 1.15.2 - v1.15.2 - By ORelio & Contributors
AppVeyor build 281, built on Thu 04/30/2020 from commit 116efc5
[MCC] [Settings] Loading Settings from <Location>\MinecraftClient.ini
Resolving xxxx
02:47:34 Initializing disk session cache using FileSystemWatcher
02:47:34 Loading Minecraft profiles: launcher_profiles.json
02:47:34 Loading session cache from disk: SessionCache.ini
02:47:34 Loaded session: xxxxxx
02:47:34 Session data has been successfully loaded from disk.
Connecting to Minecraft.net...
02:47:34 Performing request to authserver.mojang.com
02:47:35 > POST /authenticate HTTP/1.1
02:47:35 > Host: authserver.mojang.com
02:47:35 > User-Agent: MCC/1.15.2
02:47:35 > Content-Type: application/json
02:47:35 > Content-Length: 179
02:47:35 > Connection: close
02:47:35 >
02:47:35 > {"agent": { "name": "Minecraft", "version": 1 }, "username": "<username>\u0040gmail\u002ecom", "password": "<password>\u0021", "clientToken": "<token>" }

02:47:35 < HTTP/1.1 403 Forbidden
02:47:35 < Content-Type: application/json
02:47:35 < Content-Length: 107
02:47:35 < Connection: close
02:47:35 < Accept-Ranges: bytes
02:47:35 < Date: Sat, 06 Jun 2020 06:47:35 GMT
02:47:35 < Server: Restlet-Framework/2.4.1
02:47:35 < Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
02:47:35 < X-Cache: Error from cloudfront
02:47:35 < Via: 1.1 0ff11d01f4414a1e45550bed248de108.cloudfront.net (CloudFront)
02:47:35 < X-Amz-Cf-Pop: YUL62-C1
02:47:35 < X-Amz-Cf-Id: ASuBAPfEwN6-6yt1JS4zNd0vapX31YRxIRllWNiLmQ8Y_iCvhlBjAw==
02:47:35 <
02:47:35 < {"error":"ForbiddenOperationException","errorMessage":"Invalid credentials. Invalid username or password."}
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.
02:47:35 [MCC] [AutoRelog] Launching with 2147483647 reconnection attempts
02:47:35 [MCC] [AutoRelog] Loading messages from file:

**Comment by OverHash** [comment]
@MasterNKdog Looks like you have invalid credentials, according to that error.

**Comment by MasterNKdog** [comment]
@OverHash I have the correct credentials, I was able to log in with them with the physical launcher on my local machine. I have a feeling it might be the ip address is blacklisted but I would like to confirm.

**Comment by OverHash** [comment]
@MasterNKdog The possible causes:
No, that's not possible. The error message there is `Invalid credentials. Invalid username or password.` which matches this error highlighted (The `error` field also matches up)
![image](https://user-images.githubusercontent.com/46231745/83939355-5e2b1600-a830-11ea-8012-1b882581f94f.png)

Are you absolutely sure you copied the username and password field correct? What happens when you run MinecraftConsoleClient as a CLI with the `username password server` parameters?
e.g. if username was example@gmail.com and password was example, then you would do something like
```
MinecraftClient.exe example@gmail.com example eu.mineplex.com
```

**Comment by MasterNKdog** [comment]
I am absolutely sure that the credentials I have set are correct. I have copied/pasted into the launcher from the config file and they let me log in.

**Comment by ORelio** [comment]
Make sure there is no whitespace after your password, just in case. Also try decoding the raw JSON sent by MCC and comparing with your actual password. Example of tool that can unescape JSON sequences: https://www.freeformatter.com/json-escape.html (might not be safe to put a password in an online tool)
