### ISSUE TITLE
HTTP Post request cause timeout

### ISSUE THREAD

**Issue by 5tanly** [ORelio/Minecraft-Console-Client#1041]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**

Following the [sample http request](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-http-request.cs) script I made it post every message to a http server (my own local server)

It works as expected and I can see the messages in my post server, but after the 2nd post request the account times out and no longer posts anymore.

This isn't just because it sends the requests very fast after each other (it posts every chat message right now) because I have also observed in my [other script](https://gihtub.com/5tanly/factiontop) that uses post requests that after the 2nd one it also times out.
I looked at issue #715 but they are sending messages to python, and then from python to discord, I want to skip the python step since I am running it in a mono docker and don't have access to python in there

This is the code that is causing issues for me
```
//MCCScript 1.0

MCC.LoadBot(new test());

//MCCScript Extensions

public class test : ChatBot{

  public override void Initialize(){
    Console.WriteLine("Initialized");
  }
  public override void GetText(string text){
    text = GetVerbatim(text);
    //POST
    var httpWebRequest = (HttpWebRequest)WebRequest.Create("http://192.168.1.66:5000/post");
    httpWebRequest.ContentType = "text/plain";
    httpWebRequest.Method = "POST";
    using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream())){
      streamWriter.Write(text);
    }
    var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
    LogToConsole(httpResponse);
    }
  }
```

to reproduce, hook it up to any [post request service](https://ptsv2.com/) and after 2 messages are sent in the chat it will time out

OS: Debian 5.5.1-1 (Usul)
Mono 6.8.0.96

No debug messages showed up when testing this

Also, when it is in "timeout" mode, I have observed using another account on the server that the timed out account can still send messages, but nothing will show up in its console window

**Comment by 5tanly** [comment]
It may be an issue with [this](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/)
since it seems that the program is already using HTTP requests when [searching the code](https://github.com/ORelio/Minecraft-Console-Client/search?q=HttpWebRequest&unscoped_q=HttpWebRequest)

**Comment by ORelio** [comment]
The packet processing thread cannot be stopped for performing many HTTP requests or it will fall behind other packets sent by the server and ultimately time out. You can perform HTTP requests asynchronously using a Thread to avoid stopping the packet processing thread:
```C#
void SendHttpPostAsync(string uri, string text)
{
    new Thread(() => {
        var request = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(uri);
        request.ContentType = "text/plain";
        request.Method = "POST";
        using (var streamWriter = new StreamWriter(request.GetRequestStream()))
            streamWriter.Write(text);
        var response = (System.Net.HttpWebResponse)request.GetResponse();
        string responseString;
        using (var stream = response.GetResponseStream())
        using (var reader = new StreamReader(stream))
            responseString = reader.ReadToEnd();
        //LogToConsole(responseString);
    }).Start();
}
```
LogToConsole() should be thread-safe.

**Comment by 5tanly** [comment]
The above code works! Thank you
