### ISSUE TITLE
Player inventory empty after respawn

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1043]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**

Inventory of the bot is not possible to see after he died and respawn

**Comment by ORelio** [comment]
Should be resolved as per #1067, I'll let you check if it works.
