### ISSUE TITLE
Is there a way to show login (email address) on the window titlebar?

### ISSUE THREAD

**Issue by grantemsley** [ORelio/Minecraft-Console-Client#1046]
I've tried setting `consoletitle=%username% - %login%`, but that doesn't work.
Is there a variable for the login that can be used?

I'm starting several clients with a bat script with login and password specified in the command line, and it would make it easier to identify which is which when there are problems if I could show the email address in the window.

**Comment by Nekiplay** [comment]
#1048

**Comment by Nekiplay** [comment]
You could also specify it manually

**Comment by Nekiplay** [comment]
Modify this request pool to your project yourself
