### ISSUE TITLE
Auto mine sugar canes

### ISSUE THREAD

**Issue by Tnavillacs** [ORelio/Minecraft-Console-Client#1047]

**Comment by Nekiplay** [comment]
> _No description provided._

For what purpose?
Block mining or what?

**Comment by Scallivant** [comment]
> > _No description provided._
> 
> For what purpose?
> Block mining or what?

yes sugar cane

**Comment by Nekiplay** [comment]
> > > _No description provided._
> > 
> > 
> > For what purpose?
> > Block mining or what?
> 
> yes sugar cane

Expect to give you an example soon - a ready-made script

**Comment by Nekiplay** [comment]
> > > _No description provided._
> > 
> > 
> > For what purpose?
> > Block mining or what?
> 
> yes sugar cane
`//MCCScript 1.0

/* This is a sample script that will load a ChatBot into Minecraft Console Client
 * Simply execute the script once with /script or the script scheduler to load the bot */

MCC.LoadBot(new SurgarCaneMiner());


//MCCScript Extensions
/* The ChatBot class must be defined as an extension of the script in the Extensions section
 * The class can override common methods from ChatBot.cs, take a look at MCC's source code */

public class SurgarCaneMiner: ChatBot
{	
	Location SugarCane = new Location(x, y, z); /* SurgarCane location */
    public override void Initialize()
    {
		LogToConsole("Бот включен");
    }
	public override void Update()
	{
		PlayerDigging(0, SugarCane, 1);
		Thread.Sleep(100);
		PlayerDigging(2, SugarCane, 1);
	}
}
`

**Comment by Nekiplay** [comment]
> > > _No description provided._
> > 
> > 
> > For what purpose?
> > Block mining or what?
> 
> yes sugar cane

https://pastebin.com/vP0V2Ytk

**Comment by Nekiplay** [comment]
> > > _No description provided._
> > 
> > 
> > For what purpose?
> > Block mining or what?
> 
> yes sugar cane

Using two sugarcane blocks
https://pastebin.com/9Wwi7y4c

**Comment by Scallivant** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > For what purpose?
> > > Block mining or what?
> > 
> > 
> > yes sugar cane
> 
> https://pastebin.com/vP0V2Ytk

I have Problems with running it. It says (LoadError)  and theres a Problem with 'PlayerDigging'. Can I contact you on discord?

**Comment by Nekiplay** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > For what purpose?
> > > > Block mining or what?
> > > 
> > > 
> > > yes sugar cane
> > 
> > 
> > https://pastebin.com/vP0V2Ytk
> 
> I have Problems with running it. It says (LoadError) and theres a Problem with 'PlayerDigging'. Can I contact you on discord?

Update to the latest versions.

**Comment by ORelio** [comment]
Looks cool @Nekiplay with your permission may I add your script to the repository?

**Comment by Nekiplay** [comment]
> Looks cool @Nekiplay with your permission may I add your script to the repository?

Yes

**Comment by Scallivant** [comment]
> > > > > > _No description provided._
> > > > > 
> > > > > 
> > > > > For what purpose?
> > > > > Block mining or what?
> > > > 
> > > > 
> > > > yes sugar cane
> > > 
> > > 
> > > https://pastebin.com/vP0V2Ytk
> > 
> > 
> > I have Problems with running it. It says (LoadError) and theres a Problem with 'PlayerDigging'. Can I contact you on discord?
> 
> Update to the latest versions.
> This was added in this commit. [cf9bc4c](https://github.com/ORelio/Minecraft-Console-Client/commit/cf9bc4c3d54cec609c2d103a9df254fa83226c37)

I downloaded MinecraftClient build 303 why isnt it working.

**Comment by Nekiplay** [comment]
> > > > > > > _No description provided._
> > > > > > 
> > > > > > 
> > > > > > For what purpose?
> > > > > > Block mining or what?
> > > > > 
> > > > > 
> > > > > yes sugar cane
> > > > 
> > > > 
> > > > https://pastebin.com/vP0V2Ytk
> > > 
> > > 
> > > I have Problems with running it. It says (LoadError) and theres a Problem with 'PlayerDigging'. Can I contact you on discord?
> > 
> > 
> > Update to the latest versions.
> > This was added in this commit. [cf9bc4c](https://github.com/ORelio/Minecraft-Console-Client/commit/cf9bc4c3d54cec609c2d103a9df254fa83226c37)
> 
> I downloaded MinecraftClient build 303 why isnt it working.


Have you replaced x, y, z with the surgarcane coordinates?

**Comment by Scallivant** [comment]
> > > > > > > > _No description provided._
> > > > > > > 
> > > > > > > 
> > > > > > > For what purpose?
> > > > > > > Block mining or what?
> > > > > > 
> > > > > > 
> > > > > > yes sugar cane
> > > > > 
> > > > > 
> > > > > https://pastebin.com/vP0V2Ytk
> > > > 
> > > > 
> > > > I have Problems with running it. It says (LoadError) and theres a Problem with 'PlayerDigging'. Can I contact you on discord?
> > > 
> > > 
> > > Update to the latest versions.
> > > This was added in this commit. [cf9bc4c](https://github.com/ORelio/Minecraft-Console-Client/commit/cf9bc4c3d54cec609c2d103a9df254fa83226c37)
> > 
> > 
> > I downloaded MinecraftClient build 303 why isnt it working.
> 
> Have you replaced x, y, z with the surgarcane coordinates?

coordinates? im moving in a minecart

**Comment by Nekiplay** [comment]
Yes the coordinates of the sugarcane block
![image](https://user-images.githubusercontent.com/35975332/83980641-d7aa2d80-a930-11ea-8fca-9ed5c757f64a.png)

**Comment by Nekiplay** [comment]
> Looks cool @Nekiplay with your permission may I add your script to the repository?

I also have a script for auto tree farm
https://youtu.be/kXFYBH9aUd4

https://pastebin.com/7acKCZYc

**Comment by Scallivant** [comment]
> Yes the coordinates of the sugarcane block
> ![image](https://user-images.githubusercontent.com/35975332/83980641-d7aa2d80-a930-11ea-8fca-9ed5c757f64a.png)

Then that script is not working for me sadly. Because I'm moving in a Minecart hitting thousands of different Sugar canes. Thats why I was just asking for a Script that holds leftclick.

**Comment by Nekiplay** [comment]
> > Yes the coordinates of the sugarcane block
> > ![image](https://user-images.githubusercontent.com/35975332/83980641-d7aa2d80-a930-11ea-8fca-9ed5c757f64a.png)
> 
> Then that script is not working for me sadly. Because I'm moving in a Minecart hitting thousands of different Sugar canes. Thats why I was just asking for a Script that holds leftclick.

Then you need to add the coordinates of each sugarcane block

**Comment by ORelio** [comment]
The latest dev build was not compiling, fixed the issue in latest commit bfdfbe300972d91a49c64863ade48f5875db4fa0 you can download the newest build. Although build 303 should already contain all the API needed for the sugar cane script.

**Comment by Nekiplay** [comment]
> The latest dev build was not compiling, fixed the issue in latest commit [bfdfbe3](https://github.com/ORelio/Minecraft-Console-Client/commit/bfdfbe300972d91a49c64863ade48f5875db4fa0) you can download the newest build. Although build 303 should already contain all the API needed for the sugar cane script.

Yes

**Comment by Scallivant** [comment]
But how do I make it just hold leftclick? Because im not just hitting a single Scane.

**Comment by Nekiplay** [comment]
> But how do I make it just hold leftclick? Because im not just hitting a single Scane.

Not like
Just continue the code for this example.
https://pastebin.com/iREbCBnf

**Comment by Nekiplay** [comment]
@ORelio Here you can add AutoCobbleMiner
https://pastebin.com/vrh4CV4U

**Comment by Scallivant** [comment]
I would need to add like 4000 different coordinates. So thats not working for me. Is there no way to just hold leftclick and do nothing else? Your scripts look way too difficult. Just a script that holds leftclick.

**Comment by Nekiplay** [comment]
> I would need to add like 4000 different coordinates. So thats not working for me. Is there no way to just hold leftclick and do nothing else? Your scripts look way too difficult. Just a script that holds leftclick.


use the for loop
https://pastebin.com/Ve7EA98q

**Comment by Scallivant** [comment]
Actually with the newest Build The script is still not loading. And is there really no way to just hold digging?

**Comment by Nekiplay** [comment]
> Actually with the newest Build The script is still not loading. And is there really no way to just hold digging?


No, because the company uses the coordinates of the block to send the package

**Comment by Scallivant** [comment]
> > Actually with the newest Build The script is still not loading. And is there really no way to just hold digging?
> 
> No, because the packet uses the coordinates of the block to send the packet

Would it work with coordinates like ~ ~ ~2

**Comment by Nekiplay** [comment]
> > > Actually with the newest Build The script is still not loading. And is there really no way to just hold digging?
> > 
> > 
> > No, because the packet uses the coordinates of the block to send the packet
> 
> Would it work with coordinates like ~ ~ ~2

I told you to use the for loop
And add or decrease in the country that you need
https://pastebin.com/Ve7EA98q

**Comment by Nekiplay** [comment]
> > > Actually with the newest Build The script is still not loading. And is there really no way to just hold digging?
> > 
> > 
> > No, because the packet uses the coordinates of the block to send the packet
> 
> Would it work with coordinates like ~ ~ ~2


True Update does not work so fast so you can use a separate thread in which while will go

**Comment by Scallivant** [comment]
I need to break these in a Minecart. https://gyazo.com/a0fdd816481fccafaf420c7864c14f4b I would just need to hold Leftclick.

**Comment by Nekiplay** [comment]
> Looks cool @Nekiplay with your permission may I add your script to the repository?

https://pastebin.com/4cvUvpNy

**Comment by Nekiplay** [comment]
> @Nekiplay Sorry for disturbing you here but, i did all you said, i replaced the x y z from the sugarcane script, i have the latest vesion but im still getting this error
> failed to run (Load Error).
> system.invalidoperationexception: the name 'playerdigging' does not exist in the current context
> Im probably doing something wrong i have no clue what is it. I have the script on the same folder where my minecraftclient.exe still not working.

DigBlock

**Comment by ORelio** [comment]
Indeed. Fixed [in repository](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config/ChatBots).

**Comment by Heizee** [comment]
Not sure how to contact you so i'll just do it here @Nekiplay. I was wondering if its possible for the  cobblestoneminer to be used with plugin that generate random ores.

**Comment by Ansh51** [comment]
Hey i was wondering if the player could plant saplings automatically the rest would be done my the redstone machine like breaking and stuff
