### ISSUE TITLE
Can I move your software to my blog, only provide a download lin.

### ISSUE THREAD

**Issue by godkzm** [ORelio/Minecraft-Console-Client#1052]

**Comment by ORelio** [comment]
You can link download to https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts and create an article on your blog put please add a link to the repository https://github.com/ORelio/Minecraft-Console-Client as source. Thanks for sharing Minecraft Console Client 😉

**Comment by godkzm** [comment]
thanks!
