### ISSUE TITLE
I get kicked and my auto relog wont work.

### ISSUE THREAD

**Issue by TheFluffyPug** [ORelio/Minecraft-Console-Client#1054]
I keep getting kicked, which is shown by the photo below and I find it hard to afk for over an hour. I have my auto relog set to try every 30 seconds, but only 10 retries and it doesn't work.
<img width="392" alt="Screen Shot 2020-06-11 at 09 30 20" src="https://user-images.githubusercontent.com/66773335/84363158-35a37300-abc6-11ea-89dd-46ab37c2180d.png">

**Comment by ORelio** [comment]
Try `debugmessages=true` in config. The bot should display additional info about its behaviour and help you diagnosing your issue. You should be able to see if it's releated e.g. to the kick message or other reasons for not relogging automatically.
