### ISSUE TITLE
Inventories are not currently not handled for that MC Version

### ISSUE THREAD

**Issue by Stymix** [ORelio/Minecraft-Console-Client#1059]
Hi, 
When I tried to join a server, with minecract 1.8.8, this message appear :

https://gyazo.com/f6da25cf4f003ad2688198078222b783

Do you know if a fix is possible ?
Thanks.

**Comment by ORelio** [comment]
Hi,
MC 1.8 is not implemented for inventory handling.
I'll close your issue as a duplicate of #997.
