### ISSUE TITLE
PlayerDigging change to DigBlock

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1062]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
@ORelio could you replace in my chat bots PlayerDigging with DigBlock

**Comment by ORelio** [comment]
Fixed in #1047 / 09bfe92071b55cfbad9d0bd26acb1c0c05e6dd88
