### ISSUE TITLE
How to download this on mac

### ISSUE THREAD

**Issue by Vitaylity** [ORelio/Minecraft-Console-Client#1064]
Hey, Ive been looking for an afk console client for ages now. Ive recently found this one and Ive read over the instructions and installed mono but I still have no idea how to download this and run it on my mac. Can someone help me out? Thanks a lot!

**Comment by Vitaylity** [comment]
I have already downloaded this file but its .exe
https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by Vitaylity** [comment]
Ive already downloaded mono but its just not working

**Comment by Vitaylity** [comment]
Correction: Its there but Im not sure how I'm supposed to use it

**Comment by OverHash** [comment]
If you add mono to your PATH you can run something like
```
mono MinecraftClient.exe
```

**Comment by Vitaylity** [comment]
I did that however it did not work

**Comment by Vitaylity** [comment]
Cannot open assembly 'MinecraftClient.exe': No such file or directory.

**Comment by OverHash** [comment]
You have to be cd'ed into the folder that contains MinecraftClient.exe.

**Comment by Vitaylity** [comment]
cd'ed? Wdym

**Comment by ORelio** [comment]
`pwd`: show the folder you are currently in
`ls`: display folder contents
`cd <folder>`: move into <folder>
Still having trouble? Read a tutorial about how to use your terminal
https://computers.tutsplus.com/tutorials/navigating-the-terminal-a-gentle-introduction--mac-3855
