### ISSUE TITLE
using Hangman in C# Script with regex ?

### ISSUE THREAD

**Issue by Chtholly** [ORelio/Minecraft-Console-Client#1066]
[ChatFormat]
builtins=true
# private=...

While using this in Settings MCC respond  /msg bot start and Hangman dont starts.
If I delete the '#' infront of 'private=...' regex wont work anymore.
Is it possible to start Hangman via C# and using regex together ?

**Comment by ORelio** [comment]
I don't think so. The Hangman bot waits for a private message so the Regex needs to be right. If you regex does not properly detect private messages, that won't work.

**Comment by Chtholly** [comment]
Im using a regex in matches.ini that detects private messages, when i delete in settings the '#' infront of private=... then hangman responds on msgs and starts, but then matches.ini wont work anymore and this is the problem, i need that regex in matches.ini works and that i can start hangman on msgs or with a command via c#

**Comment by ORelio** [comment]
You should put your regex in the [ChatFormat] section, then AutoRespond will automatically use it with `actionprivate` and you just need to put some keywork in the match, or some regex that will be evaluated only against the message part of the private message instead of the whole line.

**Comment by Chtholly** [comment]
Thanks, works now
