### ISSUE TITLE
Incorrect items in inventory

### ISSUE THREAD

**Issue by Stymix** [ORelio/Minecraft-Console-Client#1070]
Hi, 
That's the first time than I see this error:

I'm login on the same server at the same moment on the both screen.
But look the /inventory doesn't send me real block, do you know why ?

![image](https://user-images.githubusercontent.com/23586833/84595667-74049080-ae59-11ea-928e-c8eb5732b0ab.png)

Thanks

**Comment by Nekiplay** [comment]
> Hi,
> That's the first time than I see this error:
> 
> I'm login on the same server at the same moment on the both screen.
> But look the /inventory doesn't send me real block, do you know why ?
> 
> ![image](https://user-images.githubusercontent.com/23586833/84595667-74049080-ae59-11ea-928e-c8eb5732b0ab.png)
> 
> Thanks

Check if you have the latest version of MCC before I noticed this, right now I do not have this

**Comment by Stymix** [comment]
I tryed by downloading the latest version 5 minutes ago
And nothing happening

**Comment by CrewParzi** [comment]
@Stymix try the same with mc version as 1.15.2
works on that version
