### ISSUE TITLE
Find Block location

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1073]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Can you please give a ready-made function to search for a specific block in 5 blocks?

**Comment by Nekiplay** [comment]
resolved

**Comment by ORelio** [comment]
Implemented in: #1152
