### ISSUE TITLE
Debug messages don't show when I disconnect

### ISSUE THREAD

**Issue by Isaacw24** [ORelio/Minecraft-Console-Client#1074]
I have turned debug messages on and when my character disconnects from the server it doesnt give a reason. Thank you

**Comment by ORelio** [comment]
Make sure you have the latest [dev build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), and watch for the startup line stating which configuration file is being loaded. Maybe it's not the one you are expecting.
