### ISSUE TITLE
Chat Colors

### ISSUE THREAD

**Issue by JeffHolliday** [ORelio/Minecraft-Console-Client#1075]
So I don't know if this is an issue on my side or what since I haven't seen any reports, but for some reason on my client chat colors like tags with color like Officer with the color blue in chat or people with custom tags on the server I play, the bot chat log wont record the chat down and if I have bot owner even it wont see my commands unless I msg the bot directly and even then it sometimes doesn't work. For example if I have the Hangman game running I can msg the bot start and it will see it but if I type a letter in chat it doesn't recognize my answer.
![Capture](https://user-images.githubusercontent.com/63996862/85097139-376bc880-b1bc-11ea-8b29-d8f0c939276a.PNG)

As you can see in the picture it will see my friend who doesn't have any custom tag but me with the colored Officer tag and even my name is colored blue (doesn't only happen with blue text btw) it wont see my text and even wont put my text in chat logs.

Was hoping if there was anyone that could help explain why this is happening and possibly how to fix it. I have even tried to add this § chat color code into the minecraft.ini chatformat to see if it would fix but no luck.

Server is pitforge.com or play.prismforge.com separate servers, but both are the same.

**Comment by ORelio** [comment]
See [detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages). You need to configure MCC with a regex corresponding to your server chat format as unfortunately, many servers are using a custom chat format that MCC cannot detect. As you noticed, MCC supports chat format `[Tag] Playername` but not `> Tag Playername:` which is specific to your server.
