### ISSUE TITLE
Fix ChatBots CobbleMiner, SugarCaneMiner new Direction

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1077]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**

**Comment by ORelio** [comment]
About that, I'm wondering if we could automate the dig block mechanism to avoid managing the "dig start" / "dig end" stuff manually in the bots, which is not intuitive. I'm thinking that we would need to determine how long we need to dig for a block, then dig automatically, and send a "dig end" event to the ChatBot which could then move on to the next block, for instance.

**Comment by Nekiplay** [comment]
It’s necessary to somehow track the block in front of the player

**Comment by Nekiplay** [comment]
it seems to me better to create like Nuker for a certain type of block

**Comment by ORelio** [comment]
Ok, so according to https://wiki.vg/How_to_Write_a_Client#Digging we might be able to send "dig start" then immediately "dig end" then wait for "Acknowledge Player Digging" or "Block Change" from server.

**Comment by Nekiplay** [comment]
Now add it

**Comment by ORelio** [comment]
In that case please wait before working on a new pull request.

**Comment by Nekiplay** [comment]
![image](https://user-images.githubusercontent.com/35975332/85209075-79c50f00-b34e-11ea-859c-67ac09fbe3f1.png)
Heh, with this code, it breaks the block but not to the end and it does not drop out

**Comment by ORelio** [comment]
Please note that if we're both working on the same code, we won't be able to merge properly. At the moment I'm also attempting to implement that.

**Comment by Nekiplay** [comment]
this requires a cycle that determines that the unit is not air

**Comment by ORelio** [comment]
Weird. On my side I have something very similar and it's not breaking anything. Still looking at it.

**Comment by Nekiplay** [comment]
Perhaps the distance to the block is large, I have everything on 1.12.2, 1.15.2 everything is fine

**Comment by ORelio** [comment]
I'm standing right in front of the block, and even compared "dig block" packets sent by a vanilla 1.15.2 with packet sent by MCC, they're the same. I pushed the commit so you can look at it.

**Comment by ORelio** [comment]
Well, at least you have the idea of what I had in mind: leave only the "location" parameter and let McClient handle the complicated part so chatbot and command only need to tell which block they want the client to break. I'll stop editing the code for now.

> Heh, with this code, it breaks the block but not to the end and it does not drop out

Yup, if you send dig start but never send dig end, you can run the dig animation forever :D
