### ISSUE TITLE
allowSmalTeleport

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1079]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
I noticed that your version of allowSmalTeleport works differently and slower than my version, I would still use my version or make a choice between yours and mine

**Comment by ORelio** [comment]
When merging your pull request, I replaced the existing implementation with yours so the `oldSmallTeleport` parameter is not added.
