### ISSUE TITLE
Help needed with command script

### ISSUE THREAD

**Issue by alimtairek** [ORelio/Minecraft-Console-Client#1082]
I am an absolute newbie and know little about code. I am trying to make a script that makes the client reconnect from the server every 4 minutes but I just can't get it to work. If anyone could make me a quick script that I could use and how to load it I'd appreciate it, thank you.

**Comment by ORelio** [comment]
I'd say this `tasks.ini` with ScriptScheduler bot that you can enable in `MinecraftClient.ini`:
```
[Task]
timeInterval=240
action=reco
```
