### ISSUE TITLE
Minecraft tree farm

### ISSUE THREAD

**Issue by Ansh51** [ORelio/Minecraft-Console-Client#1083]
**Prerequisites**
 - [yes] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [yes] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [yes] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

So i want to afk at a tree farm where you have to plant a sapling and the machine will do the rest of the work so are there any script makers who can help me with this please

**Comment by ORelio** [comment]
Still work in progress but a script for doing this is being developped and discussed in #1047

**Comment by ORelio** [comment]
Resolved as per [TreeFarmer.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/TreeFarmer.cs).
