### ISSUE TITLE
Inventory handling, containers

### ISSUE THREAD

**Issue by Ed6003** [ORelio/Minecraft-Console-Client#1084]
I am trying to automatically join a server with a server selector, the server selector automatically opens when you spawn in but I can also right click the compass with /inventory player/0 and open it. I try to do /inventory container list to see the items in the server selector but it says cannot find the container, please retry with explicit ID. How would I be able to find the container ID

**Comment by ORelio** [comment]
Just use `/inventory` to list inventories.
