### ISSUE TITLE
Error MSB4025 on Mac

### ISSUE THREAD

**Issue by TheSkelron** [ORelio/Minecraft-Console-Client#1086]
After typing 'msbuild MinecraftClient.exe' in an error message has now started to come up. error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

Not exactly sure on how to fix this on mac.

**Comment by ReinforceZwei** [comment]
The correct build command should be `msbuild MinecraftClient.csproj`

**Comment by TheSkelron** [comment]
When I try to do 'msbuild MinecraftClient.csproj' it comes up with another error. (ResolveAssemblyReferences target) -> 
  /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2101,5): warning MSB3256: No assemblies were read in from the redist lists. A TargetFramework profile exclusion list could not be generated.

**Comment by ORelio** [comment]
Unsure how to solve this, sorry.
