### ISSUE TITLE
Auto-Rejoin not working when my wifi cuts off

### ISSUE THREAD

**Issue by ningkaiyang** [ORelio/Minecraft-Console-Client#1087]
I've set up my console client so I can afk Hypixel at night.
I just used AutoRespond to automatically warp to my skyblock island whenever the server says something like "You are now in the HUB!" So I don't get afk kicked.

But, one problem is that sometimes when my wifi turns off, I just disconnect from the server with no message, and I do not rejoin. Only when I manually type /connect hypixel.net will it rejoin.

I tried toggling the "ignorekickmessage" so it would rejoin no matter what the message was, but it didn't work.
So what else can I do?

i guess i could use ScriptScheduler to automatically do connect hypixel.net, but that would disconnect me from the server if im already on and will waste time, so are there better ways?

How have other people handled wifi going off?

**Comment by ORelio** [comment]
Try `debugmessages=true` in config to show additional messages that may give hints about why you are not reconnecting.

**Comment by ningkaiyang** [comment]
k ty for answering, I thought this wasn't going to be answered. I'll turn on debugmessages=true and send more info, will be testing tonight

**Comment by CrewParzi** [comment]
yeah happens to me when I change networks, what you can do it have anti afk set up so that every 10 min or so there will be a command sent and if mcc is not connected it will say "Connection has been lost", you u can add that to the kick messages and when ever mcc sees that message it tries to reconnect

**Comment by ningkaiyang** [comment]
> yeah happens to me when I change networks, what you can do it have anti afk set up so that every 10 min or so there will be a command sent and if mcc is not connected it will say "Connection has been lost", you u can add that to the kick messages and when ever mcc sees that message it tries to reconnect

yeah thats what i just tried tonight since i noticed after it cut out I could just type a command and it would realize it was disconnected..



> Try `debugmessages=true` in config to show additional messages that may give hints about why you are not reconnecting.

also, I used debugmessages, and it really just seems the entire MCC just stops after wifi cuts. All Anti-Afk things stop, no debug messages, no scripts run, so I can't set anti-afk to spam commands cause it stops after wifi stops too.

I think I found a better app on phone to afk on my skyblock island called craftchat, idk why but my wifi is much more stable on my phone. I guess i won't trouble you guys anymore, thank you for helping.
