### ISSUE TITLE
How do I break automatic blocks?

### ISSUE THREAD

**Issue by Zuharik** [ORelio/Minecraft-Console-Client#1088]
**Prerequisites**
 - [+] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [+] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [+] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

How do I break automatic blocks?

**Comment by ningkaiyang** [comment]
Define 'Automatic'

Like blocks that appear automatically?
Or do you mean how do I automatically break blocks?

**Comment by ORelio** [comment]
Example: [CobblestoneMiner.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs).
