### ISSUE TITLE
Items not being picked up

### ISSUE THREAD

**Issue by otter360** [ORelio/Minecraft-Console-Client#1089]
Apologies in advance if this is my fault, I am very new to coding let alone GitHub so this may be an issue on my part.

I have used this program to afk an alt on a 1.12.2 skyblock server at a farm of mine. It would sit there all day doing ''/sell all'' and reconnect to the server when it rebooted. However, the recent update of Minecraft 1.16 has caused it to not work as expected. My alt now would log onto the server and afk the farm. The issue is that the items produced by my farm don't go into my alts inventory to be sold (my alts inventory is empty). Instead they sit at my alts feet and cause mass server lag until they are clagged. When I visit the island where my alt is the items get sucked into my alts inventory but without me loading the island on a ''legit'' form of Minecraft the same issue keeps occurring. I had the same issue before but I fixed it by enabling ''Terrain movements'', it is still enabled but it does not fix my issue.

Could someone please help me out by either helping me with my coding to fix this issue or giving me some advice? I am unsure how to download the latest version of this program so that may be the problem aswell.

Many thanks,
otter360

**Comment by OverHash** [comment]
You can download the latest version from the development builds located on the README.md of the repository

**Comment by otter360** [comment]
Thank you for this, I have downloaded it. Unfortunately, I am still having the same issue with my alt not picking up the items

**Comment by ningkaiyang** [comment]
maybe make a hopper system... idk how its fixed

**Comment by otter360** [comment]
I could do that but its not ideal as there is a /sell all cooldown (30s) so it would take a while to sell it all. I may do this if there is no fix for my issue

**Comment by ORelio** [comment]
Terrain and movements need to work in order to pick up items. Make sure it is enabled and check your coordinates with `/move get`

**Comment by otter360** [comment]
Terrain and movements are enabled but my alt is still unable to pick up items

**Comment by otter360** [comment]
Had to rewrite a few parts of my script but it now works! :D
Thanks all of you for your help, support and patience
