### ISSUE TITLE
1.16(.1) support

### ISSUE THREAD

**Issue by Bas950** [ORelio/Minecraft-Console-Client#1090]
Minecraft 1.16 implementation status:

☑️ Basic Chat Support
☑️ Terrain Handling
☑️ Inventories
☑️ Entities

**Comment by ORelio** [comment]
OK so basic chat is now handled thanks to your pull request 👍
Updated your post with check list of features that still need work for 1.16 support.

**Comment by ORelio** [comment]
Entity handling for 1.16 done in #1149

**Comment by ORelio** [comment]
Mojang released 1.16.2 a few days ago. Need to update protocol support for 1.16.2 also.

**Comment by ORelio** [comment]
1.16.2 and inventory support done in #1214 - Only Terrain is missing for full 1.16 support.

**Comment by JackTYM** [comment]
Any updates on ETA of Terrain and Movements?

**Comment by ReinforceZwei** [comment]
I am working on it and I have a good news. I am able to move around correctly on 1.16+
But there is an issue that processing chunk data took too much time and causing the server to kick me for timeout. (some server did kick me, but some didn't)

It would be great if someone could have a look of my code and maybe improve it for me. Here is the commit that contain the code [b1beafd](https://github.com/ReinforceZwei/Minecraft-Console-Client/commit/b1beafd5462f95e299d59dcefeec618b26e176eb)

**Comment by ReinforceZwei** [comment]
Update:
Seems like the issue is not related to chunk reading but reading an array of VarInt. In 1.16.2+, the biomes field in `ChunkData` packet changed from Int to VarInt array. Therefore the time costed is 10-12 times longer than before. But since the data length is variable, I can't "skip" it by reading a fixed amount of data. @ORelio any help would be appreciated :pray:

**Comment by ORelio** [comment]
Thanks @ReinforceZwei for working on this I'll review your PR straight away 👍

**Comment by ORelio** [comment]
Terrain support has been added, so now MCC fully supports Minecraft 1.16 🎉
