### ISSUE TITLE
Kickmessages.txt not found

### ISSUE THREAD

**Issue by Whereismycantaloupe** [ORelio/Minecraft-Console-Client#1094]
https://imgur.com/a/3WOF1xA

When I run the console client it says that the kick messages file cannot be found despite it being in my console client folder. Are there any solutions to this?

**Comment by CrewParzi** [comment]
Make sure its in the folder and named "kickmessages.txt". Make sure there IS ".txt" at the end of the file name.

**Comment by Whereismycantaloupe** [comment]
There is a .txt at the end and it is for sure in the folder, so I am confused

**Comment by ORelio** [comment]
I think your forgot the leading `C:` in your path so it should begin with `C:\Users` not `\Users`.
Unless of course your are running Mac or Linux.

**Comment by Whereismycantaloupe** [comment]
I run Mac, so maybe it is just not possible for me to have auto relog

**Comment by ORelio** [comment]
It's completely possible to have auto relog on Mac, but maybe you are invoking MCC from a different folder.
Try the following:
 - Open a terminal in the folder containing Minecraft Console Client
 - Invoke it using `mono MinecraftClient.exe`

If the kick messages are still not found, make sure the setting is simply `kickmessagesfile=kickmessages.txt` and the file is located in the same folder containing MinecraftClient.exe

**Comment by Whereismycantaloupe** [comment]
Here are screenshots of what I have: https://imgur.com/a/aleQ7i4

I believe that everything is in place and is enabled

**Comment by ORelio** [comment]
Yes, everything looks great. However, your file is inside the "Console Client" folder while your screenshot https://imgur.com/a/3WOF1xA shows MCC is trying to load it from your home directory. So maybe you did not invoke MCC from inside the "Console Client" directory and its "working directory" is set to your home directory.

**Comment by Whereismycantaloupe** [comment]
That was spot on--I have my folder on my desktop so when I opened terminal I first typed "cd Desktop" which made the terminal run from that directory. It's still not as smooth as running directly from PC, but it works!

**Comment by ORelio** [comment]
For troubleshooting, you may want to set `debugmessages=true` in your configuration file, some debug lines might help you to figure out what could be wrong.
