### ISSUE TITLE
AutoAttack

### ISSUE THREAD

**Issue by adrielalfeus03** [ORelio/Minecraft-Console-Client#1096]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

Is There A way to add some cooldown in autoattack ?
because in 1.9+ combat , attacking have cooldown like 1-2seconds
and to make entity search faster ?
because if i used like 10 mob spawners+ the bot cant keep it up and it even cant hit the mob

Sorry i dont know  wheres to put this issue , so i just put it in general question

**Comment by ReinforceZwei** [comment]
The 1.9+ combat cooldown is implemented. It will calculate and adjust the attack speed base on what weapon is being held.

**Comment by adrielalfeus03** [comment]
is it already implemented in new build ? , because when i try it in new build its still not working

**Comment by ReinforceZwei** [comment]
Could you give more explanation? Like what did the bot do, which part is not working?

**Comment by adrielalfeus03** [comment]
when there is a lot of mobs , like 20+ mobs in 1 block wide , the auto attack is not attacking the mob, i dont know whether its because anticheat on server or console client .

(the bot get kicked because sending too many packets)

**Comment by ReinforceZwei** [comment]
Everything works fine on my own testing environment. 20+ mobs in 1 block, able to attack and kill every mobs. Maybe the issue is the anti-cheat plugin as you mentioned.

**Comment by ReinforceZwei** [comment]
May I know what is the mob you want to attack? Is it spider?

**Comment by adrielalfeus03** [comment]
i use like 10 blaze spawners in server

**Comment by milutinke** [comment]
@ORelio How I can generate Entity Pallete for 1.16.1?
Auto Attack currently does not work because of that.

**Comment by ORelio** [comment]
@milutinke See instructions in [EntityType.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/EntityType.cs#L8) and [EntityPaletteGenerator.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/EntityPalettes/EntityPaletteGenerator.cs).

Add a call to `EntityPaletteGenerator.GenerateEntityTypes()` with correct path to the json you generated from MC 1.16 using [Data_Generators](https://wiki.vg/Data_Generators) inside `Main()` in `Program.cs` and launch the project once. It should generate `EntityType.cs` and `EntityPalette.cs`.

Add missing entries in the existing `EntityType.cs` then add the new palette in [EntityPalettes](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/Mapping/EntityPalettes) and look for existing references to ` EntityPalette115.cs`. Add the appropriate case for using ` EntityPalette116.cs` for Minecraft 1.16.

Finally, make sure there are no changes to implement for Entity Handling in Minecraft 1.16. Packet changes are on [Pre-Release Protocol](https://wiki.vg/index.php?title=Pre-release_protocol&oldid=15881) in the wiki.
