### ISSUE TITLE
inventoryhandling won't enable

### ISSUE THREAD

**Issue by aldermath** [ORelio/Minecraft-Console-Client#1099]
I have "inventoryhandling=true" in the config file but if I use something like /useitem it returns "Please enable inventoryhandling in config to use this command."

Not sure why it thinks the setting is disabled.

**Comment by aldermath** [comment]
This also happens for terrainandmovements. Are these settings not implemented yet?

**Comment by ReinforceZwei** [comment]
Which Minecraft version are you using?

**Comment by aldermath** [comment]
1.16.1

**Comment by Nekiplay** [comment]
last support version 1.15.2

**Comment by ReinforceZwei** [comment]
Currently only the chat is supported on 1.16+

**Comment by aldermath** [comment]
Ok, I'll keep an eye on the progress. Thanks
