### ISSUE TITLE
Project file does not exist - Linux

### ISSUE THREAD

**Issue by OnAQuest** [ORelio/Minecraft-Console-Client#1100]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

![image](https://user-images.githubusercontent.com/60120362/86316043-6b4de180-bbf1-11ea-8151-cecb9936fc41.png)

I installed Mono on this server, however, it doesn't let me install the project. Could I be doing something wrong here? Thanks.

**Comment by konata2027** [comment]
Are you trying to compile the project? Because you don't have to do that, you can just download development build
https://github.com/ORelio/Minecraft-Console-Client#download

But if you really need to compile it yourself, than first cd into Minecraft-Console-Client/MinecraftClient
