### ISSUE TITLE
Client exits when connected to server while using NodeJS ChildProcess

### ISSUE THREAD

**Issue by testing-js** [ORelio/Minecraft-Console-Client#1103]
When I run the below script in NodeJS, the client successfully starts, but as soon as it successfully connects to the server, the process closes:
```
const cp = require("child_process");

const minecraftClient = cp.spawn("MinecraftClient.exe");
let clientOn = true;

process.stdin.on("data", (data) => {
  if (serverOn) minecraftClient.stdin.write(data);
  else {
    console.log("client is now off. Restart this file to restart client");
  }
});
minecraftClient.stdout.on("data", (data) => {
  console.log(data.toString());
});

minecraftClient.on("close", (code, signal) => {
  console.log("Client closed");
  clientOn = false;
});

```
How do I keep the client open so I can provide input into it from NodeJS?

When I do not provide a config file and manually enter the e-mail from the NodeJS stdin, the client also immediately exits.

**Comment by ORelio** [comment]
You need `BasicIO` for non-interactive mode.
```
cp.spawn("MinecraftClient.exe BasicIO");
```
should do.

**Comment by testing-js** [comment]
Thanks a lot for the help, changing that line to add the extra parameter worked:
```
cp.spawn("MinecraftClient.exe", ["BasicIO"]);
```
Now the process waits for further input instead of immediately closing.

Although, now all the color codes sent in chat are also included in the console output. Should I handle this myself, or is there an in-built solution to filter out the color codes?

Changing the config file line below under MCSettings doesn't work either:
```
chatcolors=false                    # Allows disabling chat colors server-side
```

**Comment by ORelio** [comment]
BasicIO-NoColor

**Comment by testing-js** [comment]
Thanks again!
Is there a place I can find the documentation of all command-line options like these? I was not able to locate them in the README files of the repository and the config folder.
