### ISSUE TITLE
Negative byte

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1104]
![image](https://user-images.githubusercontent.com/39955851/86514178-02f63e80-be43-11ea-8eb9-1456282304ea.png)
See [Set Slot](https://wiki.vg/Protocol#Set_Slot), `To set the cursor (the item currently dragged with the mouse), use -1 as Window ID and as Slot.`
The 255 should be -1 instead.

I wrote a SByte method but it gave me a `System.OverflowException` error.
![image](https://user-images.githubusercontent.com/39955851/86514434-ae53c300-be44-11ea-9c4b-302879fd4903.png)

I don't know how to fix it :cry:

Edit:
Also, when I try to compare that byte with 255, I think the thread just hanged without any message. I cannot continue my work on testing clicking item in inventory before this issue was solved :C
![image](https://user-images.githubusercontent.com/39955851/86514896-e4467680-be47-11ea-8f24-21bd555bd036.png)

**Comment by ORelio** [comment]
If slot IDs are signed, the data type read from packets should be changed to `sbyte` instead of `byte`.

**Comment by ReinforceZwei** [comment]
I figured out the thread hanged up problem, it's my careless mistake. 

Look like the negative inventoryId/windowId only appear in SetSlot packet, so maybe we just leave the byte there, and check for Id 255 and put it back to inventory 0.
