### ISSUE TITLE
how do I make a minecraft console client do these things

### ISSUE THREAD

**Issue by duhitzmedamo** [ORelio/Minecraft-Console-Client#1105]
I just want to know how to make a minecraft console client 1. react to a message and 2. do an action. I want the console to see a message and turn its head. I also want it to accept ONLY my tpa requests. please can someone help!!

**Comment by Daenges** [comment]
It depends. The easiest would be to setup a "matches.txt" where you specify, what the bot does, if it gets a certain message and then use the "/turn" command. (search on yt for some examples on how to set it up.)
For the tpa you could use the "remotecontrol" section in the minecraft.client.ini.
If you are able to make a c# script it would be a bit easier.

**Comment by adrielalfeus03** [comment]
you can use auto respond feature in cclient, it would do all of that things
