### ISSUE TITLE
Automating the scripts on Raspbian 

### ISSUE THREAD

**Issue by periskil** [ORelio/Minecraft-Console-Client#1109]
So i am currently messing around with running the console client on a 4gb raspberry pi 4 (rpi 4). I run it fine through mono but have trouble getting the scripts to automate. Ex: AutoRelog, AntiAfk, and ScriptScheduler. My resolve for antiafk and script scheduler is to just make the string of code last 25 hours (desperate i know). But as of now I dont know what to do about the AutoRelog.

Any suggestions? none of the scripts run on start up, I have to manually start it through the client
/script Desktop/(user)/(text file name)

Any help is appreciated :)

**Comment by periskil** [comment]
idk what info i need to provide that would help. so just lmk if i can add any additional info for you
ty <3

**Comment by adrielalfeus03** [comment]
i never use raspberry pi before , but if its same like console client in windows , there is autorelog feature in it. just enabled it  and put text that make you kicked out from server to  kickmessages.txt . and done

for script scheduler u can do loop with it , just use

 timeinterval=30

30 means 30 seconds

**Comment by periskil** [comment]
Im saying my issue is the fact that the scripts don't start even when enabled. and when i force start them they dont keep happening. I use this in windows fine. I just want to use it on a pi so I can turn my pc off. But my issue rn is that i cant get any of the auto programs to work even when enabled. It just doesn't start them

**Comment by ORelio** [comment]
See #1094, you need to invoke MCC from the correct directory or it will not look for the config file you modified.

**Comment by periskil** [comment]
I tried this and it seems to get everything to work except ScriptScheduluer. (i invoke it from the file)

After Turning on debugmessages i went to see if it was loading the file in the first place and it came up with the following 

"[ScriptScheduler] Loading tasks from '/home/pi/Desktop/MinecraftClient/mainscript.txt' 
Translations file loaded." However, not of the commands from my mainscript.txt file are executed. here is the layout of the file

wait 50
send /server lavaplanet
wait 60
send /home afk

The client doesn't send these but it seems like it is reading the file. Sorry for the lengthy post and thank you for the replies
