### ISSUE TITLE
Auto Drop item

### ISSUE THREAD

**Issue by adrielalfeus03** [ORelio/Minecraft-Console-Client#1110]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

I know inventory feature already exists, but in order to auto drop i still need to do the script that drop all my items from inventory (kinda suck )

so what do i want is , i wanna do auto drop items that instantly drop unnecessary items such as stone,wood or cobblestone

Is there a way to do it?

**Comment by Nekiplay** [comment]
it’s not difficult to do

**Comment by adrielalfeus03** [comment]
it's difficult for me , since i don't know anything about c # :(

**Comment by ReinforceZwei** [comment]
Yes, this is on my todo list. I will try to implement it after or during the implementation of AutoCraft.

**Comment by ReinforceZwei** [comment]
I am sorry it's a bit late, but auto-drop is finished.
