### ISSUE TITLE
How to use BlockPaletteGenerator.cs?

### ISSUE THREAD

**Issue by konata2027** [ORelio/Minecraft-Console-Client#1111]
Material.cs says you should generate temporary MaterialXXX.cs and PaletteXXX.cs using BlockPaletteGenerator.cs, but my brian is to smol to understand how to use it and I have zero experience in C#. Also I'm on Arch Linux, if that matter.

Could you give some instructions on how to generate block palette?

**Comment by ORelio** [comment]
Here you are: 5eea7441b7d9d17d70aef714ea50c942207238d1 😉

**Comment by konata2027** [comment]
tnx, that helped. Also I'm still to stupid to implement terrain'n'movement support.
