### ISSUE TITLE
Return exit codes on login failure, server disconnect

### ISSUE THREAD

**Issue by grantemsley** [ORelio/Minecraft-Console-Client#1116]
Is there any way I can tell what caused a failure from my batch file?  Many programs set the exit code/errorlevel differently depending on why they exited, but MCC doesn't seem to.

I have exitonfailure turned on, and a batch file that restarts the console client when it exits. Now I'm trying to find a way to differentiate between login failures and server problems, so I can have my console client stop trying on login failures, but get restarted for everything else.  That would help avoid getting your IP blacklisted from trying bad passwords too many times.

Any suggestions on how I could do that?

**Comment by CrewParzi** [comment]
Just use auto relog and in kickmessages.txt add all the possible errors the server you play on can give.

**Comment by ORelio** [comment]
Currently, I think there are no return codes. Indeed, you may use AutoRelog without using the "login failed" message although that may not fully fit your needs. Adding this to the TODO list.
