### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by Awpocalypse** [ORelio/Minecraft-Console-Client#112]
Do you have a release where the player can pick up entities?

**Comment by ORelio** [comment]
Use latest dev build with terrain ans mouvements enabled for item pickup to work properly ;)

Le 21 févr. 2016 01:36, Awpocalypse <notifications@github.com> a écrit :
Do you have a release where the player can pick up entities?

---
Reply to this email directly or view it on GitHub:
https://github.com/ORelio/Minecraft-Console-Client/issues/112

**Comment by Awpocalypse** [comment]
I could not find that option anywhere in the 1.8.2 build and i checked minecraft.ini multiple times

**Comment by Awpocalypse** [comment]
Its the one downloaded off your forums on minecraft site

**Comment by Awpocalypse** [comment]
I found it nvm
