### ISSUE TITLE
System.IO.InvalidDataException: Failed to process incoming packet of type SetExperience.

### ISSUE THREAD

**Issue by rUsTyBlOcKs** [ORelio/Minecraft-Console-Client#1122]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
-Crashes on successful connection to server.
-Tried connecting to a crack(offline mode) spigot(paper)1.14.4 server with default config.
Console:
[Console.txt](https://github.com/ORelio/Minecraft-Console-Client/files/4904064/Console.txt)

**Comment by CrewParzi** [comment]
I tried to log in to the server and found no problem.

**Comment by ORelio** [comment]
@Nekiplay Seems like there is an issue in 1.14.4 with SetExperience from #1027. Maybe you could have a look? 🙂

**Comment by rUsTyBlOcKs** [comment]
> I tried to log in to the server and found no problem.

@CrewParzi would you care to elaborate the configuration used?

**Comment by CrewParzi** [comment]
Latest build with default settings.
Just logged it normally and didn't get kicked.

**Comment by rUsTyBlOcKs** [comment]
> Latest build with default settings.
> Just logged it normally and didn't get kicked.

@CrewParzi did you use offline method (password:-) or was it with mojang authentication?

**Comment by CrewParzi** [comment]
Offline method.

**Comment by rUsTyBlOcKs** [comment]
@CrewParzi then it seems there must be something wrong in the configuration files I'm using. If possible, could you please attach the configuration used?

**Comment by Nekiplay** [comment]
I found only EntityEquipment error in 1.14.4

**Comment by CrewParzi** [comment]
@rUsTyBlOcKs just delete you old configs file. The MCC will create a new default one, that should work.

**Comment by rUsTyBlOcKs** [comment]
> @rUsTyBlOcKs just delete you old configs file. The MCC will create a new default one, that should work.

@CrewParzi  It's still showing the same error for me, even with the default config.

**Comment by CrewParzi** [comment]
Try making a new folder and download the latest build from https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts and try doing it again.

**Comment by rUsTyBlOcKs** [comment]
> Try making a new folder and download the latest build from https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts and try doing it again.

Yes, I've already done that too, but it's still showing the same error
[New Text Document.txt](https://github.com/ORelio/Minecraft-Console-Client/files/4913451/New.Text.Document.txt)

**Comment by CrewParzi** [comment]
Try this please.
[MCC.zip](https://github.com/ORelio/Minecraft-Console-Client/files/4913568/MCC.zip)

**Comment by ReinforceZwei** [comment]
I had the same issue after logging into the server `communityrealm.my.pebble.host` that I found inside @rUsTyBlOcKs 's [log file](https://github.com/ORelio/Minecraft-Console-Client/files/4913451/New.Text.Document.txt). 

The client crashes after received and processed the first 4 bytes of the following packet data `EE 0F 02 03 FD 8D FD BE`, and seems like the data is different every time. Before the crashes, the server also sent several of this packet to us.

Either this is server side issue (sending incorrect packet) or client side issue (cannot handle the packet correctly). Or both (server sending incorrect packet and we cannot handle them correctly). Changing the config file around probably will not fix this issue.

**Comment by CrewParzi** [comment]
Well its not a error in a bit older version.
I used MCC where 1.16 support was not added and it works all fine.

**Comment by ORelio** [comment]
There is a fix by @Nekiplay from #1129 in the latest development build, this should resolve your issue. Please try it out.

**Comment by rUsTyBlOcKs** [comment]
> Try this please.
> [MCC.zip](https://github.com/ORelio/Minecraft-Console-Client/files/4913568/MCC.zip)

This one works. Thanks very much, @CrewParzi.

**Comment by rUsTyBlOcKs** [comment]
> There is a fix by @Nekiplay from #1129 in the latest development build, this should resolve your issue. Please try it out.

The new development build also shows the same error. I used @CrewParzi's link and it works perfectly fine now. Thanks for helping.

**Comment by Nekiplay** [comment]
> > There is a fix by @Nekiplay from [#1129 ](https://github.com/ORelio/Minecraft-Console-Client/pull/1129) in the latest development build, this should resolve your issue. Please try it out.
> 
> The new development build also shows the same error. I used @CrewParzi's link and it works perfectly fine now. Thanks for helping.

I did not find any errors
