### ISSUE TITLE
I need some help.

### ISSUE THREAD

**Issue by AddictedCrew** [ORelio/Minecraft-Console-Client#1123]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

So hi. I tried to do this:

```
wait 10
send /login password
wait 10
/useitem
```

But dosent work. Because after login command /send doesn't work anymore.. And if use /useitem or any command from  mainscript.txt doesn't work and I need to write in terminal. Can someone tell me how i can use commands from bot without send and not need to write in Terminal ? Thank you

**Comment by CrewParzi** [comment]
For useitem, do just useitem instead of /useitem.

**Comment by AddictedCrew** [comment]
Doesn't work on mainscript.txt.

**Comment by CrewParzi** [comment]
Could you post Minecraft.ini? Remove any username and password.

**Comment by AddictedCrew** [comment]
# Minecraft Console Client v1.12.1 DEV
# Startup Config File

[Main]

# General settings
# Leave blank to prompt user on startup
# Use "-" as password for offline mode

login=xRamy
password=
serverip=play.fith.net

# Advanced settings

language=en_GB
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash              # Use 'none', 'slash' or 'backslash'
splitmessagedelay=2                # Seconds between each part of a long message
botowners=Amidone  # Use name list or myfile.txt with one name per line
botmessagedelay=2                  # Seconds to delay between message a bot makes to avoid accidental spam
mcversion=1.15.2                     # Use 'auto' or '1.X.X' values
brandinfo=mcc                      # Use 'mcc','vanilla', or 'none'
chatbotlogfile=                    # Leave empty for no logfile
privatemsgscmdname=tell            # Used by RemoteControl bot
showsystemmessages=true            # System messages for server ops
showxpbarmessages=true             # Messages displayed above xp bar
showchatlinks=true                 # Show links embedded in chat messages
terrainandmovements=true          # Uses more ram, cpu, bandwidth
sessioncache=memory                # Use 'none', 'memory' or 'disk' (disk session storing is experimental)
resolvesrvrecords=false             # Use 'false', 'fast' (5s timeout), or 'true'. Required for joining some servers.
accountlist=accounts.txt           # See README > 'Servers and Accounts file' for more info about this file
serverlist=servers.txt             # See README > 'Servers and Accounts file' for more info about this file
playerheadicon=true                # Only works on Windows XP-8 or Windows 10 with old console
exitonfailure=false                # Disable pauses on error, for using MCC in non-interactive scripts
debugmessages=false                # Please enable this before submitting bug reports. Thanks!
scriptcache=true                   # Cache compiled scripts for faster load on low-end devices
timestamps=false  
inventoryhandling=true                 # Prepend timestamps to chat messages

[AppVars]
# yourvar=yourvalue
# can be used in some other fields as %yourvar%
# %username% and %serverip% are reserved variables.

[Proxy]
enabled=false                      # Use 'false', 'true', or 'login' for login only
type=HTTP                          # Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=0.0.0.0:0000                # Proxy server must allow HTTPS for login, and non-443 ports for playing
username=                          # Only required for password-protected proxies
password=                          # Only required for password-protected proxies

[ChatFormat]
# Do not forget to uncomment (remove '#') these settings if modifying them
builtins=true                      # MCC built-in support for common message formats
# public=^<([a-zA-Z0-9_]+)> (.+)$
# private=^([a-zA-Z0-9_]+) whispers to you: (.+)$
# tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

[MCSettings]
enabled=true                       # If disabled, settings below are not sent to the server
locale=en_US                       # Use any language implemented in Minecraft
renderdistance=medium              # Use tiny, short, medium, far, or chunk amount [0 - 255]
difficulty=normal                  # MC 1.7- difficulty. peaceful, easy, normal, difficult
chatmode=enabled                   # Use 'enabled', 'commands', or 'disabled'. Allows to mute yourself...
chatcolors=true                    # Allows disabling chat colors server-side
main_hand=left                     # MC 1.9+ main hand. left or right
skin_cape=true
skin_hat=true
skin_jacket=false
skin_sleeve_left=false
skin_sleeve_right=false
skin_pants_left=false
skin_pants_right=false
# Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=false
delay=-
command=0

[AutoRelog]
enabled=true
delay=10
retries=3 #-1 = unlimited
kickmessagesfile=kickmessages.txt

[ChatLog]
enabled=false
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=false
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=true
tasksfile=mainscript.ini

[RemoteControl]
enabled=false
autotpaccept=false
tpaccepteveryone=false

[AutoRespond]
enabled=false
matchesfile=matches.ini

**Comment by CrewParzi** [comment]
Download the latest build.
In script scheduler, change tasksfile=mainscript.txt
and in mainscript.txt enter this:
wait 10
send /login password
wait 10
useitem

**Comment by AddictedCrew** [comment]
> Download the latest build.
> In the folder, change mainscript.txt to mainscript.ini
> and in mainscript.ini enter this:
> [Task]
> triggerOnFirstLogin=true
> triggerOnLogin=true
> triggerOnInterval=false
> timeInterval=900
> script=check.txt
> 
> Now create a text file called check.txt in the same folder.
> Enter the following in check.txt and save:
> wait 10
> send /login password
> wait 10
> useitem
> 
> This should hopefully work.

Thank you, work perfectly. Thank you so much.
