### ISSUE TITLE
Freezing at "logging in..." / Disk session cache bug

### ISSUE THREAD

**Issue by grantemsley** [ORelio/Minecraft-Console-Client#1124]
I find my console client often freezing at the "Logging in..." step right before "Checking session".
While it's stuck there, it's using 100% CPU and causes any other running clients to freeze up.

If I delete the session cache file, it starts working again.

Any idea how to diagnose/fix that?

**Comment by CrewParzi** [comment]
Having the same problem but it happens when the server kicks you for restart(using Linux VPS).

**Comment by ORelio** [comment]
Seems e bug with the disk synchronization feature allowing multiple MCC instances to share the same session cache.
I'll try to reproduce. Meanwhile, you should be able to circumvent this with `sessioncache=memory`. Please note that in Memory mode, relaunching the client will perform logins from scratch, but logins are rate limited by Mojang.

**Comment by ORelio** [comment]
One more question : What operating system? Using .NET Framework or Mono?

**Comment by grantemsley** [comment]
Windows 10/Server 2016/2019. 
.NET Framework 4.7.2.

I want to avoid using memory mode for the reason you mentioned.  I do have a lot of clients sharing one session cache, so that explanation makes sense.

**Comment by CrewParzi** [comment]
I use Mono and I do also have quite some clients running.

**Comment by ORelio** [comment]
Unfortunately we could not reproduce this issue.
