### ISSUE TITLE
How can I disable kickmessages.txt?

### ISSUE THREAD

**Issue by DasherPack** [ORelio/Minecraft-Console-Client#1125]
I am in a SMP server and want to stay AFK. Is there a way to tell Console Client: "Ignore the kick message, just reconnect in 10 seconds"
Thank you

**Comment by CrewParzi** [comment]
Yes, there is a way.
Open MinecraftClient.ini and under auto relog enter this:
[AutoRelog]
enabled=true
delay=10
retries=-1 #-1 = unlimited
ignorekickmessage=true
kickmessagesfile=kickmessages.txt

**Comment by DasherPack** [comment]
THX
