### ISSUE TITLE
Remote Control stopped working...

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [ORelio/Minecraft-Console-Client#113]
Most of you know that I have been running a custom flavor of MCC for quite some time, returning only to grab the latest updates when needed.

I have moved from one server to another as my main and suddenly my client's remote control stopped working.

Considering I own the server I changed several chat message formats and no formats worked.
This includes the following,
[me -> player] message
[me @ player] message
in various colors.  No matter what I do it doesn't work.  This server has one thing that I know is different and that is the fact it's 1.7/1.8 compatible. My client is set for 1.8.0.  None of my custom features should affect this operation and I can't figure it out. 
Currently installing visual studio to double check my source code.

server ip: pvp.deagonner.com  
current message format: [me @ player] message

Any help is appreciated.

**Comment by ZizzyDizzyMC** [comment]
I fixed this, simply was a very tragic mistake of capitalizing the 'm' in [me @ player]... Sorry lol. There is another issue though I'll post that in a new issue tag.

**Comment by ORelio** [comment]
You can use whatever regex you want in app config using the latest dev build ;)
There is also support for C# scripts.
