### ISSUE TITLE
Username-Variable in C#-Script

### ISSUE THREAD

**Issue by TheRedVillager** [ORelio/Minecraft-Console-Client#1130]
Am I doing something wrong?
It doesn't send the username, instead it sends "%match_u%"

```
//MCCScript 1.0

string[] commands = new[] {
    "send /bc &c[RedBot] &eHallo %match_u%",
    "send /bc &c[RedBot] &eHey %match_u%",
    "send /bc &c[RedBot] &eHi %match_u%",
    "send /bc &c[RedBot] &eGuten Tag, %match_u%",
    "send /bc &c[RedBot] &eMoin %match_u%",
    "send /bc &c[RedBot] &eServus %match_u%",
    "send /bc &c[RedBot] &eIch begrüße dich, %match_u%",
    "send /bc &c[RedBot] &eSalut %match_u%"
    

};

int randomIndex = new Random().Next(0, commands.Length);
string randomCommand = commands[randomIndex];
MCC.PerformInternalCommand(randomCommand);
```

**Comment by konata2027** [comment]
I guess, %match_u% is variable for internal scripts. For C# script you should use something like MCC.GetUsername().
Not sure if I'm right or wrong.

**Comment by TheRedVillager** [comment]
How do i do that?

**Comment by Nekiplay** [comment]
string[] commands = new[] {
    "send /bc &c[RedBot] &eHallo " + MCC.GetUsername(),
    "send /bc &c[RedBot] &eHey " + MCC.GetUsername(),
    "send /bc &c[RedBot] &eHi " + MCC.GetUsername(),
    "send /bc &c[RedBot] &eGuten Tag, " + MCC.GetUsername(),
    "send /bc &c[RedBot] &eMoin " + MCC.GetUsername(),
    "send /bc &c[RedBot] &eServus " + MCC.GetUsername(),
    "send /bc &c[RedBot] &eIch begrüße dich, " + MCC.GetUsername(),
    "send /bc &c[RedBot] &eSalut " + MCC.GetUsername()
};

**Comment by TheRedVillager** [comment]
[MCC] [AutoRespond] script hi.cs
[MCC] [Script] Script 'hi.cs' failed to run (LoadError).
[MCC] [Script] System.InvalidOperationException: Der Zugriff auf 'MinecraftClient.ChatBot.GetUsername()' ist aufgrund der Sicherheitsebene nicht möglich.

Translation: 
Access to 'MinecraftClient.ChatBot.GetUsername ()' is not possible due to the security level

**Comment by ORelio** [comment]
`MCC.GetVar("match_u")`
Of course this will only work when called from AutoRespond.

**Comment by Nekiplay** [comment]
> [MCC] [AutoRespond] script hi.cs
> [MCC] [Script] Script 'hi.cs' failed to run (LoadError).
> [MCC] [Script] System.InvalidOperationException: Der Zugriff auf 'MinecraftClient.ChatBot.GetUsername()' ist aufgrund der Sicherheitsebene nicht möglich.
> 
> Translation:
> Access to 'MinecraftClient.ChatBot.GetUsername ()' is not possible due to the security level

string[] commands = new[] {
"send /bc &c[RedBot] &eHallo " + GetUsername(),
"send /bc &c[RedBot] &eHey " + GetUsername(),
"send /bc &c[RedBot] &eHi " +GetUsername(),
"send /bc &c[RedBot] &eGuten Tag, " + GetUsername(),
"send /bc &c[RedBot] &eMoin " + GetUsername(),
"send /bc &c[RedBot] &eServus " + GetUsername(),
"send /bc &c[RedBot] &eIch begrüße dich, " +GetUsername(),
"send /bc &c[RedBot] &eSalut " +GetUsername()
};
