### ISSUE TITLE
Asking for help with auto-restarting/rejoining +crontab inefficiency

### ISSUE THREAD

**Issue by mijiperki** [ORelio/Minecraft-Console-Client#1131]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

I am using the latest dev build on linux (ubuntu 16)

When I launch MinecraftClient.exe in terminal it all loads up fine using around 2%-5% CPU and works as it should for a few hours until it will suddenly just return me back to a plain terminal (it crashes).

This itself is not really the issue but it also kind of is, stick with me xd.

I have tried to make a solution to this by restarting the application with crontab every hour so that if it does crash, it will be backup within 60 minutes. The reason I am doing this and not relying on the built-in auto reconnect is that the auto reconnect doesnt reconnect me after silent disconnects or server restarts and I have tried a shit ton of different configs and setups with kickmessages.txt and matches over several months to try to solve this but it just wont 100% reliably rejoin.

So my main question is, when I run MinecraftClient.exe with crontab, it uses A LOT more CPU, like 25%-100% CPU allllllll the time, not just starting up, its also stuck running in the background and I cant view the terminal which is really annoying and has stopped me being able to find a solution as I dont know what the problem is. 

So to conclude, is this normal? Is it due to the version of mono I am using because I also cant find out how to downgrade to 4.0-4.2 like you recommend. Is there a better alternative to crontab to reliably restart MCC when it crashes or hourly. Was this a really shit explanation of nothing you can understand because idk what im talking about? lemme know xd

**Comment by CrewParzi** [comment]
Ok. 
So, first of all no need to use crontab if cpu usage is an issue, and about silent disconnects, you can setup a anti afk command which executes every 5 min or so. This way when 2 commands are executed MCC realizes that it has been disconnected and it can reconnects. 
Also, add "Connection has been lost." to the kickmessages.txt

I also use linux and faced this problem and the above method worked for me.

**Comment by mijiperki** [comment]
Thanks for responding! I will add that to my kickmessages.txt and see how it performs. When you say "you can setup a anti afk command which executes every 5 min or so." do you mean the inbuild [AntiAFK] module, if so I have that running "/sell all" every 30 seconds, is that okay (will it trigger the disconnection detection)?

**Comment by CrewParzi** [comment]
Yeah that should work. Any command will work. If its still doesn't work try increasing the time to 1 min.

**Comment by mijiperki** [comment]
At my current 30 seconds it gets hung like this: 
https://gyazo.com/bd71c31344c0ce7fed66cac1e4ffc8bd

It only restarts once per day so I can only test once a day so might have to setup a server to test on

**Comment by CrewParzi** [comment]
Do you have auto reconnect turned on?

**Comment by ORelio** [comment]
If running non-interactively use `BasicIO-NoColor` to disable the rich terminal prompt. See #1121

**Comment by mijiperki** [comment]
> Do you have auto reconnect turned on?
When the above screenshot happened my MinecraftClient.ini contained:

[AntiAFK]
enabled=true
delay=310 #10 = 1s
command=/sell all

[AutoRelog]
enabled=true
delay=5
retries=-1 #-1 = unlimited
ignorekickmessage=false
kickmessagesfile=kickmessages.txt

That obviously didnt work so I've changed it to this and will see what happens after todays restart. (im using matches.txt to auto sell now as that wont trigger if I've been disconnected so it will only send a command every 2.5 mins after im disconnected)

[AntiAFK]
enabled=true
delay=1500 #10 = 1s
command=/near

[AutoRelog]
enabled=true
delay=10
retries=-1 #-1 = unlimited
ignorekickmessage=false
kickmessagesfile=kickmessages.txt

**Comment by Govindass** [comment]
crontab is overkill for this, here's how I do it so it auto-restarts, it's all in the .sh script:
```
while true; do
	sleep 5
	mono MinecraftClient.exe BasicIO-NoColor
done;
```

this will make it take 5 seconds at most to restart
