### ISSUE TITLE
I want to know how I can run "wait" on C # script

### ISSUE THREAD

**Issue by heruizhe-bey** [ORelio/Minecraft-Console-Client#1133]
Hello, I want to know how I can run "wait" on C # script

**Comment by CrewParzi** [comment]
I don't really know c# but I think there is a function for it. Try WaitForSeconds(time).

**Comment by ReinforceZwei** [comment]
@CrewParzi There are no such method. According to [this script example](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.cs), you may use `Thread.Sleep(time)`.

**Comment by heruizhe-bey** [comment]
> @CrewParzi没有这种方法。根据[此脚本示例](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.cs)，您可以使用`Thread.Sleep(time)`。

Thank you very much
