### ISSUE TITLE
support authlib-injector

### ISSUE THREAD

**Issue by jinzhijie** [ORelio/Minecraft-Console-Client#1136]
Nowadays, lots of servers use authlib-injector and custom Yggdrasil API. But MCCC doesn't support this. So I can't use MCCC to contorl my server. :sob: 

[yushijinhun/authlib-injector](https://github.com/yushijinhun/authlib-injector)

Please support this, **THANKS!**

> English is not my first language, sorry

**Comment by ORelio** [comment]
Hi. Minecraft Console Client is written in C# while the project you are linking to is written in Java. However, you might be able to use MCC with your custom authentication server by replacing occurences of `authserver.mojang.com` inside [ProtocolHandler.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs) with your own session server. That should work as long as the session server has the same API endpoints as the official one.

**Comment by jinzhijie** [comment]
> Hi. Minecraft Console Client is written in C# while the project you are linking to is written in Java. However, you might be able to use MCC with your custom authentication server by replacing occurences of `authserver.mojang.com` inside [ProtocolHandler.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs) with your own session server. That should work as long as the session server has the same API endpoints as the official one.

That's great, it has the same API endpoints as the official one.

And, can you help me do that? **THANK YOU!** :smile:

**Comment by ORelio** [comment]
1. download the project: [Minecraft-Console-Client-master.zip](https://github.com/ORelio/Minecraft-Console-Client/archive/master.zip)
2. search and replace `authserver.mojang.com` with your `custom.authserver.com`
3. [build from source](https://github.com/ORelio/Minecraft-Console-Client#building-from-source) to produce a custom MinecraftClient.exe from your modified source code

Note: You might want to use [Visual Studio Community](https://visualstudio.microsoft.com/vs/community/) to make your job easier

**Comment by Hiasinsu** [comment]
It would be nice if someone can add an option to do this instead of recompiling. 🙂

**Comment by ReinforceZwei** [comment]
@Hiasinsu Mojang account are going to be replaced by Microsoft account soon. I don't think it is worth to add this function now.

**Comment by Hiasinsu** [comment]
> @Hiasinsu Mojang account are going to be replaced by Microsoft account soon. I don't think it is worth to add this function now.

That's OK, I understand it.
Anyway, thank all developers did this great work!
😀

**Comment by RankFrank4010** [comment]
> Hi. Minecraft Console Client is written in C# while the project you are linking to is written in Java. However, you might be able to use MCC with your custom authentication server by replacing occurences of inside [ProtocolHandler.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs) with your own session server. That should work as long as the session server has the same API endpoints as the official one.`authserver.mojang.com`

I don't think so, because authlib-injector has some new logic likes more players
