### ISSUE TITLE
MInecraft Client Proxy.

### ISSUE THREAD

**Issue by AddictedCrew** [ORelio/Minecraft-Console-Client#1137]
**Prerequisites**
 - [x ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

My question is. If I use another Proxy Minecraft Client will have another IP? Yes or Not. Thank you.

**Comment by ORelio** [comment]
Yes. It will go through the proxy.

**Comment by AddictedCrew** [comment]
Ok, thank you !
