### ISSUE TITLE
access most recent inventory id

### ISSUE THREAD

**Issue by aldermath** [ORelio/Minecraft-Console-Client#1138]
Is there a way to save the most recently created inventory id to a variable or just overwrite id 1 whenever a new inventory is opened? I have tried just counting up the inventory id when I expect it to change but this is not 100% accurate.

**Comment by aldermath** [comment]
Will ClearInventories() work to reset what id new inventories are assigned to? If so how do I callit in a script?

I tried just MCC.ClearInventories(); but it gives this:
[MCC] [Script] Script 'test.cs' failed to run (LoadError).
[MCC] [Script] System.InvalidOperationException: 'MinecraftClient.ChatBot.ClearInventories()' is inaccessible due to its protection level

**Comment by ReinforceZwei** [comment]
`ClearInventories()` only clear the client inventory cache. The inventory ID are determined base on what ID server sent to us and currently not able to change them manually.

**Comment by aldermath** [comment]
Is there a way I could track when a new inventory is created and automatically update a variable?

**Comment by aldermath** [comment]
I modified this in McClient.cs to change update a variable when an inventory is opened. It would be nice if %lastinventory% were a default variable like %login% etc. I got everything to work though.

public void OnInventoryOpen(int inventoryID, Container inventory)
        {
            inventories[inventoryID] = inventory;

            if (inventoryID != 0)
            {
		string command1 = "set lastinventory=" + inventoryID.ToString();
		string output1 = "";
                ConsoleIO.WriteLogLine("Inventory # " + inventoryID + " opened: " + inventory.Title);
                ConsoleIO.WriteLogLine("Use /inventory to interact with it.");
                DispatchBotEvent(bot => bot.OnInventoryOpen(inventoryID));
		PerformInternalCommand(command1, ref output1);
            }
        }

**Comment by ORelio** [comment]
How about `/inventory container` instead of `/inventory <id>`?
