### ISSUE TITLE
Auto tpaccept and remote control

### ISSUE THREAD

**Issue by leinadplayz** [ORelio/Minecraft-Console-Client#1139]
I need help. I have setup my auto tpaccept and it isn't working as the command needed to accept needs to be /tpaccept (username) instead of just tpaccept. If you can help me change code so it does this or any other fix that would help a lot. Also remote control access by using /msg or /tell isn't working. I made it work before I went to sleep but when I woke up it suddenly stop working. If you could help me fix it that would be great thanks

**Comment by ORelio** [comment]
You should be able to get around this by using AutoRespond instead of AutoRelog:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini
You would configure it to automatically respond with `/tpacept $u` in `actionother` instead of `/tpaccept` alone.
