### ISSUE TITLE
armhf client keepalive not working

### ISSUE THREAD

**Issue by JohnnyLin-a** [ORelio/Minecraft-Console-Client#1143]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

Full story: (Shorter version below)

I have just started to use Minecraft-Console-Client. I mainly want to use it on my SBC called OrangePi Zero.
It's basically a cheaper alternative to RaspberryPi boards.
It's running a 18.04 Ubuntu-like distro called Armbian. (arch is armhf)

So I tested it on my main Windows machine and all is fine.
I installed mono-complete just to make sure I wouldn't run into errors whatnot etc.
Now here is the issue. The console client wouldn't get any response back from the server.
However, when I send a message to the server, it does receive it successfully.
The client logs no error at all.
30~ish seconds later, the server kicks the client and disconnects it.
Occasionally, it would state that user was kicked due to keepalive timeout.
(Followed by: user lost connection: Timed out)
I believe the connection should be kept alive normally, but it is not the case for my ARM device.
The mono version installed is latest 6.10.0.104 by following their website install guide.
Debug messages from the client show no error so screenshots are useless, basically all success messages and it's also not showing that I have been disconnected until after another 30 seconds.
My server is paper 1.16.1 build-101. I removed all plugins and doesn't change anything.

Short story:
OS: Ubuntu 18.04 arch: armhf
Client connection doesn't keep alive.
Client doesn't receive server messages.
Client gets kicked for keepalive timeout, or just timed out.
Client logs no errors.
Everything is latest version as of July 20 2020.
mono version: 6.10.0.104
Game version: 1.16.1
papermc server build: 101

**Comment by ORelio** [comment]
Hi,
Silent disconnections on Mono are a recurring issue:
https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue+silent+disconnect
We never found out the cause and we suspect it is a bug in Mono itself because Microsoft .NET does not have this.

**Comment by JohnnyLin-a** [comment]
I see thanks for the info, I will close the issue.

**Comment by ORelio** [comment]
Just a quick hint: the usual workaround is to use a combination of antiafk and autorelog, because antiafk helps detecting that connection is lost and autorelog will reconnect to the server

**Comment by JohnnyLin-a** [comment]
Thanks for the help, I'll be taking a look at those

**Comment by JohnnyLin-a** [comment]
I ended up fixing this by changing device entirely. I am now using an ARM-64 device and everything is smooth.

Bottom line is that armhf is not well supported by mono.

**Comment by Mhowser** [comment]
How did you get mono running on arm64 smoothly? Because I have tried to run MCC on my phone using Termux. The phone is aarch64.

**Comment by JohnnyLin-a** [comment]
> How did you get mono running on arm64 smoothly? Because I have tried to run MCC on my phone using Termux. The phone is aarch64. To be specific:
> 
> SUPPORTED_ABIS = [arm64-v8a, armeabi-v7a, armeabi]
> SUPPORTED_32_BIT_ABIS = [armeabi-v7a, armeabi]
> SUPPORTED_64_BIT_ABIS = [arm64-v8a]

The device I'm running MCC on is not a phone, it's an old android tv which I installed Armbian Linux (Ubuntu-like distro) Kernel version 5.7.(something) Focal.

I said smoothly, but in reality, the first 10 seconds I connect to my server, MCC will not get any response back. Then after that 10 seconds, everything works perfectly. Instant feedback on player messages.

**Comment by ORelio** [comment]
> I said smoothly, but in reality, the first 10 seconds I connect to my server, MCC will not get any response back.

This is likely due to terrain handling on low-power devices. Had the same on a 1st-gen Raspberry Pi.

**Comment by Mhowser** [comment]
Where did you get mono for arm64?

**Comment by ORelio** [comment]
With apt-get install on Raspbian. Please note that 1st-gen Raspberry Pi was 32bit ARM, not arm64. And I did that years ago.
