### ISSUE TITLE
SetSlot crash 1.15.2

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1144]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

MC Version 1.15.2
Server Core 1.8.8 Paper Spigot
![image](https://user-images.githubusercontent.com/35975332/88343238-68f72700-cd5a-11ea-847a-42c7c833807a.png)

**Comment by ORelio** [comment]
Maybe an issue with packet ID?

**Comment by Nekiplay** [comment]
Now I will try to solve this problem

**Comment by Nekiplay** [comment]
Something to do with checking ContainsKey judging by the error
![image](https://user-images.githubusercontent.com/35975332/90340708-88106e00-e013-11ea-8599-c92e19ab91b6.png)

**Comment by Nekiplay** [comment]
There was no such problem before

**Comment by Nekiplay** [comment]
Something tells me that she appeared after https://github.com/ORelio/Minecraft-Console-Client/pull/1107/commits/a901c7103151df84cad9fa2314d1d2cf3105d484#diff-0f0a6c52bf7703cdaa878785348ebb98

**Comment by ORelio** [comment]
Seems likely, because `inventories[0]` is accessed without checking. Seems like a special case for storing item under cursor while moving items in inventories. Maybe the SetSlot() happens before the inventory is initialized.
https://github.com/ORelio/Minecraft-Console-Client/blob/a901c7103151df84cad9fa2314d1d2cf3105d484/MinecraftClient/McClient.cs#L1549

**Comment by ReinforceZwei** [comment]
If it really the case that setslot happened before windowopen, maybe we could assume the inventory 0 is present and always initialize it ourselves before the windowopen event.

**Comment by ORelio** [comment]
Yes or store the item at hand in a separate variable outside the inventory no. 0

**Comment by ReinforceZwei** [comment]
But we still need to store it within the inventories list otherwise we cannot access to it with the current getter method. It might become more complicated if we store it separately.

**Comment by ORelio** [comment]
You can. In that case, the inventory needs to be initialized without waiting for data from the server (`ClearInventories()` on logon?) and beware to keep item in slot `-1` inside `OnInventoryOpen()`. Not sure which one is easier between having an additional API for managing item at hand or making sure not to overwrite it in other places in the code. Do as you prefer.

**Comment by ReinforceZwei** [comment]
> Maybe the SetSlot() happens before the inventory is initialized.

I think this should never be happened as inventory 0 is always initialized in `OnRespawn()` event, which happens on login, respawn and world change. Maybe just adding the check before accessing inventory 0 for cursor item to prevent crashes. (If inventory 0 is absent we ignore the SetSlot)

**Comment by ORelio** [comment]
Resolved in #1217
