### ISSUE TITLE
MacOS Guide Link is Broken

### ISSUE THREAD

**Issue by mark27077** [ORelio/Minecraft-Console-Client#1147]
So on the Minecraft Forum page, there is a Minecraft Console Client thread. 
![image](https://user-images.githubusercontent.com/68750561/88418118-109f4400-cdb1-11ea-93fd-2ff6f88a4d80.png)
 
The link from the image goes to: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1263927-win-mac-linux-minecraft-console-client?page=31#c623

This link is not to the guide and is instead straight back to the page.

![image](https://user-images.githubusercontent.com/68750561/88418254-49d7b400-cdb1-11ea-8f3e-ecd07240a0b9.png)
This second image, also from the MCC Minecraft Forum page, has a detailed guide for MacOS link that leads right back to: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1263927-win-mac-linux-minecraft-console-client?page=31#c623

Is there a fixed link where I can view the guide?

**Comment by ORelio** [comment]
You can still find it by browsing the thread, but I think all images are gone anyway. Basically, install Mono on your Mac:
https://www.mono-project.com/download/stable/#download-mac
Then follow the Linux instructions.

**Comment by mark27077** [comment]
I get an error when running the msbuild MinecraftClient.csproj command.
![image](https://user-images.githubusercontent.com/68750561/88419333-054d1800-cdb3-11ea-9304-27cad0cb3f29.png)

**Comment by ReinforceZwei** [comment]
You can download the newest build from [here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and run it with `mono MinecraftClient.exe`. No need to build it yourself.

**Comment by ORelio** [comment]
You are not in the correct folder anyway. `pwd`, `ls` and `cd` are your friends.

**Comment by mark27077** [comment]
Alright, so I got it working. Is there a way I can do this process not manually? Such as the login information, server IP, and other commands? I have the scripts but when I do a command such as /script check it says that it can't find a file called "check."

I also have an afk.bat file where I can put in the login information and server IP: 
![image](https://user-images.githubusercontent.com/68750561/88421893-53641a80-cdb7-11ea-92f5-dc34d2a5471e.png)

I watched a tutorial and the guy opens the afk.bat and is able to run scripts there. Is it possible to do this on MacOS?

**Comment by mark27077** [comment]
Any idea why it says that these files aren't found when I have them?
![image](https://user-images.githubusercontent.com/68750561/88483225-7a942680-cf34-11ea-8ee9-be98d75b933f.png)

**Comment by ORelio** [comment]
Make sure that MCC is running from the correct directory.
Don't do `mono /path/to/MCC/MinecraftClient.exe` but rather `cd /path/to/MCC/` then `mono MinecraftClient.exe`.

**Comment by mark27077** [comment]
In the MincraftClient.ini:
![image](https://user-images.githubusercontent.com/68750561/88832919-83d4fb80-d19f-11ea-9fba-d628691a82db.png)
If I add my account info and the server IP, and I run the command to start Console Client, will it automatically log me in and connect to the server? Is it possible to do this with alt accounts as well in the same .ini file?

**Comment by mark27077** [comment]
For anyone wondering, no it was not possible to do with multiple accounts. However, it was able to work with one account at a time.
