### ISSUE TITLE
Auto relog issue: Version not supported

### ISSUE THREAD

**Issue by Whereismycantaloupe** [ORelio/Minecraft-Console-Client#1148]
When accounts crash or the server reboots they auto relog, yet it is stuck on this message every time: 

![Screen Shot 2020-07-24 at 1 25 28 AM](https://user-images.githubusercontent.com/66886849/88423404-9666c380-cda0-11ea-9d8a-0060e9dce3cb.png)

I manually type in 1.13.2 each time this happens and the accounts log back in. This is my .ini file: 

![Screen Shot 2020-07-24 at 1 26 00 AM](https://user-images.githubusercontent.com/66886849/88423480-b4342880-cda0-11ea-878c-7ed13fffe596.png)

Im not sure what I am missing. Please let me know!

**Comment by ORelio** [comment]
try `mcversion=1.13.2` in config.

**Comment by Whereismycantaloupe** [comment]
The same message still appears

**Comment by ORelio** [comment]
This setting must be defined in the `[Main]` section. All settings are already present, you need to edit the existing line.

**Comment by Whereismycantaloupe** [comment]
![Screen Shot 2020-07-26 at 12 38 16 AM](https://user-images.githubusercontent.com/66886849/88474093-5571ca80-ced8-11ea-9ffc-289c3abda28d.png)

Im not sure if this is what you mean, but adding this did not work

**Comment by ReinforceZwei** [comment]
Please look at few lines below. You will see the option `mcversion` there with default value of `auto`. Change it to your version and save the file.

**Comment by Whereismycantaloupe** [comment]
Thank you!
