### ISSUE TITLE
Default config error.

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [ORelio/Minecraft-Console-Client#115]
In the default config generation there is not a new line between botmessagedelay and mcversion.  Will cause a failed to start error and instant closure of window.  (On servers that have modded protocols for sure, unsure about vanilla.)

Simple fix but I don't feel like it is necessary to file a pull request for something so simple.

**Comment by Pokechu22** [comment]
I see what I did - [there _is_ a new line](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/Settings.cs#L411), but it's the wrong type: `\n\n` instead of `\r\n`.  So with some text editors (notepad), it'll mess up the new line...  My mistake.

**Comment by ORelio** [comment]
Got it, changed, will push that later. Thanks!

**Comment by ORelio** [comment]
This should be fixed now, thanks for reporting :)
