### ISSUE TITLE
Stuck at 99% cpu usage during Checking Session...

### ISSUE THREAD

**Issue by Govindass** [ORelio/Minecraft-Console-Client#1150]
**Prerequisites**
 - [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [NO] I have set `debugmessages=true` in config to diagnose my issue
 - [X] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
I am using debian 10, with mono. sometimes at "Checking Session..." (or something like that) it gets stuck forever and the machine gets stuck at 99% cpu until the process is killed.

**Comment by Govindass** [comment]
my issue sounds similar to https://github.com/ORelio/Minecraft-Console-Client/issues/1124 but I am already using memory cache.

**Comment by ORelio** [comment]
Still unsure what is causing this, leaving your issue open

**Comment by ORelio** [comment]
Unfortunately we could not reproduce this 😕

**Comment by Govindass** [comment]
the bug is still present by the way, noticed it recently, during relog

**Comment by ORelio** [comment]
Hi, still could not reproduce but added a safety in packet reading loop after session check to make sure the login process cannot stay there indefinitely if for some reason there is an issue reading packets from the server. Should hopefully resolve your issue.
