### ISSUE TITLE
Trying to open an inventory using a c# script

### ISSUE THREAD

**Issue by Antr0p0s** [ORelio/Minecraft-Console-Client#1151]
Pretty much the title, using the relatively new inventory handling tools, how can I open and navigate through inventories from a c# script.

E.G. (on a server)
/shop is inventory 1 > how can I press an item on there (automatic using c#) to go to a subshop etc.

**Comment by Antr0p0s** [comment]
MCC.PerformInternalCommand("inventory"); 

gives the error

Access to a non-static member of the outer type ScriptLoader.Script via the nested type ScriptLoader.Script.name is not possible

**Comment by ORelio** [comment]
Beware not to call `MCC.PerformInternalCommand` from a ChatBot. In ChatBots, use the ChatBot API:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs
You can use PerformInternalCommand() without leading MCC or use inventory-related API methods.
