### ISSUE TITLE
DigBlock No longer works / not working for me and how do i use the .cs scrips

### ISSUE THREAD

**Issue by Crazyy1** [ORelio/Minecraft-Console-Client#1153]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question
Hello , i apologise if this is just me being stupid however when i try to run the AutoCobble the client comes up with a error of  "Script 'hit.cs' failed to run (LoadError).
[MCC] [Script] System.InvalidOperationException: The name 'DigBlock' does not exist in the current context"
and when i try to write my own .cs script it says there is not a appropriate header
any help would be appreciated thank you

**Comment by ORelio** [comment]
I'm not sure DigBlock() is available from the Script API:
 - [Script API](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/CSharpRunner.cs#L190)
 - [ChatBot API](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs)

**Comment by Crazyy1** [comment]
Woah The man the myth the legend haha .. thanks for your reply - how would i implement making it hold down left click / dig constantly :D

**Comment by ORelio** [comment]
It's trickier than it sounds because you need to select a block to dig by coordinates. The game does it for you, but MCC doesn't since it has no user interfaces to directly click your target block. See an example here: [CobblestoneMiner.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs)

**Comment by Crazyy1** [comment]
Ah thank you so much - i only got into learning java so i was finding it quite difficult to code a chat bot but thank you for being active and helpful :D

**Comment by ORelio** [comment]
For your information, although it looks similar to Java, MCC is written in C#. And MCC scripts are slightly different to standard C# source code files so it's confusing for beginners. By the way, welcome to GitHub!

**Comment by Crazyy1** [comment]
ah i hope i can learn enough about coding then! and thank you for the welcome :D. and thanks for replying quickly , lots of respect for you ORelio 👍

**Comment by ORelio** [comment]
The network protocol of Minecraft is documented at https://wiki.vg/

**Comment by Crazyy1** [comment]
Wow thanks for all your help , its been really helpful :D
