### ISSUE TITLE
Libs

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1154]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Using third party libraries in a script? I want to connect System.Net.Http, but I am told that the link is not specified

**Comment by ORelio** [comment]
`System.Net.Http` is not part of .NET Framework 4.0. But indeed, it is currently not possible to load DLLs from scripts.

**Comment by ORelio** [comment]
Please note that's it is likely that the web request stuff you are looking for is simply in a different namespace in .NET 4.0

**Comment by Nekiplay** [comment]
I am using the latest version of NetFramework, I hope it will be possible to use other DLLs in my scripts, this would give a bunch of possibilities

**Comment by Nekiplay** [comment]
> Please note that's it is likely that the web request stuff you are looking for is simply in a different namespace in .NET 4.0

![image](https://user-images.githubusercontent.com/35975332/88975162-2d68d980-d2d3-11ea-8d38-e01716661064.png)

**Comment by ORelio** [comment]
The project is targeting .NET 4.0 for compatibility purposes so even when using a newer visual studio, it's limited to .NET 4.0.
See [sample-script-with-http-request.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-http-request.cs).
