### ISSUE TITLE
"Process is terminated due to StackOverflowException."

### ISSUE THREAD

**Issue by PsychoticMrEpic** [ORelio/Minecraft-Console-Client#1160]
Whenever I launch the console client it almost immediately gets the error message "Process is terminated due to StackOverflowException.". I've tried reinstalling everything related to it, but it doesn't help. It was working perfectly fine without having changed anything, but then this randomly happened and I'm just confused.
![Screenshot (29)](https://user-images.githubusercontent.com/68573461/88912098-c85aa880-d22c-11ea-8626-5b08a71046c0.png)

**Comment by ReinforceZwei** [comment]
Hi, could you enable `debugmessage` in the configuration file and post the screenshot again? That could provide more information for us to help you.

**Comment by PsychoticMrEpic** [comment]
I dont know what happened but it just worked normally. I didn't touch anything between when I posted this and now.
