### ISSUE TITLE
click on an item in the window

### ISSUE THREAD

**Issue by goncharov5606** [ORelio/Minecraft-Console-Client#1167]
how to click on an item in the window?

**Comment by ReinforceZwei** [comment]
`/inventory <inventoryID> click <slot-you-want-to-click> <left|right>`

**Comment by goncharov5606** [comment]
after using this command, kicks from the server

**Comment by ReinforceZwei** [comment]
Please make sure you are using the latest build of MCC and try again. If it didn't work, the server may have anti-cheat plugins installed.
