### ISSUE TITLE
I don't know how to write this match of autorespond bot.

### ISSUE THREAD

**Issue by crosspedestrian** [ORelio/Minecraft-Console-Client#1169]
Clearly I'm a newbie.
Sometimes the server will send message, for example,  "ABCDEFGHIJK 12 LMNOPQRSTUVWXYZ", and players should send 12. The number is different at every turn but others are same. Well, it's a verification code.
I don't know the regex. I tried to write the match, then failed.

[Match]
regex=^.*ABCDEFGHIJK ([0-9]+).*$    //I think it is wrong.
wait 30     // I want to delay 3 seconds.
action=send $1   //send the number once.

Can you help me? Thanks.

**Prerequisites**
 - [√] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [√] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [√] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Comment by Tnavillacs** [comment]
With a .cs you could split it with spaces like this:` string[] part text.Split(' ');`
Split(' ') split your message into 3 parts (part[0], part[1] and part[2])
And I think you add a delay like this: `Thread.Sleep(30000);`
To send the 12 you would have to: `SendText(part[1]);`

I hope this helps somehow

**Comment by crosspedestrian** [comment]
> With a .cs you could split it with spaces like this:` string[] part text.Split(' ');`
> Split(' ') splits your message into 3 parts (part[0], part[1] and part[2])
> And I think you add a delay like this: `Thread.Sleep(30000);`
> To send the 12 you would have to: `SendText(part[1]);`
> 
> I hope this helps somehow

Thank you very much, your meaning is clear, however I don't know C# so can't write the .cs. And if it is possible, I hope to get the .cs or match.ini. Moreover, does the .cs locate in /scripts then the client can auto-execute it？

**Comment by Tnavillacs** [comment]
> > With a .cs you could split it with spaces like this:` string[] part text.Split(' ');`
> > Split(' ') splits your message into 3 parts (part[0], part[1] and part[2])
> > And I think you add a delay like this: `Thread.Sleep(30000);`
> > To send the 12 you would have to: `SendText(part[1]);`
> > I hope this helps somehow
> 
> Thank you very much, your meaning is clear, however I don't know C# so can't write the .cs. And if it is possible, I hope to get the .cs or match.ini. Moreover, does the .cs locate in /scripts then the client can auto-execute it？

You can simply start it like any other script.

`//MCCScript 1.0

MCC.LoadBot(new AutoRespondBot());

//MCCScript Extensions

public class AutoRespondBot : ChatBot
{

    public override void Initialize()
    {
        LogToConsole("AutoRespondBot enabled!");
    }
    public override void GetText(string text)
    {
            if(text.Contains("ABCDEFGHIJK"))
                {
                LogToConsole(text);
                string[] part = text.Split(' ');
                Thread.Sleep(30000);
                SendText(part[1]);
                }
    }
}`

**Comment by crosspedestrian** [comment]
> > > With a .cs you could split it with spaces like this:` string[] part text.Split(' ');`
> > > Split(' ') splits your message into 3 parts (part[0], part[1] and part[2])
> > > And I think you add a delay like this: `Thread.Sleep(30000);`
> > > To send the 12 you would have to: `SendText(part[1]);`
> > > I hope this helps somehow
> > 
> > 
> > Thank you very much, your meaning is clear, however I don't know C# so can't write the .cs. And if it is possible, I hope to get the .cs or match.ini. Moreover, does the .cs locate in /scripts then the client can auto-execute it？
> 
> You can simply start it like any other script.
> 
> ```
> //MCCScript 1.0
> 
> MCC.LoadBot(new AutoRespondBot());
> 
> //MCCScript Extensions
> 
> public class AutoRespondBot : ChatBot
> {
> 
>     public override void Initialize()
>     {
>         LogToConsole("AutoRespondBot enabled!");
>     }
>     public override void GetText(string text)
>     {
>             if(text.Contains("ABCDEFGHIJK"))
>                 {
>                 LogToConsole(text);
>                 string[] part = text.Split(' ');
>                 Thread.Sleep(30000);
>                 SendText(part[1]);
>                 }
>     }
> }
> ```
> 
> Hope this works. Didn't try it myself.

Thanks for your patience. I will try to understand the code and test it.

**Comment by ORelio** [comment]
`action` is for chat messages, you're looking for `actionother` for system messages.
```INI
[Match]
regex=^ABCDEFGHIJK ([0-9]+) LMNOPQRSTUVWXYZ$
actionother=send $1
```
There is currently no "wait" feature so you need a script if you want to wait:
```INI
[Match]
regex=^ABCDEFGHIJK ([0-9]+) LMNOPQRSTUVWXYZ$
actionother=script sendwait.txt
```
sendwait.txt can retrieve the match like this:
```
wait 30
send %match_1%
```
