### ISSUE TITLE
KCauldron bot not triggering join message or player spawning in

### ISSUE THREAD

**Issue by DigitalSniperz** [ORelio/Minecraft-Console-Client#117]
I finally got the bot to connect to a kcauldron server, however he doesn't actually spawn in or trigger the "has joined the game!" message. KCauldron 1.7.10, centos 6.6, mono 3.2.8 and the latest beta version of the client. Heres my log,

`Console Client for MC 1.4.6 to 1.8.8 - v1.8.2 - By ORelio & Contributors
Username : BLANK
Password : <******>                                                             
Connecting to Minecraft.net...
Success. (session ID: BLANKED)
Server IP : BLANKED
Retrieving Server Info...
Server version : kcauldron,cauldron,craftbukkit,mcpc,fml,forge 1.7.10 (protocol v5).
Server is running forge. Mod list:
  mcp v9.05
  FML v7.10.99.99
  Forge v10.13.4.1614
  kimagine v0.2
  appliedenergistics2-core vrv2-stable-10
  CodeChickenCore v1.0.7.47
  Micdoodlecore v
  <CoFH ASM> v000
  <DragonAPI ASM> v0
  CoFHCore v1.7.10R3.0.3
  advancedgenetics v1.5.9
  animalsPlus v1.2
  appliedenergistics2 vrv2-stable-10
  Baubles v1.0.1.10
  Artifacts v1.1.3
  Backpack v2.0.1
  ThermalFoundation v1.7.10R1.2.0
  ThermalExpansion v1.7.10R4.0.3B1
  BigReactors v0.4.3A
  BiomesOPlenty v2.1.0
  Thaumcraft v4.2.3.5
  Botania vr1.8-248
  BrandonsCore v1.0.0.10
  BuildCraft|Core v7.1.14
  BuildCraft|Builders v7.1.14
  BuildCraft|Transport v7.1.14
  BuildCraft|Energy v7.1.14
  BuildCraft|Silicon v7.1.14
  BuildCraft|Robotics v7.1.14
  BuildCraft|Factory v7.1.14
  CarpentersBlocks v3.3.8_dev_r8
  BuildMod vv1.0
  CoroPets vv1.0
  CoroAI vv1.0
  ExtendedRenderer vv1.0
  ConfigMod vv1.0
  DraconicEvolution v1.0.2-snapshot_9
  HardcoreEnderExpansion v1.8.5
  Forestry v4.2.5.53
  Railcraft v9.8.0.0
  ImmersiveEngineering v0.6.5.1
  Mantle v1.7.10-0.3.2.jenkins191
  MineFactoryReloaded v1.7.10R2.8.0
  TConstruct v1.7.10-1.8.8.build988
  DragonAPI v1.0
  enviromine v1.3.124
  exoticbirds v1.0
  Steamcraft v0.28.12
  fossil v1.7.10 Build 7.2.1
  GalacticraftCore v3.0.12
  GalacticraftMars v3.0.12
  InfernalMobs v1.6.6
  IronChest v6.0.62.742
  MeteorCraft v1.0
  MineFactoryReloaded|CompatAppliedEnergistics v1.7.10R2.8.0
  MineFactoryReloaded|CompatAtum v1.7.10R2.8.0
  MineFactoryReloaded|CompatBackTools v1.7.10R2.8.0
  MineFactoryReloaded|CompatBuildCraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatChococraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatExtraBiomes v1.7.10R2.8.0
  MineFactoryReloaded|CompatForestry v1.7.10R2.8.0
  MineFactoryReloaded|CompatForgeMicroblock v1.7.10R2.8.0
  MineFactoryReloaded|CompatIC2 v1.7.10R2.8.0
  MineFactoryReloaded|CompatMystcraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatProjRed v1.7.10R2.8.0
  MineFactoryReloaded|CompatRailcraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatSufficientBiomes v1.7.10R2.8.0
  MineFactoryReloaded|CompatThaumcraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatThermalExpansion v1.7.10R2.8.0
  MineFactoryReloaded|CompatTConstruct v1.7.10R2.8.0
  MineFactoryReloaded|CompatTwilightForest v1.7.10R2.8.0
  MineFactoryReloaded|CompatVanilla v1.7.10R2.8.0
  Oceancraft v1.4.1
  rftools v4.20
  corerm v1.0c
  Roguelike v1.4.4
  RTG v0.4.0
  camping v2.1g
  erebus v0.4.1
  ThermalDynamics v1.7.10R1.1.0
  weather2 vv2.3.10
  witchery v0.24.1
  ZombieInfection v@VERSION@
Translations file loaded.
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...`

Any help?

**Comment by ORelio** [comment]
Not sure what is causing that, since Forge is now supported thanks to @Pokechu22 's work :/
Related issue: #88

**Comment by Pokechu22** [comment]
I'm looking into this.  What I do see is that it isn't making it all the way through (or even to the start of) the forge login - if it were it would mention "Forge protocol version".

I'll try to set up a server similar to the one you're trying to connect to.  I only tested against regular cauldron, not kcauldron - kcauldron may do something slightly differently (though a quick look at the code doesn't show anything like that).

**Comment by DigitalSniperz** [comment]
I noticed when I was using mono on my centos machine, it would stop at "checking session.."  however joining the exact same server but using windows (windows 10), it connected. When it connected there was no "has joined the game!" and the bot didn't spawn in/appear on the tab list.

**Comment by DigitalSniperz** [comment]
Confirmed that you fixed it on windows 10, I am able to join the kcauldron server and player spawns in/join message triggered. However on centos 6.6, mono 3.2.8 it does not work at all. I'm not seeing any coloured text, this is all I am getting.

`Console Client for MC 1.4.6 to 1.8.8 - v1.8.2 - By ORelio & Contributors
Username : BLANKED
Password : BLANKED                                                             
Connecting to Minecraft.net...
Success. (session ID: BLANKED)
Server IP : BLANKED
Using Minecraft version 1.7.10 (protocol v5)
Translations file loaded.
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server.
>hi
>`

**Comment by ORelio** [comment]
You can thank the Minecraft Forge expert @Pokechu22 for that :smile:
Regarding Mono there are often issues with older versions of Mono.
Version `3.2.8` dates back to two years ago ([see release dates](http://www.mono-project.com/docs/about-mono/releases/)).
Latest version is `4.2.2.30` so you might want to try upgrading?

**Comment by DigitalSniperz** [comment]
Its not working on windows, I thought it was. I'm getting this error on my windows & my linux server when joining a kcauldron server.

```
Console Client for MC 1.4.6 to 1.8.8 - v1.8.2 - By ORelio & Contributors
Connecting to Minecraft.net...
Success. (session ID: BLANKED)
Server IP : BLANKED
Retrieving Server Info...
Server version : kcauldron,cauldron,craftbukkit,mcpc,fml,forge 1.7.10 (protocol v5).
Server is running forge. Mod list:
  mcp v9.05
  FML v7.10.99.99
  Forge v10.13.4.1614
  kimagine v0.2
  appliedenergistics2-core vrv2-stable-10
  CodeChickenCore v1.0.7.47
  Micdoodlecore v
  <CoFH ASM> v000
  <DragonAPI ASM> v0
  CoFHCore v1.7.10R3.0.3
  advancedgenetics v1.5.9
  animalsPlus v1.2
  appliedenergistics2 vrv2-stable-10
  Baubles v1.0.1.10
  Artifacts v1.1.3
  Backpack v2.0.1
  ThermalFoundation v1.7.10R1.2.0
  ThermalExpansion v1.7.10R4.0.3B1
  BigReactors v0.4.3A
  BiomesOPlenty v2.1.0
  Thaumcraft v4.2.3.5
  Botania vr1.8-248
  BrandonsCore v1.0.0.10
  BuildCraft|Core v7.1.14
  BuildCraft|Builders v7.1.14
  BuildCraft|Transport v7.1.14
  BuildCraft|Energy v7.1.14
  BuildCraft|Silicon v7.1.14
  BuildCraft|Robotics v7.1.14
  BuildCraft|Factory v7.1.14
  CarpentersBlocks v3.3.8_dev_r8
  BuildMod vv1.0
  CoroPets vv1.0
  CoroAI vv1.0
  ExtendedRenderer vv1.0
  ConfigMod vv1.0
  DraconicEvolution v1.0.2-snapshot_9
  HardcoreEnderExpansion v1.8.5
  Forestry v4.2.5.53
  Railcraft v9.8.0.0
  ImmersiveEngineering v0.6.5.1
  Mantle v1.7.10-0.3.2.jenkins191
  MineFactoryReloaded v1.7.10R2.8.0
  TConstruct v1.7.10-1.8.8.build988
  DragonAPI v1.0
  enviromine v1.3.124
  exoticbirds v1.0
  Steamcraft v0.28.12
  fossil v1.7.10 Build 7.2.1
  GalacticraftCore v3.0.12
  GalacticraftMars v3.0.12
  InfernalMobs v1.6.6
  IronChest v6.0.62.742
  MeteorCraft v1.0
  MineFactoryReloaded|CompatAppliedEnergistics v1.7.10R2.8.0
  MineFactoryReloaded|CompatAtum v1.7.10R2.8.0
  MineFactoryReloaded|CompatBackTools v1.7.10R2.8.0
  MineFactoryReloaded|CompatBuildCraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatChococraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatExtraBiomes v1.7.10R2.8.0
  MineFactoryReloaded|CompatForestry v1.7.10R2.8.0
  MineFactoryReloaded|CompatForgeMicroblock v1.7.10R2.8.0
  MineFactoryReloaded|CompatIC2 v1.7.10R2.8.0
  MineFactoryReloaded|CompatMystcraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatProjRed v1.7.10R2.8.0
  MineFactoryReloaded|CompatRailcraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatSufficientBiomes v1.7.10R2.8.0
  MineFactoryReloaded|CompatThaumcraft v1.7.10R2.8.0
  MineFactoryReloaded|CompatThermalExpansion v1.7.10R2.8.0
  MineFactoryReloaded|CompatTConstruct v1.7.10R2.8.0
  MineFactoryReloaded|CompatTwilightForest v1.7.10R2.8.0
  MineFactoryReloaded|CompatVanilla v1.7.10R2.8.0
  Oceancraft v1.4.1
  rftools v4.20
  corerm v1.0c
  Roguelike v1.4.4
  RTG v0.4.0
  camping v2.1g
  erebus v0.4.1
  ThermalDynamics v1.7.10R1.1.0
  weather2 vv2.3.10
  witchery v0.24.1
  ZombieInfection v@VERSION@
Translations file loaded.
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Forge protocol version : 2
Sending falsified mod list to server...
Accepting server mod list...
Received registry with 5573 entries
Accepting server registries...
Forge server connection complete!
Server was successfully joined.
Type '/quit' to leave the server.
[] PLAYER joined the game.
[DragonAPI Notification:]
[DragonAPI is out of date, likely has errors, and is no longer supported. Update to v11a.]
[MeteorCraft is out of date, likely has errors, and is no longer supported. Update to v11a.]
[To disable this notifcation for any mod, type "/checker disable [modname]".]
[Changes take effect upon server or client restart.]

Unhandled Exception:
System.ArgumentException: index and count exceed length of list
  at System.Collections.Generic.List`1[System.Byte].CheckRange (Int32 idx, Int32 count) [0x00000] in <filename unknown>:0
  at System.Collections.Generic.List`1[System.Byte].RemoveRange (Int32 index, Int32 count) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.readData (Int32 offset, System.Collections.Generic.List`1 cache) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextUShortsLittleEndian (Int32 amount, System.Collections.Generic.List`1 cache) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.ProcessChunkColumnData (Int32 chunkX, Int32 chunkZ, UInt16 chunkMask, Boolean hasSkyLight, Boolean chunksContinuous, System.Collections.Generic.List`1 cache) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket (Int32 packetID, System.Collections.Generic.List`1 packetData) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update () [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: index and count exceed length of list
  at System.Collections.Generic.List`1[System.Byte].CheckRange (Int32 idx, Int32 count) [0x00000] in <filename unknown>:0
  at System.Collections.Generic.List`1[System.Byte].RemoveRange (Int32 index, Int32 count) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.readData (Int32 offset, System.Collections.Generic.List`1 cache) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextUShortsLittleEndian (Int32 amount, System.Collections.Generic.List`1 cache) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.ProcessChunkColumnData (Int32 chunkX, Int32 chunkZ, UInt16 chunkMask, Boolean hasSkyLight, Boolean chunksContinuous, System.Collections.Generic.List`1 cache) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket (Int32 packetID, System.Collections.Generic.List`1 packetData) [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update () [0x00000] in <filename unknown>:0
  at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
```

**Comment by ORelio** [comment]
`readNextUShortsLittleEndian` : Seems like Forge-related stuff.
However once logged in forge support can be disabled, I guess.

**Comment by DigitalSniperz** [comment]
How can I fix that?

**Comment by ORelio** [comment]
Try the latest dev build that includes the above commit.
Not sure it fixes your issue but it might work?

**Comment by DigitalSniperz** [comment]
Worked, good job! Bot now connects to kcauldron & spawns in/triggers the join message.

**Comment by ORelio** [comment]
Yay, glad it worked, I was absolutely not sure about that but I think Forge was sending some further messages after Forge login, which weren't handled properly and could as well be ignored ^^

**Comment by Pokechu22** [comment]
It also looks like forge [tweaked the structure of the packet slightly](https://github.com/MinecraftForge/MinecraftForge/commit/6e90348dc546164b21735aefd83ed0bac0d8283c), which would combine with data remaining in the list between packets (even if it's just a 0, that 0 will be added to the list and corrupt further packets).  I've [updated the protocol docs](http://wiki.vg/index.php?title=Minecraft_Forge_Handshake&diff=7439&oldid=7436), though I don't think we need to handle this new data.

**Comment by ORelio** [comment]
That's a bit weird indeed. Not sure why they need so many changes to the protocol.
