### ISSUE TITLE
view coordinates

### ISSUE THREAD

**Issue by goncharov5606** [ORelio/Minecraft-Console-Client#1171]
How can you find out the coordinates of the block the player is looking at?

**Comment by Nekiplay** [comment]
![image](https://user-images.githubusercontent.com/35975332/89131730-854c4e00-d528-11ea-847e-c210a291c980.png)

**Comment by ORelio** [comment]
And from the command prompt: `/move get`

**Comment by goncharov5606** [comment]
Спасибо

**Comment by goncharov5606** [comment]
![image](https://user-images.githubusercontent.com/58649986/89156091-e9ecc480-d58b-11ea-9a92-06833c9349c5.png)
Выдает ошибку
