### ISSUE TITLE
Is there any clean way to get the Sender of every chat message for .cs?

### ISSUE THREAD

**Issue by Tnavillacs** [ORelio/Minecraft-Console-Client#1172]
Is there any clean way to get the **Sender** of every chat message for .cs?
I was about to split the message and do it with arguments but remembered that people use the nickname plugin.

**Comment by ORelio** [comment]
You have everything you need in the ChatBot API, e.g. [IsChatMessage](
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L512) with [GetText](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L114) event.
Caveat: Server admins can spoof usernames with /nick for instance (#1142)
