### ISSUE TITLE
On question 1171

### ISSUE THREAD

**Issue by goncharov5606** [ORelio/Minecraft-Console-Client#1173]
https://github.com/ORelio/Minecraft-Console-Client/issues/1171
When using this method, the bot throws such an error!
![image](https://user-images.githubusercontent.com/58649986/89156962-777ce400-d58d-11ea-8788-bfa61ab6e0ef.png)

**Comment by goncharov5606** [comment]
And I asked about the current coordinates of the block that the player is looking at

**Comment by ORelio** [comment]
Sorry but I cannot read cyrillic. What does it say?

**Comment by goncharov5606** [comment]
Sorry, I threw off another, here
![image](https://user-images.githubusercontent.com/58649986/89162146-6f28a700-d595-11ea-81d4-b8c49bedaaa7.png)
Says that a non-statistical field, method or property MinecraftClient.ChatBot.GetCurrentLocation () requires an object reference. But that's not the point, I need the coordinates of the block that the bot is looking at, not the coordinates of the bot!

**Comment by ORelio** [comment]
Ah, I think that's because you are trying to use that method from a script, instead of a chatbot. You would need to define a script that loads a chatbot as shown by @Nekiplay in https://github.com/ORelio/Minecraft-Console-Client/issues/1171#issuecomment-667720826

**Comment by goncharov5606** [comment]
that's not the point, I need the coordinates of the block that the bot is looking at, not the coordinates of the bot!

**Comment by ReinforceZwei** [comment]
Currently there is no method for getting the block player is looking at.

**Comment by goncharov5606** [comment]
> Ah, I think that's because you are trying to use that method from a script, instead of a chatbot. You would need to define a script that loads a chatbot as shown by @Nekiplay in [#1171 (comment)](https://github.com/ORelio/Minecraft-Console-Client/issues/1171#issuecomment-667720826)

That's exactly what I did

**Comment by ORelio** [comment]
As @ReinforceZwei stated, this is not possible at the moment.
