### ISSUE TITLE
How to dig up blocks in order?

### ISSUE THREAD

**Issue by goncharov5606** [ORelio/Minecraft-Console-Client#1177]
How to dig up blocks in order? In a generator of 5 blocks in a row.

**Comment by ReinforceZwei** [comment]
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/TreeFarmer.cs

An example of Tree farmer. Modify it as your need.

**Comment by goncharov5606** [comment]
thank

**Comment by goncharov5606** [comment]
thank
