### ISSUE TITLE
inventory click error

### ISSUE THREAD

**Issue by laskgay** [ORelio/Minecraft-Console-Client#1178]
Hello, why in your bot, when I want to go to the skyblock server to put the bot to dig, when I enter the command / intentorty 1 click 33 left ( 1-slot for selecting mini-games, 33-skyblock), the bot turns off? How to fix it tell me.

**Comment by ORelio** [comment]
If the client crashes, please enable debug messages in config and provide output. We cannot help otherwise.

**Comment by hammarez** [comment]
> Если клиент выходит из строя, пожалуйста, включите отладочные сообщения в конфигурации и предоставьте выходные данные. Иначе мы не сможем помочь.

You can find out where these debugging messages are coming from, I have already enabled them. But I don't know where they go. Explain to me please.

**Comment by ORelio** [comment]
Here is an example of valid bug report: #1060
