### ISSUE TITLE
I published this resource on a Russian forum 

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1183]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

![image](https://user-images.githubusercontent.com/35975332/89583486-dbd0c980-d853-11ea-8bba-918d205dc6aa.png)

**Comment by ORelio** [comment]
Feel free to share Minecraft Console Client with anyone you want as long as you include a link to the repository, which you did 😉

Note: Found the thread here: https://yougame.biz/threads/151849/
