### ISSUE TITLE
Delay for cs

### ISSUE THREAD

**Issue by Tnavillacs** [ORelio/Minecraft-Console-Client#1185]
How can I add a delay without making the chat stop? Thread.Sleep is stopping the chat.

**Comment by ORelio** [comment]
In ChatBots, you need to wait for subsequent calls to Update(). You can use a counter for that.

**Comment by Tnavillacs** [comment]
@ORelio I'm trying to skip a few messages.

**Comment by ORelio** [comment]
Not sure a delay would help here. You could implement a counter in GetText() to skip the desired amount of messages, or save the current DateTime.Now timestamp and ignore all subsequent calls to GetText() when DateTime.Now is not recent enough. Example from [Mailer](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/Mailer.cs):
```C#
nextMailSend = dateNow.AddSeconds(10);
```
```C#
DateTime dateNow = DateTime.Now;
if (nextMailSend < dateNow)
{
```
