### ISSUE TITLE
Connecting to Minecraft.net... (On Ubuntu VPS)

### ISSUE THREAD

**Issue by ilan1009** [ORelio/Minecraft-Console-Client#1186]
**Prerequisites**
 - [y] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [y] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [ y] I have set `debugmessages=true` in config to diagnose my issue
 - [y ] I have redacted session tokens and passwords before attaching screenshots

When trying to connect to "0b0t.org", or any server, It will appear to be stuck indefinitely at "Connecting to minecraft.net..."
![2020-08-08 03_10_46-DigitalOcean Droplet Console - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/51132557/89697457-d42d2580-d924-11ea-9a37-8380b390a3e8.png)

**Comment by henrydatei** [comment]
I have the same issue, here is the log with all the debug messages:
```
$ mono MinecraftClient_new.exe MinecraftClient.ini 
Console Client for MC 1.4.6 to 1.16.1 - v1.16.1 - By ORelio & Contributors
AppVeyor build 360, built on Fri 08/07/2020 from commit ce83cc0
[MCC] [Settings] Loading Settings from /home/henry/Downloads/MinecraftClient.ini
Resolving minetania.net...
Found server mc.minetania.net:25565 for domain minetania.net
[SessionCache] Initializing FileSystemWatcher for file: /home/henry/Downloads/SessionCache.ini
Loading session cache from disk: SessionCache.ini
No sessions could be loaded from disk
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
> POST /authenticate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.16.1
> Content-Type: application/json
> Content-Length: 149
> Connection: close
> 
> {"agent": { "name": "Minecraft", "version": 1 }, "username": "***", "password": "***", "clientToken": "***" }

< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 535
< Connection: close
< Accept-Ranges: bytes
< Date: Sat, 08 Aug 2020 10:42:04 GMT
< Server: Restlet-Framework/2.4.1
< Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
< X-Cache: Miss from cloudfront
< Via: 1.1 a477b8537c9bc4c10a3c144386a7b5bf.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: ***
< X-Amz-Cf-Id: ***
< 
< {"accessToken":"***","clientToken":"***","availableProfiles":[{"legacy":true,"name":"***","id":"***"}],"selectedProfile":{"legacy":true,"name":"***","id":"***"}}
Saving session cache to disk
```

**Comment by henrydatei** [comment]
The file `SessionCache.ini` is empty.

**Comment by ORelio** [comment]
Thanks for the detailed bug report. I think I found the cause thanks to your detailed log. Please retry with the latest build 🙂
