### ISSUE TITLE
When typing /help or any command, no feedback shows.

### ISSUE THREAD

**Issue by ilan1009** [ORelio/Minecraft-Console-Client#1187]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
A bug report should contain the following items:
* A clear and concise description of what the bug is
* Steps to reproduce the behavior
* What I expected to happen instead
* If applicable, add screenshots to help explain your problem
* Specify which kind of operating system you are running

Running ubuntu 20.04 VPS.
(I cant seem to find debug logs.)

**Comment by Nekiplay** [comment]
use [x] no [y ] )

**Comment by ilan1009** [comment]
Aight.

**Comment by ORelio** [comment]
Not sure how to diagnose or reproduce this. Does it simply hang without any additional steps? How do you launch MCC?

**Comment by ilan1009** [comment]
Hello, I run using `mono MinecraftClient.exe`, It literally just prints some empty lines, different with each command. Also /move doesn't work.

**Comment by ORelio** [comment]
Make sure your console properly prints dark gray text, maybe your console displays dark gray text on dark gray background.

**Comment by ilan1009** [comment]
> Make sure your console properly prints dark gray text, maybe your console displays dark gray text on dark gray background.

Wouldn't know how to check, Both digitaloceans console and PUTTY dont show anything, Any recommendations?

**Comment by ORelio** [comment]
I'll add a debug line 🤔

**Comment by ORelio** [comment]
Please try out the latest build with `debugmessages=true` set in the configuration file. Your terminal should display this:

![image](https://user-images.githubusercontent.com/1128206/89737214-9a1c6a80-da6f-11ea-9b86-3a83eceae92a.png)
