### ISSUE TITLE
Is autofishing not available in version 1.11.2?

### ISSUE THREAD

**Issue by Oopas** [ORelio/Minecraft-Console-Client#1190]
Autofishing requires `entityhandling` to be enabled.
But I saw in an issue that it can only be used after 1.12.2.
When I connected to the 1.11.2 server, I found that the fish bit the character and did not respond.
Does that mean it can't be used?😅

**Comment by ReinforceZwei** [comment]
Since entity handling only support 1.12.2 or higher, so yes, it cannot be used in 1.11.2.

**Comment by Oopas** [comment]
> Since entity handling only support 1.12.2 or higher, so yes, it cannot be used in 1.11.2.

Is there any alternative way to share😓
I try autofish mod, but fishing will stop automatically after a while. I tried a fishingbot. Although it supports 1.11.1, it does not support 1.11.2...........

**Comment by ReinforceZwei** [comment]
One way is implement entity handling for 1.11.2 and below. It will take some times to do though.

**Comment by Oopas** [comment]
> One way is implement entity handling for 1.11.2 and below. It will take some times to do though.

thanks

**Comment by ORelio** [comment]
Entity handling is now implemented by @ReinforceZwei for MC versions between 1.10 and 1.12.2 (#1195)
