### ISSUE TITLE
Need help with generating Entity Palettes for 1.12 and below

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1192]
Seems like it is okay to support version 1.10, 1.11 and 1.12 as the packet ID were added and packet didn't have change.
@ORelio Could you help me with this, please?

**Comment by Nekiplay** [comment]
I think this can be done manually by running the cannon on the server with this version and the main minecraft and spawn mobs by recognizing their ID

**Comment by ORelio** [comment]
Entity palettes were introduced in 1.14. Below, it was a fixed set of IDs: Use [EntityPalette113](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/EntityPalettes/EntityPalette113.cs) for any version below Minecraft 1.14.

**Comment by ReinforceZwei** [comment]
@ORelio I have tried enable entity in 1.12.2 and it instantly thrown the type ID not found error.

**Comment by ReinforceZwei** [comment]
Solved

**Comment by ORelio** [comment]
Related: #1195
