### ISSUE TITLE
AutoCraft

### ISSUE THREAD

**Issue by Oopas** [ORelio/Minecraft-Console-Client#1193]
How to use autocraft? I tried to find the documentation but failed.
I try to use the default configuration file. After executing `/ autocraft start whatever,` it reports an error `table not found`
pls....

**Comment by ReinforceZwei** [comment]
First you need to define the crafting recipe in the configuration file. You may follow the default recipe format to write your own recipe.
```ini
[Recipe]
name=brick            # name could be whatever you like. This field must be defined first
type=player            # crafting table type: player or table
result=StoneBricks     # the resulting item

# define slots with their deserved item
slot1=stone            # slot start with 1, count from left to right, top to bottom
slot1=stone
slot1=stone
# For the naming of the items, please see
# https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Inventory/ItemType.cs
```
You can do `/autocraft help` for commands usage.
