### ISSUE TITLE
Item durability of current slot

### ISSUE THREAD

**Issue by Tnavillacs** [ORelio/Minecraft-Console-Client#1197]
Been looking for some time. Is there a way to get the item durability of the current slot?

**Comment by Nekiplay** [comment]
Use NBT

**Comment by ReinforceZwei** [comment]
As @Nekiplay stated, use NBT, but it is not implemented in MCC yet. So you cannot get it now.

**Comment by ORelio** [comment]
```C#
Item item = // [...]
Dictionary<string, object> nbt = item.NBT;
```
You might find what you want in the NBT dictionary. Haven't looked yet. If you find it, we can help adding a getter for it.

**Comment by Nekiplay** [comment]
> ```cs
> Item item = // [...]
> Dictionary<string, object> nbt = item.NBT;
> ```
> 
> You might find what you want in the NBT dictionary. Haven't looked yet. If you find it, we can help adding a getter for it.

![image](https://user-images.githubusercontent.com/35975332/90092536-9b38ea80-dd42-11ea-98ca-1bf21dbc8427.png)

**Comment by Nekiplay** [comment]
![image](https://user-images.githubusercontent.com/35975332/90319641-4f10c480-df53-11ea-9d51-7150f955d769.png)

**Comment by Nekiplay** [comment]
Resolved

**Comment by Nekiplay** [comment]
#1213

**Comment by ORelio** [comment]
Closing as resolved since [Damage](https://github.com/ORelio/Minecraft-Console-Client/blob/a6a5f0c333a8f26c6edb87f7e3b700546f3815c5/MinecraftClient/Inventory/Item.cs#L77) field is now implemented in Item.cs
