### ISSUE TITLE
Inventory Support

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#120]
I Know I just Did An Issue Was rlly a question But... Can This console do Inventory Checking/Moving
Because Factions Servers I Want it To Auto Sell Things Wich Means /Shop Walking to a location Clicking on a Sign And Clicking The 7th Button

**Comment by ORelio** [comment]
Inentory : No (currently not handled at all)
Moving : Yes (you need `terrainandmovements=true` then you can `/move`)
