### ISSUE TITLE
OnUpdate crash

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1206]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [ ] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots
![image](https://user-images.githubusercontent.com/35975332/90263300-f1a04900-de68-11ea-8629-ebba7ae6baad.png)

**Comment by Nekiplay** [comment]
event Update I do not use in the script

**Comment by ORelio** [comment]
by chance, were you able to get the line number? You might need to recompile in debug mode.

**Comment by Nekiplay** [comment]
I do not know how this crash appeared, but when the console was restarted, it no longer appeared.

**Comment by ORelio** [comment]
Unfortunately we could not find out the root cause of this.
