### ISSUE TITLE
Interactions with the Factions plugin

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#121]
I Use This Console Client Along With My Skype Bot To Do Faction management That includes Adding,Promoting,Demoting,Description Changing,Title Changeing. But Since I can Get More alts Is there any way Of making it so The Client Can Get The Faction List And Filter Out Everything Exept The users If We wanted 30 Users I Would Just Have to make It Subtract The Number we have now and then Run A Script For Grabbing the users From A ini File My Skype Bot Is Coded in VB I See Your Source Code Is Also In Vb

**Comment by Aragas** [comment]
dat formatting tho

**Comment by CarbonNeuron** [comment]
Then I Wanted It To Only Respond For People in My Faction Chat For Certain Commands I Think the auto respond Bot would be helpful but That Could Also Use The Public Chat

**Comment by CarbonNeuron** [comment]
I Figured Part Of It Out Dont Know How To Implement Our Faction Chat Has A +[Name] And a *[Name] How Can i make it So Thats the only One to Respond to?

**Comment by ORelio** [comment]
Well, first of all, `I Have Alot Of needs Im Sorry` is not a clear issue title. Also please refrain from putting a capital letter for each word of your sentences, that's harder to read :package: 

Regarding your issue you can make a C# bot as a .cs file that does what you want.
See [configuration files](https://github.com/ORelio/Minecraft-Console-Client/tree/Indev/MinecraftClient/config) from the Indev branch for more info ;)

Renaming your issue, and closing as this isn't a bug nor a feature request for the core project, that's a specific need of yours so I can't really help you besides telling you that you can write your own chat bot ;)
