### ISSUE TITLE
Script timing not working

### ISSUE THREAD

**Issue by Awpocalypse** [ORelio/Minecraft-Console-Client#122]
So basically I am trying to make a script like this

wait 1
send /server jurassic
wait 1
send /sell cactus
wait 120
send /sell cactus
wait 120
send /sell cactus
wait 120 
send /sell cactus

Instead of it waiting 120 seconds it just sells every like 16 seconds...

**Comment by ORelio** [comment]
For legacy reasons 10 is roughly about 1 second son juste add a zero to your values ;)
