### ISSUE TITLE
Firework crash

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1221]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

Version 1.15.2
![image](https://user-images.githubusercontent.com/35975332/90563268-fa708200-e1bc-11ea-82a3-be8e9f051b26.png)

**Comment by Nekiplay** [comment]
This crash appeared after the launch of Firework

**Comment by Nekiplay** [comment]
Resolved

**Comment by ORelio** [comment]
Likely fixed in #1227
