### ISSUE TITLE
Digging blocks up to 5 blocks away

### ISSUE THREAD

**Issue by Turururshka** [ORelio/Minecraft-Console-Client#1228]
Hello
When I put the bot on the coordinates to dig the upper blocks for me, it started to dig only 3 blocks each (standing on the hatch). Can I do the same as with the regular version of minecraft so that it can dig up 5 blocks? I do not know if you understood, because I wrote in the translator: 0

**Comment by ORelio** [comment]
OK, found it: https://github.com/ORelio/Minecraft-Console-Client/blob/4cc29a6ee662613eb3e4d916cc5bda3f699a029a/MinecraftClient/Commands/Dig.cs#L30
Will change this check to `> 25` to allow up to 5 blocks away (distance squared: `5²`=`5*5`=`25`)

**Comment by ORelio** [comment]
Done! Please try out the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by ReinforceZwei** [comment]
Simply changing the player digging range would work but I think adding 1 to the y-axis of player location could be better. Player mining range is calculated from player's head coordinate while the location of player we have is player's feet, hence causing the incorrect range check result.

**Comment by ORelio** [comment]
Indeed. More exactly, it's 1.62 (https://wiki.vg/Protocol#Player_Position_And_Rotation_.28serverbound.29)

**Comment by Sorfab** [comment]
Hello, do I understand correctly what needs to be done like that? But when I run the script, it says that "Invalid" switch "token in the declaration of a class, structure or interface"

**Comment by Sorfab** [comment]
[MinecraftClient.txt](https://github.com/ORelio/Minecraft-Console-Client/files/5220953/MinecraftClient.txt)
