### ISSUE TITLE
BOT failed to connect to the server (Aegis fallcheck) 

### ISSUE THREAD

**Issue by telfrancesco** [ORelio/Minecraft-Console-Client#1231]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
When a server have aegis or a fallcheck, bot can't connect to the server.
I use Linux (Ubuntu 18.04) 
![Screenshot_18](https://user-images.githubusercontent.com/22562779/90984034-bc83ad00-e572-11ea-93a3-7a67b41713fa.png)

**Comment by ReinforceZwei** [comment]
Your server has anti-bot plugin installed so you can only use vanilla Minecraft client to login your server.

**Comment by telfrancesco** [comment]
I do not understand

**Comment by telfrancesco** [comment]
I need use minecraftconsoleclient for my alt, but fallcheck can't connect to him

**Comment by ReinforceZwei** [comment]
MinecraftConsoleClient is BOT client and your server refused BOT client to connect so you cannot use MinecraftConsoleClient to login your alt.

**Comment by telfrancesco** [comment]
would a fall check bypass be so hard to make?

**Comment by ReinforceZwei** [comment]
MCC has fall mechanism. You need to set `terrainanandmovements` to true in `MinecraftClient.ini` file. But in the kick message, I can see it also have knock back check.

MCC doesn't have knock back support so even though you bypassed the fall check, the knock back check still kicks you out.

**Comment by telfrancesco** [comment]
ok, fixxed

**Comment by Nekiplay** [comment]
Also, for this, you need to finish processing the Map Item to process the image from the map to which the captcha is mainly written
