### ISSUE TITLE
Current version of MCC can't handle modded item

### ISSUE THREAD

**Issue by interesting-233** [ORelio/Minecraft-Console-Client#1232]
the older version can handle, now it can't
![image](https://user-images.githubusercontent.com/61296195/91052297-d9dc7800-e653-11ea-9a66-9924cf4a8b6f.png)

**Comment by ReinforceZwei** [comment]
Indeed. I changed the way to get the ItemType but forgot about forge. My bad.

**Comment by ORelio** [comment]
Thanks @ReinforceZwei for the fix. Note: Although MCC will now correctly ignore custom items, manipulating them using /inventory will likely not work because of custom item IDs not being handled in the current form of the program.
