### ISSUE TITLE
HTTPS Proxy

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1245]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Can HTTPS proxy be used and will it be available in the future?

**Comment by ORelio** [comment]
MCC is using a library for proxy handling, but that library is open source. You might be able to add HTTPS support by overriding [HttpProxyClient](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Proxy/Handlers/HttpProxyClient.cs) and rewriting its `CreateConnection` method to handle HTTPS. You can have a look to `DoHTTPSRequest` inside [ProtocolHandler](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs) for an example on how to add TLS layer on a socket.
