### ISSUE TITLE
I need a solution

### ISSUE THREAD

**Issue by Ramy-D** [ORelio/Minecraft-Console-Client#1247]
**Prerequisites**
 - [x ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

Yo i try to open /inventory with useitem.. in the beggining. But first time when i use /useitem to open /inventory. I got this... 

>/useitem
[MCC] Used an item
[MCC] Inventory # 2 opened: » LOBBY SELECTOR
[MCC] Use /inventory to interact with it.
[MCC] Inventory # 2 closed.

He close alone...

**Comment by ORelio** [comment]
That's weird indeed. MCC does not close the inventory itself, the server must have auto-closed it for some reason 🤔

**Comment by AddictedCrew** [comment]
And is a solution to do something ?

**Comment by ORelio** [comment]
I currently have no idea on why your server would close the inventory or what to do to avoid this, so I'm leaving your question open.

**Comment by Ramy-D** [comment]
UP ?

**Comment by ReinforceZwei** [comment]
Hi, could you provide the server ip that you have encountered this problem?

**Comment by Ramy-D** [comment]
188.212.101.69:25565 This one.

**Comment by ReinforceZwei** [comment]
After using the debug proxy program by ORelio, I found that the server sent the client open inventory twice. The first open inventory is then closed by server, after that a second open inventory which is the actual inventory. I don't see any obvious reason that might cause this problem.

**Comment by Ramy-D** [comment]
So i cant use /inventory 0 click ?

**Comment by ReinforceZwei** [comment]
Unfortunately yes.

I have noticed that the server is multi-version compatible. Maybe you could try to specify a low Minecraft version (i.e. 1.9) in the MinecraftClient.ini file and try again.

**Comment by Ramy-D** [comment]
Same... Try please.
/useitem 
/inventory 1 click 36

At u working ?

**Comment by ReinforceZwei** [comment]
Okay then please wait for the fix.

**Comment by Ramy-D** [comment]
Ok, thank you ReinforceZwei

**Comment by ReinforceZwei** [comment]
Sorry for late reply. I finally have some time to work on this issue. After doing more test, comparing with vanilla client, I found that simply enable `terrainandmovements` solved the issue. Probably server have some bot detection. Anyway, @Ramy-D you just need to set `terrainandmovements=true` in the `MinecraftClient.ini` file and you can use the selector normally.

**Comment by Ramy-D** [comment]
Thank you @ReinforceZwei
