### ISSUE TITLE
WorldDownloader

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1248]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

[Source](https://github.com/Pokechu22/WorldDownloader)

**Comment by ORelio** [comment]
The hardest part in this would be implementing support for writing chunk files and storing data as soon as it is received from the server. Currently, MCC parses chunk data directly upon receive from server, but does not keep everything. As a result, saving the inner representation to chunk files would lead to an inaccurate representation of the Minecraft world.

**Comment by Pokechu22** [comment]
Furthermore, you'd need to deal with changing world data representations across different versions (including block entities, which can cause issues if they're not saved properly in some versions).  Saving block entity content would add more complexity too.  And there's the region-file level of saving (including compression) in addition to the chunk level.  WDL benefits from being able to use existing Minecraft code to handle most of this, but implementing it in MCC would require redoing it all yourself.

**Comment by konata2027** [comment]
Just use this world downloader
https://github.com/mircokroon/minecraft-world-downloader

**Comment by ORelio** [comment]
Why reinventing the wheel when you can just use this. Seems to respond to the need expressed in this issue 👍
