### ISSUE TITLE
how to save chat logs

### ISSUE THREAD

**Issue by Devilz123-hash** [ORelio/Minecraft-Console-Client#1251]
im a staff member in a minecraft server and im using the console client and i wanted it save chat logs but i can't figure it out 
can someone tell me how to do that?
and i got a problem with my internet keeps cutting out every few hours and it takes like 2-5 mins to come back i set the auto reconnect to 2.5 mins but i wanted it to retry to reconnect after few mins if it failed

**Comment by ORelio** [comment]
Enable the ChatLog bot in configuration with `enabled=true`
If chat messages are not correctly detected, see [detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages).
