### ISSUE TITLE
Arm animation when breaking blocks

### ISSUE THREAD

**Issue by Gewi549** [ORelio/Minecraft-Console-Client#1254]
I play on a skyblock server (with ore spawn)
Is it possible to make him click ore or hold down the left mouse button

**Comment by ReinforceZwei** [comment]
Yes, you may refer to this [stone miner script](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs) sample and make your own modification.

**Comment by Gewi549** [comment]
> Да, вы можете обратиться к этому [примеру скрипта](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs) добычи [камня](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs) и внести свои изменения.

Yes, I have already tried it, but the problem is that if the bot digs without animation, then I will get a ban on the server

**Comment by ReinforceZwei** [comment]
For the animation, you can use `SendAnimation()`.

**Comment by Gewi549** [comment]
> For the animation, you can use `SendAnimation()`.

I do not really understand, could not tell where to write this

**Comment by ReinforceZwei** [comment]
Try to put it at the end of `Update()`

**Comment by Gewi549** [comment]
> Try to put it at the end of `Update()`

Sorry, but I don't understand this topic at all.
I have in the folder:
lang
Minecrft Client
Minecraft Client.ini
MinecraftClient.pdb
Which of these folders do I need to open and write this code

**Comment by ReinforceZwei** [comment]
First you need to create a new file `oreminer.cs`, paste the content of example script that I mentioned above into that new file, make your modification and save it.

**Comment by Gewi549** [comment]
> Сначала вам нужно создать новый файл `oreminer.cs`, вставить содержимое примера сценария, который я упомянул выше, в этот новый файл, внести изменения и сохранить его.

Thanks, I'll try now

**Comment by Gewi549** [comment]
> First you need to create a new file `oreminer.cs`, paste the content of example script that I mentioned above into that new file, make your modification and save it.



> First you need to create a new file `oreminer.cs`, paste the content of example script that I mentioned above into that new file, make your modification and save it.

I added the necessary ores, launched the bot, wrote / script oreminer.cs
and nothing happens

**Comment by ReinforceZwei** [comment]
Did you set the location of the ore at [this line](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs#L12)?

**Comment by Gewi549** [comment]
> Did you set the location of the ore at [this line](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs#L12)?

No, here https://github.com/ORelio/Minecraft-Console-Client/blob/9bfb2bf6c7b6d6c016724a1ce2ba0e8dfef634d6/MinecraftClient/config/ChatBots/CobblestoneMiner.cs#L25

**Comment by Gewi549** [comment]
> Did you set the location of the ore at [this line](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs#L12)?

Could you please write some code for me?
Or is it too long

**Comment by ReinforceZwei** [comment]
You need to give the exact coordinate of the ore.
```cs
Location cobblestone = new Location(16, 64, -128); // for example
```

**Comment by Gewi549** [comment]
> You need to give the exact coordinate of the ore.
> 
> ```cs
> Location cobblestone = new Location(16, 64, -128); // for example
Nothing works for me. Apparently this is not for me

**Comment by Gewi549** [comment]
> You need to give the exact coordinate of the ore.
> 
> ```cs
> Location cobblestone = new Location(16, 64, -128); // for example
> ```

How to make it just click many many times endlessly

**Comment by ORelio** [comment]
Maybe we could automatically perform the animation directly in DigBlock()?
https://github.com/ORelio/Minecraft-Console-Client/blob/7e20e409a890d15d18ff3bb05b1310107241ec6a/MinecraftClient/McClient.cs#L1406-L1422
With an optional parameter like `bool withAnimation = true` to allow disabling the animation.

**Comment by Gewi549** [comment]
> Maybe we could automatically perform the animation directly in DigBlock()?
> https://github.com/ORelio/Minecraft-Console-Client/blob/7e20e409a890d15d18ff3bb05b1310107241ec6a/MinecraftClient/McClient.cs#L1406-L1422
> 
> 
> With an optional parameter like `bool withAnimation = true` to allow disabling the animation.

where to write it down

**Comment by Gewi549** [comment]
> Maybe we could automatically perform the animation directly in DigBlock()?
> https://github.com/ORelio/Minecraft-Console-Client/blob/7e20e409a890d15d18ff3bb05b1310107241ec6a/MinecraftClient/McClient.cs#L1406-L1422
> 
> 
> With an optional parameter like `bool withAnimation = true` to allow disabling the animation.

with this code it will dig down (under itself)

**Comment by Gewi549** [comment]
> Maybe we could automatically perform the animation directly in DigBlock()?
> With an optional parameter like `bool withAnimation = true` to allow disabling the animation.
how to apply it?

**Comment by ORelio** [comment]
Done. Please try out the latest dev build 😉

**Comment by Sorfab** [comment]
Hello, do I understand correctly what needs to be done like that? But when I run the script, it says that "Invalid" switch "token in the declaration of a class, structure or interface"


  ```
  public override void Initialize()
    {
        LogToConsole("Bot enabled!");
    }

    public override void Update()
    {
        Material blockType = GetWorld().GetBlock(cobblestone).Type;
        switch (blockType)
        {
            case Material.Stone:
                DigBlock(cobblestone);
                break;
            case Material.Cobblestone:
                DigBlock(cobblestone);
                break;
        }
    }	Material blockType = GetWorld().GetBlock(diamondore).Type;
        switch (blockType)
        {
            case Material.diamondore:
                DigBlock(diamond);
                break;
		}
		Material blockType = GetWorld().GetBlock(emeraldore).Type;
        switch (blockType)
        {
            case Material.emeraldore:
                DigBlock(emerald);
                break;
		}
		Material blockType = GetWorld().GetBlock(goldore).Type;
        switch (blockType)
        {
            case Material.goldore:
                DigBlock(goldore);
                break;
		}
		Material blockType = GetWorld().GetBlock(ironore).Type;
        switch (blockType)
        {
            case Material.ironore:
                DigBlock(ironore);
                break;
		}
		Material blockType = GetWorld().GetBlock(coalore).Type;
        switch (blockType)
        {
            case Material.coalore:
                DigBlock(coal);
                break;
		}
		Material blockType = GetWorld().GetBlock(lapisore).Type;
        switch (blockType)
        {
            case Material.lapisore:
                DigBlock(lapis);
                break;
		}
		Material blockType = GetWorld().GetBlock(redstoneore).Type;
        switch (blockType)
        {
            case Material.redstoneore:
                DigBlock(redstonel);
                break;
		}
		Material blockType = GetWorld().GetBlock(netherquartzore).Type;
        switch (blockType)
        {
            case Material.netherquartzore:
                DigBlock(quartz);
                break;
		}
```

**Comment by ReinforceZwei** [comment]
@Sorfab Your script is incorrect. I wrote the script for you. Copy and paste the below code to your script file. Remember to change the block location (x, y, z)
```cs
//MCCScript 1.0

MCC.LoadBot(new OreMiner());

//MCCScript Extensions

public class OreMiner: ChatBot
{
    // === CONFIG - REPLACE BLOCK LOCATION x y z VALUES HERE ===
    Location location = new Location(x, y, z);
    // === END OF CONFIG ===

    public override void Initialize()
    {
        LogToConsole("Bot enabled!");
    }

    public override void Update()
    {
        Material blockType = GetWorld().GetBlock(location).Type;
        switch (blockType)
        {
            case Material.DiamondOre:
            case Material.EmeraldOre:
            case Material.GoldOre:
            case Material.IronOre:
            case Material.CoalOre:
            case Material.LapisOre:
            case Material.RedstoneOre:
            case Material.NetherQuartzOre:
                DigBlock(location);
                break;
        }
    }
}
```

**Comment by Sorfab** [comment]
@ReinforceZwei Thank you, now he is digging, but there is a problem that quartz does not react, and when quartz is generated, he just looks at it. And please tell me how to make it dig into 5 blocks and not 1?

**Comment by Sorfab** [comment]
> @Sorfab Your script is incorrect. I wrote the script for you. Copy and paste the below code to your script file. Remember to change the block location (x, y, z)
> 
> ```cs
> //MCCScript 1.0
> 
> MCC.LoadBot(new OreMiner());
> 
> //MCCScript Extensions
> 
> public class OreMiner: ChatBot
> {
>     // === CONFIG - REPLACE BLOCK LOCATION x y z VALUES HERE ===
>     Location location = new Location(x, y, z);
>     // === END OF CONFIG ===
> 
>     public override void Initialize()
>     {
>         LogToConsole("Bot enabled!");
>     }
> 
>     public override void Update()
>     {
>         Material blockType = GetWorld().GetBlock(location).Type;
>         switch (blockType)
>         {
>             case Material.DiamondOre:
>             case Material.EmeraldOre:
>             case Material.GoldOre:
>             case Material.IronOre:
>             case Material.CoalOre:
>             case Material.LapisOre:
>             case Material.RedstoneOre:
>             case Material.NetherQuartzOre:
>                 DigBlock(location);
>                 break;
>         }
>     }
> }
> ```

The problem with quartz was solved by the fact that instead of 1.12.2 I changed the version to 1.14.4, but I still did not figure out how to make 5 blocks to dig. Can you please tell me where to add block coordinates or how to do directional digging. Thank you in advance

**Comment by ReinforceZwei** [comment]
@Sorfab Sorry I don't understand what you mean by 5 block to dig. Do you mean dig a row of 5 blocks?

**Comment by Sorfab** [comment]
> @Sorfab Sorry I don't understand what you mean by 5 block to dig. Do you mean dig a row of 5 blocks?

yes

**Comment by Nekiplay** [comment]
> > @Sorfab Sorry I don't understand what you mean by 5 block to dig. Do you mean dig a row of 5 blocks?
> 
> yes

https://github.com/ORelio/Minecraft-Console-Client/issues/1047

**Comment by ReinforceZwei** [comment]
@Sorfab Here is the updated version of script. I didn't test it so please tell me if the script doesn't work.
```cs
//MCCScript 1.0

MCC.LoadBot(new OreMiner());

//MCCScript Extensions

public class OreMiner: ChatBot
{
    // === CONFIG - REPLACE BLOCK LOCATION x y z VALUES HERE ===
    List<Location> location = new List<Location>()
    {
        new Location(x, y, z),
        new Location(x2, y2, z2),
        new Location(x3, y3, z3),
        // Add more here
    };
    // === END OF CONFIG ===
    int index = 0;

    public override void Initialize()
    {
        LogToConsole("Bot enabled!");
    }

    public override void Update()
    {
        Material blockType = GetWorld().GetBlock(location[index]).Type;
        switch (blockType)
        {
            case Material.DiamondOre:
            case Material.EmeraldOre:
            case Material.GoldOre:
            case Material.IronOre:
            case Material.CoalOre:
            case Material.LapisOre:
            case Material.RedstoneOre:
            case Material.NetherQuartzOre:
                DigBlock(location[index]);
                break;
        }
        index++;
        if (index >= location.Count)
            index = 0;
    }
}
```

**Comment by LilSadPanda** [comment]
Script to break all blocks in that location?

**Comment by Sorfab** [comment]
> @Sorfab Here is the updated version of script. I didn't test it so please tell me if the script doesn't work.
> 
> ```cs
> //MCCScript 1.0
> 
> MCC.LoadBot(new OreMiner());
> 
> //MCCScript Extensions
> 
> public class OreMiner: ChatBot
> {
>     // === CONFIG - REPLACE BLOCK LOCATION x y z VALUES HERE ===
>     List<Location> location = new List<Location>()
>     {
>         new Location(x, y, z),
>         new Location(x2, y2, z2),
>         new Location(x3, y3, z3),
>         // Add more here
>     };
>     // === END OF CONFIG ===
>     int index = 0;
> 
>     public override void Initialize()
>     {
>         LogToConsole("Bot enabled!");
>     }
> 
>     public override void Update()
>     {
>         Material blockType = GetWorld().GetBlock(location[index]).Type;
>         switch (blockType)
>         {
>             case Material.DiamondOre:
>             case Material.EmeraldOre:
>             case Material.GoldOre:
>             case Material.IronOre:
>             case Material.CoalOre:
>             case Material.LapisOre:
>             case Material.RedstoneOre:
>             case Material.NetherQuartzOre:
>                 DigBlock(location[index]);
>                 break;
>         }
>         index++;
>         if (index >= location.Count)
>             index = 0;
>     }
> }
> ```


everything works fine, thanks a lot
