### ISSUE TITLE
Cobblestone Miner ChatBot fails after script is executed twice

### ISSUE THREAD

**Issue by calebh44** [ORelio/Minecraft-Console-Client#1255]
Hello, I am playing on a server, and the when the ChatBot cobbleminer is executed once, everything runs fine and cobblestone is mined, however, when executing it a second time in the same session, the cobblestone only half-breaks then the bot goes back to trying to mine it again. I hope there can be a fix for this, and if you need me to give any more info let me know. Sorry, English is not my first language and I am not familiar with this site

**Comment by ORelio** [comment]
That's because when relogging the bots are not unloaded so you loaded it twice, they likely conflict with each other.

**Comment by calebh44** [comment]
Ah. That make sense. How would you go about unloading the bot? before the script is executed to ensure there are no other instances of it running

**Comment by ReinforceZwei** [comment]
You can override the `OnDisconnect()` event and call `UnloadBot()` in it.

**Comment by calebh44** [comment]
Hi, bear with me as I have no C# experience. 

I have added a 

`    public virtual bool OnDisconnect()
	{
		 ChatBot.UnloadBot();
	}`
but return the error that ChatBot.UnloadBot is unaccessible due to its protection level.

Thank you for the quick reply

**Comment by ReinforceZwei** [comment]
The below code should work.
```cs
public override bool OnDisconnect(DisconnectReason reason, string message)
{
    UnloadBot();
    return false;
}
```

**Comment by calebh44** [comment]
Thanks. You are incredible.

**Comment by ORelio** [comment]
Good idea! Alternatively, I think you are launching the script using ScriptScheduler, in that case, you can also use `triggerOnFirstLogin` instead of `triggerOnLogin` to launch the script only once.
