### ISSUE TITLE
Install Minecraft mods in MCC

### ISSUE THREAD

**Issue by marsman233** [ORelio/Minecraft-Console-Client#1259]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Is there a feature that let us to install custom mod and control it by using the command line( if it can )
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

**Comment by ReinforceZwei** [comment]
MCC doesn't support installing mods.

May I ask what kind of mods you want to install? forge or something else?

**Comment by marsman233** [comment]
> MCC doesn't support installing mods.
> 
> May I ask what kind of mods you want to install? forge or something else?

hypixel skyblock assist mod that allow me to do "robot" like things to make money whan i am not able to be online xD

**Comment by ReinforceZwei** [comment]
It is not possible to install any kinds of mods to MCC as they are designed for vanilla Minecraft client.

**Comment by marsman233** [comment]
> It is not possible to install any kinds of mods to MCC as they are designed for vanilla Minecraft client only.

there is replay mod built in so there must be some way to install mods

**Comment by ReinforceZwei** [comment]
> there is replay mod built in so there must be some way to install mods

The replay mod was integrated into MCC code-base by hand, meas that it is not "installed" into MCC by few clicks but a re-wrote code that can be used by MCC. 

If you really want that mod, you may integrate the mod yourself by writing codes for MCC.

**Comment by marsman233** [comment]
> > there is replay mod built in so there must be some way to install mods
> 
> The replay mod was integrated into MCC code-base by hand, meas that it is not "installed" into MCC by few clicks but a re-wrote code that can be used by MCC.
> 
> If you really want that mod, you may integrate the mod yourself by writing codes for MCC.

i find a setting in the minecraftclient.ini file generated by mcc
`mcforge=true                       # Use 'auto' or 'false'`
maybe this have some kind of connection with forge ?

**Comment by ReinforceZwei** [comment]
This allow you to log into a forge server without really having all required mods (since MCC cannot install mods).

**Comment by ORelio** [comment]
To make it clear: There are **no Minecraft mods** in MCC, and never will.

Minecraft Console Client is a custom C# client created from scratch. Minecraft is in Java and Mods make use of existing code in Minecraft so you can't install them at all in MCC. What you are seeing in MCC is support for some common mods reimplemented in C# by the MCC team. Forge support in MCC does not actually support Forge mods, it just fakes the mod list expected by the server to pass the login check and join the server anyway. That won't work on some servers depending on the mods. Replay mod support is custom code for generating replay files in the correct format for opening with the official Replay mod.

We are open to suggestions for improving MCC, but we have few contributors so we can't implement everything.
On a side note, MCC provides its own API so people can write C# "mods" in the form of ChatBot script files.

**Comment by LowScripters** [comment]
> MCC doesn't support installing mods.
> 
> May I ask what kind of mods you want to install? forge or something else?

What about baritone? Maybe there will be some kind of “garter” implementation for such mods?

**Comment by breadbyte** [comment]
> > MCC doesn't support installing mods.
> > 
> > May I ask what kind of mods you want to install? forge or something else?
> 
> What about baritone? Maybe there will be some kind of “garter” implementation for such mods?


There are no plans at the moment to implement any kind of support or connectivity/bridge with Forge/Fabric mods, and we don't have enough contributors for such a feature anyway. 

It is quite literally translating from one language to another, and is not such a simple task to achieve.
