### ISSUE TITLE
Console not outputting internal commands

### ISSUE THREAD

**Issue by OverHash** [ORelio/Minecraft-Console-Client#1260]
**Prerequisites**
 - [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [X] I have set `debugmessages=true` in config to diagnose my issue
 - [X] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
Basically I cannot see any of the output from commands such as /help. I am able to see server messages, and things like the timestamp are correctly outputting.
![image](https://user-images.githubusercontent.com/46231745/93447042-0ff4db00-f926-11ea-8999-a4e0577790ec.png)

This is ran inside a screen session on linux w/ mono. Details about my mono here:
![image](https://user-images.githubusercontent.com/46231745/93447094-21d67e00-f926-11ea-8b5e-34e4553604ec.png)

How can I debug this issue?

**Comment by ReinforceZwei** [comment]
This is console issue. Seems like you are using putty. Putty default output gray colour as black (stupid design). You can change it to other colour and you will see those invisible text.

**Comment by OverHash** [comment]
Yeah, I am using PuTTy. Is there a way to configure MCC to output different color? Or is it easier to adjust my PuTTy. I would prefer not to adjust my PuTTy.

**Comment by ReinforceZwei** [comment]
I think you should just change your putty's setting since it is a issue about the console colour setting.

**Comment by OverHash** [comment]
Do you know what color setting I have to adjust? The options are
```
Default Foreground
Default Bold Foreground
Default Background
Default Bold Background
Cursor Text
Cursor Colour
ANSI Black
ANSI Black Bold
ANSI Red
ANSI Red Bold
ANSI Green
ANSI Green Bold
ANSI Yellow
ANSI Yellow Bold
ANSI Blue
ANSI Blue Bold
ANSI Magenta
ANSI Magenta Bold
ANSI Cyan
ANSI Cyan Bold
ANSI White
ANSI White Bold
```

**Comment by ReinforceZwei** [comment]
```
ANSI Black
ANSI Black Bold
```
Set those two colors to some visible color.

**Comment by OverHash** [comment]
Thanks!
