### ISSUE TITLE
Where to find digging speed calculations when using efficiency or effects

### ISSUE THREAD

**Issue by NikitaLik** [ORelio/Minecraft-Console-Client#1266]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**

Where to find digging speed calculations when using efficiency or effects?

**Comment by ReinforceZwei** [comment]
Maybe take a look at the [wiki](https://minecraft.gamepedia.com/Breaking)?

**Comment by Denaryplanet** [comment]
> Maybe take a look at the [wiki](https://minecraft.gamepedia.com/Breaking)?

I tried, but for some reason the bot digs faster

**Comment by ReinforceZwei** [comment]
If you are talking about the digging speed of MCC bot, MCC didn't implement the digging "cooldown". Meaning that MCC bot will always dig with a constant speed regardless the tools or the blocks.

**Comment by ORelio** [comment]
See https://wiki.vg/How_to_Write_a_Client#Digging
