### ISSUE TITLE
How to get current server TPS

### ISSUE THREAD

**Issue by CheesyBC** [ORelio/Minecraft-Console-Client#1268]
I would like to make a in game command so players can do @tps and get "The current tps is (tps)" but I'm not sure what to put in my script to fetch the tps. I know that ping is GetPlayersLatency

**Comment by ReinforceZwei** [comment]
Assuming you are using ChatBot. You may use `GetServerTPS()` method.

**Comment by CheesyBC** [comment]
ok thanks :)

**Comment by CheesyBC** [comment]
I forgot to mention, how would I go about sending the output of this to SendText

**Comment by ReinforceZwei** [comment]
`SendText("Server TPS is: " + GetServerTPS().ToString())` I guess?

**Comment by ORelio** [comment]
You don't even need `.ToString()` because concatenating non-string object to a string will automatically call `.ToString()` 😉
