### ISSUE TITLE
Ping error

### ISSUE THREAD

**Issue by LuukOriginal** [ORelio/Minecraft-Console-Client#1269]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

**Comment by LuukOriginal** [comment]
I can't connect to a server (from inside visual studio),
settings script:
`        public static string Login = "";
        public static string Username = "LuukTest";
        public static string Password = "";
        public static string ServerIP = "78.47.31.237:24416";
        public static ushort ServerPort = 25565;
        public static string ServerVersion = "1.16.3";
        public static bool ServerMayHaveForge = true;
        public static string SingleCommand = "";
        public static string ConsoleTitle = "";`


![image](https://user-images.githubusercontent.com/51383330/94604541-255bf480-0298-11eb-8aa0-11bf107a01f2.png)
all information in the settings script is correct, I am sure, also the console says a totally different IP then the one in the settings

**Comment by ReinforceZwei** [comment]
You need to change the debug setting of Visual Studio. _My VS is not in English. I am sorry for that._
Inside the Project tab, click on the last item
![](https://user-images.githubusercontent.com/39955851/94679884-6c5af000-0353-11eb-8cd6-6d5fed8e8c5a.png)

Then click on the Debug tab, and modify the content in that red circle. In your case you may delete them.
![](https://user-images.githubusercontent.com/39955851/94680222-f7d48100-0353-11eb-860b-91b445961cb3.png)

Press Ctrl+S save it, try again and it should work.

**Comment by LuukOriginal** [comment]
Thnx, this helped, also I have another question: 
![image](https://user-images.githubusercontent.com/51383330/94970038-14afb680-0504-11eb-98d6-58ac8cee11d0.png)
where does the Â come from in the Gui version? and how could I get rid of it?

**Comment by ORelio** [comment]
Seems like an encoding issue for color codes. Output from MCC is UTF-8 but maybe your console is not set to UTF-8?
