### ISSUE TITLE
This program is really great, we have sinicized this project, and now we plan to publish it to mcbbs(China's Biggest Minecraft Forum). Is that ok

### ISSUE THREAD

**Issue by 1689295608** [ORelio/Minecraft-Console-Client#1271]
This program is really great, we have sinicized this project, and now we plan to publish it to mcbbs(China's Biggest Minecraft Forum). Is that ok

**Comment by ReinforceZwei** [comment]
This question has been asked before. Please see #1039

**Comment by 1689295608** [comment]
What I mean is: we have this project in Chinese culture and want to post on MCBBS again

**Comment by ReinforceZwei** [comment]
I saw your friend's post and I will continue discuss on your friend's post. You may close this issue.

**Comment by 1689295608** [comment]
啊这！

**Comment by ORelio** [comment]
It would be best to implement translation support and add Chinese translation. Less work for you in the long run 😉
Here's a sample class I wrote in the past for that:
https://github.com/ORelio/Sharp-Tools/blob/master/Utility/Translations.cs

**Comment by 1689295608** [comment]
I'm sorry. I'm not good at C#. I don't think I can do it...

**Comment by ORelio** [comment]
@1689295608 I did not though you were just changing the text without touching the code. Makes sense.
@ReinforceZwei is interested on working on this. Discussion continued in ▶️ #1272
