### ISSUE TITLE
How to code a script?

### ISSUE THREAD

**Issue by NiceCraftz** [ORelio/Minecraft-Console-Client#1274]
I am quite struggling, I installed the .exe file and logged in then closed it and went into the configuration file and enabled the terrain movement but it's not working, am I doing something wrong? could you help me? Thanks

**Comment by NiceCraftz** [comment]
also, i would like so the ConsoleClient can move in the AFK pool, I don't want him to be still cuz the admin could see.

**Comment by NiceCraftz** [comment]
how can I make so the player moves around the AFK pool? i don't see anything about the scripting

**Comment by ORelio** [comment]
Hi,
1. Help and sample files are here: https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config
2. Minecraft Console Client doesn't handle water flows. Just schedule a script with a few `move` instructions instead.
3. To schedule a script... see help and sample files 😉

**Comment by NiceCraftz** [comment]
still haven't figured it out how to make a script in 16 hours ;_;

**Comment by ORelio** [comment]
put your instructions in a text file then user `/script myscript.txt`
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.txt
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#internal-commands

**Comment by NiceCraftz** [comment]
Hi, I am quite trying to do this but making the player move in the afk pool is hard, when I come back home I'll make a video and show you the problem that I can't fix. Thank you in advance.

**Comment by ORelio** [comment]
You don't need to be in a pool. Just stand on ground and do something like this:
```
move east
move west
```
The player will move a bit then go back to its initial location.

**Comment by NiceCraftz** [comment]
It's in Hypixel SkyBlock and they detect movement if not in a water source.

**Comment by ORelio** [comment]
Are you supposed not to move as you play normally? 😅

**Comment by NiceCraftz** [comment]
I need to move or antiafk will kick me, is there a way to make water movement work?

**Comment by ORelio** [comment]
No, it is not implemented at the moment. MCC would need to analyze water flows and calculate movements by itself.
But I see no reason why you would not be able to `/move` instead. `/move` is an internal MCC command for moving. Like when you move using the vanilla Minecraft client. Of course this will make the AntiAFK believe you are still active.
