### ISSUE TITLE
proxy stopped working, bad request 400

### ISSUE THREAD

**Issue by slaapkopamy** [ORelio/Minecraft-Console-Client#1276]
**Prerequisites**
 - [x ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x ] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [ x] I have set `debugmessages=true` in config to diagnose my issue
 - [ x] I have redacted session tokens and passwords before attaching screenshots

Hi there,

I got since this week problems with the console client logging in with a proxy server it spits out a 400 error named bad request but im not sure how to solve this since my proxy just worked when im using curl...

`Console Client for MC 1.4.6 to 1.16.1 - v1.16.1 - By ORelio & Contributors
AppVeyor build 375, built on Fri 08/14/2020 from commit 4a3a23e
[MCC] [Settings] Loading Settings from C:\Users\Administrator\Desktop\test\MinecraftClient.ini
Resolving serverip.example.com...
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
[SessionCache] Initializing FileSystemWatcher for file: C:\Users\Administrator\Desktop\test\SessionCache.ini
No sessions could be loaded from disk
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
Connected to proxy x.x.x.x:3128
Proxy destination x.x.x.x on port 3128 responded with a 400 code - Bad Request
System.Net.Sockets.SocketException (0x80004005): A socket operation was attempted to an unreachable host
   at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSRequest(List`1 headers, String host, String& result)
   at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSPost(String host, String endpoint, String request, String& result)
   at MinecraftClient.Protocol.ProtocolHandler.GetLogin(String user, String pass, SessionToken& session)
Minecraft Login failed : Network error.
[MCC] [AutoRelog] Launching with 3 reconnection attempts`

my config looks like this:
`# Minecraft Console Client v1.16.1
# Startup Config File

[Main]

# General settings
# Leave blank to prompt user on startup
# Use "-" as password for offline mode

login=email@example.com
password=passwd
serverip=serverip.example.com

# Advanced settings

language=en_GB
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash              # Use 'none', 'slash' or 'backslash'
splitmessagedelay=2                # Seconds between each part of a long message
botowners=player1  # Name list or myfile.txt, one name per line. !Server admins can impersonate owners!
botmessagedelay=2                  # Seconds to delay between message a bot makes to avoid accidental spam
mcversion=auto                     # Use 'auto' or '1.X.X' values
mcforge=auto                       # Use 'auto' or 'false'
brandinfo=mcc                      # Use 'mcc','vanilla', or 'none'
chatbotlogfile=                    # Leave empty for no logfile
privatemsgscmdname=tell            # Used by RemoteControl bot
showsystemmessages=true            # System messages for server ops
showxpbarmessages=true             # Messages displayed above xp bar
showchatlinks=true                 # Show links embedded in chat messages
terrainandmovements=false          # Uses more ram, cpu, bandwidth
inventoryhandling=false            # Toggle inventory handling (beta)
entityhandling=false               # Toggle entity handling (beta)
sessioncache=disk                  # How to retain session tokens. Use 'none', 'memory' or 'disk'
resolvesrvrecords=fast             # Use 'false', 'fast' (5s timeout), or 'true'. Required for joining some servers.
accountlist=accounts.txt           # See README > 'Servers and Accounts file' for more info about this file
serverlist=servers.txt             # See README > 'Servers and Accounts file' for more info about this file
playerheadicon=true                # Only works on Windows XP-8 or Windows 10 with old console
exitonfailure=false                # Disable pauses on error, for using MCC in non-interactive scripts
debugmessages=true                # Please enable this before submitting bug reports. Thanks!
scriptcache=true                   # Cache compiled scripts for faster load on low-end devices
timestamps=false                   # Prepend timestamps to chat messages
autorespawn=false                  # Toggle auto respawn if client player was dead (make sure your spawn point is safe)

[AppVars]
# yourvar=yourvalue
# can be used in some other fields as %yourvar%
# %username% and %serverip% are reserved variables.

[Proxy]
enabled=login
type=HTTP
server=x.x.x.x:3128
username=proxyusername
password=proxypasswd

[ChatFormat]
# Do not forget to uncomment (remove '#') these settings if modifying them
builtins=true                      # MCC built-in support for common message formats
public=^<([a-zA-Z0-9_]+)> (.+)$
private=^([a-zA-Z0-9_]+) whispers to you: (.+)$
tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

[MCSettings]
enabled=true                       # If disabled, settings below are not sent to the server
locale=en_US                       # Use any language implemented in Minecraft
renderdistance=medium              # Use tiny, short, medium, far, or chunk amount [0 - 255]
difficulty=normal                  # MC 1.7- difficulty. peaceful, easy, normal, difficult
chatmode=enabled                   # Use 'enabled', 'commands', or 'disabled'. Allows to mute yourself...
chatcolors=true                    # Allows disabling chat colors server-side
main_hand=left                     # MC 1.9+ main hand. left or right
skin_cape=true
skin_hat=true
skin_jacket=false
skin_sleeve_left=false
skin_sleeve_right=false
skin_pants_left=false
skin_pants_right=false
# Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=false
delay=600 #10 = 1s
command=/ping

[AutoRelog]
enabled=true
delay=120
retries=3 #-1 = unlimited
ignorekickmessage=false
kickmessagesfile=kickmessages.txt

[ChatLog]
enabled=false
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=false
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=true
tasksfile=tasks.ini

[RemoteControl]
enabled=true
autotpaccept=true
tpaccepteveryone=false

[AutoRespond]
enabled=true
matchesfile=matches.ini

[AutoAttack]
# Entity Handling NEED to be enabled first
enabled=false

[AutoFishing]
# Entity Handling NEED to be enabled first
enabled=false
antidespawn=false

[AutoEat]
# Inventory Handling NEED to be enabled first
enabled=false
threshold=6

[AutoCraft]
# Inventory Handling NEED to be enabled first
# Enable terrainandmovements if you need to use crafting table
enabled=false
configfile=autocraft\config.ini

[Mailer]
# Let the bot act like a mail plugin
enabled=false
database=MailerDatabase.ini
ignorelist=MailerIgnoreList.ini
publicinteractions=false
maxmailsperplayer=10
maxdatabasesize=10000
retentiondays=30

[AutoDrop]
# Inventory Handling NEED to be enabled first
enabled=false
mode=include                      # include, exclude or everything. Include: drop item IN the list. Exclude: drop item NOT IN the list
items=                            # separate each item with comma ','
# For the naming of the items, please see 
# https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Inventory/ItemType.cs 

`
2 weeks ago with the same cc and same config files it worked just fine...
Its just me or did mojang update their auth servers again?

**Comment by slaapkopamy** [comment]
update:

The problem was on my end. I updated the squid proxy server and that broke everything. Tip dont update things if they are working correctly and if security is no issue.

**Comment by ORelio** [comment]
Yes, I'd suggest that error codes from the proxy are because of non-working proxies 😉
Also did you know you can create a SOCKS proxy using SSH without installing Squid?
https://linuxize.com/post/how-to-setup-ssh-socks-tunnel-for-private-browsing/
Never tried it with MCC but MCC supports SOCKS.
