### ISSUE TITLE
Can I display received and sent packets?

### ISSUE THREAD

**Issue by goncharovchik** [ORelio/Minecraft-Console-Client#1278]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Can I display received and sent packets?

**Comment by ReinforceZwei** [comment]
You can do it using ChatBot API. There's a network packet event.

**Comment by ORelio** [comment]
How to write a C# script:
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-write-a-c-script

Example of script with ChatBot:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs

The API you'll want to use:
https://github.com/ORelio/Minecraft-Console-Client/blob/b1233ace7cdc83f233cc1c656ef682e03ee5982d/MinecraftClient/ChatBot.cs#L367

**Comment by goncharovchik** [comment]
> How to write a C# script:
> https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-write-a-c-script
> 
> Example of script with ChatBot:
> https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs
> 
> The API you'll want to use:
> https://github.com/ORelio/Minecraft-Console-Client/blob/b1233ace7cdc83f233cc1c656ef682e03ee5982d/MinecraftClient/ChatBot.cs#L367

As I understood this in bytes? Is it possible to translate into a scheme json?

**Comment by ReinforceZwei** [comment]
Yes, but you need to write your own translator. That event only gives you raw packets. If you really need the packet in json format, I would suggest you using this Javascript library [minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) which will handle and translate every packet into json for you.

**Comment by goncharovchik** [comment]
> Yes, but you need to write your own translator. That event only gives you raw packets. If you really need the packet in json format, I would suggest you using this Javascript library [minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) which will handle and translate every packet into json for you.

I just tried it. But when you log into the server, a strange packet is sent and this ends the login. I want to see how this client responds to this package

**Comment by ReinforceZwei** [comment]
If you don't care about the content of the packets, you can simply subscribe to the network packet event and you will get the packet type ID for every received and sent packets.

**Comment by ORelio** [comment]
Yes just print `packetID` for each packet you received and look at the protocol page for your version: https://wiki.vg/Protocol_version_numbers to learn more about the packet ID causing your issue.

Also if you want to debug and have Visual Studio (Community will do) you can also open Minecraft Console Client in debug mode and put some breakpoints in Protocol18.cs
