### ISSUE TITLE
Logging chat with essentials nickname and hero chat

### ISSUE THREAD

**Issue by DCxCyBeR** [ORelio/Minecraft-Console-Client#1279]
Hello I am struggling to get the bot to log chat to a file for users with a essentials nick name please see the below as a example of something that wont log
[G] [President] [VIP] **DCxCyBeR: {chat message}

the same format but for users without the nickname works fine.

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages
> ## Detecting chat messages
> Minecraft Console Client can parse messages from the server in order to detect private and public messages. This is useful for reacting to messages eg when using the AutoRespond, Hangman game, or RemoteControl bots. However, for unusual chat formats, so you may need to tinker with the ChatFormat section of the config file. Building regular expressions can be a bit tricky, so you might want to try them out eg on regex101.com

**Comment by DCxCyBeR** [comment]
I have looked at that all afternoon and cannot work it out any assistance would be greatly appreciated I know it might seem a pain

**Comment by ORelio** [comment]
Here you go:
```
^(?:\[[^]]+\] )*\**([A-Za-z0-9]+): (.*)$
```
https://regex101.com/r/IRDxb8/1
