### ISSUE TITLE
1.9 supports the intention to have it?

### ISSUE THREAD

**Issue by Cat7373** [ORelio/Minecraft-Console-Client#128]

**Comment by ORelio** [comment]
Quoted from [the forum thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1263927-win-mac-linux-minecraft-console-client-1-8-3) in bold red :
 > Experimental 1.9 support is currently available in development builds - see spoiler below in this post.

**Comment by Cat7373** [comment]
Thanks for Development 0.0

**Comment by Cat7373** [comment]
Just found Indev branch :)

**Comment by ORelio** [comment]
Yes, latest code is there, Will soon be pulled into the master branch for stable release ;)
