### ISSUE TITLE
Random delay for command - Using /fly

### ISSUE THREAD

**Issue by several5** [ORelio/Minecraft-Console-Client#1280]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before 

Question 1
Is it possible to have a random timedelay in between commands. For example i want to have a command sent to the server between 10-50 seconds. This is so the client doesn't look like a bot

Question 2
I want to use the mcc client to move in the air with /fly. For example i want the client to fly from coords A to B above skylimit. Is this possible somehow?

**Comment by ORelio** [comment]
Hi, regarding question 1, see [sample-script-with-task.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-task.cs) and use the following code to set a random delay:
```C#
nextTaskRun = dateNow.AddSeconds(new Random().Next(60, 120)); // Between 60 and 120 seconds
```

Regarding question 2, Minecraft Console Client does not support flying, even with /fly it will still calculate gravity and fall.
Don't hesitate to create 2 issues if you have 2 separate questions. We have more than 1000 issues anyway 😁

**Comment by several5** [comment]
Thanks for the response, i'm quite clueless with writing scripts. I've copied the sample-script-with-tasks into a cs file. But where do i exactly put the code? 
(nextTaskRun = dateNow.AddSeconds(new Random().Next(60, 120));)

i've tried editing the script multiple times but without success.

**Comment by ORelio** [comment]
Replace the existing line (nextTaskRun = dateNow.AddSeconds(60)) with the one I provided.

**Comment by several5** [comment]
It works thanks! Is there a way to remove the infinite loop? I'm trying to make it to where when my autorespond is activated the randomdelay kicks in and sends a certain command 1 time.

**Comment by ORelio** [comment]
Sure, replace the declaration of `nextTaskRun` with this one:
```C#
private DateTime nextTaskRun = DateTime.Now.AddSeconds(new Random().Next(60, 120));
```
And replace `nextTaskRun = dateNow.AddSeconds(60);` below `// Schedule next run` with:
```C#
UnloadBot();
```
This will unload the script rather than keeping it inactive in memory.

**Comment by several5** [comment]
Thanks! for helping me out
