### ISSUE TITLE
ChangeSlot crashes client

### ISSUE THREAD

**Issue by OverHash** [ORelio/Minecraft-Console-Client#1281]
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [X] I have set `debugmessages=true` in config to diagnose my issue
 - [X] I have redacted session tokens and passwords before attaching screenshots

![image](https://user-images.githubusercontent.com/46231745/96329041-aa6f4800-10a5-11eb-805c-274099385229.png)
When calling ChangeSlot, occasionally it will cause Minecraft Console Client to crash. This has happened twice so far in the latest 24h. Hasn't happened earlier than this for weeks.

Here is my code:
```cs
new Thread(() =>
{
    while (true)
    {
        Thread.Sleep(MESSAGE_INTERVAL * 1000);
        ChangeSlot(0);
        SendText("[item] sell shop! Sell tokens for $5000 each! Get rich quick!");
        Thread.Sleep(MESSAGE_INTERVAL * 1000);
        ChangeSlot(1);
        SendText("Visit [item] sell shop! Sell tokens $5000 each! Get rich quick!");
    }
}).Start();
```
which is wrapped inside a ChatBot.

**Comment by ORelio** [comment]
The API is not thread safe. It is currently not possible to call ChatBot methods from a different thread.

**Comment by OverHash** [comment]
What's the best way of creating an infinite loop like this then? With an interval?

**Comment by ReinforceZwei** [comment]
You may make use of the `Update()` event. You can take a look at [AutoAttack](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/AutoAttack.cs).

**Comment by OverHash** [comment]
How often is the Update function fired?

**Comment by ReinforceZwei** [comment]
Around 10 times per second

**Comment by OverHash** [comment]
Thanks. Out of curiosity, is there any better way to wait a specific amount of time in C#? I don't primarily use .NET

**Comment by ReinforceZwei** [comment]
You can compare two `DateTime` object directly using `<` or `>`.

**Comment by OverHash** [comment]
Thanks!

**Comment by ORelio** [comment]
@OverHash Just added a sample script for other people having the same issue as you 😉
▶️ [sample-script-with-task.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-task.cs)
