### ISSUE TITLE
Hangman chatbot

### ISSUE THREAD

**Issue by FishWith3Arms** [ORelio/Minecraft-Console-Client#1283]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

I am trying to use the hangman chatbot on a survival server, but I cant for the life of me find how to activate it. I have enabled it, but how do I actually start playing hangman. I also want to know how to make myself a bot owner so I can actually run hangman. Sorry for the noob question, I'm new to coding and this cc in particular

**Comment by ORelio** [comment]
1. Set your username in `botowners` inside `MinecraftClient.ini`
2. Configure the ChatBot in the `[Hangman]` section, in particular, `enabled=true` and `wordsfile`: [hangman-en.txt](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/hangman-en.txt)
3. From a bot owner, type `start` in chat to start the game, `stop` in chat to stop playing before the game is over
4. If the game does not work, test if that chat messages are correctly detected using [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs)
   - See also: [Internal commands](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#internal-commands): `/script file.cs`
   - See also: [Detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages)
