### ISSUE TITLE
Mailer bot

### ISSUE THREAD

**Issue by MrHallway0** [ORelio/Minecraft-Console-Client#1285]
So, I looked at the docs and stuff but I am still confused about how to use the mailer bot. This might just being dumb though.

**Comment by ORelio** [comment]
You didnt ask a specific question yet so I can only give a link to the apropriate documentation:
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-mailer

**Comment by MrHallway0** [comment]
when running `/tell mail` It just gives me an error about how the player isn't online or something. Even though I have it turned on and `/mailer` works as a command...

**Comment by ORelio** [comment]
Indeed. It's sending a PM to the account running the bot. I'll update the readme.

**Comment by ORelio** [comment]
Fixed, you can check the README again.

**Comment by MrHallway0** [comment]
Thank you!
