### ISSUE TITLE
Dinnerbone announcing migrating Mojang accs to Microsoft

### ISSUE THREAD

**Issue by TNTUP** [ORelio/Minecraft-Console-Client#1286]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Title. https://www.youtube.com/watch?v=i9cqIwrgz7w

That would be complex to implement Microsoft auth as that would require a browser authentification I think :cries:

**Comment by OverHash** [comment]
dinnerbone blink twice if held hostage

just kidding(?)

Too early to say, but it shouldn't be too hard to fake a browser. Just have to change the user-agent header.

**Comment by TNTUP** [comment]
> dinnerbone blink twice if held hostage
> 
> just kidding(?)
> 
> Too early to say, but it shouldn't be too hard to fake a browser. Just have to change the user-agent header.

Indeed, just wanted to make it aware^^ I'm keeping an eye on updates, meaning any 3rd party launchers (*cough* MagicLauncher which im still using!! will be dead officially)

**Comment by ORelio** [comment]
I love how people are unenthusiastic even in Mojang's own video. I never migrated my Minecraft account to a Mojang account to begin with so... :p

We'll see how this affect the login procedure when it's done. In the worst case, you'll need to authenticate in a web browser and extract the session token for use in MCC. Too soon to talk.

**Comment by TNTUP** [comment]
Yeah, ikr. We'll see what happens next

**Comment by Mhowser** [comment]
You guys may or may not have heard about the Linux launcher for Bedrock edition, but they have something called MSA which allows users to sign in to their Microsoft account already. 

https://github.com/minecraft-linux/msa-manifest

Hopefully this can be useful for this project.
