### ISSUE TITLE
Create a databank with c# script

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1287]
Is it possible to save some data in a external file. For example adding each player, who runs a certain command to a player list. Also if its possible, how can I read this data from within another script.

In know you can do it in CSharp, but as far as I know there is no real way to use external libraries in MCC. Is it?

Because i want to create a command which each player can run once every 24 hours. 

Thanks

**Comment by ORelio** [comment]
An easy way would be through an [INI File](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/INIFile.cs). See how the [Mailer](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/Mailer.cs) bot use it.

**Comment by xXjojaXx** [comment]
![Screenshot_20201023_075058_com sec android app sbrowser](https://user-images.githubusercontent.com/73311246/96961324-a8254780-1504-11eb-87ac-20d0329cc8da.jpg)
Like here?
Can you cut me the important lines out, so i can test it in a little bit more uncomplicated way? I'm not too good in sorring out the line
