### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1288]
Im not able to reproduce the transition to discord with a webhook. Can someone explain the whole process and all needed files with a little bit more detail?

**Comment by ORelio** [comment]
A related discussion that might help: #715

**Comment by xXjojaXx** [comment]
I already read it like 10 times and copied the scripts. Also i changed the webhook url and the description where the data is saved. But I cant get it to run. I think im going to send you an picture of my setup this afternoon

**Comment by ORelio** [comment]
Never used it myself, but I assume that you need to:
1. Make sure MCC catches chat messages using [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs)
2. Use scripts in https://github.com/ORelio/Minecraft-Console-Client/issues/715#issuecomment-489442588
  a. You load `DiscordRelay.cs` into MCC it will call a python script that has a Discord webhook configured
  b. `relay.py` is called by the DiscordRelay ChatBot and receives chat messages. It then submits them to Discord

See also https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config for details about how to write scripts, detect chat messages, use the `/script` command to run your script, etc.
