### ISSUE TITLE
How to use the AutoAttack?

### ISSUE THREAD

**Issue by tunkusalim** [ORelio/Minecraft-Console-Client#1290]
ive used the auto respond feature like
```
[Match]
match=hello world
actionprivate=send /reply hello too

//or 

[Match]
match=hello world
actionprivate=script hello.cs
```

and is it possible to triggered this script [AutoAttack.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/8d2b9ab4e25d72b0eee2c77f9d0cffb18d604552/MinecraftClient/Commands/AutoAttack.cs) when the autorespond matches the text/string we send? or triggering the script on-login with specific time?
ive been looking around but i cannot find any documentation related to this

i need help with how to use the [AutoAttack.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/8d2b9ab4e25d72b0eee2c77f9d0cffb18d604552/MinecraftClient/Commands/AutoAttack.cs) script or any commands script

**Comment by ReinforceZwei** [comment]
No. AutoAttack doesn't support control over command so it is not possible to trigger it by AutoRespond.

**Comment by tunkusalim** [comment]
so how can i use it? the documentation only said "must enable entity handling" and ive enabled the entity handling, but i dont know what to do next to use it.
```
entityhandling=true
...
[AutoAttack]
enable=true
```

**Comment by ReinforceZwei** [comment]
After enabling AutoAttack, it will attack mobs within 4 blocks. That's all.

**Comment by tunkusalim** [comment]
so i just need to put the [AutoAttack.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/8d2b9ab4e25d72b0eee2c77f9d0cffb18d604552/MinecraftClient/Commands/AutoAttack.cs) on the file directory and enable the auto attack? and it will attack the nearby mobs?

and what about other players? is it also attack nearby players or we can whitelist which mobs that should be attacked?

**Comment by ReinforceZwei** [comment]
AutoAttack is a built-in ChatBot. You don't need to put it to the directory. Just enable it in the config file to use it.

Currently AutoAttack would only attack hostile mobs and doesn't support custom whitelist.

**Comment by tunkusalim** [comment]
``Currently AutoAttack would only attack hostile mobs and doesn't support custom whitelist.`` so it wont attack a player entities?

**Comment by ReinforceZwei** [comment]
It won't attack players.
