### ISSUE TITLE
How to set a var in cs script?

### ISSUE THREAD

**Issue by XIAYM-gh** [ORelio/Minecraft-Console-Client#1291]
How to set a var in cs script?

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-write-a-c-script
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.cs
https://github.com/ORelio/Minecraft-Console-Client/blob/2017d5d652251657cb8944002b2df2bd32ff72d8/MinecraftClient/CSharpRunner.cs#L333
```C#
MCC.SetVar("var", "value");
```
