### ISSUE TITLE
Checking session indefinitely

### ISSUE THREAD

**Issue by vanoxide** [ORelio/Minecraft-Console-Client#1292]
Hi my internet cuts every now during the night. When trying to autolog sometimes the console client would get stuck on "Checking session" until I have to manually restart the console client. Why is this happening?

![download](https://user-images.githubusercontent.com/60445588/97089347-62b56700-1637-11eb-8049-50a2638b2a23.png)

**Comment by ORelio** [comment]
Unsure why, the session check HTTP request should time out after 30 seconds 🤔

**Comment by ORelio** [comment]
Should be resolved as per #1321
