### ISSUE TITLE
Linux C# scripting

### ISSUE THREAD

**Issue by mijiperki** [ORelio/Minecraft-Console-Client#1294]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

I have been making some C# scripts on my Windows PC and they work pretty nicely (very basic) and I have now tried to get them to work with my 24/7 bot setup on my Linux machine. When I try to load the script in Linux the bot crashes and provides a rather nice wall of text. I don't understand why as it is the exact same config files and script just not on Windows. 

![image](https://user-images.githubusercontent.com/68189471/97127229-f0c14880-1730-11eb-91fa-98c09ae26b9b.png)
https://gyazo.com/b70b6622be1d6bfecfa85d284e7c018a

So my question is, do C# scripts have to be done differently / are they possible to do when using MCC on Linux?

I have also tried downloading and using the example AutoLook.cs script and that also produces a very similar wall of text and crash on Linux however runs perfectly on Windows.

Thanks for any help :D

**Comment by OverHash** [comment]
Looks like the error is related to a missing file. Are you sure you have all the correct files (with correct file permissions)?

**Comment by mijiperki** [comment]
That's what I'm not sure of, I have all the same files in the Linux directory as I have on Windows and all files have the same text/code.

This works and loads the bot perfectly:

![image](https://user-images.githubusercontent.com/68189471/97213319-5b1dcb80-17b9-11eb-85cc-065330eeabcf.png)
![image](https://user-images.githubusercontent.com/68189471/97212998-037f6000-17b9-11eb-9ffd-8830e7d9d858.png)

--------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------

This doesn't work and crashes after typing /script AutoLook.cs:

![image](https://user-images.githubusercontent.com/68189471/97212910-e5b1fb00-17b8-11eb-9ec7-d4efa9bf5f0d.png)
![image](https://user-images.githubusercontent.com/68189471/97212941-f06c9000-17b8-11eb-9ebe-efb19a7395f8.png)

**Comment by mijiperki** [comment]
It appears I didn't REALLY fully read the user manual xd
![image](https://user-images.githubusercontent.com/68189471/97241775-034b8880-17ea-11eb-925a-110cfbd8c2a5.png)


![image](https://user-images.githubusercontent.com/68189471/97241673-b7004880-17e9-11eb-94b5-d705ca23e3f4.png)


I tried again with mono-complete instead of mono-runtime and it worked just like in Windows :D
![image](https://user-images.githubusercontent.com/68189471/97241755-f464d600-17e9-11eb-87b4-1dbcdc554ba4.png)
