### ISSUE TITLE
AutoRelog with sending commands after login with delays.

### ISSUE THREAD

**Issue by CryBaby2332** [ORelio/Minecraft-Console-Client#1295]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

**Feature description**
A feature request should contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any alternative solutions or features you've considered.
* If applicable, add screenshots to help explain your request

Hi. Could you please help me to create a script? I need a script that would re-join the server for any reason for a kick, and send 4 commands after entering at a certain interval.
AutoRelog is not suitable because there is no command sending after login, and the ability to restart for only 1 reason. This can be used, for example, when you are playing on a project where you need to go to the skyblock by entering several commands, and run a script to extract, for example, a stone.
My English is very bad but I use google translator. Sorry guys.

**Comment by mijiperki** [comment]
Auto relog is perfectly suitable to re-join in this situation and can have numerous "restart reasons".
To set this up:

In your MinecraftClient.ini file enbale AutoRelog and set retries to -1 (infinite retires):

![image](https://user-images.githubusercontent.com/68189471/97357460-b7ecb500-1891-11eb-8f99-d70a6fc637f3.png)

Then, in the same directory as your MinecraftClient.exe and MinecraftClient.ini make a new text file (.txt) called "kickmessages.txt":
![image](https://user-images.githubusercontent.com/68189471/97357594-f08c8e80-1891-11eb-908c-9351fd72f1fc.png)

Inside this file, write on each line an exact copy of the message received when kicked/disconnected. An example:
![image](https://user-images.githubusercontent.com/68189471/97357706-1d40a600-1892-11eb-987e-80395eca127d.png)

This will now auto re-join you after you are disconnected from the server for any reason in kickmessages.txt. Keep adding to this file if you get disconnected with a new message!

---------------

Now, you wanted to also send 4 commands after re-joining. To do this, I would recommend using the inbuilt script scheduler.

In your MinecraftClient.ini file enable ScriptScheduler:
![image](https://user-images.githubusercontent.com/68189471/97357985-7f011000-1892-11eb-9a22-389dedb341b8.png)

Then, in the same directory as your MinecraftClient.exe and MinecraftClient.ini make a new file (.ini) called "taks.ini":
![image](https://user-images.githubusercontent.com/68189471/97358119-b079db80-1892-11eb-8b3b-cff42a5204e6.png)

Now inside this file you want to call a script to send the 4 commands (we haven't created that script yet):
![image](https://user-images.githubusercontent.com/68189471/97358392-1d8d7100-1893-11eb-9390-e20ef291ee9e.png)

Now we need to create loginCommands.txt. To do this, in the same directory as your MinecraftClient.exe and MinecraftClient.ini make a new text file (.txt) called "loginCommands.txt":
![image](https://user-images.githubusercontent.com/68189471/97358649-74934600-1893-11eb-88c7-00251d951978.png)

Inside this script we need to send the 4 commands with a little bit of delay in-between so you don't get kicked for spam (adjust this to your preference):
![image](https://user-images.githubusercontent.com/68189471/97358913-dc499100-1893-11eb-9460-c339650bbebd.png)

That's it! Your bot will now automatically re-join after any of kickmessages provided and will always send the 4 commands every time it re-joins the server! Hopefully this is pretty close to what you were looking for :D

**Comment by CryBaby2332** [comment]
Thank you very much!

> Auto relog is perfectly suitable to re-join in this situation and can have numerous "restart reasons".
> To set this up:
> 
> In your MinecraftClient.ini file enbale AutoRelog and set retries to -1 (infinite retires):
> 
> ![image](https://user-images.githubusercontent.com/68189471/97357460-b7ecb500-1891-11eb-8f99-d70a6fc637f3.png)
> 
> Then, in the same directory as your MinecraftClient.exe and MinecraftClient.ini make a new text file (.txt) called "kickmessages.txt":
> ![image](https://user-images.githubusercontent.com/68189471/97357594-f08c8e80-1891-11eb-908c-9351fd72f1fc.png)
> 
> Inside this file, write on each line an exact copy of the message received when kicked/disconnected. An example:
> ![image](https://user-images.githubusercontent.com/68189471/97357706-1d40a600-1892-11eb-987e-80395eca127d.png)
> 
> This will now auto re-join you after you are disconnected from the server for any reason in kickmessages.txt. Keep adding to this file if you get disconnected with a new message!
> 
> Now, you wanted to also send 4 commands after re-joining. To do this, I would recommend using the inbuilt script scheduler.
> 
> In your MinecraftClient.ini file enable ScriptScheduler:
> ![image](https://user-images.githubusercontent.com/68189471/97357985-7f011000-1892-11eb-9a22-389dedb341b8.png)
> 
> Then, in the same directory as your MinecraftClient.exe and MinecraftClient.ini make a new file (.ini) called "taks.ini":
> ![image](https://user-images.githubusercontent.com/68189471/97358119-b079db80-1892-11eb-8b3b-cff42a5204e6.png)
> 
> Now inside this file you want to call a script to send the 4 commands (we haven't created that script yet):
> ![image](https://user-images.githubusercontent.com/68189471/97358392-1d8d7100-1893-11eb-9390-e20ef291ee9e.png)
> 
> Now we need to create loginCommands.txt. To do this, in the same directory as your MinecraftClient.exe and MinecraftClient.ini make a new text file (.txt) called "loginCommands.txt":
> ![image](https://user-images.githubusercontent.com/68189471/97358649-74934600-1893-11eb-88c7-00251d951978.png)
> 
> Inside this script we need to send the 4 commands with a little bit of delay in-between so you don't get kicked for spam (adjust this to your preference):
> ![image](https://user-images.githubusercontent.com/68189471/97358913-dc499100-1893-11eb-9460-c339650bbebd.png)
> 
> That's it! Your bot will now automatically re-join after any of kickmessages provided and will always send the 4 commands every time it re-joins the server! Hopefully this is pretty close to what you were looking for :D

Thank you very much!

**Comment by CryBaby2332** [comment]
Thank you very much! the issue is closed!

**Comment by ReinforceZwei** [comment]
`send` is a console command for sending message to the server. You may replace that command with other console commands you want.

**Comment by CryBaby2332** [comment]
thanks.

**Comment by ORelio** [comment]
Thank you @mijiperki for creating a highly detailed tutorial 👍
