### ISSUE TITLE
Want to be able to trade with villagers by chatbot

### ISSUE THREAD

**Issue by mexiscool** [ORelio/Minecraft-Console-Client#1296]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

**Feature description**
A feature request should contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any alternative solutions or features you've considered.

**Description**
- Want to be able to trade with villagers by chatbot (in 1.16.3).
- Want to be able to access the information contained in the packet TradeList (0x26) sent by the server after sending use/InteractEntity  (0x0e). Also being able to send the SelectTrade (0x22) packet.
here are two screenshots of what's in the packets for opening a farmer villager and selecting the pumpkin trade: 
TradeList received from the server:
![trade_list](https://user-images.githubusercontent.com/27775925/97184550-564c1e00-179f-11eb-8e88-5185cda622d6.PNG)
SelectTrade sent to the server:
![select_trade](https://user-images.githubusercontent.com/27775925/97184576-5c41ff00-179f-11eb-9085-f1b8a1433b1e.PNG)
(used [pakkit](https://github.com/Heath123/pakkit) to analyze this)
the server also sends various other packets but I believe those are already supported.
From what I understand these need to be added in MinecraftClient/Protocol/Handlers/Protocol18.cs but I'm new to c# so I can only kinda understand what's already there.
- For receiving the TradeList I have considered using the OnNetworkPacket in the chatbot API and translating it.
I don't think there is a possible way to send a SelectTrade packet with the api?

**Comment by mexiscool** [comment]
Update got handling the tradelist packet implemented and working. Gonna do the selectTrade one next and try and make a pull request after that.

**Comment by ORelio** [comment]
Would be great! Thanks for investigating that 👍
