### ISSUE TITLE
How to use SugarCaneMiner

### ISSUE THREAD

**Issue by LidForr** [ORelio/Minecraft-Console-Client#1299]
How do uses suger cane miner?
thanks for your answers

**Comment by ORelio** [comment]
1. Put coordinates of the sugar can inside [SugarCaneMiner.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/SugarCaneMiner.cs)
2. Stand in front of the sugar cane
3. Launch the script once: `/script SucarCaneMiner.cs`
4. To auto-launch on first login, use [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler).
