### ISSUE TITLE
joining a 1.9 server 

### ISSUE THREAD

**Issue by ImProLeader** [ORelio/Minecraft-Console-Client#130]
i try to join a server "play.saicopvp.com"
Its 1.8 with 1.9 compatability and it keeps saying outdated client anything i can do?

**Comment by ORelio** [comment]
your server is probably reporting itself as 1.8 when pinged.
Please try the following :
 - Use the [latest development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) in an empty directory
 - Launch it once to generate the INI file
 - Set `debugmessages=true` in the INI file
 - Relaunch it and try joining the server
 - Please copy and past the whole "Server version" line that will appear.
Meanwhile, you can force 1.9 with `mcversion=1.9` in INI file.

**Comment by ORelio** [comment]
No news, closing, feel free to reopen if needed.
