### ISSUE TITLE
Check block at x,y,z?

### ISSUE THREAD

**Issue by Antr0p0s** [ORelio/Minecraft-Console-Client#1301]
I'm currently trying to make a script to check a block in specific coordinates.
the script I'm currently trying out with is at the bottom.

What I'm asking is how to check if a block (at coordinate x, y, z) is present and, if present, what block it is. 

The script:
//MCCScript 1.0

MCC.LoadBot(new CheckBlock());

//MCCScript Extensions

public class CheckBlock : ChatBot
{
    public override void Initialize()
    {
        Location current1 = GetCurrentLocation();
		LogToConsole("Current location: " + current1);                  
		Material block = GetWorld().GetBlock(current1).Type;
    }
}

**Comment by Antr0p0s** [comment]
I also can't manage to get this function to work https://github.com/ORelio/Minecraft-Console-Client/issues/123

**Comment by ReinforceZwei** [comment]
You can log the block type to the console by using `LogToConsole(block.ToString())` to see what block is it. If it is air, mean no block present.

**Comment by Antr0p0s** [comment]
it does not seem to get that far, after the first LogToConsole it says 
"object reference not set to an instance of an object"

same for script along the lines of https://github.com/ORelio/Minecraft-Console-Client/issues/244

**Comment by Antr0p0s** [comment]
Turns out I'm stupid and did not turn on terrain handling, anyway I can delete this post to stop wasting people's time?
