### ISSUE TITLE
Cant download newest version

### ISSUE THREAD

**Issue by Meowlan** [ORelio/Minecraft-Console-Client#1302]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

![Capture](https://user-images.githubusercontent.com/69299012/97752286-013c3f00-1af4-11eb-9b7e-48cda71cf45e.JPG)

i think im just stupid or smt but please help me

**Comment by ORelio** [comment]
My bad. Fixed.

**Comment by Meowlan** [comment]
K Thx
