### ISSUE TITLE
Discord Script works in VS but not with MCC

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1305]
Sry for not continuing my old issues, but I tried to continue on an other way of sight and came to the following issue:
I want to send a Message to Discord with the following script, which works completely fine if I run it with VisualStudio. But when I execute it via MCC it simply does nothing, which makes me believing that the script crashes. Can anybody explain me why? Did i miss anything. Btw. I dont want to make a chatbot out of the script. 
Thanks 
My Script:
//MCCScript 1.0
//using System;
//using System.Collections.Generic;
//using System.Collections.Specialized;
//using System.Linq;
//using System.Net;
//using System.Text;
//using System.Threading.Tasks;
MMC.SendText("ausgeführt");

using (dWebHook dcWeb = new dWebHook())
{
    string webHook = "https://discordapp.com/api/webhooks/767843366078644277/6fT0qxZy3XWt3YwWU_7nnRCnbhRPZ5VMr-8-YewLOLymXcmlumzGG-XXXXXXXXXXXXXX";
    dcWeb.ProfilePicture = "https://pasteboard.co/XXXXXXX.jpg";
    dcWeb.UserName = "Bot";
    dcWeb.WebHook = webHook;
    dcWeb.SendMessage("Hallo!");
}
public class dWebHook : IDisposable
{
    private readonly WebClient dWebClient;
    private static NameValueCollection discordValues = new NameValueCollection();
    public string WebHook { get; set; }
    public string UserName { get; set; }
    public string ProfilePicture { get; set; }

    public dWebHook()
    {
        dWebClient = new WebClient();
    }

    public void SendMessage(string msgSend)
    {
        discordValues.Add("username", UserName);
        discordValues.Add("avatar_url", ProfilePicture);
        discordValues.Add("content", msgSend);

        dWebClient.UploadValues(WebHook, discordValues);
    }

    public void Dispose()
    {
        dWebClient.Dispose();
    }
}

**Comment by ORelio** [comment]
The MCC script is wrapped in a class in the following way:
https://github.com/ORelio/Minecraft-Console-Client/blob/916903689346f4878c5409e8c2ee1b183638fb52/MinecraftClient/CSharpRunner.cs#L80-L103

So the code you want to execute goes into the main section while the dWebHook goes into the `//MCCScript Extensions` section.

See [sample-script-extended.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-extended.cs) and [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs).

**Comment by xXjojaXx** [comment]
Now I moved the dWebhook class in thr //MCC Extensions part but i still cant get it to work. Whats about the usings do I even have to declare the libraries that i want to use in my script?

**Comment by ORelio** [comment]
As shown above, some `using` statements are already there automatically, but you can add the missing ones as comments at the beginning of your script. Adding `using` statements already present by default such as `//using System;` will probably not work.

**Comment by xXjojaXx** [comment]
Ok, thanks for your help. I will try it later ro remove the pre-existing ones and hope that it will work then

**Comment by Nekiplay** [comment]
You can also add a DLL using //dll dllpath.dll

**Comment by xXjojaXx** [comment]
Ok, update: My script now looks like this and still doesnt run, because it crashes:

//MCCScript 1.0
//using System.Collections.Specialized;

MMC.SendText("ausgeführt");

using (dWebHook dcWeb = new dWebHook())
{
    string webHook = "https://discordapp.com/api/webhooks/767843366078644277/6fT0qxZy3XWt3YwWU_7nnRCnbhRPZ5VMr-8-YewLOLymXcmlumzGG-XXXXXXXXXXX";
    dcWeb.ProfilePicture = "https://pasteboard.co/Jyd6ud8.jpg";
    dcWeb.UserName = "Bot";
    dcWeb.WebHook = webHook;
    dcWeb.SendMessage("Hallo!");
}

//MCCScript Extensions

public class dWebHook : IDisposable
{
    private readonly WebClient dWebClient;
    private static NameValueCollection discordValues = new NameValueCollection();
    public string WebHook { get; set; }
    public string UserName { get; set; }
    public string ProfilePicture { get; set; }

    public dWebHook()
    {
        dWebClient = new WebClient();
    }

    public void SendMessage(string msgSend)
    {
        discordValues.Add("username", UserName);
        discordValues.Add("avatar_url", ProfilePicture);
        discordValues.Add("content", msgSend);

        dWebClient.UploadValues(WebHook, discordValues);
    }

    public void Dispose()
    {
        dWebClient.Dispose();
    }

Would be nice to find out why

**Comment by xXjojaXx** [comment]
> You can also add a DLL using //dll dllpath.dll
> ![image](https://user-images.githubusercontent.com/35975332/98460425-1c7b0e80-21c6-11eb-87bd-2f20f313161f.png)

Is there any advantage of using an dll? Is it more reliable?

**Comment by xXjojaXx** [comment]
Ok, next Update: Know there are getting messages delivered to discord via the webhook. But there is a delay up to 20 minutes till they arrive, which is a littlebit akward. The problem was a typing mistake and the using of the "using statement", which seems to be interpreted the weong way. Now i have shortened the script to the following:

//MCCScript 1.0
//using System.Collections.Specialized;
MCC.SendText("ausgeführt");
dWebHook dcWeb = new dWebHook();
    string webHook = "https://discordapp.com/api/webhooks/767843366078644277/6fT0qxZy3XWt3YwWU_7nnRCnbhRPZ5VMr-8-YewLOLymXcmlumzGG-XXXXXXXXX";
    dcWeb.ProfilePicture = "https://pasteboard.co/Jyd6ud8.jpg";
    dcWeb.UserName = "Bot";
    dcWeb.WebHook = webHook;
    dcWeb.SendMessage("Hallo!");
    
//MCCScript Extensions

public class dWebHook : IDisposable
{
    private readonly WebClient dWebClient;
    private static NameValueCollection discordValues = new NameValueCollection();
    public string WebHook { get; set; }
    public string UserName { get; set; }
    public string ProfilePicture { get; set; }

    public dWebHook()
    {
        dWebClient = new WebClient();
    }

    public void SendMessage(string msgSend)
    {
        discordValues.Add("username", UserName);
        discordValues.Add("avatar_url", ProfilePicture);
        discordValues.Add("content", msgSend);

        dWebClient.UploadValues(WebHook, discordValues);
    }

    public void Dispose()
    {
        dWebClient.Dispose();
    }

But now I have to new problems: First of all the very long delay, which has to be an issue apecifically of MCC or my server, because thats no issue when i try it via Visual Studio from my computer. But more important is the second issue: The first message that got sended was all fine in meaning of the context, but then the username and the main part of the sended Messages stacked up. I cant describe it pretty well so heres a picture:
![Screenshot_20201108_164113](https://user-images.githubusercontent.com/73311246/98469730-a97f9100-21e1-11eb-94ee-a74987c58e59.jpg)
Maybe it stacks the username etc. Because it isnt protected to overwriting anymore?
Pls help

**Comment by ORelio** [comment]
I assume the issue was resolved since then
