### ISSUE TITLE
How do I force sending commands and getting the result in a new file?

### ISSUE THREAD

**Issue by kostya23475** [ORelio/Minecraft-Console-Client#1308]
I want to force the console to send commands and receive the server response in a new file.

Example: the bot sends the command /check (player's nickname)

this command shows whether the player is banned. And I want to get the server response in a new file, so that I don't have to scroll through the console, but immediately open a text document and find out the result.

I also want him to send the command:
/ban [player's nickname] 2.1.

please Tell me. I'm sorry if I'm not clear, I'm from Russia and use Google translate

**Comment by ORelio** [comment]
Hi,

For your information, MCC cannot correlate commands and responses. The server sends a flow of text lines to the client. But you cannot reliably tell which line contains the response for your command. So you cannot get the response directly.

However, you can do something close to that. I'd suggest this approach:
1. Configure `chatbotlogfile` in `MinecraftClient.ini` to have a log file for chatbots
2. Configure [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler) to send a command on a regular time interval
3. Configure [AutoRespond](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorespond-feature) to react to the output lines for your command using some `regex=`
4. Use `actionother=log $0` to log the whole line matching your match pattern into the log file
