### ISSUE TITLE
Cannot activate Terrain and Movements in the config file

### ISSUE THREAD

**Issue by JackTYM** [ORelio/Minecraft-Console-Client#1309]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
A bug report should contain the following items:
* A clear and concise description of what the bug is
* Steps to reproduce the behavior
* What I expected to happen instead
* If applicable, add screenshots to help explain your problem
* Specify which kind of operating system you are running

I am attempting to enable /dig or /look etc but even though my config file has terrainandmovements enabled, it still gives the error

 [MCC] Please enable Terrain and Movements in the config file first.

I still get the error even when having it enabled. All other config settings work except for that.

![Screenshot_2](https://user-images.githubusercontent.com/50038825/97933086-9fafe680-1d26-11eb-8d6a-5df249bfb15b.png)

![Screenshot_3](https://user-images.githubusercontent.com/50038825/97933169-d423a280-1d26-11eb-91f3-06e37c7a77c7.png)

**Comment by JackTYM** [comment]
I am running the latest version from AppVeyor too

**Comment by ReinforceZwei** [comment]
This is because the terrain and movement doesn't support the Minecraft version you are using. You can see there is a red line telling you about that in the console.

**Comment by JackTYM** [comment]
Ah thank you. Sorry I missed that somehow. Do you know if it ever will be?

**Comment by ReinforceZwei** [comment]
Do you mean when would the terrain and movement be supported? Please see #1090 and #1300
