### ISSUE TITLE
terrainandmovements=true when crashes

### ISSUE THREAD

**Issue by Cat7373** [ORelio/Minecraft-Console-Client#131]
Server：Spigot1.9
OS：Windows 10 64bit

未经处理的异常:  System.ArgumentException: 偏移量和长度超出数组的界限，或者计数大于从索引到源集合结尾处的元素数量。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.RemoveRange(Int32 index, Int32 count)
   在 MinecraftClient.Protocol.Handlers.Protocol18Handler.ProcessChunkColumnData(Int32 chunkX, Int32 chunkZ, UInt16 chunkMask, Boolean hasSkyLight, Boolean chunksContinuous, List`1 cache)
   在 MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   在 MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   在 MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by ORelio** [comment]
Terrain and movements is currently not handled for 1.9.
It should have printed a message while joining the server :
 > Terrain & Movements currently not handled for that MC version.

In fact even if printing that message, it was still tying to handle terrain and movements, so of course it crashed as terrain is not in the same format in Minecraft 1.9. Just added a fix for that. Thanks.

Will work on terrain handling for 1.9, later ;)
