### ISSUE TITLE
1.16.3 Fishing Script?

### ISSUE THREAD

**Issue by JackTYM** [ORelio/Minecraft-Console-Client#1310]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

How could i get/make a fishing script for afking? basically what i want to do is check inventory for a rod, switch to that rod, and then throw it into water which is in front of the player. When a fish is caught on the hook it pulls it back and sends it out instantly. There are mods that do this but i couldn’t figure out how to do them inside of Console Client.

**Comment by ReinforceZwei** [comment]
Are you looking for the AutoFish feature? Please see [README](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-auto-fishing)
