### ISSUE TITLE
Random delay for autorelog

### ISSUE THREAD

**Issue by several5** [ORelio/Minecraft-Console-Client#1312]
1. Some servers blacklist IPs if they detect scripts/bot activities.

It might be helpful to add a random delay in the autorelog option.
Exmaple: the console client will relog in between 50-80 seconds.

2. How do i make the autorespond script pickup sentences instead of words?

Thanks!

**Comment by ORelio** [comment]
Hello,

If the server admin does not want you to use a bot, maybe you shouldn't...
However, there are also legitimate reasons for using random delay: when you need to reconnect many accounts at once.
So I added the requested feature for that purpose.

AutoRespond can pick up sentences, just put what you want in your match.

**Comment by several5** [comment]
Orelio, i appreciate it alot! Thanks
