### ISSUE TITLE
Right Clicking NPCs

### ISSUE THREAD

**Issue by Yazability** [ORelio/Minecraft-Console-Client#1318]
Is it possible to right click NPCs with the console client. The server I want to setup a bot on has disabled any command that can send you from the hub to the actual game server, you instead have to right click an NPC.

**Comment by ReinforceZwei** [comment]
You may first enable entity handling, then use `/entity` command to find out the NPC's entity ID that you want to interact with. After that you can use `/entity <ID> use` to 'right click' that NPC.

**Comment by Yazability** [comment]
> You may first enable entity handling, then use `/entity` command to find out the NPC's entity ID that you want to interact with. After that you can use `/entity <ID> use` to 'right click' that NPC.

I tried that, the thing is the NPC is invisible to the player unless it moves. Terrain handling is not supported with this server, its a 1.12.2 server. It has many anti bot features but I have permission from the staff to have this one.

**Comment by Yazability** [comment]
> > You may first enable entity handling, then use `/entity` command to find out the NPC's entity ID that you want to interact with. After that you can use `/entity <ID> use` to 'right click' that NPC.
> 
> I tried that, the thing is the NPC is invisible to the player unless it moves. Terrain handling is not supported with this server, its a 1.12.2 server. It has many anti bot features but I have permission from the staff to have this one.

Correction: Server version : Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x (protocol v753)

**Comment by ReinforceZwei** [comment]
Then you can specify a Minecraft version that support terrain and movement (e.g. 1.15.2) in the configuration file and enable terrain and movement.

**Comment by Yazability** [comment]
> Then you can specify a Minecraft version that support terrain and movement (e.g. 1.15.2) in the configuration file and enable terrain and movement.

It worked, thank you!
