### ISSUE TITLE
Copy Inventory

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1320]
Is there any way to get the bot to copy the inventory of another user? Its possible for me to see in their inventory via /invsee if that does matter. Or is it at least possible to get the id and count of blocks/items in the first slot of an inventory? Thanks

**Comment by ORelio** [comment]
You should be able to by running sending the `/invsee` command to the server and using the regular inventory API.

**Comment by ReinforceZwei** [comment]
By the way you cannot get the full inventory items of other players in vanilla server.

**Comment by Mhowser** [comment]
That's right, the only things that are visible to other clients is armor
and held items.

**Comment by xXjojaXx** [comment]
Ok, thanks. But how does the Inventory API works. Is there any method for a csharp script, which allows me to get the details of an slot of an open inventory? (Like:) 
MCC. GetItemCount([InventoryNumber], [Slot])  or
MCC.GetItemType([InventoryNumber], [Slot])

**Comment by ReinforceZwei** [comment]
Please use the ChatBot API. See [example script with chatbot](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs).
For getting the inventories, you can use [`GetInventories()`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L1169) method or `GetPlayerInventory()` for getting player inventory only.
You may want to have a look at the [Container Class](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Inventory/Container.cs) to see the methods for manipulating inventory.

**Comment by xXjojaXx** [comment]
Sry, if im not far enough in programming

**Comment by ReinforceZwei** [comment]
```cs
//MCCScript 1.0

/* This is a sample script that will load a ChatBot into Minecraft Console Client
 * Simply execute the script once with /script or the script scheduler to load the bot */

MCC.LoadBot(new ExampleBot());

//MCCScript Extensions

/* The ChatBot class must be defined as an extension of the script in the Extensions section
 * The class can override common methods from ChatBot.cs, take a look at MCC's source code */

public class ExampleBot : ChatBot
{
    public override void AfterGameJoined()
    {
        // Get inventory
        Container inventory = GetPlayerInventory();
        // Count how many slot has item
        LogToConsole("Player inventory total " + inventory.Items.Count + " items:");
        // Print out every item inside inventory
        foreach(var item in inventory.Items)
        {
            LogToConsole(string.Format("{0} x{1}", item.Value.Type, item.Value.Count));
        }
    }
}
```

**Comment by xXjojaXx** [comment]
Thank you very much. Ill try it this evening and update my comment then.
