### ISSUE TITLE
Setting up MCC on Ubuntu 20.04 VPS

### ISSUE THREAD

**Issue by Yazability** [ORelio/Minecraft-Console-Client#1322]
I am trying to set up MCC on my VPS, running Ubuntu 20.04. I am new to all this VPS stuff but from what I understand I must first install mono 4.0 - 4.2. I am having trouble doing that, if anyone can guide me that would be highly appreciated!

**Comment by ORelio** [comment]
I think your're looking for [how to use](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-use). You can use any version above Mono 4.0 now.

**Comment by Yazability** [comment]
> I think your're looking for [how to use](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-use). You can use any version above Mono 4.0 now.

Ok so this is what I did.
- Connected via SSH and logged in.
- apt-get install mono-complete
- mozroots --import --ask-remove
- mono --version (running newest version)
- I then uploaded the files using FileZilla over SFTP. All the scrips and my config.
- In the same screen I did cd ConsoleClient (which is the file that contains everything, I placed this in the root directory)
- I then did mono MinecraftClient.exe

It is running fine. But my question is: How can I open a new screen for MCC specifically. Cause right now I have it like in the main screen and I can't really do anything with the VPS since its open.

**Comment by Yazability** [comment]
I did apt

**Comment by Yazability** [comment]
I did:
- mono install screen
- screen -D -R -S mccclient mono MinecraftConsole.exe

But it didn't work. The screen just closed

**Comment by mexiscool** [comment]
i don't know what mono install screen does but might be the same as ''sudo apt install screen''.
once you have it installed you do "screen -S [name you want to use, i normally just use the minecraft account name]".
then you get something that looks like a new ssh session in your ssh session, you start MCC like normal by "mono MinecraftClient.exe".
Then to close the screen you do ctrl+a and second ctrl+d. Now you can close the actual ssh connection.
When you want to reconnect to the screen you type "screen -R [name you used]" and use ctrl+a and ctrl+d when you want to exit.

**Comment by Yazability** [comment]
> I don't know what mono install screen does but try doing "sudo apt update" to update some stuff (I recommend running this before you do anything else on a new vps) and ''sudo apt install screen'' to install screen.
> once you have it installed you do "screen -S [name you want to use, i normally just use the minecraft account name]".
> then you get something that looks like a new ssh session in your ssh session, you start MCC like normal after navigating to the folder with "cd ConsoleClient" you do "mono MinecraftClient.exe".
> Then to close the screen you do ctrl+a and second ctrl+d. Now you can close the actual ssh connection.
> When you want to reconnect to the screen you type "screen -R [name you used]" and use ctrl+a and ctrl+d when you want to exit.

Ok yeah so after reading that and doing some research I got it to work.

Here is what I did:
- Installed Screen with sudo apt-get install screen
- screen -S <Screen Name>
- cd ConsoleClient (the folder I have the MCC in)
- mono MinecraftClient.Exe
- And then I detached the screen using Ctrl A + D
- Exited and the bot was still there and up so I guess I got it to work. Thanks!
