### ISSUE TITLE
Console client for CentOS at VPS servers

### ISSUE THREAD

**Issue by CryBaby2332** [ORelio/Minecraft-Console-Client#1323]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

Hello. Can the Linux version work with CentOS, Debian and Ubuntu? Let's say I have a script for automatic login and a VPS server on CentOS, so I want my accounts to be on it.
I am using google translator, so the text may not be correct ;/
I am not very good at this, so don't throw tomatoes :3

**Comment by ORelio** [comment]
Yes you can use almost any Linux distribution, just install Mono.
▶️ [how to use](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-use)

**Comment by CryBaby2332** [comment]
thanks!

**Comment by goncharovchik** [comment]
> **Prerequisites**
>  - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
>  - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
>  - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one
> 
> **Description of the Questions**
> Your question may contain the following items:
> * A concise description of your problem (I'm always frustrated when [...])
> * A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
> * Any solutions or features you've already considered (I tried to set this setting in config [...]).
> * If applicable, add screenshots to help explain your question
> 
> Hello. Can the Linux version work with CentOS, Debian and Ubuntu? Let's say I have a script for automatic login and a VPS server on CentOS, so I want my accounts to be on it.
> I am using google translator, so the text may not be correct ;/
> I am not very good at this, so don't throw tomatoes :3

Уйди
