### ISSUE TITLE
Respond to Confirm Transaction Packets

### ISSUE THREAD

**Issue by Rerd** [ORelio/Minecraft-Console-Client#1324]
The console client should respond to Confirm Transaction packets. Some anti-cheats use them to detect lag and if a client does not respond to them, they will be kicked from the server.

**Comment by ReinforceZwei** [comment]
It was implemented. Please see [Protocol18.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#767)

**Comment by Rerd** [comment]
Still getting timed out for not responding to transactions. It should be packet ID 0x32 for 1.8.x at least

**Comment by ReinforceZwei** [comment]
You will need inventory handling enabled for it to work.

**Comment by Rerd** [comment]
I enabled inventory handling, still getting kicked.

**Comment by ReinforceZwei** [comment]
Look like you had mentioned 1.8.x. Unfortunately inventory handling doesn't support 1.8 at the time.

**Comment by Rerd** [comment]
Are there any plans on support for 1.8 inventory handling?

**Comment by ReinforceZwei** [comment]
Honestly, no. I don't have time to implement new features now.

**Comment by ReinforceZwei** [comment]
Duplicate of #997
