### ISSUE TITLE
Wondering if there is a way to detect if player is not moving

### ISSUE THREAD

**Issue by Qwayne** [ORelio/Minecraft-Console-Client#1325]
Hello, I am wondering if there is a way for mcc to detect if my player model is not moving and hence trigger a specific command for that.

This is mainly because, I sometimes get kicked for flying and the server I play on teleports me to a different lobby.

**Comment by mexiscool** [comment]
As far as I know the player model doesn't move by gravity unless the client in this case mcc simulates it and tells the server that it moved. Depending on the minecraft version it might be solvable, which one do you use?

**Comment by Qwayne** [comment]
Oops mb, forgot to mention that I stimulate the movements using the move x y z command. I'm using 1.8.9

**Comment by mexiscool** [comment]
could use GetCurrentLocation() and check every update if the result changed

**Comment by Qwayne** [comment]
Oh so using a C# script? My script atm it just a very simple script of move commands and send commands. I dont really have much experience on making a C# script for mcc.

**Comment by mexiscool** [comment]
any chance you know on which kind of blocks your bot is standing when you use it?

**Comment by Qwayne** [comment]
I walk over obsidian, which is there on the list, the coordinates are in integers without any decimal values. The kick for flying isnt really often but it can ruin a day of afk sometimes.

**Comment by mexiscool** [comment]
okay ehm I'm not sure than, to rule out my hypothesis you could try and replace 'Movement.IsOnGround(world, location)' on line 885 with 'true' in this file https://github.com/ORelio/Minecraft-Console-Client/blob/2eba2149b720a194fbb2a2be19e95be74c04ce4a/MinecraftClient/McClient.cs#L885 after downloading the repository and recompiling it as explained here https://github.com/ORelio/Minecraft-Console-Client#building-from-source

**Comment by mexiscool** [comment]
Oh actually does the player actually move when you use that command cause i'm not sure if terrain handling works in 1.8.9
