### ISSUE TITLE
sat in minecart holding right click 

### ISSUE THREAD

**Issue by crazylee1000** [ORelio/Minecraft-Console-Client#1327]
I play on a skyblock server and I like to automatically sell the chest of items all the time so I was wondering if I could get an alt to sit in a minecart and hold down right click it will need to be holding a sell wand. I have seen other people do it but I think they use minebot.

issues I am having:
getting alt to sit in a minecart
getting alt to continuasly hold down right-click on chests

**Comment by ReinforceZwei** [comment]
You can use `/entity` command to find out the entity ID of the minecart and use `/entity <ID> use` to ride it. For holding right-click, you might need to write a ChatBot C# script that will call `SendPlaceBlock()` inside `Update()` event.

**Comment by crazylee1000** [comment]
/entity is a unknow command, and i am not smart enough to make a chatbot c# script

**Comment by crazylee1000** [comment]
> You can use `/entity` command to find out the entity ID of the minecart and use `/entity <ID> use` to ride it. For holding right-click, you might need to write a ChatBot C# script that will call `SendPlaceBlock()` inside `Update()` event.

so iv got him sitting in a minecart now i need to get him facing a certain direction while holding down right click. do you know if someone has already made a chatbot c# script

**Comment by several5** [comment]
You can use the /look (coords) command to make your client look a certain way

**Comment by crazylee1000** [comment]
> You can use the /look (coords) command to make your client look a certain way

seems to be unknow, do i need to enable something in the config

**Comment by several5** [comment]
Enable "terrainandmovements=true"

**Comment by crazylee1000** [comment]
> Enable "terrainandmovements=true"
it says currently not handled for that MC version, is there a way to force mc version

**Comment by several5** [comment]
You can change the minecraft version in the config file; mcversion=1.12.2
1.12.2 works with /look /move etc

**Comment by crazylee1000** [comment]
how do I get my alt to hold down right clickk
