### ISSUE TITLE
Inventory Management/Container Confusion.

### ISSUE THREAD

**Issue by amigoexp** [ORelio/Minecraft-Console-Client#1328]
Hello everybody more than 1 week, i have been reading your github however, i cannot find any solution for logging server which have lobby. (and also which does not have /survival, /skyblock etc...)

Here is the photos and log and i will show you what i have done or trying to do.

First of all i cannot select diamond i tried /inventory player click 1 left or many different combinations. I cannot click.
I tried /inventory player list. It shows me that diamond slot is #36 however, when i click 36 nothing happens. And also i tried to use <container> however, i could not find anything.

waiting for your helps

![image](https://user-images.githubusercontent.com/40539114/98818463-ac29f280-243c-11eb-87e6-ebf161e38a22.png)
![image](https://user-images.githubusercontent.com/40539114/98818639-e4313580-243c-11eb-899d-c82977cea9fc.png)

`MC4FUN ▸ Başarıyla giriş yaptın.
Sana ait 2 hesap bulundu:
swapskips, Lucifer31.
MC4FUN Hoşgeldiniz
MC4FUN Hoşgeldiniz
MC4FUN Hoşgeldiniz
>/inventory player
[MCC] Inventory #0 - Player Inventory
 #36: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #40: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #44: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
Your selected hotbar is 1
MC4FUN Hoşgeldiniz
MC4FUN Hoşgeldiniz
MC4FUN Hoşgeldiniz
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory player click 1 left
[MCC] Left clicking slot 1 in window #0
MC4FUN
MC4FUN
MC4FUN
>/inventory container click 36 right
[MCC] Cannot find container, please retry with explicit ID
play.mc4fun.net
play.mc4fun.net
>/inventory container click 11 right
[MCC] Cannot find container, please retry with explicit ID
play.mc4fun.net
>/inventory container click 11 right
[MCC] Cannot find container, please retry with explicit ID
>/inventory con
[MCC] Cannot find container, please retry with explicit ID
>/inventory
[MCC] Inventories:
 #0: Player Inventory
Basic usage: /inventory <player|container|<id>> <action>.
MC4FUN
MC4FUN
MC4FUN
>/inventory container click 11 right
[MCC] Cannot find container, please retry with explicit ID
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory chest click 11 right
[MCC] Cannot find container, please retry with explicit ID
>/inventory chest click 11 right
[MCC] Cannot find container, please retry with explicit ID
MC4FUN
MC4FUN
/inventory chest
MC4FUN
>/inventory player click 11 right
[MCC] Right clicking slot 11 in window #0
SwapSkipS joined the game
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory
[MCC] Inventories:
 #0: Player Inventory
Basic usage: /inventory <player|container|<id>> <action>.
>/inventory list
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
>/inventory player
[MCC] Inventory #0 - Player Inventory
 #36: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #40: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #44: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
Your selected hotbar is 1
MC4FUN
MC4FUN
MC4FUN
>/inventory player click 1 right
[MCC] Right clicking slot 1 in window #0
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory player click 28 right
[MCC] Right clicking slot 28 in window #0
MC4FUN
MC4FUN
>/inventory player
[MCC] Inventory #0 - Player Inventory
 #36: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #40: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #44: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
Your selected hotbar is 1
MC4FUN
>/inventory player click 0 right
[MCC] Right clicking slot 0 in window #0
play.mc4fun.net
>/inventory player
[MCC] Inventory #0 - Player Inventory
 #36: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #40: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #44: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
Your selected hotbar is 1
play.mc4fun.net
play.mc4fun.net
MrGuimauve joined the game
>/inventory container click 11 right
[MCC] Cannot find container, please retry with explicit ID
MC4FUN
MC4FUN
MC4FUN
>/inventory Example Menu click 11 right
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
_CesurAslan_ joined the game
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
_CesurAslan_ left the game
Qsaf joined the game
MrGuimauve left the game
_CesurAslan_ joined the game
MC4FUN
MC4FUN
MC4FUN
_CesurAslan_ left the game
Emrekrpnar joined the game
Emrekrpnar has made the advancement [Diamonds!]
Qsaf left the game
>log
{PREFIX} Lucifer31 > log
>/log
[MCC] log <text>: log some text to the console.
>/log text
[MCC] text
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
MC4FUN
MC4FUN
>/save
MC4FUN
Unknown command. Type "/help" for help.
>/savelog
Unknown command. Type "/help" for help.
Emrekrpnar left the game
>/keeplog
Unknown command. Type "/help" for help.
locate locatebiome log login logout loot
login logout
locate locatebiome log login logout loot
Emrekrpnar joined the game
play.mc4fun.net
play.mc4fun.net
list locate locatebiome log login logout loot lp luckperms luckperms:lp luckperms:luckperms luckperms:perm luckperms:permission luckperms:permissions luckperms:perms
play.mc4fun.net
enqn123 joined the game
>/survival
Unknown command. Type "/help" for help.
3kurusa5kofte joined the game
MC4FUN
MC4FUN
MC4FUN
3kurusa5kofte left the game
enqn123 left the game
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
Emrekrpnar left the game
MC4FUN
MC4FUN
MC4FUN
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
MC4FUN
MC4FUN
MC4FUN
>/inventory Generic_9x1 click 11 right
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory shulker click 11 right
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
>/inventory shulkerbox click 11 right
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
MC4FUN
MC4FUN
MC4FUN
>/inventory help id
[MCC] Unknown action.Available actions: list, close, click, drop.
>/inventory help drop
[MCC] Drop an item from inventory.Usage: /inventory <player|container|<id>> drop <slot> [all].
All means drop full stack
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory player drop all
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
MC4FUN
MC4FUN
MC4FUN
>/inventory player drop [all]
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory player drop 1 all
[MCC] No item in slot #1
>/inventory player drop 2 all
[MCC] No item in slot #2
MC4FUN
>/inventory player drop 3 all
[MCC] No item in slot #3
MC4FUN
MC4FUN
>/inventory player drop 4 all
[MCC] No item in slot #4
>/inventory player drop 5 all
[MCC] No item in slot #5
>/inventory player drop 6 all
[MCC] No item in slot #6
>/inventory player drop 26 all
[MCC] No item in slot #26
>/inventory player drop 36 all
[MCC] Dropped whole item stack from slot #36
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory player
[MCC] Inventory #0 - Player Inventory
 #36: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #40: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #44: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
Your selected hotbar is 1
>/inventory player drop 36 all
[MCC] Dropped whole item stack from slot #36
>/inventory player drop 36 all
[MCC] Dropped whole item stack from slot #36
>/inventory player drop 36 all
[MCC] Dropped whole item stack from slot #36
>/inventory player drop 36 all
[MCC] Dropped whole item stack from slot #36
>/inventory player drop 36 all
[MCC] Dropped whole item stack from slot #36
MC4FUN
>/inventory player drop 36 all
[MCC] Dropped whole item stack from slot #36
MC4FUN
MC4FUN
>/inventory player drop 1 all
[MCC] No item in slot #1
play.mc4fun.net
>/inventory player drop 36
[MCC] Dropped 1 item from slot #36
play.mc4fun.net
play.mc4fun.net
MC4FUN
MC4FUN
MC4FUN
>/inventory player drop 12
[MCC] No item in slot #12
>/inventory player drop 1
[MCC] No item in slot #1
play.mc4fun.net
>/inventory player
[MCC] Inventory #0 - Player Inventory
 #36: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #40: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #44: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
Your selected hotbar is 1
play.mc4fun.net
play.mc4fun.net
>/inventory player use
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
>/use
Unknown command. Type "/help" for help.
MC4FUN
MC4FUN
MC4FUN
>/inventory player click 1 left
[MCC] Left clicking slot 1 in window #0
>/inventory container click 12 right
[MCC] Cannot find container, please retry with explicit ID
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>/inventory player drop 12
[MCC] No item in slot #12
>/inventory player drop 36
[MCC] Dropped 1 item from slot #36
emirhareis joined the game
>/inventory container drop 12
[MCC] Cannot find container, please retry with explicit ID
MC4FUN
MC4FUN
MC4FUN
>/inventory enderchest drop 12
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
>/inventory ender_chest drop 12
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
emirhareis left the game
play.mc4fun.net
play.mc4fun.net
play.mc4fun.net
>`

**Comment by ReinforceZwei** [comment]
Could you try again with terrain and movement enabled? There was a similar case that server refused to open the inventory and enabling terrain and movement fixed the issue.

**Comment by amigoexp** [comment]
> Could you try again with terrain and movement enabled? There was a similar case that server refused to open the inventory and enabling terrain and movement fixed the issue.

OK. I set it TRUE. What should i write to use diamond? Isn't it _**/inventory player click 36 left**_

![image](https://user-images.githubusercontent.com/40539114/98841308-fa4cef00-2458-11eb-801d-1217b062e279.png)

**Comment by amigoexp** [comment]
```
>/inventory player click 15
[MCC] Left clicking slot 15 in window #0
>/inventory player click 15
[MCC] Left clicking slot 15 in window #0
>/inventory player click 16
[MCC] Left clicking slot 16 in window #0
>/inventory player click 17
[MCC] Left clicking slot 17 in window #0
>/inventory player click 18
[MCC] Left clicking slot 18 in window #0
>/inventory player click 19
[MCC] Left clicking slot 19 in window #0
>/inventory player click 20
[MCC] Left clicking slot 20 in window #0
>/inventory player click 21
[MCC] Left clicking slot 21 in window #0
MC4FUN
>/inventory player click 22
[MCC] Left clicking slot 22 in window #0
>/inventory player click 23
[MCC] Left clicking slot 23 in window #0
MC4FUN
>/inventory player click 24
[MCC] Left clicking slot 24 in window #0
MC4FUN
>/inventory player click 25
[MCC] Left clicking slot 25 in window #0
>/inventory player click 26
[MCC] Left clicking slot 26 in window #0
>/inventory player click 27
[MCC] Left clicking slot 27 in window #0
>/inventory player click 28
[MCC] Left clicking slot 28 in window #0
>/inventory player click 29
[MCC] Left clicking slot 29 in window #0
>/inventory player click 30
[MCC] Left clicking slot 30 in window #0
>/inventory player click 31
[MCC] Left clicking slot 31 in window #0
>/inventory player click 32
[MCC] Left clicking slot 32 in window #0
>/inventory player click 33
[MCC] Left clicking slot 33 in window #0
>/inventory player click 34
[MCC] Left clicking slot 34 in window #0
>/inventory player click 35
[MCC] Left clicking slot 35 in window #0
>/inventory player click 36
[MCC] Left clicking slot 36 in window #0
>/inventory player click 37
[MCC] Left clicking slot 37 in window #0
>/inventory player click 38
[MCC] Left clicking slot 38 in window #0
>/inventory player click 39
[MCC] Left clicking slot 39 in window #0
>/inventory player click 40
[MCC] Left clicking slot 40 in window #0
```

**Comment by amigoexp** [comment]
Update: 
`>/dig
20:25:31 [MCC] Please enable Terrain and Movements in the config file first.`

The folder;
![image](https://user-images.githubusercontent.com/40539114/98843523-261da400-245c-11eb-8cb7-d5ff62bb6603.png)
![image](https://user-images.githubusercontent.com/40539114/98843599-3cc3fb00-245c-11eb-95c3-a22ed24c9efd.png)

**Comment by amigoexp** [comment]
I installed it again however, i cannot enable _terrainandmovements_

![image](https://user-images.githubusercontent.com/40539114/98844678-bf998580-245d-11eb-8f4a-c71cb0f45074.png)

**Comment by amigoexp** [comment]
### **_Problem has been fixed_**

Here is the details.

```
 ▸ Başarıyla giriş yaptın.
Sana ait 2 hesap bulundu:
SwapSkipS, Lucifer31.
 Hoşgeldiniz
>/useitem
[MCC] Used an item
Lobi >> Bu dünyada mevcut değil.
[MCC] Inventory # 1 opened: . Example Menu .
[MCC] Use /inventory to interact with it.
>/inventory container
[MCC] Inventory #1 - . Example Menu .
 #0: RedStainedGlassPane x1 -   | Damage: 14
 #1: RedStainedGlassPane x1 -   | Damage: 14
 #2: RedStainedGlassPane x1 -   | Damage: 14
 #3: RedStainedGlassPane x1 -   | Damage: 14
 #4: RedStainedGlassPane x1 -   | Damage: 14
 #5: RedStainedGlassPane x1 -   | Damage: 14
 #6: RedStainedGlassPane x1 -   | Damage: 14
 #7: RedStainedGlassPane x1 -   | Damage: 14
 #8: RedStainedGlassPane x1 -   | Damage: 14
 #9: RedStainedGlassPane x1 -   | Damage: 14
 #10: RedStainedGlassPane x1 -   | Damage: 14
 #11: PlayerHead x1 - ★ Oyun Modları ★
 #12: RedStainedGlassPane x1 -   | Damage: 14
 #13: Sponge x1 - ★ Referans Sistemi ★
 #14: RedStainedGlassPane x1 -   | Damage: 14
 #15: PlayerHead x1 - ★ Profil ★
 #16: RedStainedGlassPane x1 -   | Damage: 14
 #17: RedStainedGlassPane x1 -   | Damage: 14
 #18: RedStainedGlassPane x1 -   | Damage: 14
 #19: RedStainedGlassPane x1 -   | Damage: 14
 #20: RedStainedGlassPane x1 -   | Damage: 14
 #21: Repeater x1 - ★ Ayarlar ★
 #22: RedStainedGlassPane x1 -   | Damage: 14
 #23: Diamond x1 - ★ Dükkan★
 #24: RedStainedGlassPane x1 -   | Damage: 14
 #25: RedStainedGlassPane x1 -   | Damage: 14
 #26: RedStainedGlassPane x1 -   | Damage: 14
 #27: RedStainedGlassPane x1 -   | Damage: 14
 #28: RedStainedGlassPane x1 -   | Damage: 14
 #29: RedStainedGlassPane x1 -   | Damage: 14
 #30: RedStainedGlassPane x1 -   | Damage: 14
 #31: RedStainedGlassPane x1 -   | Damage: 14
 #32: RedStainedGlassPane x1 -   | Damage: 14
 #33: RedStainedGlassPane x1 -   | Damage: 14
 #34: RedStainedGlassPane x1 -   | Damage: 14
 #35: RedStainedGlassPane x1 -   | Damage: 14
 #36: PlayerHead x1 - ★ Kredi ★
 #37: RedStainedGlassPane x1 -   | Damage: 14
 #38: RedStainedGlassPane x1 -   | Damage: 14
 #39: RedStainedGlassPane x1 -   | Damage: 14
 #40: RedStainedGlassPane x1 -   | Damage: 14
 #41: RedStainedGlassPane x1 -   | Damage: 14
 #42: RedStainedGlassPane x1 -   | Damage: 14
 #43: RedStainedGlassPane x1 -   | Damage: 14
 #44: RedStainedGlassPane x1 -   | Damage: 14
 #72: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #76: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #80: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
YusufOPS joined the game
>/inventory container click 11 right
[MCC] Right clicking slot 11 in window #1
[MCC] Inventory # 2 opened: . Oyun Modları .
[MCC] Use /inventory to interact with it.
Stawhooo left the game
>/inventory container click 11 right
[MCC] Cannot find container, please retry with explicit ID
>/inventory
[MCC] Inventories:
 #0: Player Inventory
 #1: . Example Menu .
 #2: . Oyun Modları .
Basic usage: /inventory <player|container|<id>> <action>.
>/inventory 2
[MCC] Inventory #2 - . Oyun Modları .
 #0: BlackStainedGlassPane x1 -   | Damage: 15
 #1: BlackStainedGlassPane x1 -   | Damage: 15
 #2: BlackStainedGlassPane x1 -   | Damage: 15
 #3: BlackStainedGlassPane x1 -   | Damage: 15
 #4: BlackStainedGlassPane x1 -   | Damage: 15
 #5: BlackStainedGlassPane x1 -   | Damage: 15
 #6: BlackStainedGlassPane x1 -   | Damage: 15
 #7: BlackStainedGlassPane x1 -   | Damage: 15
 #8: BlackStainedGlassPane x1 -   | Damage: 15
 #9: BlackStainedGlassPane x1 -   | Damage: 15
 #10: BlackStainedGlassPane x1 -   | Damage: 15
 #11: Grass x1 - ★ SURVIVAL ★ (53)
 #12: BlackStainedGlassPane x1 -   | Damage: 15
 #13: Bow x1 - ★ SKYBLOCK ★ (53)
 #14: BlackStainedGlassPane x1 -   | Damage: 15
 #15: Bricks x1 - ★ BUILDBATTLE ★ (0/20)
 #16: BlackStainedGlassPane x1 -   | Damage: 15
 #17: BlackStainedGlassPane x1 -   | Damage: 15
 #18: BlackStainedGlassPane x1 -   | Damage: 15
 #19: BlackStainedGlassPane x1 -   | Damage: 15
 #20: BlackStainedGlassPane x1 -   | Damage: 15
 #21: BlackStainedGlassPane x1 -   | Damage: 15
 #22: BlackStainedGlassPane x1 -   | Damage: 15
 #23: BlackStainedGlassPane x1 -   | Damage: 15
 #24: BlackStainedGlassPane x1 -   | Damage: 15
 #25: BlackStainedGlassPane x1 -   | Damage: 15
 #26: BlackStainedGlassPane x1 -   | Damage: 15
 #27: BlackStainedGlassPane x1 -   | Damage: 15
 #28: BlackStainedGlassPane x1 -   | Damage: 15
 #29: DiamondSword x1 - ★ PVP ★ (0/20)
 #30: BlackStainedGlassPane x1 -   | Damage: 15
 #31: DragonEgg x1 - ★ EGGWARS ★ (0/20)
 #32: BlackStainedGlassPane x1 -   | Damage: 15
 #33: GoldenApple x1 - ★ UHC ★ (0/20)
 #34: BlackStainedGlassPane x1 -   | Damage: 15
 #35: BlackStainedGlassPane x1 -   | Damage: 15
 #36: BlackStainedGlassPane x1 -   | Damage: 15
 #37: BlackStainedGlassPane x1 -   | Damage: 15
 #38: BlackStainedGlassPane x1 -   | Damage: 15
 #39: BlackStainedGlassPane x1 -   | Damage: 15
 #40: BlackStainedGlassPane x1 -   | Damage: 15
 #41: BlackStainedGlassPane x1 -   | Damage: 15
 #42: BlackStainedGlassPane x1 -   | Damage: 15
 #43: BlackStainedGlassPane x1 -   | Damage: 15
 #44: BlackStainedGlassPane x1 -   | Damage: 15
 #45: NetherStar x1 - ★ Lobby ★ (0/20)
 #46: BlackStainedGlassPane x1 -   | Damage: 15
 #47: BlackStainedGlassPane x1 -   | Damage: 15
 #48: BlackStainedGlassPane x1 -   | Damage: 15
 #49: WoodenAxe x1 - ★ Builder ★ (0/20)
 #50: BlackStainedGlassPane x1 -   | Damage: 15
 #51: BlackStainedGlassPane x1 -   | Damage: 15
 #52: BlackStainedGlassPane x1 -   | Damage: 15
 #53: NetherStar x1 - ★ Menü ★
 #81: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #85: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #89: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
>/inventory 2 click right 11
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
>/inventory 2 click right 11
[MCC] Basic usage: /inventory <player|container|<id>> <action>.: Inventory command
>/inventory 2 click 11 right
[MCC] Right clicking slot 11 in window #2
>/inventory player
[MCC] Inventory #0 - Player Inventory
 #36: Diamond x1 - ★  Lobi Menüsü ★  (Sağ Tıkla)
 #40: NetherStar x1 - ★  Oyun Modları Lucifer31 ★  (Sağ Tıkla)
 #44: Book x1 - ★  Profil Lucifer31 ★  (Sağ Tıkla)
Your selected hotbar is 1
sicipt3 joined the game
>/inventory 2 click 11 right
[MCC] Right clicking slot 11 in window #2
```
