### ISSUE TITLE
Using MCC on CentOS

### ISSUE THREAD

**Issue by CryBaby2332** [ORelio/Minecraft-Console-Client#1329]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

Hello to all users of this wonderful client. I ask for help in setting up the console on Linux. I had a VPS server on Windows, everything worked perfectly. Now I decided to try Linux, but there were some problems. I don't quite understand how to use the console on Linux. After entering all the commands, the MinecraftClient.exe file appears, but I do not know how to run it on Linux :D 
P.S. I am not very versed in Linux, so I am writing this issue :D There may also be errors here, since I use google translator/

**Comment by Mhowser** [comment]
You should visit this site to learn how to use the terminal
https://linuxjourney.com/

**Comment by OverHash** [comment]
You'll need to install mono and then use something like screen to keep your bash session alive.

**Comment by goncharovchik** [comment]
> **Prerequisites**
>  - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
>  - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
>  - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one
> 
> **Description of the Questions**
> Your question may contain the following items:
> * A concise description of your problem (I'm always frustrated when [...])
> * A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
> * Any solutions or features you've already considered (I tried to set this setting in config [...]).
> * If applicable, add screenshots to help explain your question
> 
> Hello to all users of this wonderful client. I ask for help in setting up the console on Linux. I had a VPS server on Windows, everything worked perfectly. Now I decided to try Linux, but there were some problems. I don't quite understand how to use the console on Linux. After entering all the commands, the MinecraftClient.exe file appears, but I do not know how to run it on Linux :D 
> P.S. I am not very versed in Linux, so I am writing this issue :D There may also be errors here, since I use google translator/

Ухади
