### ISSUE TITLE
Specify port

### ISSUE THREAD

**Issue by Lbniese** [ORelio/Minecraft-Console-Client#133]
Being able to specify another port than 25565 would be nice, since not all servers use the default port and it's not possible to auto-connect the client to a server etc atm - only manually.

**Comment by initsuj** [comment]
Any place where the server ip is taken should accept <ip>:<port>. For example, in the ini file, this should make the connection work on port 25585: serverip=mc.minenite.com:25585

**Comment by ORelio** [comment]
ou can also use the `server:port` syntax directly when prompted for server IP ;)

**Comment by Lbniese** [comment]
I did try to specify the port in the .ini file with the server:port format and it didn't work, so I had to do /connect to make it work.

But I will test it again and provide a screenshot :-)

**Comment by ORelio** [comment]
Okay, but that would be quite strange are the same function is used everywhere to parse the server IP and retrieve port information. Anyway, don't hesitate to reopen if you find an issue with port handling :)
