### ISSUE TITLE
SendPlaceBlock

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1330]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

mcversion: 1.12.2
SendPlaceBlock always returns false, no block is placed
![image](https://user-images.githubusercontent.com/35975332/98881466-e54d7b80-24ab-11eb-8de0-b0d4a7e06e5a.png)
![image](https://user-images.githubusercontent.com/35975332/98881416-c0590880-24ab-11eb-98f2-6ae26415c88b.png)
![image](https://user-images.githubusercontent.com/35975332/98881424-c51dbc80-24ab-11eb-949a-d57a9df2df60.png)

**Comment by Nekiplay** [comment]
![image](https://user-images.githubusercontent.com/35975332/98886052-06ff3080-24b5-11eb-83f2-17b72fcbb751.png)
This works, but the block coordinates are not read correctly

**Comment by ORelio** [comment]
Try using `Direction.Up` on the block below the one you want to place a block?

**Comment by Nekiplay** [comment]
> Try using `Direction.Up` on the block below the one you want to place a block?

I have tried all Direction

**Comment by mijiperki** [comment]
I have also just had this issue, also in 1.12.2 and can't get it to place at all, DigBlock still works though.

@Nekiplay Did you ever get this to work?

**Comment by ORelio** [comment]
OK so it seems specific to MC 1.12. With so many MC versions to handle, older versions are indeed less tested.
