### ISSUE TITLE
EntityMetadata crash

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1331]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots
mcversion: 1.14
![image](https://user-images.githubusercontent.com/35975332/98887869-8e9a6e80-24b8-11eb-9f40-9a06d9ee3b8f.png)

**Comment by ORelio** [comment]
Could you try commenting this `catch` block to get the actual exception location?
