### ISSUE TITLE
Movement and terrain issues

### ISSUE THREAD

**Issue by areny7** [ORelio/Minecraft-Console-Client#1334]
Is it possible for the author to solve the problem of terrain and movement? The server version is 1.16+, which I will use to make items. I will use the Autocraft, which will be a great help              Terrain & Movements currently not handled for that MC version.

**Comment by mexiscool** [comment]
i'm not sure but i remember autocraft script with crafting table working in 1.16

**Comment by ReinforceZwei** [comment]
AutoCraft doesn't require terrain and movement if you write down the coordinate of the crafting table in the configuration file.

It is required for auto-searching a crafting table, but it is not implemented yet.

**Comment by areny7** [comment]
> 我不确定，但我记得在1.16中使用制作表的autocraft脚本，它应该工作，导致SendPlaceBlock打开制作表时不检查地形处理。您启用了库存处理吗？

![image](https://user-images.githubusercontent.com/65305146/99033978-1ff00a80-25b7-11eb-827c-5109f915e759.png)
But if I use the Autocraft, it will prompt an error directly

What I want to achieve is for the character to take the watermelon pieces out of the box, use the table to synthesize the watermelon pieces, and then put them into the box. Can I achieve this?

**Comment by ReinforceZwei** [comment]
Since your computer cannot print out the error message correctly, I cannot tell you what is going wrong.

因為你的電腦不能正常顯示錯誤訊息，我不能告訴你出什麼問題了。

**Comment by areny7** [comment]
> 由于您的计算机无法正确打印出错误消息，因此我无法告诉您出了什么问题。
> 
> 因为你的电脑不能正常显示错误消息，我不能告诉你出什么问题了。

What information should I provide
