### ISSUE TITLE
SHIFT + RIGHT CLICKING certain blocks

### ISSUE THREAD

**Issue by imsalinas** [ORelio/Minecraft-Console-Client#1335]
I have a few questions about the console client and what I want to integrate with it. 

So I play on a Generator Minecraft server which requires a lot of afking. I have utilized the basic features of the console client (afking, simple scripts like /sell, etc.). However I want to take it a little bit further... In the server you can upgrade generators by doing SHIFT + RIGHT CLICK. 

I'm not sure what the most efficient way I would want this done, but I would like to SHIFT + RIGHT CLICK certain blocks (example: coal block, diamond block, emerald block, etc.) when that specific block is currently placed on the ground so it will upgrade to the next block (generator). I have no experience with C# scripting but I would not mind attempting to do accomplish this if I can get the right pointers.

Not sure if this will help with figuring out how to complete this, but when generators are upgraded they do not go back into inventory. They stay placed in their current position.

**Comment by ReinforceZwei** [comment]
You can use the ChatBot API and write a C# script to "click" a block by using the `SendPlaceBlock()` method. You may have a look at the [example script with chatbot](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) and the [ChatBot Class](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs)

**Comment by imsalinas** [comment]
So what program would I use to create this C# script? I've kinda done some research in the meantime and saw Visual Studio would work? As far as setting everything up what steps would I take?

**Comment by Nekiplay** [comment]
> So what program would I use to create this C# script? I've kinda done some research in the meantime and saw Visual Studio would work? As far as setting everything up what steps would I take?
> 
> EDIT:
> I have no clue what I am doing. I do not understand this at all LMAO

I am use Notepad++ )

**Comment by ORelio** [comment]
@imsalinas Easiest way is with Visual Studio. Clone the repository and open the project. Add your custom ChatBot for testring. Finally, when you are done, wrap it in a script as shown in sample scripts: https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config so that you can use your bot with precompiled MCC releases with /script yourbot.cs
