### ISSUE TITLE
Get current bot/player cord location

### ISSUE THREAD

**Issue by GOLOKKU** [ORelio/Minecraft-Console-Client#1336]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [424](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
how do i get current bot/player cord location using MCC command ?

**Comment by ReinforceZwei** [comment]
I don't think you can get player coordinate by using command only. You might need to use the ChatBot API.

**Comment by GOLOKKU** [comment]
but how ?

**Comment by Nekiplay** [comment]
> I don't think you can get player coordinate by using command only. You might need to use the ChatBot API.
/entity

**Comment by Nekiplay** [comment]
> but how ?
Other players example: https://pastebin.com/JprQnV6U

**Comment by ORelio** [comment]
`/move get`

**Comment by GOLOKKU** [comment]
ok thanks :)
