### ISSUE TITLE
Physics code

### ISSUE THREAD

**Issue by goncharovchik** [ORelio/Minecraft-Console-Client#1339]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**

Where is physics in the code?

**Comment by ReinforceZwei** [comment]
MCC doesn't support physics.

**Comment by goncharovchik** [comment]
> MCC doesn't support physics.

then how does it pass the bot check?

**Comment by ReinforceZwei** [comment]
There are tons of way for detecting bot. What kind of bot check are you referring to? Could you give a brief description?

**Comment by goncharovchik** [comment]
> There are tons of way for detecting bot. What kind of bot check are you referring to? Could you give a brief description?

Checking bot filter Upon entering the server, the player falls into the abyss, thus a check is made. You can look at this one mc.prostocraft.ru

**Comment by goncharovchik** [comment]
> There are tons of way for detecting bot. What kind of bot check are you referring to? Could you give a brief description?

The bot passes this check only if terrainandmovements equal to true.
Where in the code is the part responsible for terrainandmovements?

**Comment by ReinforceZwei** [comment]
The movement are done in `McClient.cs` and path finding methods are in `Movement.cs`.

**Comment by goncharovchik** [comment]
> The movement are done in `McClient.cs` and path finding methods are in `Mapping/Movement.cs`.

And the specific lines of the fall? from which line?

**Comment by ReinforceZwei** [comment]
Line 22 of `Movement.cs`, called from line 579 of `McClient.cs`

**Comment by goncharovchik** [comment]
Thank!
