### ISSUE TITLE
AutoRelog after connection failure should continue to try to

### ISSUE THREAD

**Issue by Cat7373** [ORelio/Minecraft-Console-Client#134]
Sometimes the server will shut down for a period of time.
I hope that during this period of time have been trying to connect
Instead of failures stopped working after

**Comment by ORelio** [comment]
In fact, the `Failed to ping this IP.` error message *can* be used as a kick message in `AutoRelog`.
You can also configure a larger amount of time between reconnect attemps :)

**Comment by Cat7373** [comment]
Retrieving Server Info...
23:52:57 System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:25565
Failed to ping this IP.
Server version :

Get stuck waiting for input

**Comment by ORelio** [comment]
Ah, you can disable interactive prompts with `exitonfailure=true` in the INI file.

**Comment by Cat7373** [comment]
exitonfailure = true will cause the program to exit after a connection failure

**Comment by ORelio** [comment]
Okay, after re-checking source code, you don't need to enable `exitonfailure` and my first statement was accurate: You just have to add `Failed to ping this IP.` to your `kickmessages.txt` (or whatever you named it), and the `AutoRelog` bot will automatically... try again after waiting again.

**Comment by Cat7373** [comment]
## MinecraftClient.ini
    [Main]
    login=Cat73
    password=-
    serverip=127.0.0.1

    #Advanced settings
    language=zh_CN
    botowners=
    consoletitle=%username%@%serverip% - Minecraft Console Client
    internalcmdchar=slash #use 'none', 'slash' or 'backslash'
    splitmessagedelay=2 #seconds between each part of a long message
    botmessagedelay=2 #seconds to delay between message a bot makes to avoid accidental spam
    mcversion=auto #use 'auto' or '1.X.X' values
    brandinfo=mcc #use 'mcc','vanilla', or 'none'
    chatbotlogfile=chatbot.log #leave empty for no logfile
    privatemsgscmdname=tell #used by RemoteControl bot
    showsystemmessages=true #system messages for server ops
    showxpbarmessages=true #messages displayed above xp bar
    terrainandmovements=false #uses more ram, cpu, bandwidth
    accountcache=memory #use 'none', 'memory' or 'disk'
    accountlist=
    serverlist=
    playerheadicon=true
    exitonfailure=false
    scriptcache=true
    timestamps=true
    
    [AppVars]
    #yourvar=yourvalue
    #can be used in some other fields as %yourvar%
    #%username% and %serverip% are reserved variables.
    
    [Proxy]
    enabled=false #use 'false', 'true', or 'login' for login only
    type=HTTP #Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
    server=0.0.0.0:0000
    username=
    password=
    
    [ChatFormat]
    builtins=true #support for handling vanilla and common message formats
    #public=^<([a-zA-Z0-9_]+)> (.+)$ #uncomment and adapt if necessary
    #private=^([a-zA-Z0-9_]+) whispers to you: (.+)$ #vanilla example
    #tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$
    
    #Bot Settings
    
    [Alerts]
    enabled=false
    alertsfile=alerts.txt
    excludesfile=alerts-exclude.txt
    beeponalert=true
    
    [AntiAFK]
    enabled=true
    delay=12000 #10 = 1s
    command=/list
    
    [AutoRelog]
    enabled=true
    delay=30
    retries=-1 #-1 = unlimited
    kickmessagesfile=kickmessages.txt
    
    [ChatLog]
    enabled=true
    timestamps=true
    filter=messages
    logfile=chatlog-%username%-%serverip%.txt

    [Hangman]
    enabled=false
    english=true
    wordsfile=hangman-en.txt
    fichiermots=hangman-fr.txt

    [ScriptScheduler]
    enabled=true
    tasksfile=tasks.ini

    [RemoteControl]
    enabled=false
    autotpaccept=true
    tpaccepteveryone=false

    [AutoRespond]
    enabled=false
    matchesfile=matches.ini

## kickmessages.txt
    Failed to ping this IP.
    
## Export
    Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
    20:15:54 You chose to run in offline mode.
    Retrieving Server Info...
    20:15:56 System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:25565
    Failed to ping this IP.
    Server version :

**Comment by Cat7373** [comment]
exitonfailure=true

## Export
    E:\game\MC\MinecraftClient>MinecraftClient.exe
    Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
    20:20:02 You chose to run in offline mode.
    Retrieving Server Info...
    20:20:04 System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:25565
    Failed to ping this IP.

    E:\game\MC\MinecraftClient>

**Comment by ORelio** [comment]
Oh, snap! Indeed that doesn't work. Kick messages weren't properly loaded in that error context.
Just fixed it in development builds. Thanks for your report :)

**Comment by Cat7373** [comment]
Thanks 0.0
