### ISSUE TITLE
Launching scripts from other directories?

### ISSUE THREAD

**Issue by mijiperki** [ORelio/Minecraft-Console-Client#1340]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

I can't seem to figure out how / if its possible to launch a new .cs chatbot with ScriptScheduler from a directory other than the current or "scripts" subfolder. Is there a way? (Currently trying to have multiple bots use the same single script location as is manually edited often and takes a long time to put in every individual bots folder)

**Comment by masterX244** [comment]
Tip: you can usually symlink folders on the Filesystem. That way you can "redirect" the scripts folder to a central location

**Comment by ORelio** [comment]
By default, MCC will look for scripts in its working directory and the scripts subfolder but as hinted by @masterX244 you can symlink the scripts folder to another location and put all scripts for your different instances in the same folder.
