### ISSUE TITLE
How to get server tps?

### ISSUE THREAD

**Issue by tunkusalim** [ORelio/Minecraft-Console-Client#1341]
ive checked the Command file and there is command for "/tps", but the problem is theres also "/tps" command on the server (i guess) because everytime i do "/tps" it shows ``[⚡] You do not have permission to use this command.``

then i tried using the AutoRespond instead, so i can check it through my other account 
```
...
MCC.SendText("Server TPS is: " + MCC.GetServerTPS() );
...
```

but there is an error
```
 [MCC] [AutoRespond] script test.cs
[MCC] [Script] Script 'test.cs' failed to run (LoadError).
[MCC] [Script] System.InvalidOperationException: 'MinecraftClient.ChatBot.GetServerTPS()' is inaccessible due to its protection level
```
how do i fix these?

<br><br>
``*related issues i can found`` #1268  #1138

**Comment by ReinforceZwei** [comment]
To use the server TPS command, use `/send /tps` instead. Else just do `/tps` for MCC's TPS counter.

**Comment by tunkusalim** [comment]
still not working and its shows ``[⚡] You do not have permission to use this command.``

**Comment by ReinforceZwei** [comment]
Are you using the latest version of MCC?

**Comment by cubic86** [comment]
Some servers don't give you the access to the `/tps` command.

**Comment by ORelio** [comment]
You need a ChatBot to access the ChatBot API.
```C#
//MCCScript 1.0

MCC.LoadBot(new TpsCheck());

//MCCScript Extensions

public class TpsCheck : ChatBot
{
    public override void Initialize()
    {
        SendText("Server TPS is: " + GetServerTPS());
        UnloadBot();
    }
}
```

**Comment by rizzybtw** [comment]
> You need a ChatBot to access the ChatBot API.
> 
> ```cs
> //MCCScript 1.0
> 
> MCC.LoadBot(new TpsCheck());
> 
> //MCCScript Extensions
> 
> public class TpsCheck : ChatBot
> {
>     public override void Initialize()
>     {
>         SendText("Server TPS is: " + GetServerTPS());
>         UnloadBot();
>     }
> }
> ```

Hello. I want to make the bot send the current tps to the general chat when someone writes “tps” to the chat. I configured matches so that the bot runs a script with this code when it sees the word "tps" in the chat. For some reason, everything is displayed normally in the console, as if the player is sending a message with the current TPS, but there is no message on the server. Someone help me please
