### ISSUE TITLE
When terrainandmovements is true i receive this error

### ISSUE THREAD

**Issue by telfrancesco** [ORelio/Minecraft-Console-Client#1342]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
When "terrainandmovements" is on "true", and i try to connect to any server i receive this error
![Screenshot_2](https://user-images.githubusercontent.com/22562779/99436986-1990c400-2912-11eb-9c44-760f392b26bc.png)

**Comment by ORelio** [comment]
This might happen if your server is using Forge and a mod changed the chunk format 🤔

**Comment by ORelio** [comment]
Could not reproduce
