### ISSUE TITLE
How to automatically mine at a cobble stone generator / mine in a straight line?

### ISSUE THREAD

**Issue by bruhmomento23453245** [ORelio/Minecraft-Console-Client#1343]
Hello! Is there any way to make the console client mine in a straight line or mine certain blocks at a cobble stone generator? Thanks in advanced!

**Comment by ReinforceZwei** [comment]
Please check out this [comment](https://github.com/ORelio/Minecraft-Console-Client/issues/1254#issuecomment-694694290)

**Comment by bruhmomento23453245** [comment]
Thank you!
