### ISSUE TITLE
the problem with OreMiner

### ISSUE THREAD

**Issue by kysteno4ek** [ORelio/Minecraft-Console-Client#1344]
I'm trying to run the OreMiner script, and I get this error. Who knows how to solve help..
 `[MCC] Update: Got error from ScriptLoader.Script+OreMiner: System.NullReferenceException: Object reference not set to an instance of an object.
   at ScriptLoader.Script.OreMiner.Update()
   at MinecraftClient.McClient.OnUpdate() in c:\Users\Гость\Desktop\Minecraft-Console-Client-master\MinecraftClient\McClient.cs:line 537`

**Comment by ReinforceZwei** [comment]
Did you enabled terrain and movement in the `MinecraftClient.ini` file?

**Comment by kysteno4ek** [comment]
> Вы включили рельеф и движение в `MinecraftClient.ini`файле?



> Did you enabled terrain and movement in the `MinecraftClient.ini` file?

no... I didn't know about it...

**Comment by kysteno4ek** [comment]
Thank you very much. Sorry for the stupid question...
