### ISSUE TITLE
[Script] Sending a command when a person who is not on the whitelist enters the server.

### ISSUE THREAD

**Issue by CrazyFoxxx** [ORelio/Minecraft-Console-Client#1346]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question
Hello guys. I need a script that would run when a person whose nickname is not on the whitelist logs into the server and sends a command.

**Comment by Nekiplay** [comment]
> **Prerequisites**
> 
> * [x]  I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
> * [x]  I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
> * [x]  I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one
> 
> **Description of the Questions**
> Your question may contain the following items:
> 
> * A concise description of your problem (I'm always frustrated when [...])
> * A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
> * Any solutions or features you've already considered (I tried to set this setting in config [...]).
> * If applicable, add screenshots to help explain your question
>   Hello guys. I need a script that would run when a person whose nickname is not on the whitelist logs into the server and sends a command.

https://pastebin.com/f70uiqNQ

**Comment by ORelio** [comment]
Copying/Pasting the code snippet here in case the paste expires on Pastebin:
```C#
//MCCScript 1.0
 
MCC.LoadBot(new Whitelist());
 
//MCCScript Extensions
 
public class Whitelist: ChatBot
{   
    public List<string> whitelistplayers = new List<string>();
    
    public override void Initialize()
    {
        LogToConsole("Bot enabled");
        // ADD WHITELISTED PLAYERS HERE
        whitelistplayers.Add("Player name 1");
        whitelistplayers.Add("Player name 2");
        whitelistplayers.Add("Player name 3");
    }
    public override void OnPlayerJoin(Guid uuid, string name)
    {
        bool allow = false;
        foreach (string playername in whitelistplayers)
        {
            if (playername == name)
            {
                allow = true;
                break;
            }
        }
        if (!allow)
            SendText("/kick " + name + " you not whitelisted");
    }
}
```
