### ISSUE TITLE
Support for /title command

### ISSUE THREAD

**Issue by thojo0** [ORelio/Minecraft-Console-Client#1347]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

**Feature description**
Is there a way to get the data of the /title command from a Minecraft Server?
I would like to be also able to autorespond to an specific title witch normaly displays big on your screen.
Maybe MCC could just write it in the normal Chat or something simellar so that autorespond can search for it with normal regex pattern.

**Comment by Vort** [comment]
Looks like you can use `OnTitle` function inside your script:
https://github.com/ORelio/Minecraft-Console-Client/blob/e06438b582def5b52fbffda7691da95f9f3b2c3e/MinecraftClient/ChatBot.cs#L242
