### ISSUE TITLE
is there a re-entry function?

### ISSUE THREAD

**Issue by kysteno4ek** [ORelio/Minecraft-Console-Client#1349]
does someone have a script or can write a script Account crashes (or server restart) then the account itself then went and wrote some commands? and is it even possible to implement this?

**Comment by ORelio** [comment]
You're looking for AutoRelog and ScriptScheduler:
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler
