### ISSUE TITLE
 Help me figure out the installation VkMessager.cs 

### ISSUE THREAD

**Issue by kysteno4ek** [ORelio/Minecraft-Console-Client#1350]
I don't know what to do with Newtonsoft.Json.dll. I don't know much about programming can you help me? 
`Download Newtonsoft.Json.dll and install it into the program folder Link: https://www.newtonsoft.com/json`

**Comment by CryBaby2332** [comment]
Лол, зачем тебе выводить твинков в вк? Если ты ставишь через пк, смысла в этом 0 (если конечно, не хочешь управлять ими с телефона). У меня твинки стоят на дедике, подключаюсь с помощью бота в дс или на прямую через mstsc (с пк и телефона соответственно). Честно, не вижу в этом смысла. 
+ Будет задержка небольшая.
P.S. ProstoCraft one love❤
