### ISSUE TITLE
Hangman game issue

### ISSUE THREAD

**Issue by AwsomerGamer** [ORelio/Minecraft-Console-Client#1351]
for some reason i can't start the hangman game 
ive tried saying start 
ive tried /script but it said this
![MCC](https://user-images.githubusercontent.com/74900146/99943035-9b1da180-2dab-11eb-9155-08cb2dc88762.png)
i have listed myself as a bot owner 
i have also made it enabled in the thing
is there a way to fix this?

**Comment by ORelio** [comment]
It's not a script you can load with /script, I think your message is not detected as a chat message. See:
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages

**Comment by ORelio** [comment]
See also: #1283
