### ISSUE TITLE
the problem with VkMessager

### ISSUE THREAD

**Issue by kysteno4ek** [ORelio/Minecraft-Console-Client#1352]
trying to run Vkmessager writes an error
 ` System.InvalidOperationException: The type or namespace name 'VkMessager' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by Nekiplay** [comment]
//dll NetsoftJSON.dll

**Comment by kysteno4ek** [comment]
> //dll NetsoftJSON.dll

new problem...
`Metadata file 'NetsoftJSON.dll' could not be found`

**Comment by Nekiplay** [comment]
![image](https://user-images.githubusercontent.com/35975332/100499582-90d51c00-318c-11eb-9b53-d76be58a5235.png)
https://github.com/Nekiplay/Minecraft-Console-Client-Scripts/raw/master/Newtonsoft.Json.dll

**Comment by kysteno4ek** [comment]
`The type or namespace name 'VkMessager' could not be found (are you missing a using directive or an assembly reference?)`

> ![image](https://user-images.githubusercontent.com/35975332/100499582-90d51c00-318c-11eb-9b53-d76be58a5235.png)
> https://github.com/Nekiplay/Minecraft-Console-Client-Scripts/raw/master/Newtonsoft.Json.dll
> If my dll doesn't fit
> 
> 1. Download the package via nuget
> 2. Find the dll where it was downloaded
> 3. Use downloaded dll from nuget

**Comment by Nekiplay** [comment]
namespace VkLongPoolClient not VkMessager

**Comment by kysteno4ek** [comment]
> namespace VkLongPoolClient not VkMessager

I don't understand please explain what to replace where ((

**Comment by ReinforceZwei** [comment]
You need to replace `MCC.LoadBot(new VkMessager(vkToken, chatId, botCommunityId));` to `MCC.LoadBot(new VkLongPoolClient(vkToken, chatId, botCommunityId));`

**Comment by kysteno4ek** [comment]
`The best overloaded method match for 'ScriptLoader.Script.VkLongPoolClient.VkLongPoolClient(string, string, System.Action<string,string,string,string,string,string>, System.Net.IWebProxy)' has some invalid arguments -_-
`

**Comment by ReinforceZwei** [comment]
Then you have to ask @Nekiplay for solution. I can't help.

**Comment by Nekiplay** [comment]
Example: https://pastebin.com/zFnZx94Z

**Comment by kysteno4ek** [comment]
> Example: https://pastebin.com/zFnZx94Z

`The name 'ProcessMsgFromVk' does not exist in the current context` I'm doing something wrong...

**Comment by Nekiplay** [comment]
Sorry my problem

**Comment by Nekiplay** [comment]
https://pastebin.com/jpBmP5zK

**Comment by kysteno4ek** [comment]
> https://pastebin.com/jpBmP5zK

`[MCC] [Script] Script 'jpBmP5zK.cs' failed to run (RuntimeError).
[MCC] [Script] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ScriptLoader.Script.VkLongPoolClient.Init()
   at ScriptLoader.Script.VkLongPoolClient..ctor(String token, String botCommunityId, Action`6 onMessageReceivedCallback, IWebProxy webProxy)
   at ScriptLoader.Script.VkMessager..ctor(String vkToken, String chatId, String botCommunityId)
   at ScriptLoader.Script.__run(CSharpAPI __apiHandler, String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MinecraftClient.CSharpRunner.Run(ChatBot apiHandler, ManualResetEvent tickHandler, String[] lines, String[] args, Dictionary`2 localVars, Boolean run) in c:\Users\Гость\Desktop\Minecraft-Console-Client-master\MinecraftClient\CSharpRunner.cs:line 138`

**Comment by Nekiplay** [comment]
you configured for access token and botCommunityId as well as chatId?

**Comment by kysteno4ek** [comment]
> you configured for access token and botCommunityId as well as chatId?

yes

**Comment by kysteno4ek** [comment]
> > https://pastebin.com/jpBmP5zK
> 
> `[MCC] [Script] Script 'jpBmP5zK.cs' failed to run (RuntimeError). [MCC] [Script] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
> at ScriptLoader.Script.VkLongPoolClient.Init()
> at ScriptLoader.Script.VkLongPoolClient..ctor(String token, String botCommunityId, Action`6 onMessageReceivedCallback, IWebProxy webProxy) at ScriptLoader.Script.VkMessager..ctor(String vkToken, String chatId, String botCommunityId) at ScriptLoader.Script.__run(CSharpAPI __apiHandler, String[] args) --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at MinecraftClient.CSharpRunner.Run(ChatBot apiHandler, ManualResetEvent tickHandler, String[] lines, String[] args, Dictionary`2 localVars, Boolean run) in c:\Users\Гость\Desktop\Minecraft-Console-Client-master\MinecraftClient\CSharpRunner.cs:line 138`

can someone help?

**Comment by kysteno4ek** [comment]
I decided... who has the same problem botCommunityId without " - " you need to write... Thank you to everyone who helped)

**Comment by kysteno4ek** [comment]
I was a little hasty with your conclusions... Writes that it works but doesn't send messages. help!

**Comment by Nekiplay** [comment]
> I was a little hasty with your conclusions... Writes that it works but doesn't send messages. help!

Have you got the correct chat ID? if the bot is in the chat, then it is desirable to give it administrator rights

**Comment by Nekiplay** [comment]
To get a conversation ID:
1. Invite a bot to a conversation
2. Run the script, get the peer_id this is the chat ID.
3. Use it to send messages
4. See example below:
![image](https://user-images.githubusercontent.com/35975332/100657434-136a0100-3370-11eb-97e8-2d9744822d57.png)

**Comment by Nekiplay** [comment]
> To get a conversation ID:
> 
> 1. Invite a bot to a conversation
> 2. Run the script, get the peer_id this is the chat ID.
> 3. Use it to send messages
> 4. See example below:
>    ![image](https://user-images.githubusercontent.com/35975332/100657434-136a0100-3370-11eb-97e8-2d9744822d57.png)

If you need the bot to write to you in ls, the peer_id will be equal to the ID of your VK page

**Comment by kysteno4ek** [comment]
nothing is clear in the screenshot

**Comment by kysteno4ek** [comment]
I don't understand what script to run

**Comment by kysteno4ek** [comment]
`MCC.LoadBot(new VkMessager(vkToken, chatId, botCommunityId));` above we wrote that you need to replace with `MCC.LoadBot(new VkLongPoolClient(vkToken, chatId, botCommunityId));`

**Comment by kysteno4ek** [comment]
`[MCC] [Script] System.InvalidOperationException: Identifier expected` what does this error mean?

**Comment by kysteno4ek** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/73881712/100861227-94c1b080-34a2-11eb-89d1-659d6123a762.png)
Writes that it works and messages are not sent to the VK...

**Comment by Nekiplay** [comment]
> ![Screenshot_5](https://user-images.githubusercontent.com/73881712/100861227-94c1b080-34a2-11eb-89d1-659d6123a762.png)
> Writes that it works and messages are not sent to the VK...

To send messages to VK you need to get the text from GetText () and in this method send the text to VK via Messages_Send_Text (id, message)

**Comment by Nekiplay** [comment]
Give me your script, no VK token

**Comment by Nekiplay** [comment]
> > ![Screenshot_5](https://user-images.githubusercontent.com/73881712/100861227-94c1b080-34a2-11eb-89d1-659d6123a762.png)
> > Writes that it works and messages are not sent to the VK...
> 
> Для отправки текста из чата тебе нужен
> ![image](https://user-images.githubusercontent.com/35975332/100868088-f1ca6000-34bc-11eb-84e0-a212106b4229.png)
> и уже в нем отправлять сообщение в вк

Пример
2000000020 ID чата
![image](https://user-images.githubusercontent.com/35975332/100868286-3c4bdc80-34bd-11eb-9275-aed21136b07e.png)

**Comment by kysteno4ek** [comment]
The name 'text1' does not exist in the current context

**Comment by Nekiplay** [comment]
> `The name 'text1' does not exist in the current context`

Кинь свой скрипт без токена бота, я скину готовый результат раз на столько все сложно, и можешь писать на Русском )

**Comment by Nekiplay** [comment]
> > `The name 'text1' does not exist in the current context`
> 
> Кинь свой скрипт без токена бота, я скину готовый результат раз на столько все сложно, и можешь писать на Русском )
Если прям все плохо плохо в плане скриптов могу помочь 05.12.2020 в дискорде Neki_play#4093
Можешь туда писать помогу чем смогу.
