### ISSUE TITLE
Some block can not find in "ItemType.cs"

### ISSUE THREAD

**Issue by XIAYM-gh** [ORelio/Minecraft-Console-Client#1356]
Hello,I have some questions.
When I editing my codes,I found something wrong,
It looks like :
_C:\projects\minecraft-console-client-chinesetranslate\MinecraftClient\Mapping\BlockPalettes\Palette116.cs(56,38): error CS0117: 'Material' does not contain a definition for 'NetherGoldOre' [C:\projects\minecraft-console-client-chinesetranslate\MinecraftClient\MinecraftClient.csproj ..]_(The Items not found?)
I don't know why because I'm updating to last commit. XD

**Comment by XIAYM-gh** [comment]
Oh,my English maybe wrong.

It's
_I want to update to the last commit_
and not is
_I'm updating to last commit_

Sorry

**Comment by ReinforceZwei** [comment]
Are you able to compile the project?

**Comment by ORelio** [comment]
@XIAYM-gh I think you are confusing [ItemType.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Inventory/ItemType.cs) with [Material.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Material.cs).
`ItemType` is for inventory, `Material` is for blocks. However, both the block and item exist:
https://github.com/ORelio/Minecraft-Console-Client/blob/b648e4f86df6208033951180fc12d8210b5b898b/MinecraftClient/Inventory/ItemType.cs#L599
https://github.com/ORelio/Minecraft-Console-Client/blob/53bd56100f604924aa513c0bfe0e9191459c8fe8/MinecraftClient/Mapping/Material.cs#L51
Make sure you are using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by XIAYM-gh** [comment]
oh,I see,I forgot that.

**Comment by XIAYM-gh** [comment]
Hum,I'm using the latest code,but my Notepad++ saved the old one,:(

**Comment by XIAYM-gh** [comment]
Oh,I fixed it,thanks.
