### ISSUE TITLE
Tree farm

### ISSUE THREAD

**Issue by CrazyFoxxx** [ORelio/Minecraft-Console-Client#1358]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

**Feature description**
A feature request should contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any alternative solutions or features you've considered.
* If applicable, add screenshots to help explain your request

**Comment by ReinforceZwei** [comment]
Perhaps this [pull request](https://github.com/ORelio/Minecraft-Console-Client/pull/1361) could solve your problem.
