### ISSUE TITLE
Minecraft Factions

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#136]
Hello,
I wanted to know Is there anyway to treat My Factions Chat As a private  message For the chat Our faction has There is either a Star a Plus or Nothing Followed by A Custom Name They Set A Space Then their Name Followed By A colon 
So Their Name Looks Like 
(Rank , , + , *, )(Faction Tag) (Name):

**Comment by CarbonNeuron** [comment]
No Parenthesis 
*(or)+(Coustom Name Contains A-Za-z0-9)(username):(message)
I tried Making my own Regex But it will not work 
(?:[\+\*])([A-Za-z0-9_]+) ([A-Za-z0-9_]+): (.*)$
Why Wont this work?

**Comment by ORelio** [comment]
Hello,
Sorry for the late reply.
Have you tried it on https://regex101.com/ ?
Faction name on your regex should not have parenthesis, eg
````
^[\+\*]*[A-Za-z0-9_]+ ([A-Za-z0-9_]+): (.+)$
````
matches
````
**Leader ORelio: hello
````

**Comment by CarbonNeuron** [comment]
My Question Is Now Is their Any way to make the chat Logger Only log this Chat?

**Comment by ORelio** [comment]
In the INI file, in ChatLogger, there is a setting for that ;)
