### ISSUE TITLE
TheAltening Support

### ISSUE THREAD

**Issue by HeyItskPan1c** [ORelio/Minecraft-Console-Client#1362]
I was curious if you would be able to add rhealtening support for premium altering users

**Comment by Mhowser** [comment]
There is no point as mojang is forcing everyone to migrate to a microsoft
account in the future.

**Comment by ORelio** [comment]
We do not add support for services offering stolen/for-rent accounts are they are too often misused.

**Comment by Tiebe** [comment]
I added MCLeaks support (similar to TheAltening) #1577
