### ISSUE TITLE
Unable to join servers.

### ISSUE THREAD

**Issue by ElijahRus250** [ORelio/Minecraft-Console-Client#1363]
**Prerequisites**
 - I am running the most recent build 
 - I have tried to use past closed issues for the same issue before opening this one
 - [Yes  ] I have set `debugmessages=true` in config to diagnose my issue
 - [Yes ] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
Bug: It will not allow me to join a server on my client. I am running Ubuntu 20.04 in docker. 

Logs: https://paste.dedimc.io/rovemugapo.sql

**Comment by ReinforceZwei** [comment]
Are you able to join your server with vanilla client?

**Comment by ElijahRus250** [comment]
Yes

**Comment by ElijahRus250** [comment]
Not sure what I did but its solved now
