### ISSUE TITLE
Get which block player is looking

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1364]
I am not sure if this is useful, but I wrote a method to do that. The following code require .Net Framework 4.6+ or .Net Core 1+ so I can't put it into the project now. I will leave the code here and wait until the project is ported to .Net 5. (or someone write a simple Vector3 class for me :P)
```cs
// Designed to work in ChatBot class
public Location LookingAtBlock(double yaw, double pitch)
{
    double rotX = (Math.PI / 180) * yaw;
    double rotY = (Math.PI / 180) * pitch;
    double x = -Math.Cos(rotY) * Math.Sin(rotX);
    double y = -Math.Sin(rotY);
    double z = Math.Cos(rotY) * Math.Cos(rotX);
    Vector3 vector = new Vector3((float)x, (float)y, (float)z);
    for (int i = 0; i < 5; i++)
    {
        Vector3 v = Vector3.Multiply(vector, i);
        Location l = GetCurrentLocation().EyesLocation() + new Location(v.X, v.Y, v.Z);
        l.X = Math.Floor(l.X);
        l.Y = Math.Floor(l.Y);
        l.Z = Math.Floor(l.Z);
        Block b = GetWorld().GetBlock(l);
        if (b.Type != Material.Air)
        {
            return l;
        }
    }
    return new Location();
}
```

@ORelio  Also I have a question about the yaw and pitch in `McClient.cs` Class. I tried to get the yaw and pitch value by using `yaw.GetValueOrDefault(0)` but they seems to be empty all the time, even after the `/look` command was executed. I got zero only. Am I doing something wrong?

**Comment by ORelio** [comment]
Your `Vector3` class looks very similar to MCC's [`Location`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Location.cs) class, which implements the `*` operator with a `double`.

**Comment by ORelio** [comment]
Regarding your other question, yaw and pitch are updated when this callback is invoked in McClient.cs:
```c#
UpdateLocation(Location location, float yaw, float pitch)
```
Maybe it's never called for some reason?

**Comment by ReinforceZwei** [comment]
But the `/look <yaw> <pitch>` command is working and the player is able to turn around. So I think that method is called.

**Comment by ORelio** [comment]
Yes, I think that maybe the yaw and pitch received **from server** is never passed correctly to McClient.cs. This method is called either when data is received from server **or** when a ChatBot or Command requests movement.

**Comment by ReinforceZwei** [comment]
Is there any reason that need to use the nullable type on `yaw` and `pitch`? (`float? yaw`)

**Comment by ORelio** [comment]
I don't recall very well but I think they were nullable because initially not set as long as not received from the server and not set by a bot or command.

**Comment by ReinforceZwei** [comment]
> Regarding your other question, yaw and pitch are updated when this callback is invoked in McClient.cs:
> 
> ```cs
> UpdateLocation(Location location, float yaw, float pitch)
> ```
> 
> Maybe it's never called for some reason?

I found the root cause after a year has passed. Basically `yaw` and `pitch` doesn't reflect the client real yaw and pitch, they are used for server location update only, and being set to `null` after update sent.
https://github.com/ORelio/Minecraft-Console-Client/blob/240468ad228a66dd0548a1049fe158a017d6b85f/MinecraftClient/McClient.cs#L600-L601

**Comment by ReinforceZwei** [comment]
It is working great now :tada:
![image](https://user-images.githubusercontent.com/39955851/111031545-08307200-8443-11eb-8afb-ae4146afdbfa.png)

**Comment by ORelio** [comment]
Good job! 👍
