### ISSUE TITLE
How did you get the bot filter to pass?

### ISSUE THREAD

**Issue by goncharovchik** [ORelio/Minecraft-Console-Client#1365]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**

How did you get the bot filters to pass? what is it based on?

**Comment by ORelio** [comment]
> How did you get the bot filter to pass?

By implementing terrain and movements.

**Comment by goncharovchik** [comment]
> > How did you get the bot filter to pass?
> 
> By implementing terrain and movements.

What packages?

**Comment by ORelio** [comment]
MCC is written from scratch without pre-made packages apart from libraries handling non-minecraft things.

**Comment by goncharovchik** [comment]
> MCC is written from scratch without pre-made packages apart from libraries handling non-minecraft things.

I mean which packets from server are processed  in terrarianandmovements?

**Comment by ReinforceZwei** [comment]
`ChunkData, MultiBlockChange, BlockChange, PlayerPositionAndLook`

**Comment by goncharovchik** [comment]
> `ChunkData, MultiBlockChange, BlockChange, PlayerPositionAndLook`

that is, is that all?

**Comment by ReinforceZwei** [comment]
Those are from my memory. If in doubt, please refer to https://wiki.vg/Protocol
