### ISSUE TITLE
Pinging server before joining

### ISSUE THREAD

**Issue by several5** [ORelio/Minecraft-Console-Client#1366]
On a regular minecraft client you click on refresh to ping your server(s). is it possible to add a feature who pings the server before joining it? 

Some servers use ping captchas upon joining.

**Comment by ReinforceZwei** [comment]
This feature already exists.

**Comment by several5** [comment]
> This feature already exists.

Does it do it automatically? or do i have to enable / setup something

**Comment by ORelio** [comment]
Indeed, by default MCC will ping the server to determine which Minecraft version is running on the server.
