### ISSUE TITLE
Some text data is not displayed in linux via ssh client

### ISSUE THREAD

**Issue by BadgerAAV** [ORelio/Minecraft-Console-Client#1367]
When I run mcc in win10 - everything is fine, but when I try to run on vps from ubuntu server 20.10 via putty ssh client, or AWS EC2 Instance Connect
![mcc-win10](https://user-images.githubusercontent.com/18073910/101133470-d759c900-3619-11eb-8066-0e9d0645ac16.png)
![mcc-ubuntu](https://user-images.githubusercontent.com/18073910/101133474-d7f25f80-3619-11eb-876e-ed92431f52ab.png)
![mcc-aws](https://user-images.githubusercontent.com/18073910/101134455-74693180-361b-11eb-8278-fce073d61630.png)

part of the program output is lost (gray text).
I tried it with the compiled version and tried to build it myself on this workstation, the result is the same.

**Comment by ReinforceZwei** [comment]
This an issue with the color scheme of putty. Please see [this issue](https://github.com/ORelio/Minecraft-Console-Client/issues/1260).

**Comment by BadgerAAV** [comment]
Putty fixed, but what about  AWS EC2 Instance Connect?

**Comment by ReinforceZwei** [comment]
You should ask AWS.

**Comment by BadgerAAV** [comment]
Ok, thx for quick replys

**Comment by ORelio** [comment]
For your information on Windows 10 you can just type `ssh login@serverip` in a command prompt to access your server.
