### ISSUE TITLE
New Captcha at Minecraft Server.

### ISSUE THREAD

**Issue by CrazyFoxxx** [ORelio/Minecraft-Console-Client#1368]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

Hi guys. The server on which I am using twinks recently installed a new captcha. Now, I need to enter the code from the picture. Can you see the image from the map at the MCC?

Sorry for the bad english, I use google translator.

**Comment by ReinforceZwei** [comment]
There is no way to render the map out since MCC is a console app.

**Comment by CrazyFoxxx** [comment]
I understand, but is there some way to find out the code?

**Comment by ReinforceZwei** [comment]
Use a GUI client...
