### ISSUE TITLE
Interacting with container blocks

### ISSUE THREAD

**Issue by MeowchChan** [ORelio/Minecraft-Console-Client#1369]
Is there a possible method to use to open a chest and take items out of it

**Comment by ORelio** [comment]
Opening chests is not implemented yet. Related issue: #183

**Comment by ORelio** [comment]
I'll close this one as duplicate to reduce the amount of open issues.

**Comment by ReinforceZwei** [comment]
Open chest was implemented. Use `/useblock x y z` command with the coordinate of your chest. You have to enable terrain and movement first.

**Comment by ORelio** [comment]
Ok so ignore what I just said 😅
