### ISSUE TITLE
} Can not enter

### ISSUE THREAD

**Issue by Cat7373** [ORelio/Minecraft-Console-Client#137]
OS Language: Chinese Simplified

You can do the following tests↓
/tellraw @p {"text":"test"}

**Comment by ORelio** [comment]
So you can't type `}` on a Chinese keyboard using the built-in `>_` console interactive prompt?

**Comment by Cat7373** [comment]
In fact, the instruction does not work copy and paste into

**Comment by ORelio** [comment]
Well, not sure of what I'm supposed to see in that case:
````
>/tellraw @p {"text":"test"}
test
>_
````
Tried that on Spigot 1.9 and latest MCC dev build :/

**Comment by Cat7373** [comment]
It may be the reason Chinese system bars- -

**Comment by Cat7373** [comment]
I have a few more questions, such as:
Enter two Chinese characters
Delete the contents entered
You will see only gone a word

**Comment by ORelio** [comment]
That's probably due to the interactive prompt not handling Chinese keyboards, in fact, it was completely written from sratch because by default you can't have a command prompt below and the chat above, so output apprears directly into the text being typed ex `> inp<output>ut` quite annoying ^^

So there is some code in MCC for automatically handling input and output: a prompt appears and handles typing character by character, then when some output needs to be done, it completely removes the prompt and text being typed, performs the output, and places back the prompte as it was before outputting some text.

Of course this has the drawback of having some issues with keyboards and languages we couldn't test. I think I'd need to setup some virtual machine running Windows in Chinese to reproduce your issue and maybe find out what's wrong with it :/

**Comment by Cat7373** [comment]
Before connecting to the server
That is, enter your username ip time and server version
Not the problem

This problem occurs after the connection to the server

**Comment by Cat7373** [comment]
If the network is interrupted, disconnected from the server, the problem disappears

**Comment by Cat7373** [comment]
OS：Windows 10 64bit

**Comment by Cat7373** [comment]
In this version the repetition problem
https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/32

**Comment by ORelio** [comment]
The IO prompt is used only when output is possible, so not used during login phase.
That's why it works before connecting to the server.
Is build 32 the first version affected. Is latest build affected?
Is "repetition problem" a different issue or the same issue?

**Comment by Cat7373** [comment]
I only tested version 32
I do not have previous 1.8 server for testing
So I chose this version
And in this version to reproduce the problem

**Comment by ORelio** [comment]
Okay, as far as I know all versions should have the same issue. That's because typing was almost completely re-done for allowing typing when chat messages are coming from the server. I don't know why it does not work on a Chinese keyboard... yet.

**Comment by Cat7373** [comment]
Here's a demo video
https://github.com/Cat7373/tmps

**Comment by 15Ibans** [comment]
I have the same issue; I try to type in "]" into the chat, however it doesn't seem to be registered. Pasting the character into the prompt works, though. I've tested it on my PC running Windows 10 and Windows 8.1 both with a standard QWERTY keyboard.

**Comment by ORelio** [comment]
I'll try making a keyboard input logger to better understand what's going on when you type some of those characters not properly handled in MCC.

**Comment by ORelio** [comment]
So, please use the latest development build and launch it this way:
On Windows cmd.exe or `.bat` file:
````
MinecraftClient.exe --keyboard-debug
````
On Mac or Linux, in a terminal:
````
mono MinecraftClient.exe --keyboard-debug
````
For instance, on my side, when pressing `]` I'm getting the following:
````
> MinecraftClient.exe --keyboard-debug
Console Client for MC 1.4.6 to 1.11.2 - v1.11.0 DEV - By ORelio & Contributors
Keyboard debug mode: Press any key to display info
Key: Oem4       Char: ] Modifiers: Alt, Control
````

**Comment by ORelio** [comment]
For your information the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) might finally fix your issue. See #382. 😉

**Comment by Cat7373** [comment]
I do not have windows now 😂
So I can not test it😂
