### ISSUE TITLE
Y coordinate is shown at the postion of the Z coordinate

### ISSUE THREAD

**Issue by oskarkraemer** [ORelio/Minecraft-Console-Client#1370]
/entity shows the Y coordiante at the postiton of the Z coordinate.

Fix:
string location = String.Format("X:{0}, Y:{1}, Z:{2}", Math.Round(entity.Location.X, 2), Math.Round(entity.Location.Y, 2), Math.Round(entity.Location.Z, 2));

insted of:
string location = String.Format("X:{0}, Y:{1}, Z:{2}", Math.Round(entity.Location.X, 2), Math.Round(entity.Location.Y, 2), Math.Round(entity.Location.Y, 2));

**Comment by ORelio** [comment]
Just fixed it, thanks for pointing that out!

**Comment by RuscalWorld** [comment]
> Just fixed it, thanks for pointing that out!

It looks like there is same error in line 149:
```C#
string location = String.Format("X:{0}, Y:{1}, Z:{2}", Math.Round(entity2.Value.Location.X, 2), Math.Round(entity2.Value.Location.Y, 2), Math.Round(entity2.Value.Location.Y, 2));
```

**Comment by ORelio** [comment]
Indeed, fixed the second occurrence of the bug. Thanks!
