### ISSUE TITLE
Place for not finished works, ideas / BoatFlyer draft

### ISSUE THREAD

**Issue by Vort** [ORelio/Minecraft-Console-Client#1372]
Hello.

I have made a draft for boat flying bot.
Here it is: https://github.com/Vort/Minecraft-Console-Client/commit/70d55894cc0e37328e939f8af1e340c79a60e9ac

It was interesting for me to learn how boatflying work.
But I don't need this code anymore.
So I want to share it with community.

Did not found a better place to do this.

Since this is a draft, it is not ready for merging.
But anyone can look at my code for ideas.

Prerequisites: `entityhandling=true` and player is sitting inside boat.
And, of course, server, which supports boatflying.

You may do anything you want with this report and code.

**Comment by ORelio** [comment]
Looks nice. Looks nice! What does it do exactly? Flying with a boat? Is it a glitch? 😃

**Comment by Vort** [comment]
> What does it do exactly? Flying with a boat?

Yes :)

> Is it a glitch?

It is a consequence of not precise checks in server code.
For example, some servers prevents flying without elytra.
But not prevents flying with boats.

Idea was taken from [Wurst's](https://wiki.wurstclient.net/hack) BoatFly module.
It was analyzed with proxy and slightly modified.
For example, moving up may be cosidered as flying.
But moving constantly up and down - as not flying (maybe jumping, I don't know).

**Comment by ORelio** [comment]
Oh, OK. Indeed, I'm not sure you can use a boat with MCC yet.

**Comment by Nekiplay** [comment]
> Oh, OK. Indeed, I'm not sure you can use a boat with MCC yet.

You can get into the boat at the expense of its installation, then I think you need a PlaceBlock on the water block
