### ISSUE TITLE
How does the digging work?

### ISSUE THREAD

**Issue by goncharovchik** [ORelio/Minecraft-Console-Client#1373]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**

Hello. Where is the digging completion package? I found sending the beginning of digging a block, but I cannot find the completion.

**Comment by ReinforceZwei** [comment]
We didn't implement it.

**Comment by goncharovchik** [comment]
> We didn't implement it.

and how then the bot understands when enough is enough?

**Comment by ReinforceZwei** [comment]
It doesn't know.

**Comment by ORelio** [comment]
MCC does not calculate the wait. It lets the server do it:
https://wiki.vg/How_to_Write_a_Client#Digging
See _If you don't want to be able to abort digging_

**Comment by goncharovchik** [comment]
> MCC does not calculate the wait. It lets the server do it:
> https://wiki.vg/How_to_Write_a_Client#Digging
> See _If you don't want to be able to abort digging_

Where is the digging code?

**Comment by ORelio** [comment]
DigBlock() in McClient.cs
