### ISSUE TITLE
Scan all messages (not just private or public)

### ISSUE THREAD

**Issue by bzigus** [ORelio/Minecraft-Console-Client#1374]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**

Ok, so I want to be able to monitor all chat messages such as, /f who 
![image](https://user-images.githubusercontent.com/22013942/101837046-73993980-3b0c-11eb-86f5-7c31d1e61d70.png)
or the faction chat 
![image](https://user-images.githubusercontent.com/22013942/101837089-86ac0980-3b0c-11eb-8f74-05b80390f5cd.png)
I use the GetText feature in a script, and then I use the if (IsChatMessage). I tried just scanning the messages in the GetText part however that did not work. Any assistance would be appreciated.

**Comment by ORelio** [comment]
*all* messaes will arrive in GetText(), then you can check if it's a chat message with `IsChatMessage()` or a private message with `IsPrivateMessage()`. By default the message has `§c` color codes, you can strip them with `GetVerbatim()`.
See also: [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs).

**Comment by Chtholly** [comment]
How is it possible to react to your own messages using a .cs file or maybe a regex ?

**Comment by ORelio** [comment]
@Chtholly See example in [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) and filter by username based on the current username.
