### ISSUE TITLE
Can start hangman, but cant guess letters. Help?

### ISSUE THREAD

**Issue by periskil** [ORelio/Minecraft-Console-Client#1375]
**Prerequisites**
 - [ x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

So I am able to start the hangman game by simply doing
/msg *name* start

I get the message saying the game has started, a word has been chosen, and good luck. But, whenever I message it a letter it seems to not work, and weirdly after waiting a little bit it randomly guessed "E" and do so again later on.

Let me know what I need to show you because I am a little lost, because the bot owner and chatformat should be working if I am able to start it i thought.

**Comment by goncharovchik** [comment]
> **Prerequisites**
>  - [ x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
>  - [x ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
>  - [ x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one
> 
> So I am able to start the hangman game by simply doing
> /msg *name* start
> 
> I get the message saying the game has started, a word has been chosen, and good luck. But, whenever I message it a letter it seems to not work, and weirdly after waiting a little bit it randomly guessed "E" and do so again later on.
> 
> Let me know what I need to show you because I am a little lost, because the bot owner and chatformat should be working if I am able to start it i thought.

Show your code

**Comment by ORelio** [comment]
Your client is only detecting PMs, not public messages. See [Detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages).

**Comment by periskil** [comment]
Are you able to help me then? I thought I had the regex right for the messages I want to read
[https://imgur.com/a/V2GAZb3](url)

^.(?:ISLAND)^V^.(?:[\d\d]) <([a-zA-Z0-9_]+)> (.+)$   is what I currently have down
I'm not the brightest when it comes to stuff like this

**Comment by ORelio** [comment]
Assuming all messages start with `ISLAND V [some number] USERNAME:`
```
^ISLAND V \[[0-9]+\] ([a-zA-Z0-9_]+): (.+)$
```
Try it at https://regex101.com/r/H0s1ZI/1

**Comment by periskil** [comment]
Thanks for the help! much love and sorry for the troubles 👍
