### ISSUE TITLE
bungeecord with forge problem

### ISSUE THREAD

**Issue by ninjaboy805** [ORelio/Minecraft-Console-Client#1376]
**Prerequisites**
 - [YES] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [YES] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [YES] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**

I am running on a server with forge and BungeeCord, the version is 1.12.2, and I have written 1.12.2 in the MinecraftClient.ini version, the server connection is lost, but I found that the modlist in the debugging feedback is empty, this could it be the reason? Because my robot has to enter the lobby first, and then select each server (they have most of the same mods, but some are different), it may cause the modlist to be empty. I want to know how to solve this situation(), thank you for your time

MCC：
Console Client for MC 1.4.6 to 1.16.4 - v1.16.4 - By ORelio & Contributors
AppVeyor build 427, built on Sat 11/28/2020 from commit 53bd561
[MCC] [Settings] Loading Settings from C:\Users\jh\Desktop\MCCC\MinecraftClient.ini
Resolving play.ltcraft.cn...
21:18:02 [MCC] [Translations] No translation file found for en. (Looked 'C:\Users\jh\Desktop\MCCC\\lang\mcc\en.ini'
21:18:02 [MCC] [Translations] No translation file found for system language (zh-CHS). (Looked 'C:\Users\jh\Desktop\MCCC\\lang\mcc\zh-CHS.ini'
21:18:02 Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
21:18:02 [SessionCache] Initializing FileSystemWatcher for file: C:\Users\jh\Desktop\MCCC\SessionCache.ini
21:18:02 No sessions could be loaded from disk
21:18:02 You chose to run in offline mode.
Success. (session ID: )
21:18:02 Using Minecraft version 1.12.2 (protocol v340)
Checking if server is running Forge...
§1 127 BungeeCord 1.8.x-1.16.x §f    §9§L『§b§lLTCraft§9§l』 §7§l多玩法混合   §7- §r 47 200
{"version":{"name":"BungeeCord 1.8.x-1.16.x","protocol":754},"players":{"max":200,"online":47,"sample":[]},"description":{"text":"    §9§L『§b§lLTCraft§9§l』 §7§l多玩法混合   §7- §r\n    §b§l\u003c\u003c§9§l◎§b§L------------双击我进服------------§9§L◎§b§l\u003e\u003e"},"modinfo":{"type":"FML","modList":[]}}
21:18:02 Server is running Forge without mods.
21:18:02 Server version : BungeeCord 1.8.x-1.16.x (protocol v754)
21:18:02 Server reports a different version than manually set. Login may not work.
21:18:02 [MCC] [AutoRelog] Launching with 10 reconnection attempts
21:18:02 [MCC] [AutoRelog] File not found: C:\Users\jh\Desktop\MCCC\kickmessages.txt
21:18:02 [MCC] [AutoRelog] Current directory was: C:\Users\jh\Desktop\MCCC
21:18:02 [MCC] [ScriptScheduler] File not found: 'C:\Users\jh\Desktop\MCCC\tasks.ini'
21:18:02 [MCC] [AutoRespond] File not found: 'C:\Users\jh\Desktop\MCCC\matches.ini'
21:18:02 Translations file loaded.
Version is supported.
Logging in...
21:18:02 Server is in offline mode.
Server was successfully joined.
Type '/quit' to leave the server.

**Comment by gedvinas123** [comment]
I get an error where the console says "Proxy is restarting" and then it just stops

**Comment by ninjaboy805** [comment]
> I get an error where the console says "Proxy is restarting" and then it just stops

If you want to try to access the server, maybe it needs vpn?

I want to know if I can fake a modlist by myself

**Comment by gedvinas123** [comment]
No, it doesnt require a vpn, just happens from time to time

> > I get an error where the console says "Proxy is restarting" and then it just stops
> 
> If you want to try to access the server, maybe it needs vpn?
> 
> I want to know if I can fake a modlist by myself

No, it doesnt require a vpn, just happens from time to time

**Comment by ORelio** [comment]
"Proxy is restarting" happens when the Bungeecord proxy is stopped, you may use AutoRelog to relog.

**Comment by ninjaboy805** [comment]
I tried again. This time I don’t know why my robot successfully entered the server lobby this time, but I can’t use /server to reach the sub-server I want. I tried /server on the java client, and it works. of. The debugmessage is turned on, but there is no feedback.

**Comment by ninjaboy805** [comment]
It seems that the admin wanted to make the sub-server mod different, but bungeecord seemed unable to do it. I was wrong to say that some sub-server mods were different. If this confused you, I’m sorry.

**Comment by ORelio** [comment]
Unfortunately if MCC logs back but hangs. MCC has a TCP timeout and a keepalive timeout when connected to the server, so if it hangs without doing anything that's not supposed to happen to begin with 😕

**Comment by ninjaboy805** [comment]
I tried it again.After I successfully entered the server lobby.Unable to enter the sub server.

>/server apple
12:54:58 Already connecting to this server!
>/server apple
13:02:44 Already connecting to this server!               //8min later
>/server lobby
13:03:08 You are already connected to this server!

**Comment by ORelio** [comment]
Closing this in favour of #1289
