### ISSUE TITLE
Joins for a few seconds

### ISSUE THREAD

**Issue by RealLexLuthor** [ORelio/Minecraft-Console-Client#1378]
I'm not really sure what's happening but every time I join a server my player will be online for a handful of seconds and then just stop.

(Raspberry pi 3 B +)

I've looked thru other reports and can't seem to find a fix.

Thanks

(Screenshot attached)

![Screenshot_33](https://user-images.githubusercontent.com/76274977/102705979-8c67c480-425b-11eb-846b-48313d8b3862.png)

**Comment by ReinforceZwei** [comment]
What device are you using? Did you enabled the terrain and movement?

**Comment by RealLexLuthor** [comment]
I haven't much clue what you are talking about.

**Comment by ORelio** [comment]
Closing this issue in favour of #1303
