### ISSUE TITLE
Struggle with /move on stairs & slabs

### ISSUE THREAD

**Issue by SwiftCH** [ORelio/Minecraft-Console-Client#1380]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Good evening

I'm struggeling with the /move command and the Y-coordinate... I need my account to move up / down some stairs or slabs to get to a specific point. But I always get kicked for flying if I move down a stair / slab, because the Y-coordinate does not change. 
I know that stairs / slabs are viewed as full blocks, but at the edge I also can't just move to the next block (and fall down for example).
And if I try to /move up or down, it still does not change the Y-coordinate.
/move x y z does also not work...

How do I solve this problem or is there another walk around?

Thank you very much

**Comment by nirikikry** [comment]
Can you be more specific? I have the same problem. Instead of where I need to cover the half-blocks. And does not want to go further and rise by 1.5.

**Comment by SwiftCH** [comment]
> 
> 
> Can you be more specific? I have the same problem. Instead of where I need to cover the half-blocks. And does not want to go further and rise by 1.5.

I just had to try & error... So if you're standing in front of a stair / step, just try to move one block per command and move diagonal. Sometimes use a /move up command to adjust the height. Just play around, after a while it "glitches" and moves up / down

**Comment by nirikikry** [comment]
> > Can you be more specific? I have the same problem. Instead of where I need to cover the half-blocks. And does not want to go further and rise by 1.5.
> 
> I just had to try & error... So if you're standing in front of a stair / step, just try to move one block per command and move diagonal. Sometimes use a /move up command to adjust the height. Just play around, after a while it "glitches" and moves up / down

Once he jumped and then immediately appeared on the block where he was standing. If you overdo it then kick for spickach.
There is no other method to make you climb stairs or semi-blocks ?
