### ISSUE TITLE
Help the feeble-minded

### ISSUE THREAD

**Issue by nirikikry** [ORelio/Minecraft-Console-Client#1381]
![Безымянный](https://user-images.githubusercontent.com/8069607/102900245-0e830380-447d-11eb-84d2-008c4492d90f.png)

How can I interact with # 36: Compass x1 ? To get to the anarchy games. And throw off at the same time the source that would be better to deal with the command "/inventory " (Sorry for my English)
*I noticed that I uploaded the wrong screenshot...

**Comment by ReinforceZwei** [comment]
`/inventory p 36 click`

**Comment by nirikikry** [comment]
![Безымянный](https://user-images.githubusercontent.com/8069607/102899863-9e747d80-447c-11eb-9e2a-b45e31128df3.png)

> How can I interact with # 36: Compass x1 ? To get to the anarchy games. And throw off at the same time the source that would be better to deal with the command "/inventory " (Sorry for my English)

**Comment by nirikikry** [comment]
> `/inventory p 36 click`

![Безымянный](https://user-images.githubusercontent.com/8069607/102900383-3f633880-447d-11eb-8e30-42d096c98721.png)
Why it doesn't work :c

**Comment by ReinforceZwei** [comment]
Sorry it should be `/inventory p click 36`

**Comment by nirikikry** [comment]
> Sorry it should be `/inventory p click 36`

Prompt. What should I do when I can't jump over a semi-block ? And then here through the command /move assigned where to go and he stood in front of the semi-block...
