### ISSUE TITLE
Sonsol non-clickable

### ISSUE THREAD

**Issue by nirikikry** [ORelio/Minecraft-Console-Client#1382]
![изображение_2020-12-22_225726](https://user-images.githubusercontent.com/8069607/102928005-0fca2580-44a9-11eb-856d-e8eb8dfe822c.png)
After that, when I register inventory,
then I click on "Анархия 5" 
After this action, I can no longer write anything in the console, but the chat works.

**Comment by ORelio** [comment]
Might be fixed now, sorry for not responding to your issue. Feel free to reopen if not fixed.
