### ISSUE TITLE
Problem with semi-blocks

### ISSUE THREAD

**Issue by nirikikry** [ORelio/Minecraft-Console-Client#1386]
![Безымянный33 (2)](https://user-images.githubusercontent.com/8069607/103134169-63628c00-46c0-11eb-9d9e-70817d626349.png)

Is there a solution to the problem ? The bot can't go and stand on the blocks. There is a problem. Happened that gluchilo but got up not on 12.5 and on 13. But then he returned to the same place immediately.

**Comment by ORelio** [comment]
Currently no because MCC does not know the shape of the blocks.

**Comment by ORelio** [comment]
Closing this in favour of #300
