### ISSUE TITLE
Need a ready-made script

### ISSUE THREAD

**Issue by nirikikry** [ORelio/Minecraft-Console-Client#1387]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

I need to click the right mouse button without end.
But with a delay of 1-2 milliseconds. I need it for AFC fishing. If you click very quickly, they will suspect that the button is not clamped and will be banned...
I don't know how to make scripts. But I have just an endless clicking with the right mouse button. Well, what could stop if that. Drop the finished file. I strongly blagadaren

**Comment by ReinforceZwei** [comment]
Are you looking for auto-fishing? Please see [README](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.md), the "Using Auto-fishing" section.

**Comment by nirikikry** [comment]
> Are you looking for auto-fishing? Please see [README](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.md), the "Using Auto-fishing" section.
"Using automatic fishing" He throws the rod and catches as soon as the bait appears.
On the server that I want to put only Twinkies are allowed.
What would a twink fish he needs to hold down the right mouse button or useitem with a millisecond of 1 I do not know how to loop. I don't know how to make scripts. I wanted someone to write a ready-made script.

**Comment by nirikikry** [comment]
Or a script that clamped the right mouse button

**Comment by ORelio** [comment]
There is no "right mouse button" at the protocol level. Right clicking in the game will trigger an action determined by the client based on what is displayer on screen, so there is no "rightA clicking" when there is no user interface.

**Comment by Nekiplay** [comment]
UseItem delay UseItem
