### ISSUE TITLE
Sending a command and Replying the results

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#139]
Is there any way of making it so when i send the command /bal (example) it would send back the balance it Got so like i would send a /f who and it would reply a f list?

**Comment by ORelio** [comment]
Currently there is no custom command mechanism, so it's not really possible to easily define something like /bal. However through a ChatBot it is possible to send command and retrieve the result. You can take a look at the [sample-script](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-script.cs) and [sample-script-with-chatbot](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-script-with-chatbot.cs) ;)

**Comment by TheSnoozer** [comment]
Since this questions has been answered and is inactive for quite so time I'm closing this issue as part of an issue cleanup. feel free to reopen if you still have any issues in getting this sorted. Otherwise please open a new issue.
