### ISSUE TITLE
Running MCC commands through a script

### ISSUE THREAD

**Issue by Werewolf6845** [ORelio/Minecraft-Console-Client#1391]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question

Hello, how can you make sure that when the launcher starts, the script is launched using the commands of the console itself and the commands are not sent to the server. For example, 10 seconds after logging into the server, use the script name command, and after 5 seconds, for example, change slot 1.
wait 10 000
/ script name
wait 5000
/ changeslot 1.
I tried to do it through task, I figured out how to run the script, but didn’t figure out how to run the command for MCC.

**Comment by ReinforceZwei** [comment]
You don't need the "/" in front of the command when using script.

**Comment by Werewolf6845** [comment]
but how to make sure that there was a delay between departures? "wait" doesn't work :(
And another question is whether it is possible to do all these actions in the task or do you need to run the script through the task where all the commands will be?

**Comment by ReinforceZwei** [comment]
Not "wait" but "sleep".

Regarding your second question, sorry I don't understand your sentence.

**Comment by Werewolf6845** [comment]
> Not "wait" but "sleep".
> 
> Regarding your second question, sorry I don't understand your sentence.

I figured out the second question, but something does not work and is activated at the same time
![image](https://user-images.githubusercontent.com/75979792/103163091-e8a18a00-4801-11eb-9a76-424c78bd1faa.png)

**Comment by ReinforceZwei** [comment]
Sorry my bad. It's "wait".

**Comment by Werewolf6845** [comment]
Thank you, but how to make the script run in addition to logging in with a certain message in the chat (or in the log).

**Comment by ORelio** [comment]
That's because you want to use ScriptScheduler instead: https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini to run scripts on server join.

**Comment by Werewolf6845** [comment]
Well, I already figured out how to do it at startup, now the problem is how to do something else, this script reacted to messages in the chat. For example, a typical message in the hub: The player opened the case and got ...
![image](https://user-images.githubusercontent.com/75979792/103175394-5eddd500-4872-11eb-9537-22923956235c.png)

**Comment by ORelio** [comment]
You can use **both** AutoRespond **and** ScriptScheduler if you want.
For announcement messages, use something like this:
```ini
[Match]
match=server is restarting
actionother=script restart.txt
```

**Comment by Werewolf6845** [comment]
> You can use **both** AutoRespond **and** ScriptScheduler if you want.
> For announcement messages, use something like this:
> 
> ```ini
> [Match]
> match=server is restarting
> actionother=script restart.txt
> ```

Спасибо
