### ISSUE TITLE
Create DLL

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1392]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Can I create a DLL that can execute MCC commands?

Across:
//dll path
//using dll

**Comment by Vort** [comment]
What it will add to regular script functionality?

**Comment by Nekiplay** [comment]
![image](https://user-images.githubusercontent.com/35975332/103280937-67114e00-49f3-11eb-99e8-4e961833c390.png)

I need my ddl to execute the command that ChatBotAPI has under certain conditions

**Comment by Vort** [comment]
I don't see why DLL is needed here.
It is more likely that you need IPC or API.

For example, you can implement simple protocol in MCC script.
Open TCP port, receive commands and retransmit them into chat.
