### ISSUE TITLE
Autofishing bug

### ISSUE THREAD

**Issue by several5** [ORelio/Minecraft-Console-Client#1393]
There's a bug with the autofishing script:

I have this setup for the autofishing
[Match]
match=loaded!
actionother=useitem
ownersonly=false

On the first time activating the autofishing script it works perfectly fine. But once in a while the server reboots itself and the autofishing won't continue (if you do /reco the same bug appears). On the next re-log my client activates /useitem but the rod goes into the water but will not pull any fish out. Basically after this the rod is stuck to where it doesn't get re-activated cause it's not pulling any fish. 

If there's any information needed please let me know!

**Comment by ReinforceZwei** [comment]
Should be fixed in #1395

**Comment by several5** [comment]
> Should be fixed in #1395

Thanks alot!!
