### ISSUE TITLE
Get author of public messages

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1394]
First of all a short view onto my problem:
I try to allow users with different groups (and prefixes) to access different commands of the bot in the public chat. But because the regex of the public chat filters out the prefix of the group, I cant use it to determine whether a user should be able to activate that action or not.

What i tried to fix the problem:
I was thinking of including the group prefix in the public regex, but that causes the problem that all functions like "ownersonly" and all my scripts would stop working, because the other groups would be shifted over by 1.
Then i tried to make an regex that outputs the first match as the last match which would fix the old problem, but it seems like thats not possible within a regex. 
Next i tried using named Groups as the first group of the regex (for Example: ^(?<group>[A-Za-z0-9_])) $ and getting the match in the "matches.ini" with $group and in a cs script with "match_group"(pretty much like match_u) 
but that also doesnt seem to be a feature/possibility.
Last i tried to add a new Chat format to the Section of the MCClient.ini 
(like this:
public=...
private=...
group=...
And using the same regex as in the public regex just with the Group part extra at the beginning. Then it sorted all of the chatmessages in the public category, which is understandable, because it cant match both and i think it will choose the upper one. But when i commented out the public format, everythin got put into the other category, even if they were matching the group regex. So i dont get that up and running either.

Would be very nice if you could give me a hint what else i could try or what I did wrong in my tries till now. Especially if their are ways to implement named regex groups and/or a own chat format for my usage. Please dont bother me to use a chatbot for reading that kind of messages in a seperate way, if its possible. Wouldnt be very effective and also not very easy to keep an eye on just for 1 feature. If theres no way to do it now please describe how to get it implemented in the future. 
Thanks a lot, hope you can help me.

Ps: Pls dont link me to another question, if not needed, because I already read all of the related ones and cant get an information out of them. Thanks

**Comment by ORelio** [comment]
Hi @xXjojaXx,

Since you're making a bot I'd suggest to run another regex manually when processing GetText() in addition of using the built-in IsPublicMessage or IsPrivateMessage methods in order to retrieve the user group.

Indeed, named groups are not automatically converted to $variables yet in AutoRespond.

**Comment by xXjojaXx** [comment]
First all it would be nice if you could help me with making a pull request for the named group variables. Second of all i have to ask what you mean with "run another regex manually when processing GetText()" Where do I have to include the "other regex" to be able to use it?

**Comment by xXjojaXx** [comment]
Ok, I got it up and running, thanks for your help :)

**Comment by xXjojaXx** [comment]
If it is useful for others thex can can contact me, if I should upload the file
