### ISSUE TITLE
Timing out while using inventory handling on hypixel skyblock

### ISSUE THREAD

**Issue by KibbeWater** [ORelio/Minecraft-Console-Client#1396]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
I am trying to make a bot use items on hypixel skyblock, I noticed that using UseItemInHand() would just fail so I guessed to use inventory handling. However in skyblock dungeons lobby the time between one of the messages sent is incedibly slow and times out. 

There are no additional debug messages after or previous to the timeout except login data

**Comment by KibbeWater** [comment]
CORRECTION:

it happens with inventory handling off, this issue is for the 1.10 - 1.16 protocols it seems

**Comment by Nekiplay** [comment]
At 1.15.2 everything works fine

**Comment by ORelio** [comment]
Unfortunately we could not reproduce this issue 😕
