### ISSUE TITLE
Using Tor Proxy?

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1399]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Can I conveniently and automatically connect to Tor Proxy?

**Comment by ORelio** [comment]
Apparently the Tor Browser already has a SOCKS proxy:
https://darkweblinks.org/2018/08/10/guide-how-to-use-tor-as-a-socks5-proxy/
MCC supports SOCKS proxies.

**Comment by Nekiplay** [comment]
and it is possible without groaning programs having only Tor?

**Comment by ORelio** [comment]
I'm not sure what you meant ("groaning programs") but apparently you don't need to launch the browser at all:
https://www.wikihow.com/Route-All-Network-Traffic-Through-the-Tor-Network
You can just download Tor and launch a proxy with it.
