### ISSUE TITLE
AutoDrop.cs Help

### ISSUE THREAD

**Issue by pIxel4oBg** [ORelio/Minecraft-Console-Client#1400]
Hello, as I am new to coding I literally do not understand how to use the AutoDrop script connected with the MCC.
I downloaded the file and put it into my console client folder.
And what is next ?
If you can, please provide me further information about the commands I am able to use and how to work with the script.

**Comment by ReinforceZwei** [comment]
You do not need to download AutoDrop script. It is embedded in the console client. 

You just need to open `MinecraftClient.ini` with a text editor, find the `[Autodrop]` section, set `enabled` to `true` and save the file. After that you will be able to use the `/autodrop` command.

**Comment by pIxel4oBg** [comment]
I did everything but it seems not to be working !
