### ISSUE TITLE
[SCRIPT] Tree farm with treecapitator

### ISSUE THREAD

**Issue by CrazyFoxxx** [ORelio/Minecraft-Console-Client#1401]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Hi guys. I play on a server where anti-cheat kicks players from the skyblock to the hub if they dig faster than possible (I and other participants talked about this here #1377).

I used to use a reworked oreminer.cs to dig the bottom block of the tree and a 2nd account to plant the seedlings. But with the advent of the new anti-cheat, this has become as impossible as digging blocks.

Could someone make a script for me that would put a sapling on the coordinates, and change the slot to the second, and break the tree?
I would be very grateful.

*Existing scripts do not work for me.

**Comment by Nekiplay** [comment]
Сервер ProstoCraft?

**Comment by CrazyFoxxx** [comment]
ды

**Comment by CrazyFoxxx** [comment]
Для гена скрипт то есть, но не будет работать на моей ферме

**Comment by Niklikq** [comment]
> Для гена скрипт то есть, но не будет работать на моей ферме

Скриптом поделишься?
