### ISSUE TITLE
How to make it so if internet goes out it keeps on trying to relog?

### ISSUE THREAD

**Issue by MrHickaru** [ORelio/Minecraft-Console-Client#1402]
<img width="410" alt="Screenshot_1" src="https://user-images.githubusercontent.com/67824982/103758583-60f52000-5038-11eb-9e38-f7e091861c09.png">

So there are frequent power cuts in my area and internet goes off sometimes.Is there some way to set the auto relog code in such a way that it keeps on trying to reconnect on loop until internet comes back? With the settings i got from your latest build its something like this

<img width="269" alt="Screenshot_2" src="https://user-images.githubusercontent.com/67824982/103758982-04463500-5039-11eb-8a0c-c5034601be8c.png">

right now, it tries to auto relog once, and if there is not internet it says connection failed as you can see in the first screenshot.

is there a way to make it so it will keep on trying to reconnect until it detects an internet connection? Like if connection fails, it does that **waiting 10 seconds before reconnecting** thing again. 

Thanks!

**Comment by ORelio** [comment]
You can add `Login failed` to the list of kick messages to reconnect when login fails.

**Comment by MrHickaru** [comment]
Thanks a lot! I love your software, in the future if i want to donate do you have a paypal or something?

**Comment by ORelio** [comment]
It's very nice of you, but lately contributors are doing most of the work, so I would't feel comfortable with donations 😉

**Comment by MrHickaru** [comment]
Oh okay :+1:
