### ISSUE TITLE
cs file send messages

### ISSUE THREAD

**Issue by August2211** [ORelio/Minecraft-Console-Client#1403]
How do i make a .cs file send an ingame message?

**Comment by ReinforceZwei** [comment]
Use ChatBot method `SendText("your message")`.

**Comment by August2211** [comment]
ty

**Comment by ORelio** [comment]
For future reference: Sample scripts are available here:
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config
