### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by August2211** [ORelio/Minecraft-Console-Client#1404]
It says "connected to server type /quit to leave" every attempty but its only on my 25th try it actually logs on to the server

**Comment by MrHickaru** [comment]
Download the latest https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts build, i had the same issue, this fixed it for me.

**Comment by MrHickaru** [comment]
replace this with .exe in your current folder

**Comment by ORelio** [comment]
Looks similar to #1303 although we were not able to diagnose why sometimes joining does not complete fully.

**Comment by August2211** [comment]
Solved it somehow changed some stuff dont know what fixed it but it works now
