### ISSUE TITLE
Launch multiple clients at once

### ISSUE THREAD

**Issue by MrHickaru** [ORelio/Minecraft-Console-Client#1405]
Is it possible to open more than one console client at the same time and have different accounts in each? I want to afk on a server with 3-4 alts. 

If possible I would love to know.

**Comment by ORelio** [comment]
Create a batch file:
```batch
@echo off
start /min MinecraftClient.exe example.ini  user1 pass1 serverip
timeout 5
start /min MinecraftClient.exe example.ini  user2 pass2 serverip
timeout 5
start /min MinecraftClient.exe example.ini  user3 pass3 serverip
timeout 5
start /min MinecraftClient.exe example.ini  user4 pass4 serverip
````
use notepad and save the script as .bat file then click on it to start multiple instances
