### ISSUE TITLE
Losing connection on console client after teleporting to a different server 

### ISSUE THREAD

**Issue by legouju** [ORelio/Minecraft-Console-Client#1406]
Hello,

When I connect to the main smp from the lobby with /server smp. This happens:
![image](https://user-images.githubusercontent.com/44247490/104084147-d4925b00-51f9-11eb-88c2-868bb35b47d3.png)

Server logs:
05:18:19 WARN]: [/XX.XXX.XX.XXX:XXXXX|FUNTlMES] -> UpstreamBridge - read timed out
[05:18:19 INFO]: [FUNTlMES] disconnected with: ReadTimeoutException : null

asked server owner to increase time out and still waiting on that
autho the server proxy's been having issues lately so not sure if its the client itself or not 

Linux version: arch Linux

Also just wondering is there like a system minimum requirement to run dis
cuz arch is running off a steam link:
https://en.wikipedia.org/wiki/Steam_Link

**Comment by periskil** [comment]
same thing happening to me currently, when running on an rpi, this is happening. It is specific to the smp server I am trying to connect to, for example Hypixel is stable, and when i transfer the MCC over to windows it works fine. Not very helpful but thought I would throw in that it still works on big servers, but some it doesn't work on.

**Comment by legouju** [comment]
If I had to guess it could just be processing power, as my steam link cpu is potato

**Comment by legouju** [comment]
update: i run into this same issue when I try running the client on my s20 (with userland + arch)

just disconnects so doesn't seems to be only limited to cpu power

**Comment by ORelio** [comment]
Unfortunately we could not find the root cause of this issue.

**Comment by redmine4404** [comment]
same problem here
