### ISSUE TITLE
Device for running mcc

### ISSUE THREAD

**Issue by August2211** [ORelio/Minecraft-Console-Client#1408]
Whats the best device for running mcc so i dont have to keep my computer on at all times?

**Comment by ReinforceZwei** [comment]
A raspberry pi 3B/4 should be enough for AFK.

**Comment by legouju** [comment]
^ autho a spare pc should prob be fine

Im rn trying to see if i can toss this on an android with termux to see if its possible
issue im having rn is cross-compiling mono to work on termux cuz im noob at it
https://github.com/IanusInferus/termux-mono

if anyone is able to do it plox send file e

**Comment by periskil** [comment]
you can also rent a vps, you can usually get ab 2gb ram with 80gb SSD for ~$5 a month

**Comment by legouju** [comment]
Found out u can get minechat for android:
https://www.minechatapp.com/

it's not as full fledged as MCC, but at least u can AFK and use server commands
autho it doesn't seem to be open source so tread carefully

**Comment by javaarchive** [comment]
I use https://repl.it with an external uptime checker like uptimerobot to auto afk almost 24/7 sometimes.

**Comment by August2211** [comment]
How do i run it in repl?

**Comment by August2211** [comment]
Says run isn't configured in the .replit file

**Comment by August2211** [comment]
nvm fixed that now it says permission denied

**Comment by tunkusalim** [comment]
i have same question, if anyone have spec recommendation to run 5-10 mcc at the same time?
also i have a webserver if is it possible to run them 24/7 there?

**Comment by AayanTDE** [comment]
would something like heroku work? i dont know how to go about this
