### ISSUE TITLE
Can we use Microsoft Accounts?

### ISSUE THREAD

**Issue by tunkusalim** [ORelio/Minecraft-Console-Client#1409]
ive bought few minecraft account but its all now using Microsoft Accounts for their login so I cant use it for AFKing on my server, also ive checked the #1397 but i still don't know if its already implemented for Microsoft login, and how to use it

**Comment by p5** [comment]
Just read through the commit changes.  It looks like all you need to do is add the following to MinecraftClient.ini under the serverip:
`type=microsoft`
Then just put your Microsoft account credentials in the login and password field.  I'm not sure how well it handles 2fa, so you may need to disable this if it doesn't work.

**Comment by tunkusalim** [comment]
Thank you, I tried it earlier but it still failed, but after turning on 2fa authentication its working fine now
