### ISSUE TITLE
[MCC] [Script] Script 'gug.cs' failed to run (LoadError). [MCC] [Script] System.InvalidOperationException: } expected

### ISSUE THREAD

**Issue by Christian913cin** [ORelio/Minecraft-Console-Client#1412]
Using a code already mentioned in the Issues Tab, I keep getting this error, to no avail.
`[MCC] [Script] Script 'gug.cs' failed to run (LoadError).
[MCC] [Script] System.InvalidOperationException: } expected`

//MCCScript 1.0

namespace test
{
    /// <summary>
    /// Example of message receiving.
    /// </summary>

    class Join : ChatBot
    {
        private string name;
        private HashSet<string> SeenPlayers = new HashSet<string>();
        public Join()
        {
            foreach (string username in LoadDistinctEntriesFromFile("SeenPlayers.txt"))
                SeenPlayers.Add(username);
        }
        public override void GetText(string text)
        {
            string message = "";
            string username = "";
            message = GetVerbatim(text);
            if (message.StartsWith("Join> ")) //If message is a player joining the server
            {
                username = message.Substring(6);
                text = GetVerbatim(text);
                ConsoleIO.WriteLine("Username: " + username);
                if (SeenPlayers.Contains(username))
                {
                    ConsoleIO.WriteLine("Join: The username " + username + " has already joined before.");
                }
                else //If username is not in SeenPlayers.txt
                {
                    ConsoleIO.WriteLine("Join: " + username + " has been logged into SeenPlayers.txt");
                    SeenPlayers.Add(username);
                    File.WriteAllLines("SeenPlayers.txt", SeenPlayers.ToArray());
                    SendText("Welcome to the Server for the first time " + username + "!");
                }
            }
        }
    }
}

**Comment by Christian913cin** [comment]
I fixed that but the issue I'm having now is the script loads but doesn't do anything
`//MCCScript 1.0

//MCCScript Extensions

 class Join : ChatBot
{
    private string name;
    private HashSet<string> SeenPlayers = new HashSet<string>();
    public Join()
    {
        foreach (string username in LoadDistinctEntriesFromFile("SeenPlayers.txt"))
            SeenPlayers.Add(username);
    }
    public override void GetText(string text)
    {
        string message = "";
        string username = "";
        message = GetVerbatim(text);
        if (message.StartsWith("Join> ")) //If message is a player joining the server
        {
            username = message.Substring(6);
            text = GetVerbatim(text);
            ConsoleIO.WriteLine("Username: " + username);
            if (SeenPlayers.Contains(username))
            {
                ConsoleIO.WriteLine("Join: The username " + username + " has already joined before.");
            }
            else //If username is not in SeenPlayers.txt
            {
                ConsoleIO.WriteLine("Join: " + username + " has been logged into SeenPlayers.txt");
                SeenPlayers.Add(username);
                File.WriteAllLines("SeenPlayers.txt", SeenPlayers.ToArray());
                SendText("Welcome to the Server for the first time " + username + "!");
            }
        }
    }
}
`

**Comment by ReinforceZwei** [comment]
```cs
//MCCScript 1.0
MCC.LoadBot(new Join());

//MCCScript Extensions
class Join : ChatBot
{
    private string name;

    private HashSet SeenPlayers = new HashSet();

    public override void AfterGameJoined()
    {
        SeenPlayers.Clear();
        foreach (string username in File.ReadAllLines("SeenPlayers.txt"))
            SeenPlayers.Add(username);
    }

    public override void GetText(string text)
    {
        string message = "";
        string username = "";
        message = GetVerbatim(text);
        if (message.StartsWith("Join> ")) //If message is a player joining the server
        {
            username = message.Substring(6);
            text = GetVerbatim(text);
            ConsoleIO.WriteLine("Username: " + username);
            if (SeenPlayers.Contains(username))
            {
                ConsoleIO.WriteLine("Join: The username " + username + " has already joined before.");
            } //If username is not in SeenPlayers.txt
            else
            {
                ConsoleIO.WriteLine("Join: " + username + " has been logged into SeenPlayers.txt");
                SeenPlayers.Add(username);
                File.WriteAllLines("SeenPlayers.txt", SeenPlayers.ToArray());
                SendText("Welcome to the Server for the first time " + username + "!");
            }
        }
    }
}
```

**Comment by Christian913cin** [comment]
`[MCC] [Script] System.InvalidOperationException: Using the generic type 'System.Collections.Generic.HashSet<T>' requires 1 type arguments`
With the New Script

**Comment by ReinforceZwei** [comment]
I edited the script above. Please try again.

**Comment by Christian913cin** [comment]
[MCC] [Script] Script 'gug.cs' failed to run (LoadError).
[MCC] [Script] System.InvalidOperationException: } expected

**Comment by Christian913cin** [comment]
`//MCCScript 1.0
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MinecraftClient.ChatBots
{
    class Join : ChatBot
    {
        private string name;

        private HashSet<string> SeenPlayers = new HashSet<string>();

        public override void AfterGameJoined()
        {
            SeenPlayers.Clear();
            foreach (string username in File.ReadAllLines("SeenPlayers.txt"))
                SeenPlayers.Add(username);
        }

        public override void GetText(string text)
        {
            string message = "";
            string username = "";
            message = GetVerbatim(text);
            if (message.StartsWith("Join> ")) //If message is a player joining the server
            {
                username = message.Substring(6);
                text = GetVerbatim(text);
                ConsoleIO.WriteLine("Username: " + username);
                if (SeenPlayers.Contains(username))
                {
                    ConsoleIO.WriteLine("Join: The username " + username + " has already joined before.");
                } //If username is not in SeenPlayers.txt
                else
                {
                    ConsoleIO.WriteLine("Join: " + username + " has been logged into SeenPlayers.txt");
                    SeenPlayers.Add(username);
                    File.WriteAllLines("SeenPlayers.txt", SeenPlayers.ToArray());
                    SendText("Welcome to the Server for the first time " + username + "!");
                }
            }
        }
    }
}`

[MCC] [Script] System.InvalidOperationException: } expected

Please help me with a fix it doesn't look to me a code problem as much as its a mcc problem.

**Comment by ReinforceZwei** [comment]
The syntax of your script is incorrect. Please see my script. Also, I could not reproduce your problem with my updated script. Are you using the latest version of MCC?

**Comment by Christian913cin** [comment]
I am using the latest build of MCC, I am also using your updated script, when I go to execute it via `/script chatbot.cs ` in the mcc client it now does nothing.

**Comment by Christian913cin** [comment]
Would it be possible for you just to make a repo or a dropbox of all the necessary files that are required to run this script. because something is not working on my end and I have no clue what it is.

**Comment by ReinforceZwei** [comment]
> I am using the latest build of MCC, I am also using your updated script, when I go to execute it via `/script chatbot.cs ` in the mcc client it now does nothing. 

If nothing is shown after executing the `/script` command, it means the script is loaded and should be working. 

According to your script, it will show some text only if a message that start with "Join>" was received. Have you tested it?

**Comment by Christian913cin** [comment]
Yes the SeenPlayer.txt does exist but nothing is happening at all.

**Comment by ORelio** [comment]
Why not adding debug messages? Here is an example (untested):
```C#
//MCCScript 1.0
MCC.LoadBot(new Join());

//MCCScript Extensions
class Join : ChatBot
{
    private string name;

    private HashSet<string> SeenPlayers = new HashSet<string>();

    public override void AfterGameJoined()
    {
        if (File.Exists("SeenPlayers.txt"))
        {
            LogDebugToConsole("Loading SeenPlayers.txt");
            SeenPlayers.Clear();
            foreach (string username in File.ReadAllLines("SeenPlayers.txt"))
            {
                LogDebugToConsole(" * " + username);
                SeenPlayers.Add(username);
            }
        }
        else
        {
            LogDebugToConsole("SeenPlayers.txt does not exist yet, initializing with an empty list");
        }
    }

    public override void GetText(string text)
    {
        string message = "";
        string username = "";
        message = GetVerbatim(text);
        if (message.StartsWith("Join> ")) //If message is a player joining the server
        {
            username = message.Substring(6);
            text = GetVerbatim(text);
            LogDebugToConsole("Username: " + username);
            if (SeenPlayers.Contains(username))
            {
                LogDebugToConsole("Join: The username " + username + " has already joined before.");
            } //If username is not in SeenPlayers.txt
            else
            {
                LogDebugToConsole("Join: Adding " + username + " into SeenPlayers.txt");
                SeenPlayers.Add(username);
                File.WriteAllLines("SeenPlayers.txt", SeenPlayers.ToArray());
                SendText("Welcome to the Server for the first time " + username + "!");
                LogDebugToConsole("Join: Added " + username + " into SeenPlayers.txt");
            }
        }
    }
}
````
Set `debugmessages=true` in config to see the messages. Or use `LogToConsole` instead to always display the message.

**Comment by Christian913cin** [comment]
```
>/script cws
[MCC] [Join] Loading SeenPlayers.txt
```
I enabled debug and it only shows this with your script also thank you both for taking your time to help me.

**Comment by ORelio** [comment]
Indeed, when the file is empty, it should not print anything after stating it's loading the file.
You can add a line to state when the file is loaded:
```C#
            LogDebugToConsole("Loading SeenPlayers.txt");
            SeenPlayers.Clear();
            foreach (string username in File.ReadAllLines("SeenPlayers.txt"))
            {
                LogDebugToConsole(" * " + username);
                SeenPlayers.Add(username);
            }
            LogDebugToConsole("Loaded SeenPlayers.txt"); // <--- NEW LINE HERE
```
