### ISSUE TITLE
System.InvalidOperationException: An object reference is required to access non-static member `ScriptLoader.Script.MCC'

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1413]
I get the error System.InvalidOperationException: An object reference is required to access non-static member ScriptLoader.Script.MCC when starting the following script:
[`Code`](https://pastebin.pl/view/2bc52281), I already tried something like var Sl = new ScriptLoader.Script() and replacing MCC stuff with sl.MCC.SetVar() and so on. Pls reply quickly because i am in a hurry.
Thanks a lot

**Comment by ReinforceZwei** [comment]
Since you are already using class, you may replace `MCC.SetVar()` with class property.

**Comment by ORelio** [comment]
Use the ChatBot API for large scripts:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs
Although for this API you can use `Settings.SetVar()` (https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Settings.cs#L764) from the extensions part of your script.
