### ISSUE TITLE
Auto Craft making items not in recipe

### ISSUE THREAD

**Issue by periskil** [ORelio/Minecraft-Console-Client#1414]
**Prerequisites**
 - [x ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x ] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x ] I have set `debugmessages=true` in config to diagnose my issue
 - [x ] I have redacted session tokens and passwords before attaching screenshots

So I am currently using AutoCraft to craft iron blocks, and it is currently making items other than an iron block (will show all in screenshots). As of now, it is making iron nuggets, trap doors, iron doors, and iron chestplates, as well as iron blocks. I figured it would just be making only iron blocks. My only guess as to why this is happening is that the iron is not evenly distributed, so there can be the off chance that an item slot/s is not used fully (having some iron remaining) causing the AutoCraft to make an item it shouldn't make?

I'm on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/67888857/104667222-3429b400-569b-11eb-8cdc-ae9d4885cb6f.png)
![image](https://user-images.githubusercontent.com/67888857/104667238-3ee44900-569b-11eb-9258-8b0a8838a512.png)

**Comment by ReinforceZwei** [comment]
Should be fixed in #1415. Please download the newest version and try again.
