### ISSUE TITLE
Can't join Hypixel

### ISSUE THREAD

**Issue by hmz04** [ORelio/Minecraft-Console-Client#1416]
![image](https://user-images.githubusercontent.com/44414423/104731056-114ade80-5733-11eb-9825-7ec0b7b7e7f8.png)

![image](https://user-images.githubusercontent.com/44414423/104731116-26277200-5733-11eb-9049-d01ebb39437b.png)

![image](https://user-images.githubusercontent.com/44414423/104731272-5ff87880-5733-11eb-8500-4b1086b39d2e.png)

I keep getting these 3 issues, i have no clue what i need to change to fix this, the ip im using is hypixel.net which is clearly an actual working server and i want to use this for hypixel specifically

**Comment by ReinforceZwei** [comment]
Seems like you are using a very old version of this program. Please download the newest version from https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by hmz04** [comment]
oh alright that works

thanks

also is there a list of examples or idk what you'd call it but info for auto respond and what i can do with it 
(like $u gets the users username) 

is there more?

**Comment by hmz04** [comment]
is there a way to match an exact message like i added !afk but with 
[Match]
match=!afk
action=send /tp $u -10.4 117 -12.4

it just checks if the message has !afk in it but i want it to only activate if the message says !afk

**Comment by ReinforceZwei** [comment]
You may use regex to do this.
```ini
[Match]
regex=^!afk$
action=send /tp $u -10.4 117 -12.4
```
