### ISSUE TITLE
Create a new Github release with download link inside

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1418]
Perhaps we could create a new release and put the AppVeyor download link in the description and hopefully reduce some issue like #1416, #1388

**Comment by ORelio** [comment]
That's the case here: https://github.com/ORelio/Minecraft-Console-Client/releases/tag/1.9.0
How about removing the zip files with executable? Do you think it would help?

**Comment by ReinforceZwei** [comment]
I think removing the zip file and changing the content a bit would be great, leaving the link to AppVeyor only.

```md
## ▶️ Grab latest version here: [Minecraft Console Client](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) ◀️
```

**Comment by ORelio** [comment]
Done!
