### ISSUE TITLE
Logout server without exit the program and unload bots and Feature request

### ISSUE THREAD

**Issue by marklai1998** [ORelio/Minecraft-Console-Client#142]
i'm writing a script using C#
i need to afk for a farm but i don't want a certain player see it for some reason
so i need to logout when he login
and log back in when he leave
So here is the problem

So first, can i logout server without exit the program and unload bots??

And second, anyt method can get the player list without joining the server??
i know i can do it in game ,but i wanna ask if it is possible in MCC
if not, i willing to see it at minecraft MCC 1.9.2 full release

**Comment by ORelio** [comment]
Hello,
Sorry for the late reply
 - You can logout but that requires swithching to another server
 - Scripts are automatically resumed once server is joined
Not sure how you would detect that a player leaves if you are not logged in to see him leave.
1.9.2 is already handled through dev builds ;)

**Comment by marklai1998** [comment]
![dsfsadfas](https://cloud.githubusercontent.com/assets/18364699/14452370/d6f6850e-00c0-11e6-8ad4-e5dbde97389c.PNG)
i can simply point it on the player counter to see who is inside the server
but i really don't know how can i handle it through mcc

**Comment by marklai1998** [comment]
if i can get that list, we can do a lot of things
like use mcc auto login your account to afk after you leave the server =]

**Comment by Pokechu22** [comment]
That list is found in the [Server List Ping](http://wiki.vg/Server_List_Ping).  MCC does perform a ping while logging in, but scripts aren't set up at that time.  However, I'll note that that list only contains up to 12 players (which are randomly selected from all of the players) - it may not be ideal for your purposes depending on how populated your server is.

**Comment by ORelio** [comment]
Also, i you detect that a player logins and then you logout, wouldn't he find it suspicious that you always log out when he logs in?

**Comment by ORelio** [comment]
ChatBots now have the ability to disconnect for a specified amount of time and then reconnect, see #252 for more details, especially [this message](https://github.com/ORelio/Minecraft-Console-Client/issues/252#issuecomment-286230589).
