### ISSUE TITLE
Selectively display debug messages in console

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1420]
Is there a possibility to block some messages for showing up in the mcc console? For example i dont want to see messages that start with test. If yes, how can I implement it. If no, can you open a pull request?
Thanks

**Comment by ReinforceZwei** [comment]
Unfortunately you cannot "block" specific messages.

**Comment by ORelio** [comment]
You're talking about messages from the server, not from the console client itself, right?

**Comment by xXjojaXx** [comment]
No, I am talinkg about all messages that are loggad into thr Console by MCC including the [MCC]... messages and also Server Messages because in much general uses there are many messages that get into the console frequently that aren't important and that get you to lose your vision at debugging etc. Other features. This leads into an general configurable "blocking function", that would be very usefull, as far as possible. Thanks for adding the new feature label and for helping

**Comment by xXjojaXx** [comment]
You should judge by yourself but I am thinking towards an option like the matches file or a configuration possibility in the Client.ini file to have the option to:
1. Filter console messages out that contain specific phrases (maybe even the option to give an array like: {"where", "find"} and so on
2. Filter messages out that begin with specific phrases

**Comment by ORelio** [comment]
I guess debug messages are enabled. Set `debugmessages=false` in config to disable them.

**Comment by xXjojaXx** [comment]
Of cause they are, I think you don't understand what I mean. Exactly in debugging its very useful not to see any crap coming into the console. Like i mentioned earlier their needs to be a functipn to specify which messages you want to see and which not, no mattee from which point they are coming in.

**Comment by ReinforceZwei** [comment]
What kind of debug are you doing? Is MCC itself or custom scripts?

**Comment by xXjojaXx** [comment]
For example if i debug one script I dont wanna see the starting messages from other scripts but the messages from the script i debug or the unimportant parts of the ingame chat. But i also have to see some messages that are coming out of the script i am working with. And there are much more cases with different messages you need and dont need, so it would be very useful to just be able to manage the filtering at your own

**Comment by ReinforceZwei** [comment]
Why don't just disable other scripts and turn off the server chat before debugging?

**Comment by xXjojaXx** [comment]
Thanks for your reply. Of cause its useful to disableother scripts to debug. But in my use and maybe many othrrs the mcc client is directly interacting with other users permanently and it has to be functional in the first place. But its ok if its just for chat messages. That even would help me and probably many more to be able to keep an eye on the console, because mine is very stacked with messages flying all around. Sry for my bad english. Looking forward to an implementation, if it really gets through. Thanks

**Comment by ORelio** [comment]
I think you'd need to have debug channels (categories) and MCC currently does not have that feature so of course as debug messages are not sorted you can't print them selectively. Currently there is no plan for that although contributions are welcome (as always).

**Comment by xXjojaXx** [comment]
Ok then it would be nice to see two features coming:
1. Be able to filter the chat messages with own configuration
2. Add the sorting of debug messages and make it possible to filter them too

Think I'm just going to wait until somebody has time and so on to implement it. Thanks for your many answers and the time.

PS: If there are any questions left, just ask. And of cause you can change the idea in whatever way, that you think would be the best to use it

**Comment by ReinforceZwei** [comment]
I made a "multi-channel" logger that can optionally display different type of messages (chat, error, debug, etc). I haven't implement the log filter yet.
https://github.com/ReinforceZwei/Minecraft-Console-Client/tree/log


> Add the sorting of debug messages

I don't get you meaning. How do you "sort" messages as they are logged to console immediately?

**Comment by Pokechu22** [comment]
I think they mean "categorizing" instead of "sorting" (as something separate from log level (chat/error/debug)).

**Comment by xXjojaXx** [comment]
Congrats on your work, but how to use it? If I just look at the code it seems like I just have to add these new attributes in the MinecraftClient.ini:
chatmessages=true                  # Show server chat messages
warningmessages=true               # Show warning messages
errormessages=true                 # Show error messages
infomessages=true                  # Informative messages (i.e Most of the message from MCC)
#chatfilter= [regex?]

**Comment by xXjojaXx** [comment]
Or is it there autinatically in the next update?
And one more time, big respect @ReinforceZwei

**Comment by ReinforceZwei** [comment]
You can download the latest build after the PR is merged and start using the new feature.

Put the following setting to your `MinecraftClient.ini` if you do not want to delete the old one.
```ini
[Logging]
# Only affect the messages on console.
debugmessages=false                # Please enable this before submitting bug reports. Thanks!
chatmessages=true                  # Show server chat messages
warningmessages=true               # Show warning messages
errormessages=true                 # Show error messages
infomessages=true                  # Informative messages (i.e Most of the message from MCC)
#chatfilter=                       # Regex for filtering chat message
#debugfilter=                      # Regex for filtering debug message
filtermode=blacklist               # blacklist OR whitelist. Blacklist hide message match regex. Whitelist show message match regex
```
