### ISSUE TITLE
How to run MCC with gui

### ISSUE THREAD

**Issue by OmarRahmanK** [ORelio/Minecraft-Console-Client#1421]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
* A concise description of your problem (I'm always frustrated when [...])
* A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
* Any solutions or features you've already considered (I tried to set this setting in config [...]).
* If applicable, add screenshots to help explain your question
I noticed that there is a folder called 'MinecraftClientGUI' in the source code for this project, however, I couldn't figure out how to run that version. I tried compiling it myself as well, but when trying to run 'MinecrafClientGUI.exe' I got an error saying 'File not found: MinecraftClient.exe'

![image](https://user-images.githubusercontent.com/49323171/104836018-68e66880-585f-11eb-8782-581479c258cb.png)

**Comment by ReinforceZwei** [comment]
You have to put `MinecraftClient.exe` (the console one) together with `MinecraftClientGUI.exe` in the same folder.
