### ISSUE TITLE
MCC freeze

### ISSUE THREAD

**Issue by Werewolf6845** [ORelio/Minecraft-Console-Client#1424]
**Prerequisites**
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [ ] I have set `debugmessages=true` in config to diagnose my issue
 - [ ] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
A bug report should contain the following items:
* A clear and concise description of what the bug is
* Steps to reproduce the behavior
* What I expected to happen instead
* If applicable, add screenshots to help explain your problem  
* Specify which kind of operating system you are running. 

Hello, there are such freezes from time to time and there is a loss of connection, and although there is an auto-reconnection, it does not work, the Program seems to freeze and only if you write any character, even without sending, auto-reconnection starts.

https://user-images.githubusercontent.com/75979792/105275277-fef7f700-5baf-11eb-84e1-25c8e5e8ee0e.mp4

**Comment by ReinforceZwei** [comment]
Are you using the latest version of MCC? Also the video you provided doesn't shown anything.

**Comment by Werewolf6845** [comment]
![image](https://user-images.githubusercontent.com/75979792/105275558-affe9180-5bb0-11eb-914e-266f2a6a5084.png)
In the video, this process

**Comment by ReinforceZwei** [comment]
Are you using the latest version of MCC? If not, please download the latest version of MCC and try again.

**Comment by ReinforceZwei** [comment]
Then you should ask @Vort for support since you are using a custom version.

**Comment by Werewolf6845** [comment]
okay
