### ISSUE TITLE
Having an issue with the autodrop feature

### ISSUE THREAD

**Issue by UnknownVariables-here** [ORelio/Minecraft-Console-Client#1429]
This error pops up after joining a server while autodrop is enabled, Unsure what it means or how to fix it. Im using the latest release.

[MCC] Update: Got error from MinecraftClient.ChatBots.AutoDrop: System.Collectio
ns.Generic.KeyNotFoundException: The given key was not present in the dictionary
.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MinecraftClient.ChatBots.AutoDrop.OnUpdateFinish()
   at MinecraftClient.ChatBots.AutoDrop.Update()
   at MinecraftClient.McClient.OnUpdate()

**Comment by UnknownVariables-here** [comment]
So I inserted the changes linked in the pull request and made a build from source with the changes, no longer having the error but auto drop isn't working, is it something server sided ?

**Comment by ReinforceZwei** [comment]
Could you enable debug message and try again? Do you see some message like `Cannot find inventory #0`?

**Comment by UnknownVariables-here** [comment]
Yes [MCC] [AutoDrop] Cannot find inventory 0!

**Comment by ReinforceZwei** [comment]
Do the message shows every time you start MCC?

**Comment by UnknownVariables-here** [comment]
yes, auto-drop works fine on localhost tho.

**Comment by ReinforceZwei** [comment]
If so, could you provide the server address so that I could try to reproduce the issue?

**Comment by UnknownVariables-here** [comment]
Sure, Play.MineSaga.Net then joining one of the sub servers /space or /western

**Comment by ReinforceZwei** [comment]
For some reason the player inventory was closed by server:
![image](https://user-images.githubusercontent.com/39955851/106275883-8eb53980-6271-11eb-8b8d-d66790b85027.png)

I am not sure how vanilla client would handle the case like this. So for now, I will make MCC to clear the inventory without deleting it. That should fix the problem.

**Comment by UnknownVariables-here** [comment]
Interesting, Thank you

**Comment by ReinforceZwei** [comment]
`PacketDump` is a little ChatBot wrote right before I start debugging this. You can find the code at [here](https://github.com/ReinforceZwei/Minecraft-Console-Client/blob/packet-dump/MinecraftClient/ChatBots/PacketDump.cs).
