### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by hmz04** [ORelio/Minecraft-Console-Client#1432]
Hi, I wanted to ask if its possible for me to select a random text from a list each time i send a command using scripts

for example if i wanted it to select from "Hi how are you" "hello how are you" "welcome" how would i make it select and send one of these random messages

**Comment by ReinforceZwei** [comment]
Please see [#972 comment](https://github.com/ORelio/Minecraft-Console-Client/issues/972#issuecomment-620771307)
