### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by hmz04** [ORelio/Minecraft-Console-Client#1433]
Is there a documentation or a tutorial on how to make scripts

if not can someone help me with the following: 
i want the alt to start the script on login

Then use a random command using c# script and after that use a random C# script to select a random message to send and then loop this

thanks

**Comment by ReinforceZwei** [comment]
You could re-open your last issue if you still have question about writing script.

> Is there a documentation or a tutorial on how to make scripts

Check out the [sample configuration file and example scripts](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config).

> i want the alt to start the script on login

You can use `ScriptScheduler` to start a script on login. See [sample-tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini) for example.

> Then use a random command

I think your last issue have solved this question already. Just create a `.cs` script and paste the content into the file and modify the messages to suit your need.
```cs
//MCCScript 1.0

string[] commands = new[] {
    "send command1", // <- Modify them to suit your need
    "send command2",
    "send command3"
};

int randomIndex = new Random().Next(0, commands.Length);
string randomCommand = commands[randomIndex];
MCC.PerformInternalCommand(randomCommand);
```

**Comment by hmz04** [comment]
how would i loop 2 scripts so it keeps going through both

**Comment by ReinforceZwei** [comment]
You can use `ScriptScheduler` to run script on interval.
```ini
[Task]
triggerOnInterval=true
timeInterval=30
action=script yourscript.cs
```

**Comment by hmz04** [comment]
last question is it possible to make it say in the console when a command is executed

**Comment by ReinforceZwei** [comment]
```cs
//MCCScript 1.0

string[] commands = new[] {
    "send command1", // <- Modify them to suit your need
    "send command2",
    "send command3"
};

int randomIndex = new Random().Next(0, commands.Length);
string randomCommand = commands[randomIndex];
MCC.PerformInternalCommand(randomCommand);
MCC.LogToConsole("Command executed!");
```
