### ISSUE TITLE
MCC going around anti-bot plugin

### ISSUE THREAD

**Issue by Dzygius** [ORelio/Minecraft-Console-Client#1434]
I'm playing in offline server and they implemented plugin that you need to press a button to be able to stay afk.

I know that there is a inventory handling, but i cant figure it out...

Ill add a screenshot of the example
https://imgur.com/wVzqokX
![image](https://user-images.githubusercontent.com/45564904/106160246-4a04a200-618e-11eb-997c-c00abdc99b37.png)
i need to press a green button

**Comment by ReinforceZwei** [comment]
List the inventory and find out the slot ID of the your target item.
`/inventory c`
For example slot ID of 13
`/inventory c click 13`
