### ISSUE TITLE
Auto rejoin

### ISSUE THREAD

**Issue by PrivateServersGANG** [ORelio/Minecraft-Console-Client#1436]
Alright with the server i play on when the server restarts it sends u to the "hub" how do i make it everytime it does that it runs like 2 commands

**Comment by UnknownVariables-here** [comment]
Using auto respond, in MinecraftClient.ini make sure
 [AutoRespond]
enabled=false
is set to true. 
Then create a file called matches.ini and in there you'd want to use something like:

[Match]
match=server is restarting
actionother=script restart

(might need to use regex)

then make a txt file named restart
and in it you can list instructions like
wait 60
send 1stcommand
wait 10
send 2ndcommand

**Comment by PrivateServersGANG** [comment]
Where would i put the script restart thing what folder?

**Comment by ReinforceZwei** [comment]
In the same folder where you put your `MinecraftClient.exe` at.

**Comment by PrivateServersGANG** [comment]
alright alsoc an i get yalls discors so i dont needa post here 24 if i need help?

**Comment by ReinforceZwei** [comment]
If you have further question, feel free to ask here or open an new issue.

**Comment by PrivateServersGANG** [comment]
okay well for the "anotherother= script restart" where would that file be and what would the name be just can u explait it further

**Comment by PrivateServersGANG** [comment]
Like when the server restarted i need it to send /useitem /inventory c click 5 via console command not ingame since it dont have /join or anything

**Comment by PrivateServersGANG** [comment]
Ima close since none is responding
