### ISSUE TITLE
Polish terrain API documentation that is accessible from scripts

### ISSUE THREAD

**Issue by Cat7373** [ORelio/Minecraft-Console-Client#144]
Some extended functionality through plugins support
For example: terrainandmovements

Plug-in to provide some API
For example more protocols, more commands

**Comment by ORelio** [comment]
Currently, terrain API is accessible from scripts, although not very documented.
See [sample-script-with-world-access](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-script-with-world-access.cs) for an example of world access.

Plug-in API is already accessible, courtesy of @Pokechu22 in 1ea8f119d91e3fa4e2db812998fdaabd4825b005.
You can use `RegisterPluginChannel()` override `OnPluginMessage()` and use `SendPluginChannelMessage()`, all of this from a ChatBot defined in a C# script.

**Comment by Cat7373** [comment]
https://github.com/PrismarineJS/mineflayer
Create Minecraft bots with a powerful, stable, and high level JavaScript API.

**Comment by ORelio** [comment]
I think this old issue has been resolved since it was created. Closing as resolved.
