### ISSUE TITLE
regex auto respond

### ISSUE THREAD

**Issue by hmz04** [ORelio/Minecraft-Console-Client#1441]
how would i use regex to automatically make my bot thank people for cookies?  

The message is either 
You received 1 cookie from username!
or 
You received (2-6) cookies from username! 

Can someone please help me figure out how to make this

**Comment by ORelio** [comment]
Hello,
1. Make sure your chat messages are detected. See _Detecting chat messages_: https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages
2. Set-up AutoRespond: https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorespond-feature
3. I'd suggest this config:
```ini
[Match]
regex=^.* You received .* cookies? from ([a-zA-Z0-9_]+)!$
action=send Thanks for the meal, $1!
```
Try it at https://regex101.com/r/zRMbzW/1
