### ISSUE TITLE
Nick glitch

### ISSUE THREAD

**Issue by PrivateServersGANG** [ORelio/Minecraft-Console-Client#1442]
The autoaccept tp dont work if u have a /nick

**Comment by ReinforceZwei** [comment]
https://github.com/ReinforceZwei/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-remote-control

> Please note that server admins can read what you type and output from the bot. They can also impersonate bot owners with /nick. See #1142 for more info.

**Comment by ORelio** [comment]
➡️ #1443
