### ISSUE TITLE
Nick not accepting tp

### ISSUE THREAD

**Issue by PrivateServersGANG** [ORelio/Minecraft-Console-Client#1443]
I turned on accept all tps and if someone is nicked it wont accept any way to fix?

**Comment by ORelio** [comment]
Adjust `tprequest` regex in config
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages

**Comment by PrivateServersGANG** [comment]
How would i do that i have 0 idea how to code

**Comment by ReinforceZwei** [comment]
Please provide a screenshot of your tpa request message.

**Comment by PrivateServersGANG** [comment]
https://your-mom.eats.dog/zPCtWMl0

**Comment by PrivateServersGANG** [comment]
@ReinforceZwei

**Comment by ReinforceZwei** [comment]
```regex
^\* ([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$
```
