### ISSUE TITLE
afk rails

### ISSUE THREAD

**Issue by kkha1996** [ORelio/Minecraft-Console-Client#1448]
Alts wont let it grow on when left on afk rail for farm

**Comment by ORelio** [comment]
Sorry, but I'm not sure to understand your question.

**Comment by kkha1996** [comment]
I put those alt accounts on afk rails, to make farms grow, but the farms wont grow, only if i have them in the real MC client.

**Comment by several5** [comment]
MCC doesn't calculate movement in a minecart connected with rails. you could use the /move (coords) feature

**Comment by kkha1996** [comment]
> MCC doesn't calculate movement in a minecart connected with rails. you could use the /move (coords) feature to have your alt walk around

This must be kinda wrong?

When i use the minecraft client and places the alt in the cart, and go off, it loads the farm, but not when the same alt is in the same cart when i use this software.

**Comment by ORelio** [comment]
Minecraft Console Client does not handle minecarts at all so I think it will try to move incorrectly if you attempt to ride a cart.
