### ISSUE TITLE
Auto reboot

### ISSUE THREAD

**Issue by kkha1996** [ORelio/Minecraft-Console-Client#1449]
Hey!

Is there a way to let these alt's auto-reboot if the server kicks them for random reaons, or if the server it self's restarts?

**Comment by ReinforceZwei** [comment]
See [AutoRelog](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot).

**Comment by kkha1996** [comment]
But we got a problem there, i cant find minecraftclient.ini

**Comment by kkha1996** [comment]
Solved!
