### ISSUE TITLE
Protocol v.110

### ISSUE THREAD

**Issue by Sheridan** [ORelio/Minecraft-Console-Client#145]
I try to change protocol version to 110 (1.9.3-pre2) and it seems to work fine.

```
diff --git a/MinecraftClient/Program.cs b/MinecraftClient/Program.cs
index c4958dd..3df9f08 100644
--- a/MinecraftClient/Program.cs
+++ b/MinecraftClient/Program.cs
@@ -23,7 +23,7 @@ namespace MinecraftClient
 
         public const string Version = "1.9.0 DEV";
         public const string MCLowestVersion = "1.4.6";
-        public const string MCHighestVersion = "1.9.0";
+        public const string MCHighestVersion = "1.9.3-pre2";^M
 
         private static Thread offlinePrompt = null;
         private static bool useMcVersionOnce = false;
diff --git a/MinecraftClient/Protocol/Handlers/Protocol18.cs b/MinecraftClient/Protocol/Handlers/Protocol18.cs
index 4e80439..650cfb7 100644
--- a/MinecraftClient/Protocol/Handlers/Protocol18.cs
+++ b/MinecraftClient/Protocol/Handlers/Protocol18.cs
@@ -19,7 +19,7 @@ namespace MinecraftClient.Protocol.Handlers
     class Protocol18Handler : IMinecraftCom
     {
         private const int MC18Version = 47;
-        private const int MC19Version = 107;
+        private const int MC19Version = 110;
 
         private int compression_treshold = 0;
         private bool autocomplete_received = false;
diff --git a/MinecraftClient/Protocol/ProtocolHandler.cs b/MinecraftClient/Protocol/ProtocolHandler.cs
index 894f1c0..7aef321 100644
--- a/MinecraftClient/Protocol/ProtocolHandler.cs
+++ b/MinecraftClient/Protocol/ProtocolHandler.cs
@@ -71,7 +71,7 @@ namespace MinecraftClient.Protocol
             int[] supportedVersions_Protocol16 = { 51, 60, 61, 72, 73, 74, 78 };
             if (Array.IndexOf(supportedVersions_Protocol16, ProtocolVersion) > -1)
                 return new Protocol16Handler(Client, ProtocolVersion, Handler);
-            int[] supportedVersions_Protocol18 = { 4, 5, 47, 107 };
+            int[] supportedVersions_Protocol18 = { 4, 5, 47, 107, 110 };^M
             if (Array.IndexOf(supportedVersions_Protocol18, ProtocolVersion) > -1)
                 return new Protocol18Handler(Client, ProtocolVersion, Handler, forgeInfo);
             throw new NotSupportedException("The protocol version no." + ProtocolVersion + " is not supported.");
@@ -126,7 +126,9 @@ namespace MinecraftClient.Protocol
                     case "1.8.9":
                         return 47;
                     case "1.9.0":
-                        return 107;
+                       return 107;^M
+                    case "1.9.3-pre2":^M
+                        return 110;^M
                     default:
                         return 0;
                 }
```

**Comment by Sheridan** [comment]
um ... first it worked, but then became the client off after about 30 seconds. How can I see what's going on?

```
[00:23:21] [Server thread/INFO]: Chief_Garibaldi lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[00:23:21] [Server thread/INFO]: Chief_Garibaldi left the game

```

**Comment by ORelio** [comment]
Pre-release versions and snapshots are not supported until they get released as stable versions.
The MC19Version constant is for differentiating 1.8 and 1.9, you should not need to touch it.
There are generally some changes in the protocol: http://wiki.vg/Pre-release_protocol

So to add support for a new version, usually we need to:
 - Add version to the list/swith just as you did
 - Implement protocol changes detailed in the link above.

As there are changes on almost every snapshot, implementing them week after week would require too much work that's why only stable version are being worked out once they get released ;)

**Comment by Sheridan** [comment]
I understand this and therefore show you the diff, instead of pull request :)

I also found how to bypass the bot disconnect: just have to run from bot console command (e.g. /send /help). If the command accepted (not always the first time), then the bot is not disconnect :)

**Comment by ORelio** [comment]
Oh. That would mean keep-alives don't work. The server periodically sends a keep-alive (ping packet) to the client, which must reply to the keep-alive otherwise it gets disconnected shortly afterwards. However if the client shows some other activity such as sending commands or so, it is considered as alive and don't get disconnected. So you might want to dig a bit in that direction.

**Comment by Sheridan** [comment]
I'll wait for the release of 1.9.3 and is likely to try to understand the changes in the protocol.
Thanks for pointing out areas of work :)

Your project is interesting to me that I run the bot on eeepc (Intel (R) Atom (TM) CPU N270 @ 1.60GHz). Native the client there is terribly slow, it needs xserver and no ability to manage through ssh. Maybe I'm more closely connected to the development of the bot. In particular I want to teach him crafting ([i have experience already](https://github.com/Sheridan/minecraft-automation)), including the search for raw materials in the chests within sight.

**Comment by ORelio** [comment]
That would be very intersesting, currently therrain is handled (although it needs 1.9 update but at least API for bots is there) but all the inventory things still needs to be done, and some interactions also, for triggering levers and opening chests. At the time I started it I thought of maybe automatically build things but that never happened :sweat_smile:

**Comment by Pokechu22** [comment]
Yea... 1.9 terrain handling is going to be a bit of a pain (there were some pretty big changes to it).  If you factor in forge blocks, things will get really painful (the pallete can vary in size based off of how many blocks forge adds).

1.9.3-pre2 itself doesn't make [too many changes](http://pokechu22.github.io/Burger/diff_1.9.2_and_1.9.3-pre2.html), though.

**Comment by ORelio** [comment]
Well, protocol v110 is now handled, so closing this issue. Feel free to reopen if needed.
