### ISSUE TITLE
How to get a player's health, position and entity ID in a script?

### ISSUE THREAD

**Issue by XIAYM-gh** [ORelio/Minecraft-Console-Client#1451]
**Prerequisites**
 - [Y] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [Y] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [Y] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
I want to get a player's information, but I can't write it in a script file.
And I can't save them in a var.

**Comment by ReinforceZwei** [comment]
Use ChatBot API. See [example ChatBot script](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) for how to write a chatbot.

Use [`GetEntities()`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L897) to get a list of entities around player. Each item is an [`Entity`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Entity.cs) object. Loop through the list and check the [`EntityType`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/EntityType.cs). If the type is player, get his information as your need.
