### ISSUE TITLE
Activate internal MCC commands in a .cs script

### ISSUE THREAD

**Issue by several5** [ORelio/Minecraft-Console-Client#1452]
How do i make a .cs script perform internal commands 

https://gyazo.com/3261db7efa6655d4bcd589df86346b2e

To what does ''sendText'' need to be changed?

**Comment by ReinforceZwei** [comment]
Use ChatBot method `PerformInternalCommand("command")`

**Comment by several5** [comment]
> PerformInternalCommand("command")

It works but i think i defined my question wrong...

I want the .cs script to launch another script. example: PerformInternalCommand("/script test.txt");

What's the command line to launch other scripts?

**Comment by ReinforceZwei** [comment]
`RunScript("script.cs")`

**Comment by several5** [comment]
Thanks alot!
