### ISSUE TITLE
Client disconnects when screen goes to sleep.

### ISSUE THREAD

**Issue by Heringen** [ORelio/Minecraft-Console-Client#1454]
[Title] Any way to bypass this?

**Comment by ReinforceZwei** [comment]
Please provide information about your device that runs the client.

**Comment by Heringen** [comment]
> Please provide information about your device that runs the client.

Precisely which information?

**Comment by Mhowser** [comment]
describe what your device IS. Are you running MCC on a desktop, laptop or mobile phone. And what Operating system is it using? Without this information we can't help you.

**Comment by Heringen** [comment]
Windows 10 PC

**Comment by Heringen** [comment]
Also there is mobile version?

**Comment by Mhowser** [comment]
Try this, https://thegeekpage.com/prevent-your-wi-fi-from-turning-off-in-windows-10/



> Also there is mobile version?

are you asking about Win10 or MCC?

**Comment by ReinforceZwei** [comment]
> Also there is mobile version?

See #1000, #1338, #1407

**Comment by Heringen** [comment]
> Try this, https://thegeekpage.com/prevent-your-wi-fi-from-turning-off-in-windows-10/
> 
> > Also there is mobile version?
> 
> are you asking about Win10 or MCC?

I often run 1 instance of minecraft as game alongside alts and don't get disconnected from servers soo it's very unlikely my internet turns off.
