### ISSUE TITLE
Something about Chatbot.cs

### ISSUE THREAD

**Issue by XIAYM-gh** [ORelio/Minecraft-Console-Client#1455]
I wrote a script to get information, but they're protected in the code of Chatbot.cs.
Such as:
>protected Mapping.Location GetCurrentLocation()
>protected Mapping.World GetWorld()
I wrote them in the script, but they can't use because they're got protected.

Should I replace them with "public" or something?

**Comment by ReinforceZwei** [comment]
Could you provide your script? Those methods should be able to access if you inherit from ChatBot class.

**Comment by XIAYM-gh** [comment]
Like this:
//MCCScript 1.0
MCC.SendText("Now logged in: " + MCC.GetUsername());
MCC.SendText("UUID: " + MCC.GetUserUUID());

**Comment by ReinforceZwei** [comment]
This is a c# script but not chatbot script. See [example chatbot script](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) for hot to write a chatbot.

**Comment by XIAYM-gh** [comment]
OK.
(In fact, I don't know how to write a chabot...)
