### ISSUE TITLE
Auto respond with regex

### ISSUE THREAD

**Issue by XIAYM-gh** [ORelio/Minecraft-Console-Client#1456]
I have a question. (Sorry about that I asked too many questions.)
My code is:
>[Match]
>regex=^. *([a-zA-Z0-9_\s\S]+) joined the game. *$ (markdooooooown!!!)
>actionother=send /msg $1 Welcome!

I think it should be :
TestPlayer joined the game
[me -> TestPlayer] Welcome!

But it's :
TestPlayer joined the game
[me -> e] Welcome!

What can I do?

**Comment by ReinforceZwei** [comment]
I am not familiar with auto respond, but could you try to replace $1 with $u and see if it works?

**Comment by XIAYM-gh** [comment]
OK, I will try it.

**Comment by XIAYM-gh** [comment]
It seems it's not right.
I tried "$u":
[MCC] [AutoRespond] send /msg  Welcome!

**Comment by ReinforceZwei** [comment]
Maybe your regex cannot capture username. You can visit https://regex101.com and try to play around with your regex.

**Comment by XIAYM-gh** [comment]
^.*([a-zA-Z0-9_\s\S]+) joined the game.*$
is right, I can use it in regex101.com .
I think It's a bug.

**Comment by ReinforceZwei** [comment]
Your regex doesn't work. It cannot capture the username. See the red circle.
![image](https://user-images.githubusercontent.com/39955851/107019580-ce81a100-67dc-11eb-8a49-e71768037d57.png)

I modified your regex to capture username properly.
```regex
^([a-zA-Z0-9_]*) joined the game$
```
![image](https://user-images.githubusercontent.com/39955851/107019953-3fc15400-67dd-11eb-95bc-06f01dc6cce7.png)

Please try again.

**Comment by XIAYM-gh** [comment]
thx
