### ISSUE TITLE
Regex not working

### ISSUE THREAD

**Issue by Mangoesy** [ORelio/Minecraft-Console-Client#1460]
Sorry im new to this but I created a regex:
^(?:Welcome) \w+ to Complex-Vanilla Creative! \[#\w+,\w+\]
To match:
Welcome D0num to Complex-Vanilla Creative! [#72,919]
Here it works fine: https://regex101.com/

[Match]
regex=^(?:Welcome) \w+ to Complex-Vanilla Creative! \[#\w+,\w+\]
action=send Welcome
But like this it doesn't work? Help appriciated.

**Comment by ORelio** [comment]
use `actionother=` not `action=` this is not a chat message.

https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini#L44

```ini
# Example of matching a server announcement
[Match]
match=server is restarting
actionother=script restart
```

**Comment by Mangoesy** [comment]
Ooo my bad, thanks a bunch!
