### ISSUE TITLE
Lore NBT Data

### ISSUE THREAD

**Issue by Korgen1** [ORelio/Minecraft-Console-Client#1461]
var bdic = item.NBT;
    			if (bdic != null && bdic.ContainsKey("display"))
    			{
    				var displayProperties = bdic["display"] as Dictionary<String, object>;
    				if (displayProperties != null && displayProperties.ContainsKey("Lore")) {
    					String lore = displayProperties["Lore"] as String;

    						LogToConsole(lore);
 
    				}
    			}
    			
    			
I cant figure out how to get the Lore. It just turns up blank. When I try to directly do LogToConsole(displayProperties["Lore"]); it will just print out System.Object[] which seems to be an array but when trying to iterate through it I get, 

`System.InvalidOperationException: foreach statement cannot operate on variables of type 'object' because 'object' does not contain a public definition for 'GetEnumerator'`

And if I try to index it I get,

`System.InvalidOperationException: Cannot apply indexing with [] to an expression of type 'object'`

Is getting item lore not possible with MCC or am I doing something wrong? Its 3 AM and I'm going to sleep. Hopefully this gets responded to tomorrow... 

Sorry if this is a mess, like I said it's 3 am and I am very tired from debugging all night. Thanks for helping.

**Comment by ReinforceZwei** [comment]
`Item` class has a `Lores` property that extracts the lore from the item NBT for you. 

Use it like this:
```cs
if (item.Lores != null && item.Lores.Length > 0)
{
    foreach (var lore in item.Lores)
    {
        ConsoleIO.WriteLine("Lore: " + lore);
    }
}
```

**Comment by Korgen1** [comment]
Thanks
