### ISSUE TITLE
Console Client logs not showing up on ubuntu

### ISSUE THREAD

**Issue by Korgen1** [ORelio/Minecraft-Console-Client#1463]
Running MCC on ubuntu 20.04 VPS. Scripts work fine but they cant log anything. When trying to do /log <text> it is blank.

![image](https://user-images.githubusercontent.com/65197237/107135580-edaa2c80-68c9-11eb-807c-c99d0cb1fa6a.png)

**Comment by Korgen1** [comment]
I should probably mention I am running Putty to connect to SSH

**Comment by ReinforceZwei** [comment]
This is an issue in putty color scheme which outputting gray as black. See #1260 for solution.

**Comment by Korgen1** [comment]
Thank you.
