### ISSUE TITLE
Remote Control With Plugin?

### ISSUE THREAD

**Issue by Unbounder1** [ORelio/Minecraft-Console-Client#1464]
Would it be possible to still use remote control in a server with tell plugins that make them fancy? For some reason I can't get it to work in that server but in a fully vanilla server it works fine.

**Comment by Unbounder1** [comment]
My tiny brain is dum srry

**Comment by autodistries** [comment]
I played on a server with multiple plugins and mods on it, and it worked fine ¯\_(ツ)_/¯

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages
