### ISSUE TITLE
Event for World Change

### ISSUE THREAD

**Issue by Kevqn11** [ORelio/Minecraft-Console-Client#1466]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

 

---
## Description of the Question

I want the client to do some commands after the world changes, like when doing /server a new world is loaded.

---
## Describe your current situation
I want to make an auto fishing client but the problem is that the server which I want to use it on has a queue system. So server kicks people that are seemingly afk and lets some people in. I want the client to start fishing when it gets in the server.

---
## Solutions you've already considered

I tried doing this by adding `UseItemInHand()` in the `AfterGameJoined()`  method in `Minecraft-Console-Client-master\MinecraftClient\ChatBot.cs` so that it sends the fishing rod out and then the auto-fishing feature will take care of the rest. But that doesnt work. I guess it executes the command in the queue world that is first loaded and not the actual server.

Then I tried adding `UseItemInHand()` in the `OnSetExperience()` method in the same file. But for some reason it sends the fishing rod and then quickly takes it back as if the command was executed twice even though it shows up only once in the console. 

I also made some changes to `Minecraft-Console-Client-master\MinecraftClient\ChatBots\AutoFishing.cs` so that it doesnt check for available fishing rods because for some reason it was saying that the rod was broken when it wasn't. I don't think that this has any influence on the problem i'm having but i thought i would add it just in case.

 ---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)
Here are the changes I made.

Minecraft-Console-Client-master\MinecraftClient\ChatBots\AutoFishing.cs
![image](https://user-images.githubusercontent.com/41635867/107856245-e85e5c00-6e4c-11eb-899d-b9c31e0aa0fb.png)

Minecraft-Console-Client-master\MinecraftClient\ChatBot.cs
![image](https://user-images.githubusercontent.com/41635867/107856157-5bb39e00-6e4c-11eb-83c0-e391bd8fb448.png)

Console Output
![image](https://user-images.githubusercontent.com/41635867/107856175-7e45b700-6e4c-11eb-835d-4ead17b6964c.png)

**Comment by Kevqn11** [comment]
sry for the trouble I did it on my own.

**Comment by ORelio** [comment]
Thanks for submitting a detailed issue, this might help other people anyway. Glad you could solve it 👍
