### ISSUE TITLE
Console client is freezing and not reconnecting

### ISSUE THREAD

**Issue by Tnavillacs** [ORelio/Minecraft-Console-Client#1467]
Every night at around 2am I lose my connection and if I only run like 4 console client windows they reconnect as they should. But if I run more than 5 half of them don't reconnect after 2am and just completely freeze. I can't type any message or command in. I can only close the window. 
Maybe my IP is blacklisted when so many alts try to reconnect at once? But it says connection has been lost not blacklisted so I'm not sure. Any ideas what could be the issue and how I could fix it?

**Comment by ORelio** [comment]
In AutoRelog, you may specify a random delay to reduce this issue.
For instance, set `delay=10-120` so that each client chooses a delay between 10 seconds and 2 minutes.
Related issues: #663, #740, #975, #1312

**Comment by Tnavillacs** [comment]
> In AutoRelog, you may specify a random delay to reduce this issue.
> For instance, set `delay=10-120` so that each client chooses a delay between 10 seconds and 2 minutes.
> Related issues: #663, #740, #975, #1312

It Says `[MCC] Failed to convert '10-200' into an int. Please check your settings.`

**Comment by ReinforceZwei** [comment]
Probably you are using an old version of MCC. Please download the newest version from [here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by Tnavillacs** [comment]
![6cdeccd676f2a09e2309c1b76c6ba297](https://user-images.githubusercontent.com/52362571/108049689-e82ab000-7048-11eb-9179-e2ede7d903a3.png)
This happens in the night after my internet restarts. 9/10 alts rejoined and 1 alt kept trying to reconnect and in the morning the window is frozen.

**Comment by ORelio** [comment]
This issue might be solved by #1560
