### ISSUE TITLE
Ip usage

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1468]
Is there a possibility to pretend that you've joined with another ip than you really have? Because as a console client most applications of mcc are running on a server of some hoster. And a lot of times you can't join public servers from the address of a hoster. Maybe its possible to make the bot running on the server connect to the server via an ip at home he is linked to or using the proxy function. If you have an idea, pls let me know. Im very thankful for your help

**Comment by ORelio** [comment]
No. Else, VPNs and Proxies would not exist.
To use your home address, you need to setup a VPN/Proxy there.
