### ISSUE TITLE
Autorelog

### ISSUE THREAD

**Issue by CrazyFoxxx** [ORelio/Minecraft-Console-Client#1469]
Hi everyone. How do I create a script that would move my twink to the skyblock server if it gets kicked into the hub? 
I would be very grateful for your help in creating the script.

**Comment by Tnavillacs** [comment]
I use this AntiAFK thing in my MinecraftClient.ini
```
[AntiAFK]
enabled=true
delay=3000 #10 = 1s
command=/server sb
```

**Comment by CrazyFoxxx** [comment]
Maybe it works for you, but on the server where I play, the command /server is disabled for players.

**Comment by Tnavillacs** [comment]
And how do you usually join?
I'm not sure if you can directly link scripts to AntiAFK
But you can put this in the `MinecraftClient.ini`:
```
[ScriptScheduler]
enabled=true
tasksfile=tasks.ini
```
Put this task into the `tasks.ini`:
```
[Task]
triggerOnInterval=true
timeInterval=30
script=reconnect.txt
```
And then the script you usually run to join the server into `reconnect.txt`.

**Comment by CrazyFoxxx** [comment]
Thanks!
