### ISSUE TITLE
Idea for an anti afk!

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#147]
So instead of it sending a command make it send a command to the console client to "/move up"
Or make it edit able so you can make it do like "/move south" then "/move east" at the same time. that would make it so the player isn't registered as afk.

**Comment by ORelio** [comment]
You can use ScriptScheduler for that :)

**Comment by AppleCidar** [comment]
How do you make a script that sends a command to console

**Comment by ORelio** [comment]
You can use any MCC command in your scripts, including `move`.
That's when you want to send something to the server that you need the `send` command.

**Comment by AppleCidar** [comment]
I tryed to do `MCC.SendText(/move west);
But it didnt work

**Comment by ORelio** [comment]
Of course, here you're sending an internal command to the server.
That's `MCC.PerformInternalCommand("move west");` ;)

**Comment by ORelio** [comment]
Of course, here you're sending an internal command to the server.
That's `MCC.PerformInternalCommand("move west");` ;)
Also, if you only need to perform a sequence of internal commands, you can simply use a plain text script eg move.txt with `move west` and other instructions on the lines below.

**Comment by AppleCidar** [comment]
Thanks so Much! This really does help!

**Comment by AppleCidar** [comment]
Will you ever support left and right clicks?

**Comment by ORelio** [comment]
Currently that is not planned, need to bring back support for terrain and movement in 1.9 before considering such additions.

**Comment by AppleCidar** [comment]
Sounds good!
