### ISSUE TITLE
Auto TP Accept from Specific people.

### ISSUE THREAD

**Issue by SmellySteve** [ORelio/Minecraft-Console-Client#1470]
Hallo people.

How do i make to bot accapet a tpa from some1.

halp plaz

**Comment by Tnavillacs** [comment]
In MinecraftClient.ini you set `botowners=yourname`
and
```
[RemoteControl]
enabled=true
autotpaccept=true
```

**Comment by SmellySteve** [comment]
cant.

**Comment by SmellySteve** [comment]
https://imgur.com/a/zUvMT1o. tpa text looks like that. help plaese

**Comment by SmellySteve** [comment]
i need a format

**Comment by ReinforceZwei** [comment]
Just a little bit modification, changing `has requested` to `wants`.
Put below regex to your `MinecraftClient.ini` file, the `[ChatFormat]` section.
```ini
tprequest=^([a-zA-Z0-9_]+) wants (?:to|that you) teleport to (?:you|them)\.$
```
