### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by pruthvi-lalji** [ORelio/Minecraft-Console-Client#1471]
Is there a guide on how to contribute to this project, I am interested in contributing to this project, and I have a good understanding of Java so I think I would be able to add and improve. 

Just need help on how do I get started. If there was a guide would be helpful.

Thanks

**Comment by ORelio** [comment]
Hi @pruthvi-lalji and welcome to the project!

First of all, this is a C# project. Although it's similar to Java, it's not exactly the same so you'll need to learn a few things before feeling comfortable. Also, for your information, it's currently written with compatibility for .NET 4.0. A few things from newer C# versions are not (yet) available in the project.

Here are a few pointers to get familiar with the code:
 - [config](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config) user manual and sample files/scripts
 - [Program.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Program.cs) contains info on how to add support for a new version
 - [ChatBot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs) the ChatBot API

General architecture

[Program.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Program.cs) handles startup/login and launches a [McClient](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/McClient.cs). The McClient instantiates a [ProtocolHandler](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs) to write and read network packets, i.e. interact with the server. It also allows to type commands, launch and manage [ChatBots](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs) which are similar (but much simpler) to plugins in Bukkit servers: they have events and an API for interacting with the game.

Feel free to ask if you have more specific questions.

**Comment by pruthvi-lalji** [comment]
@ORelio  Thanks for the update, I would start learning C#, looks similar but yh would be very happy to learn and contribute. 

One question, which is not related to this, but I saw something about villager  trading and i was not able to find on how to run it, and that interest me to start to contribute on this project.

Thank you so much

**Comment by ORelio** [comment]
See #1296, you have a couple of ChatBot APIs for that so you can write a ChatBot and interact with the villagers. I think you'd need to retrieve the entity list, walk to the villager if needed, look to the villager, interact to open the trade list, then browse the trade list and select the trade you want. I did not interact with villagers myself, these APIs are contributed by the community :)
