### ISSUE TITLE
Ability to filter messages in chatlog

### ISSUE THREAD

**Issue by joey1313** [ORelio/Minecraft-Console-Client#1472]
Hello,

I've been trying to filter both my console and chatlog in a certain way such that certain messages get filtered out. I've been successful in filtering my console messages with regex, but I'm not sure how to do the same with chatlog (even after fiddling with chatformat).

How would I apply the same regex filter that I apply on my console output to my chatlog output?

**Comment by ReinforceZwei** [comment]
`ChatLog` currently doesn't support regex message filtering. You can only filter messages by message type, e.g. private message, internal message, etc.

**Comment by ReinforceZwei** [comment]
With the newer version, you can enable writing console output to log file. Both content would be the same. 

You may copy the settings below to your `MinecraftClient.ini` file `[Logging]` section if you don't want to delete your old `.ini` file.
```ini
[Logging]
logtofile=false                    # Write log messages to file
logfile=console-log-%username%-%serverip%.txt    # Log file name
prependtimestamp=false             # Prepend timestamp to messages in log file
```
