### ISSUE TITLE
AutoRespond help

### ISSUE THREAD

**Issue by JimBob0121** [ORelio/Minecraft-Console-Client#1473]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Basically i'm trying to get my autorespond to work for a server message that pops up in chat for local server reboot. The reason for this is my alts disconnect when the local server reboot but are stuck are the hub due to the local server reboot so i need to make them disconnect at 10 seconds so they respawn at the last location**

The message that pops up in chat

*** THE SERVER IS REBOOTING IN 10 second(s) ***

i can't seem to get it to work

this is my matches.ini
[Match]
match=^.*** THE SERVER IS REBOOTING IN 10 second(s) ***.*$
actionprivate=script restart

i am new to this regex stuff mb

**Comment by ORelio** [comment]
`actionprivate` triggers on private messages. You're looking for `actionother`.

**Comment by JimBob0121** [comment]
> `actionprivate` triggers on private messages. You're looking for `actionother`.
> Also you can test your regex on https://regex101.com/

I tried that didn't seem to work.

**Comment by ORelio** [comment]
Your regex seems incorrect since `*` has a special meaning and needs to be escaped `\*`
Regex101 would tell you so if you paste your regex inside.

**Comment by JimBob0121** [comment]
this seemed to work thank you
