### ISSUE TITLE
Console client not logging in with microsoft account

### ISSUE THREAD

**Issue by qphantasia** [ORelio/Minecraft-Console-Client#1474]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])
Whenever I attempt to log in to one of my Minecraft accounts I purchased a few months ago via microsoft, it says "Cached session is invalid or expired" once I put in the email. It works just fine on my main account that I've had for a few years via Mojang.

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])
I'm not sure if it's an issue with what I'm inputting or the way my accounts are set up, but I can't get it to log in.

---
## Solutions you've already considered

1. Set [...] setting in my config
2.
I've insured my emails are different, I've asked multiple of my friends who don't have the same issue

---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

I'm not sure what information I could provide that helps, if there is I'll happily provide it.

**Comment by ReinforceZwei** [comment]
Have you change the account type to microsoft in `MinecraftClient.ini`?

**Comment by AFT3R-max** [comment]
> Have you change the account type to microsoft in `MinecraftClient.ini`?

I have the same issue, how do i changet the account type to microsoft?, can you explain more?

**Comment by ReinforceZwei** [comment]
1. Download the latest version from [here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

2. If you have your own modified `MinecraftClient.ini`, you may copy it to somewhere safe.

3. Delete your old `MinecraftClient.ini` and launch MCC once. A new version of configuration file should be generated.

4. Edit the new generated `MinecraftClient.ini`, change the `type` from `mojang` to `microsoft`.
![image](https://user-images.githubusercontent.com/39955851/109441584-946c8d80-7a70-11eb-9644-de0dae01f385.png)

5. Now you should be able to sign-in with your Microsoft account.

**Comment by AFT3R-max** [comment]
> 1. Download the latest version from [here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
> 2. If you have your own modified `MinecraftClient.ini`, you may copy it to somewhere safe.
> 3. Delete your old `MinecraftClient.ini` and launch MCC once. A new version of configuration file should be generated.
> 4. Edit the new generated `MinecraftClient.ini`, change the `type` from `mojang` to `microsoft`.
>    ![image](https://user-images.githubusercontent.com/39955851/109441584-946c8d80-7a70-11eb-9644-de0dae01f385.png)
> 5. Now you should be able to sign-in with your Microsoft account.

Thank you!

**Comment by ReinforceZwei** [comment]
You should use email for sign-in.

> sends me to nowhere

Do you mean it sent you to a blank page after signed-in? If yes, blank page means sign-in success. You should copy the link from browser address bar and paste it to MCC.
