### ISSUE TITLE
AutoRespond help me pls

### ISSUE THREAD

**Issue by farfromsubtlee** [ORelio/Minecraft-Console-Client#1475]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Hello, sorry for my bad English. I'm using google translate.

https://regex101.com/r/qVHkRw/1
![image](https://user-images.githubusercontent.com/63727203/108624087-9b354800-7453-11eb-874a-1121b9922b3b.png)

![image](https://user-images.githubusercontent.com/63727203/108624492-4d6e0f00-7456-11eb-8a95-35197cb1d1da.png)

There is no problem here.
But I can't get a response.

Couldn't it perceive because (?) Appears? I thought.
![image](https://user-images.githubusercontent.com/63727203/108624148-1565cc80-7454-11eb-90aa-88fe22ac86eb.png)

I replaced (〣) & (┊) with (?). But nothing has changed.
Can you help me? I am new to using Regex.

**Comment by ORelio** [comment]
Hello,
1. Make sure your chat messages are detected. See Detecting chat messages: https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages
2. Test your regex at https://regex101.com/
