### ISSUE TITLE
Autocraft problem

### ISSUE THREAD

**Issue by MCwenka** [ORelio/Minecraft-Console-Client#1476]
I use autocraft on a 1.16.5 server. When I tried to use autocraft to synthesize bone meal, it succeeded. But when I continued to try to synthesize bone meal into bone block, it seemed that I failed....
This picture shows the configuration and composition of autocraft. I'm pretty sure the recipe for the bone block is nine bone meal.

![-7320a02b68a2022a](https://user-images.githubusercontent.com/69469371/108718336-4976e580-7559-11eb-84dd-4675478935c5.jpg)

**Comment by ReinforceZwei** [comment]
Currently auto-craft doesn't support distributing items if there's not enough number of stacks. So it is one item stack per slot. You only have 4 and a half stacks of bone meal in your inventory and that's not enough to craft a bone block.

The only way to address this issue for now is to split the item stack yourself by using `/inventory p <slot> click right`, then put it on an empty slot `/inventory p <empty slot> click`.

**Comment by MCwenka** [comment]
ok, I see, thank you.

But how can I use a bot like this.
`https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/AutoTree.cs`

Is it through configuring `[AutoTree] enabled = true` in `.ini` ?
Can I then use `/autotree` ?

**Comment by ReinforceZwei** [comment]
For autotree, you have to download the script and put it in the same folder as your `MinecraftClient.exe`. Then load the script by using `/script autotree.cs`. Remember to change the coordinates of your sapling in the script.

**Comment by MCwenka** [comment]
OK, thank you again for your help.
I have one last question I want to ask, how to climb the scaffold.....
I tried `/move up` and `/move x y z`. The former climbs half way and falls, while the latter moves to where the scaffold is and stops.

**Comment by ReinforceZwei** [comment]
It is not possible to climb scaffolding.

**Comment by MCwenka** [comment]
That scaffold is only one grid high. Is there any way to jump on it...

**Comment by ReinforceZwei** [comment]
Sorry, I have no idea how to do that as I have never studied it.
