### ISSUE TITLE
Turn off computer / put computer to sleep depending on chat messaged filtered using regex

### ISSUE THREAD

**Issue by joey1313** [ORelio/Minecraft-Console-Client#1478]
Is it possible to use MCC to affect the state of the computer depending on messages in chat?

**Comment by OverHash** [comment]
You can write a C# script to detect this

**Comment by ORelio** [comment]
I'd suggest to create a C# script that will execute the `shutdown` command.
Here is an example on how to run system commands in C#: https://github.com/ORelio/Minecraft-Console-Client/issues/715#issuecomment-489162715
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/shutdown

**shutdown.cs**
```
//MCCScript 1.0
System.Diagnostics.Process.Start("shutdown", "/s /t 0");
```
Then launch `shutdown.cs` when a specific message is detected using the AutoRespond bot.
