### ISSUE TITLE
C# Slow Messages

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1480]
Mcc Gives the opportunity to lower the minimum duration between messages, which allows an significant speed if messages are send via an normal script, but if you use MCC. SendText or PerformInternalCommand in an c# file the chat messages are arriving very slow even if the delay between the messages is set to 0. This leads to enourmous duration times and makes larger projects which need access to sending text nearly impossible, because the program waits until the message got send before it is continuing. Quick example:
for(int i = 0; i < SomeArray.Length; i++)
{
       Mcc. SendText(i + ": " + SomeArray[i] ;
      ... Some extra code using i...
}
In this example its just one line of the array getting send every second. And all the other actions after thr argument have to wait for that long. As a consequence my question is their an option to send the messages out of c# scripts faster, because its available in other scripts too. Or as another option continuing with the rest of the script before completing the Send statrment, but i think thats very bad practice. If not can you please add an way to do it?

Thank you very much!
xXjajoXx

**Comment by xXjojaXx** [comment]
Ok, after I go througz the code I realized the 1000 tick sleep after each send action. Which means the delay absolutely makes sense. (Send-Method: " public bool SendText(object text)
        {
            base.SendText(text is string ? (string)text : text.ToString());
            tickHandler.WaitOne();
            ***Thread.Sleep(1000);***
            return true;
        }". But shouldn't the sending delay be synchronised with that from normal scripts? And if not is there an option to change this delay. And again if not pls add it, its really necassary.
Thanks again

**Comment by ORelio** [comment]
This was a long time ago so I'm not 100% sure why I put this delay, but I think it was there to avoid triggering antispam when sending a few commands in a row from a script. Since MCC now has a global message queue, this delay should be irrelevant now so I'll remove it. Let me know if it breaks anything.

**Comment by xXjojaXx** [comment]
Dont want to use up your time, but as an quick general qurstion: If something is added or rwmoved from mcc is it instantly in the newest version of mcc I can download or does it take a while until the next update comes out? If yes, how long is it? Thanks

**Comment by ORelio** [comment]
A new development build is compiled instantly for any new commit.
For instance, this change is available in build 449 or greater
https://ci.appveyor.com/project/ORelio/minecraft-console-client/builds/37953523
