### ISSUE TITLE
Is there's a way to know how many people are connected to a server before the connexion ?

### ISSUE THREAD

**Issue by ChRiiS** [ORelio/Minecraft-Console-Client#1481]
Hi !
Like i said on the title, i wanted to know how many people are connected to the server while resolving it (like minecraft does) and check this count to know if i can connect or not.

IE : 
- i want to have an instance connected if there's more than ten connected ans less than twenty
- i want to have an instance connected if there's more than one people
- - i want to have an instance connected if there's no one
- ...

Maybe be i miss something, but seen from here, i only can handle thing once i connected.

PS : I already told you, but thank you again for this very powerful tool ! <3

**Comment by ChRiiS** [comment]
It can be done just with a simple socket before lauchning your tools.

Example in PHP : 
```php
<?php
$ip = "play.azazelcraft.fr";
$port = "25566";
$timeout = "3";

if ($ip && $port && $timeout)
{
    $statut = @fsockopen($ip, $port, $errno, $errstr, $timeout);
    if($statut)
    {
        fwrite($statut, "\xFE\x01");
        $output = fread($statut, 1024);
        if ($output != false && substr($output, 0, 1) == "\xFF")
        {
            fclose($statut);
            $output = substr($output, 3);
            $output = mb_convert_encoding($output, 'auto', 'UCS-2');
            $output = explode("\x00", $output);
            //$output[4] -> players connected
            //$output[5] -> players max allowed
        }
    }
}
?>
```
Now I can do whatever I wanted with this tool, sorry for the inconvenience and once again great job ! :heart_eyes:

**Comment by ORelio** [comment]
It's cool you could solve your issue :+1:
For your information, the equivalent C# code in MCC for server ping is here:
https://github.com/ORelio/Minecraft-Console-Client/blob/9d41e2223dba453864a481eb1f433e4b90d96e47/MinecraftClient/Protocol/Handlers/Protocol18.cs#L1345-L1410
Additional details and documentation here: https://wiki.vg/Server_List_Ping
