### ISSUE TITLE
Detect when the player is hit

### ISSUE THREAD

**Issue by D4niele-git** [ORelio/Minecraft-Console-Client#1485]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

---
## Describe your problem
Present a concise description of the problem to be addressed by this feature request. 

---
## Suggest a possible solution
A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])

---
## Screenshot to help explain your request (If applicable)

**Comment by ORelio** [comment]
Hi, for now, you can detect health changes in ChatBot API, but currently can't detect the player is being hit (sometimes, you can be hit without damage e.g. snowball, and you can lose health without being hit, e.g. fire, poison, starving...). Putting your request on the enhancement list.

**Comment by ReinforceZwei** [comment]
To detect player is being hit, we can observe `EntityStatus` packet and look for byte enum value of 2, which is `Plays the hurt animation and hurt sound`. Document: https://wiki.vg/Entity_statuses#Living_Entity

**Comment by D4niele-git** [comment]
How can I add this feature in my client?

**Comment by ORelio** [comment]
Using a C# ChatBot. Example:

**watchforhit.cs**
```c#
//MCCScript 1.0

MCC.LoadBot(new WatchForHit());

//MCCScript Extensions

public class WatchForHit : ChatBot
{
    public override void OnPlayerStatus(byte statusId)
    {
        if (statusId == 2)
        {
            LogToConsole("I've been hit!");
            //SendText("/command");
        }
    }
}
```

**Comment by D4niele-git** [comment]
I tried to use this script but it doesn't seem to work, can you tell me how to enable it? (I also tried with / script)

**Comment by ReinforceZwei** [comment]
You have to set entity handling to true in your `MinecraftClient.ini` before using the script.

**Comment by ORelio** [comment]
Indeed, just edited my example above to check for entity handling.

**Comment by D4niele-git** [comment]
There is a problem, [ERROR] Entities are currently not handled for that MC version.
I use version 1.8.9

**Comment by ReinforceZwei** [comment]
Entity handling only support version 1.10 and above.
