### ISSUE TITLE
Console client breaking

### ISSUE THREAD

**Issue by orange0530** [ORelio/Minecraft-Console-Client#1486]
**Prerequisites**
 - [Yes] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [Yes] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [Yes]  I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

Console client running like normal

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])

having a connection error then console client breaking

---
## Solutions you've already considered

1. Restarting console client when it happens

---
## Screenshots to help explain your situation (If applicable)
https://gyazo.com/412877f66375e09989751748ee945ceb

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

CentOS 7, a script to run /chicken on join

**Comment by ORelio** [comment]
Seems like the issue happens in this line:
https://github.com/ORelio/Minecraft-Console-Client/blob/d19764869c05e9f4458f4ee13457df6d0b0cf6ab/MinecraftClient/McClient.cs#L544
I suspect a threading issue since MCC is not fully thread safe. Would you mind sharing the script you are using?

**Comment by ORelio** [comment]
Should be resolved as per #1510
