### ISSUE TITLE
Chatformat

### ISSUE THREAD

**Issue by RobertFowley** [ORelio/Minecraft-Console-Client#1487]
I am trying to set it up so that when I message the bot "/script t" it runs script t.
I cannot figure out how to format the chat for this private message.
![image](https://user-images.githubusercontent.com/79899407/109614519-36c35a00-7adf-11eb-95d0-cb11965df427.png)

**Comment by ReinforceZwei** [comment]
```regex
^\[([a-zA-Z0-9_]+).->.me\].(.+)$
```
https://regex101.com/
![image](https://user-images.githubusercontent.com/39955851/109629670-07fcc080-7b7f-11eb-90e4-76e8e4f35b25.png)

**Comment by Mineralz0** [comment]
you might have to do it without the [ ] eg.
 -> me /script t
instead of [ -> me] /script t

**Comment by Tnavillacs** [comment]
```
//MCCScript 1.0

MCC.LoadBot(new Bot());

//MCCScript Extensions

public class Bot : ChatBot
{
	
    public override void Initialize()
    {
        LogToConsole("ChatBot enabled!");
    }
    public override void GetText(string text)
    { 
		text = GetVerbatim(text);

            if(text.Equals("[Lenrem -> me] /script t"))
			{
			PerformInternalCommand("/script t");
			}	 
    }
}
```
This might work.
You paste this script into a file with a .cs ending for example runscript.cs
and then type in /script runscript into console client.

**Comment by ORelio** [comment]
Why not use the built-in RemoteControl bot?
