### ISSUE TITLE
Internet Cutting out

### ISSUE THREAD

**Issue by Cxrnage1612** [ORelio/Minecraft-Console-Client#1489]
whenever my internet cuts out or does a scheduled reboot my console client automatically shuts down, it doesn't just disconnect me from the server it completely closes the entire client itself, was hoping there was a fix/work around for this

**Comment by ReinforceZwei** [comment]
Please provide more information about the situation, e.g. console output, your configuration file.

**Comment by ORelio** [comment]
Normally with AutoRelog MCC should reconnect after connection is lost?
