### ISSUE TITLE
Upgrade to 1.9.4

### ISSUE THREAD

**Issue by Cat7373** [ORelio/Minecraft-Console-Client#149]

**Comment by Pokechu22** [comment]
For reference: http://wiki.vg/Pre-release_protocol

I don't think MCC listens to any of the packets that were changed (well, it uses chunk data, but that's not handled for 1.9 yet), so it probably will be easy.

**Comment by Cat7373** [comment]
https://github.com/Cat7373/server_diff/blob/master/network.patch

**Comment by ORelio** [comment]
Is 1.9.3 protocol 109 or 110?

**Comment by Pokechu22** [comment]
1.9.3 and 1.9.4 are both 110.

**Comment by Cat7373** [comment]
Don't quite understand what you mean, my English is not very good, sorry –

Contrast of the patch file is 1.9.2 and 1.9.4

**Comment by ORelio** [comment]
Display version : 1.9.4
Internal version : 110
My question was : 1.9.3 -> 109 or 110 ;)
Anyway, done in 5e6f4d3af987a3a459d1743ab5ba6c3e3dd07280 :)
(Although not tested)

**Comment by Cat7373** [comment]
There seems to be no question

**Comment by ORelio** [comment]
The question was wether to write
````C#
case "1.9.3":
    return 109;
````
or
````C#
case "1.9.3":
    return 110;
````
but that's not very important anyway since it's already figured out.

**Comment by Cat7373** [comment]
1.9.3 official version is 110

**Comment by ORelio** [comment]
Yes, got it here: https://github.com/ORelio/Minecraft-Console-Client/issues/149#issuecomment-218588503
