### ISSUE TITLE
Forge 1.12.2 Support

### ISSUE THREAD

**Issue by duygusuzz** [ORelio/Minecraft-Console-Client#1493]
I want to login a server with forge 1.12.2. Can you add 1.12.2 support for forge?

**Comment by ReinforceZwei** [comment]
Forge support for 1.12.2 is already there. Please check your configuration file to make sure forge is not being disabled.

**Comment by ORelio** [comment]
Also make sure you are using the latest build.
https://github.com/ORelio/Minecraft-Console-Client#download

**Comment by duygusuzz** [comment]
![image](https://user-images.githubusercontent.com/80117415/110240463-0f481380-7f5d-11eb-8f2a-600af2c2337a.png)

**Comment by duygusuzz** [comment]
![image](https://user-images.githubusercontent.com/80117415/110240486-2ab31e80-7f5d-11eb-9727-4b28a3cc8b2a.png)

**Comment by ReinforceZwei** [comment]
Set `mcforge=auto` in your `MinecraftClient.ini` file.

**Comment by duygusuzz** [comment]
I'll try wait a sec

**Comment by duygusuzz** [comment]
![image](https://user-images.githubusercontent.com/80117415/110240537-7e256c80-7f5d-11eb-9a17-197e28d1206b.png)

**Comment by ReinforceZwei** [comment]
Can you capture the full console output?

**Comment by duygusuzz** [comment]
yeah sure
![image](https://user-images.githubusercontent.com/80117415/110240654-0d328480-7f5e-11eb-9712-9e9bd76ec8c8.png)

**Comment by duygusuzz** [comment]
Server has pixelmon and biomes'o plenty mod btw

**Comment by duygusuzz** [comment]
I understand the problem I can connect when there is no lobby because ur software detects lobby's version and prepare itself for this so I can't join pixelmon from lobby

**Comment by duygusuzz** [comment]
are there any fix for that?

**Comment by duygusuzz** [comment]
Console Client for MC 1.4.6 to 1.16.5 - v1.16.5 - By ORelio & Contributors
AppVeyor build 450, built on Sat 02/27/2021 from commit 771a5b9
[MCC] [Settings] Loading Settings from C:\Users\Downloads\bot2\MinecraftClient.ini
Login :karakartal
You chose to run in offline mode.
Server IP :localhost
Using Minecraft version 1.12.2 (protocol v340)
Checking if server is running Forge...
Server is running Forge with 6 mods.
Server version : 1.12.2 (protocol v340, with Forge)
[MCC] Version is supported.
Logging in...
[MCC] Server is in offline mode.
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
>/help
[MCC] help <cmdname>. Available commands: entity, animation, changeslot, connect, debug, dig, inventory, look, move, exit, log, reco, respawn, script, send, set, health, sneak, tps, useblock, useitem, list. For server help, use '/send /help' instead.
>/reco play.poke-miner.com
[MCC] Unknown account 'play.poke-miner.com'.
>/disconnect
[commands.generic.notFound]
>/log
[MCC] log <text>: log some text to the console.
>/help
[MCC] help <cmdname>. Available commands: entity, animation, changeslot, connect, debug, dig, inventory, look, move, exit, log, reco, respawn, script, send, set, health, sneak, tps, useblock, useitem, list. For server help, use '/send /help' instead.
>/tps
[MCC] Current tps: 18,4
>/connect play.poke-miner.com
Resolving play.poke-miner.com...
Restarting Minecraft Console Client...
You chose to run in offline mode.
Using Minecraft version 1.12.2 (protocol v340)
Checking if server is running Forge...
Server is running Forge without mods.
Server version : Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x (protocol v754)
Server reports a different version than manually set. Login may not work.
[MCC] Version is supported.
Logging in...
[MCC] Server is in offline mode.
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
karakartal joined the game
Welcome, karakartal!
Type /help for a list of commands.
Type /list to see who else is online.
Players online: 1 - World time: 11:57 AM
Please, login with the command: /login <password>
>/login ******
Successful login!
Welcome karakartal on PokeMiner server

This server uses AuthMeReloaded protection!
>/server pixelmon
Kicked whilst connecting to pixelmon: This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.
>

**Comment by duygusuzz** [comment]
software seeing waterfall as a main server so it doesn't install forge or mods I think

**Comment by ORelio** [comment]
> Checking if server is running Forge...
> Server is running Forge without mods.

So MCC does not enable Forge support. For MC 1.12 and lower, MCC _needs_ the mod list in server ping response. On MC 1.13 and greater, you may force support with `mcforge=true`.

**Comment by duygusuzz** [comment]
can't we add modlist in config?

**Comment by ORelio** [comment]
currently, no, and I think Forge attempts to renegotiate the mod list on server change and MCC does not implement that 🤔
