### ISSUE TITLE
Support for snapshots?

### ISSUE THREAD

**Issue by NiceCraftz** [ORelio/Minecraft-Console-Client#1496]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

Add support for snapshot servers?
as you can see its not joining servers?

![image](https://user-images.githubusercontent.com/47219477/110236812-35a78800-7f38-11eb-9d69-ddd627fb597e.png)

**Comment by ReinforceZwei** [comment]
Why do you want to use MCC in snapshot server? I don't see any point of doing it, as snapshot versions are used for early testing only. Beside that, it is not worth to implement snapshot as it is not stable and will change very frequently.

**Comment by NiceCraftz** [comment]
> Why do you want to use MCC in snapshot server? I don't see any point of doing it, as snapshot versions are used for early testing only. Beside that, it is not worth to implement snapshot as it is not stable and will change very frequently.

support would be great because many server run snapshots. like i have 1 with my friends and we would like to keep our farms loaded during the whole day. since we have a VPS where we can host the bots.

**Comment by ReinforceZwei** [comment]
Then you have to wait for contributor to implement snapshot version for you.

**Comment by ORelio** [comment]
We don't have enough workforce to implement snapshots.
Supporting snapshots requires implementing a new Minecraft version every week.
