### ISSUE TITLE
Issue with autocraft

### ISSUE THREAD

**Issue by Redev837** [ORelio/Minecraft-Console-Client#1497]
"[MCC] [AutoCraft] Error while parsing config:
Duplicate recipe name specified: Part1"
![image](https://user-images.githubusercontent.com/71851438/110266314-81cfe800-7f8b-11eb-99a3-0db5b7849b84.png)

**Comment by ReinforceZwei** [comment]
Please check your auto-craft configuration file. You cannot have two recipe with same name as the error message already told.

**Comment by Redev837** [comment]
[AutoCraft]
# A valid autocraft config must begin with [AutoCraft]

tablelocation=-410,58,3261   # Location of the crafting table if you intended to use it. Terrain and movements must be enabled. Format: x,y,z
onfailure=abort        # What to do on crafting failure, abort or wait

# You can define multiple recipes in a single config file
# This is an example of how to define a recipe
[Recipe]
name=Part1          # name could be whatever you like. This field must be defined first
type=table            # crafting table type: player or table
result=Paper     # the resulting item

# define slots with their deserved item
slot1=Sugarcane
slot2=Gunpowder            # slot start with 1, count from left to right, top to bottom
# For the naming of the items, please see
# https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Inventory/ItemType.cs

**Comment by ReinforceZwei** [comment]
The configuration file is good. The issue is your configuration file is already loaded and you use `/autocraft load` command to load it again. If you want to reload your configuration file, use `/autocraft reload`.
