### ISSUE TITLE
entity.name

### ISSUE THREAD

**Issue by socus** [ORelio/Minecraft-Console-Client#1500]
For entity.name what class is that set in? for example on entity spawn, trying to figure out where the entity.name string is set.

**Comment by Pokechu22** [comment]
It is only set when using this constructor:

https://github.com/ORelio/Minecraft-Console-Client/blob/240468ad228a66dd0548a1049fe158a017d6b85f/MinecraftClient/Mapping/Entity.cs#L105

which is called in `OnSpawnPlayer`:

https://github.com/ORelio/Minecraft-Console-Client/blob/240468ad228a66dd0548a1049fe158a017d6b85f/MinecraftClient/McClient.cs#L1960

Other entity spawns (which'd use the other constructor) don't set it as far as I can tell.
