### ISSUE TITLE
block

### ISSUE THREAD

**Issue by PrivateServersGANG** [ORelio/Minecraft-Console-Client#1501]
How would i block a specific text from going in colsole for me its "|||||||||||||||||||||||||||||| (10%) to B Rank"

**Comment by ReinforceZwei** [comment]
Use the chat filtering feature. In your `MinecraftClient.ini` file `[Logging]` section, uncomment `chatfilter` and setup your regex to block messages.
```ini
#chatfilter=                       # Regex for filtering chat message
```

**Comment by PrivateServersGANG** [comment]
didnt work @ReinforceZwei i put chatfilter=|||||||||||||||||||||||||||||| (97.2%) to Prestige 21,267                # Regex for filtering chat message and it wont show anything now

**Comment by ReinforceZwei** [comment]
Please make sure your regex is in correct format. You may test it at https://regex101.com

**Comment by PrivateServersGANG** [comment]
How do i use regex ive look for a converter and everything dont work

**Comment by ORelio** [comment]
Try this: `\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|` as `|` has a special meaning in regex and must be escaped.

**Comment by PrivateServersGANG** [comment]
Didnt work i put "chatfilter=\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\| as# Regex for filtering chat message"

**Comment by PrivateServersGANG** [comment]
chatfilter=\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\|\| as# Regex for filtering chat message

**Comment by PrivateServersGANG** [comment]
the \ wont show up

**Comment by ORelio** [comment]
Edited your message to make them appear. Your filter looks good, you may attempt to remove anything but the `\|` part to check if it works better.

**Comment by PrivateServersGANG** [comment]
Nothing seems to be working

**Comment by PrivateServersGANG** [comment]
Its a GUI that i dono how to hide it sits above the xp level bar

**Comment by ReinforceZwei** [comment]
You should set below setting to `false` in your `MinecraftClient.ini` file `[Main]` section to hide xp bar message.
```ini
showxpbarmessages=false             # Messages displayed above xp bar
```

Remember to remove `chatfilter` setting if you don't need it.

**Comment by PrivateServersGANG** [comment]
Thank youuuuu
