### ISSUE TITLE
The OreMiner script digs slowly, at ef 6.

### ISSUE THREAD

**Issue by AlexVIA2256** [ORelio/Minecraft-Console-Client#1505]
In general, the script "OreMiner" digs slowly, although it costs a beacon + pickaxe for an efficiency of 6. 
I apologize for my English - I use Yandex translator c;

**Comment by AlexVIA2256** [comment]
Is it possible to somehow add a speed check for the beacon and the tool with which it digs, or how to do it so that it can dig normally?

**Comment by ORelio** [comment]
Currently MCC doesn't calculate the time required to break a block (which depends on block type, item in hand, enchants, effects...) and leaves it to the server so you may notice speed inconsistencies like in #1377
