### ISSUE TITLE
'#' character in INI file password

### ISSUE THREAD

**Issue by Sheridan** [ORelio/Minecraft-Console-Client#151]
Possible fast fix:
string line = lineRAW.Length > 8 && lineRAW.Substring(0, 8) == "password" ? lineRAW.Trim() : lineRAW.Split('#')[0].Trim();

**Comment by ORelio** [comment]
Took me about 5 minutes of thinking to realize you were talking about INI files :sweat_smile:

**Comment by Sheridan** [comment]
Sorry. In the future I will clarify :)

**Comment by Sheridan** [comment]
Maybe JSON? But unfortunately there can not leave comments, it is necessary to make understandable keys. But you can not parse the file, but simply serialize \ deserialize structures. [Or Dictionaryes]([url](http://stackoverflow.com/questions/5597349/how-do-i-convert-a-dictionary-to-a-json-string-in-c))

**Comment by ORelio** [comment]
INI is fine, well, maybe disabling comments on "password" line is okay after all.

**Comment by Sheridan** [comment]
okay. I'm still going to realize bots settings\store data between sessions in json, and therefore proposed.
By the way, I slowly begin to remember С# and [began with refactoring chatbot](https://github.com/Sheridan/Minecraft-Console-Client/commits/Indev).

**Comment by ORelio** [comment]
Splitting ChatBot.cs into smaller files seems a good idea indeed ;)
Closing this issue, feel free to reopen if something does not work properly in INI file passwords.
