### ISSUE TITLE
Loading and unloading of bots are unreliable

### ISSUE THREAD

**Issue by Vort** [ORelio/Minecraft-Console-Client#1510]
There are multiple issues I want to describe in this report.

First of all, it looks like it is not possible to maintain single instance of script without hacks.
If you put in `tasks.ini` `triggerOnFirstLogin`, then after some amount of relogins script will unloaded and not loaded anymore.
If you put `triggerOnLogin`, then after several relogins you will end up with lots of script copies loaded.

To solve this problem I have added such code in my bot (`OreMiner2`):
```csharp
        if (GetLoadedChatBots().Count(x => x is OreMiner2) > 1)
        {
            LogToConsole("OreMiner 2 is already loaded.");
            UnloadBot();
            return;
        }
```

But it did not helped too much since MCC despite `UnloadBot` being called, feels ok to invoke handlers like `Update` for uninitialized and unloaded bot.
I have added checks to return from that functions ASAP since if I allow them to throw exception, MCC often crashes.

But it did not solved problems too!
Because loading and unloading process can produce crashes by itself!

First thing that I have noticed is that sometimes in `DispatchBotEvent` function last element of `selectedBots` array becomes null, which means crash.
Then I decided to make minimized script which can reproduce this problem.
And got another crash:

![image](https://user-images.githubusercontent.com/1242858/112592832-48163280-8e0f-11eb-8a58-801d6c088820.png)

Here is the script:

```csharp
//MCCScript 1.0

MCC.LoadBot(new LoadUnloadBug());

//MCCScript Extensions

public class LoadUnloadBug : ChatBot
{
    public override void Initialize()
    {
        LogToConsole("Load");
        if (GetLoadedChatBots().Count(x => x is LoadUnloadBug) > 1)
        {
            UnloadBot();
            LogToConsole("Unload");
        }
    }
}
```

As you can see at screenshot, I was testing latest version with LoadUnloadBug script.

Please try to improve reliability of loading and unloading process.

I can try to get additional information if you will start working on this problem and will have a need for it.

**Comment by Vort** [comment]
More useful test script:

```csharp
//MCCScript 1.0

MCC.LoadBot(new LoadUnloadBug());

//MCCScript Extensions

public class LoadUnloadBug : ChatBot
{
    List<int> list;

    public override void Initialize()
    {
        LogToConsole("Load");
        if (GetLoadedChatBots().Count(x => x is LoadUnloadBug) > 1)
        {
            UnloadBot();
            LogToConsole("Unload");
            return;
        }
        list = new List<int>();
    }

    public override void Update()
    {
        LogToConsole("Update");
        for (int i = 0; i < list.Count; i++)
        {
            // Do something
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1242858/112598611-80ba0a00-8e17-11eb-8397-1361f5750c25.png)

**Comment by Vort** [comment]
+1:
![image](https://user-images.githubusercontent.com/1242858/112598734-b19a3f00-8e17-11eb-93b8-efa1819ea490.png)

**Comment by ORelio** [comment]
Hello,

Thanks for your report.
Indeed, exceptions inside Initialize() and AfterGameJoined() were not caught, this is now fixed 👍

Regarding your initial issue: Usually when you run a script, the script is compiled on the fly, giving an assembly with `YourBot` class inside. But if you run the script again, unless the assembly was cached in memory (`scriptcache=true` in config), you get a new assembly with a new `YourBot` class inside, so static variables are gone and the class is not equal to the previous one so using the `is` operator will return False.

Please let me know if crashes persist after commit 47c19466c32a074897ef1afba06b60a4e0bbe234 or if bots are still called after being uloaded.

**Comment by Vort** [comment]
I did not knew about `scriptcache=true`, but it is a default value and I did not changed it, so my problems were not related to it: `is` by itself was working fine.
Initial problem was that script was unloaded during disconnects (I can test it further if needed, but I am not sure that I will be able to catch the problem) and I was needed to load it again, but without duplicates.
I see from the code that enumeration should work fine now, not even need to test it.
But script crashes are still possible:
(Same LoadUnloadBug code, but 47c1946 version)
![image](https://user-images.githubusercontent.com/1242858/112726580-e34dfb80-8f26-11eb-9ff9-9d23beebbeea.png)

**Comment by ORelio** [comment]
I could not reproduce using [this script](https://github.com/ORelio/Minecraft-Console-Client/issues/1510#issuecomment-808009633). The second bot unloads fine and the first one works also 🤔

![image](https://user-images.githubusercontent.com/1128206/112728780-2c06b400-8f29-11eb-9f5b-4a326701977d.png)

**Comment by Vort** [comment]
> I could not reproduce using [this script](https://github.com/ORelio/Minecraft-Console-Client/issues/1510#issuecomment-808009633). The second bot unloads fine and the first one works also

That's a [race condition](https://en.wikipedia.org/wiki/Race_condition), it happens not every time and is critical to timing. I was loading scripts fast, but in real situation it can happen sometimes even if scripts are not loaded fast (because of other software uses CPU for example).
I will try to make better reproduction.

**Comment by Vort** [comment]
Simple change:
```csharp
//MCCScript 1.0

for (int i = 0; i < 20; i++)
    new Thread(() => MCC.LoadBot(new LoadUnloadBug())).Start();

//MCCScript Extensions

public class LoadUnloadBug : ChatBot
{
    List<int> list;

    public override void Initialize()
    {
        LogToConsole("Load");
        if (GetLoadedChatBots().Count(x => x is LoadUnloadBug) > 1)
        {
            UnloadBot();
            LogToConsole("Unload");
            return;
        }
        list = new List<int>();
    }

    public override void Update()
    {
        LogToConsole("Update");
        for (int i = 0; i < list.Count; i++)
        {
            // Do something
        }
    }
}
```

And you can catch even crashes in the loop:
![image](https://user-images.githubusercontent.com/1242858/112729070-ff579a00-8f32-11eb-8eb1-53846a424fc4.png)

**Comment by ORelio** [comment]
The Chatbot API is not thread safe. Do not call API methods from a different thread.

**Comment by Vort** [comment]
> The Chatbot API is not thread safe. Do not call API methods from a different thread.

1. It is here just to simplify testing so you do not need to type several <Ctrl>+<V>, <Enter> commands in a second. Script crashes was reproducing also without threads.
2. I suspect that MCC actually uses threads in script loading (and it is why race condition happens). Think about what will happen if `ScriptScheduler.cs` and user from console will execute `/script` at the same time. Will execution happens sequentially or simultaneously?

**Comment by ORelio** [comment]
There is indeed a second thread just for the command prompt. Let me check. 🤔

**Comment by ORelio** [comment]
`/script` and any other command invoked interactively from the command prompt in console should be thread-safe now.
Thanks for pointing that out.

**Comment by Vort** [comment]
That is good, thanks.
But I think about different thing more.

Here is another test:
```csharp
//MCCScript 1.0

MCC.LoadBot(new ThreadTest(Thread.CurrentThread.ManagedThreadId));

//MCCScript Extensions

public class ThreadTest: ChatBot
{
    int tid;

    public ThreadTest(int tid)
    {
        this.tid = tid;
    }

    public override void Initialize()
    {
         LogToConsole("Thread# " + tid);
    }
}
```

![image](https://user-images.githubusercontent.com/1242858/112730863-a2f97800-8f3c-11eb-9cdd-8c74f256fd8b.png)

Every script instance have their own thread.
Which means that `MCC.LoadBot` should be thread safe.

**Comment by ORelio** [comment]
What you are noticing is linked to how MCC loads and run C# scripts.
When running a C# script, MCC will initialize a thread with your C# code inside, see Update() in [Script.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/Script.cs).
On each Update(), your C# code runs for a short time span and is then paused until next update.
The main thread is waiting while the child thread runs, so there is no race condition possible.
When your bot is loaded and initialized from the script, it's done from the child thread hence the different thread ID.
Once loaded, your ChatBot is called from the main thread, try retrieving thread ID from Update() inside your bot.

**Comment by Vort** [comment]
> The main thread is waiting while the child thread runs, so there is no race condition possible.

But script # 1 is not waiting while script # 2 executes its `MCC.LoadBot`.
So `MCC.LoadBot` should not break if it is executed from different threads simultaneously.

**Comment by ORelio** [comment]
In that case the script pause/resume mechanism is not working as intended. I'll see what I can do about this.

**Comment by ReinforceZwei** [comment]
> But script # 1 is not waiting while script # 2 executes its MCC.LoadBot.
> ![](https://user-images.githubusercontent.com/1242858/112730863-a2f97800-8f3c-11eb-9cdd-8c74f256fd8b.png)

This is the expected behavior of script execution. The script pause/resume mechanism ensure all scripts instruction is started one after one, one instruction per tick. The instruction is still executed asynchronously in a dedicated thread. That's why the thread IDs are different.

**Comment by ORelio** [comment]
Hi,
We worked in an invoke mechanism to make the ChatBot API thread-safe: all API calls are invoked on the main thread.
Scripts now run in a separate thread in parallel of the main thread, removing the "short time span on each update" mechanism.
This feature is new and has undergone limited testing so it may contain bugs, however this should resolve the issue.

**Comment by Vort** [comment]
Ok, thanks. I don't play Minecraft now, so I will not test fixes and will close this report.
In case of any problems another report can be opened instead.
