### ISSUE TITLE
How to change attack speed?

### ISSUE THREAD

**Issue by korunanbaka** [ORelio/Minecraft-Console-Client#1511]
How to change attack speed? Attack Speed is low, sorry my English very bad :(

**Comment by ReinforceZwei** [comment]
Are you referencing `AutoAttack` ChatBot? The attack speed of `AutoAttack` is calculated automatically by following factors to ensure maximum attack damage: player attack cooldown (combat cooldown), player mining speed, weapon attack speed and server TPS. You are not able and do not have to adjust the attack speed manually.

> Attack Speed is low

If you think the attack speed is unusual, please provide more information such as video or screenshots.

**Comment by korunanbaka** [comment]
Yeah it's AutoAttackChatBot. I'm playing on 1.8 server, so i need speed attack very high (like tapemouse 1-2), so you can tell me how to change attack speed, very thanks and very sorry because my English so bad

**Comment by ReinforceZwei** [comment]
I don't think you can use `AutoAttack` on 1.8 server because entity handling only works on Minecraft version 1.10 or above and `AutoAttack` require entity handling to be enabled.

**Comment by korunanbaka** [comment]
Oops sorry, i mean my server using a plugin attack 1.18 for 1.12.2, so i need speed to farm xp

**Comment by korunanbaka** [comment]
> I don't think you can use `AutoAttack` on 1.8 server because entity handling only works on Minecraft version 1.10 or above and `AutoAttack` require entity handling to be enabled.

please help me how to change attack speed, i need it, please huhuhuhu

**Comment by korunanbaka** [comment]
please help me, my PC is very low, so i was finding this client, finally i got it but attack speed so low than i need, very thanks, sorry my English so bad

**Comment by korunanbaka** [comment]
@ReinforceZwei this is first time i use github so i don't know how to get it, pls give me a file , i'm very very very sorry because i'm 11 years old, so i'm very stupid and sorry again because my English so bad

**Comment by korunanbaka** [comment]
Thank you very much, it works
