### ISSUE TITLE
Can you add auto click?

### ISSUE THREAD

**Issue by okokmayconchonayok** [ORelio/Minecraft-Console-Client#1513]
Can you create a autoclick chatbot? Just only 1 record at center before i leave game and can change delay speed. If you can, thank you very much, if you can't, thank you again! ^_^. (Sorry my English is not good because i'm from ASIA, Viet Nam =^_^=

**Comment by ORelio** [comment]
Hello,
There is not such thing as "clicking" in the network protocol used by Minecraft.
For instance, when you click in the Minecraft game, you can perform an inventory action, place a block, hit a mob, etc.
But the game will determine the appropriate action for you and do it.
Depending on the action you want to do, Minecraft Console Client can or cannot yet do it.
