### ISSUE TITLE
how to use OreMiner and CobbleStoneMiner?

### ISSUE THREAD

**Issue by okokmayconchonayok** [ORelio/Minecraft-Console-Client#1514]
i found OreMiner and CobbleStoneMiner at \MinecraftClient\config\ChatBots but i don't know how to use, if this ChatBots can use pls help me how to use, thanks

**Comment by ReinforceZwei** [comment]
Put those scripts to the same folder as your `MinecraftClient.exe`. Then load them with command `/script scriptname.cs`.
