### ISSUE TITLE
Inventory closed

### ISSUE THREAD

**Issue by etochesnok** [ORelio/Minecraft-Console-Client#1515]
**Prerequisites**
 - 

- [ + ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)

 - [ + ] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [ + ] I have set `debugmessages=true` in config to diagnose my issue
 - [ + ] I have redacted session tokens and passwords before attaching screenshots

## Specifications

  - Console Client version: last
  - Device: Laptop
  - Operating System: win 10
  - Minecraft version: 1.10

I use script:
_**send /skyblock
wait 5
inventory 1 click 1**_

I have an error:

![image](https://user-images.githubusercontent.com/81507954/112746603-797e3200-8fb8-11eb-860e-c17f234d4f7b.png)

Inventory closed, but i'm need to choose first item for connect to second server.

**Comment by ORelio** [comment]
Try enabling terrain and movements and/or entity handling.
The server may close the inventory if it cannot detect where you are.
Also see #1247 this issue looks similar.

**Comment by etochesnok** [comment]
Thank you.
