### ISSUE TITLE
OnDisconnect() is aborted too fast when using AutoRelog

### ISSUE THREAD

**Issue by Vort** [ORelio/Minecraft-Console-Client#1517]
Not enough time is given for my script to perform cleaning tasks.
Packet processing thread, which calls `OnDisconnect` handler, is aborted almost immediately.

Here is the test script:
```csharp
//MCCScript 1.0

MCC.LoadBot(new SlowDisconnect());

//MCCScript Extensions

public class SlowDisconnect: ChatBot
{
    public override void Initialize()
    {
         LogToConsole("SlowDisconnect script is initialized.");
    }

    public override bool OnDisconnect(DisconnectReason reason, string message)
    {
        if (reason != DisconnectReason.UserLogout)
        {
            for (int i = 10; i > 0; i--)
            {
                LogToConsole("Cleaning up: " + i);
                Thread.Sleep(100);
            }
            LogToConsole("Cleaning finished.");
        }
        return false;
    }
}
```
Here is the result of running script and terminating connection using CurrPorts software (with admin rights):
![image](https://user-images.githubusercontent.com/1242858/112873588-80956500-90ca-11eb-980c-6c3c3d1e5503.png)

`[AutoRelog]` is enabled with `delay=10`.
When I disable it, problem not reproduces.
But I need autorelog functionality.

**Comment by ORelio** [comment]
Seems definitely plausible that AutoRelog triggering a relog will kill the thread immediately. I'll see what I can do about this.

**Comment by Vort** [comment]
Random ideas: 417894e727c653ea82037dea34b2b2b1115dc356.

**Comment by ORelio** [comment]
OK so after thinking about the issue I changed the code so that `AutoRelog` will always be called last in the event of lost connection. This should give your bot unlimited time to perform cleanup because `AutoRelog` is called only after every other bot has finished processing the `OnDisconnect` event.
