### ISSUE TITLE
Cannot detect %variable% in matches.ini regex

### ISSUE THREAD

**Issue by WolfgamingWG** [ORelio/Minecraft-Console-Client#1518]
As the title of this issue said, I cannot detect a variable in matches.ini
Yes, I did make sure that %searchtarget% is correctly configured, and yes I did make sure with regex101 that it can detect the regex if it was the username instead of the username via a variable.

Example of what I am trying to do:
I am trying to detect: " 15. [Rankhere] Namehere, $12,345,678.90 "

with this regex: [0-9]+\. (?:\[[^]]+\] )?%searchtarget%, (\$[0-9]+(?:,[0-9]+,[0-9]+.[0-9]+|,[0-9]+|,[0-9]+,[0-9]+|,[0-9]+.[0-9]+|,[0-9]+,[0-9]+.[0-9]+|.[0-9]+|))

%searchtarget% being Namehere under the variable, and the number, $ and rank being random.

when the regex gets detected it will send me a msg it found where the person is.

The full thing in matches.ini looks like this:  
[Match]
regex=[0-9]+\. (?:\[[^]]+\] )?%searchtarget%, (\$[0-9]+(?:,[0-9]+,[0-9]+.[0-9]+|,[0-9]+|,[0-9]+,[0-9]+|,[0-9]+.[0-9]+|,[0-9]+,[0-9]+.[0-9]+|.[0-9]+|))
actionother=send /msg Owner (BOT SEARCH) %searchtarget% has been found on spot $1 with a balance of $2!

**Comment by ORelio** [comment]
Hello,
Indeed, currently regexes and matches in AutoRespond do not take into account %variables%. We could add this, but since the regex is compiled when loading the bot (for performance reasons), the bot would read the %variable% value at the time it's loaded, and the match would not change afterwards if you change the variable. Would that fit your needs anyway?

**Comment by WolfgamingWG** [comment]
Sadly no, I do not see another way to make the bot do what i want without the variable, is there another way to make the bot be able to detect something as if it is a variable (as in my example)?

**Comment by WolfgamingWG** [comment]
Update: i have given up on this idea, i am suggesting to you to add variable support in matches.ini since it would be useful. Feel free to close this ticket if you would like.
