### ISSUE TITLE
Matches won't send actions in game

### ISSUE THREAD

**Issue by 32andrewlew** [ORelio/Minecraft-Console-Client#1520]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])
I am using the sample matches.ini and I would like to use the action commands to send messages on a server, however, the console client never seems to execute any commands or send messages. 

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])
When using matches.ini, my console client seems to detect the message but it never seems to execute any action command. I can see in the console client "actionother" detects the message and logs it. However, action= ... never seems to work in game.

---
## Solutions you've already considered

1. Set [...] setting in my config
2. Restarting from scratch, making new match commands, testing different ways

---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

This detects the match, but never sends any chat message or command in chat
[Match]
match=hi
action=send hi, $u!
actionprivate=send /tell $u Hello!
actionother=log detected "hi" message
ownersonly=false

**Comment by ORelio** [comment]
Did you make sure chat messages are properly detected to begin with?
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages

**Comment by u9g** [comment]
I was testing with him, yes they were being detected, i'm sure that the regex was right, the problem was that every match action would work that was just to log to the console, but the one that was `send hi` to the actual server chat wouldn't send.

**Comment by ORelio** [comment]
If... :
```
 actionother=log detected "hi" message
```
...triggers all time, this means that chat messages are not detected as chat messages and you need to [fix chat format regex]( https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages).
You can check that everything is detected properly using [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs).

**Comment by u9g** [comment]
no, no, not all the time, just when someone says hi, then the hi match works. the match works fine, it just wont use `send hi` back, it will only `log hi`.

**Comment by ORelio** [comment]
Ok, I'll explain myself better.
When MCC sees a messages, it determines if it is a public message, a private message, or something else.
In AutoRespond, depending on the type of message, it triggers actionpublic, actionprivate or actionother.
Seems like all your messages are detected as other, which means chat message format is not properly configured.

**Comment by u9g** [comment]
> Ok, I'll explain myself better.
> When MCC sees a messages, it determines if it is a public message, a private message, or something else.
> In AutoRespond, depending on the type of message, it triggers actionpublic, actionprivate or actionother.
> Seems like all your messages are detected as other, which means chat message format is not properly configured.

so it only runs the actionother?

**Comment by ORelio** [comment]
it never runs several actions at once. Only one out of three depending on message type.

**Comment by 32andrewlew** [comment]
Thanks, this fixed the issue
