### ISSUE TITLE
Script wont send actions to game half of the time

### ISSUE THREAD

**Issue by NotIMaestro** [ORelio/Minecraft-Console-Client#1521]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])
I want the app to log in to a server, do /home, and start looking up and down every so often, with around a 1200 tick difference
so i dont get kicked for afk

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])
in the console app it says "MCSCRIPT(or something) Look Down" and it works, but half of them time it says that and doesnt move
(i have checked by using an alt to view my account)

---
## Solutions you've already considered

1. Changing the tick interval
2. Deleteing everything and doing it again

---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)
[commands.txt](https://github.com/ORelio/Minecraft-Console-Client/files/6249031/commands.txt)
this is the script that gets called upon on login using the script handler or scheduler thing

Thanks!

**Comment by ORelio** [comment]
Hi,
I'd suggest using [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler) for that purpose. Here is an example to do /home on login and jump every 30 seconds:
```ini
[Task]
triggerOnLogin=true
action=send /home

[Task]
triggerOnInterval=true
timeInterval=30
action=move up
```

You can also mix scripts by using `action=script myscript.txt` then put several actions in your script.

**Comment by NotIMaestro** [comment]
Yeah, the same things happens.. it works once in a while  but not every time i tell it to
this is what i tried:
`[Task]
triggerOnLogin=true
action=script commands.txt

[Task]
triggerOnInterval=true
timeInterval=30
action=look east

[Task]
triggerOnInterval=true
timeInterval=60
action=look west`

I've also tried doing it manually through the console and it doesnt work, like /move up or /move south
it says "Moving south" but in fact doesnt move

**Comment by NotIMaestro** [comment]
Is there any way to make it so every 30 seconds it just spins? like faces north then east then south then west ect ect'
repeating itself every 30 seconds?

**Comment by ORelio** [comment]
Use the [Look](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Commands/Look.cs) command.
`look <x y z|yaw pitch|up|down|east|west|north|south>`
