### ISSUE TITLE
How to Interact with Shop GUI and doing autocrafting?

### ISSUE THREAD

**Issue by ghifarry** [ORelio/Minecraft-Console-Client#1522]
I need to make a bot that will do a command and buy materials that needed for crafting, is it possible to interact/click Shop GUI and do autocrafting from ``/craftingtable`` command without using crafting table?

so, first the player will do ``/market`` to open the shop gui and then selecting item that needed for the crafting
```
╔═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╦═══╗
║ A ║ B ║ C ║ D ║ E ║ F ║ G ║ H ║ I ║
╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
║ J ║ K ║ L ║ M ║ N ║ O ║ P ║ Q ║ R ║
╠═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╬═══╣
║ S ║ T ║ U ║ V ║ W ║ X ║ Y ║ Z ║ 0 ║
╚═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╩═══╝
...
```
here, player will click the ``M`` slot to buy diamonds (x64), after that it will do ``/craftingtable`` command and open the crafting gui
```
╔═══╦═══╦═══╗
║ 1 ║   ║ 3 ║
╠═══╬═══╬═══╣
║ 4 ║ 5 ║ 6 ║
╠═══╬═══╬═══╣
║ 7 ║ 8 ║ 9 ║ 
╚═══╩═══╩═══╝
```
and place the diamonds to 1,3,4,5,6,7,8,9 slots to make diamonds armor.

and loop the process until player reach the certain levels for mcMMO jobs

how can i make the script like this and how? is there any example script to interact with shop gui? ive seen the [autocraft bot](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autocraft-bot) bot i still dont know how to implement them into a script

**Comment by ORelio** [comment]
I'm not very familiar with the crafting part, @ReinforceZwei maybe you could have a look?

**Comment by ReinforceZwei** [comment]
Sorry but you cannot use autocraft in this situation. Autocraft currently isn't smart enough to split a set of material to craft the required item. In your case, you would need 8 sets of diamond or splitting one set of diamond into 8 stack manually to craft the diamond armor. This will be improved in the future.

**Comment by ghifarry** [comment]
> Sorry but you cannot use autocraft in this situation. Autocraft currently isn't smart enough to split a set of material to craft the required item. In your case, you would need 8 sets of diamond or splitting one set of diamond into 8 stack manually to craft the diamond armor. This will be improved in the future.
> 
> Related issue: [#1476 (comment)](https://github.com/ORelio/Minecraft-Console-Client/issues/1476#issuecomment-783405551)

but if im not splitting the item and just buy 8 stacks of diamonds and craft them all into diamond armor, is it still possible?

**Comment by ReinforceZwei** [comment]
> just buy 8 stacks of diamonds

Yes, it is possible.

Define a recipe of diamond armor for `AutoCraft`

Use a simple script to execute commands.
```
send /market
wait 1
inventory c click 12
wait 1
send /craftingtable
wait 1
autocraft start <recipe name>
wait 5
script <script name>
```
Adjust the delay if the commands executing too fast.

**Comment by ghifarry** [comment]
so, if want to make something like that,
i add this to ``MinecraftClient.ini``
```
[AutoCraft]
enabled=false
configfile=recipe.ini
```
and for the ``recipe.ini``
```
[Recipe]
name=diaarmor
type=table
result=DiamondChestplate

slot1=Diamond

slot3=Diamond
slot4=Diamond
slot5=Diamond
slot6=Diamond
slot7=Diamond
slot8=Diamond
slot9=Diamond
```

and then add that to ``[Task]`` .txt file
```
send /market
wait 1
inventory c click 12
wait 1
send /craftingtable
wait 1
autocraft start diaarmor
wait 5
script <script name>    # i still dont get it what you mean by this, what script i should run?
```


and now i have a question, everytime it craft is it automatically goes into my inventory? i mean diamond chestplate is non-stackable item and player inventory can only hold 36 items while in total it will craft 64 diamond armor, can i just throw it after its done crafting? 
or should i just buy 4.5 stack of diamonds and craft 36 diamond chestplate and then ``/clearinventory`` (to clear all my inventory) and repeat the process? since i dont need any of them and only doing that to get my mcMMO exp

**Comment by ReinforceZwei** [comment]
> and then add that to [Task] .txt file

Not task but script. Save the text to a file named `<script name>.txt` and replace `script <script name>` with the file name. See https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-write-a-script-file

> can i just throw it after its done crafting?

To drop items from inventory, use `AutoDrop`. 

> player inventory can only hold 36 items while in total it will craft 64 diamond armor

Honestly I have never tested `AutoCraft` with non-stackable item and I have no idea what would happens if inventory was full.
