### ISSUE TITLE
Need help regarding Autoresponder 

### ISSUE THREAD

**Issue by HeavinSlayer109** [ORelio/Minecraft-Console-Client#1525]
Hi, I wanted to have an Autoresponder that responds to server messages, like if the bot sees a tellraw message saying something like:

You have a new friend, (ign of a player) !!

And the bot autoresponds with:

Hi (ign of the player) !!

And the variable for the player as %friend%

**Comment by ORelio** [comment]
```ini
[Match]
regex=^You have a new friend, ([a-zA-Z0-9_]+) !!$
actionother=hi $1 !!
```

**Comment by HeavinSlayer109** [comment]
Thanks
