### ISSUE TITLE
Detect world change

### ISSUE THREAD

**Issue by NotIMaestro** [ORelio/Minecraft-Console-Client#1527]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

---
## Describe your problem
Present a concise description of the problem to be addressed by this feature request. 
The server i afk on uses bungeecord, and it has a hub for when you first join, then you do a command to go into the server (factions server) so i setup a script that makes me afk, but sometimes the bungeecord fails/restarts and it kicks me out of the server/the end dimension (i afk at the enf dimension and sometimes it just kicks me “the fallback server you were on failed blah blah ect”)

---
## Suggest a possible solution
A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])
Add a function that detects dimension/world change (when you go into a loading screen to get into another world)
Example: 
[Task]
OnWorldChange
action = somerandomscript.txt

other example:
[Task]
OnWorldChange
action = send /join factions

---
## Screenshot to help explain your request (If applicable)

**Comment by ReinforceZwei** [comment]
You may use ChatBot API `OnRespawn()` to detect player respawn, which would also happens when changing world. See https://github.com/ORelio/Minecraft-Console-Client/issues/1411#issuecomment-759510061 for example script.
