### ISSUE TITLE
Can the App interact with weird inventory GUI sizes?

### ISSUE THREAD

**Issue by crypthusiast0** [ORelio/Minecraft-Console-Client#1528]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])
I'm wondering if the app could click on a non-vanilla inventory GUI, like such: 
![image](https://user-images.githubusercontent.com/42322215/113654741-53f2c780-964d-11eb-837c-40c3bd5fbb52.png)

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])
I don't know how to do this lol

---
## Solutions you've already considered

1. I was thinking to use AutoCrafter for interacting with the GUI, however I'm not sure how it would do with this because it is a 4x9 inv instead of a regular chest size (3x9) or double chest (6x9).
2.

---
## Screenshots to help explain your situation (If applicable)
![image](https://user-images.githubusercontent.com/42322215/113654846-9a482680-964d-11eb-8516-6c08dee8c4fc.png)
As shown in the image, I want to be able to click on the head

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

**Comment by ReinforceZwei** [comment]
In theory, yes. You may want to test it with `/inventory p` command to see if you can view the whole inventory slots.
