### ISSUE TITLE
Chat Format Help (If Possible)

### ISSUE THREAD

**Issue by warzoneak** [ORelio/Minecraft-Console-Client#1529]
**Prerequisites**
 - [yes ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [yes] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [yes ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

I'm try to figure out the regex for my client. So i can join a party

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])
So i have no real coding experience or really understanding but i gave this a go before i decided to ask for help. I checked all the chat format issues and worked out a little here and there and i thought i had it figured out but i def dont.

---
## Solutions you've already considered

1. Set [...] setting in my config
2.

![56abcf9b99d9920b4c74973b5646619a](https://user-images.githubusercontent.com/43768433/113656343-b2c63a00-9669-11eb-8c0f-e6b3eead71b8.png)

---
## Screenshots to help explain your situation (If applicable)
![Screenshot_2](https://user-images.githubusercontent.com/43768433/113656060-0f752500-9669-11eb-9e12-d3b07184c5ab.png)

This is what i came up with for regex:

^(.[a-zA-Z]+) (.[a-zA-Z]+[^a-z].) (.[a-zA-Z]+.) (.+)$

![regex](https://user-images.githubusercontent.com/43768433/113656114-30d61100-9669-11eb-8b48-f44af99fda9c.png)

https://regex101.com/r/yjwsFk/1

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

Anything you need i will post. Im obviously wrong cause its not working and i mean it would be amazing for some help but if you could atleast point me in the right direction ill take the time to figure it out.

**Comment by ReinforceZwei** [comment]
Your regex cannot capture username and message correctly. Username should be captured in group 1 and message should be in group 2. Please try again with below regex:
```
^From .* ([a-zA-Z0-9_]+): (.+)$
```
https://regex101.com/r/j30I7a/1
