### ISSUE TITLE
MinecraftClient.ini file line break become \r

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1536]
---
## Expected Behavior
File in `Resource\config\` folder. (newly cloned from Github)
![image](https://user-images.githubusercontent.com/39955851/114307047-7b93d500-9b10-11eb-9eb0-6aaaeea377e2.png)

---
## Actual Behavior
File created by MCC
![image](https://user-images.githubusercontent.com/39955851/114307034-6fa81300-9b10-11eb-8790-d8a097d2fd4f.png)

How it looks using built-in Notepad
![image](https://user-images.githubusercontent.com/39955851/114307167-fe1c9480-9b10-11eb-933f-49b8bcf5dc68.png)

---
## Steps to Reproduce the Problem

  1. Download latest build.
  2. Make sure MCC is in a clean directory.
  3. Launch MCC and open the `MinecraftClient.ini`

---
## Specifications

  - Device: Desktop
  - Operating System: Windows 7

---

Not sure if it is my problem or something else.

**Comment by ORelio** [comment]
That's weird indeed. Line breaks are dependant of Git configuration, maybe AppVeyor clones the repository with `\r` line endings and embeds the `MinecraftClient.ini` that was cloned using incorrect line endings? The only fix I see here would be to automatically adjust line endings depending on the operating system when writing the file to disk. i.e `\r\n` on Windows and `\n` on Mac/Linux.

https://docs.microsoft.com/en-us/dotnet/api/system.environment.newline

**Comment by ReinforceZwei** [comment]
> maybe AppVeyor clones the repository with \r line endings and embeds the MinecraftClient.ini that was cloned using incorrect line endings


If it is the case, translation file should be affected too. I will do more investigation when free.

**Comment by ORelio** [comment]
[Translations.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Translations.cs) uses [File.ReadAllLines](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalllines), which handles all kinds of line breaks (`\r` or `\n` or `\r\n`) automatically:

https://github.com/ORelio/Minecraft-Console-Client/blob/2017d5d652251657cb8944002b2df2bd32ff72d8/MinecraftClient/Translations.cs#L127-L131

https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalllines

> This method opens a file, reads each line of the file, and then adds each line as an element of a string array. It then closes the file. **A line is defined as a sequence of characters followed by a carriage return ('\r'), a line feed ('\n'), or a carriage return immediately followed by a line feed.** The resulting string does not contain the terminating carriage return and/or line feed.
