### ISSUE TITLE
Can anyone fix this script?

### ISSUE THREAD

**Issue by Tnavillacs** [ORelio/Minecraft-Console-Client#1541]
```
    public override void GetText(string text)
    {
		text = GetVerbatim(text);
			if(text.Equals("message in chat"))
				{
				SendText("/shop");
public override void OnInventoryUpdate(int inventoryId)
        {
				SendText("/inventory " + inventoryId + " click 0");
				public override void OnInventoryUpdate(int inventoryId)
                {
				SendText("/inventory " + inventoryId + " click 10");
				     public override void OnInventoryUpdate(int inventoryId)
                     {
				      SendText("/inventory " + inventoryId + " close");
                                      SendText("/useitem");
		             }
		        }
									
        }
				}
}
}
```
I'm trying to make him open the shop GUI, buy something and then right click it.

**Comment by ORelio** [comment]
`SendText` will send the `/inventory` command to the server.
You'll want to use `PerformInternalCommand` instead, and for internal commands, do not prepend `/`.
You can also use `WindowAction` instead of the `inventory` command.
See [ChatBot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs) for full API.

**Comment by Tnavillacs** [comment]
It already worked like that, but I'll use PerformInternalCommand instead. The actual problem was, that I need some kind of delay between all commands. My script didn't start.

**Comment by ORelio** [comment]
You can defer an action by setting a counter in GetText e.g. `ticksBeforeInventoryAction = 10`
Then in `Update()` decrement the counter and when it reaches 0, do the action.
```C#
public override void Update()
{
    if (ticksBeforeInventoryAction > 0)
    {
        ticksBeforeInventoryAction--;
        if (ticksBeforeInventoryAction == 0)
        {
            // do action here
        }
    }
}
```
