### ISSUE TITLE
MCC On Raspberry Pi

### ISSUE THREAD

**Issue by eternalUnion** [ORelio/Minecraft-Console-Client#1542]
I am trying to run MCC (build 466) on raspberry pi (3rd generation model B to be more specific) from terminal with a decent ethernet connection. I managed to install mono (v6.12.0.122) and login to my account. However for some reason, client freezes when it joins the server and after ~30s (exactly after timeout) it slowly prints all the past chat [at the beggining, for some reason, it prints the first few lines server send eg. rank advertisements before freezing] and gets disconnected from the server [Disconnected by Server : ] [ReadTimeoutException : null]. It also processes my past commands, eg /send /help, after disconnecting. I tested MCC with same version on my main linux pc and it worked well, so I am suspicious of raspberry's armhf architecture, mono and the speed of the raspberry [though it should be capable of handling such a task with 1.2 ghz clock]. Has running this on armhf ever attempted? Is there anything I can do to make it work?

Edit: For some reason, MCC works on some servers, cause could be severe lag on the other ones?

Edit 2: After some monitoring, I found that when I join that one server with problem, cpu usage bumps up to 100% (though servers that work fine work at 100% too). I do not know the cause but I do not think MCC would be this heavy, maybe because of mono emulating the whole program? [If the server is very light, eg. Hypixel's Limbo, cpu usage is near 0.3%]

**Comment by ORelio** [comment]
The high CPU usage when joining might be due to terrain handling which takes a while to load everything on login.
However there is a known silent disconnection bug on Mono for the Pi that we still could not track down. See #1306.

**Comment by MrDeniz** [comment]
Is it possible to disable terrain modeling? What I need is just the chat interface

**Comment by ReinforceZwei** [comment]
Terrain and movement is default off if you didn't change the configuration. 
```ini
terrainandmovements=false
```

**Comment by MrDeniz** [comment]
```
terrainandmovements=false
inventoryhandling=false
entityhandling=false
```

I did not change the config file, the problem persists.

**Comment by ReinforceZwei** [comment]
There's a setting for render distance.
```ini
[MCSettings]
...
renderdistance=medium
...
```
Maybe setting it to `tiny` would help a bit.

**Comment by MrDeniz** [comment]
> There's a setting for render distance.
> 
> ```ini
> [MCSettings]
> ...
> renderdistance=medium
> ...
> ```
> 
> Maybe setting it to `tiny` would help a bit.

Unfortunately it did not work, even though I had high hopes for this one. Planning on digging the ini file a little more

**Comment by MrDeniz** [comment]
For now, I solved it by writing my own chat client on nodejs. The project would have been better if it could have been compiled to both mac and linux's own image (though I think there was universal one for .core where you can use c# for all platforms)

**Comment by Laukage** [comment]
I planning on installing this on a raspberry pi, doesn't it work at all or only specific tasks are causing issues?

**Comment by ORelio** [comment]
It should work for everything _but_ you may experience silent disconnections.

**Comment by Laukage** [comment]
Doesn't autoreconnect solve this?

**Comment by eternalUnion** [comment]
> I planning on installing this on a raspberry pi, doesn't it work at all or only specific tasks are causing issues?

From my experience, it may not work on every server. Maybe if you have a faster pi you may have higher odds than me since mine is a 'little' outdated model. The best way I suggest is to finding it out.

**Comment by Laukage** [comment]
i have PI 4 model b, however only with 4gb ram and not 8.

**Comment by ReinforceZwei** [comment]
I wrote a debug version of MCC that can generate a report of the processing time of each packet to help diagnosing the problem. You can clone the following branch and build it with Visual Studio.

https://github.com/ReinforceZwei/Minecraft-Console-Client/tree/timing

It will generate a report `packet-timing-report.txt` after disconnected or using `/stoptime` command:
![image](https://user-images.githubusercontent.com/39955851/114980241-c15cee80-9ebe-11eb-9fb9-310ea6f5cdd7.png)

**Comment by ReinforceZwei** [comment]
> i have PI 4 model b, however only with 4gb ram and not 8.

Pi4 4GB is enough for running MCC. I used to be using MCC on my Pi4 to AFK on a server 24/7 and it is working great. For the _silent disconnections_ issue, it should be fine with `AutoRelog` enabled from my own experience.

**Comment by ORelio** [comment]
A long time ago I would run MCC in chat-only mode on a Pi1 Model B+... that thing had 512MB of RAM. So 4GB is plenty.

**Comment by eternalUnion** [comment]
> A long time ago I would run MCC in chat-only mode on a Pi1 Model B+... that thing had 512MB of RAM. So 4GB is plenty.

How can I start in chat-only mode?

**Comment by ReinforceZwei** [comment]
MCC is default chat-only mode if you didn't change any settings.

**Comment by ReinforceZwei** [comment]
MCC is default chat-only mode if you didn't change any settings.

**Comment by ORelio** [comment]
(Tried to delete a duplicate comment for cleaning up but that just replace it with a deletion notice 😅 )

> How can I start in chat-only mode?

```ini
[Main]
terrainandmovements=false
inventoryhandling=false
entityhandling=false
```

Those are default settings in MinecraftClient.ini just don't change them and you are in chat-only mode.
