### ISSUE TITLE
Auto /tpacccept

### ISSUE THREAD

**Issue by RSNFreud** [ORelio/Minecraft-Console-Client#1543]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

When the bot is teleported for it to /tpaccept username

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do

Console client can't seem to pick up the chat message
---

**Comment by ORelio** [comment]
If your server is using a non-standard chat format, you need to adjust the chat format in the configuration file
See: https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages

**Comment by RSNFreud** [comment]
![image](https://user-images.githubusercontent.com/23102186/114772921-11309e00-9d77-11eb-9483-e6698cafbc9d.png)
This is how the message looks... Do I need to remove the ^ from the regex?

**Comment by RSNFreud** [comment]
for the chatformat am i able to define a new format for server messages?

**Comment by ORelio** [comment]
See **MinecraftClient.ini**:
```ini
[ChatFormat]
builtins=false
public= # Regex goes here
private= # Regex goes here
tprequest=^\(!\) ([a-zA-Z0-9_]+) has requested (?:to|you) teleport to (?:YOU|THEM)!$
```

https://regex101.com/r/oqDORG/1

**Comment by RSNFreud** [comment]
Does the regex have to be the full message?

**Comment by ORelio** [comment]
Yes.

With capture groups to detect which part is the username and which part is the message.
First one with username, second one with message.

Sample regex for vanilla messages:
```ini
public=^<([a-zA-Z0-9_]+)> (.+)$
private=^([a-zA-Z0-9_]+) whispers to you: (.+)$
tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$
```

Try them out on https://regex101.com/ 😉
