### ISSUE TITLE
Allow subfolders to be used for scripts

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1546]
Until now we have 3 Bots which have script folders with up to 80 script files and its very hard to get an structure into them because they have to be all in the script folder. Would be very nice, if an option would be implemented to kinda sort them in different subregisters in the scripts folder. I know you know want to give me the advice to use links to scripts somewhere else but this apperead to be also unmanagable up from a specific number of scripts you want to use. (Also can you explain me how i can use links in such a way that multiple bots use the same subfolder of scripts without interrupting each other afterwards)
Would be very very grateful if something like this would be made possible and could imagine to help with the technical part if some kind of pull request is opened, even if I'm kinda new to c#.
Thanks, xXjojaXX

**Comment by ORelio** [comment]
Currently, you can do this:

* `MinecraftClient.exe`
* `scripts`
  * `samplescript1.txt`
  * `subfolder`
    * `samplescript2.txt`

Then launch scripts like this:
```
/script samplescript1
/script subfolder/samplescript2
```
Would that fit your needs?

**Comment by ReinforceZwei** [comment]
I would suggest allowing both relative path and absolute path as input.

E.g. 
- `/script D:\script\a.cs` would load the script from D drive.
- `/script ..\script\b.cs` would load the script from parent folder.

The flexibility would be higher.

**Comment by xXjojaXx** [comment]
> Currently, you can do this:
> 
> * `MinecraftClient.exe`
> * `scripts`
>   
>   * `samplescript1.txt`
>   * `subfolder`
>     
>     * `samplescript2.txt`
> 
> Then launch scripts like this:
> 
> ```
> /script samplescript1
> /script subfolder/samplescript2
> ```
> 
> Would that fit your needs?

Its also nice indeed to have this option but I hoped there is or will be an option that is usable a little bit more for automation. If I want to start scripts manually thats completly fine, but most of scripts get started automatically and should still be able to run in the same way if they get reorganized.

**Comment by xXjojaXx** [comment]
> I would suggest allowing both relative path and absolute path as input.
> 
> E.g.
> 
> * `/script D:\script\a.cs` would load the script from D drive.
> * `/script ..\script\b.cs` would load the script from parent folder.
> * `/script d.cs` would load the script from current directory (same as current behavior)
> 
> The flexibility would be higher.

First of all, can this already be used in the task or matches files? Second off all thats very nice to use in combination with orelios suggestion so I can store all my scripts in one external folder with one subfolder for each mcc application and one with scripts that get used by all of them. I'm gonna try that out this evening. Thanks for your answers.

**Comment by ReinforceZwei** [comment]
> I'm gonna try that out this evening.

My comment is a suggestion and have not be implemented yet.

**Comment by xXjojaXx** [comment]
Would be nice if you would implement it (your suggestion) , because it would be very useful. Looking forward to trying it :)

**Comment by ReinforceZwei** [comment]
> I would suggest allowing both relative path and absolute path as input.
> 
> E.g.
> 
> * `/script D:\script\a.cs` would load the script from D drive.
> * `/script ..\script\b.cs` would load the script from parent folder.
> * `/script d.cs` would load the script from current directory (same as current behavior)
> 
> The flexibility would be higher.

I found that this behavior is already supported.
![image](https://user-images.githubusercontent.com/39955851/116786482-743d6700-aad1-11eb-86a1-ffcf86dc0adb.png)

**Comment by xXjojaXx** [comment]
Thank you very much
