### ISSUE TITLE
Hypixel text on screen showing in log

### ISSUE THREAD

**Issue by SsValor** [ORelio/Minecraft-Console-Client#1547]
so i tried using MCC in hypixel and i found a problem , hypixel has a system that outputs text in screen , things like announcements , points , and player stats 
for better understanding of what i'm saying check this picture 

![Screenshot 2021-04-19 201819](https://user-images.githubusercontent.com/71332929/115265370-66402b80-a14c-11eb-9356-02f6bee365b5.png)

the problem is MCC thinks this is a chat message ( maybe thats the hypixel chat format and nothing is wrong with MCC )
but as you can see in the picture bellow the log will get filled with that text 

![Screenshot 2021-04-19 202018](https://user-images.githubusercontent.com/71332929/115265640-ac958a80-a14c-11eb-8066-3643e0a943c1.png)

and thats a bit annoying i tried filtering the text in MinecraftClient.ini . [Logging] Section , by writing a simple Regex and i tried testing that its working in https://regex101.com/ and its working fine in there
but it doesn't work in the bot ( i am using the latest version of the build and everything else i checked is working fine )
im guessing its something to do with the coloring of the text and the bot doesn't detect it in that color 

if anyone could help i would really appreciate it , its getting a bit annoying seeing all these text in my log xD

**Comment by ReinforceZwei** [comment]
You can disable it in the configuration file.
```
[Main]
...
showxpbarmessages=true
```
Set it to `false`.

**Comment by GamingFrazix** [comment]
Tried It Still Dosent Work Im I Doing This Wrong?
![image](https://user-images.githubusercontent.com/101343003/157862961-b967a3de-4409-400c-818b-dbe37019e864.png)

**Comment by ReinforceZwei** [comment]
@GamingFrazix 
https://github.com/MCCTeam/Minecraft-Console-Client/blob/41950c8b20f0d54528b59fc228e01070328b4f67/MinecraftClient/Resources/config/MinecraftClient.ini#L31-L34

**Comment by GamingFrazix** [comment]
> @GamingFrazix
> 
> https://github.com/MCCTeam/Minecraft-Console-Client/blob/41950c8b20f0d54528b59fc228e01070328b4f67/MinecraftClient/Resources/config/MinecraftClient.ini#L31-L34

Oh Sorry Got It Now Ty For Helping

**Comment by ORelio** [comment]
If you put the same option twice, the second one will override the first one.
Your config file likely had `showxpbarmessages=false` first then `showxpbarmessages=true` below 😉
