### ISSUE TITLE
How do you update your client to a different version ?

### ISSUE THREAD

**Issue by Abandonnn** [ORelio/Minecraft-Console-Client#155]
I have a lad of mine who very briefly explained to me how to do this-- however I didn't really understand any of it.

He told me that I have to use the Developer version of Minecraft Console Client, and that I'd have to go into the configs and manually change the version. He then linked me here, and I completely blanked out (rather than bothering him further, I figured it'd be best to come and get some help here): https://ci.appveyor.com/project/ORelio/minecraft-console-client

I noticed on the minecraftforum.net post the 'Development Builds' download option, and went and downloaded that .exe file here:
https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

I do not know how to do any of this, as I'm not very experienced in this fileld. I was hoping I could get some assistance.

Thanks in advance.
- Abandon

**Comment by ORelio** [comment]
Hello,
Simply replace the exe from the release version (zip from forum thread) with the exe from development build and you'll have a development version supporting 1.9.4.

**Comment by Abandonnn** [comment]
Thank you - that seemed to have worked.

I had the chance to become a bit acquainted with using the correct values in the files in such-- it's way more simple than I thought initially.

Again, thanks for all the help!

Cheers, 
- Abandon
