### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by Tnavillacs** [ORelio/Minecraft-Console-Client#1550]
I copied my console client folder to another computer and this error appears when I'm trying to run any c# script.
![1169ca59e4de506d395a97af4f7e11af](https://user-images.githubusercontent.com/52362571/115887380-29c54600-a452-11eb-98b6-0499d7ad4580.png)

**Comment by ORelio** [comment]
`The system cannot find the path specified`
Somewhere your script tries to open a file that is no longer at the expected location. The bug seems to occur in your script.

**Comment by Tnavillacs** [comment]
> `The system cannot find the path specified`
> Somewhere your script tries to open a file that is no longer at the expected location. The bug seems to occur in your script.

No. It must be something else. I get that error with any script even if I removed all tasks with paths.

**Comment by ReinforceZwei** [comment]
Create a new folder, download a new copy to that folder and try again.

**Comment by ORelio** [comment]
Well, after a second look, for some reason you script fails to compile because the C# compiler cannot create its temporary directory. It seems indeed that the issue is outside your script... but also outside Minecraft Console Client.

**Comment by ORelio** [comment]
It seems you are using a path that is too long. Which means the C:\Path\To\Mcc\Directory is over 260 characters:
https://stackoverflow.com/questions/65499468/terraform-the-system-cannot-find-the-path-specified
You might be able to sort it out using a registry tweak, or just use a smaller path.
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by Tnavillacs** [comment]
> Create a new folder, download a new copy to that folder and try again.

Wow. Thanks. That actually worked!
