### ISSUE TITLE
Is it possible to somehow change the digging speed?

### ISSUE THREAD

**Issue by KJION** [ORelio/Minecraft-Console-Client#1551]
I play on a sky block where ores will spawn in a cobblestone generator.  There are picks with an efficiency of 6, but I'm wondering if it is possible to increase the digging speed?

**Comment by ReinforceZwei** [comment]
See https://github.com/ORelio/Minecraft-Console-Client/issues/1505#issuecomment-803407662

**Comment by KJION** [comment]
The fact is that a bot is digging for me on a dumb one, it tries to dig for air, etc.
