### ISSUE TITLE
How to log multiple alts at once wihtout needing to type every accounts login info seperate?

### ISSUE THREAD

**Issue by Heringen** [ORelio/Minecraft-Console-Client#1555]
[Title]

**Comment by ReinforceZwei** [comment]
You may create a batch file and write your account email and password to it if you are brave enough. See [wiki](https://github.com/ORelio/Minecraft-Console-Client/wiki), the bottom of the page, for example.

**Comment by Heringen** [comment]
> You may create a batch file and write your account email and password to it if you are brave enough. See [wiki](https://github.com/ORelio/Minecraft-Console-Client/wiki), the bottom of the page, for example.

i open CMD and type this
START /MIN MinecraftClient.exe example.ini  user1 pass1 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user2 pass2 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user3 pass3 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user4 pass4 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user5 pass5 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user6 pass6 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user7 pass7 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user8 pass8 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user9 pass9 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini  user10 pass10 pvp.daegonner.com
?

**Comment by ReinforceZwei** [comment]
1. Create a new text file.
2. Copy the above content and modify it as you need.
3. Click `Save as` button.
4. Select `any/all` as file type.
5. The file name must end with `.bat`
6. Double click on the file you have created.

**Comment by Heringen** [comment]
http://prntscr.com/121f7qq displays me this.
My file name indeed is MinecraftClient.exe

**Comment by Heringen** [comment]
Nvm solved it

**Comment by Heringen** [comment]
http://prntscr.com/121fpml it seems to enter wrong pass and stuff tho?

**Comment by ReinforceZwei** [comment]
If your email/password contains special characters, e.g. !$&?, use quote " to quote it.

**Comment by Heringen** [comment]
Quote just the special characters or whole email/password?

**Comment by ReinforceZwei** [comment]
Whole email/password. `MinecraftClient.exe "123@abc.com" "mypassword"`

**Comment by Heringen** [comment]
still broken

**Comment by Heringen** [comment]
Solved

**Comment by Heringen** [comment]
http://prntscr.com/1223047 This happens when i try to open 9 at once. Can i smhw make it retry to connect from this screen in a loop?

**Comment by ReinforceZwei** [comment]
Use `AutoRelog`. See https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot

**Comment by Heringen** [comment]
Firstly, thanks for help.
Secondly, i'm not too much into the MCC programming so i'd ask is it possible to:
START /MIN MinecraftClient.exe example.ini user1 pass1 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user2 pass2 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user3 pass3 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user4 pass4 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user5 pass5 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user6 pass6 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user7 pass7 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user8 pass8 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user9 pass9 pvp.daegonner.com
START /MIN MinecraftClient.exe example.ini user10 pass10 pvp.daegonner.com
Put some code that makes lets say first mcc open instantly, second one 10 sec layer 3rd once 10 sec later etc.. in format like
START /MIN MinecraftClient.exe example.ini user10 pass10 pvp.daegonner.com [delay command]?

**Comment by ReinforceZwei** [comment]
`REM` is just a line of comment. You may ignore it.
```bat
start client.exe ...

REM Use Ping command to create delay. Adjust the value after -w
PING 127.0.0.1 -n 1 -w 10 >NUL

start client.exe ...
PING 127.0.0.1 -n 1 -w 10 >NUL
start client.exe ...
PING 127.0.0.1 -n 1 -w 10 >NUL
REM And so on
```

**Comment by Heringen** [comment]
PING 127.0.0.1 -n 1 -w 10 >NUL
I always type 127.0.0.1 or i need to enter a specific ping?

**Comment by ReinforceZwei** [comment]
Always use 127.0.0.1

**Comment by Heringen** [comment]
START /MIN MinecraftClient.exe  */*/*
PING 127.0.0.1 -n 1 -w 100000 >NUL
START /MIN MinecraftClient.exe  */*/*
PING 127.0.0.1 -n 1 -w 100000 >NUL
They still all open in same time

**Comment by ReinforceZwei** [comment]
Sorry my bad. The timeout value should be after `-n`. So the correct delay command should be 
```bat
REM Delay 10 seconds
PING 127.0.0.1 -n 10 >NUL
```

**Comment by Heringen** [comment]
Yeah this does the trick, thanks again!
