### ISSUE TITLE
Not sure how to get script scheduler to work

### ISSUE THREAD

**Issue by HomeSellBackHome** [ORelio/Minecraft-Console-Client#1556]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

I want to log in to a server, and throughout the whole time I'm on the server I want it to run a few commands 
/home afk2 
/sell all
/home afk

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])

I can get the script to work with /script events.txt but doesn't seem task scheduler is doing anything to trigger this by itself.
currently trying with these 
triggerOnFirstLogin=true
triggerOnInterval=true
timeInterval=00:02
action=script event.txt

There's no sign that scheduler is even active through the console

---
## Solutions you've already considered

1. scheduler is set to true
2. debugger set to true

---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

**Comment by ORelio** [comment]
Post your config, set debugmessages=true and post console output. Redact session tokens and passwords before posting.
