### ISSUE TITLE
DiscordWebhook

### ISSUE THREAD

**Issue by n00b69** [ORelio/Minecraft-Console-Client#1557]
I may just be really stupid, but where in the script do I paste my webhook URL?

Also I have not figured out how to add a label to this post, my bad.

**Comment by ReinforceZwei** [comment]
The webhook URL is set using `/discordwebhook changeurl <your webhook url>` command. You may use `/dw` as command alias to replace `/discordwebhook`.

**Comment by EpicDude1238** [comment]
where do you enter the command for it, as doing that while logged into a server just gives an error msg from the server

**Comment by ReinforceZwei** [comment]
Have you loaded the ChatBot before entering the command? Download the script from github and place it with your `MinecraftClient.exe`, then execute `/script DiscordWebhook.cs`.

**Comment by EpicDude1238** [comment]
> Have you loaded the ChatBot before entering the command? Download the script from github and place it with your `MinecraftClient.exe`, then execute `/script DiscordWebhook.cs`.

where do i get the script?

**Comment by ReinforceZwei** [comment]
_Where you know MCC support DiscordWebhook when you don't even have that script?_

[DiscordWebhook.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/DiscordWebhook.cs)

**Comment by EpicDude1238** [comment]
i have the DiscordWebhook.cs in the folder with MinecraftClient.exe, i do \script DiscordWebhook.cs, it gives me this message, 
![Screenshot_27](https://user-images.githubusercontent.com/43878094/116253199-2ab6ea00-a768-11eb-8bfb-074f98aabb66.png) and when i try to do \discordwebhook changeurl, i get this:
![image](https://user-images.githubusercontent.com/43878094/116253302-43bf9b00-a768-11eb-83a6-b405e3078c03.png)

The items in the folder are: 
![Screenshot_26](https://user-images.githubusercontent.com/43878094/116253394-5a65f200-a768-11eb-90ee-6f1eae178a78.png)

**Comment by ReinforceZwei** [comment]
The script itself contains error and it has been fixed. Please download the script again from Github.

**Comment by ORelio** [comment]
Related commit: 7fd0f9157f9f248dca61167a848a7d4374903412

**Comment by n00b69** [comment]
Amazing, that fixed it. However, every time I boot up the console client, I need to change the Webhook url. Is there a workaround for this?

Also will a relay be added in the future? I've found old conversations of the EchoesNetwork where he posted some code, however it didn't work.

**Comment by n00b69** [comment]
Added: When running the webhook script, I seem to get disconnected after a while. The account remains ingame, but the client loses connection.

Also to clarify, with a relay I mean the ability to send messages from Discord straight into the game.

**Comment by ReinforceZwei** [comment]
For the first question, you might want to ask the script author, @Daenges 

For the second question, you will have to wait until someone made a script that does the job. See https://github.com/ORelio/Minecraft-Console-Client/issues/258#issuecomment-677631905

**Comment by n00b69** [comment]
> To your update: I am not able to recreate your bug. :/ Maybe reload the script?

So far, I have not been able to run any MCC commands without manually typing them myself. When I put a command like /move east as an AntiAFK measure in the MinecraftClient.ini file, it says it's an invalid command. The same applies to any other commands in scripts etc.|

I am going to try adding the WebhookURL right now. I will update this message when I succeed / fail.

**Comment by ReinforceZwei** [comment]
You don't need the leading `/` when using command in `MinecraftClient.ini` or in tasks file.

**Comment by n00b69** [comment]
[AntiAFK]
enabled=true
delay=1200 #10 = 1s
command=move east

If I write it like this, it sends it as a normal message.

[AntiAFK]
enabled=true
delay=1200 #10 = 1s
command=/move east

Tells me it's an invalid command

**Comment by n00b69** [comment]
> Just add:
> `WebhookURL = "Your URL";`
> To the constructor of the WebookSettings class -> `public WebhoookSettings()` and the bot should start with your url predefined.

How/where do I do that? The only files for the webhook that I have is the chatbot.cs and DiscordWebhook.cs

When I try to use commands through a simple event.txt file, I get the following results:

^send /command
Invalid command

^send command
It sends command as a message in chat

^send "/command"
It sends "/command" as a message in chat

^send "command"
It sends "command" as a message in chat

^/command
Nothing

**Comment by Daenges** [comment]
@n00b69 Since you raised this question, I am assuming that you are not familiar with Visual Studio or any other C# IDE. This is not a Problem, since you can open the DiscordWebhook.cs with basically anything. I used notepad++ as an example for you:
![Screenshot 2021-05-04 172437](https://user-images.githubusercontent.com/57369924/117044146-64f72d00-ad0e-11eb-9cfd-bc7149cac71a.png)
But you can also use the normal notepad, it does not matter.
Maybe you could also consider to auto trigger the command "/dw changeurl URL" on join. This would be an easier sollution than editing code without knowledge.

To your second question:
The "send" command sends everything you type after it to the server chat. For instance if you want to send /help to the server instead of the client. If you want to execute a command inside the client, just type "script load XY".

**Comment by n00b69** [comment]
I'm probably just really stupid, but;
• Adding the WebhookURL line into DiscordWebhook.cs does not do anything (by default, the line was not present)

I replaced chatbot.cs with a simple .txt file, which starts by launching DiscordWebhook.cs, then a 5 second wait, and then I want to send the "/dw changeurl URL" command, which so far has not been succesful.

>script DiscordWebhook.cs
wait 50
command /dw changeurl




No matter what I try and how I change it (by adding/removing "'s), it doesn't recognize it as a command.

**Comment by ReinforceZwei** [comment]
When you use command in script, use it directly. You don't need to prepend anything.
```
script DiscordWebhook
dw changeurl blablala
```

**Comment by ReinforceZwei** [comment]
> ![Screenshot 2021-05-04 172437](https://user-images.githubusercontent.com/57369924/117044146-64f72d00-ad0e-11eb-9cfd-bc7149cac71a.png)

@Daenges Would you mind adding the highlighted part in the screenshot to your script in the repo?

**Comment by Daenges** [comment]
@ReinforceZwei I made a PR with the line implemented.

@n00b69 You can find further examples for scripts here: https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config

**Comment by n00b69** [comment]
> When you use command in script, use it directly. You don't need to prepend anything.
> 
> ```
> script DiscordWebhook
> dw changeurl blablala
> ```

This solved my issue perfectly and it's all working fine now. A way to automate it by default would probably be nice for other people like me who aren't good at scirpting.
