### ISSUE TITLE
Console and Debugging-Possibilities

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1558]
I have two things I would like to recommend:
1. Allowing the MCC Console to be used in Fullscreen
2. Be able to log the last Minute of the console into a file via a command (for debugging and other similar reasons)

**Comment by ReinforceZwei** [comment]
> 1. Allowing the MCC Console to be used in Fullscreen

It depends on what console program you use to run MCC and it is not controllable by MCC.

> 2. Be able to log the last Minute of the console into a file

MCC already support log to file. Check out the following settings in your `MinecraftClient.ini` file.
https://github.com/ORelio/Minecraft-Console-Client/blob/7fd0f9157f9f248dca61167a848a7d4374903412/MinecraftClient/Resources/config/MinecraftClient.ini#L54-L56

**Comment by xXjojaXx** [comment]
@1 Ok, sry for bothering, does not seem to work in putty and windows cmd. Are there any applications you can recommend?
@2 Sry again, parts of our MinecraftClient.ini file seem to be very old, because it wasnt included, gonna fix that now. Is there any way to enable/disable the consolelog programmatically? Because my goal is to *output the Main part of the errors into the chat* while im debugging, so I considered making a chatbot to turn off and on my debugger mode via an internal command. Or are there any other ways to acquire new errors that get thrown by scripts?

**Comment by ReinforceZwei** [comment]
I guess you may want to take a look at the [current loggers](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/Logger) and implement a custom logger if you know C#.

For full-screen console, seems like pressing `alt+enter` can enter full-screen mode with Windows 10 cmd. I cannot test it for you as I am not using Windows 10.

**Comment by xXjojaXx** [comment]
Ok I'm used to c# quite well, but I don't have a clue of how to implement the custom logger if i finished it without recompilng the whole project. Also i didnt meant that the console isnt in fullscreen mode, I think i didnt explain it very well. Its just not used completly by MCC unlike other programms. It gets cuts off after some lines with a seperator line like this: - - - - - - - - - - - - - -

**Comment by ReinforceZwei** [comment]
> I think i didnt explain it very well

How about providing a screenshot?

> if i finished it without recompilng the whole project

It is recommended to use Visual Stdio 2017/2019 to write C# code. After you have finished implementing your logger, just press `F5` and Visual Stdio will compile and run the code for you.

**Comment by xXjojaXx** [comment]
Youre right a screenshot like this would have been very useful:
[space for future screenshot] 
I'm already using Visual Studio for my c# projects and know about compiling but I use MCC on a Linux Server without graphical interface etc. like many people do and its not a big deal to compile it once and upload it, but when updating to the next Version of MCC the custom implemented functions of the last version will be deleted. Any recommends? In my opinion it would be very neat if there would be an option to implement system fies (like an logger) outside of the exe itself to keep it safe and fast editable.

**Comment by ReinforceZwei** [comment]
> but when updating to the next Version of MCC the custom implemented functions of the last version will be deleted

Option 1 would be using git. Create a new branch and make your custom logger there. When there's new update on master branch, you can use `git rebase` command to "update" your own modified branch to the latest without losing your own code.

Option 2, which might be better in long-term, would be making a highly customizable logger that can be controlled/customized using external configuration file. We could merge your logger into MCC if it is well-made.

**Comment by xXjojaXx** [comment]
Thanks for correcting the typo, english isnt my first language :)

**Comment by xXjojaXx** [comment]
Looking into programming the custom logger but might take some time

**Comment by xXjojaXx** [comment]
I will close the issue for now, but its definetly something I will look forward to do in the future, I just don't really have time for such projects right now.
