### ISSUE TITLE
Properly disconnect from server when closing console

### ISSUE THREAD

**Issue by Heringen** [ORelio/Minecraft-Console-Client#1559]
Basically my alts stay online for several mintues after i turn off MCC. Anyone knows why or a fix?

**Comment by ObscenityIB** [comment]
are you exiting correctly or just killing the program

could be the servers timeout settings

**Comment by Heringen** [comment]
Right click on taskbar icon - close window.
Used to do the trick always instantly.

**Comment by ReinforceZwei** [comment]
> Right click on taskbar icon - close window.

You are killing the program. Use `/exit` command to close the client correctly.

**Comment by Heringen** [comment]
Oh okay

**Comment by ORelio** [comment]
Apparently there's a way to capture console close and perform cleanup in C#
https://stackoverflow.com/questions/474679/capture-console-exit-c-sharp
But meanwhile please properly disconnect using the Exit command 😉

**Comment by ReinforceZwei** [comment]
> Apparently there's a way to capture console close and perform cleanup in C#
> https://stackoverflow.com/questions/474679/capture-console-exit-c-sharp
> But meanwhile please properly disconnect using the Exit command

It works on Windows but doesn't work with mono.
![image](https://user-images.githubusercontent.com/39955851/116773731-cbb7e480-aa89-11eb-8d6f-04029c5d1128.png)

I found another solution that works on both. 
https://stackoverflow.com/a/929717
But somehow the terminating code will run twice on mono.
(Left: mono, right: Windows)
![image](https://user-images.githubusercontent.com/39955851/116773888-34539100-aa8b-11eb-8b95-3c4eed18b6a4.png)

**Comment by ReinforceZwei** [comment]
Worth to mention there is timeout for console closing event of 5000ms and no timeout for `ctrl+c`. ([MSDocs](https://docs.microsoft.com/en-us/windows/console/handlerroutine#timeouts))

Full example code:
```cs
using System;
using System.Runtime.InteropServices;
using System.Threading;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // Capture all close event
                SetConsoleCtrlHandler(delegate (CtrlType sig) 
                {
                    Console.WriteLine("Quit after 1 second: SetConsoleCtrlHandler");
                    Thread.Sleep(1000);
                    Console.WriteLine("I'm out of here");
                    // Must return false
                    return false; 
                }, true);
            }
            catch (DllNotFoundException)
            {
                // Probably on mono, fallback to ctrl+c only
                Console.CancelKeyPress += delegate (object sender, ConsoleCancelEventArgs e)
                {
                    Console.WriteLine("Quit after 1 second: Console.CancelKeyPress");
                    Thread.Sleep(1000);
                    Console.WriteLine("I'm out of here");
                };
            }

            int a = 0;
            while (true)
            {
                Console.WriteLine("Hi there, " + a);
                a++;
                Thread.Sleep(1000);
            }
        }

        [DllImport("Kernel32")]
        private static extern bool SetConsoleCtrlHandler(ConsoleCtrlHandler handler, bool add);
        private delegate bool ConsoleCtrlHandler(CtrlType sig);

        enum CtrlType
        {
            CTRL_C_EVENT = 0,
            CTRL_BREAK_EVENT = 1,
            CTRL_CLOSE_EVENT = 2,
            CTRL_LOGOFF_EVENT = 5,
            CTRL_SHUTDOWN_EVENT = 6
        }
    }
}
```

**Comment by ORelio** [comment]
Thanks for your research. I'd say to use the generic Ctrl+C handler, and if running on Windows, also set-up the ConsoleClose handler. I'll check out your pull request.

**Comment by ORelio** [comment]
Should be resolved as per @ReinforceZwei's contribution. @Heringen: Please try out the latest development build.
