### ISSUE TITLE
Is it possible to hold right click?

### ISSUE THREAD

**Issue by ImLostTbh** [ORelio/Minecraft-Console-Client#1563]
So I'm playing on a server where afk fish farms are allowed, but bots that fish for you are against the rules. So I'm wondering if there's a command to make MCC hold down the right click button so I can use it with a fish farm to automate it while not having to have the whole game open.

**Comment by ORelio** [comment]
If server rules forbid fishing bots, why would they allow automated fishing farms?
To answer your question, I'm not sure. There is no "right click" in Minecraft protocol, the game automatically chooses the correct action to perform. In your case, that could be "use item". You can ideed "use item" in a look, e.g. using a script.

**Comment by ImLostTbh** [comment]
Thanks, I've gotten the script to work, but I know almost nothing about coding/scripting, how would I make it so the script will repeat until I type a command to cancel it?

**Comment by ReinforceZwei** [comment]
> repeat until I type a command to cancel it?

This will require using the `ChatBot` API if you want to control the script by command.
Save the script with file name ended with `.cs`
```cs
//MCCScript 1.0
MCC.LoadBot(new UseRod());

//MCCScript Extensions
public class UseRod : ChatBot
{
    private bool enabled = false;
    public override void Initialize()
    {
        RegisterChatBotCommand("userod", "UseItem repeatly", "start, stop", CommandHandler);
        LogToConsole("Loaded");
    }

    public string CommandHandler(string cmd, string[] args)
    {
        if (args.Length >= 1)
        {
            switch (args[0])
            {
                case "start": enabled = true; break;
                case "stop": enabled = false; break;
            }
            return "Switched to " + args[0];
        }
        else
        {
            return "Current: " + (enabled ? "running" : "stopped") + ". Use /userod start|stop to switch";
        }
    }

    public override void Update()
    {
        if (enabled)
            UseItemInHand();
    }
}
```

Control the script with command,
![image](https://user-images.githubusercontent.com/39955851/116804684-43057b00-ab53-11eb-89af-874d6557eb61.png)
