### ISSUE TITLE
Can login without command /server?

### ISSUE THREAD

**Issue by okokmayconchonayok** [ORelio/Minecraft-Console-Client#1564]
I'm playing in a network can't join a server with command /server, i must login and click to choose server, so can i login without command /server? sorry my English not good ^^

**Comment by ReinforceZwei** [comment]
Use `/inventory` command to interact with inventory. Use `/inventory help` to see the usage of the command. Remember to enable inventory handling in your `MinecraftClient.ini` file.
https://github.com/ORelio/Minecraft-Console-Client/blob/0400ad89acf2aa3fad985ce45afbefda2d90db1d/MinecraftClient/Resources/config/MinecraftClient.ini#L31-L32

**Comment by okokmayconchonayok** [comment]
please give me a example, i try it but can't do it

**Comment by ReinforceZwei** [comment]
It would be better for us to help you if you could post a screenshot to show what have you done and why it didn't work.

**Comment by ORelio** [comment]
Looks very similar to #1574 so you might have a look there for guidance.

**Comment by MessengerRNA** [comment]
I am doing exactly what u said in #1574 and the client says that it clicked the block but my character didn't go anywhere in-game.

![](https://i.gyazo.com/384f071e484ea32a3cd28f5692e14b42.png)

**Comment by xXjojaXx** [comment]
Did you make sure that inventory 0 is the right one? Also are you aware that the inventory managment is 0-index-based, which means the first slot is called 0 the second 1 and so on... Also make sure again you are clicking the right block and inventory handling is enabled. Also is left clicking what you have to do? Would be nice if you would provide an screenshot of the inventory you want to use out of the real minecraft client too.

**Comment by MessengerRNA** [comment]
![image](https://user-images.githubusercontent.com/83925300/117614769-cbc57d80-b136-11eb-8de9-6649026ae762.png)
This is the compass that I need to click, I need to then click on the grass block

**Comment by Kevqn11** [comment]
First you need to do `/changeslot 5` then it should say "Inventory Opened". Then use the command `/inventory container click 13 left`. Here 13 is the number for the slot starting from 0 at top left and increasing from left to right.

**Comment by MessengerRNA** [comment]
I'm doing the exact commands you are telling me to use but the account is not being teleported to the game mode I'm trying to play on.

**Comment by ReinforceZwei** [comment]
Could you provide more details such as console output?

**Comment by MessengerRNA** [comment]
Never mind for some reason it works today but not yesterday lol. Thank you for the help!
