### ISSUE TITLE
Is there a way to relay in-game chat messages that contain specific keywords/substrings, via this console client?

### ISSUE THREAD

**Issue by darnItWhy** [ORelio/Minecraft-Console-Client#1565]
I have little to no coding experience, so I am not sure about how feasible this is to set up. I ideally want to have a discord ping each time a message is sent in-game (that includes a specific keyword). 

I can think of two ways to do this: 
1. Relay every single message to Discord, and have another Discord bot (some kind of automod) ping me when a keyword pops up
or, 
2. Only relay messages to Discord that contain the specific keyword. 

I think that method 2 is more ideal because it is not as affected by Discord webhook rate-limiting. However, if it is not possible, method 1 is also acceptable. Assuming I have exactly zero knowledge of how to start, how would I go about setting this up?

**Comment by ReinforceZwei** [comment]
To relay messages to Discord Webhook, take a look at this script: [DiscordWebhook.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/DiscordWebhook.cs)

To detect/filter messages, you may modify the above script and add your own regular expression to the `GetText()` method.
