### ISSUE TITLE
set var from mcc internal output | inventory or entity

### ISSUE THREAD

**Issue by Chtholly** [ORelio/Minecraft-Console-Client#1567]
Is it possible to set a var from a renamed item in inventory or  detect as entity ?
- using /inventory 0  and /entity there can found the item, but regex not detect this internal output from mcc

**Comment by ORelio** [comment]
[Item.cs] has a `DisplayName` property so if you write a ChatBot you should be able to process inventory items and act upon the custom item name. But you'd need to write a bit of code because no built-in ChatBot can do what you want.
