### ISSUE TITLE
Entity Handling

### ISSUE THREAD

**Issue by railroadss** [ORelio/Minecraft-Console-Client#1568]
Since there is no entity handling support for lower than 1.10 can you still track players coming nearby with packets such as what the replaymod uses

**Comment by ReinforceZwei** [comment]
No, you can't. In order to "track" entities, entity related packets must be read. `ReplayMod` feature only record the received packets but doesn't read them.

**Comment by ORelio** [comment]
Unfortunately you'll need to wait until someone works on #1523 (entity handling for older versions) but we can't provide an ETA because we don't have many active contributors to work on everything.
