### ISSUE TITLE
How do i enable it so i can pick up items.

### ISSUE THREAD

**Issue by Prap123** [ORelio/Minecraft-Console-Client#157]
Can i have some help i want to be able to make it so that the player would pick up items and then i want to make a script for the command /sell all every 30 seconds

**Comment by ORelio** [comment]
Hello,
Take a look at the [README](https://github.com/ORelio/Minecraft-Console-Client/blob/67fc431d4a053fa09f67e754224d9ba4850ef735/MinecraftClient/config/README.txt) file :
 - [Interacting with the Minecraft world](https://github.com/ORelio/Minecraft-Console-Client/blob/67fc431d4a053fa09f67e754224d9ba4850ef735/MinecraftClient/config/README.txt#L84) (includes picking up items)
- [Using the Script Scheduler](https://github.com/ORelio/Minecraft-Console-Client/blob/67fc431d4a053fa09f67e754224d9ba4850ef735/MinecraftClient/config/README.txt#L178)
NB: Terrain handling has not been ported to 1.9, yet.
