### ISSUE TITLE
AutoRespond to server messages

### ISSUE THREAD

**Issue by EpicDude1238** [ORelio/Minecraft-Console-Client#1572]
I am currently trying to get my client to automatically respond to the following server message, but it doesn't seem to detect it
![image](https://user-images.githubusercontent.com/43878094/117143894-3aa67d80-ada9-11eb-913c-4621d321f140.png)

Is there a specific format to add server messages to it?

**Comment by toni1506mc** [comment]
Maybe you can try to
add something like this to your matches.ini

[Match]
regex=^Please welcome ([a-zA-z0-9_]+) to Skyblock$
actionother=send Welcome $1

**Comment by ORelio** [comment]
There is none in AutoRespond but you can configure `messagecooldown` cooldown in `MinecraftClient.ini` - see #661

**Comment by ORelio** [comment]
Not currently.

**Comment by xXjojaXx** [comment]
Maybe u should consider to build an custom script which has implemented the cooldown like you want it around the message and start it via an regex in the matches.ini.

*Not tested* code:
`//MCCScript 1. 0
//Get cooldown-variable
int cooldown = 0;
try
{
	cooldown= MCC.GetVarAsInt("cooldown");
}
catch
{
	MCC. SetVar("cooldown", 0) ;
}

//Check if message should be sent
if(cooldown <= 2) //Replace 2 with the count of messages you want to be possible in the timespan set below (at the wait)
{ 
	//increase cooldown-variable by 1
	MCC.SetVar("cooldown", cooldown + 1);

	//Send Message
	MCC.SendText("Hello World"); //Your Message here

	//wait 1 second (or how long of an timespan you want between your messages) - May be replaced with an timer or something similar for Performance
	System.Threading.Thread.Sleep(1000); //in Milliseconds

	//decrease cooldown-variable by 1
	MCC.SetVar("cooldown", MCC.GetVar("cooldown" - 1)
}`
