### ISSUE TITLE
Invisible outputs

### ISSUE THREAD

**Issue by chriss59** [ORelio/Minecraft-Console-Client#1573]
All Internal Command outputs and Script outputs are invisible.
The Scripts are working fine.
I use the newest Minecraft-Console-Client Version with Debian 9.
I can copy the invisible output and paste it in a text file.
debugmessages are invisible too.
https://prnt.sc/12l2p50

**Comment by ReinforceZwei** [comment]
This is a known issue with putty color scheme. See #1260 for solution.

**Comment by chriss59** [comment]
@ReinforceZwei It's still invisible. It apparently changes both the text and the background color together

**Comment by ORelio** [comment]
Use a color scheme that properly displays dark gray.
Example: https://github.com/AlexAkulov/putty-color-themes/

[Monokai Dimmed](https://github.com/AlexAkulov/putty-color-themes/blob/master/28.%20Monokai%20Dimmed.reg) seems to properly display dark gray:

![28 monokai-dimmed](https://user-images.githubusercontent.com/1128206/117567352-41d8ce80-b0bc-11eb-8345-3f3f97062310.png)
