### ISSUE TITLE
Need help to join servers minigame. Thanks.

### ISSUE THREAD

**Issue by polermen** [ORelio/Minecraft-Console-Client#1574]
Hello! First of all thanks for making MCC, its really useful to chat and afk =) but i really need your help for simple thing, that i cant figure out. how can i join minigame on server (you need to use compas and click in menu to join, screens attached). Thank you if you can help =)

![3](https://user-images.githubusercontent.com/29254107/117468687-fd3b1f00-af65-11eb-81ee-2b9fc7fed25d.PNG)
![2](https://user-images.githubusercontent.com/29254107/117468693-fe6c4c00-af65-11eb-97cb-39ac0984247e.PNG)
![1](https://user-images.githubusercontent.com/29254107/117468729-07f5b400-af66-11eb-9997-0c4cbf76cb02.PNG)

**Comment by ReinforceZwei** [comment]
Enable inventory handling in your `MinecraftClient.ini` file first.
```ini
inventoryhandling=true            # Toggle inventory handling (beta)
```

***

To use the compass, run `/useitem` command. Make sure your selected hotbar is the compass. If not, change it with `/changeslot` command.

After the inventory is opened, use `/inventory container` command to see the slot ID of the item you want to click. Then use `/inventory container click <slotID>` to "click" the item.

**Comment by ORelio** [comment]
You need to edit the script to set the coordinates of the target block, then move in front of the block, then run the script with `/script nameofthefile.cs`
