### ISSUE TITLE
Extend command line arguments

### ISSUE THREAD

**Issue by APPxPY** [ORelio/Minecraft-Console-Client#1578]
Hello, I am faced with the problem that it is impossible to use more than one proxy if you run many clients and do not change MinecraftClient.ini. Is it possible to implement obtaining information about the proxy not only through the settings file but also through the command line arguments?

**Comment by APPxPY** [comment]
Yeah, I already running multiple clients with different proxies, but if you also will add proxy to command line arguments, running multiple instances at once will be more easier. Thank you!)

**Comment by ORelio** [comment]
The command-line enhancement has been implemented in the newest build.
You can now specify `--setting=value` for the main settings in INI file and `--section.setting=value` for other settings.
The README file contains further explanations: [Command-line usage](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#command-line-usage)
