### ISSUE TITLE
Add MC Version 1.9.4

### ISSUE THREAD

**Issue by Delivator** [ORelio/Minecraft-Console-Client#158]
Can you please add support for version Minecraft 1.9.4?

**Comment by Pokechu22** [comment]
The latest development build supports 1.9.3 and 1.9.4 (see the spoiler in the forum post).  [You should be able to download it here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by Delivator** [comment]
Thank you!
