### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by socus** [ORelio/Minecraft-Console-Client#1580]
![image](https://user-images.githubusercontent.com/55073027/117561677-bde7fd80-b04d-11eb-814a-e6093e7e9bef.png)

Is there a way to get the name above someones head?

**Comment by ORelio** [comment]
Are you looking for [`Entity.CustomName`](https://github.com/ORelio/Minecraft-Console-Client/blob/90505dbc4c9375dbbefb5992112c74ed6e2122e1/MinecraftClient/Mapping/Entity.cs#L40) or `/entity list`?

**Comment by socus** [comment]
So, when OnEntitySpawn is called with the entity, is there a way to get the name above the head? As of right now, I am only getting like random text hovering but the text above someones head.

**Comment by socus** [comment]
So yes, entity.custonname

**Comment by ORelio** [comment]
There is OnEntitySpawn and OnEntityMetadata, maybe the custom name is sent _after_ spawing the entity.
