### ISSUE TITLE
Is it possible to somehow make a trigger on the blocks and poke at them?

### ISSUE THREAD

**Issue by KJION** [ORelio/Minecraft-Console-Client#1589]
I play on a server where there are 14 sky blocks, between them there is one store and through it you can transfer resources from 1 Sky block to another. Is there any way to automate this using the console client?

**Comment by xXjojaXx** [comment]
Please describe further how this shop works or what the console client has to do to transfer between them. (For example if it is a gui, what slot he clicks on etc.)

**Comment by KJION** [comment]
I can't explain right now, there are 4 tabs. 1 tab - how the store works, 2 tab-buying something in this store, 3 tab - this is for sale and 4 tab - this is to pick up the product from the store that you bought or passed the day and the product returned. Server IP : mc.prostocraft.ru (as I will be at home, I will try to describe in more detail)
