### ISSUE TITLE
Upgrade to 1.10

### ISSUE THREAD

**Issue by Cat7373** [ORelio/Minecraft-Console-Client#159]
[minecraft_server_1.10.jar](http://s3.amazonaws.com/Minecraft.Download/versions/1.10/minecraft_server.1.10.jar)
http://wiki.vg/Pre-release_protocol
https://github.com/Cat7373/server_diff/blob/master/network.patch

**Comment by ORelio** [comment]
Oh, in packets handled by MCC they only changed resource pack status updates.
Now implemented and tested working on vanilla 1.10 server with custom server resource pack :)
