### ISSUE TITLE
Delete items

### ISSUE THREAD

**Issue by xXjojaXx** [ORelio/Minecraft-Console-Client#1590]
Is it pissible to delete items in the creative inventory, like a normal player can do? If yes, how? If not, can it be implemented?
Thanks. xXjojaXx

**Comment by ORelio** [comment]
Currently, only "creative give" is implemented. Converting your question to enhancement request.

**Comment by xXjojaXx** [comment]
Looking forward to the time it is implemented!

**Comment by ReinforceZwei** [comment]
You can actually delete an item from inventory using the following command: (creative mode only)
`/inventory creativegive <slotid> null 0`

A command shortcut might be added in the future.

**Comment by ORelio** [comment]
> `/inventory creativegive <slotid> null 0`

Clever! 👏

**Comment by xXjojaXx** [comment]
Nice, never thought of that!

**Comment by ORelio** [comment]
Added a proper `creativedelete` command for this.

**Comment by xXjojaXx** [comment]
Can I use it to delete Items directly out of opened Inventorys in a chatbot too?

**Comment by ORelio** [comment]
The  `creativedelete` command justs calls the `creativegive` API with the arguments stated by @ReinforceZwei

**Comment by ORelio** [comment]
Just added `CreativeDelete(int slot)` in ChatBot API as alias for `CreativeGive(slot, ItemType.Null, 0, null)`.
