### ISSUE TITLE
How to use premade chatbots

### ISSUE THREAD

**Issue by ImLostTbh** [ORelio/Minecraft-Console-Client#1594]
So I've been looking a little into some of the chatbots that you can use with this program, however I'm absolutely atrocious at coding and scripting. I found some useful bots (for example the AntiAFK chatbot) in the ChatBots folder: (Minecraft-Console-Client-master\MinecraftClient\ChatBots), but I've got absolutely no clue how to use them... Any help would be appreciated!

**Comment by ReinforceZwei** [comment]
The Chatbots you found are built-in bot, which means you can enable them in your `MinecraftClient.ini` file.

**Comment by ImLostTbh** [comment]
Alright, works great thanks!
