### ISSUE TITLE
Useitem for tools does not work

### ISSUE THREAD

**Issue by LarsNijhuis** [ORelio/Minecraft-Console-Client#1596]
Hello I have been testing today. My goal is for my console client to automatically use a sell wand on a chest every 5 seconds.I have not managed to use tools it does not work with /useitem. Also /useblock x y z does not work for tools. Placing blocks with /useblock and using food with /useitem do work.  So my question is, is there a /usetool or something to do this?

**Comment by ReinforceZwei** [comment]
The `/useblock` command should do the trick. Make sure the block coordinate is where your chest at and you have enabled `terrainandmovement` in your `MinecraftClient.ini` file.

**Comment by LarsNijhuis** [comment]
Wow it works! Thank you so much! Thank you so much for your help!

**Comment by LarsNijhuis** [comment]
Another question, is there any way to render a frame. because you get a captcha every so often. I need 1 frame to solve that one. Is there a possibility for that?

**Comment by ReinforceZwei** [comment]
Sorry I don't understand what you mean by frame.

**Comment by LarsNijhuis** [comment]
Let me explain, sometimes after clicking on a chest so many times you get a captcha (https://imgur.com/a/l0uTLss). Then you have to type the 5 symbols in the chat. Only without picture I can't do that. Is there a possibility that the console client can make a frame or screenshot or something so that I know which symbols they are.

**Comment by ReinforceZwei** [comment]
No, it is not possible. MCC is a console application and it can't display image.

**Comment by LarsNijhuis** [comment]
Okay, no problem
