### ISSUE TITLE
Inventory Handling problem

### ISSUE THREAD

**Issue by Heringen** [ORelio/Minecraft-Console-Client#1600]
So im trying to make inventory handling enabled but it won't work ([MCC] Please enable InventoryHandling in the config file first.)

I tried putting inventoryhandling=true/inventoryhandling=enabled under both main and mc settings, and tried adding seperate column with 
[InventoryHandling]
enabled=true
But noone seems to work.
How and where should i type it? Thanks in advance!

Warm regards.

**Comment by ReinforceZwei** [comment]
Inventory handling only support Minecraft version 1.10 and afterward.

**Comment by ORelio** [comment]
As stated by @ReinforceZwei, inventory handling will not work for older Minecraft versions, but a message in console should tell you that inventory handling is not supported for your server's version. Possible duplicate of #929

**Comment by Heringen** [comment]
Oh okay.
Will it work for older version somwhere in future?

**Comment by ORelio** [comment]
Cannot provide an ETA but there is a feature request open here: #929

**Comment by Heringen** [comment]
Aight, ty for clarification!
