### ISSUE TITLE
DiscordWebHook: Handle multi-word strings

### ISSUE THREAD

**Issue by BlexMC** [ORelio/Minecraft-Console-Client#1601]
Hello,
as I'm running the client on a server, the alert sound does not really help me. So I thought adding maybe other ways to be notified when there has been a specific word used may be helpful.

**Comment by ORelio** [comment]
What kind of ways are you thinking of?
Please note that MCC is cross-platform so some ways may or may not work depending on your operating system.

**Comment by BlexMC** [comment]
That's the problem - I'm kinda uncreative and don't know what's possible.. :/

**Comment by xXjojaXx** [comment]
I think this is just about what you really want to achive, should an potential alert be ti which platform and what medium should it use? (For example: If you are using Linux and think it would be practical to link it to Email or as an push message on your smartphone). What I mean by this is that you have to describe your needs or functions you would appreciate if someone should help you.

**Comment by BlexMC** [comment]
Ah okay, I see. Yeah, the E-Mail and push notification on your smarthphone seems like a good idea. Another thing I though of was being notified via Discord (maybe with the help of webhooks?).

**Comment by xXjojaXx** [comment]
There is already a function to pass messages to Discord via an Webhook, you might want to have a look at Minecraft-Console-Client/MinecraftClient/config/ChatBots/DiscordWebhook.cs in the Cide section. Theres an implemented Chatbot that might fit your needs.

**Comment by BlexMC** [comment]
Oh yeah, didn't knew this exists. But for some reason, it wont allow me to use "dw ping message add..." in my scripts. "Exit" for example works.

**Comment by ORelio** [comment]
If you put `"word1 word2"` the bot will ping you only if the message contains `word1 world2`.
If you want `word1` _or_ `word2` then add them separately
```
dw ping message add "word1" "@here"
dw ping message add "word2" "@here"
```

**Comment by BlexMC** [comment]
Yeah, but that's what I want - I want that it only pings me, when someone sends a message containing exactly this two words. But, however, when I write in into my script, it wont work. When doing so, not even the "normal" pings work (the ones with only one word).
Here's an example:

```
dw ping message add "word1 word2" "@here"
dw ping message add "word3" "@here"
```
Neither the 1st and 2nd one works. Means, it wont ping me when someone says "Hello word1 word2" & "wonderful word3".

```
dw ping message add "word1" "@here"
dw ping message add "word2" "@here"
dw ping message add "word3" "@here"
```

Works.

**Comment by ORelio** [comment]
@Daenges Any idea why @BlexMC 's ping would not work? Mentioning you as the author of the DiscordWebhook chatbot

**Comment by Daenges** [comment]
The Discord ping system is a bit tricky.
``"@here"`` and ``"@everyone"`` work as supposed.

[Here](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) is the Discord support page on how to obtain different IDs.

If you want to ping a user you need to enter:

``"<@DiscordUserID>"`` 

To ping a role you need to type:

``"<@&ROLEID>"``

There is also a channel ping, for whatever reason:

``<@CHANNELID>``

You need to enter the whole syntax in the ping field, including the IDs.
(e. g. ``/dw ping message add "SampleText" "<@684309756589074816>"``)

**Comment by Daenges** [comment]
Ohhh.. seems like I found the bug with multiple words ;D

```
            msg = new string(msg.Where(c => !char.IsPunctuation(c)).ToArray());

            foreach (string word in msg.Split(' '))
            {
                if (settings.GetMessageContains().ContainsKey(word.ToLower())) { pings += string.Join(" ", settings.GetMessageContains()[word.ToLower()]); }
            }
```
Here I check whether the message contains a word, that should trigger a ping. I go through the message word by word, which breaks the thing if you take two words. This should be fixed by iterating all keys in `settings.GetMessageContains()` and checking whether the message contains them. I add a fix for this to the PR.

**Comment by ORelio** [comment]
The bug should be resolved now. Thanks @Daenges for stepping in! 👍
@BlexMC Please try it out and let us know if your issue is not resolved
