### ISSUE TITLE
How can I make support for the Russian language with the console via the "send" command?

### ISSUE THREAD

**Issue by KJION** [ORelio/Minecraft-Console-Client#1602]
How can I make support for the Russian language with the console via the "send" command?

**Comment by ORelio** [comment]
Not sure what the "send" command has to do here, but you can translate the app to Russian by creating your own translation file and sending it to us. Translation files are here: [lang](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/Resources/lang).

**Comment by KJION** [comment]
The fact is that the client is completely translated into Russian, but if you make a script and you need to write something to the chat, then the place of Russian letters will be question marks

**Comment by ORelio** [comment]
> The fact is that the client is completely translated into Russian

It's not. Therefore, your are using a fork: a modified version of Minecraft Console Client, or a repackaged version with a custom translation file. Anyway, that should not matter for your question:

> but if you make a script and you need to write something to the chat, then the place of Russian letters will be question marks

Make sure your script file is encoded as UTF-8.

**Comment by CrazyFoxxx** [comment]
@KJION Как я понимаю, ты ставишь твинков на VPS/VDS. Установи на него русский языковый пакет, и всё станет на свои места.
Лично мне помогло
