### ISSUE TITLE
Suggestion or not about skin's second layers

### ISSUE THREAD

**Issue by TNTUP** [ORelio/Minecraft-Console-Client#161]
Hi, I guess i've already said that before on MCF, loading my account or (s), having their second skin layer visible, before 1.8, in 1.7.10 I was able to see their helmet, but since 1.8.x and later no helmet nor their chestplate, arms, legs visible. 

I've enabled terrainandmovement, thought it would enable their second skin layer, it doesn't. Is it quite possible or not? If not possible, feel free to close this issue^^

**Comment by ORelio** [comment]
That's probably because [Client Settings](http://wiki.vg/Protocol#Client_Settings) is not sent. Not related to terrain and movements.

**Comment by TNTUP** [comment]
That's possible to see this implemented or not?^^

**Comment by ORelio** [comment]
It is possible. That would require some setting entries for... enabling settings or not.
Also that's one more packet to update in case of changes in the protocol :p

**Comment by TNTUP** [comment]
Oh, hm well if you can^^ Was an idea^^ x)

**Comment by ORelio** [comment]
You'd be the main (only?) one using that I think, so feel free to point me to the way that suits you the best.

**Comment by TNTUP** [comment]
Well, I don't want to force you to add a feature which I'd be the only one will use it, I guess it can give some interest to some people^^

**Comment by ORelio** [comment]
The "Client Settings" feature is now implemented, allowing to customize several settings, all sent to server.
This mainly includes skin layers, other settings are no-so-useful or ignored by server.
