### ISSUE TITLE
How I can use move command in script (now Unexpected symbol MCC error)

### ISSUE THREAD

**Issue by Timtaran** [ORelio/Minecraft-Console-Client#1616]
How i can cycled this commands?
```
/move north
/move south
/move west
/move east
```

**Comment by Timtaran** [comment]
If I use `MCC.SendText("/move east");` I have `Unknown command. Type "/help" for help.`

**Comment by toni1506mc** [comment]
For Internal Commands use MCC.PerformInternalCommand

**Comment by Timtaran** [comment]
I have new error `[MCC] [Script] Script 'script.cs' failed to run (LoadError). [MCC] [Script] System.InvalidOperationException: Unexpected symbol `MCC'`
Code:
```//MCCScript 1.0

while (1<2)
{
MCC.PerformInternalCommand("move north")
MCC.PerformInternalCommand("wait 1")
MCC.PerformInternalCommand("move south")
MCC.PerformInternalCommand("wait 1")
MCC.PerformInternalCommand("move west")
MCC.PerformInternalCommand("wait 1")
MCC.PerformInternalCommand("move east")
MCC.PerformInternalCommand("wait 1")
}```

**Comment by toni1506mc** [comment]
> I have new error `[MCC] [Script] Script 'script.cs' failed to run (LoadError). [MCC] [Script] System.InvalidOperationException: Unexpected symbol `MCC'`
> Code:
> 
> ```
> 
> while (1<2)
> {
> MCC.PerformInternalCommand("move north")
> MCC.PerformInternalCommand("wait 1")
> MCC.PerformInternalCommand("move south")
> MCC.PerformInternalCommand("wait 1")
> MCC.PerformInternalCommand("move west")
> MCC.PerformInternalCommand("wait 1")
> MCC.PerformInternalCommand("move east")
> MCC.PerformInternalCommand("wait 1")
> }```
> ```


```
//MCCScript 1.0

MCC.PerformInternalCommand("move north");
System.Threading.Thread.Sleep(15);
MCC.PerformInternalCommand("move south");
System.Threading.Thread.Sleep(15);
MCC.PerformInternalCommand("move west");
System.Threading.Thread.Sleep(15);
MCC.PerformInternalCommand("move east");
System.Threading.Thread.Sleep(15);
```

You could try that

**Comment by Timtaran** [comment]
> > I have new error `[MCC] [Script] Script 'script.cs' failed to run (LoadError). [MCC] [Script] System.InvalidOperationException: Unexpected symbol `MCC'`
> > Code:
> > ```
> > 
> > while (1<2)
> > {
> > MCC.PerformInternalCommand("move north")
> > MCC.PerformInternalCommand("wait 1")
> > MCC.PerformInternalCommand("move south")
> > MCC.PerformInternalCommand("wait 1")
> > MCC.PerformInternalCommand("move west")
> > MCC.PerformInternalCommand("wait 1")
> > MCC.PerformInternalCommand("move east")
> > MCC.PerformInternalCommand("wait 1")
> > }```
> > ```
> 
> ```
> //MCCScript 1.0
> 
> MCC.PerformInternalCommand("move north");
> System.Threading.Thread.Sleep(15);
> MCC.PerformInternalCommand("move south");
> System.Threading.Thread.Sleep(15);
> MCC.PerformInternalCommand("move west");
> System.Threading.Thread.Sleep(15);
> MCC.PerformInternalCommand("move east");
> System.Threading.Thread.Sleep(15);
> ```
> 
> You could try that

why script use only one command

**Comment by Timtaran** [comment]
I fixed it with recoursion... 
```
//MCCScript 1.0

MCC.PerformInternalCommand("move north");
System.Threading.Thread.Sleep(1);
MCC.PerformInternalCommand("move south");
System.Threading.Thread.Sleep(1);
MCC.PerformInternalCommand("move west");
System.Threading.Thread.Sleep(1);
MCC.PerformInternalCommand("move east");
System.Threading.Thread.Sleep(1);
MCC.PerformInternalCommand("script script.cs");
```

**Comment by ORelio** [comment]
Hi, for your information, for such a simple script, you do not need to code in C#:

**script.txt**
```
move north
wait 10
move south
wait 10
move west
wait 10
move east
wait 10
script script.txt
```

Or you can omit the last line and schedule your script on a regular basis using ScriptScheduler.
