### ISSUE TITLE
Delete Mail.cs from config/Chatbots/

### ISSUE THREAD

**Issue by Daenges** [ORelio/Minecraft-Console-Client#1618]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Just a small reminder, that [this file](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/Mail.cs) can be deleted safely, since it was only a test, that did not work out and now wastes unnecessary disk space. :)

**Comment by ReinforceZwei** [comment]
I think it would be better you open a new PR deleting the file.

**Comment by Daenges** [comment]
Okay, then I open a PR!

**Comment by ORelio** [comment]
Resolved in #1619
