### ISSUE TITLE
Support for Special Characters in chat

### ISSUE THREAD

**Issue by Chalwk77** [ORelio/Minecraft-Console-Client#162]
Are you able to add support for character encoding? (Unicode)

My server's rank prefixes use special characters that are replaced with a **?** in the Console Client.

**Comment by ORelio** [comment]
Unicode ils already handled by MCC.
However, the Windows cmd console does not.

**Comment by Chalwk77** [comment]
Using a better console application? How exactly do I do that?

Could you provide a link to some references on how to do this?

**Comment by ORelio** [comment]
Windows 10 ships with a better console. You can also use [Cmder](http://cmder.net/).

**Comment by ORelio** [comment]
Answer to this issue should have been provided, feel free to reopen if needed.
