### ISSUE TITLE
AutoRespond bug

### ISSUE THREAD

**Issue by CrazyFoxxx** [ORelio/Minecraft-Console-Client#1620]
Hello. I am using AutoRespond to define messages and send text to chat, but that doesn't work. MCC sees that the player has sent a message, but does not send text to the chat.
![Screenshot_13](https://user-images.githubusercontent.com/71690715/120684066-f8a35100-c4a6-11eb-84fe-26e2846eb789.png)
![Screenshot_14](https://user-images.githubusercontent.com/71690715/120684083-fc36d800-c4a6-11eb-9492-895ef866137d.png)

**Comment by ORelio** [comment]
Your messages are not detected to be chat messages. See [detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages) for more info on how to fix it.

**Comment by CrazyFoxxx** [comment]
> Hey,
> 
> the problem is that actionother responds to every message thats not machting the public regex.
> If you can provide a screenshot i could help with the regex.
> 
> (sorry for my bad english)

![Screenshot_15](https://user-images.githubusercontent.com/71690715/120707026-7a54a800-c4c2-11eb-8e71-31de9e24a8da.png)
Russian language :D

**Comment by ORelio** [comment]
As y cannot type (nor read) russian, could you provide a text version of this and tell me what is the dark gray part and green part?
You should be able to get a text version by using the log bot, reading your logs inside .minecraft folder, or just copy paste from your console.

**Comment by CrazyFoxxx** [comment]
dark gray - Игрок
green - Хакер
🙂

**Comment by toni1506mc** [comment]
> > As y cannot type (nor read) russian, could you provide a text version of this and tell me what is the dark gray part and green part?
> > You should be able to get a text version by using the log bot, reading your logs inside .minecraft folder, or just copy paste from your console.
> > If you provide that, @toni1506mc (or myself) could help with the regex 🙂
> 
> dark gray - Игрок
> green - Хакер
> [L]Игрок PhoenixMC Хакер ➠ message
> dark gray is a prefix and green is a suffix

^\[L\].* ([a-zA-Z_]+) .* ➠ ([a-zA-Z_]+)$

https://regex101.com/r/FND7iD/1

**Comment by ORelio** [comment]
Thanks @toni1506mc for helping out 👍
Just a quick warning, beware of `.*` as it takes as much as possible, and thus can take more that you'd expect:

![image](https://user-images.githubusercontent.com/1128206/120713695-8f313b80-c4c2-11eb-8d2d-e5e1ca0ec86e.png)

An evil user could spoof another message as due to `.*` the regex would take the wrong username and message.
For this reason I'd suggest `[^ ]+` for prefix/suffix and keep `.*` only at the end of the regex, for the contents of the message:

![image](https://user-images.githubusercontent.com/1128206/120714203-344c1400-c4c3-11eb-9611-3ab1f4c2d163.png)

```
^\[L\][^ ]+ ([a-zA-Z_]+) [^ ]+ ➠ (.*)$
```

https://regex101.com/r/FND7iD/2

**Comment by toni1506mc** [comment]
> Thanks @toni1506mc for helping out 👍
> Just a quick warning, beware of `.*` as it takes as much as possible, and thus can take more that you'd expect:
> 
> ![image](https://user-images.githubusercontent.com/1128206/120713695-8f313b80-c4c2-11eb-8d2d-e5e1ca0ec86e.png)
> 
> An evil user could spoof another message as due to `.*` the regex would take the wrong username and message.
> For this reason I'd suggest `[^ ]+` for prefix/suffix and keep `.*` only at the end of the regex, for the contents of the message:
> 
> ![image](https://user-images.githubusercontent.com/1128206/120714203-344c1400-c4c3-11eb-9611-3ab1f4c2d163.png)
> 
> ```
> ^\[L\][^ ]+ ([a-zA-Z_]+) [^ ]+ ➠ (.*)$
> ```
> 
> https://regex101.com/r/FND7iD/2

ok thanks for the tip @ORelio 
We dont use .* instead we use (RangA|RangB)

**Comment by CrazyFoxxx** [comment]
Unfortunately this doesn't work
Or am I doing something wrong :c
![image](https://user-images.githubusercontent.com/71690715/120715184-ea682b80-c4cc-11eb-9b7e-984a86cfb9b7.png)

**Comment by ORelio** [comment]
Try replacing `➠` with `.` and/or making sure your config file is encoded as UTF-8.

**Comment by toni1506mc** [comment]
> Unfortunately this doesn't work
> Or am I doing something wrong :c
> ![image](https://user-images.githubusercontent.com/71690715/120715184-ea682b80-c4cc-11eb-9b7e-984a86cfb9b7.png)
> ![Screenshot_16](https://user-images.githubusercontent.com/71690715/120715548-66627380-c4cd-11eb-80f8-516a23d2c2e4.png)


The regex was missing 0-9 for numbers in the player name

`^\[L\][^ ]+ ([a-zA-Z0-9_]+) [^ ]+ ➠ (.*)$`
https://regex101.com/r/FND7iD/4

or

https://regex101.com/r/FND7iD/5 (ignores ➠)
`^\[L\][^ ]+ ([a-zA-Z0-9_]+) [^ ]+ . (.*)$`

**Comment by CrazyFoxxx** [comment]
> > Unfortunately this doesn't work
> > Or am I doing something wrong :c
> > ![image](https://user-images.githubusercontent.com/71690715/120715184-ea682b80-c4cc-11eb-9b7e-984a86cfb9b7.png)
> > ![Screenshot_16](https://user-images.githubusercontent.com/71690715/120715548-66627380-c4cd-11eb-80f8-516a23d2c2e4.png)
> 
> The regex was missing 0-9 for numbers in the player name
> 
> `^\[L\][^ ]+ ([a-zA-Z0-9_]+) [^ ]+ ➠ (.*)$`
> https://regex101.com/r/FND7iD/4
> 
> or
> 
> https://regex101.com/r/FND7iD/5 (ignores ➠)
> `^\[L\][^ ]+ ([a-zA-Z0-9_]+) [^ ]+ . (.*)$`

Thank you! It finally works! @ORelio @toni1506mc <3 <3 <3
