### ISSUE TITLE
1.7.10 More support

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1624]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

---
## Describe your problem
Present a concise description of the problem to be addressed by this feature request. 

There is no Inventory and Entity Processing

---
## Suggest a possible solution
A clear description of what you want to happen (I'd like the app to do this to solve my problem [...])

![image](https://user-images.githubusercontent.com/35975332/120893931-2b785100-c62f-11eb-8209-4a546ac71c57.png)
I tried to organize the digging myself but the package system is different from 1.8
---
## Screenshot to help explain your request (If applicable)

**Comment by ORelio** [comment]
Hi Nekiplay, there are other open issues for that:
#929  Inventory handling for older Minecraft versions
#1523 Entity handling for older Minecraft versions
Also for your information the history of wiki.vg/Protocol is available directly on the site itself:
https://wiki.vg/index.php?title=Protocol&offset=&limit=500&action=history

**Comment by Nekiplay** [comment]
As soon as I have more free time I will try to implement something

**Comment by ORelio** [comment]
Thanks, any help is appreciated!
I'll close this issue in favour of the two others.
