### ISSUE TITLE
Failed to connect to localhost

### ISSUE THREAD

**Issue by Ixogamer** [ORelio/Minecraft-Console-Client#1626]
**Prerequisites**
 - [Y] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [Y] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [Y] I have set `debugmessages=true` in config to diagnose my issue
 - [ ] I have redacted session tokens and passwords before attaching screenshots

---
## Expected Behavior
I type "localhost" "127.0.0.1" and I can connect to the server

---
## Actual Behavior
![image](https://user-images.githubusercontent.com/68835899/121265096-85d81280-c8b8-11eb-886b-cf8cc7866dc7.png)

---
## Steps to Reproduce the Problem

  1. Login to localhost
  2. Doesn't work

---
## Screenshot (If applicable)
![image](https://user-images.githubusercontent.com/68835899/121265126-94262e80-c8b8-11eb-9e7a-931077dd878f.png)

---
## Anythings that could help diagnosing the bug
https://gist.github.com/655646211eee92d6b563a301de2868b0 config

---
## Specifications

Device: Windows
Server: Localhost
Plugins: BetterBowTrails*, BlockParticles, ConsoleSpamFix, PixelMOTD*, PlayerParticles, PlugMan, ProtocolLib, Skript, Vault
(Could be caused by PixelMOTD)
Version: 1.16.5

**Comment by Ixogamer** [comment]
I removed the PixelMOTD plugin, now it works.
![image](https://user-images.githubusercontent.com/68835899/121265322-eb2c0380-c8b8-11eb-828c-6d2c108c67db.png)
Weird. Sorry.

**Comment by ORelio** [comment]
Hi,
In your screenshot, the protocol version is set to `-1` so ping will not work as expected because MCC cannot detect the server version. You can bypass the ping by setting `mcversion=1.X.X` (exact version to use) and `mcforce=false` (or `true` but not `auto`).

**Comment by ORelio** [comment]
Also fixed the underlying bug in above commit, thanks for reporting. You'll still need to manually specify the server version.
