### ISSUE TITLE
Need help Texture Verification

### ISSUE THREAD

**Issue by TeacVern** [ORelio/Minecraft-Console-Client#1628]
How to accept tex verification console ? Please help me :(( ?

**Comment by TeacVern** [comment]
> How to accept tex verification console ? Please help me :(( ?

Server rescue pack how to enable

**Comment by TeacVern** [comment]
> I do not know, whether I am understanding your question correctly. Is your question:
> "How to accept a server ressourcepack, so that it is also recognized by the server as installed on the client?"

Yes exactly it is, sorry for my bad english

**Comment by ORelio** [comment]
Hi,
As shown in this block of code, the client will automatically accept texture packs:
https://github.com/ORelio/Minecraft-Console-Client/blob/39b7d878dd3cc29fc0179346cd4edea62168428c/MinecraftClient/Protocol/Handlers/Protocol18.cs#L849-L863

**Comment by TeacVern** [comment]
> Hi,
> As shown in this block of code, the client will automatically accept texture packs:
> https://github.com/ORelio/Minecraft-Console-Client/blob/39b7d878dd3cc29fc0179346cd4edea62168428c/MinecraftClient/Protocol/Handlers/Protocol18.cs#L849-L863
> 
> 
> Are you having trouble connecting to a server?

No no :) 

Is there a way to use the files we download exactly youtune ?

**Comment by ORelio** [comment]
I'm not sure I understood your question. However I googled for you a YouTube video for obtaining server resource pack:
https://www.youtube.com/watch?v=Dtt63a-a-A0
