### ISSUE TITLE
Can't get Mailer to work/add.

### ISSUE THREAD

**Issue by periskil** [ORelio/Minecraft-Console-Client#1633]
Hello, I am trying to add the Mailer chatbot to my MCC, and for some reason I can't even get /mailer as a command in the client. So far I have tried adding the Mailer.cs file straight into my MCC folder, and I have also tried creating a seperate ChatBots folder and putting it in there, and neither have worked for me. Any help would be appreciated, and any info I can give to help feel free to ask for, there is just nothing specific I feel I could actually report.

**Comment by ReinforceZwei** [comment]
To enable mailer bot, edit your `MinecraftClient.ini`, find `[Mailer]` section and set `enabled` to `true`.

**Comment by periskil** [comment]
Ah, thought I had already set it to true which is what confused me. Sorry for the obsolete question then, didn't realized I had missed that
