### ISSUE TITLE
Translated the en.ini file into Russian

### ISSUE THREAD

**Issue by iwixw** [ORelio/Minecraft-Console-Client#1635]
I translated the file into Russian (MinecraftClient\Resources \lang)

File:
https://gist.github.com/iwixw/d8aa9741800eeeafd70f3ca68de65621
Can you add it?

**Comment by ReinforceZwei** [comment]
Hi, thanks for your contribution. Before adding your work to the repository, here's little feedback for you:

https://gist.github.com/iwixw/d8aa9741800eeeafd70f3ca68de65621#file-ru-ini-L55
The text encapsulated in `[]` are `.ini` file section name and you do not need to translate them.

Please let me know when you are finished.

**Comment by iwixw** [comment]
I finished, if I understood correctly what needed to be changed

**Comment by ReinforceZwei** [comment]
Your work have been added to the repository. Thanks again!
