### ISSUE TITLE
Can I go to connect server that uses its own launcher?

### ISSUE THREAD

**Issue by iwixw** [ORelio/Minecraft-Console-Client#1636]
The server I want to go to uses its own launcher for the game. That is, you cannot enter it from ordinary minecraft, but only from their launcher. Сan do this somehow through Minecraft Console Cient?

**Comment by ORelio** [comment]
Hi,
The only thing I could suggest to try is discovering the server IP and trying to input that into MCC.
See https://github.com/ORelio/Minecraft-Console-Client/issues/51#issuecomment-61053851

**Comment by iwixw** [comment]
Server 50/50 consists of a launcher, that is, some mini-games can be accessed from their launcher, and some can be accessed from the usual

**Comment by ORelio** [comment]
I think you won't be able to bypass that unless reverse engineering the launcher and making a custom MCC build designed to pass the check and join your server with a custom launcher. Quite some work 😄

**Comment by iwixw** [comment]
Quite difficult and not clear :D

**Comment by ORelio** [comment]
I'll close the issue as answered (answer is No, unless you'll willing to develop a custom MCC build) 😉
