### ISSUE TITLE
Implement flying when allowed by server (/fly, creative mode)

### ISSUE THREAD

**Issue by KJION** [ORelio/Minecraft-Console-Client#1638]
When the bot starts digging and flying, it is thrown into the hub.
The fact is that I play on a server where there is a sky block and there you can buy a flight, and there, when you put a bot with a flight, it throws it into the hub almost instantly.
(Sorry for my English. This is google translate)
![lcAhLr1Gh44](https://user-images.githubusercontent.com/72937972/122308158-83a73100-cf14-11eb-8d44-614489ed570f.jpg)

**Comment by ORelio** [comment]
Hi,
Flying is not handled actually, so I'll convert your question into a feature request.
When the player has the ability to fly, MCC would need to take it into account and stop trying to handle gravity.
Related: #1508

**Comment by KJION** [comment]
Can't somehow turn off the fly without a command that should be on the server itself?

**Comment by ORelio** [comment]
@KJION Not currently, that's the topic of #1508
