### ISSUE TITLE
How made simple script

### ISSUE THREAD

**Issue by iwixw** [ORelio/Minecraft-Console-Client#1639]
How can you make a simple script that will send commands:
/useitem
/inventory (n) click (n)
/inventory (n) click (n)
/sneak
 Take turns

N - Any digit

**Comment by iwixw** [comment]
I saw a simple script called sample-script.txt in the config, but it sends the name of the message, and I need commands like the ones I listed above.
![image](https://user-images.githubusercontent.com/84740733/122351916-b0346a80-cf5f-11eb-93fd-986a72422be6.png)

**Comment by ReinforceZwei** [comment]
You don't need the leading slash in script. Just remove them.
```
useitem
inventory (n) click (n)
inventory (n) click (n)
sneak
```

**Comment by iwixw** [comment]
Hmm, really. Thanks for the help.
