### ISSUE TITLE
Jumping

### ISSUE THREAD

**Issue by dan7em** [ORelio/Minecraft-Console-Client#164]
Hi ORelio,

It would really help my bots if you could implement jumping as a part of terrainandmovement. Do you think it's possible?

**Comment by ORelio** [comment]
Just /move up and you'll jump :p

**Comment by dan7em** [comment]
Oh cool! Last time I checked (the 1.9.0 version), it didn't work. I'm happy now, thanks! 😉

**Comment by ORelio** [comment]
You can thank @Pokechu22 for his work on updating terrain and movements for 1.9+ :)
