### ISSUE TITLE
What is a regex? How does it work?

### ISSUE THREAD

**Issue by Netherite2** [ORelio/Minecraft-Console-Client#1640]
how do i make a regex?, how does it work?, what is a regex?

**Comment by xXjojaXx** [comment]
A regex or in long "regular expression" is a pattern of characters to describe if and how an string/text should be processed. In general a regex has to functionalitys: Describing if a string matches the pattern and if it does the regex outputs defined groups for processing. The symbols ^ and $ are often used to describe the start and end of an regex. 
For example the regex
Abcd
Matches to the text
Abcd
But not to
Efgh
which in MCC means if you use the regex for reacting to chat messages, that it will trigger the action when someone writes Abcd in the chat.

Important to know are the following symbols/technics:
- If you put an . in an regex he will match to any character
- If you put charactes in this brackets [] it means that the character at this place in the text will match if it is included in the characterlist in the brackets. This also means u could use:
- [a-zA-Z] to match every letter
- [0-9] to match every one digit number
- [aGpq] to match the character a G p or q

-if you use a plus it repeats the pattern right before itself, which means:
-[0-9]+ will match to every number, for example 837362
-[a-z]+ will match to every text only containing lowercase letters

The * symbol will have the same effect as the + but accepts spaces. This lets u use the dollowing combinations:
. + matches to a whole word or line of chracters like "hello123" but not "hello 123"

. * matches to nearly everything, for example to "Hello, i think 1+1 is 2!"

If you surround somwthing with this brackets () it will be outputted as a group. For example the regex "([0-9]+) fruits are in the [a-zA-Z0-9_]" will match to both "12 fruits are in the kitchen" and "4 fruits are in the garden" and will output the groups "12" and "kitchen" for the first sentence and "4" and "garden" for the second one.

To react to symbols that usually wouls be interpreted in the regex like a . or a + u have to put an backslash in front of it, which means the regex "1+1" wont work but the regex "1\+1" would match the input "1+1"

Also there are hundreds more of symbols and functionalitys that are important, but these are the most important ones. A good website to start testing and making your regex's is regex101.com

Tips:
[a-zA-Z0-9_]+ will match every Minecraft Name. 
Putting (?i) before and after a regex will make it ignore capitalizing
If the rest of a sentence isn't important, but it should match if you write something behind, just put .* at the end of your regex
Google is your best friend of you dont understand something and also feel free to ask at any time.

**Comment by ORelio** [comment]
Thanks @xXjojaXx for your explanations, added a link to here inside the README file 🥇
