### ISSUE TITLE
Switch language

### ISSUE THREAD

**Issue by iwixw** [ORelio/Minecraft-Console-Client#1643]
I read the file "Readme" but it is not clear how to change the language. I recently created a translation file  RU.ini But I don't understand how to install it in MMC

**Comment by Ccode-lang** [comment]
Go to MinecraftConsole.ini and change the language setting

**Comment by Ccode-lang** [comment]
This only works if you put RU.ini in languages though.

**Comment by Ccode-lang** [comment]
Sorry that is wrong.  It says on the main page of the repo.

**Comment by ReinforceZwei** [comment]
There should be a folder call `lang` in your MCC folder. Inside the `lang` folder there's a more folder call `mcc`. Put your translation file in the `mcc` folder.

**Comment by iwixw** [comment]
> В вашей папке MCC должен быть вызов папки`lang`. Внутри `lang`папки есть еще один вызов папки `mcc`. Поместите ваш файл перевода в `mcc`папку.

iwixw\MinecraftClient\lang\mmc and there file ru.ini?

**Comment by ReinforceZwei** [comment]
Not `mmc` but `mcc`. You have to put your `ru.ini` file to `mcc` folder.

**Comment by iwixw** [comment]
Oh, sorry for the typo. thanks I got it
