### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by PrivateServersGANG** [ORelio/Minecraft-Console-Client#1645]
**Prerequisites**
 - [Y ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ Y] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ Y] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

How would i setup a task ive looked at the sample

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])
currently i have 
[Task]
triggerOnLogin=true
triggerOnInterval=true
timeInterval=300

respawn
send /joinqueue survival
send /home
respawn
wont work

---
## Solutions you've already considered

1. Set [...] setting in my config
2.

---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

**Comment by iwixw** [comment]
Create a file with the extension script.txt in the folder with MinecraftClient.exe
The content of the file should be:

respawn
send /joinqueue survival
send /home
respawn

Go to the server and write /script script.txt

**Comment by PrivateServersGANG** [comment]
Wip it auto run tho? @iwixw

**Comment by PrivateServersGANG** [comment]
Will*

**Comment by ORelio** [comment]
Hi,

Your tasks file cannot contain an inline script. You need a separate file for that.

**tasks.ini**
```ini
[Task]
triggerOnLogin=true
triggerOnInterval=true
timeInterval=300
action=script script.txt
```

**script.txt**
```
respawn
send /joinqueue survival
send /home
respawn
wont work
```

**Comment by PrivateServersGANG** [comment]
thanks uuu
