### ISSUE TITLE
How do i get my script to trigger on an alert?

### ISSUE THREAD

**Issue by HarryGK** [ORelio/Minecraft-Console-Client#1646]
I am making a script for a server that automatically does something in the inventory, i have everything figured out as far as it clicking all the correct places, but im looking to complicate things and have the script trigger on an alert, how would i do that?

[Autominer.txt](https://github.com/ORelio/Minecraft-Console-Client/files/6687489/Autominer.txt)

**Comment by ORelio** [comment]
Use [AutoRespond](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorespond-feature) to trigger your script.

**Comment by HarryGK** [comment]
> 
> 
> Use [AutoRespond](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorespond-feature) to trigger your script.

It doesnt seem to be working, i have the trigger set to the join message on the server

[Match]
match=ArtGuru has joined the server!
action=script Autominer.txt

the script works perfectly fine through /script, and alert is noticing the the chat message but auto respond isnt doing anything
