### ISSUE TITLE
bot won't move in nether

### ISSUE THREAD

**Issue by Rabkaleta** [ORelio/Minecraft-Console-Client#1648]
i create a warp in nether, when the bots are go to warp they doesn't move

**Comment by Rabkaleta** [comment]
![2021-06-22_03 21 56](https://user-images.githubusercontent.com/84437677/122823094-2393fe80-d309-11eb-84fe-db6004794577.png)
it said it move but not move

**Comment by Rabkaleta** [comment]
Failed to compute path to {cord}

**Comment by ORelio** [comment]
I see blocks that may not be implemented correctly in pathfinding due to not being configured as solid in MCC
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Material.cs
This looks similar to #1632
