### ISSUE TITLE
Auto responder- sent by server

### ISSUE THREAD

**Issue by HarryGK** [ORelio/Minecraft-Console-Client#1650]
The auto respond thing doesnt seem to be working,  i have the trigger set to the join message on the server , sent by the server

[Match]
match=ArtGuru has joined the server!
action=script Autominer.txt

the script works perfectly fine through /script, and alert is noticing the the chat message but auto respond isnt doing anything

**Comment by Daenges** [comment]
Why do you open a new issue for the same question as in #1646 ? Please consider closing one of them.

**Comment by HarryGK** [comment]
> 
> 
> Why do you open a new issue for the same question as in #1646 ? Please consider closing one of them.

deleted the last one as this one is more relevant, i wasnt sure if the other would work as it was marked as resolved

**Comment by Daenges** [comment]
@HarryGK I am not sure whether I understood you question. But here is some help:

If you want to send a message after join, use the `[ScriptScheduler]` (line 126 in the config.)
[Here](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini) are some examples for possible triggers.

Here is a working version, that first sends "hi" after a join and then it activates a script.

```
[Task]
triggerOnLogin=true
action=send hi

[Task]
triggerOnLogin=true
action=script DiscordWebhook.cs
```

**Comment by HarryGK** [comment]
> 
> 
> @HarryGK I am not sure whether I understood you question. But here is some help:
> 
> If you want to send a message after join, use the `[ScriptScheduler]` (line 126 in the config.)
> [Here](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini) are some examples for possible triggers.
> 
> Here is a working version, that first sends "hi" after a join and then it activates a script.
> 
> ```
> [Task]
> triggerOnLogin=true
> action=send hi
> 
> [Task]
> triggerOnLogin=true
> action=script DiscordWebhook.cs
> ```

that works when im joining initially, but when the server restarts, it kicks us to the hub, after the restart itll rejoin the subserver, would it recognize that and start the script?

**Comment by Daenges** [comment]
Hmm.. I am not sure, but I do not think it would do so.

**Comment by HarryGK** [comment]
> 
> 
> Hmm.. I am not sure, but I do not think it would do so.

yeah, thats why i was trying to use alerts, cause that notices the chat message

**Comment by Daenges** [comment]
So your issue is, that the matches are not detecting the correct message?

**Comment by HarryGK** [comment]
no, the matches are detecting the message, the issue is that i dont know how to make the alert trigger the script
alert works perfectly fine

**Comment by ORelio** [comment]
For messages that are not chat messages, you are looking for `actionother` instead of `action`.

**Comment by HarryGK** [comment]
> 
> 
> For messages that are not chat messages, you are looking for `actionother` instead of `action`.
> 
> ```ini
> [Match]
> match=server is restarting
> actionother=script restart
> ```
> 
> Source : [sample-matches.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini)

its not triggering the script

task-
[Task]
triggerOnlogin=true
actionother=script autominer.txt
script-

send /server atlantic5
wait 10
send /mine
wait 5
changeslot 1
wait 3
useitem
wait 3
inventory 1 click 25
wait 3
inventory 2 click 11

**Comment by HarryGK** [comment]
oh wait
thats match

**Comment by HarryGK** [comment]
It has worked, thank you for the help

**Comment by ORelio** [comment]
Don't forget to put ` match=ArtGuru has joined the server!` or any other text you want.
