### ISSUE TITLE
time SIMPLE

### ISSUE THREAD

**Issue by PrivateServersGANG** [ORelio/Minecraft-Console-Client#1653]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

for the timeInterval=18000 in tasks is it seconds or ticks?

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])

---
## Solutions you've already considered

1. Set [...] setting in my config
2.

---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

**Comment by ReinforceZwei** [comment]
In seconds.
https://github.com/ORelio/Minecraft-Console-Client/blob/c0f128f6327242acf4d3e91bc9ed2b3a5288c814/MinecraftClient/config/sample-tasks.ini#L36-L42
