### ISSUE TITLE
Custom 'Server version' support for `showinventorylayout`, `terrainandmovements` , `inventoryhandling`, `entityhandling` ?

### ISSUE THREAD

**Issue by Bobu5** [ORelio/Minecraft-Console-Client#1664]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue

---
**Issue Description**

MCC doesnt recognize the version that the server is running on, and giving the console this error
![image](https://user-images.githubusercontent.com/87025837/124622205-1b10fb80-dea5-11eb-9d35-4395becc0a40.png)

the error only occur on that one server that had custom Version name (i assume thats because the custom version doesnt have a Version number like 1.16.5)

heres a screenshot of the MCC running fine on my plain Paper server
![image](https://user-images.githubusercontent.com/87025837/124622537-662b0e80-dea5-11eb-937a-71122e680075.png)

i've made sure that `showinventorylayout`, `terrainandmovements` , `inventoryhandling`, `entityhandling` is on `true` while trying to enable the option on the first server 
![image](https://user-images.githubusercontent.com/87025837/124623137-e9e4fb00-dea5-11eb-9fef-82eb2c5e3cbf.png)
 

Note: this is my first time submitting an Issue , sorry if i posted the issue on the wrong category

**Comment by Daenges** [comment]
Is the server, where terrain handling fails also running on 1.16.5? I think terrain handling is only working for 1.8 - 1.16.5. If the server runs 1.17, terrain handling is not supportet yet.

**Comment by ReinforceZwei** [comment]
Set `mcversion=1.16.5` in your `MinecraftClient.ini`.

**Comment by Bobu5** [comment]
ah thx Daenges and ReinforceZwei for the answer, didnt know that there was an option for `mcversion` , also is there anyway to see the other option that are not listed in the .ini file just like the `mcversion`?

**Comment by Daenges** [comment]
What do you mean by "see"? You can just open the .ini file with any text editor and read through it. Most things are commented.
The manual to the bot can be found [here](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#minecraft-console-client-user-manual)

**Comment by Bobu5** [comment]
aah i see..., thx for the reply, i guess all of my question is answered now, imma close this issue, Thx!
