### ISSUE TITLE
Custom Command

### ISSUE THREAD

**Issue by PrivateServersGANG** [ORelio/Minecraft-Console-Client#1665]
**Prerequisites**
 - [ ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

How do i make a custom command , i need it to be like if i send /collectb it runs a script

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])

^^^

---
## Solutions you've already considered

1. Set [...] setting in my config
2.

---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

**Comment by Daenges** [comment]
You could do this by creating a C# script and registering a new command.
But it would be easier to just run a script with "/script [filename]" than creating a seperate command for it.
If you need event triggered execution I would recomment to read through "tasks" and "autorespond" [here](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config).

**Comment by PrivateServersGANG** [comment]
Yeah sorry i forgot to mention i figured it out, thanks tho
