### ISSUE TITLE
Connecting a Multiplayer 1.17 Server with Resource pack Enabled.

### ISSUE THREAD

**Issue by UniqueNIHAL** [ORelio/Minecraft-Console-Client#1667]
On the latest MCC , when joining a Server it gives an Alert/Error Error enable resource pack in Edit.

**Comment by ReinforceZwei** [comment]
Please provide screenshots showing the error.

**Comment by UniqueNIHAL** [comment]
> Please provide screenshots showing the error.

![image](https://user-images.githubusercontent.com/87065344/124732397-cb781180-df30-11eb-9a21-a5b56992f7f2.png)

Having this issue since I Redownloaded MCC for 1.17. Didn't have any issue before , same server. But the server updated to 1.17 with a new resource pack tho!

**Comment by UniqueNIHAL** [comment]
MCC has been a life saver for my AFK needs , and do Really love it btw!
Anyway is there a support discord btw?

**Comment by UniqueNIHAL** [comment]
So is there a way to enable that?

**Comment by ReinforceZwei** [comment]
Hi, a fix attempt was made. Please download the latest version and try again.

**Comment by UniqueNIHAL** [comment]
> Hi, a fix attempt was made. Please download the latest version and try again.

Ty will try!

**Comment by UniqueNIHAL** [comment]
I don't think it worked still get the same error ):

**Comment by UniqueNIHAL** [comment]
It worked before when I was in 1 .16.4 on the server server btw
Like the MCC accepted the resource pack

**Comment by ReinforceZwei** [comment]
MCC will accept all resource pack as shown in the code below and it haven't been changed.
https://github.com/ORelio/Minecraft-Console-Client/blob/581095e03e789609e6f0e718f2887ca0ff95d46f/MinecraftClient/Protocol/Handlers/Protocol18.cs#L869-L870

**Comment by ReinforceZwei** [comment]
Could you provide the server address so that I can try to reproduce the problem on my machine?

**Comment by UniqueNIHAL** [comment]
Yes "play.craftadia.com" 1.17.1

**Comment by UniqueNIHAL** [comment]
Hey the server did an Update and it fixed it , Tysm for helping and guiding me also a side note MCC IS THE BEST <3

**Comment by UniqueNIHAL** [comment]
NVM the server did another reboot and it broke again .-.

**Comment by UniqueNIHAL** [comment]
Not working w ith any resource pack servers ):

**Comment by ReinforceZwei** [comment]
As I was mentioned above, MCC will not send accept resource pack if the hash length not equal to 40. For the reason please see issue #1056
![image](https://user-images.githubusercontent.com/39955851/125161220-a810c900-e1b3-11eb-92e2-30b1cd62f4c9.png)

It should be fixed in https://github.com/ORelio/Minecraft-Console-Client/commit/982f358bf37b69ac1d99887887d71fe86226a2fb . Please download the latest version and try again.

**Comment by ORelio** [comment]
How is this fix compatible with #1056?

**Comment by UniqueNIHAL** [comment]
This fixed this tysm ReinforceZwei

**Comment by ReinforceZwei** [comment]
> How is this fix compatible with #1056?

I checked the evil plugin source code and saw the url wasn't start with `http` while normal server resource pack should have a http URL. So it is compatible with #1056

**Comment by ORelio** [comment]
> I checked the evil plugin source code and saw the url wasn't start with http

That's right. Good job! 😄
