### ISSUE TITLE
How can I change the webhook icon

### ISSUE THREAD

**Issue by Fr-gs** [ORelio/Minecraft-Console-Client#1668]
It's a short question
![image](https://user-images.githubusercontent.com/73062425/124802605-70f2ab80-df58-11eb-938c-55548805dacf.png)
How can I change the icon and name of the default server webhook?

I'm using this script https://github.com/ORelio/Minecraft-Console-Client/blob/b9935ab8fa2d23e81090d475cfe884fcfd0891c2/MinecraftClient/config/ChatBots/DiscordWebhook.cs

Edit: Messed around with stuff now I know how to change it

**Comment by AbdobiZark** [comment]
can you help me how do you change it?

**Comment by ORelio** [comment]
It's hardcoded here:
https://github.com/ORelio/Minecraft-Console-Client/blob/b9935ab8fa2d23e81090d475cfe884fcfd0891c2/MinecraftClient/config/ChatBots/DiscordWebhook.cs#L448
https://github.com/ORelio/Minecraft-Console-Client/blob/b9935ab8fa2d23e81090d475cfe884fcfd0891c2/MinecraftClient/config/ChatBots/DiscordWebhook.cs#L457
