### ISSUE TITLE
When will 1.17.1 be seen?

### ISSUE THREAD

**Issue by Atchbo2001** [ORelio/Minecraft-Console-Client#1669]
**Prerequisites**
 - [ x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

1.17.1 not supported and i cant for the life of me update this myself

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])

---
## Solutions you've already considered

1. Set [...] setting in my config
2.

---
## Screenshots to help explain your situation (If applicable)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)

**Comment by ReinforceZwei** [comment]
Thanks for your issue. 1.17.1 is supported now.
