### ISSUE TITLE
How do i setup a multiple botowner with file ? [example: botowner.txt]

### ISSUE THREAD

**Issue by Bobu5** [ORelio/Minecraft-Console-Client#1673]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
Need a help with setting up multiple bot owner using seperate botowner.txt file

---
## Describe your current situation
im playing in a minecraft server where we who have ranks can do /nick, i mostly change my nick to lets say originalname, name1,name2 and name3 

---
## Solutions you've already considered

1. using `botowners=originalname, name1, name2, name3`
![image](https://user-images.githubusercontent.com/87025837/124970027-a0391380-e051-11eb-8ac0-60a03763d7e2.png)

2. using a txt file with all of my name in it 
 ![image](https://user-images.githubusercontent.com/87025837/124969862-6962fd80-e051-11eb-833f-56803d56b734.png)
![image](https://user-images.githubusercontent.com/87025837/124969813-5b14e180-e051-11eb-8284-142c74130fb2.png)

those 2 way i tried both sitll didnt make the bot recognize me as a bot owner
![image](https://user-images.githubusercontent.com/87025837/124970324-fad26f80-e051-11eb-9848-a78930a9ed1f.png)

im pretty sure im missing some prefix and suffix for the file name, but cant find it in the config and the sample configs file

i appreciate any respond

**Comment by Daenges** [comment]
So, first you can leave ``name1-name3`` out, these are just placeholders.
It should be enough if you just ``enter your name``, ``safe the file`` and ``restart the client``.
Another possibility is, that the client is unable to detect this private message format. ( Although as far as I know this chat format should be supported. )

**Comment by Bobu5** [comment]
hi Daenges thx for the reply, yes i can confirm that it does work with 1 owner, but this way , i cant make it detect multiple botowner,  and about the private message format, yea i also can confirm that the client accept the private message format
![image](https://user-images.githubusercontent.com/87025837/125150169-f8fad000-e167-11eb-9b07-088cadf7dd4e.png)
![image](https://user-images.githubusercontent.com/87025837/125149967-7b829000-e166-11eb-8d49-6c5d5b2eac6e.png)

and for the txt file , it is on the same directory as the executable, sorry that i forgot to put the image when i created the question
![image](https://user-images.githubusercontent.com/87025837/125150148-bf29c980-e167-11eb-981b-4a3aec02815e.png)

**Comment by ReinforceZwei** [comment]
I saw there is a space in front of the botowner name (`name1, name2, ...`). Please remove the space and try again.

**Comment by Bobu5** [comment]
> I saw there is a space in front of the botowner name (`name1, name2, ...`). Please remove the space and try again.

thx for the reply, can confirm that this works, anyway is there anyway to add multiple line to the chat filter? do i just do it the same like im using multiple botowners rn or can i just use a txt file?

**Comment by Daenges** [comment]
What do you mean with chat filters?
Do you want to work with the task and matches of the client? So message triggered script execution?

**Comment by Bobu5** [comment]
im trying to filter an automated text that are coming from the server to the client, like the 'vote bla bla bla' and 'dont forget to subscrive to this channel!' , you get the point

**Comment by Daenges** [comment]
And what do you want to do with them? Execute a script if they show up?

**Comment by ReinforceZwei** [comment]
https://github.com/ORelio/Minecraft-Console-Client/blob/982f358bf37b69ac1d99887887d71fe86226a2fb/MinecraftClient/Resources/config/MinecraftClient.ini#L52-L53

You have to write your own Regular Expression.
For example,
![image](https://user-images.githubusercontent.com/39955851/125162196-1e63fa00-e1b9-11eb-99ef-d8e5603997ec.png)
You may use `|` to separate multiple text. If your text contains `*$&`, these characters has their meaning in Regular Expression and you have to add `\` in front of them. (`\*\$\&`)

**Comment by Bobu5** [comment]
ah thx for the reply imma give it a try and give u an update on it

**Comment by Bobu5** [comment]
> And what do you want to do with them? Execute a script if they show up?

yeah, the server autorestart like at 2AM or something , sometime its late sometime its sooner, i want to not only block a unwanted message, but also auto rejoin the subserver after 5 minute if the server restarted

**Comment by Bobu5** [comment]
sorry not sending update in a long time, i have very little to use the pc in like the last few days, anyway ive tested the bot, seems like it does works, thx for the reply and help, Bobu5 signing out
