### ISSUE TITLE
can't move through water

### ISSUE THREAD

**Issue by pp0236** [ORelio/Minecraft-Console-Client#1680]
help?
![image](https://user-images.githubusercontent.com/54238880/125232080-1d8cae80-e306-11eb-9dea-8ff4cd015de1.png)

**Comment by ReinforceZwei** [comment]
MCC doesn't handle water physics.

**Comment by ORelio** [comment]
MCC cowardly refuses to go in water as it does not handle swimming 😄

**Comment by pp0236** [comment]
ok
