### ISSUE TITLE
Added new option for AntiAFK

### ISSUE THREAD

**Issue by Mcstudio-technik** [ORelio/Minecraft-Console-Client#1681]
Hi, would it be possible to add to the Anti AFK system, the ability to call a script, not just a command?

**Comment by ReinforceZwei** [comment]
You can call a script using `script` command. For example, `script myscript.txt`.

**Comment by Mcstudio-technik** [comment]
anti afk sends the command, but the script does not respond
https://ibb.co/dPMJmyn

**Comment by ORelio** [comment]
Use [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler--task-scheduler) instead.
```ini
[Task]
triggerOnInterval=true
timeInterval=30
action=script send.txt
```
