### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Luukkk1** [ORelio/Minecraft-Console-Client#1686]
Im not very good in this sort of things, i downloaded the console client and all i managed to get the cobblestone miner but now it doesn't work. i edited the coords of the cobble but i won't mine?

**Comment by Daenges** [comment]
Did you enable terrain handling in the .ini file of the client?

**Comment by Luukkk1** [comment]
yh i did, i got it working. I didn't have any knowdledge of this type of things and i made it work lol.

**Comment by Daenges** [comment]
If it works, remember to close the issue. ;D

**Comment by Luukkk1** [comment]
sorry for the large amount of questions, after i got the oreminer working i wanted the cobblestoneminer to. After i tried this and set it up i got this error: 
![image](https://user-images.githubusercontent.com/87428326/125653331-c12f3cf9-2394-4c13-9ccf-4286815c616d.png)

**Comment by Ccode-lang** [comment]
It's a load error so try restarting client.

**Comment by Luukkk1** [comment]
it's a error because i added multiple lines, i wanted to mine more cobble than one block, because with an eff V pick you can mine 2 blocks before the first one respawns

**Comment by Luukkk1** [comment]
![image](https://user-images.githubusercontent.com/87428326/125655368-7ad048ab-851a-4f6c-b479-d8aa92198b7a.png)
I know this isn't correct but idk how i add multiple blocks of cobble

**Comment by Luukkk1** [comment]
i also figured out this
