### ISSUE TITLE
How do I change the client to accept my Microsoft login details?

### ISSUE THREAD

**Issue by YTPSDanDie** [ORelio/Minecraft-Console-Client#1687]
**Prerequisites**
 - [-] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [-] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [-] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
How do I change the client to accept my Microsoft login details?
Console Client I am using doesn't accept Microsoft login as a premium account.

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])
A clear description of what you want to happen (I'd like the app to do [...])
I have just purchased Minecraft Java as a new account the login details are a Microsoft account login.
I have used ORelio Minecraft-Console-Client previous version "Minecraft Console Client v1.12.2 DEV"
I can't seem to log in to the account as it is Microsoft.

---
## Solutions you've already considered

1. Looked through .ini file for an indication where I can change to "Microsoft"
2. Looked through all the files to see if I can change the login from "minecraft.net" to Microsoft login.

---
## Screenshots to help explain your situation (If applicable)
https://prnt.sc/1b3rnqj

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)
I have a server and computer that I run the console clients and has worked perfectly until now.

**Comment by ORelio** [comment]
Change this line in `MinecrafClient.ini` from `mojang` to `microsoft`:
https://github.com/ORelio/Minecraft-Console-Client/blob/f16e9e87dd82381514d5ea11300d88b4d47dfd25/MinecraftClient/Resources/config/MinecraftClient.ini#L12

**Comment by YTPSDanDie** [comment]
> Change this line in `MinecrafClient.ini` from `mojang` to `microsoft`:
> 
> https://github.com/ORelio/Minecraft-Console-Client/blob/f16e9e87dd82381514d5ea11300d88b4d47dfd25/MinecraftClient/Resources/config/MinecraftClient.ini#L12

Thank you!
