### ISSUE TITLE
Stopping a script

### ISSUE THREAD

**Issue by WolfgamingWG** [ORelio/Minecraft-Console-Client#1688]
Is there any way to stop a script that is repeating forever other than re-opening the full client or editing the script?

Example: a command like /stopscript to stop any script that is active.

If this isn't a thing please add it since it should be a thing!!

**Comment by Daenges** [comment]
So there is a function to unload C# scripts ( UnloadBot(); ), which can be called to stop the script.
I do not think that something similar exists for .txt scripts, but I might be wrong.

**Comment by Daenges** [comment]
@WolfgamingWG Okay, I found a workaround for your issue!
You can create a value in the [AppVars] section in the .ini file of the client:
```
[AppVars]
sendMessages=SampleScript.txt
```
Then you create a self calling script like here #1684 and name it after the value of your variable created above ( "SampleScript.txt" ).
Now you replace the script call with your variable:
```
send Hello!
// Wait 300 seconds (5 minutes)
wait 300
script %sendMessages%
```
If you now want to stop this script, you just need to enter `/set sendMessages=RandomStuff`.
This changes the AppVar and therefore the self calling script generates an error due not finding the provided value, which breaks the circle. To start the script again, change the Variable back to the scriptname with `/set sendMessages=SampleScript.txt` and call the script again with `/script SampleScript.txt`.

**Comment by WolfgamingWG** [comment]
I tried making the system suggested with the [AppVars] in the .ini and surprisingly it worked great! Never thought of that being an option.

Thank you for the help, issue is closed!
