### ISSUE TITLE
Move one block before executing any command

### ISSUE THREAD

**Issue by hp2309** [ORelio/Minecraft-Console-Client#1689]
The server i play on is a Survival server,
I use the bot to AFK my farms.

When i log into the server, and execute the "/afk-kick:notafk" command to prevent getting kicked, the server says,:
"Move atleast 1 block before executing any command"

Due to this, i can't use "/move up" etc.
I tried making an afkpool to push bot by water, but that didn't work, even after enabling terrainandmovements (it is supported for my version)
I also tried movement by Pistons with Observers and string, and also tried movement by riding a minecart. None worked.

Help will we really appreciated. =)

**Comment by ReinforceZwei** [comment]
After enabling `terrainandmovements`, you may use `/move` command to move the client player.

**Comment by hp2309** [comment]
I think the server expects a different player movement info, not similar to /move up (as move is a minecraft command not an MCC command)

This is the commandline looks like.
1. For loging in and connecting to survival mode of server from lobby.

![mcc1](https://user-images.githubusercontent.com/56913610/125962480-0614fe87-61d3-4e6a-b0e9-1a44c086857b.jpg)

2. For sending the "/move" command:
![mcc2](https://user-images.githubusercontent.com/56913610/125962698-dc088fdd-7003-458e-b925-6e8918f21896.jpg)

**Comment by Hookw** [comment]
If I understood correctly that you cannot execute the command move up with a script, then use the command in your script without "send"
Example script.txt :

send /login ****
send /survival
move up

**Comment by hp2309** [comment]
@Hookw  I tried your suggestion, but in vain
From the other client, the character doesn't seem to move, and the commands sent after "move up", via "send /afk-kick:notafk" are not accepted by the server with the reasoning: "Move 1 block before executing commands".

I get kick into the lobby, (not the server list page), with a message "[Anti-AFK]: you were kicked because you were AFK".
Can I use this message to trigger a script?, I didn't see any "triggerOnMessage" example in sample_tasks.ini. Maybe someone can help me out with this if this trigger exists or not.

Or i will use a triggerOnInterval with "send /survival" that sends me to survival after every 5 minutes.

**Comment by WolfgamingWG** [comment]
I think i know a solution to your problem, the server is requesting you to move a block over, you can do this by executing the command "/move north" in the console client, this makes the client move the player 1 block north. 

If that didn't work there is option 2:
You can use the [AutoRespond] feature in the minecraftclient.ini to make the console client react to the message:
"You were kicked for being afk"
With a command like:
"Send /survival"

This can be done if you add this in the matches.ini:
[Match]
Match=You were kicked for being afk
Actionother=send /server survival

For more info on matches.ini and [AutoRespond] please look at: [Sample-Matches.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini) and [AutoRespond part in ReadMe.md (info on console client use)](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.md#using-the-autorespond-feature) 

I hope this helps!

**Comment by hp2309** [comment]
Thanks @WolfgamingWG , It worked.

I also tried another method where I do "send /survival" continuously at the interval of 30 sec.
> When the character is in the survival world, the command is ignored by the "Move One Block Bot preventor".
> And when the character is kicked to the lobby, the command is accepted and the player is sent back to the survival world.

Thank you all for the efforts you put in. 
A really great repository.

Regards,
Hetal
