### ISSUE TITLE
Send a discord message when script activated

### ISSUE THREAD

**Issue by WolfgamingWG** [ORelio/Minecraft-Console-Client#1693]
I'm not great with C# so I don't know how to make a discord webhook connected to the console client and actually send a msg when the script is activated.

Example of what I want to do:
when I activate the C# script it sends a preset msg like "The server is restarting now" or something I can edit in the code to the discord webhook,

Thx in advance for helping!

**Comment by ReinforceZwei** [comment]
You may use [DiscordWebhook.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/DiscordWebhook.cs) ChatBot to send webhook message.

If you want something simpler, you may check out [sample-script-with-http-request.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-http-request.cs) to see how to send a HTTP request.

**Comment by WolfgamingWG** [comment]
I have tried to use DiscordWebhook.cs before but without any luck, i was very confused and couldnt figure out how it worked. I have no clue how to setup the script with http request but as i said i dont know much about C# so got no clue how to edit it, i tried to do a quick google search for a C# discordwebhook script that i could integrate but also no luck there. Can someone maybe explain how to setup the DiscordWebhook.cs properly so whenever i want i can send a msg to discord via a command or something, or can someone make a simple script that sends a msg via the webhook to the discord server?

**Comment by WolfgamingWG** [comment]
Update:
I have learned how to use the DiscordWebhook.cs, it was a bit of understanding but its up and running now.

No further help needed.
