### ISSUE TITLE
Get through the half block[Question] 

### ISSUE THREAD

**Issue by Hookw** [ORelio/Minecraft-Console-Client#1697]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

517

### Description of the Question

Is it possible to somehow get through the floor block?
(without pistons, etc.)

### Minecraft Version

1.16.5

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
See #553. Closing as duplicated.
