### ISSUE TITLE
[Question] How to actually use the CHATBOTS

### ISSUE THREAD

**Issue by AbdobiZark** [ORelio/Minecraft-Console-Client#1703]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [ ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1.4.6 to 1.12.2  - v1.12.2 -

### Description of the Question

i don't really know how to use or enable them i just tried to use /scrip but didnt work ( missing files / digblock didnt found ) I just want to ask how they work and what to need to use them. Do i need to create a separate folder? Do i need add additional files or .cs to be able to work it/them? 

### Solutions you've already considered

1. 
2. 

### Minecraft Version

1.12.2

**Comment by ORelio** [comment]
As per [User Manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-configuration-files--enabling-bots):
> Simply open the INI configuration file with a text editor and change the values. To enable a bot change the enabled value in the INI file from false to true. You will still be able to send and receive chat messages when a bot is loaded.

**Comment by AbdobiZark** [comment]
![image](https://user-images.githubusercontent.com/88251043/128622251-f116b28d-8b3c-4d0d-92d1-96824587aae7.png)

**Comment by AbdobiZark** [comment]
> As per [User Manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-configuration-files--enabling-bots):
> 
> > Simply open the INI configuration file with a text editor and change the values. To enable a bot change the enabled value in the INI file from false to true. You will still be able to send and receive chat messages when a bot is loaded.

yes i already do

**Comment by ReinforceZwei** [comment]
I guess you are loading MCC internal bots or MCC command files which you shouldn't. As your console client version is pretty old (v1.12.2), please download the latest version first.

**Comment by AbdobiZark** [comment]
> I guess you are loading MCC internal bots or MCC command files which you shouldn't. Those files were built-in to the `.exe`. As your console client version is pretty old (v1.12.2), please download the latest version first.

yay it work, thanks a lot
