### ISSUE TITLE
[BUG] Can't join realm... says different IP reported than manually set

### ISSUE THREAD

**Issue by TheOnlyOly** [ORelio/Minecraft-Console-Client#1705]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [ ] I have set debugmessages=true in config to diagnose my issue
- [x] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.1

### Console Client Version

1.17.1

### Expected Behavior

it should connect to the realm

### Actual Behavior

It pops up an error saying server reports a different version than manually set

### Steps to Reproduce the bug

1. 
2. 
3. 

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
Please:
1. Set debugmessages=true in config
2. Attach screenshot

**Comment by TheOnlyOly** [comment]
![46f9f0fc66c6040a37cb0c88cce8cc86](https://user-images.githubusercontent.com/88365903/127970872-9f05a8d5-ca31-4227-9634-943c9ef540ed.png)

**Comment by TheOnlyOly** [comment]
how do I set the debug thing

**Comment by ReinforceZwei** [comment]
![image](https://user-images.githubusercontent.com/39955851/127973612-6493c8ba-e962-4be9-bffb-3f755335b22f.png)
You should type `realms:0` as server address.

**Comment by TheOnlyOly** [comment]
thank you :)
