### ISSUE TITLE
[Question] Login failed :Network Error

### ISSUE THREAD

**Issue by smashie420** [ORelio/Minecraft-Console-Client#1708]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

When executing `mono MinecraftClient.exe` from the [latest builds](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) client cannot connect to Minecraft.net?

### Solutions you've already considered

1. Rebooting
2. Using an alt account
3. Pinging mojang.com

###  Minecraft Client
![](https://i.imgur.com/vbZtt7b.png)

### Minecraft.net pings
![](https://i.imgur.com/o9yEIfm.png)

### Mojang.com pings
![](https://i.imgur.com/EqfHrIR.png)

### Anythings that could help us answering the question

```txt
Hardware: Raspberry Pi 4 Model B
OS: Raspbian GNU/Linux 10 (buster)
```

### Minecraft Version

1.17.1

### Device

Raspberry Pi

### Operating System

Linux

**Comment by ReinforceZwei** [comment]
Please:
1. Set debugmessages=true in the config 
2. Attach screenshot

**Comment by smashie420** [comment]
I've set debug msgs to true in the ini, seems the same?
![](https://i.imgur.com/QjMU7xZ.png)

![](https://i.imgur.com/wzmgKfx.png)

**Comment by ORelio** [comment]
You are using PuTTY which by default displays dark gray messages as black, hiding them. You can adjust your PuTTY config to show dark gray messages as dark gray and take a better screenshot. Since you are likely using a VPS, I suspect that you may need to use the "browser" authentication method for your Microsoft account.

**Comment by smashie420** [comment]
CMD using MCC auth
![](https://i.imgur.com/ggaJHlg.png)

CMD using browser auth
![](https://i.imgur.com/5vrMIGX.png)

I'm currently self hosting it from my local network, Mojang doesn't seem to be blacklisted

**Comment by ORelio** [comment]
Looks like your Mono environment does not have the appropriate root certificates for performing the HTTPS request.
Similar issue: #1423

**Comment by smashie420** [comment]
Thanks! Got it working turns out `mozroots --import --ask-remove` is outdated, ive fixed this issue by installing `ca-certificates-mono` 

# Commands i used (RASPBIAN OS)
```bash
sudo apt install apt-transport-https dirmngr gnupg ca-certificates
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/debian stable-raspbianbuster main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update

sudo apt install mono-devel ca-certificates-mono
```

Thanks for the support @ORelio, @ReinforceZwei

**Comment by ORelio** [comment]
Thanks @smashie420 for your feedback. Added your solution to the README file 👍
