### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DanielAtom** [ORelio/Minecraft-Console-Client#1710]
Hello.
How can I login with a new account in a C# script? Is there a function for it?
Thanks!

**Comment by ORelio** [comment]
Not really but you can use PerformInternalCommand to run the "connect" or "reco" commands

**Comment by DanielAtom** [comment]
> Not really but you can use PerformInternalCommand to run the "connect" or "reco" commands

I know how to reconnect to the server, but I want to login to another minecraft account as well. Is there a function for logging in to another MC account?

**Comment by ReinforceZwei** [comment]
Actually you can set `Settings.Login` and `Settings.Password` to a different account in your C# script and perform reconnect.
![image](https://user-images.githubusercontent.com/39955851/128601607-245c647e-5d4d-4fc2-bac8-8d8b6f1583ad.png)

Test script:
```cs
//MCCScript 1.0

ConsoleIO.WriteLine("Origin: "+Settings.Login);
Settings.Login = "NewTestBot";
ConsoleIO.WriteLine("After:  "+Settings.Login);
MCC.PerformInternalCommand("reco");
```

**Comment by DanielAtom** [comment]
> Actually you can set `Settings.Login` and `Settings.Password` to a different account in your C# script and perform reconnect.
> 
> ![image](https://user-images.githubusercontent.com/39955851/128601607-245c647e-5d4d-4fc2-bac8-8d8b6f1583ad.png)
> 
> 
> 
> Test script:
> 
> ```cs
> 
> //MCCScript 1.0
> 
> 
> 
> ConsoleIO.WriteLine("Origin: "+Settings.Login);
> 
> Settings.Login = "NewTestBot";
> 
> ConsoleIO.WriteLine("After:  "+Settings.Login);
> 
> MCC.PerformInternalCommand("reco");
> 
> ```

Thanks! That's exactly what I'm looking for!

**Comment by ORelio** [comment]
The command accepts an optional argument for setting the account:
```
connect <server> [account]
reco [account]
```
So you don't need to set the account manually, although it does not hurt.
