### ISSUE TITLE
[Idea] An option to have no console formatting

### ISSUE THREAD

**Issue by he3als** [ORelio/Minecraft-Console-Client#1711]
### Prerequisites

- [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Minecraft Console Client crashes when using Pterodactyl panel, due to Pterodatyl panel not liking the console formatting.

### Suggest a possible solution

Add an option to have no console formatting, just regular text with no colours or anything of the sort.

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/65787561/128577017-5e5e38d4-2aad-4e5b-88ba-54043cd44975.png)

### Minecraft Version

1.17.1

### Device

VPS

### Operating System

Linux

**Comment by ReinforceZwei** [comment]
There's `BasicIO-NoColor` command argument to disable color output.
See https://github.com/ORelio/Minecraft-Console-Client/wiki/Command-arguments#explanation
