### ISSUE TITLE
Terrain and Movements 1.17.1

### ISSUE THREAD

**Issue by iCrayix** [ORelio/Minecraft-Console-Client#1712]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

When does Minecraft Console Client support Terrain and Movements for 1.17.1?

### Minecraft Version

1.17.1

### Device

VPS

### Operating System

Linux

**Comment by ORelio** [comment]
We are a small team and lacking time to work on updates so it'll arrive eventually but no ETA.
Of course, contributions are welcome!
See also #1629 for 1.17 status.

**Comment by mvoppen** [comment]
At least terrain, movement and inventory I have running under 1.17.1. In the next few days I'll provide a merge request...
