### ISSUE TITLE
[Question] How to drop items using scripts

### ISSUE THREAD

**Issue by PLSINEEDHELP213** [ORelio/Minecraft-Console-Client#1713]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

Hello, I wanted to drop items in the player inventory using scripts.
How do i do this?

Simply, I want to execute /dropitem in a script but using /send /dropitem doesn't work

It seems that i can only use /send [command] to directly send commands to the server.
How do i send it into the MCC client so its just like typing /dropitem [item] into the terminal?
Thank you in advance

### Solutions you've already considered

1. I added /dropitem diamondhelmet in the script
2. I tried /send /dropitem diamondhelmet in the script

### Anythings that could help us answering the question

```txt
Script:
send /login [Private Password]
wait 5
send /register [Password Private]
wait 5
send /faction
wait 10
send /tpa isaiah
wait 30s
send /kit weekly
wait 10
send /dropitem diamondhelmet
send /dropitem diamondsword
send /dropitem diamondleggings
send /dropitem diamondchestplate
send /dropitem diamondboots
send /dropitem EnchantedGoldenApple
send /dropitem GoldenApple

TaskScheduler Config:
[Task]
triggerOnLogin=true
action=script startup.txt
```

### Minecraft Version

1.17.1

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

Play.Pinoy-Craft.Com

**Comment by ReinforceZwei** [comment]
Hi, you may execute MCC command directly without using `send`.
Example `myscript.txt`:
```
send /login [Private Password]
wait 5
send /register [Password Private]
wait 5
send /faction
wait 10
send /tpa isaiah
wait 30s
send /kit weekly
wait 10
dropitem diamondhelmet
dropitem diamondsword
dropitem diamondleggings
dropitem diamondchestplate
dropitem diamondboots
dropitem EnchantedGoldenApple
dropitem GoldenApple
```

**Comment by PLSINEEDHELP213** [comment]
Okay thanks lov u
