### ISSUE TITLE
[Question] AutoRespond | matches.ini

### ISSUE THREAD

**Issue by AbdobiZark** [ORelio/Minecraft-Console-Client#1717]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

how to do when someone whispers to you via /tell  and with the same or exact match keyword " activatescript101 " trigger and then execute or send mccc command like " /sneak "

they also look like this
![image](https://user-images.githubusercontent.com/88251043/128637608-9a2f5e45-79bb-425b-a6b8-ac0adfd793e0.png)

### Solutions you've already considered

1. 
2. 

### Minecraft Version

Auto

### Device

Desktop

### Operating System

Windows

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages
> Detecting chat messages
> ------
> Minecraft Console Client can parse messages from the server in order to detect private and public messages.
This is useful for reacting to messages eg when using the AutoRespond, Hangman game, or RemoteControl bots.
However, for unusual chat formats, so you may need to tinker with the ChatFormat section `MinecraftClient.ini`. This section defines the chat format by the means of regular expressions. Building regular expressions can be a bit tricky, so you might want to try them out eg on https://regex101.com - See also issue [#1640](https://github.com/ORelio/Minecraft-Console-Client/issues/1640) for more explanations on regular expressions. You can test that your MCC instance properly detects chat messages using [`sample-script-with-chatbot.cs`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs).

**Comment by AbdobiZark** [comment]
@ORelio Thanks I did well 
![image](https://user-images.githubusercontent.com/88251043/128881302-aae0a1b1-0fff-44d7-ba71-6ddaddee4a7d.png)
