### ISSUE TITLE
Not Able to login to console client.

### ISSUE THREAD

**Issue by NotHashkey** [ORelio/Minecraft-Console-Client#1720]
I put in my login details and launched it and I get this error...
![New Window@play wildprison net - Minecraft Console Client 10-08-2021 11_46_45_LI](https://user-images.githubusercontent.com/88704042/128817624-7db4d5a2-0dda-434f-b8c1-e39e77544672.jpg)

**Comment by NotHashkey** [comment]
My minecraft account is a microsoft account... maybe thats the issue but please help

**Comment by ReinforceZwei** [comment]
Take a look at #1474

**Comment by NotHashkey** [comment]
> Take a look at #1474

Still getting the same error... also there doesnt seem to be a line with "type=" or "method="

**Comment by ReinforceZwei** [comment]
Your configuration file was generated by an older version of MCC. You have to delete the old configuration file, download the latest version of MCC and let it create a new one.

**Comment by NotHashkey** [comment]
![MinecraftClient ini - Notepad 10-08-2021 11_59_55](https://user-images.githubusercontent.com/88704042/128819099-f3c47567-ba0f-4911-b0ce-760f9c51611c.png)

**Comment by NotHashkey** [comment]
> Your configuration file was generated by an older version of MCC. You have to delete the old configuration file, download the latest version of MCC and let it create a new one.

just did that...

**Comment by ReinforceZwei** [comment]
> download the latest version of MCC

**Comment by NotHashkey** [comment]
where can I find that?

**Comment by NotHashkey** [comment]
> where can I find that?

@ReinforceZwei

**Comment by ReinforceZwei** [comment]
https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by NotHashkey** [comment]
omg tysm!
