### ISSUE TITLE
[Question] How to block a chat message starting with a precise word from showing up in the console

### ISSUE THREAD

**Issue by DanielAtom** [ORelio/Minecraft-Console-Client#1728]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

Hello.
The server I'm connecting to is literally spamming an annoying message in my console.
Is there any way to block it or prevent it from showing up? It's always the same and it starts with the word "Mana".
Is there any way to block the message by that criteria, by the criteria of it starting with "Mana"? I saw the chatfiler thingy in the config, but I don't know how to set it to block anything starting with "Mana", so if you could help me it would be awesome.
Thanks!

### Minecraft Version

1.15.2

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
https://github.com/ORelio/Minecraft-Console-Client/blob/a05e89cf581483c1f9aa5662e0ee001cee457957/MinecraftClient/Resources/config/MinecraftClient.ini#L52

You will need a regular expression (regex) for `chatfilter`. 
![image](https://user-images.githubusercontent.com/39955851/129348507-7bcd443e-5f0f-440c-a3f4-6d08f513dd7a.png)
```regex
^Mana.*
```

**Comment by DanielAtom** [comment]
> https://github.com/ORelio/Minecraft-Console-Client/blob/a05e89cf581483c1f9aa5662e0ee001cee457957/MinecraftClient/Resources/config/MinecraftClient.ini#L52
> 
> You will need a regular expression (regex) for `chatfilter`.
> 
> To match message start with `Mana`,
> ![image](https://user-images.githubusercontent.com/39955851/129348507-7bcd443e-5f0f-440c-a3f4-6d08f513dd7a.png)
> 
> ```regexp
> ^Mana.*
> ```

Thanks! Will it also work if the "Mana" word in the message is colored?

**Comment by ReinforceZwei** [comment]
I am not sure. Maybe you could give a try.

**Comment by DanielAtom** [comment]
> I am not sure. Maybe you could give a try.

Alright! Thanks! I will!
