### ISSUE TITLE
regex help

### ISSUE THREAD

**Issue by WolfgamingWG** [ORelio/Minecraft-Console-Client#1730]
I have been trying to make a regex for public chat for the server I play on but there is one problem, they allow custom suffixes, which is a problem when I try to make a regex, I have tried many things but without any luck.

This is what I have right now:
`(?:.* |)(?:\[.*\]|)(.*)\| (.*)`
This is what I am trying to detect: 
`(Literally anything, maybe a rank like this: [Rank] but not always)name(Literally anything)| (msg here)`
or in an example that makes at least a little sense:
`prefix [rank] name suffix| msg`
which can also be more like these examples (the - indicates a new example):
`name| msg - [rank] name| msg - prefix name| msg - name suffix| msg - prefix name suffix| msg`

more info: spaces and special characters are also a part of the custom suffixes, which means it's really hard to make a regex that actually sees the difference in what a name is or not. most of the time the msg that is sent in the chat is after the | icon however I did indeed say that the custom suffixes allowed anything including that character so I don't know if it's possible to filter out as well but if not then just make it so that anything after | is seen as msg.

Thank you to anyone who tried to help or actually helped in advance!

p.s: 
Sorry if this is too confusing it is just a little hard to explain this.

**Comment by ReinforceZwei** [comment]
It is a bit confused to understand the exact message format. Would you mind providing few message captures?

**Comment by WolfgamingWG** [comment]
As expected the message format is indeed very confusing, hence why I am reaching out.

[https://imgur.com/a/pnNeP3s](here is an image that shows chat), I have divided different parts of msgs with colors (some stuff may be blurred due to privacy), the colors are as following:
Red = Prefix (This can range from any length and can have any character)
Yellow = Name
Light Blue/aqua = Suffix (This can also range from any length and can have any character)
Purple = Normal chat msg

[https://imgur.com/FvtmVC3]((Here is an image without the colors if needed.))

as you can see, the msgs can range from anything as simple as the very last msg with just `name| msg` to something like `prefix name suffix| msg`, as I said in my original msg most of the time the msg that is sent in the chat is after the |, which means it's possible to divide the msg from the rest of the chat msg.

I'm sorry if it's still confusing but I hope this helps.

**Comment by ReinforceZwei** [comment]
https://regex101.com/r/xyGedq/1
![image](https://user-images.githubusercontent.com/39955851/130251883-3b9bdb74-ae0e-4f52-90c9-07394c036f43.png)
Green is player name and orange is message. As stated in test data, if the `[Rank]` is not enclosed in `[]`, this regex will not work and most likely no other way to capture the player name.

**Comment by WolfgamingWG** [comment]
As of this moment, the regex is good enough, I will try to look into making one that is fully workable since I found 1 problem with it but I will work that one out, but atm this one is good enough to work with. 

Thank you for the help!
