### ISSUE TITLE
Discordwebhook.cs Avatar

### ISSUE THREAD

**Issue by WolfgamingWG** [ORelio/Minecraft-Console-Client#1734]
Might be a stupid question, but the profile picture the script uses on discord is just the discord logo and I want to change it. I have looked in the config and tried to change stuff around but still cannot find it. 

Is there a way to add a URL for a picture somewhere in the config? if so then where in the config?

Thx in advance :)

**Comment by ReinforceZwei** [comment]
You may want to take a look at #1716

**Comment by WolfgamingWG** [comment]
I looked at the issue that was linked but couldn't find a way to add a custom icon from for example a URL. I only could change it to a different UUID. Is there a way to add a URL to the config instead?

@Daenges do you have anything that may be able to do this?

**Comment by Daenges** [comment]
@WolfgamingWG 
As shown in this [comment](https://github.com/ORelio/Minecraft-Console-Client/issues/1716#issuecomment-894806297), you can replace `sAPI.GetSkinURLCrafatar("UUID")` with any valid URL in string format to an image. So you can replace this whole block with lets say: `"https://vignette.wikia.nocookie.net/meme/images/5/52/Polite_Cat-0.jpg"`
This would change the code line to:

`msg.SenderName == "[Server]" ? "https://vignette.wikia.nocookie.net/meme/images/5/52/Polite_Cat-0.jpg" : sAPI.GetSkinURLCrafatar(msg.SenderUUID)`

If the server now sends a message, it should have a nice image from the internet.

**Comment by WolfgamingWG** [comment]
Aha okay, i will try that as soon as im back at my pc, i see what i have done wrong tho so ill change it up and come back here to report on how it went.

**Comment by Daenges** [comment]
> Might be a stupid question, but the profile picture the script uses on discord is just the discord logo and I want to change it. 
This can happen if the Skin API is down. This happens from time to time, but it should fix itself within a few minutes.

**Comment by Daenges** [comment]
If this happens again, you can test it by entering your UUID at https://crafatar.com/. If nothing shows up, they might be in maintenance or something. If something shows up and it does not work in Discord, you found a bug. Make sure to report it.

**Comment by WolfgamingWG** [comment]
It's working now, thx for the help!
