### ISSUE TITLE
[Idea] Enable GitHub Discussions feature on this repository

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1735]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

N/A

### Describe your problem

This feature work as a forum. People can discuss a problem or ask a question without creating a new issue.

### Suggest a possible solution

@ORelio I would like to enable this feature on this repository.

### Attach screenshot here (If applicable)

To enable it:
![image](https://user-images.githubusercontent.com/39955851/130348820-9595c30f-0292-477b-b37c-a43f855db0d7.png)

**Comment by ORelio** [comment]
Why not. Just enabled the feature.

**Comment by ReinforceZwei** [comment]
I found that I cannot create announcement at https://github.com/ORelio/Minecraft-Console-Client/discussions/categories/announcements

**Comment by ORelio** [comment]
I'm not sure how I can grant you access to the announcement part, In the "manage access" part of the repository, I can grant "collaborator" status without further settings 🤔
