### ISSUE TITLE
Server updated join commands

### ISSUE THREAD

**Issue by YanderePepe** [ORelio/Minecraft-Console-Client#175]
The server im using this on changed their way of joining (It no longer uses /server). Is there a way i can open minecraft, join the server (Factions) and then start the client? Im open to any suggestions. 

PS: The Server now uses a compass to join servers.

**Comment by ORelio** [comment]
I guess your server admin put that plugin that opens an inventory when using the compass and then you have to select an item to go to the desired server. Currently using items or interacting with inventories is not implemented so if they disabled /server I don't see a workaround for now.

**Comment by ReOp14** [comment]
YanderePepe, if there is a portal login to the server somewhere, you can turn on terrain and movements and then have a script to automaticly /move itself to the portal and go through.

**Comment by ORelio** [comment]
This issue is related to #205, closing this one to leave only the main "inventories" one open.
