### ISSUE TITLE
[Question] DiscordWebhook: sending messages only from players

### ISSUE THREAD

**Issue by CrazyFoxxx** [ORelio/Minecraft-Console-Client#1750]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Hi. I got a problem: when I use [this](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/DiscordWebhook.cs) script to transfer messages from the chat of the minecraft server to the discord server, I get other messages (for example, the player received the achievement, "join the ds of our minecraft server"), but I don't want these messages went to ds. Could you help me with this?
Sorry for my bad english)

### Minecraft Version

1.16.3

### Device

VPS

### Operating System

Windows

**Comment by Daenges** [comment]
@CrazyFoxxx 
Try to disable server messages with `/dw sendservermsg`?
If this does not help, could you provide some screenshots from discord and the corresponding messages in the mc chat?

**Comment by CrazyFoxxx** [comment]
> @CrazyFoxxx
> Try to disable server messages with `/dw sendservermsg`.
> If this does not help, could you provide some screenshots from discord and the corresponding messages in the mc chat?

When I turn off the message from the server, they turn off messages from the players including ;(

[https://i.imgur.com/eVpkgHA.png](Minecraft Chat)
[https://i.imgur.com/PjUJzTX.png](Discord Chat)

**Comment by Daenges** [comment]
@CrazyFoxxx This may be caused by the bot not recognizing the chat format of your server. 

To detect different kinds of messages (e.g. private messages, public messages) the client uses certain word patterns that can be configured in the [.ini file](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Resources/config/MinecraftClient.ini#L71).

As you can see [here](
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/DiscordWebhook.cs#L397), every message that is not detected as anything else, counts as `Server Message`. If the preconfigured chat detection fails, anything will be counted as "Server Message", which may be the reason why everything gets deactivated.

It seems like your server has an unusual chat format, which means that it is not included in the standard detection. This means a solution for your problem would be to add a new chat format in the .ini file.

**Comment by Daenges** [comment]
This is how the chat looks like, if the detection runs successful:
![Example_Chat](https://user-images.githubusercontent.com/57369924/132108216-d51474c0-01d9-4487-8a63-ea34db6a6b7f.png)

**Comment by CrazyFoxxx** [comment]
> This is how the chat looks like, if the detection runs successful:
> ![Example_Chat](https://user-images.githubusercontent.com/57369924/132108216-d51474c0-01d9-4487-8a63-ea34db6a6b7f.png)

@Daenges, I tried this, but unfortunately it doesn't work ;(

I am using this chat format and it works: 
`^\[G\] [^ ]+ ([a-zA-Z0-9_]+) .+ (.*)$`

But all the same, even when messages from the server are turned off, advertising of the discord server, site, etc. appears:
[img](https://i.imgur.com/RKa2QjU.png)

Also, only the last word from the message is sent:
[img_1](https://i.imgur.com/UpcH0f2.png)
[img_2](https://i.imgur.com/fVFbTzP.png)

**Comment by Daenges** [comment]
@CrazyFoxxx Could you provide a chat message with only the name blurred out? So I can verify that you used the correct regex expression?

**Comment by CrazyFoxxx** [comment]
[img_1](https://i.imgur.com/v8Cb7xG.png)
[img_2](https://i.imgur.com/OHR79UT.png)
[img_3](https://i.imgur.com/R8VSogJ.png)

**Comment by CrazyFoxxx** [comment]
Fortunately, messages from the server are no longer sent

**Comment by Daenges** [comment]
In which format is the advertisement sent?

**Comment by CrazyFoxxx** [comment]
@Daenges Fortunately, messages from the server (advertisements) are no longer sent

**Comment by Daenges** [comment]
Oh... Problem solved?

**Comment by Daenges** [comment]
@CrazyFoxxx  I am not too familiar with regex expressions, but in the config file, the example uses a `+` at the end, not a `*`.
Mabye change it to `^\[G\] [^ ]+ ([a-zA-Z0-9_]+) .+ (.+)$`?

**Comment by CrazyFoxxx** [comment]
> ^\[G\] [^ ]+ ([a-zA-Z0-9_]+) .+ (.+)$

Unfortunately this doesn't work :( 

[img1](https://user-images.githubusercontent.com/71690715/132109457-2d0d7a0c-f1f3-4f55-af33-7f318c9b0f38.png)
[img2](https://user-images.githubusercontent.com/71690715/132109545-725ab3f1-6555-465b-8a46-cbc1159318d8.png)

**Comment by Daenges** [comment]
@CrazyFoxxx  I tried something with a regex editor: `^\[G\] [^ ]+ ([a-zA-Z0-9_]+) .*? (.+)$`

**Comment by CrazyFoxxx** [comment]
@Daenges 
[img](https://i.imgur.com/lIx9nx3.png)

Unfortunately, this doesn't work very well. With different suffixes, messages are sent differently

**Comment by Daenges** [comment]
@CrazyFoxxx Okay, this one looks pretty promising: `^\[G\] [^ ]+ ([a-zA-Z0-9_]+) .*?\B (.+)$`

**Comment by CrazyFoxxx** [comment]
@Daenges 
This also does not work correctly. I tested and sent a couple of messages without the suffix and it worked! This cannot be adapted for my server in any way, because all players have different suffixes. 

Anyway, thank you so much for your help!
