### ISSUE TITLE
Loading chunks

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#176]
Does it load chunks?

**Comment by ORelio** [comment]
Yes. By default, chunks are only loaded server-side and ignored client-side.
For client-side chunk loading, see [Interacting with the Minecraft World](https://github.com/ORelio/Minecraft-Console-Client/blob/67fc431d4a053fa09f67e754224d9ba4850ef735/MinecraftClient/config/README.txt#L84).
