### ISSUE TITLE
This Client maybe need to add a warning in config file.[Idea] 

### ISSUE THREAD

**Issue by kelvin-lee233** [ORelio/Minecraft-Console-Client#1764]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1736

### Describe your problem

This Client may need to add some warning and disclaimer by setting  ”EULA“.
I get banned by server for your program, I want to create a new issue to reflect this program and spot a disclaimer message in your user manual mentioned the risk of GET BANNED. For me, is too late.
Beta feature **inventoryhandling**,**entityhandling** and **terrainandmovements** in this client can provide some feature that vanilla client do not have. For example, command `/entity Target attack  ` can let player attack entity and **ignoring distance, barrier, angle limit**. some source code about `inventory` allow player get block data from server client, Which I mention above let **MCC** becomes "cheat client" like impact in some server. Moreover, many server regard **automatic script** as **cheat**. 
Although there are serval warning messages in section of **Disclaimer** mentioned the risk of GET BANNED  by sever, there is a part of player would miss all of this or some of message before using client. Furthermore, I notice that someone cited/spread your products copy to other forum without illustrated  the section of **Disclaimer**, in some cases them only diliver an EXE file. Therefore,  it's nesssary to ensure the player have right to know the message of **disclaimer**. 

### Suggest a possible solution

EULA is a great example. When we run mojang.jar to create Minecraft server for the first time ,the program will remind us that the server will not create until we agree with EULA . Then program will generate  EULA.TXT file. We have to open this file, look throught file and EULA, then set EULA as TRUE. Only in this way we can create Minecraft server suceessfully.
We can create a example.TXT file which content is:

```
#============================================En_English=======================================================
#By changing the setting below to TRUE you have read and agreed to the message we list below. 
# You have read Minecraft Console Client User Manual and you know all the warning and disclaimer we set, including but not limited to:
# 1. Minecraft Console Client is a totally free of charge, open source project. Source code and help is available at https://github.com/ORelio/Minecraft-Console-Client
# 2. Unless specifically stated, source code is from me or contributors, and available under CDDL-1.0. More info about CDDL-1.0: http://qstuff.blogspot.fr/2007/04/why-cddl.html Full license at http://opensource.org/licenses/CDDL-1.0
# 3. Minecraft Console Client can provide an unfair advantage in Multiplayer mode. So we remind you that you may GET BANNED by your server for using this program and we won't be held responsible for this. For avoid anything unpleasant, we strongly suggested you to ask the administrator for the permission before you using this program in their sever unless the server is marked as "anarchy".
# 4. other disclaimer you want to set, as you like.
=============================================Zh_中文简体====================================================
#你通过将下面的设置的值改变为真表明你对我们在下面列出的信息知情并同意:
#你已经阅读了Minecraft Console Client的用户手册且知道我们所有的警告和免责声明，包括但不限于:
# 1.Minecraft Console Client 是一款完全免费，开源的项目。源代码,用户手册和帮助文档在下列网址可见:https://github.com/ORelio/Minecraft-Console-Client
# 2.除非特别说明，源代码来自我或贡献者，并在开源许可证CDDL-1.0下提供。更多有关CDDL-1.0的信息在:http://qstuff.blogspot.fr/2007/04/why-cddl.html。完整的许可证在:http://opensource.org/licenses/CDDL-1.0。
# 3.Minecraft Console Client 可以在多人游戏模式中提供非公平优势，所以我们提醒你你可能因为在服务器使用这个程序而被封禁，而我们不会对此负责。为了避免有任何不愉快的事情发生，我们强烈建议你在服务器使用本程序之前获得管理员的同意，除非该服务器被明确标记为“无政府状态”。
# 4.其它你想加入的声明，你喜欢就好。other disclaimer you want to set, as you like.
#=============================================Other_language================================================
#
===================================setting_设置_setting in other_language===================================
read_and_agreed = false 
# read_and_agreed can change to any words as you like.
# Minecraft Console Client will not run until this value is true.



```
And you can diliver a "PURE" version of console client Minecraft Console Client, which only have chat teature and regarded as real player in server. In spite of this, the risk of get banned still exist according with server rules.

### Attach screenshot here (If applicable)

none

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by ZizzyDizzyMC** [comment]
I'd argue that if one knowingly enables + uses these features they already know what they're doing enough to know that doing so isn't native functionality of MC.  

In addition the EULA here as presented is seemingly made to look scary with things like GET BANNED, when in reality the only advantages possible would be done on the user knowingly and intentionally.

MCC has a barrier of entry when it comes to using it, if you're able to pass this barrier of entry - you know exactly what you're doing.

**Comment by ORelio** [comment]
I agree pretty much with @ZizzyDizzyMC, the settings you are talking about are disabled by default and when enabling them you'll need to ask yourself if you are allowed to by the server rules. We could add a warning next to these settings in config file, which is automatically generated on first launch. Would that fit your needs?

**Comment by kelvin-lee233** [comment]
Thank you, that's enough.

**Comment by kelvin-lee233** [comment]
Wait a minute, something is wrong here. I am **content with your mearsure** but **I have doubt with your view**. Do you mean technology is netural but it is misused by some people? I admit I have do some dishonest action, cheat and get benned in a server. But I am not going to complain or pass the buck.  You presetting standpoint hurts me a lot.
What if I comment as an operator of the server? I will realsed a new to you that someone using your progarm to cheat and struggling to say it just a "chat&command tool" with no knowing some of these features isn't native functionality of MC, and the server have to **modify rules** after this event.
Yes, I agree with people should take responsibility for their own actions with know exactly what they're doing.
The warning you add is not going to scary the player, but protect them, and you. 
So could you promise to place the warning obiviously?  
The comment will close with problem solved.

**Comment by ORelio** [comment]
Hi,

> Do you mean technology is netural but it is misused by some people?

We DON'T want Minecraft Console Client to be a cheat client, but we try to add some automation for doing boring/repetitive tasks automatically. For instance, the AutoAttack mechanism allows to farm in a dungeon or enables the bot to defend itself when some hostile mobs are approaching. The same way, you can use AutoCraft, the TreeFarmer/BlockMine optional scripts for cobblestone/tree farms, and so on.

While this may be permitted on some servers, some other servers may forbid this. Adding a warning makes sense.

However, we reject features that clearly have no legitimate use, such as attacking players, supporting free alts generators or using a random proxy to evade account/IP bans. Some examples: #746 #1017 #1249 #1554. You won't find those features in official MCC builds, although some people may implement the changes in their own forks.

**Comment by kelvin-lee233** [comment]
> We DON'T want Minecraft Console Client to be a cheat client, but we try to add some automation for doing boring/repetitive tasks automatically.

I am grateful for your sincerely reply. I am deeply moved for we can reach an agreement break through the barriers of age,  region, language and prejudice.  

Waiting for your good news.

**Comment by ORelio** [comment]
As promised, I've added inline documentation and warnings in [MinecraftClient.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Resources/config/MinecraftClient.ini), assuming people will only have the EXE and not read anything before downloading MCC. The warnings in config should now be sufficient to prevent users from facing unexpected consequences when enabling bots. Thanks for suggesting that.

**Comment by kelvin-lee233** [comment]
As promised, I will close the issue after problem solved.

I will try my best to limit the sreading of outdated or unsafe version and urge the user to update their version.

**Comment by ORelio** [comment]
Newer Minecraft versions will tend to naturally make people upgrade their client, although I'm seeing bug reports for old versions (<1.10) on a regular basis, usually on modded/specific servers. As of now, old MCC versions were not found to contain big security issues, but indeed it's always better to keep up to date.
