### ISSUE TITLE
Action bar spamming

### ISSUE THREAD

**Issue by AndrewMast** [ORelio/Minecraft-Console-Client#177]
On certain servers, the action bar has a 'deal' like '20% all in shop! 7:23:10 left!' and each time the clock ticks down, it spams the client with messages
![screen shot 2016-07-30 at 11 46 23 am](https://cloud.githubusercontent.com/assets/13026511/17271845/fe97d3ce-564c-11e6-9072-6fae79ac5c24.png)

**Comment by ORelio** [comment]
In your configuration file you can disable one of these, or both:
````INI
showsystemmessages=true #system messages for server ops
showxpbarmessages=true #messages displayed above xp bar
````
