### ISSUE TITLE
[BUG] Microsoft account: connection forcibly closed by remote host

### ISSUE THREAD

**Issue by UniqueNIHAL** [ORelio/Minecraft-Console-Client#1774]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.2

### Console Client Version

The latest one I just re-downloaded it to check

### Expected Behavior

I expected it to log me into the server

### Actual Behavior

It didn't , it gave some error

### Steps to Reproduce the bug

1. Used my ID
2. Selected Microsoft login
3. Typed IP, it failed.

### Attach screenshot here (If applicable)

![error](https://user-images.githubusercontent.com/87065344/135259588-05fc93f3-bf02-41ba-8285-aed4f50f1a7d.png)

https://imgur.com/QpZLZKd

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

play.craftadia.com

**Comment by UniqueNIHAL** [comment]
Note: I didn't enter IP the mcc closes right before logging in

**Comment by ReinforceZwei** [comment]
Please attach a screenshot with debug messages enabled.

**Comment by UniqueNIHAL** [comment]
![error2](https://user-images.githubusercontent.com/87065344/135262144-58dc9bc7-0113-4c18-836f-7c31f74a95b2.png)

The Error area with debug goes 3 pages long (3screenshot long) But the client closes before I can get those ss got one of them the start above. Any other way to share them?

**Comment by ReinforceZwei** [comment]
You forgot to cover your password in the screenshot. I've deleted it. Please redacted session tokens and passwords before attaching screenshots.

**Comment by UniqueNIHAL** [comment]
![image](https://user-images.githubusercontent.com/87065344/135263438-a48b423b-8dcd-4f2c-9e25-71349c026fc4.png)

**Comment by ReinforceZwei** [comment]
> The Error area with debug goes 3 pages long (3screenshot long) But the client closes before I can get those ss got one of them the start above. Any other way to share them?

You may open a `cmd` and run MCC in it so that the messages will stays there.

**Comment by UniqueNIHAL** [comment]
> > The Error area with debug goes 3 pages long (3screenshot long) But the client closes before I can get those ss got one of them the start above. Any other way to share them?
> 
> You may open a `cmd` and run MCC in it and the messages will stays there.

Doesn't allow it just closes ): (If you mean't typing / to open the command)

**Comment by ReinforceZwei** [comment]
1. Press `win + R`
2. Type `cmd` and press enter
3. Drag `MinecraftClient.exe` into the `cmd` window and press enter

In that way the messages will stays there when MCC closed.

**Comment by UniqueNIHAL** [comment]
![image](https://user-images.githubusercontent.com/87065344/135265303-bcd4bd84-cd93-42a8-9b52-4f383f0fa539.png)
Gives this error but the password is right ): It works on Minecraft.net and microsoft.com , This above ss is from cmd

**Comment by Fr-gs** [comment]
I have the same issue

**Comment by ReinforceZwei** [comment]
It is not possible for us to diagnose the problem with only partial of log output.

**Comment by Desxman** [comment]
![Screenshot (10)_LI](https://user-images.githubusercontent.com/91612000/135275310-269b3ae2-1414-4112-8b6d-f31e2981e4bd.jpg)

This is all I get when putting it into cmd. I have the same problem as others

**Comment by UniqueNIHAL** [comment]
Thankfully not just me ;o yes it worked fine for me yesterday too

**Comment by UniqueNIHAL** [comment]
> It is not possible for us to diagnose the problem with only partial of log output.

Its difficult to get complete log with it closing immediately and cmd version not working

**Comment by UniqueNIHAL** [comment]
![2](https://user-images.githubusercontent.com/87065344/135293658-6a2aaced-157f-4a4b-b989-b95630b28325.png)
![1](https://user-images.githubusercontent.com/87065344/135293674-3af351b4-fc98-4e18-8f34-10cca18febcb.png)
![3](https://user-images.githubusercontent.com/87065344/135293689-843756c9-a2a4-4abb-80c2-bf57334ed1a1.png)


None of these are in order and were random attempts to get an ss before it auto closed.

**Comment by TNTUP** [comment]
Can confirm this problem, outputting debug isn't possible for me as it spills too much information and need to censor them all

**Comment by UniqueNIHAL** [comment]
Yep ^^^

**Comment by ibes1508** [comment]
most I could take out of the debugmessage is that theres some error witth the session cage. Mojang logins work so guess migrating ur acc - if u r able to - might not be good after all

**Comment by UniqueNIHAL** [comment]
Well Microsoft accounts did work yesterday

**Comment by ibes1508** [comment]
Oh one idea for screenshots: record while opening and scroll down. then take ss out of vid. would do it myself but sadly have no clue what I gotta sensor

**Comment by ThatThingz** [comment]
![image](https://user-images.githubusercontent.com/66683636/135368669-7fd12a09-0d50-4c80-b266-682c8be50811.png)
![image](https://user-images.githubusercontent.com/66683636/135368683-e4ff952b-96eb-4a86-9b93-cb4484201406.png)
![image](https://user-images.githubusercontent.com/66683636/135368692-3e929f51-9d4d-4fff-9bf1-5bba71c23a0d.png)
![image](https://user-images.githubusercontent.com/66683636/135368701-2269f0c6-3a7c-4800-929a-312d521bb4c1.png)
![image](https://user-images.githubusercontent.com/66683636/135368716-e02ffd8a-7128-4a1a-b81b-ac9944c4e981.png)
@ReinforceZwei I hope these will be helpful I attempted my best to get screen shots of the issue that I'm having as well.
I am using the current Version of the Client the current Device I'm using is a Laptop and current operating system is Windows 10

**Comment by ThatThingz** [comment]
I tired running it in CMD but it refused to run. I also Kept trying to get more SS past this last one but it kept Closing to fast to allow me to get more SS

**Comment by ThatThingz** [comment]
If you require more SS I can Attempt again but I don't know if I will be able to get anymore

**Comment by XeTrain** [comment]
I'm having this exact same issue too! Hopefully its an easy fix

**Comment by UniqueNIHAL** [comment]
Did Microsoft do something to prevent MCC D:?

**Comment by SintheSergal** [comment]
Also happening to me as well. :c

**Comment by YellySmelly** [comment]
Also happening to me as well. I wish the owner would give us an update on what is happening. Is there  a discord for this console client?

**Comment by quangminhxl** [comment]
> Oh one idea for screenshots: record while opening and scroll down. then take ss out of vid. would do it myself but sadly have no clue what I gotta censor

welp, never expected to see u here but still, why is it not fixed yet? I

**Comment by Nixeld** [comment]
Heres my log file
I hope I took out every sensitive information
[logs.txt](https://github.com/ORelio/Minecraft-Console-Client/files/7264213/logs.txt)

**Comment by Nixeld** [comment]
Heres my log file
I hope I took out every sensitive information
[Uploading logs.txt…]()

**Comment by Nixeld** [comment]
Heres my log file
I hope I took out every sensitive information
[logs.txt](https://github.com/ORelio/Minecraft-Console-Client/files/7264226/logs.txt)

**Comment by ReinforceZwei** [comment]
I've investigated the issue a bit. The program crashes when making request to `api.minecraftservices.com` for getting Minecraft access token.

My guess is `api.minecraftservices.com` disabled TLS 1.0/1.1 support (as shown here https://www.cdn77.com/tls-test/result?domain=api.minecraftservices.com) while other API endpoint still have the support (for example xbox https://www.cdn77.com/tls-test/result?domain=xsts.auth.xboxlive.com).

Everyone here, if possible, please report your OS version. (e.g. Windows 7, Windows 10)

**Comment by UniqueNIHAL** [comment]
![image](https://user-images.githubusercontent.com/87065344/135570177-0a68b7b5-4c4d-4522-9c83-54a0d595e73f.png)

**Comment by ReinforceZwei** [comment]
A hotfix was added. Please download the latest version and test if it works.

**Comment by DemonAKALilKid** [comment]
> A hotfix was added. Please download the latest version and test if it works.
> 
> If it doesn't work on your machine, please report if you have .NET Framework 4.5+ installed on your system or not.

Just downloaded and tried it, not having any problems on windows 11 here

**Comment by UniqueNIHAL** [comment]
Latest Build works. Thank you

**Comment by UniqueNIHAL** [comment]
![image](https://user-images.githubusercontent.com/87065344/135652302-e526036b-422e-432c-922a-37e0bcae6a1d.png)

**Comment by UniqueNIHAL** [comment]
Windows Secruity giving this info since the uhm Update

**Comment by TNTUP** [comment]
I confirm that the hotfix works and I don't get that Windows Defender warning on my computers

**Comment by ObscenityIB** [comment]
> 
> MCC's webclient cannot handle TLS 1.2 and crashed.
>

Would not have expected that, would assume 1.3 support in most active things now, since 1.2 is ancient, and 1.3 is getting on in years.

**Comment by ORelio** [comment]
> ![image](https://user-images.githubusercontent.com/87065344/135652302-e526036b-422e-432c-922a-37e0bcae6a1d.png)

@UniqueNIHAL just relaunched the build for last hotfix, please try downloading it again?

**Comment by UniqueNIHAL** [comment]
> > ![image](https://user-images.githubusercontent.com/87065344/135652302-e526036b-422e-432c-922a-37e0bcae6a1d.png)
> 
> @UniqueNIHAL just relaunched the build for last hotfix, please try downloading it again?

Okay

**Comment by UniqueNIHAL** [comment]
Seems to be working thanks! , Ill Close this Ticket in 24hrs if windows doesn't report any issue again!

**Comment by zerofelero** [comment]
glad to hear it's not just me having the issue...
![bug](https://user-images.githubusercontent.com/55669377/135950518-0314abc2-3120-40f3-87dd-ee7e3380ed51.png)

was fine as of last night, went to bring my alternate accounts online and wham. :(
