### ISSUE TITLE
[Question] Is it possible to mine blocks with the client ?

### ISSUE THREAD

**Issue by Powablocks** [ORelio/Minecraft-Console-Client#1775]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Hello,
I can't find an anwser in the infos.
Is it possible to mine blocks from the console client like by giving a coordinate or juste by verifying the coordinates the player is looking and mining until coordinates change ?

Thanks for answer

Powablocks

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
Use `/dig` command. To see help use `/help dig`.

**Comment by Powablocks** [comment]
Thank you I'll try it.
