### ISSUE TITLE
[BUG?] Microsoft Authentication instant fail, no debug messages.

### ISSUE THREAD

**Issue by ObscenityIB** [ORelio/Minecraft-Console-Client#1778]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [x] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.1

### Console Client Version

eba309191cd145c95b94dd0fed284c1b788b2e2b

### Expected Behavior

Microsoft Login.

### Actual Behavior

Instant failure.

```
Console Client for MC 1.4.6 to 1.17.1 - v1.17.1 - By ORelio & Contributors
[MCC] [Settings] Loading Settings from /path/to/config.ini
Connecting to Microsoft...
Microsoft authenticate failed: Invalid credentials. Check your credentials
Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
```

### Steps to Reproduce the bug

1. add `type=microsoft` & `debugmessages=true` to config
2. create a new "app password" for microsoft account, to avoid 2FA issues.
3. attempt to login to server with `mono mcc.exe 'config.ini' 'email' 'app_password' '127.0.0.1'`

### Anythings that could help diagnosing the bug

```txt
`debugmessages=true` does not seem to do anything for this error.
even `mono --debug` has nothing to say, and the pdb file is present.

tested reaching live.com with `curl`, works fine, no IP block.

tested normal account passsword as well as app password.

I have Microsoft Authenticator to login, hence why i created an app password for "legacy" programs with no 2fa support.

Since i migrated i cant even log in with mojang, so this is my only option now.
```

### Device

VPS

### Operating System

Linux

**Comment by ReinforceZwei** [comment]
There will be some other debug information at the start of the program if debug messages was enabled. In your case seems like debug messages was not enabled. Please check your configuration file. If it doesn't work, you may also try using `--debugmessages=true` as program argument.

**Comment by ObscenityIB** [comment]
apparently its reading the ini as the username? i dont think thats supposed to happen

**Comment by ObscenityIB** [comment]
also reading from `MinecraftClient.ini` instead of the `config.ini` supplied

**Comment by ObscenityIB** [comment]
censored log

`mono MinecraftClient.exe --debugmessages=true config.ini 'email@domain.com' 'app_password'`

```
Console Client for MC 1.4.6 to 1.17.1 - v1.17.1 - By ORelio & Contributors
﻿[MCC] [Settings] Loading Settings from /path/to/MinecraftClient.ini
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]
[SessionCache] Initializing FileSystemWatcher for file: /path/to/SessionCache.ini
Loading session cache from disk: SessionCache.ini
Loaded session: x:x
Loaded session: x:x
Session data has been successfully loaded from disk.
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
> POST /authenticate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.17.1
> Content-Type: application/json
> Content-Length: 177
> Connection: close
> 
> {"agent": { "name": "Minecraft", "version": 1 }, "username": "config\u002eini", "password": "email\u0040domain\u002ecom", "clientToken": "x" }

< HTTP/1.1 403 Forbidden
< Content-Type: application/json
< Content-Length: 107
< Connection: close
< Accept-Ranges: bytes
< Date: Sat, 02 Oct 2021 03:19:00 GMT
< Server: Restlet-Framework/2.4.1
< Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
< X-Cache: Error from cloudfront
< Via: 1.1 x.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: x-C2
< X-Amz-Cf-Id: x
< 
< {"error":"ForbiddenOperationException","errorMessage":"Invalid credentials. Invalid username or password."}
Minecraft Login failed :Incorrect password, blacklisted IP or too many logins.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
```

**Comment by ORelio** [comment]
> Connecting to Minecraft.net...
> Performing request to authserver.mojang.com

Looks like the setting `type=microsoft` did not take effect because it's trying to authenticate as a Mojang account.
Please triple check you correctly set the setting in config?

https://github.com/ORelio/Minecraft-Console-Client/blob/981dd51a9b5821eea6d2564050b82daee6ae859e/MinecraftClient/Resources/config/MinecraftClient.ini#L9-L17

You can also try removing `SessionCache.ini` 🤔

**Comment by ObscenityIB** [comment]
Its ignoring the `.ini`, only command like config options apply

It keeps reading the `.ini` as the username instead

**Comment by ORelio** [comment]
Put config file as very first argument if you want to load a different file.
```
mono MinecraftClient.exe config.ini --debugmessages=true --login='email@domain.com' --password='app_password'
```

**Comment by ObscenityIB** [comment]
After some fiddling around, mcc cant seem to handle any kind of M$ login at all, browser auth worked once, and now hangs the process every time after that, plus without a cache it eliminates any kind of scripting capability.

So its seems its a dead end for M$ migrated accounts for now.

Legacy accounts should still work fine for as long as mojang keeps the auth servers up.

So, heres hoping more people who still use .net can get on board and help with this, its the only cli minecraft client around so it would be pretty bad if it just died because of M$.
