### ISSUE TITLE
'Microsoft.CSharp.RuntimeBinder.Binder' is not defined or imported...

### ISSUE THREAD

**Issue by AndrewMast** [ORelio/Minecraft-Console-Client#178]
I have a script working fine on my Mac. (/script {script}) When I try running it on my PC (I need it to work in my PC) It says that the script failed to run and this error pops up: "System.InvalidOperationEception: Predefined type 'Microsoft.CSharp.RuntimeBinder.Binder' is not defined or imported"

**Comment by ORelio** [comment]
Could you provide a minimal crashing script example?
Not necessarily the whole script but at least a subset that triggers this error.

**Comment by AndrewMast** [comment]
I think I figured out the error. For some reason, whenever a 'dynamic' variable type is called or changed, the script calls that error. I really don't know why, but my script is now working after I fixed that.

**Comment by ORelio** [comment]
What do you mean by changing a dynamic variable type?
Maybe there is something that could be fixed in the script engine.

**Comment by ORelio** [comment]
Due to lack of feedback, this issue cannot be resolved. Feel free to reopen if you have some more elements to provide eg a minimal crashing script example.
