### ISSUE TITLE
[BUG] Mojang account: SSL error unable to sign in

### ISSUE THREAD

**Issue by DanielAtom** [ORelio/Minecraft-Console-Client#1780]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

Latest

### Expected Behavior

I expect for it to login properly.

### Actual Behavior

It doesn't reach the authentication servers properly, thus MCC became unusable. Having this issue since today.

### Steps to Reproduce the bug

Try and start MCC and it will throw that exception.

### Attach screenshot here (If applicable)

![Capture](https://user-images.githubusercontent.com/38626527/135862798-a48dab1a-79b9-4242-9557-88731732a48b.PNG)

### Device

Desktop

### Operating System

Windows

**Comment by DanielAtom** [comment]
Note: It's a mojang account

**Comment by goinsb2000** [comment]
yep having the same issue currently. All accounts, mojang or Microsoft spit out an SSL error.

**Comment by ReinforceZwei** [comment]
Might related to https://github.com/ORelio/Minecraft-Console-Client/issues/1774#issuecomment-931901866 , Mojang disabling TLS 1.0/1.1 support.

**Comment by maxhaomh** [comment]
> Might related to [#1774 (comment)](https://github.com/ORelio/Minecraft-Console-Client/issues/1774#issuecomment-931901866) , Mojang disabling TLS 1.0/1.1 support.

How can we get around this?

**Comment by DemonAKALilKid** [comment]
![image](https://user-images.githubusercontent.com/51981054/135868364-4770bfe4-0f39-427c-8a5f-d13e4ec769de.png)
i'm having this one instead of that

**Comment by ReinforceZwei** [comment]
Please wait for a fix.

**Comment by DemonAKALilKid** [comment]
ok, just remember to tell everyone when it's done xd

**Comment by maxhaomh** [comment]
> Please wait for a fix.

How long will it take?

**Comment by DemonAKALilKid** [comment]
nobody knows, just be patience and wait for it

**Comment by UniqueNIHAL** [comment]
I have the same issue but in Microsoft
![image](https://user-images.githubusercontent.com/87065344/135878588-48ebc04e-b962-4b34-a458-f8fc4a9c6aae.png)

**Comment by DemonAKALilKid** [comment]
i forgot that OP is reporting a mojang error, oof

**Comment by TNTUP** [comment]
I can confirm this isn't due to Mojang errors it happens with Microsoft aswell

**Comment by cubic86** [comment]
I also have a login issue from yesterday. I get the following stacktrace on failure:
```stacktrace
Performing request to authserver.mojang.com
System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00040] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
   --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x0003b] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
   --- End of inner exception stack trace ---
  at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSRequest (System.Collections.Generic.List`1[T] headers, System.String host, System.String& result) [0x00060] in <f5cd7824d1244b62ae87bac1bacde3f7>:0 
  at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSPost (System.String host, System.String endpoint, System.String request, System.String& result) [0x00082] in <f5cd7824d1244b62ae87bac1bacde3f7>:0 
  at MinecraftClient.Protocol.ProtocolHandler.MojangLogin (System.String user, System.String pass, MinecraftClient.Protocol.Session.SessionToken& session) [0x00084] in <f5cd7824d1244b62ae87bac1bacde3f7>:0 
It appears that you are using Mono to run this program.
The first time, you have to import HTTPS certificates using:
mozroots --import --ask-remove
```
I am running the client under Mono 4.6.2 on Ubuntu.

**Comment by dextercs** [comment]
![image](https://user-images.githubusercontent.com/91923515/135939971-8f3d55d0-0d1f-4568-890f-0dce30bd039e.png)

facing the same issue here

**Comment by DemonAKALilKid** [comment]
Server is running Forge without mods.
Server version : Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17 (protocol v756)
Server reports a different version than manually set. Login may not work.
Translations file loaded.
[MCC] Version is supported.
Logging in...
[DEBUG] Crypto keys & hash generated.
[MCC] Checking Session...
Performing request to sessionserver.mojang.com
[MCC] Login failed :
[MCC] Failed to check session.
[ERROR] Failed to login to this server.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
this is wut i got

**Comment by zerofelero** [comment]
glad to hear it's not just me having the issue...
![bug](https://user-images.githubusercontent.com/55669377/135950639-e510afc1-b1ca-4130-9c84-766ea94dc5d8.png)

was fine as of last night, went to bring my alternate accounts online and wham. :(

**Comment by tunkusalim** [comment]
i just wanna add, its working fine on my mac and raspberry pi but not working on windows (tested with windows server 2019 on my vps, even with [build 526](https://ci.appveyor.com/project/ORelio/minecraft-console-client/builds/40995315))
![Capture](https://i.imgur.com/36Qjwdk.png)
![Capture](https://i.imgur.com/XmyA45r.png)

![Capture](https://i.imgur.com/wGeDGXO.png)

**Comment by Jaydenp11** [comment]
Please contact me when its fixed i have a map to win

**Comment by r3spawned** [comment]
I have the same issue when launching Console client in Windows 10..

![ssl error](https://user-images.githubusercontent.com/51679834/136013703-f2b60b8c-a88b-4f0d-99ab-540273317319.png)

As _tunkusalim_ mentioned above, I also have no issues when running Console Client under **Mono** in Linux.  An example screenshot of logging in via my raspberry pi (Raspbian os)..

![pi login fine](https://user-images.githubusercontent.com/51679834/136014695-797940ac-cecc-418b-bf04-f207ff638442.png)

I also got it working under Windows, after installing Ubuntu inside Virtual box.  I installed **Mono**.  Worked first time. 
 Screenshot example..

![virtualbox](https://user-images.githubusercontent.com/51679834/136013941-53906de9-b666-4805-8521-aaff63560f46.png)

**Comment by Jaydenp11** [comment]
> Same here when running mcc in Windows 10.
> 
> ![ssl error](https://user-images.githubusercontent.com/51679834/136013703-f2b60b8c-a88b-4f0d-99ab-540273317319.png)
> 
> However, as _tunkusalim_ mentioned above, I also have no issues when running Console Client using my **Raspberry pi** (Raspbian OS). Works fine.
> 
> ![pi login fine](https://user-images.githubusercontent.com/51679834/136014695-797940ac-cecc-418b-bf04-f207ff638442.png)
> 
> I got it working in Windows 10, after installing **Ubuntu** inside **Virtual box**. Once I installed **Mono** i successfully logged in first time.
> 
> ![virtualbox](https://user-images.githubusercontent.com/51679834/136013941-53906de9-b666-4805-852

Do i need the ubutu to run it or is it working fine now?

**Comment by r3spawned** [comment]
> > Same here when running mcc in Windows 10.
> > ![ssl error](https://user-images.githubusercontent.com/51679834/136013703-f2b60b8c-a88b-4f0d-99ab-540273317319.png)
> > However, as _tunkusalim_ mentioned above, I also have no issues when running Console Client using my **Raspberry pi** (Raspbian OS). Works fine.
> > ![pi login fine](https://user-images.githubusercontent.com/51679834/136014695-797940ac-cecc-418b-bf04-f207ff638442.png)
> > I got it working in Windows 10, after installing **Ubuntu** inside **Virtual box**. Once I installed **Mono** i successfully logged in first time.
> > ![virtualbox](https://user-images.githubusercontent.com/51679834/136013941-53906de9-b666-4805-852
> 
> Do i need the ubutu to run it or is it working fine now?

As of now, its still not working in Windows 10 for me.   I'm using linux to keep my alts online.

**Comment by DanielAtom** [comment]
> Please wait for a fix.

did a fix and it's working
Please check pull request #1783

**Comment by Jaydenp11** [comment]
> > > Same here when running mcc in Windows 10.
> > > ![ssl error](https://user-images.githubusercontent.com/51679834/136013703-f2b60b8c-a88b-4f0d-99ab-540273317319.png)
> > > However, as _tunkusalim_ mentioned above, I also have no issues when running Console Client using my **Raspberry pi** (Raspbian OS). Works fine.
> > > ![pi login fine](https://user-images.githubusercontent.com/51679834/136014695-797940ac-cecc-418b-bf04-f207ff638442.png)
> > > I got it working in Windows 10, after installing **Ubuntu** inside **Virtual box**. Once I installed **Mono** i successfully logged in first time.
> > > ![virtualbox](https://user-images.githubusercontent.com/51679834/136013941-53906de9-b666-4805-852
> > 
> > 
> > Do i need the ubutu to run it or is it working fine now?
> 
> As of now, its still not working in Windows 10 for me. I'm using linux to keep my alts online.
> 
> **How to get it working in Windows 10 (for now)**
> 
> * Install Virtualbox in Windows
> * Install Ubuntu (or any linux distro you prefer) inside Virtual box
> * Load Ubuntu, install Mono
> * Copy your mcc files over to Ubuntu (using shared folders in Virtualbox)
> * Open Terminal, cd to your mcc directory, type : mono MinecraftClient.exe
> 
> (Apologies for the amount of edits, I tried to tidy up my reply)

i have a question for the problem when it is fixed can i run a vpn on my virtual box and no vpn on windows

**Comment by UniqueNIHAL** [comment]
I cannot get this to work can someone explain me?

**Comment by ORelio** [comment]
Hi everyone,

I'm glad to see that so many people are using Minecraft Console Client.
Maybe a bit less glad to see that people remember about the repository only when something is broken 😜
Anyway, I've added the same hotfix as in #1774 but for Mojang API this time, so it should be fixed in the [latest build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

Some people noticed Linux or Windows Subsystem for Linux (WSL) were not affected. That's because the Mono framework handles TLS 1.2 out of the box, while .NET framework has it disabled by default for apps targeting an older version of the framework. The fix simply tells .NET framework to use TLS 1.2 regardless of default settings. This will not work under old Windows versions such as XP SP3 but will be fine if you have a newer .NET version installed on your system. Work is in progress for properly porting MCC to the newer .NET 5.0 but that is a big project and will take a while (#1674)!

Meanwhile, enjoy the fix 😉
