### ISSUE TITLE
Minecraft Login Failed : SSL Error

### ISSUE THREAD

**Issue by jcodyparker** [ORelio/Minecraft-Console-Client#1782]
Works fine playing the game on the Minecraft launcher, won't log in anymore on Console Client. Even tried deleting all config and making a new console client with everything default, still does the same thing.

![image](https://user-images.githubusercontent.com/90956620/135971130-e7d48294-b704-4111-89c0-86d258c77ba0.png)

**Comment by DemonAKALilKid** [comment]
isn't this a clone of #1781 ?

**Comment by jcodyparker** [comment]
> isn't this a clone of #1781 ?

ah ok didnt see others were having the same issue

**Comment by ReinforceZwei** [comment]
Closing as duplicate of #1780.
