### ISSUE TITLE
Characters not showing properly

### ISSUE THREAD

**Issue by TheFluffyWalrus** [ORelio/Minecraft-Console-Client#180]
Characters like ▲►▼◄ ❤ ˘ ³ ˘ ಠ ω ツ ★  三 彡 ☣ are showing up as question marks in chat just makes chat look very ugly didnt know if you could add support for UTF-8

**Comment by ORelio** [comment]
Minecraft Console Client supports UTF-8, Windows CMD does not.
Just use better console such as [Cmder](http://cmder.net/) or maybe the built-in from Windows 10 although untested :wink:
