### ISSUE TITLE
[BUG] There is a problem displaying characters on Linux

### ISSUE THREAD

**Issue by horizon86** [ORelio/Minecraft-Console-Client#1808]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.1

### Console Client Version

Latest(AppVeyor build 527, built on Tue 10/05/2021 from commit bb4c131)

### Expected Behavior

Show Chinese rightly.

### Actual Behavior

Some words cannot be displayed normally include Chinese words and English.

### Steps to Reproduce the bug

1. Connect to a server which send Chinese.

### Attach screenshot here (If applicable)

![pic1](https://raw.githubusercontent.com/horizon86/horizon86.github.io/72e0fa29169aa488e3d6635e6f88fe1c7632654b/assets/img/picbed/pic1.png)

### Anythings that could help diagnosing the bug

```txt
This is not a serious problem, and it runs normally on windows and displays normally on Android using pickaxechat app.
I am running on Centos 7 and use tmux to keep mcc running.
```

### Device

VPS

### Operating System

Linux

**Comment by milutinke** [comment]
Can you test this out with the latest release, since the MCC now uses ConsoleInteractive?
