### ISSUE TITLE
Auto-feed script??

### ISSUE THREAD

**Issue by KurzPhilipp** [ORelio/Minecraft-Console-Client#181]
Is there a script i can use to autofeed. Without using /feed etc.

**Comment by ORelio** [comment]
Currently using items in your inventory is not handled.

**Comment by ORelio** [comment]
Could feeding be achieved though `/useitem`?

**Comment by ORelio** [comment]
Indeed, `/useitem` with food in hand works. Use `/inventory player` to locate food in hotbar, `/changeslot <slot>` to select food, then `/useitem` to use the food. Closing this thread as resolved.
