### ISSUE TITLE
MCC Gui CPU 100%

### ISSUE THREAD

**Issue by TNTUP** [ORelio/Minecraft-Console-Client#182]
When I launch the GUI, as soon I type the user/pwd/IP the CPU usage goes at 100% (the GUI itself) so I stopped using this but I guess its not worth fixing it?

**Comment by ORelio** [comment]
Strange, I'll try to reproduce. The GUI is pretty old but at least let's keep it usable :sweat_smile:

**Comment by TNTUP** [comment]
I've rarely used it but I've noticed it goes up at 100% xD Probably none reported that issue since none uses it x)

**Comment by ORelio** [comment]
There must be an infinite loop somewhere.

**Comment by ORelio** [comment]
Could not reproduce
