### ISSUE TITLE
Interact with world (placing blocks, right-clicking, opening chests)

### ISSUE THREAD

**Issue by Dodecane** [ORelio/Minecraft-Console-Client#183]
Just asking, is there a way to implement world interaction such as placing blocks, right-clicking npc players and opening chests?

**Comment by ORelio** [comment]
Yes, that's just currently not implemented.
 - placing blocks
   - terrain is handled
   - inventory is not handled
 - right-clicking NPC
   - entities are not handled
 - opening chests
   - inventories are not handled

Once the required items are all handled, then the "block place"/"right click" messages can be sent to the server (protocol: http://wiki.vg/Protocol)

**Comment by ORelio** [comment]
Hi,
Inventories are handled in the newest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) thanks to @ReinforceZwei 's work.
It is currently not possible to interact with a chest but you can now list what is in your inventory and click on items in GUI menus.

**Comment by ORelio** [comment]
Since `/entity use` has been implemented, all the requested features here are now supported 🥳
