### ISSUE TITLE
Restrict PM matches to bot owners

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#184]
I have every thing all set up but when it gets a message it just says "Detected HI Message" It doesnt auto send back hi

**Comment by ORelio** [comment]
Could you please copy you INI file for matches? (default name: `matches.ini`)

**Comment by AppleCidar** [comment]
[Match]
match=Payme
actionprivate=send /pay $u 1000000

**Comment by ORelio** [comment]
This file works well on my side.
Make sure matches are enabled and chat messages are [properly detected](https://github.com/ORelio/Minecraft-Console-Client/blob/67fc431d4a053fa09f67e754224d9ba4850ef735/MinecraftClient/config/README.txt#L150).
Please also note that this "payme" command would be available even for non-botowners users.

**Comment by AppleCidar** [comment]
Ya, I got it to work. It seemed that the chat log was interfering with the auto respond. Also I found out last night that it doesn't work on only bot owners. Is their a way I can make it only work on botowners?

**Comment by ORelio** [comment]
No way, but now yes you can using the new `ownersonly=true` setting in your `matches.ini` ;)

**Comment by ORelio** [comment]
(My bad, forgot to add relevant files, this time it's added)

**Comment by AppleCidar** [comment]
Thank you so much! I am going to close this now that the answer is complete! Thanks again :)
