### ISSUE TITLE
[Request] 1.10.2

### ISSUE THREAD

**Issue by sammyvsparks** [ORelio/Minecraft-Console-Client#186]
I noticed that some servers that run 1.10.2 I cannot connect to since the client natively supports 1.10.0

rsmv.net was my main reason for getting this, but as I cannot join, it seems kind of pointless.

**Comment by ORelio** [comment]
1.10.0 and 1.10.2 use the same protocol. Your issue is the same as #51 : `rsmv.net` is not the server IP, some Minecraft servers use a load balancing protocol in DNS protocol not understood by Minecraft Console Client. Eg `149.56.28.155:25565` is server IP for Lobby 5. You can use it to join.

**Comment by ORelio** [comment]
Hello,
Just to let you know, the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) automatically handles DNS redirections.
So you can input `rsmv.net` in it, and MCC will find out the real address `play.rsmv.net:25565` :)
