### ISSUE TITLE
A way to get back on the server after getting kicked to hub.

### ISSUE THREAD

**Issue by YanderePepe** [ORelio/Minecraft-Console-Client#187]
So basically the server I afk on restarts after a while. I want to know if there is a way to send a specific command in case I get kicked due to the restart. The command should be /server.

**Comment by Pokechu22** [comment]
You can do `/reco` (short for reconnect) to rejoin the server.  Does that what you need to do?

**Comment by KurzPhilipp** [comment]
Sadly thats not what i'm looking for. I need the bot to reconnect automatically if/when i get kicked to hub.

**Comment by ORelio** [comment]
If there is a specific message appearing in chat, juste use [`AutoRespond`](https://github.com/ORelio/Minecraft-Console-Client/blob/67fc431d4a053fa09f67e754224d9ba4850ef735/MinecraftClient/config/README.txt#L206) with a See also: [`matches.ini`](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-matches.ini) file eg to react to `You were moved to hub` with `reco` or `send /server <myserver>`... and you're done ;)
