### ISSUE TITLE
Client doesnt work?

### ISSUE THREAD

**Issue by YanderePepe** [ORelio/Minecraft-Console-Client#188]
So basically. I start the client. The credentials work etc. But somehow it doesn't run.
Screenshot of what is happening.
http://prntscr.com/c9k6zx

Edit: It doesn't let me write anything.

**Comment by ORelio** [comment]
You are using an old version: 1.8.0
Please retry with latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and let me know if this still happens.

**Comment by YanderePepe** [comment]
I got the latest version of the Minecraft forums account. For a second that worked. But then it stopped again. After that i got the development version and it says this:

http://prntscr.com/c9kmnx

**Comment by IRTHATDUDE** [comment]
same issue here

**Comment by ORelio** [comment]
Well that's pretty clear: it cannot connect to the requested IP address. Maybe you're having #186 in that case follow method from #51 to get actual IP address :wink:

**Comment by ORelio** [comment]
This issue should be properly resolved now since MCC can read SRV records from DNS. See #253 :)
