### ISSUE TITLE
Tasks dont work.

### ISSUE THREAD

**Issue by YanderePepe** [ORelio/Minecraft-Console-Client#189]
I have all my task on trigger on first login, and interval. Yet non of them work. They worked on the older version.

**Comment by ORelio** [comment]
Haven't touched tasks in a while.
Which older version? Which current version?
Are you sure ScriptScheduler is enabled in INI file?

**Comment by YanderePepe** [comment]
O I completely forgot to turn on script scheduler in the new version.  My bad.

**Comment by ORelio** [comment]
Well, at least, problem solved :sweat_smile:
