### ISSUE TITLE
Reconnect failure

### ISSUE THREAD

**Issue by dbear20** [ORelio/Minecraft-Console-Client#19]
When the server i play on restarts in the morning its down longer than the 10sec that the relog bot waits so when it tries to connect it gets a failed to ping ip message. Upon doing the /reco command to restart the program it crashes. I originally discovered this on my fork of the code and i decided i should try in the original code to see if its something i caused, i can report that it was not any of my changes. [Here](http://pastebin.com/qrwq1U4Y) is the exception detail i was able to gather, i would takle this my self but once again this is over my head.

**Comment by ORelio** [comment]
The issue did not reappear so it seems that fixes have worker. Closing for now.
