### ISSUE TITLE
Relog

### ISSUE THREAD

**Issue by YanderePepe** [ORelio/Minecraft-Console-Client#190]
Is there a way i can make the autorelog feature run a script when its suppose to relog? I need it because the server i play on regularly restarts. And when it does that i get returned to the hub. I need the bot to say /server survival whenever that happens.

**Comment by AppleCidar** [comment]
Just make a .txt script
Do
`Send /Server Survival`
put that In the .txt file. Then use the task manager and put 
`[Task]
triggerOnInterval=true
timeInterval=60
script=test.txt`

**Comment by ORelio** [comment]
You can use `triggerOnLogin` instead of `triggerOnInterval`.
That way it runs a script upon joining the server.

**Comment by AppleCidar** [comment]
**ORelio**, That would work but when you get kicked to the hub it doesn't run the command. It only runs the command on first login therefor i would use the `triggerOnInterval`

**Comment by ORelio** [comment]
In that case you can detect eg `You were moved to hub` using AutoRespond, then run a script which waits a while ans perform thé command. Of course runnig it on a time interval using ScriptScheduler or AntiAFK would also work, I guess.

**Comment by YanderePepe** [comment]
I got it to work, but it only works on the first time i log in. I added the triggerOnInterval line but the script wont run. I checked to see that my script scheduler was turned on and it was. What do i do.

**Comment by ORelio** [comment]
If I remember well, you cannot use both `triggerOnInterval` and `triggerOnLogin` on the same `[Task]`.
Also, if it runs only on first login maybe you are using `triggerOnFirstLogin` instead of `triggerOnLogin`?
