### ISSUE TITLE
Regex won't work in match file.

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#191]
I am trying to make it so it can read the message but the server i play it has a different chat format so i tried to use the regex method. but its still not working! Link to the regex: https://regex101.com/r/zP8tO3/2
My Code
`[Match]`
`ownersonly=true`
`regex=^([a-zA-Z0-9_]+ » [a-zA-Z0-9_]+ »)(.+)$`
`actionprivate=send /pay $u 1000000`

**Comment by ORelio** [comment]
That was close! Your parenthesis is misplaced. Your regex
````
^([a-zA-Z0-9_]+ » [a-zA-Z0-9_]+) »(.+)$
````
The parenthesis delimits what should be matched so what you want is `AppleCidar` not `AppleCidar » You`
So simply move the parenthesis:
````
^([a-zA-Z0-9_]+) » [a-zA-Z0-9_]+ »(.+)$
````

**Comment by AppleCidar** [comment]
Oh, okay Thanks again! :p

**Comment by AppleCidar** [comment]
Hey, i thought this would fix it but it still isnt working. It wont detect the word i need it to look like this in chat. https://gyazo.com/84c23514eafea97f43237d212528052b

**Comment by ORelio** [comment]
MinecraftClient.ini
````ini
[Main]
botowners=AppleCidar
````
````ini
[ChatFormat]
builtins=false
public= # TODO: Fill (haven't seen public msg sample from your server)
private=^([a-zA-Z0-9_]+) » [a-zA-Z0-9_]+ » (.+)$
tprequest= # TODO: Fill (same here)
````
````ini
[AutoRespond]
enabled=true
matchesfile=matches.ini
````

matches.ini
````ini
[Match]
match=payme
actionprivate=send /pay $u 1000000
ownersonly=true
````

**Comment by AppleCidar** [comment]
Mine looks the same but still doesn't work.. But thanks for helping it must just be the server format because it worked on other servers! Thanks for you help! :)

**Comment by ORelio** [comment]
Make sure messages are detected using the `sample-script-with-chatbot.cs` which simply states there is a public or private message. Then, if it works, make sure bot owners work by trying to enable Remote Control. Finally, if it works, make sure AutoRespond works by adding something like:
````ini
[Match]
match=joined
actionother=log `someone joined the game.`
````
Actionother will work for anything other than a chat format so let's detect if someone joined the game.

**Comment by AppleCidar** [comment]
All of that worked! So it is just the chat format. :(

**Comment by ORelio** [comment]
Does `sample-script-with-chatbot.cs` properly print private messages?
If so, the chat format is properly handled by the regex.

**Comment by AppleCidar** [comment]
[MCC] [ExampleBot] Sucessfully Initialized!
Thats what i get but it does not send any msgs

**Comment by AppleCidar** [comment]
Found a problem! 
`AppleCidar » You » payme`
`[MCC] [AutoRespond] send /msg  hi`
`Incorrect usage! /msg <player> <message>`
It isnt getting the user when i did `actionother=send /tell $u hi`
so chat format is wrong because it is picking up a space and not the name

**Comment by AppleCidar** [comment]
or is $u not supported with actionother?

**Comment by ORelio** [comment]
Of course it is not supported. "Other" chat messages are for system messages such as "You have no new mail". There is no regex step to extract username so there is no $u.
What is your INI configuration for chat messages?

**Comment by AppleCidar** [comment]
It is pure vanilla except the private messages.

**Comment by ORelio** [comment]
Your setting `private=` is commented... Remove the `#` character...

**Comment by AppleCidar** [comment]
Ya it works :) thanks

**Comment by ORelio** [comment]
Yay, finally 😂 :tada:

**Comment by AppleCidar** [comment]
Haha ya, if I just read your comment

**Comment by shop10** [comment]
Hi, i'm trying to make a alarm system when a person in a shop takes too many shit, he gets kicked, but it doesnt work (here is my regex)

```
[Match]
regex=^(?:.*)\[Shop\] (.*) bought 1 (.*) for \$\.00 from you\.$\n(?:.*)\[Shop\] \1 bought 1 \2 for \$\.00 from you\.$
action=send /is expel \1
```

**Comment by ORelio** [comment]
@shop10 Have you tested your regex on https://regex101.com ?
