### ISSUE TITLE
Console Clients on a  VPS

### ISSUE THREAD

**Issue by ImProLeader** [ORelio/Minecraft-Console-Client#193]
I recently got a VPS with ovh with putty. I got the jist of things but when i do, mono MinecraftClient.exe it crashes. Not sure how to fix it but i have been trying to for a while now. Any help/idea on what i can do?

**Comment by ImProLeader** [comment]
at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server.
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x

**Comment by ORelio** [comment]
[`README`](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/README.txt#L18)
````
If you cannot authenticate on Mono, you'll need to run "mozroots --import --ask-remove" once.
````

**Comment by ImProLeader** [comment]
Yes i have, i have been reading other posts of what others have been saying about this and i still cant seem to get this fixed. 

Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-8+deb7u1)
Copyright (C) 2002-2011 Novell, Inc, Xamarin, Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            Included Boehm (with typed GC and Parallel Mark)


this is my version where can i get 4.0-4.2?

**Comment by ImProLeader** [comment]
this is what comes up when i do mozroots --import --ask-remove
Mozilla Roots Importer - version 2.10.8.1
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
Couldn't retrieve the file using the supplied information.

**Comment by ORelio** [comment]
Oh. This version is probably too old, and certificate URL may have changed. Even when I was developing support for Mono, it was already in `3.X` version, not `2.X`. Easiest way is upgrading the VPS OS because repositories should not contain such an ancient version. If you already have stuff on it and cannot easily upgrade, refer to http://www.mono-project.com/download/#download-lin (beware, Mono 4.4 started rejecting SHA-1 certificates but the current root certification authority used to sign Mojang's certificate is SHA-1 only, so make sure to grab v4.0-4.2 to make sure it works as expected)

**Comment by ImProLeader** [comment]
Think you can get me a direct download to 4.0-4.2? having trouble finding the right one.

**Comment by ORelio** [comment]
Seems like you're running Debian Wheezy.
https://packages.debian.org/search?keywords=mono-complete
Using Stretch repositories you can have version 4.1

**Comment by ImProLeader** [comment]
Thank you. I will give this a try

**Comment by ImProLeader** [comment]
Can't seem to find the DL link for this.

**Comment by ORelio** [comment]
You'd need to use backports: https://backports.debian.org/Instructions/
See `wheezy-backports-sloppy` for packages from `testing (stretch)` for `oldstable (wheezy)`.
If you have further questions I'm afraid I haven't had to install backports myself so din't test.

**Comment by BlueDemonic** [comment]
did this work cause im in the same boat
