### ISSUE TITLE
Logging session 

### ISSUE THREAD

**Issue by ImProLeader** [ORelio/Minecraft-Console-Client#194]
Version is supported.
Logging in...
Checking Session...
Login failed :
Failed to check session.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

Why do i keep getting this message after trying to log into console client in my vps, is this based on my connection? Password/user is correct also.

**Comment by ORelio** [comment]
1. Please set debugmessages=true in your INI file
2. Ensure you are running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
3. Report again as much details as you can :)

**Comment by ImProLeader** [comment]
I will!

**Comment by ImProLeader** [comment]
Also any way to auto start a script on login :p

**Comment by ORelio** [comment]
[Yes](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini#L11)

**Comment by ImProLeader** [comment]
Also any way to send 2 commands on the anti afk instead of 1?

**Comment by ORelio** [comment]
Simply use a script with 2 commands and run it on time interval ;)

**Comment by ImProLeader** [comment]
But wouldn't I have to type if manually to start the script :p

**Comment by ORelio** [comment]
Absolutely not, use ScriptScheduler for that, same way as script on login, but it also handles script on interval (see [here](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini#L13)).

**Comment by ImProLeader** [comment]
Thank you so much. I will mess with it when I get home!

**Comment by ImProLeader** [comment]
Any way I can get in contact with you on skype or something?

**Comment by ORelio** [comment]
I'm not available enough on skype to respond on a timely manner, better use GitHub issues or PM on Minecraft Forum since there are email notification that way :wink:

**Comment by ImProLeader** [comment]
Thank you :D
