### ISSUE TITLE
Cannot authenticate with Mono

### ISSUE THREAD

**Issue by BlueDemonic** [ORelio/Minecraft-Console-Client#196]
i did these steps below but every time i try to open a mc account up it says wrong password or login failed pls help 
On Mac or Linux, open a terminal in this folder and run "mono MinecraftClient.exe".
If you cannot authenticate on Mono, you'll need to run "mozroots --import --ask-remove" once.

**Comment by ORelio** [comment]
Hello,
Maybe there are some special characters not properly handled in your password.
Try setting it in INI file, or authenticating on Windows, or using a test password with A-Za-z0-9 charset.
Also, are there more details? There is a debug setting in INI file that you can turn on.

**Comment by ORelio** [comment]
Due to lack of feedback I'll assume the issue is now resolved. Feel free to reopen if needed.
