### ISSUE TITLE
Running multiple commands to log in

### ISSUE THREAD

**Issue by TropicalMirage** [ORelio/Minecraft-Console-Client#197]
I am currently trying to log in to a server to afk for me.  However, I need to run multiple commands within minecraft to get to my afk spot.
I need it to log in, run /server Skyblock2, then do /is warp [a playername].
I can't find this anywhere.
Secondly, when I log in, the account floats in midair, and does not get moved by water or anything.
If you can help me solve these problems in your own words with super dumbed-down steps, that would be amazing.  Thanks!!
-Tropical

**Comment by ORelio** [comment]
1) Write a [script file](https://github.com/ORelio/Minecraft-Console-Client/blob/9a98a9d46f93ccfd91c720d956cd8dd45b440e2c/MinecraftClient/config/README.txt#L101) with all your [send /mycommand](https://github.com/ORelio/Minecraft-Console-Client/blob/9a98a9d46f93ccfd91c720d956cd8dd45b440e2c/MinecraftClient/config/README.txt#L63) instructions
2) Schedule your script file using [ScriptSheduler](https://github.com/ORelio/Minecraft-Console-Client/blob/9a98a9d46f93ccfd91c720d956cd8dd45b440e2c/MinecraftClient/config/README.txt#L188) on [every login](https://github.com/ORelio/Minecraft-Console-Client/blob/9a98a9d46f93ccfd91c720d956cd8dd45b440e2c/MinecraftClient/config/sample-tasks.ini#L30) to the server.
3) You might want to actually read the whole [README](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/README.txt) file to know every feature offered by the program.

**Comment by ORelio** [comment]
All questions should have been answered now, so closing the issue. Feel free to reopen if needed.
