### ISSUE TITLE
Script Force-Stop

### ISSUE THREAD

**Issue by ReOp14** [ORelio/Minecraft-Console-Client#198]
Okay so I have learned a ton with C# and it gets very interesting, but very complex at the same time.
Here is my problem:

//MCCScript 1.0
for (int test = 0; test < 10; test++)
{
MCC.SendText("test");
Thread.Sleep(1000);
{
int count = MCC.GetVarAsInt("time");
MCC.SendText("Seconds: " + count);
Thread.Sleep(1000);
}}

I need a way to stop the script at any time so it wont go for the 10 times, and this script does work as intended so far. I tried putting "int test = MCC.GetVarAsInt("flower");" right below MCCScript to make it a variable (so that I can stop it using "/set flower=10" in console) but I get an error that says you can't use it because its an integer.

Is there a way to stop the script from running or can you add a command in your next update to force-stop a script? ex: /stop (script name)

**Comment by ORelio** [comment]
Just use a `return;` statement.
And add `return;` at the end of the script so that every path leads to a return statement.
Regarding the error you are facing, could you paste the exact error message?

**Comment by ReOp14** [comment]
Yeah, the error says: 
A local variable named 'test' cannot be declared in this scope because it would give a different meaning to 'test', which is already used in a 'parent or current' scope to denote something else

I don't really understand what return; does, but wherever I put it gives this error:
System.InvalidOperationException: An object of a type convertible to 'object' is required 

I need a command to stop the script whenever, without restarting the client. Im sure its somehow possible to make the console command /set to somehow work.

**Comment by ORelio** [comment]
Okay so:
````
 A local variable named 'test' cannot be declared in this scope because it would give a different meaning to 'test', which is already used in a 'parent or current' scope to denote something else
````
Explanation: You cannot define "test" twice eg this is invalid:
````C#
bool test = false;
for (int i = 0; i < 10; i++)
{
    bool test = i < 5; //Invalid. Cannot redefine test
}
````
And this is valid:
````C#
bool test = false;
for (int i = 0; i < 10; i++)
{
    test = i < 5; //We assign the existing 'test' variable
}
````

Regarding this error:
````
 System.InvalidOperationException: An object of a type convertible to 'object' is required
````
My bad, let's explain what `return` does with the following function:
````C#
public static int add(int a, int b)
{
    return a + b;
}
````
The `return` statement is used to return a value from a function.
You can use `return;` for exiting early a function that returns nothing (a `void` return type).
However MCC builds a function like this internally from your script contents:
````C#
public static object Run(string[] args)
{
    //Your script contents below //MCCScript 1.0 and before //MCCScript Extensions
    return null; //Automatically inserted if the script has no return statement
}
````
So to exit early the easiest way is using `return null;` (not `return`, sorry).
And when you start using `return` statements, then you have to add a final `return null;` yourself ;)

**Comment by ReOp14** [comment]
Thanks so much for your help. I made this:
//MCCScript 1.0
for (int test = 0; test < 10; test++)
{
MCC.SendText("test");
Thread.Sleep(1000);
{
int count = MCC.GetVarAsInt("time");
MCC.SendText("/bc Seconds of Uptime: " + count);
Thread.Sleep(1000);
{
int end = MCC.GetVarAsInt("end");
if (end == 1)
MCC.SendText("Ending.");
return null;
}}}
return null;

At first when I looked at your answer I was clueless, but I looked it over a few times and I understood it more clearly. To stop it, I use "/set end=1" to make the script stop.

One thing I couldn't do which felt like a bug, when I replace "MCC.SendText("Ending."); with "MCC.PerformInternalCommand("set end=0");" the script seems to not work after it sends both chat messages and it dosn't matter if end=1 or end=0.

**Comment by ORelio** [comment]
The braces for `Thread` statement are not useful, and you need braces for your `if` condition.
Here is a more readable version with `if` condition improved:
````C#
//MCCScript 1.0
for (int test = 0; test < 10; test++)
{
    MCC.SendText("test");
    Thread.Sleep(1000);
    int count = MCC.GetVarAsInt("time");
    MCC.SendText("/bc Seconds of Uptime: " + count);
    Thread.Sleep(1000);
    if (MCC.GetVarAsInt("end") == 1)
    {
        MCC.SendText("Ending.");
        return null;
    }
}
return null;
````
With your version, `return null;` is reached regardless of the value of the result of the test.
I'd highly recomment to add an indentation level inside braces for better readability ;)

**Comment by ReOp14** [comment]
Thanks so much! I got everything working for now. Really love using your MCC Bot!

Much Appreciated!

**Comment by ORelio** [comment]
Let me know if you have further issues ;)
