### ISSUE TITLE
Send Text With Quotes

### ISSUE THREAD

**Issue by ReOp14** [ORelio/Minecraft-Console-Client#199]
Hey, Another quick question. Probably the most simple question ever, but that's probably alright.
`MCC.SendText("Hello, you can't put "quotes" inside of quotes.")`

Gives this error: "System.InvalidOperationException: ) expected"
Yeah, how do you put quotes in SendText without receiving an error?

**Comment by Pokechu22** [comment]
You need to escape the quotes with a backslash:

     MCC.SendText("Hello, you can't put \"quotes\" inside of quotes.");

Otherwise it thinks that you're ending the message after "Hello, you can't put " and then sees `quotes` and has no idea what to do with it.

**Comment by ReOp14** [comment]
I thought it could be something like that, Thanks pokechu22.
