### ISSUE TITLE
Caculator Decimals

### ISSUE THREAD

**Issue by ReOp14** [ORelio/Minecraft-Console-Client#200]
Ok, so I made this calculator and it works great and I love it. 
With my matches file you can ask it "Whats 1 + 2" and it will say "Solution: 1 + 2 = 3".
```
//MCCScript 1.0
int op = MCC.GetVarAsInt("op");
int cac = MCC.GetVarAsInt("cac");

for (int i = 0; i < 1; i++)
{	
	if (cac > 0)
	{
		if (op == 1)
		{
		int math2 = MCC.GetVarAsInt("math2");
		int math1 = MCC.GetVarAsInt("math1") + math2;
		int math3 = MCC.GetVarAsInt("math3") + math1 - math2;
		MCC.SendText("Solution: " + math3 + " + " + math2 + " = " + math1);
		}
		if (op == 2)
		{
		int math2 = MCC.GetVarAsInt("math2");
		int math1 = MCC.GetVarAsInt("math1") - math2;
		int math3 = MCC.GetVarAsInt("math3") + math1 + math2;
		MCC.SendText("Solution: " + math3 + " - " + math2 + " = " + math1);
		}
		if (op == 3)
		{
		int math2 = MCC.GetVarAsInt("math2");
		int math1 = MCC.GetVarAsInt("math1") * math2;
		int math3 = MCC.GetVarAsInt("math3") + math1 / math2;
		MCC.SendText("Solution: " + math3 + " * " + math2 + " = " + math1);
		}
		if (op == 4)
		{
		int math2 = MCC.GetVarAsInt("math2");
		int math1 = MCC.GetVarAsInt("math1") / math2;
		int math3 = MCC.GetVarAsInt("math3") + math1 * math2;
		MCC.SendText("Solution: " + math3 + " % " + math2 + " = " + math1);
		}
	}
	if (cac < 1)
	{
		MCC.SendText("Caculator is currently toggled off.");
		return null;
	}
}
return null;
````

Although its good, it doesn't support **decimals**. Is it possible to add decimals to this calculator script I have here?

**Comment by ORelio** [comment]
You may either
 - Multiply input by 100, then divide by 100 before printing (you get 2 decimals)
 - Use a double. just added GetVarAsDouble() for you in Script API ;)

**Comment by ReOp14** [comment]
Alright, GetVarAsDouble might do the trick, Im geussing I have to update to the latest unstable version?

**Comment by ORelio** [comment]
Yes as it was just added.
If you do not wish to do that you may use GetVar() and convert it yourself to double.

**Comment by ReOp14** [comment]
Okay everything is changed and dividing works, but how do I change [This](https://regex101.com/r/gG7yI6/1) regex that is in my matches file to support decimals?

**Comment by ORelio** [comment]
Like this? https://regex101.com/r/gG7yI6/2

**Comment by ReOp14** [comment]
Yeah like that, except how do you input negative into that? (I had negatives already in the [Regex](https://regex101.com/r/gG7yI6/1) before.)

**Comment by ORelio** [comment]
Added back: https://regex101.com/r/gG7yI6/3

**Comment by ReOp14** [comment]
Yeah that solves the problem, Thanks so much! Now people can ask the account a math question and it will answer more accurately!

**Comment by ORelio** [comment]
That's a nice usage of MCC scripts, well done :+1:

**Comment by ReOp14** [comment]
Having another issue with calculator Regex. This is my [regex](https://regex101.com/r/fO0nX5/1). 
I want to make it so you can **also** say "Whats 9.5+10.5?"  (no spaces in between numbers and plus)

My attempt at this was [this](https://regex101.com/r/fO0nX5/4). The problem with this is if you **add** decimals to the second number it will **break** the regex. I don't think negatives break the regex.

How do you fix [this regex](https://regex101.com/r/fO0nX5/3) so it matches the numbers correctly?

**Comment by ORelio** [comment]
Use my last regex and add question marks after spaces: ` ` -> ` ?` to make them optional.

**Comment by ReOp14** [comment]
`^(?!AntzBot)(?:.*[^0-9\.])([0-9\.]+) ?(?:\W|x|X) ?([0-9\.]+).*` I put ?s after the spaces and I get the same result.

**Comment by ORelio** [comment]
Like this? https://regex101.com/r/gG7yI6/4
This matches both with and without spaces.

**Comment by ReOp14** [comment]
Yeah except it needs to work with decimals. https://regex101.com/r/gG7yI6/5

Also, in the Older regex, https://regex101.com/r/fO0nX5/3 the point of `(?<!\w)` is to require a space in front of the first number.
 I need this because when a player is killed by another player in chat on a game such as Survival Games, it says in chat: "..Player ReOp725 + 1 was killed by DeOp.." If a person has a number at the end of their name it, the calculator tries to calculate 725 + 1 (the one means 1 assist)

**Comment by ORelio** [comment]
Ok so your `?(?:\W|x|X)` allows the `.` character, that's why decimals are not properly matched.
Manually looking for an operation set: `*+-/%` avoids matching the dot here.
Then, adding dots in number matching parts should do the job.
Here: https://regex101.com/r/gG7yI6/6

**Comment by ReOp14** [comment]
Okay perfect! One last thing.. https://regex101.com/r/gG7yI6/7 
What if someone says "-81 + 22.5?"
(So if someone doesn't put a space in the slot?)

**Comment by ReOp14** [comment]
I solved my own problem. https://regex101.com/r/gG7yI6/9
`^(?!AntzBot)(?:.*[^-a-zA-Z0-9\.])?([-0-9\.]+) ?[+\-*%xX] ?([-0-9\.]+).*$`
Also, I am still wondering about the [Welcome Message issue](https://github.com/ORelio/Minecraft-Console-Client/issues/202) i posted a few days ago.

**Comment by ORelio** [comment]
Oh, missed your post about missing spaces. Well at least you solved it :sweat_smile:
