### ISSUE TITLE
Feature Request: Inventories & Block Placing/Breaking

### ISSUE THREAD

**Issue by AndrewMast** [ORelio/Minecraft-Console-Client#205]
It would be AWESOME if you can make it process inventories: get slot items (array), and put stuff in slots (from personal inventory), and click on slots

**Comment by ReOp14** [comment]
Yeah, it would be pretty cool if there was a development of some inventory processing. However, there is no code ORelio can use to add this ability as far as I know.

**Comment by AndrewMast** [comment]
I don't get it?

**Comment by Pokechu22** [comment]
Inventory management is difficult to write: you have to handle [all types of inventories](http://wiki.vg/Inventory); process a bunch of packets ([close window clientbound](http://wiki.vg/Protocol#Close_Window_.28clientbound.29), [open window](http://wiki.vg/Protocol#Open_Window), [window items](http://wiki.vg/Protocol#Window_Items), [set slot](http://wiki.vg/Protocol#Set_Slot), [confirm transaction clientbound](http://wiki.vg/Protocol#Confirm_Transaction_.28clientbound.29), [confirm transaction serverbound](http://wiki.vg/Protocol#Confirm_Transaction_.28serverbound.29), [click window](http://wiki.vg/Protocol#Click_Window), [close window](http://wiki.vg/Protocol#Close_Window_.28serverbound.29), [creative inventory action](http://wiki.vg/Protocol#Creative_Inventory_Action), and probably others for things I'm not thinking of); handle displaying the actual items (which is particularly hard when you consider the way items are named is somewhat arbitrary and can vary by metadata); and even just displaying it into the console in a useable way.  It's not impossible (other clients do implement it), but it does make things difficult and there are a bunch of weird special cases.

**Comment by AndrewMast** [comment]
I get that outputting it for the console itself would be hard, but what I'm asking is for the inventory data to be accessible for a script file.

**Comment by Pokechu22** [comment]
Ah, in a script is easier to implement, though the number of packets still does make it difficult.

**Comment by ORelio** [comment]
Well, inventory handling is already on my TODO list but as @Pokechu22 said that would require a lot of work, if that was not the case, I would already have done it :laughing:

**Comment by MattCowley** [comment]
Any eta for either part?

**Comment by ORelio** [comment]
Nope, sorry. Don't have time to work on this.

**Comment by azoundria** [comment]
I think if you could have a simple /drop [#] command, where [#] is the hotbar slot, that would be useful. You could assume the end user already knows ahead of time what item they put in which hotbar slot, and since it's just the hotbar you wouldn't have to open any windows. How much complexity would be involved in something like that?

**Comment by TheSnoozer** [comment]
As per https://github.com/ORelio/Minecraft-Console-Client/issues/305

```
Hello,

The main issue with block breaking/placing is that #205 would need to be implemented first. Of course, breaking a block does not necessarily requires handling inventory, but handling inventory would allow selecting the right tool to break the block.

Breaking block could be implemented separately if you need it, but to do it properly, digging times would need to be implemented, also the player head would need to be rotated to look at the target block. Failing to implement head movements and digging times would trigger anti-cheat plugins on many servers. Also, the necessary bot API method(s) would need to be added in order to enable bots to break blocks :)

Breaking sugar cane is simple indeed as no block break delay is necessary, still, it requires at least looking at the sugar cane and sending the packet. Plus some testing, I guess. So the necessary work would be the following:

1/ Implement ability to look at specific block coordinates (compute & send packet)
2/ Implement ability to send block break start & block break end (with auto-send block break end at a later time computed depending on block type...!)
3/ Implement ChatBot method to tell the bot to break a block at the specified location, which would automatically check if this is feasible (block near enough & visible to the player) and do the actual thing

There are lots of "would" in this message as I'm not having enough time to work on all of this myself at the moment, I can however provide guidance if you are willing to contribute to the project slightly_smiling_face
```

**Comment by ORelio** [comment]
Hi,
Inventories are handled in the newest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) thanks to @ReinforceZwei 's work.
It is currently not possible to place blocks but you can now list what is in your inventory and click on items in GUI menus.

**Comment by ORelio** [comment]
MCC is now able to place blocks thanks to @Nekiplay's and @ReinforceZwei's work.
This is mainly done from the Script API, [TreeFarmer.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/TreeFarmer.cs) making a good example.
I think we can finally close this issue 👍

**Comment by hou0122** [comment]
> Hi,
> Inventories are handled in the newest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) thanks to @ReinforceZwei 's work.
> It is currently not possible to place blocks but you can now list what is in your inventory and click on items in GUI menus.
How to use?
