### ISSUE TITLE
Clickable links in chat?

### ISSUE THREAD

**Issue by brkmrr9** [ORelio/Minecraft-Console-Client#207]
Is it possible?

**Comment by ORelio** [comment]
A console terminal does not handle mouse clicks so... not easily :sweat_smile:

**Comment by Pokechu22** [comment]
Actually, [apparently it does](http://stackoverflow.com/a/6285501/3991344).  [Here's a sample of it in C#](https://www.medo64.com/2013/05/console-mouse-input-in-c/), and [here's another](http://stackoverflow.com/a/14606470/3991344).

That's with the windows command prompt; I'm not sure about other ones (or about on Linux).

**Comment by ORelio** [comment]
Yup, a platform-independent method would get tricky, was thinking about just printing URLs separately below chat messages for instance. Not sure about what is the best approach.

**Comment by ORelio** [comment]
Okay so now when links are embedded in chat MCC will print them below the message. ([dev builds](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)).
That allows clicking them if your terminal handles links, or at least copy and paste in a web browser.
````
[Announcement] Click here to visit our website!
MCC: Link: http://myawesomeserver.com/
````
Of course you can disable this using a new setting in INI file: `showchatlinks=false`
