### ISSUE TITLE
(ISP Issue) SRV

### ISSUE THREAD

**Issue by TNTUP** [ORelio/Minecraft-Console-Client#208]
Hey, I wanted to try the latest indev build and compiled, each time I launch an MCC instance, every IP I enter, it says "Resolving mcqc.ca" but I have not set any SRV on this domain. But, when it fails and log in successfully on my server, it says the remote host dasfsdfaadsf timed out.... on my ISP's DNS servers. How my domain (mcqc.ca) try to resolve SRV DNS on something in-existent? Guessing it's my ISP problem, because at my sister's home (She uses BELL) there's no issues. I'm at Videotron. Or else my ISP's DNS isn't capable of looking up SRV domains but it does work in CMD or in JAVA so idk what I did wrong?

Is there a setting to avoid waiting the timeout or a fix addressing my ISP issue without disabling the SRV feature? I've looked at the ini (default) I didn't find it how to _disable_, but that's a nice feature to have but having me to wait 10 seconds to timeout is annoying xD

Also (from another issue) the "login-error", is it possible to have it integrated or not? If not, I'd add that code snippet each time I re-compile x)

![Yeh](http://i.qcfb.ca/201610161871018.png)

**Comment by ORelio** [comment]
Well, didn't know a DNS could not respond for SRV queries while being fully functional otherwise. Are you able to connect to `rsmv.net`? (an example of server with SRV record, see issue #186)

**Comment by ORelio** [comment]
Also, which login error? Which code snippet?

**Comment by TNTUP** [comment]
@ORelio See my issue screenshot, the error is there. For the snippet code thing, its in #203. I've myself included it because Iwanted to try it xD

Tried rsmv.net, http://i.qcfb.ca/201610171797610.png (again, it's my ISP dns issue)

Should using google's DNS servers or opennic ones could solve? Because SRV domains on JAVA works fine but not in MCC :/

**Comment by ORelio** [comment]
Okay, are you able to connect to `rsmv.net` with vanilla Minecraft?
Regarding `login-error.txt` why would you need it permanently? its for a one-time debug :sweat_smile:

**Comment by ORelio** [comment]
Just added a setting for disabling SRV DNS resolving step. :wink:

**Comment by TNTUP** [comment]
Thanks! If disabled, would it still "resolve" when I enter a real SRV IP rather than a nonSRV IP? I mean, if the orelio.example.fr IS a SRV domain it will resolve but oreliotest.example.fr isn't SRV domain it ignores resolving it right?

**Comment by ORelio** [comment]
How would you know a server has an SRV record without actually trying to resolve the SRV record? :sweat_smile:

**Comment by theonlygusti** [comment]
>Just added a setting for disabling SRV DNS resolving step. 

How do I do this?

**Comment by theonlygusti** [comment]
@ORelio

**Comment by Pokechu22** [comment]
> How do I do this? 

Add `resolvesrvrecords=false` to your config.

> How would you know a server has an SRV record without actually trying to resolve the SRV record?

This might actually not be that hard - you could try connecting without SRV and if the connection fails, try connecting with SRV.  I guess there might be some cases where that wouldn't work (if it resolves as a valid server without SRV, but has multiple options with SRV) but for most cases it should be fine.  Perhaps expanding the `resolvesrvrecords` option to allow `always`, `never`, and `whenNeeded` would work well.

**Comment by theonlygusti** [comment]
@Pokechu22 

I just did that, added `resolvesrvrecords=false`, it has changed nothing #213

**Comment by Pokechu22** [comment]
Are you using the latest development build?  You need to be using the latest development build for that option to exist.

**Comment by theonlygusti** [comment]
Yes I think I am, I am using the build pointed to by @ORelio here: https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by ORelio** [comment]
Please see #213 to avoid discussing the same thing twice :laughing:

**Comment by ORelio** [comment]
@Pokechu22 : I think there is no way to properly detect if we should resolve SRV records or not except by actually trying to resolve it. Another way would be trying to connect to the IP address but there might be something responding and we would connect to something that is not the server we want :/

**Comment by TNTUP** [comment]
@ORelio There's a way to detect valid SRV domains, but slightly different and idk how it looks in c#, doing "nslookup -querytype=SRV _minecraft._tcp.<domain>... it depends....

If it detects like this: http://i.qcfb.ca/201611021770428.png, with a catch, if it finds no valid port, weight, priority and svr hostname it will detect and logging on the server http://i.qcfb.ca/201611021891328.png

Sorry my english sucks, I am french :)

**Comment by ORelio** [comment]
Pas de problème.

The `nslookup` commands allows resolving DNS records, so in fact you _are_ resolving the SRV record. ^^

**Comment by ORelio** [comment]
This issue should now be properly resolved in #253. Feel free to reopen if that's not the case :)
