### ISSUE TITLE
Player head icon in Windows 10

### ISSUE THREAD

**Issue by kotik1998** [ORelio/Minecraft-Console-Client#209]
i have set the player head icon to true, still doesnt appear on menu, 
playerheadicon=true

this feature helps me alot distnguish the players.

**Comment by ReOp14** [comment]
I have the same issue, I just never really needed the icon.

**Comment by ORelio** [comment]
This feature is only supported on Microsoft Windows, default cmd.exe

**Comment by kotik1998** [comment]
i have windows 10

**Comment by kotik1998** [comment]
any fix on that?

**Comment by ORelio** [comment]
No idea, don't have any Windows 10 setup, but that seems logical since they finally replaced cmd.exe

**Comment by kotik1998** [comment]
well, if u can get a way to put them on back i would apreciate that :)

Ps. can you show us more scripts on the consoles that we can edit ;)

**Comment by TNTUP** [comment]
@kotik1998 Have you the "modern command prompt" enabled? I had that issue earlier, I've reverted to the classic command line, open your cmd prompt or the MinecraftClient.exe, right click and click properies, then check "Use older console (needs restart" something like that and restart MinecraftClient.exe. The head should appear in the title window and in the taskbar. Or else, leave as is not touching the setting, I've made a simple script I found on the webs, you can use it if you want to generate your account's face (http://rightawake.com/tests/tntico/?n=<yournamehere>) and follow the steps. Download the ico file, make a MinecraftClient.exe shortcut, change the default icon with your head and you're done!

**Comment by kotik1998** [comment]
thanks man, worked fine :)

**Comment by ORelio** [comment]
After some research, `SetConsoleIcon` in `kernel32.dll` is undocumented and was silently removed in Windows 10 for the new console application. That means MCC cannot tell the console to update its icon with the player skin, so Windows will set the icon using MCC exe icon or shortcut icon.

**Comment by ORelio** [comment]
Unless a replacement API for `SetConsoleIcon` is added in Windows 10, this issue can't be resolved. Closing, but feel free to reopen if a replacement method exists.

**Comment by TNTUP** [comment]
I have disabled the modern console so I got it back for now XD

**Comment by ORelio** [comment]
Yes, but that's not a proper replacement method for Windows 10, you had to revert to the old console 😅

**Comment by ReOp14** [comment]
That sucks! I didn't know there was no fix. Been having this issue for a long time!

**Comment by ORelio** [comment]
A workaround (which I didn't try) might be to create a shortcut to MCC exe file and define icon in shortcut properties, but MCC itself cannot dynamically tell the new console to update the icon.
