### ISSUE TITLE
Need a way for C# scripts to reference assemblies

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#210]
I find your app wonderful and have loved writing scripts for it, but recently I ran into a problem:

I cannot find a way to reference any additional assemblies that my scripts would need, and would really like to see this functionality added :)

**Comment by ORelio** [comment]
Hello,

Would you need the equivalent to `using my.namespace.something` statements in C# files ou direct references to external DLL files? The `using` thing can be solved by using fully qualified names in scripts (I may add more references to `using` in the script engine if you need them).

However AFAIK adding references to external DLL files requires recompiling MCC.
If there is a way to dynamically load DLL files I could implement it, yes.

**Comment by theonlygusti** [comment]
I know that I can use fully qualified names and have been doing so, what I mean is that you could provide support for building with references to assemblies, perhaps by implementing some reflection-based method.

**Comment by ORelio** [comment]
The `using` statements are currently [hardcoded](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/CSharpRunner.cs#L70) but if you need them maybe the scripting feature itself could be improved to allow specifying custom `using` statements?

**Comment by theonlygusti** [comment]
I don't mean `using` statements, I mean compiling with extra assemblies, eg you need the `System.Speech` assembly to be able to use speech synthesisers, which you could normally specify in the compilation phase:

    csc SayAloud.cs /r:System.Speech

There should be a way to reference assemblies using reflection.

**Comment by ORelio** [comment]
In that case that's what I meant earlier, you have to specify it in the compilation phase. However, we're lucky here because C# scripts are actually compiled into assemblies in order to be able to run them. There may be a way to programmatically specify which assemblies to reference during this compilation step. Of course this is not possible at all at the moment but ... that's an interesting suggestion.

**Comment by theonlygusti** [comment]
Really? I'm sorry, but are you the lead developer?

**Comment by ORelio** [comment]
Yes. I'll dig this later. Putting it on my "requested features" list ;)

**Comment by theonlygusti** [comment]
Thanks, I think it would be awesome if it became possible ;)

I'd been trying to implement a "read aloud the messages" feature via a bot, but the lack of this feature has made that task nigh impossible.

**Comment by ORelio** [comment]
If you don't mind recompiling MCC you may add the assembly and recompile it.
That should be enough for developing and testing your bot :)

**Comment by theonlygusti** [comment]
You are right, I just though it might be a cool possible future update.

Hey, do you mind quickly showing me how I use the `MoveToLocation(Mapping.Location location)` method from the new API? I couldn't find out how to use the `Mapping.Location` type.

**Comment by ORelio** [comment]
You can create a `Location` from coordinates and pass it to the API whith:
````C#
MoveToLocation(new Location(x, y, z));
````
Just take a look at [Location.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/Mapping/Location.cs) if you need more details ;)

**Comment by theonlygusti** [comment]
GetCurrentLocation().X?

**Comment by ORelio** [comment]
Yes, this is valid for getting turrent X coordinate.

**Comment by ORelio** [comment]
Implemented as per #1158
