### ISSUE TITLE
Failed to connect to modded forge server

### ISSUE THREAD

**Issue by beringtom** [ORelio/Minecraft-Console-Client#211]
Using the minecraft 1.10.2, modded forge server.

using https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/136/artifacts
after logging in and trying to connect to the server ip (local ip) MCC is just hanging at logging in....
while the server logs are showing this:

> [00:27:09] [Netty Server IO #2/ERROR] [FML/]: NetworkDispatcher exception
> io.netty.handler.codec.DecoderException: Badly compressed packet - size of 3 is below server threshold of 256
>     at net.minecraft.network.NettyCompressionDecoder.decode(SourceFile:35) ~[em.class:?]
>     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) ~[ByteToMessageDecoder.class:?]
>     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) ~[ByteToMessageDecoder.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
>     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
>     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
>     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [ReadTimeoutHandler.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:?]
>     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [AbstractNioByteChannel$NioByteUnsafe.class:?]
>     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:?]
>     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:?]
>     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:?]
>     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:?]
>     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
>     at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
> [00:27:09] [Netty Server IO #2/ERROR] [FML/]: NetworkDispatcher exception
> io.netty.handler.codec.DecoderException: Badly compressed packet - size of 120 is below server threshold of 256
>     at net.minecraft.network.NettyCompressionDecoder.decode(SourceFile:35) ~[em.class:?]
>     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) ~[ByteToMessageDecoder.class:?]
>     at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:205) ~[ByteToMessageDecoder.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
>     at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228) [ByteToMessageDecoder.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ChannelInboundHandlerAdapter.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ChannelInboundHandlerAdapter.class:?]
>     at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144) [ReadTimeoutHandler.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219) [AbstractChannelHandlerContext.class:?]
>     at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769) [DefaultChannelPipeline.class:?]
>     at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567) [AbstractChannel$AbstractUnsafe$5.class:?]
>     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:?]
>     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [NioEventLoop.class:?]
>     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
>     at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by ORelio** [comment]
Hello,

I'm not a Forge expert but seems like there is an issue with the Minecraft protocol itself.

Would you be able to provide a minimum example for crashing MCC? Or is forge 1.10 itself enough?

**Comment by beringtom** [comment]
forge-1.10.2-12.18.2.2107 is the forge version the server i currently running

**Comment by ORelio** [comment]
So if I install forge and run it it will be enough to crash MCC? (If I recall weel I also need at least one mod to install, any suggestion for that? A simple mod for testing purposes?)

**Comment by beringtom** [comment]
Just running with forge is NOT enough to crash MCC, so the problem must be with a mod, I will investigate it futher.

**Comment by ORelio** [comment]
Forge without any mod will run in vanilla mode, so at least one mod is needed. So, which mod do you have which crashes MCC?

**Comment by Pokechu22** [comment]
Is terrain and movements enabled?  If so, it's likely that this is a case of the global palette being a different size due to additional blocks (though, if there are no additional mods, that shouldn't happen).

**Comment by FxDnRedFox** [comment]
i have been trying to get on saicopvp.com but i cant log its say's  that my version is out dated
so can someone help me

**Comment by ORelio** [comment]
@FxDnRedFox Please open your own issue. https://github.com/ORelio/Minecraft-Console-Client/issues/new
