### ISSUE TITLE
terrainandmovements never enabled

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#212]
I cannot use the `/move` command, it outputs this:

    MCC: Please enable terrainandmovements in config to use this command.

However, in my MinecraftClient.ini file I changed the relevant line:

    ...
    terrainandmovements=true #uses more ram, cpu, bandwidth
    ....

![http://i.cubeupload.com/gJfu12.gif](http://i.cubeupload.com/gJfu12.gif)

**Comment by ORelio** [comment]
Thanks for the detailed report :smiley:
There is no terrain and movements in v1.9.0.
Use the latest 1.10 [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) ;)

**Comment by theonlygusti** [comment]
@ORelio wow! Thank you for such a fast and succinct reply :D

Will the same bot api work with the 1.10 version?

**Comment by ORelio** [comment]
The C# API has not be touched since then, only expanded with new API methods so that should be fine :)

**Comment by theonlygusti** [comment]
Does this repository contain that most recent api?

**Comment by ORelio** [comment]
Yes, development code is on the `Indev` branch, development builds are compiled from this branch.
The `master` branch is for stable code from latest stable release, to fork into your own project.

**Comment by ORelio** [comment]
This issue should have been resolved, now. Related: #160.
