### ISSUE TITLE
API's MoveToLocation not working in C# script

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#214]
I tried to make my player wander around with this code:

```
public class WanderBot : ChatBot
{
  private System.Random random;

  public override void Initialize()
  {
    random = new System.Random();
  }

  public override void GetText(string text)
  {
    LogToConsole("Current position: " + GetCurrentLocation().ToString()); // works
    LogToConsole("Current X position: " + GetCurrentLocation().X.ToString()); // works

    // doesn't work:
    MoveToLocation(new Location( 
              GetCurrentLocation().X + random.Next(1,10),
              GetCurrentLocation().Y + random.Next(1,10),
              GetCurrentLocation().Z + random.Next(1,10)));
  }
}
```

Even though all the logs show correct coordinates, my player is not moving. This suggests to me there is some problem with `MoveToLocation`, or I am using it incorrectly.

**Comment by ORelio** [comment]
`MoveToLocation` will compute the best path using A* pathfinding whick takes several seconds to compute, if you hammer it with unreachable locations you're not going anywhere :sweat_smile:

**Comment by theonlygusti** [comment]
it isn't actually being called every time `GetText` is fired, there is always approx. a 30 second gap in between, but it still doesn't seem to do anything.

**Comment by ORelio** [comment]
Please experiment with /move instead, it internally calls MoveToLocation. Avoid unreachable coordinates, it takes forever to compute and gives up after 30 seconds.

**Comment by theonlygusti** [comment]
Yeah this issue can be closed, I made a silly mistake.

I was trying to move in a random Y direction, i.e. through the floor or into the air in a large majority of cases.

**Comment by ORelio** [comment]
You can move 1 block up to jump but otherwise that is indeed not possible ;)
