### ISSUE TITLE
Has anyone ported this to java?

### ISSUE THREAD

**Issue by Samistine** [ORelio/Minecraft-Console-Client#215]
I might port this to java, but I want to make sure no one else has :)

**Comment by Pokechu22** [comment]
There are [other clients](http://wiki.vg/Client_List) written in Java, but I don't think there are any chat-specific ones written in Java (and there isn't a direct port of MCC that I'm aware of).

**Comment by Samistine** [comment]
No current ones thou

>

**Comment by ORelio** [comment]
Hello,
AFAIK there ils no Java port for this project.
Feel free to make any port you want :)

**Comment by ORelio** [comment]
Initial question has been answered, feel free to reopen if needed.
