### ISSUE TITLE
Doesn't seem to work with 1.11

### ISSUE THREAD

**Issue by MarioFan835** [ORelio/Minecraft-Console-Client#222]
it says this
![screenshot](https://cloud.githubusercontent.com/assets/24616459/21283822/242f2774-c3d8-11e6-893a-5014573f5ca5.png)
and then gets stuck in an endless loop of trying to connect

**Comment by Pokechu22** [comment]
Try the [latest development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client); does it work there?

**Comment by MarioFan835** [comment]
it now shows this message
![screenshot2](https://cloud.githubusercontent.com/assets/24616459/21283917/aeda9aa0-c3da-11e6-9bab-8daffed7e765.png)

**Comment by MarioFan835** [comment]
it seems this only happens with certain servers

**Comment by MarioFan835** [comment]
ok, entering the dyn ip fixed it. not sure why the first ip didn't work but this is solved now
