### ISSUE TITLE
Disable logging for bots - feature request

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#223]
I think there should be a way to disable bot logging, so that I can run the program in "verbose" mode for debugging, else I'd prefer to run it without spam from bots which are using the `LogToConsole` method.

**Comment by ORelio** [comment]
Hello,
The idea behing this behavior was making sure no chatbot would send commands or chat messages without the user being informed about it. Addind a setting would be an option, however ChatBots can... change settings so programmatically changing it to hide messages would be trivial.

**Comment by theonlygusti** [comment]
I mean, I want to be able to disable a single chat bot's `LogToConsole` from outputting to stdout. 

Lots of the bots I've written use that method to display heaps upon heaps of sometimes useful debug info, but when I'm not using it for debugging I'd like to be able to turn it off through a setting.

**Comment by theonlygusti** [comment]
Maybe there could be a `LogDebugMessage` which can be disabled, and a `OutputToUser` method which cannot.

**Comment by ORelio** [comment]
That's a very good idea! Just added that as `LogDebugToConsole` in latest development build :)
````C#
/// <summary>
/// Write some text in the console, but only if DebugMessages is enabled in INI file. Nothing will be sent to the server.
/// </summary>
/// <param name="text">Debug log text to write</param>
protected void LogDebugToConsole(object text)
{
    if (Settings.DebugMessages)
        LogToConsole(text);
}
````
This is toggled by the `debugmessages` INI file setting which already exists for internal debugging.

**Comment by theonlygusti** [comment]
Is there a command I can use to toggle `debugmessages` on and off?

**Comment by ORelio** [comment]
Well, currently no, not sure if that would be useful for an end user. Would you mind to elaborate?

**Comment by theonlygusti** [comment]
Well, as a developer, I notice that everything's working fine, then suddenly a problem starts repeating itself in the current session. I could toggle on the debug messages to see what's going on, rather than restarting. Who knows, maybe the problem won't occur in the next session.

**Comment by ORelio** [comment]
Seems useful indeed. Just added `/debug` for you.

**Comment by ORelio** [comment]
Feature request is now implemented. Feel free to reopen if the result does not meet your needs.
