### ISSUE TITLE
Face a different direction - feature request

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#224]
I'd like to be able to point the player in a different direction using a C# script.

**Comment by ayy1lmao** [comment]
why tho ?

**Comment by theonlygusti** [comment]
There are many reasons I can think of:

* interact with other players
* use server features which require you to be pointing a certain direction
* look less like a bot
* non-chat based anti afk

the list goes on

**Comment by CarbonNeuron** [comment]
This has been added with the Look command.

**Comment by ORelio** [comment]
Just use the `/look` command and/or the ChatBot API to look at the desired coordinates.
You can also use the optional [AutoLook](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/AutoLook.cs) bot to automatically look at nearby players like a NPC.
