### ISSUE TITLE
Chatbots access user's IGN

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#226]
I think there should be a way to access the player's IGN from a ChatBot

**Comment by ORelio** [comment]
Thanks for your suggestions, not having that much time currently but I'll look into them :)

**Comment by theonlygusti** [comment]
Yeah, I've noticed you've not been so active as of late.

Can't imagine what you're up to, but it's definitely more important than this!

**Comment by ORelio** [comment]
Hello,
After re-reading open issues, I think this is already implemented.
In your ChatBot, you can access ingame name of the player logged with `Settings.Username` :)

**Comment by ORelio** [comment]
Suggestion has been implemented. Feel free to reopen if that's not what you wanted.
