### ISSUE TITLE
MinecraftClient.exe Crashes When I open it (mac)

### ISSUE THREAD

**Issue by arcanne** [ORelio/Minecraft-Console-Client#227]
When I try to open the file minecraftclient.exe using winebottler because of the .exe extension, the window pops up for a second and crashes. It tells me the authentication system has failed. Ive tried mozroots --import --ask-remove and to run it without winebottler with mono MinecraftClient.exe. I get a message saying cannot execute binary file.

**Comment by ORelio** [comment]
Do not use a Windows emulation program, this .exe file is a .NET app and should be run using Mono ;)

**Comment by arcanne** [comment]
So the Client is now working thanks to your mac guide, but I've ran into another problem. The scripts  that i am giving it in the minecraftclient.ini text file are not transferring into the minecraftclient.exe file. When I reload terminal after already putting all my info into minecraftclient.ini it still tells me to login and i also get kicked for afk without even relogging.

**Comment by ORelio** [comment]
Make sure your file is named `MinecraftClient.ini` not `minecraftclient.ini` because caps are important. You may use other INI files but you'll have to pass them as first argument:
````bash
mono MinecraftClient.exe myotherinifile.ini
# MMC will load myotherfile.ini
````
or
````bash
mono MinecraftClient.exe
# MCC will auto load MinecraftClient.ini
````

When using bots make sure you've set `enabled=true` in the appropriate section.

**Comment by arcanne** [comment]
Ive deleted and redownloaded the folder and the minecraftclient.ini file still wont sync with the exe file.

**Comment by arcanne** [comment]
when i first type `cd minecraftclient` then press enter, everything seems fine. then i run the command `mono MinecraftClient.exe myotherinifile.ini` and it doesnt ask for my email but instead asks for password immediately. I put in my correct password and it tells me Incorrect password.

**Comment by ORelio** [comment]
Please provide full output including commands you typed.

**Comment by arcanne** [comment]
```
Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
Password : 
```
after doing what i said in the previous message, this is what appears on my screen. simply asks for my password. After putting it in, i get this message
```
Password : <******>                                                             Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>
```

**Comment by ORelio** [comment]
There must be an email address specified in your INI file.
Make sure it contains only
````INI
login=
````
with no spaces after the `=` sign.

**Comment by arcanne** [comment]
I think the problem is that MInecraftclient.ini isnt synced with terminal but i dont know how to fix it

**Comment by ORelio** [comment]
I don't understand your issue, but you can try removing `MinecraftClient.ini` by typing:
````
rm MinecraftClient.ini
````
A new file will be generated on next MCC launch.

**Comment by sevij** [comment]
Uhm
this runs on 1.9 right?
well:
Version is supported.
Logging in...
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server.
Disconnected by Server :
SaicoPvP You are running an outdated client! Please upgrade!

I tried and Saicopvp runs on 1.8 so idk why it doesn't work :p

**Comment by Pokechu22** [comment]
It does run on 1.9, but... If the server has a multi-protocol plugin, that may be causing this issue. MCC seems to be doing the server ping via [protocol version](http://wiki.vg/Protocol_version_numbers) 4 (1.7.2-1.7.4), always, and then getting advice from the server on how what version it should _actually_ use.  Normally that'd be fine, but multi-version plugins don't behave that way; they need to mark that specific version and respond differently (there are multiple legal versions, and MCC can't know which one to use).  And sometimes, it'll first say there's a success, but reject it on trying to connect.  That's probably fixable on their end, though maybe MCC should also use a different version number when joining.

As a workaround, you can set a specific Minecraft version in MCC's configuration (eg, 1.11.2).

**Comment by ORelio** [comment]
@Pokechu22 Isn't 1.7 server ping the most recent ping protocol? There's a newer one?
@sevij Some servers are not compatible with version autodetection, you can set it in configuration file by editing the `mcversion` setting, for example `mcversion=1.8.8` if your server is running MC 1.8.8.

**Comment by Pokechu22** [comment]
> Isn't 1.7 server ping the most recent ping protocol? There's a newer one?

The ping is the same for all MC releases since 1.7, but the value given there is a normal protocol version number.  For the current MC client, it uses 316, not 4.  Multi-version servers do use that version number to make some decisions, but the notchian implementation just doesn't use the version at all.

**Comment by ORelio** [comment]
> For the current MC client, it uses 316, not 4

Completely forgot that client version is included in server ping request.
But, yes, as we don't know what server version is running we have to put something.
Maybe setting it to `MAX_INT` would trick BungeeCord into giving the actual version. Will try.

**Comment by Pokechu22** [comment]
The convention seems to be -1 for unknown version; I'd recommend that over MAX_INT (they're the same size in VarInts).

**Comment by ORelio** [comment]
Ok so performed a quick test using `us.mineplex.com` to verify your assertion.
Using `4` BungeeCord responds with the actual version as support for MC 1.7 was removed:
````
BungeeCord 1.8.x, 1.9.x, 1.10.x, 1.11.x (protocol v316).
````
But using `47`, BungeeCord indeeds responds `47` as MC 1.8 is a supported version:
````
BungeeCord 1.8.x, 1.9.x, 1.10.x, 1.11.x (protocol v47).
````
Using `-1` as you suggested, we get the actual maximum version:
````
BungeeCord 1.8.x, 1.9.x, 1.10.x, 1.11.x (protocol v316).
````
I guess that any protocol version not supported by BungeeCord would also work.
Thanks @Pokechu22, now server version detection should be more accurate :)

**Comment by TheSnoozer** [comment]
Since this issue seems quite old and seems to have gotten fixed by now, I'm closing this as part of an issue cleanup. if you still have an issue with specific problem please feel free to reopen. Otherwise please open a new issue.
