### ISSUE TITLE
Help required with the AFKing.txt

### ISSUE THREAD

**Issue by ayy1lmao** [ORelio/Minecraft-Console-Client#229]
CONFIGS : http://pastebin.com/F6mEK0m3
Well, the water afking method does not work with, so i tried to mess around with the settings but havent managed to make it work, if anyone could help me i would be appreciated

**Comment by ORelio** [comment]
Change
````INI
[ScriptScheduler]
enabled=false
tasksfile=tasks.ini
````
Into
````INI
[ScriptScheduler]
enabled=true
tasksfile=Task.ini
````
Everything else seems fine :)

**Comment by ayy1lmao** [comment]
Omg, i was looking into the most complex stuff, thanks, i love your work

**Comment by ayy1lmao** [comment]
Sadly that is not working, do you have any commands so the player will actually move, or anything to bypass anti-afk

**Comment by ORelio** [comment]
Oh, yes, there is no `/` for internal commands in scripts, these are necessary only when you manually type them in chat. So that's `move` not `/move` :)

**Comment by ayy1lmao** [comment]
http://imgur.com/a/JNcjz

**Comment by ORelio** [comment]
You must be in the wrong directory when invoking MCC.
If using a shortcut, check "start in" field in shortcut properties.
