### ISSUE TITLE
Random in C# Scripts

### ISSUE THREAD

**Issue by ReOp14** [ORelio/Minecraft-Console-Client#230]
How could I make something random appear in c# scripts? Perhaps setting variable Random from one to seven. Or could send 4 different messages.

**Comment by ORelio** [comment]
For C# related questions you can as well use a search engine.
Here is relevant documentation:
https://msdn.microsoft.com/en-us/library/system.random.aspx
http://stackoverflow.com/questions/2706500/how-do-i-generate-a-random-int-number-in-c#2706537

**Comment by ReOp14** [comment]
After doing some searching, I have found a simple answer on https://www.dotnetperls.com/random
```
//MCCScript 1.0
Random r = new Random();
for (int i = 0; i < 1; i++)
{
	MCC.SendText(r.Next(5, 10));
}
```
After doing this, I also wanted to set it as a variable so then I made this:
```
//MCCScript 1.0
Random r = new Random();
for (int i = 0; i < 1; i++)
{
	int random = (r.Next(5,10));
	MCC.SendText("Random: " + random);
}
```
But yeah, I should of searched it up. Thanks though.

**Comment by ORelio** [comment]
That's fine no worries :smiley:
