### ISSUE TITLE
Unloading a script from a command

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#231]
Is it possible to unload a script from a console client command?

**Comment by ORelio** [comment]
No. The script will unload itself when finished or if unloaded explicitely by the script but that's all.

**Comment by ReOp14** [comment]
Hey AppleCidar! I had a issue long ago, hopefully this helps. https://github.com/ORelio/Minecraft-Console-Client/issues/198

**Comment by AppleCidar** [comment]
Okay so I am using a script that reminds people to do stuff. So it messages chat every 30 mins and I wan't it to quit the script once someone messages it "Quit". To do this I need To use the Auto Respond. So I was just wondering if I could make it so when the Auto Respond picks up the message "Quit" it messages the user that the script has been canceled. So just was wondering if you could quit a script from console client

**Comment by ORelio** [comment]
Oh. In that case I'd advise to write a ChatBot. ChatBots can receive chat messages and unload themselves if the received message meets your requirements :)

**Comment by AppleCidar** [comment]
How would you do something like this?

**Comment by AppleCidar** [comment]
Never mind i see that you have a sample script.

**Comment by ORelio** [comment]
Here is a sample bot receiving messages :
https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/ChatBots/TestBot.cs
Simply check something like `message.ToLower().Trim() == "quit"` to check for "Quit" private message.

**Comment by AppleCidar** [comment]
`[MCC] [Script] System.InvalidOperationException: Cannot access a non-static member of outer type 'ScriptLoader.Script' via nested type 'ScriptLoader.Script.ExampleBot'`
I am getting this error

**Comment by ORelio** [comment]
The `MCC` object is for C# scripts, ChatBots however use the ChatBot API.
Simply see [ChatBot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/ChatBot.cs) for more details including available methods ;)

**Comment by AppleCidar** [comment]
Got it working thank you so much :D

**Comment by ORelio** [comment]
Good job! 😉
