### ISSUE TITLE
C# Script: # Of Players

### ISSUE THREAD

**Issue by ReOp14** [ORelio/Minecraft-Console-Client#233]
I don't think there is a way to show how many players there is on the server.
I'm aware there is /list but I need an automatically updating number for a C# script.
I'm making a script where when the server reaches 40 players, it activates an event, perhaps like hangman, or just announces there is 40 players.

**Comment by ORelio** [comment]
`GetOnlinePlayers()` in ChatBot API returns an array with player names so you can have the player count from the array's `Length`:
````C#
int playerCount = GetOnlinePlayers().Length;
````

**Comment by ReOp14** [comment]
```
//MCCScript 1.0
int GetOnlinePlayers = MCC.GetVarAsInt("GetOnlinePlayers");
int playerCount = GetOnlinePlayers().Length;
for (int i = 0; i < 1; i++)
{
	MCC.SendText("Players Online: " + playerCount);
}
```
When running the script, I get the error:
`System.InvalidOperationException: Cannot implicitly convert type 'string' to 'int'`
If I remove "int GetOnlinePlayers = MCC.GetVarAsInt("GetOnlinePlayers");"
I get the error: 
`The name 'GetOnlinePlayers' does not exist in the current context`

**Comment by ORelio** [comment]
I never said to use GetVarAs* to retrieve player list.
This is a ChatBot method directly called GetOnlinePlayers() and you are not calling it from a ChatBot.
Would you need it from the MCC script API? (MCC.GetOnlinePlayers()?)

**Comment by ReOp14** [comment]
Oh, I'll have to make it in visual studio then. Thought it was a script thing.

**Comment by ORelio** [comment]
You would need to do this every time MCC gets updated.
The best way is submitting a pull request so that it gets added to MCC :)
Just added it for you, just pull the changes and/or grab the latest development build.

**Comment by ReOp14** [comment]
I updated to the latest indev branch, and I cannot figure out how to use MCC.GetOnlinePlayers
Thanks very much for adding the commit though.
 /// <summary>
/// Return the list of currently online players
/// </summary>
/// <returns>List of online players</returns>
It says that it would return a list of online players, but I tried a lot of combinations while testing with a script, but I always receive an error.
```
//MCCScript 1.0
int playerCount = MCC.GetVarAsInt("playerCount");
for (int i = 0; i < 1; i++)
{
	MCC.SendText(MCC.GetOnlinePlayers);
	MCC.SendText("Players Online: " + playerCount);
}
```

**Comment by ORelio** [comment]
This is a method not a field, so you need parenthesis when calling it.
````C#
int playerCount = MCC.GetOnlinePlayers().Length;
````

**Comment by ReOp14** [comment]
Alright thanks. Final Product:
```
//MCCScript 1.0
int playerCount = MCC.GetOnlinePlayers().Length;
for (int i = 0; i < 1; i++)
{
	Thread.Sleep(1000);
	MCC.SendText("Players Online: " + playerCount);
	Thread.Sleep(1000);
	if (playerCount == 11)
	{
	MCC.SendText("10 Players so far.. Pretty Good!");
	}
}
```
Also the if statement never runs if I remove the 2nd Thread.Sleep(1000), its quite strange. Not sure why that happens but whatever.

**Comment by ORelio** [comment]
````C#
//MCCScript 1.0
while (true)
{
    Thread.Sleep(1000);
    int playerCount = MCC.GetOnlinePlayers().Length; //Always retrieve the up-to-date value
    MCC.SendText("Players Online: " + playerCount);
    if (playerCount >= 40)
    {
        MCC.SendText("40 players or more!");
        //Do stuff
        //Optionally exit from the loop
        break;
    }
}
````

**Comment by ReOp14** [comment]
Ah yes, I forgot to make it loop. I would of just made the 1 to a greater number.
`for (int i = 0; i < 1; i++)`

**Comment by ORelio** [comment]
I'd suggest `while (true)` instead for a truly infinite loop.
You can exit the loop with a `break;` statement.
Or even better, directly put your condition:
````C#
int playerCount = 0;
while (playerCount < 40)
{
    Thread.Sleep(1000);
    playerCount = MCC.GetOnlinePlayers().Length;
    MCC.SendText("Players Online: " + playerCount);
    if (playerCount >= 40)
    {
        MCC.SendText("40 players or more!");
        //Do stuff
    }
}
````
This way the loop automatically exits when the condition is satisfied (40 players or more).
