### ISSUE TITLE
The "GetText(string text)" Does not only register the text you wan't. it registers everything.

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#235]
So I have made a bot that messages minecraft every 30 mins and if it gets a specific message it will stop messaging minecraft. But I am using the "GetText(string text)" And if you message it anything it stops the messages. I need it to only stop when it gets a specific message.
`    {`
`        string message = "leele";`
`        string username = "";`
`        text = GetVerbatim(text);`

        if (IsChatMessage(text, ref message, ref username))
        {
            LogToConsole("Buffers Checked by: " + username);
            SendText("/f c f");
            Thread.Sleep(5000);
            SendText(username + " Has Checked Buffers");
            LogToConsole("unloaded");
            UnloadBot();
        }
        else if (IsPrivateMessage(text, ref message, ref username))
        {
            LogToConsole("Buffers Checked by: " + username);
            SendText("/f c f");
            Thread.Sleep(5000);
            SendText(username + " Has Checked Buffers");
            UnloadBot();
        }
    }`

**Comment by ORelio** [comment]
Well, already stated how to do this here: https://github.com/ORelio/Minecraft-Console-Client/issues/231#issuecomment-270515803
You should do something like this:
````C#
public override void GetText(string text)
{
    string message = "leele";
    string username = "";
    text = GetVerbatim(text);

    if (IsPrivateMessage(text, ref message, ref username)
        && message.ToLower().Trim() == "quit")
    {
        LogToConsole("Buffers Checked by: " + username);
        SendText("/f c f");
        Thread.Sleep(5000);
        SendText(username + " Has Checked Buffers");
        UnloadBot();
    }
}
````
This way your bot does nothing unless this is a private message equals to "quit", case insensitive.

**Comment by AppleCidar** [comment]
Oh my bad, didn't see that part of the comment.
