### ISSUE TITLE
Scrolling up in terminal window

### ISSUE THREAD

**Issue by ReOp14** [ORelio/Minecraft-Console-Client#239]
While MCC is on a server, specially a busy one. There is a lot of chat messages. Whenever I scroll up using mouse wheel, any new message will send the chat all the way to the bottom, although this is useful, Sometimes I want to scroll up and look at a message. 

Maybe make it like a Streamer's Twitch Chat, possibly only stop it from moving when not at the bottom.

**Comment by ORelio** [comment]
This depends on your terminal/console app behaviour, MCC cannot influence that.
For example on `gnome-terminal`, if you scoll up, it won't auto-scroll down if new lines are printed.

The only way within MCC would be to emulate a terminal window by detecting terminal size and printing lines within window, while offering keyboard shortcuts to scroll up (the same way as the `screen` linux utility does). That would require some work and you would not be able to use the scollbar offered by your terminal. Not really worth it, in my opinion.
