### ISSUE TITLE
Mono: Authentication/Decryption failed

### ISSUE THREAD

**Issue by period** [ORelio/Minecraft-Console-Client#240]
Currently running Mono on a Ubuntu 14.04 Kimsufi inside a screen. I have tried the commands provided in other issues such as #152 but with no avail.

```
root@ns694201337:~/console-1# mozroots --import --ask-remove
Mozilla Roots Importer - version 3.2.8.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
Couldn't retrieve the file using the supplied information.
```

```root@ns420691337~/console-1# mono MinecraftClient.exe
Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
Login : memes
Password : <******>
Connecting to Minecraft.net...

Unhandled Exception:
System.IO.IOException: The authentication or decryption has failed. ---> Mono.```

**Comment by ORelio** [comment]
The mozroots command did not complete successfully... :
````
Couldn't retrieve the file using the supplied information.
````
Never seen that before, though.

**Comment by Chearful** [comment]
Any suggestions as to what can be done? I know it works on a vps of mine so if there are some files I can copy over to make it work then could you tell me those? :p

**Comment by ORelio** [comment]
If you already have a valid Mono setup you can copy your certificates from it.
They seems to be stored in your home directory:
````
~/.config/.mono/certs/Trust
````

**Comment by Chearful** [comment]
OK, so that did work and remove the error, but now it is saying my credentials aren't valid when they work. I've tried waiting an hour too.

**Comment by ORelio** [comment]
Check your network connectivity. Seems like there is an issue there. Try
````
curl https://authserver.mojang.com
````
To check session server works properly.
Also maybe some special characters in your password don't work.
Try passing it through eg your INI file.

**Comment by Chearful** [comment]
```root@ns420~/console-1# curl https://authserver.mojang.com
{"Status":"OK","Runtime-Mode":"productionMode","Application-Author":"Mojang Web Force","Application-Description":"Mojang Authentication Server.","Specification-Version":"2.28.9","Application-Name":"yggdrasil.auth.restlet.server","Implementation-Version":"2.28.9_build7","Application-Owner":"Mojang"}
```

& there are no symbols in the password. Works fine on my home PC.

**Comment by ORelio** [comment]
No idea what's wrong then, sorry. Does it work fine _with MCC_ on your home PC?
You may want to try the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), just in case.

**Comment by Chearful** [comment]
Yes, it works perfectly fine w/ MCC on my PC.

Development build doesn't work either.

**Comment by Chearful** [comment]
^ scrap that, found it in the .ini.


I found a proxy which I know that works but it still returns incorrect password.

**Comment by BlueDemonic** [comment]
i have the same problem did this fix for you

**Comment by Chearful** [comment]
Nope :/

**Comment by BlueDemonic** [comment]
Do you know any way to fix it or use console client on a Linux vps
