### ISSUE TITLE
i really dont know the issue

### ISSUE THREAD

**Issue by ayy1lmao** [ORelio/Minecraft-Console-Client#242]
https://mega.nz/#F!fsF0STKA!t25N7Z_Usg7VKqgLHZh9pw
this is my sell bot, the anti afk is to sell every 30 secs, and the script afk is to pay me 
i just dont know what is going on, is should work, pls help, this is ruining my family, and my dad hates me now

**Comment by ReOp14** [comment]
Hello, Make a file named "Afk.cs" (Use notepad or notepad++ to open) and copy and paste this simple script to type a command every 30 seconds, or 30000 milliseconds.
```
//MCCScript 1.0
for (int i = 0; i < 9999; i++)
{
    MCC.SendText("/pay _0xy 1000");
    Thread.Sleep(30000);
}
```
Sorry to hear this is ruining your family, hope this helps! The 9999 numbers means to run it 9999 times, you can set it to 50 to only run 50 times.

**Comment by ReOp14** [comment]
Also, forgot to mention.. Type "/script Afk" in console once ingame.

**Comment by ORelio** [comment]
You can use `for(;;)` or `while (true)` for infinite loops.

**Comment by ayy1lmao** [comment]
well thanks both of you for the help, i just saw i forgot to remove my alt's  info from the file, but besides that my dad likes me now, and all my family is reunited again

**Comment by ORelio** [comment]
Oh, I'd advise you to immediately change your password.
Glad you could solve your issue :)
