### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by kmddd59** [ORelio/Minecraft-Console-Client#243]
when using dev build I don't know how to set the config I seem to not have access to the config ini I dropped the exe inside the old client folder was that a bad idea?

**Comment by ORelio** [comment]
Yes, you can drop it in the stable version's folder. Some settings won't appear, you can delete the ini file and run MCC once to get a new one.

**Comment by kmddd59** [comment]
Thanks

**Comment by kmddd59** [comment]
ummmm it didn't make the ini file however I'm on Mac if that makes a difference ill make a small video of the issue and attach it here later I'm outside so the video will be made later but it isn't making the ini file and I really only need it so I can move

**Comment by ORelio** [comment]
Make sure you are invoking MCC from the right directory. It will create the INI file in the directory you are invoking it from. Also maybe it hasn't write permissions to the selected directory but that shouldn't happen if you download it somewhere in your home folder and launch it yourself.

**Comment by kmddd59** [comment]
That is the issue thanks the file is in my ~ directory on my MacBook it's the issue so I'm putting the files in there I also found a way to make a terminal command so I can run a terminal command from the bin folder and it will launch this client I'll share this later when I'm on my MacBook I found this in a different project but it works flawlessly the downside is that the whole thing is bundled into a app file however you can't run it as a app file you need to issue the command is there a way that I can convert it to a app file so I can just double click on it on mac? I tried wine bottler and no luck and I tried the bundle thing that comes with mono if you can help bundle it into a app file I'll be glad to help you I don't know a lot of code but I know enough to do what you can tell me I understand but don't know how to write code I'm self taught so I don't know everything but I can do basics lol let me know if you can help

**Comment by ORelio** [comment]
Sorry, I'm absolutely not a mac expert 😅

**Comment by kmddd59** [comment]
It's fine

**Comment by TheSnoozer** [comment]
Since this seems to be solved and quite old, I'm closing this as part of an issue cleanup.
Feel free to reopen if you still have a problem with this specific problem. Alternatively please open a new issue.
