### ISSUE TITLE
Split Message Causes Bot to Disconnect from Server

### ISSUE THREAD

**Issue by JacksonWillford** [ORelio/Minecraft-Console-Client#246]
https://dl.dropboxusercontent.com/u/4841592/ShareX/2017/02/2017-02-08_20-43-06.mp4

I have splitmessagedelay on, so it isn't being kicked for spam.

Additionally, terrain and movements is a bit wonky currently. Accounts on MCC cannot go up or down stairs.

Current version: http://i.imgur.com/KdG2lQ3.png

**Comment by ORelio** [comment]
Crashes exactly how I like them: when there is no error message... not your fault, through. :sweat_smile:
Thanks for your report! What is your config? (If pasting config don't forget to remove personal data, especially credentials)

**Comment by ReOp14** [comment]
Hey ORelio, I would like to add I have been getting this crash for a long time now, and it disconnects me at the most random of times.

**Comment by Pokechu22** [comment]
1.11.2 increased the max chat length to 255 (or so) characters; maybe the splitting is using that length even on older versions where the max length is much smaller?

**Comment by ReOp14** [comment]
For me, its not length of chat or clicking anything. If I don't type in MCC for atleast 30 seconds, and noone in chatting in the server's chat, (I always play on us.mineplex.com) it will disconnect from the server exactly how jackson413 showed it. I do think when I got a new computer last month, it does happen less, but next time my buddy is streaming on the weekend, ill try and record this happening.

**Comment by ORelio** [comment]
Make sure you are using a recent Mono version. At least 4.0.
@Pokechu22 Split is set depending on version since 609b939159a46d2ccc73052e65f8a14a6397a9b5 but thanks for the suggestion :/
