### ISSUE TITLE
Setup Minecraft Console Client on a Linux VPS

### ISSUE THREAD

**Issue by BlueDemonic** [ORelio/Minecraft-Console-Client#247]
hey there im looking for some help with setting up console cleint on a linux vps thanks

**Comment by ORelio** [comment]
Basically run it as you would run it on linux, optionally using the `screen` command. See #163

**Comment by BlueDemonic** [comment]
could you show me how to set it up on linux

**Comment by ORelio** [comment]
There is enough info in given links. Please read them. Especially [here](https://github.com/ORelio/Minecraft-Console-Client/issues/163#issuecomment-226483646) and [here](https://github.com/ORelio/Minecraft-Console-Client/issues/174#issuecomment-237163828).
