### ISSUE TITLE
How can a C# script get an appvar?

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#249]
In `MinecraftClient.ini`:

```ini
[AppVars]
#yourvar=yourvalue
#can be used in some other fields as %yourvar%
#%username% and %serverip% are reserved variables.
foo=bar
```

How do I get the value of `foo` from a C# script?

**Comment by ORelio** [comment]
MCC.[GetVarAsString](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/CSharpRunner.cs#L274)("foo') //returns `bar`
See embedded link for full API reference :)

**Comment by theonlygusti** [comment]
Thank you, that resolved it ;)

I was looking in the wrong classes, I was looking at ChatBot.cs instead of the script runner :P so i couldn't find it.

**Comment by theonlygusti** [comment]
It tells me that it `Cannot access a nonstatic member of outer type `ScriptLoader.Script' via nested type `ScriptLoader.Script.MyClass'`

Was it meant to be a static method? Or am I meant to instantiate my own `MCC`?

**Comment by ORelio** [comment]
See [`sample-script.cs`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.cs) for usage examples.
If you are still facing issues please paste your script so I can see what's wrong.

**Comment by theonlygusti** [comment]
Oh, I am trying to use it from within another class. I have written a class which (C# terminology) inherits from ChatBot

**Comment by theonlygusti** [comment]
The full script is 500 lines long, I'm trying to use an appvar from inside the GetText method

**Comment by theonlygusti** [comment]
Actually I might be able to write my own initialiser, and pass arguments when I instantiate the class?

**Comment by theonlygusti** [comment]
I can't seem to access `MCC` in the `//MCCScript Extensions` section, how can I get appvars from that section?

**Comment by ORelio** [comment]
From ChatBots you need to use the ChatBot API instead. There is indeed currently no `GetVar()` in ChatBot API, but fortunately you can access it directly from the Settings class with [`Settings.GetVar()`](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/Settings.cs#L741) so it should work as well. This method is safe to use from ChatBots :
````C#
Settings.GetVar("foo").ToString() //bar
````
The variable can be of any type so the `ToString()` part will ensure you get a string.

**Comment by theonlygusti** [comment]
I just tried it with `Settings.GetVar("username").ToString()` and it throws a massive error:

    TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object

**Comment by Pokechu22** [comment]
Probably that means that there is no variable named `username`; `ToString` would fail with a `NullReferenceException` if there is no variable.  (You can ignore the `TargetInvocationException` portion for the most part).

It looks like the variables `username`, `serverip`, and `serverport` are special and are only handled within `ExpandVars`; `GetVar` won't retrieve them.

You can get those variables instead via `Settings.Username`, `Settings.ServerIP`, and `Settings.ServerPort`.

**Comment by theonlygusti** [comment]
Awesome, thank you both!

This resolved the problems I was having ;)

**Comment by ORelio** [comment]
Seems like the initial question has been answered, feel free to reopen if needed :)
