### ISSUE TITLE
Need to wait x ammount of seconds!

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#250]
So I am not very advanced in c sharp, but I was just messing around with `Thread.Sleep();` and noticed it made the client sleep and froze the console client. I mainly know python so I just use `asyncio` to wait x amount of time. But c sharp is so old you have to use some sort of timer? I don't really know how to do this so if someone could help me it would be appreciated!

**Comment by ORelio** [comment]
This is not C#'s fault, this is how MCC works internally.
Scripts can safely use `Thread.Sleep()`, see [sample-script.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.cs).
However ChatBot callbacks are called on MCC's thread. Obviously it *will* freeze the main thread.
If you need to delay something you'll need to either start a thread or use a counter.
`OnUpdate()` is called ~10 times per second (every 100 ms) so you could use a counter threre.

**Comment by AppleCidar** [comment]
Sorry, but is there any way you can give me an example of how to make a type of counter?

**Comment by ORelio** [comment]
There is a counter in [Hangman.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/HangmanGame.cs) which is decremented on every update.
Once it reaches zero, the game is cancelled.

**Comment by ORelio** [comment]
Seems like the initial question has been answered, feel free to reopen if needed :)
