### ISSUE TITLE
Client exits on /quit

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#252]
I have set `exitonfailure` to false in the `ini` file but after a `/quit` or `PerformInternalCommand("quit")` the client still exits (terminates) rather than simply logging out of the server.

**Comment by ORelio** [comment]
Using `/quit` is not a failure, that's normal exit behaviour :sweat_smile:
If you want to go back to terminal after exiting, simply open a terminal and launch MCC from there...

**Comment by theonlygusti** [comment]
No, I need to make a CS script that quits the server, waits a couple seconds up to a couple minutes, and then rejoins.

I cannot find a method of doing this, the way I've tried (`PerformInternalCommand("quit")`) makes the client close.

**Comment by ORelio** [comment]
You may perform infinite reconnections with a wrapper script:

````batch
@echo off
:reconnect
MinecraftClient.exe <args>
timeout 30
goto reconnect
````

````bash
#!/bin/bash
while true; do
    mono MinecraftClient.exe #<args>
    sleep 30 # seconds
done
````

**Comment by theonlygusti** [comment]
Is that honestly the only way in which this is currently possible?

I can't believe that the current behaviour of `/quit` is intentional, the `/exit` command should terminate the program but I feel that `/quit` (and `PerformInternalCommand("quit")` by extension) should just leave the current server, returning to the "default" state where you can use the `/connect` command to join a server again.

**Comment by theonlygusti** [comment]
@Orelio is it possible to write a script that quits then re-joins a server?

**Comment by ORelio** [comment]
Scripts and chatbots do not run while disconnected, they are in a suspended state.
You may use [ReconnectToTheServer](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L526), though it currently has no delay in it.

**Comment by theonlygusti** [comment]
Ok thank you. Does that restart all the scripts as well and kill the currently running ones?

**Comment by ORelio** [comment]
No, scripts are suspended and resumed when re-joining.
However the "exit" method with wrapper script would do this.

**Comment by theonlygusti** [comment]
No, suspending is the behaviour I'd prefer :)

Awesome, thanks for all your help!

**Comment by ORelio** [comment]
Well the hardest part was understanding your needs 😜

**Comment by theonlygusti** [comment]
Sorry to have to bother you again, but `Initialize` seems to be called on every bot after one of them calls `ReconnectToTheServer`.

Is there a method which only fires once when the app is first started?

**Comment by theonlygusti** [comment]
Also it seems that scripts are actually killed and restarted. Maybe I am wrong.

**Comment by ORelio** [comment]
Well that's probably a bug, you can get around this by adding a boolean:
````C#
private bool initialized = false;

public override void Initialize()
{
    if (!initialized)
    {
        initialized = true;
        //do stuff
    }
}

**Comment by theonlygusti** [comment]
That didn't work, I just tried to use a boolean as you suggested, but every time `initialized` is false.

**Comment by ORelio** [comment]
That would mean the class is loaded on each join, probably because the ChatBot is embedded in a script launched when joining.

**Comment by theonlygusti** [comment]
It's in my tasks file.... should it not be?

**Comment by ORelio** [comment]
Unless there is a bug in bot suspend system while reconnecting, loading it only on first login should do what you want, because otherwise an additional bot is created and loaded on every subsequent login.

**Comment by theonlygusti** [comment]
Weird, looks like there's a [problem with `triggerOnFirstLogin`](https://github.com/ORelio/Minecraft-Console-Client/issues/255) then.

**Comment by ORelio** [comment]
Indeed, fixed #255, please retry with latest build :smiley:

**Comment by ORelio** [comment]
ChatBot method `ReconnectToTheServer()` now allows an optional `delaySeconds` argument
````C#
/// <summary>
/// Disconnect from the server and restart the program
/// It will unload and reload all the bots and then reconnect to the server
/// </summary>
/// <param name="attempts">In case of failure, maximum extra attempts before aborting</param>
/// <param name="delaySeconds">Optional delay, in seconds, before restarting</param>
protected void ReconnectToTheServer(int ExtraAttempts = 3, int delaySeconds = 0)
{
    McTcpClient.ReconnectionAttemptsLeft = ExtraAttempts;
    Program.Restart(delaySeconds);
}
````
This way you can stay disconnected for the specified time amount, then reconnect and resume script :)

**Comment by ORelio** [comment]
Suggested changes have been implemented. Feel free to reopen the issue if necessary.
