### ISSUE TITLE
triggerOnFirstLogin : scripts never run

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#255]
When I use `triggerOnLogin` the script runs fine. Replace it with `triggerOnFirstLogin`, the script never gets run.

**Comment by ORelio** [comment]
You're right, that wasn't working anymore, thaks for your report.
This is now fixed and automatically available in development builds :wink:

**Comment by theonlygusti** [comment]
Hey, I don't have VS. 

How do I get the `exe` of the latest Indev version?

**Comment by Pokechu22** [comment]
You can get it from [appveyor](https://ci.appveyor.com/project/ORelio/minecraft-console-client), where it's automatically built each commit.

**Comment by ORelio** [comment]
As @Pokechu22 stated, this link gives latest Indev exe file:
https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by ORelio** [comment]
Seems like this issue is now resolved, feel free to reopen if needed :)
