### ISSUE TITLE
problem with terrain and movement

### ISSUE THREAD

**Issue by iNordic** [ORelio/Minecraft-Console-Client#256]
If i use 1.9.0, it tells me that terrain is not available. Then i take 1.8.2, he says it is available, but gives a whole bunch of errors before just shutting down. Is this known/is there a way to get arround this?

**Comment by ORelio** [comment]
Stable build only has basic and experimental terrain support. Use [development builds](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) instead.

**Comment by ORelio** [comment]
This issue should be resolved by using latest development build. Feel free to reopen if needed.
