### ISSUE TITLE
Skype/Discord Association

### ISSUE THREAD

**Issue by Zypsie** [ORelio/Minecraft-Console-Client#258]
Hello, I am sorta a noob when it comes to coding etc...

I was wondering how can i send alerts to discord or skype when a redstone lamp turns off... I got a sound to play but that is it.

**Comment by ORelio** [comment]
Hello,

To interact with some third-party service they would need to provide an API for interacting with it. That is probably the case for both (at least, discord). Then, someone needs to develop a library (some code) for interacting with it. Finally, that could be integrated in MCC using a ChatBot for instance.

I don't have enough time to invest in that, but feel free to contribute if you are really interested.
Related issue: #138 - Bridge chat to IRC

**Comment by Zypsie** [comment]
There is no simple way of sending an alert to an iphone? What about trigger a script based on a sound?

**Comment by ORelio** [comment]
Same here, that requires interoperability work especially if you plan to include speech recognition.

**Comment by AppleCidar** [comment]
What faction server do you play on? I might be able to help you with doing this

**Comment by ORelio** [comment]
Related to this issue: See [this message](https://github.com/ORelio/Minecraft-Console-Client/issues/715#issuecomment-489442588) for an example of relaying chat messages to Discord using a python script and the `discord-webhook` module (#715).

**Comment by ORelio** [comment]
I'll close this old issue as a question for interacting with third party services. I think we will not implement third party services directly in MCC but some optional scripts can be found in [config/ChatBots](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config/ChatBots).
