### ISSUE TITLE
Why no generics? And a microoptimization

### ISSUE THREAD

**Issue by Icecream-burglar** [ORelio/Minecraft-Console-Client#260]
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Settings.cs#L613

Why not add another function building on top of this one like so:
```cs
public static T GetVar<T>(string varName)
{
    return (T)GetVar(varName);
}
```
Then expose it in CSharpRunner.

https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/CSharpRunner.cs#L297
You should probably do:
```cs
public int GetVarAsInt(string varName)
{
    var value = GetVar(varName);
    if (value is int)
        return (int)GetVar(varName);
    int result;
    if (int.TryParse(value.ToString(), out result))
        return result;
    return 0;
}
```
This reduces the total number of GetVar call counts to one instead of two. Hash lookups are fast, but code-duplication is bad.

Disclaimer:
If I look totally "off-the-rocker" for suggesting this stuff, it's because I'm not really interested in this project or minecraft XD
I'm just a passer-by helping a guy with his script.

**Comment by Icecream-burglar** [comment]
Also, quick question: `int.TryParse(value.ToString(), out result)` why would an integer value ever be added to  settings.appvars as a string?

**Comment by ORelio** [comment]
Hello,

Thanks for your suggestions!
Good idea for adding generics.
And nice catch for the duplicate call to `GetVar()`, wasn't intended indeed! :)

Regarding your second question, the `TryParse` part is in case the variable is of the wrong type.
Let's say it is a `double`, or whatever else, and and `int` is requested. Then, let's try to convert to int.
To do this, the variable is converted to string as every object has `ToString()`, then, we try parsing that.

So, as generics are better indeed, I'd write this:
````C#
/// <summary>
/// Get a global variable by name, as the specified type, and try converting it if possible.
/// If you know what you are doing and just want a cast, use (T)MCC.GetVar("name") instead.
/// </summary>
/// <typeparam name="T">Variable type</typeparam>
/// <param name="varName">Variable name</param>
/// <returns>Variable as specified type or default value for this type</returns>
public T GetVar<T>(string varName)
{
    object value = GetVar(varName);
    if (value is T)
        return (T)value;
    if (value != null)
    {
        try
        {
            TypeConverter converter = TypeDescriptor.GetConverter(typeof(T));
            if (converter != null)
                return (T)converter.ConvertFromString(value.ToString());
        }
        catch (NotSupportedException) { /* Was worth trying */ }
    }
    return default(T);
}
````
(parts of this come from http://stackoverflow.com/questions/2961656)

Does that seems better? :)

**Comment by ORelio** [comment]
`GetVar<T>()` is now implemented in above commit :)

**Comment by ORelio** [comment]
Since the suggested change has been implemented, I'm closing the issue. Feel free to reopen if needed ;)
