### ISSUE TITLE
Item pickup doesnt work with terrain

### ISSUE THREAD

**Issue by NighteranceMC** [ORelio/Minecraft-Console-Client#264]
Hello, I am using your console-client. I enabled that terrain thing, but I am not able to pick up items. Inventory is not full, can be edited inside Minecraft (with /invsee), but items can't be picked up. Using latest version. Can you help me? Thanks!

**Comment by ORelio** [comment]
Try moving with `/move` in order to update location. Pickup is handled server-side, not client-side.

**Comment by Simran-B** [comment]
Also see: http://wiki.vg/Protocol#Collect_Item

> The server only checks for items to be picked up after each Player Position (and Player Position And Look) packet sent by the client.

**Comment by TheSnoozer** [comment]
Closing as answered (and as part of an issue cleanup).

Feel free to reopen if you still got a problem.
