### ISSUE TITLE
Raspberry-Pi (Pi 3 Model B)

### ISSUE THREAD

**Issue by WorldWithoutEnd** [ORelio/Minecraft-Console-Client#266]
So I've been trying for ages to get console client working on my raspberry pi, but I can't get it to work I have followed all your instructions correctly and looked at loads of other threads on it but I still can't find a way of making it work please help me or give it a try youself and tell me if you can get it working and how you do it.

**Comment by ORelio** [comment]
If you face a specific issue you'll have to be more specific and describe the exact issue you are facing.
Also, you can read #247 and links in that issue, for general guidance about how to install it on Linux.

**Comment by ORelio** [comment]
Closing the issue as no more questions have been asked and information has been given.
Feel free to reopen if you have further questions.
