### ISSUE TITLE
1.11.2 connecting issue

### ISSUE THREAD

**Issue by nokimaro** [ORelio/Minecraft-Console-Client#267]
Server ip is ```meepcraft.com```
I have no problems when connecting with vanila client.
But i can't connect with console client.
![screen](https://i.gyazo.com/20fc6cdd666ba729b59e297a569726c2.png)

I'm using latest indev build from here https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by ORelio** [comment]
Please check `resolvesrvrecords` in your INI file. This feature is required for resolving many server domain names, including `meepcraft.com` which resolves to `mc.meeplabs.us:25565`.

**Comment by nokimaro** [comment]
Changed default
```resolvesrvrecords=fast```
to
```resolvesrvrecords=false```
And joined to server without problems. Thanks for help!

**Comment by ORelio** [comment]
Well that's weird, that would mean the SRV record exists, does not resolve to the actual server, and needs to be ignored in order to connect to the right server. At least your could solve your issue, but that was in an unexpected way :sweat_smile:
