### ISSUE TITLE
Exit On Failure isn't working with lost connection

### ISSUE THREAD

**Issue by MattCowley** [ORelio/Minecraft-Console-Client#268]
Hey,

So I have exitonfailure set to true in the config file, but whenever the account loses connection to the server, the client does not quit?

**Comment by ORelio** [comment]
Please use latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), set `debug=true` in config, and provide full output. Thanks!

**Comment by MattCowley** [comment]
With debugmessage=true on, this is what i get when i get kicked https://gyazo.com/7581e48c117143f08ecab81527c6c3f1 nothing else and the window doesn't close.

**Comment by ORelio** [comment]
Well, was expecting more details thanks to the debug setting, but I'll try to reproduce. Thanks for your report!

**Comment by MattCowley** [comment]
Further screenshot, still just as useful: https://gyazo.com/2116a7f44763b67df6fa2b84d89dd304

**Comment by MattCowley** [comment]
Just as an update, as soon as i interact with the window by typing anything at that stage it then does close.

**Comment by ORelio** [comment]
This should be resolved in the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), please check it out. Thanks for your report :)

**Comment by MattCowley** [comment]
Yup working, thank you very much!

 


  <http://mattcowley.co.uk/me-trace.png> 

	Matt Cowley 
Website & Graphic Designer / Theatre Technician / Radio Programme Controller 

07507 037511 |  <https://twitter.com/MattIPv4> @MattIPv4 
 <mailto:me@mattcowley.co.uk> me@mattcowley.co.uk |  <http://mattcowley.co.uk/> mattcowley.co.uk

**Comment by ORelio** [comment]
Great! Closing the issue, in that case :)
