### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by iNateDaPanda** [ORelio/Minecraft-Console-Client#269]
I installed the certificates and everything, but it just returns
```
Minecraft Login failed : Incorrect password.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
```
It works fine on my home pc, it's hosted on a DigitalOcean Debian 8 (Jessie) VPS.
I don't have any proxies to test if it's blocked, `curl https://authserver.mojang.com` returns
```
{"Status":"OK","Runtime-Mode":"productionMode","Application-Author":"Mojang Web Force","Application-Description":"Mojang Authentication Server.","Specification-Version":"2.30.14","Application-Name":"yggdrasil.auth.restlet.server","Implementation-Version":"2.30.14_build31","Application-Owner":"Mojang"}
```

Installing the certs returns
```
Downloading from 'https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt'...
Importing certificates into user store...
1 new root certificates were added to your trust store.
Import process completed.
```

I've even tried multiple accounts, I've waited a few hours and it still won't work.

**Comment by Pokechu22** [comment]
Does your password contain any special characters?  (don't post your actual password, just say whether it does)  "Incorrect password" (usually) indicates that it reached the server but the server didn't like what it got.

**Comment by iNateDaPanda** [comment]
No, it doesn't.
It just has numbers & letters.

**Comment by Pokechu22** [comment]
Are you passing the password via command-line arguments, or in the console itself?

**Comment by iNateDaPanda** [comment]
The console itself

**Comment by ORelio** [comment]
There may be issues depending on the keyboard layout as the prompt is custom made. Please try with password in config file or as a command line argument, to try narrowing the issue :)

**Comment by iNateDaPanda** [comment]
I've tried both.

**Comment by iNateDaPanda** [comment]
Wait, how would I do it as a command line argument?

**Comment by Pokechu22** [comment]
MinecraftClient.exe username password server command

is the full command line; you can skip server and command though.  So for example:

<pre>MinecraftClient.exe YourName <a href="http://www.bash.org/?244321">Hunter2</a></pre>

**Comment by iNateDaPanda** [comment]
Still says incorrect

**Comment by BinaryBandit** [comment]
Hi, thought i would weigh in with an almost identical problem for additional data.  Here's what i did and the results:

- Enabling debug on the newest dev version produced no additional results from the errors he was getting
- If i enabled a proxy, the program would crash instantly out of mono with no other results than
`
Connecting to Minecraft.net...
` and then proceeding to crash and put be back into the terminal line.
- I changed password complexity down from 30 characters to a simple password with 6 characters with no success.
- I tired two different accounts to no avail.
- I tried multiple server IP's (Not that should make a difference here as the problem is auth, but it never hurts to be thorough) 

This might just be an issue with mono or authing from VPS's in general. I run an OVH box instead of DigitalOcean with Ubuntu but am still getting the same error. Wish i could provide more but I'm just not getting proper output for debugging.

**Comment by GLadithon** [comment]
I'm getting the same issue with an OVH VPS

**Comment by ORelio** [comment]
Hello, just added login request and response raw json debug messages, that you can enable using `debugmessages=true` in INI file. You should get something like this if everything goes well:
````
Console Client for MC 1.4.6 to 1.11.2 - v1.11.0 DEV - By ORelio & Contributors
Login : login@email.com
Password : <******>
Connecting to Minecraft.net...
Login Request: {"agent": { "name": "Minecraft", "version": 1 }, "username": "login@email.com", "password": "MyL33tP4swd", "clientToken": "********************************" }
Login Response: {"accessToken":""********************************"","clientToken":"02215e8507844722ad2065cb48219de6","selectedProfile":{"id":"********************************","name":"PlayerName"},"availableProfiles":[{"id":""********************************"","name":"PlayerName"}]}
Success. (session ID: "********************************")
Server IP :
````
Of course if you paste JSON debug messages please at least redact tokens and passwords.

**Comment by iNateDaPanda** [comment]
I enabled debugmessages=true in the latest dev build but it doesn't output any more info...?

**Comment by ORelio** [comment]
That's not supposed to happen, make sure you are using the latest dev build and the configuration file has the correct name and is placed in the correct folder. If necessary, you may user `mono MinecraftClient.exe /path/to/my-config.ini` to explicitly specify the configuration file to load. If you get empty lines, maybe the debug lines are displayed with the same colors as your background as the color for non-important and debug messages is dark gray.

**Comment by GLadithon** [comment]
Done the above and noting shows in the console

**Comment by ORelio** [comment]
Just can't figure out why. It works on my side, it also works on xdMatthewbx's side (see #270). 😕
