### ISSUE TITLE
SRV records feature prevents joining some servers

### ISSUE THREAD

**Issue by xdMatthewbx** [ORelio/Minecraft-Console-Client#270]
I tested it works on non-bungeecord however I get this error when connecting to bungeecord servers: https://mix1337.gyazo.com/ae647c7d258971624873a8d1c69f0a98

Any ideas?

**Comment by ORelio** [comment]
Please use latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), set `debug=true` in config, and provide full output. Thanks!

**Comment by xdMatthewbx** [comment]
didnt show much else but heres a screenshot https://mix1337.gyazo.com/43c6f499742106d84b8f8e87633e3af3

**Comment by xdMatthewbx** [comment]
I'm connecting to 2b2t.org but I also checked mc.hypixel.net

**Comment by xdMatthewbx** [comment]
nvm i fixed it by changing resolvesrvrecords to false in the config

**Comment by ORelio** [comment]
Well sorry for the login output that was for another issue 😅
Regarding the SRV records setting, switching it to false means there is another issue there.

**Comment by TheSnoozer** [comment]
This issue seems to be resolved (or at least working somewhat now).
Based on the age and the status I'll close it as part of an issue cleanup.

Feel free to reopen if you still have this problem.
