### ISSUE TITLE
auto command on join

### ISSUE THREAD

**Issue by wobby123** [ORelio/Minecraft-Console-Client#272]
is there a way to run a common on join, ive used the script but you have to do /script so might as well do the command myself...

**Comment by ORelio** [comment]
The ScriptScheduler has this feature. See [README](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt) and [sample-tasks](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini).

**Comment by TheSnoozer** [comment]
Since there is a response given and this issue is inactive for quite some time, I'm closing it as part of an issue cleanup. Feel free to reopen if you still got a problem in getting this sorted. otherwise please open a new issue.
