### ISSUE TITLE
Interact with chest?

### ISSUE THREAD

**Issue by MattCowley** [ORelio/Minecraft-Console-Client#273]
Hey,

Would it be possible to add a way to interact with a chest and the player inventory. So that I can take items from a chest to my inv and then sell them?

Matt.

**Comment by ORelio** [comment]
Well, that's pretty complicated. Please refer to #205 since there's already an issue for that :wink:

**Comment by MattCowley** [comment]
Ah okay. Not to worry. Even just player inventory would be useful.
