### ISSUE TITLE
Anyway to render chunks further away!

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#274]
Hey, so I have been using console client for a long period time now. I have always noticed that you can only render about 1 chunk away from the bot. I was wondering if there was any possible way to change this so it can be 4+ chunks away! This would be very nice for scripts that get block types and more.

**Comment by ORelio** [comment]
Chunks sent by server are stored in memory and available, unload only occurs if the server tells MCC to do so. So it depends on what the server sends. You may want to try altering the `renderdistance` setting but if I recall correctly this only affects chunk unloading.

**Comment by AppleCidar** [comment]
Sorry, but I am not seeing a `renderdistance` setting. Is it in minecraftclient.ini?

**Comment by AppleCidar** [comment]
Ya, max I can make it work is around 75 blocks. Anyways, thanks for your help!

**Comment by ORelio** [comment]
Great :) For more details about chunk loading, you can read #140 ;)
