### ISSUE TITLE
Mono 5.x connection lost

### ISSUE THREAD

**Issue by alexlab963** [ORelio/Minecraft-Console-Client#276]
Hey,

I was using the console client on my  main windows pc and it worked just fine.
Today i decided to run it on raspberry pi so i can afk overnight, however every time it connects to the server  it shows a connection lost message and the whole thing restarts. Any suggestions?

**Comment by ORelio** [comment]
Use mono v4.0 or greater. Lower versions have weird issues like this one.

**Comment by alexlab963** [comment]
It shows that i am running version 5.0.1.1

**Comment by ORelio** [comment]
Well I never tested MCC on 5.x so I have no idea about what is going wrong, sorry 😅

**Comment by alexlab963** [comment]
So should i downgrade and see if it works any better?

**Comment by alexlab963** [comment]
After a lot of effort i managed to downgrade to 4.0.5, it seems to work good so far, i will let you know if there are any other problems.
Thanks for the client :)

**Comment by ORelio** [comment]
Hello, thanks for your feedback, that's very weird that recent Mono versions have this issue again, but I'm glad that your could fix it by switching to Mono 4.x. So Mono 4.4-4.2 stays the [recommended version range](https://github.com/ORelio/Minecraft-Console-Client/blob/ffb1adeb4da93275e1432b30ba22b0c5228991f9/MinecraftClient/config/README.txt#L22) for MCC. I'll add "random disconnections" in the README for Mono issues :)

What is the log issue?

**Comment by alexlab963** [comment]
It simply doesnt show, i can read the server  messages just fine but the messages from the client do not appear.

**Comment by ORelio** [comment]
Make sure the `filter` settings does not filter out user messages in `[ChatLog]` in your INI file.
