### ISSUE TITLE
CleverBot in Console Client?

### ISSUE THREAD

**Issue by Cannuner** [ORelio/Minecraft-Console-Client#280]
i think it would be cool to have a clever bot in console client, as i code discord bot and know a thing or two about c# i think it would be a great idea to see it come to the surface. Here's a link to a popular CleverBot https://github.com/Sorashi/Cleverbot.Net this could be modified to fit in console client using tasks.ini?

**Comment by Pokechu22** [comment]
You could probably do this using a C# script (though, since it's an external library, that may be somewhat complicated).  `tasks.ini` probably would not work.
