### ISSUE TITLE
[Bug] Parsing escaped control characters (\n)

### ISSUE THREAD

**Issue by fixator10** [ORelio/Minecraft-Console-Client#281]
Works not right
![Screenshot](https://Moeka.is-a-good-waifu.com/40634d.png)
**What must do:**
Switch to next line

**What does actually:**
Just shows `n`

**Comment by ORelio** [comment]
Hello fellow Cmder user :smiley:
Thanks for your report, will take a look!

**Comment by Pokechu22** [comment]
If I recall correctly, sending `\n` in chat components causes issues on the notchian client as well (it mostly works, but it runs into some problems with word wrapping I think) - if you have control over the plugin, try to get it changed.  Though the fact that it isn't escaped here still is a problem.

**Comment by ORelio** [comment]
Added support for `\n` Json escape sequence, and allowed line breaks while printing chat messages.
Please try out the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) :)

**Comment by fixator10** [comment]
Seems fine now
![Seems fine now](https://Moeka.is-a-good-waifu.com/7aea7f.png)
