### ISSUE TITLE
Matches how to grab the message a user sends

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#282]
Hey, I was wondering if/how to grab the whole message the user sends in a private message. I need this so I can just message my alt and tell it how much to pay like `/tell <alt> /pay 32621`

**Comment by ORelio** [comment]
Use AutoRespond with a regex and capturing groups just as shown in [sample-matches.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-matches.ini). In your case for your custom RemoteControl command you would want something like this:
````ini
[Match]
regex=^pay ([0-9]+)$ # If you /tell <alt> pay 123...
actionprivate=send /pay $u $1 # ...the bot will perform /pay AppleCidar 123
ownersonly=true # Ensure only bot owners can get paid from your bot
````
Make sure ChatFormat is properly set in your INI file, MCC must be able to properly parse private messages to allow for `actionprivate` and `$u` to properly work.

**Comment by AppleCidar** [comment]
Thank you! It works perfect!
