### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by treehugger2790** [ORelio/Minecraft-Console-Client#283]
Is it possible for something like your watch lamps script to make it so that it can send maybe a skype or other platforms alerts when the lamp goes off? I'm completely new to this kind of thing so please try be as simple as possible xd

**Comment by MattCowley** [comment]
I think there is an exmaple script for checking a block. Just use that and then hook into an api.

**Comment by ORelio** [comment]
As @MattCowley says, once you have your ChatBot, you need to call an API just like you would do in plain C#. Never done that with Skype before, so I cannot provide additional hints.
