### ISSUE TITLE
Flying is not enabled on this server (1.12)

### ISSUE THREAD

**Issue by TNTUP** [ORelio/Minecraft-Console-Client#285]
Heya! Downloaded the source code and compiled, when I log one of my accounts on my 1.12 test server (terrain movements enabled) they get kicked for flying despite being on the ground. Tried several other accounts on 1.12 and sometimes gets kicked for flying and some not. Never happened in 1.11.2, idk if something changed between 1.11 and 1.12 :/

Noticed aswell when the player falls down slowy in 1.11 (I guess thats normal for me?) they go fast at the ground in 1.12.

I notice when they log on, I see them flying by one block (Guess its my spawnpoint issue) but when I do tp the player to me it gets kicked (probably MCC timedout) because I guess too much things to "download" or idk else. The test server is a newly generated world with lots of trees so idk if its plugin related or chat :/

PS: I suck at explaining things, I hope you'll understand what I mean.

**Comment by Pokechu22** [comment]
Can you try compiling the 1.11.2 build right before my 1.12 changes (214f8a23dac6f5d9106e590e29fed7403c182994)?  It's possible that I broke movement, but it's also possible that it was broken before and just never noticed.

**Comment by TNTUP** [comment]
Hi @Pokechu22, I did a test with the last commit and the one I used since Aug 24 or the 28th (last compilation date)

![test](https://i.qcfb.ca/20170611040303.png) 
and here the video of it: https://i.qcfb.ca/java%202017-06-11%2004-07-06.mp4

I'll return with that version for 1.11.2 and reporting back if it still occurs. Happens again in 1.12, moar testings xD

**Comment by ORelio** [comment]
What you are seeing on the left side is "normal" it is the result of much work in #195 in order to produce realistic falling just like the vanilla client does. The main point was that advanced anti-cheat detectors were preventing the old/slow falling method from working (on the right in your video).

**Comment by TNTUP** [comment]
Well, that causes flying not enabled on my 1.12 test server, never happened when I tried MCC in 1.11/1/2. 

Not sure if any workarounds I can guess, either reverting that change myself or allow flying but that'll be bad for my community XD
