### ISSUE TITLE
Accounts cycle

### ISSUE THREAD

**Issue by alexlab963** [ORelio/Minecraft-Console-Client#286]
Hey, i was wondering, is there any way that mcc can cycle through accounts after a given time?

I came up with the following script (which is really bad), since my accounts are named based on numbers (ex: player1, player2 etc) I using a for loop and an internal command (reco player#) would do the trick, however i do not understand how i am supposed to use internal commands since i am not familiar with the use of APIs

```
 for (int i = 1; i < 51; i++)
{
   ///Internal command goes here///
    MCC.LogToConsole("Logged in as player" + i);
    Thread.Sleep(300000);
}
```

Edit:

This seems to work for my purpose
```
//MCCScript 1.0
int i = 1;
while (i<52)
{
	if (i<51)
	{
		MCC.PerformInternalCommand("reco player" + i);
		MCC.LogToConsole("Logged in as player" + i);
		Thread.Sleep(300000);
		i++;
	}
	else
	{
		MCC.LogToConsole("All players logged in");
		i = 1;
	}
}	

```

**Comment by ORelio** [comment]
Yes, that's a way of doing it. There is not builtin support for that so a script seems the best way.

**Comment by alexlab963** [comment]
So if the account fails to connect /reco is not recognized therefore the scripts becomes useless until i restart it. Would using SetAccount fix this?

**Comment by ORelio** [comment]
Yes use `SetAccount("myAccountAlias", true)` that should always work.

**Comment by alexlab963** [comment]
Running the script works fine on my windows pc however it gives me the following [error ](https://pastebin.com/kuNm7kLH)on my raspberry pi

**Comment by ORelio** [comment]
Seems like compiling your script did not work because the file was not found. Please check where your script is located relatively to the working directory for MCC. Eg try placing it as `cycle.cs` in the same directory as MCC, then use `mono MinecraftClient.exe` and try `/script cycle.cs`?

**Comment by alexlab963** [comment]
No luck, all of my scripts are placed in the same directory as the  MCC. in fact i copied the working folder from my windows and transferred it to my raspberry pi. Interestingly trying to run random scripts returns no errors

**Comment by ORelio** [comment]
Weird. Try verifying the path for MCC does not contains spaces nor non-ASCII characters, just in case? Eg `pwd` in MCC's directory should return `/home/raspberry/mcc/` or something similar. Finally, Mono has been reported to cause various issues depending on its version and v4.0 to v4.2 is the recommended range for `mono --version`. Usually, low versions can crash, and low/high versions can cause silent disconnections. However I'm not sure your issue is specifically tied to the mono version being used...

**Comment by alexlab963** [comment]
`pwd` returns /home/pi/desktop/mcc/ which means its fine, my mono version is 4.0.5.1 which is in the recommended range. I also tried mono 4.2 but got the same error

**Comment by ORelio** [comment]
I'm starting to get out of suggestions as I've never seen this error before. Try making a very simple script and add more things step by step in order to determine what in the script causes the error.

**Comment by alexlab963** [comment]
Well, It looks like that the error just stays there no matter what, i only left the MCC header and it still gave me it. Maybe it cant compile for some reason?

**Comment by ORelio** [comment]
So whatever you do, no script works? In that case maybe the compiler is missing, indeed.
From https://packages.debian.org/wheezy/mono-complete:
Try installing the `mono-dmcs` package.

**Comment by alexlab963** [comment]
It seems to work fine right now
