### ISSUE TITLE
Suffix + Prefix

### ISSUE THREAD

**Issue by 3840px** [ORelio/Minecraft-Console-Client#287]
Hi there, 

Using remote control doesn't work when the "Bot owners" have a prefix or a suffix on the server.

Is there a way to get around this?

**Comment by ORelio** [comment]
Adapt your chat format regexes. See #238 for instance.

**Comment by 3840px** [comment]
How do you use the Regexes correctly?

**Comment by 3840px** [comment]
Say i wanted this... 

[[Prefix]3840px[Suffix] -> Me] Hello

**Comment by alexlab963** [comment]
You can use this 
`^(\[)([a-zA-Z]+)3840px([a-zA-Z]+) (-> Me)(\]) (.+)$`

**Comment by 3840px** [comment]
I added that into my [chatFormat] and it didn't seem to work, even after I removed the brackets to leave the [ ] brackets 

[ChatFormat]
builtins=true #support for handling vanilla and common message formats
#public=^\[\[[a-zA-Z]+\]([0-9a-zA-Z]+)\[[a-zA-Z]+\] (.+)$ 
private=^\[\[[a-zA-Z]+\]([0-9a-zA-Z]+)\[[a-zA-Z]+\] -> (me)\] (.+)$ 
tprequest=^\[\[[a-zA-Z]+\]([0-9a-zA-Z]+)\[[a-zA-Z]+\] has requested (?:to|that you) teleport to (?:you|them)\.$


Making private chat being this... 
[[Rank1]3840px[Suffix] -> me] send test

Ignoring the public as I don't use it. However, for some reason that still doesnt work for me?

**Comment by ORelio** [comment]
For private messages of the provided format I'd say something like this:
````
^\[(?:\[[^\]]+\])?~?([0-9a-zA-Z_]+)(?:\[[^\]]+\])? -> Me\] (.+)$
````
This should handle all the corner cases including lack of prefix/suffix, nickname...
Try it: https://regex101.com/r/9vwVya/1

**Comment by TheSnoozer** [comment]
Since the question was answered a while ago, I'm closing this as part of an issue cleanup. Feel free to reopen if you still have any problems in getting this setup. Otherwise please open a new issue.
