### ISSUE TITLE
GetText(text, json)

### ISSUE THREAD

**Issue by MattCowley** [ORelio/Minecraft-Console-Client#288]
The GetText(text,json) is throwing the following error with leave/join messages:

```
Collided Left
GetText: Got error from ScriptLoader.Script+RemoteBot: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ScriptLoader.Script.RemoteBot.GetText(String text, String json)
   at MinecraftClient.McTcpClient.OnTextReceived(String text, Boolean isJson)
```

**Comment by ORelio** [comment]
The builtin `GetText()` method does nothing at all:
````C#
public virtual void GetText(string text, string json) { }
````
The issue is probably in what you implemented in your own `GetText()`.
To find out what's wrong I'd advise to save the raw json string triggering the issue.
Eg with a try-catch block:
````C#
public override void GetText(string text, string json)
{
    try
    {
        //Your code here
    }
    catch (IndexOutOfRangeException err)
    {
        LogToConsole("IndexOutOfRangeException while processing JSON: " + json);
        LogToConsole("Detail: " + err);
    }
}

**Comment by MattCowley** [comment]
No where in my code uses the json so I see no cause of the error. I have tried the try catch yet.

**Comment by MattCowley** [comment]
[MCC] [RemoteBot] JSON: {"extra":[{"color":"blue","text":"_Logic301 Left"}],"text":""}
[MCC] [RemoteBot] Err: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ScriptLoader.Script.RemoteBot.GetText(String text, String json)

**Comment by MattCowley** [comment]
That's all your try catch gives

**Comment by ORelio** [comment]
Would you mind giving a crashing example so that I can try your code on my side?

**Comment by MattCowley** [comment]
Update it was me being stupid. I thought something was inside an if when it wasn't, which was causing the issue.
