### ISSUE TITLE
Server Connection Dropped causes a "freeze state" on the client

### ISSUE THREAD

**Issue by Barnehhh** [ORelio/Minecraft-Console-Client#291]
Title says it all, in the event that the server the MCC client is connected to crashes, or the connection is unexpectedly dropped, the client seems to go in a state where the chatbot did not detect that the connection was lost. The manual way to update it was typing into the console client window, but in terms of AutoRelog and any other chat bot everything will stop working unless those manual commands are typed into the window. 

One personal fix I found for it was to have another thread (I have a factions raid alert thread running with discord) constantly checking the state of the TcpClient and restarting if it drops, but as it's another background thread on my version it's not really a viable solution for some friends of mine who use the normal console client.

Would you have any thoughts on this? I'm not at all the most experienced in C#, but I hope this outlines the issue briefly. I'm sure it can be replicated on a local server simply by terminating the server (without stopping it normally and having it send the disconnect)

**Comment by MattCowley** [comment]
Yup I have seen this before, really really annoying cause it won't reconnect.

**Comment by Barnehhh** [comment]
Seems to be fixed in #313

**Comment by Pokechu22** [comment]
I can safely say that #313 wasn't intended to fix that, and it doesn't seem to have fixed it either.  I use MCC to test [MC-106551](https://bugs.mojang.com/browse/MC-106551) each snapshot, and just now (ironically, actually more or less exactly when you posted that) the same issue happened to me.

**Comment by Barnehhh** [comment]
Glad attention was brought to it then, it seems to have been fixed on the specific server I've been using console client on. (This issue at the time was only specific to one server)
