### ISSUE TITLE
Checking Session

### ISSUE THREAD

**Issue by ktr0x** [ORelio/Minecraft-Console-Client#292]
I am trying to use the latest version of Minecraft Console Client for 1.5.2 Hexxit. I have noticed this client is compatible with Forge and I wish to use this functionality, however, the client gets stuck on 'Checking Session' and does not leave that state. The server version is MC 1.5.2 (protocol v61).
Thanks.

**Comment by Pokechu22** [comment]
Forge was implemented for the 1.7+ protocol handler, but I don't think versions prior to 1.7 are handled.
