### ISSUE TITLE
Retrieving Server Info...

### ISSUE THREAD

**Issue by Alwardi** [ORelio/Minecraft-Console-Client#296]
I log in the console cleint and it just says retrieving server info and never actually logs i
![image](https://user-images.githubusercontent.com/30464570/28615102-cf7055b8-71ac-11e7-9ad6-90794b8fe60f.png)

**Comment by Alwardi** [comment]
and then this

![image](https://user-images.githubusercontent.com/30464570/28615250-527a6f3e-71ad-11e7-817d-b870e5edcea9.png)

**Comment by ORelio** [comment]
You are using an old version. See [development builds](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by Alwardi** [comment]
well this is the latest one
but still 
![image](https://user-images.githubusercontent.com/30464570/28634541-5a5c80fe-71ec-11e7-8378-0164ba83341e.png)

**Comment by ORelio** [comment]
Seems like the server ping is disabled so MCC cannot determine server version. Try manually specifying server version in the Server version prompt or in the configuration file.

**Comment by Alwardi** [comment]
ill try that thank you

**Comment by Alwardi** [comment]
Can you show me how to do that please?

**Comment by ORelio** [comment]
You are prompted to type a Minecraft version. Simply type a Minecraft version such as `1.12` or `1.11.2` and press Enter. That's it.

**Comment by Alwardi** [comment]
OMG , didnt know that it was that simple ty it worked

**Comment by ORelio** [comment]
Great! You can edit the configuration file that comes with MCC (`MinecraftClient.ini`) and edit the `mcversion` line to avoid typing the version every time. :wink:
