### ISSUE TITLE
Making this into a library

### ISSUE THREAD

**Issue by beppe9000** [ORelio/Minecraft-Console-Client#298]
Maybe the code code could be reorganized to make it easier for a developer to add minecraft chat integration by referencing the compiled assembly of this client? I for example was hoping to find some public module that allowed me to create a client object and register a chat handler without editing the code. For exampl an "OnChat" event.

**Comment by ORelio** [comment]
Currently this is not possible as there is no API, however you can programmatically launch the exe file, see how the GUI works.

**Comment by beppe9000** [comment]
I ripped the I/O redirect class from the GUI. Anyways wrapping a separate process is not exactly the cleanest solution as it adds unnecessary complexity to the setup.

**Comment by ORelio** [comment]
MCC has never been developed with a library in mind, but as usual if you thing that would be very useful to you, I'm still open to contributions. Cannot do every request myself, sorry.

**Comment by beppe9000** [comment]
i think i will contribte the necessary refactorings in the future
