### ISSUE TITLE
a way to send packets?

### ISSUE THREAD

**Issue by beppe9000** [ORelio/Minecraft-Console-Client#299]
Let's say I want to move the player and click inventory slots. Is there a way to tell the client to send those packets?

*If this was a library (#298) i would be using reflection and call the sendpacket method of the current protocol handler.*

**Comment by ORelio** [comment]
No. But if you could implement all those packets I'd gladly include your contribution directly in MCC.
Also, you can use C# ChatBots to execute code in MCC. There is a C# bot API.
See #205 for inventories :wink:

**Comment by beppe9000** [comment]
right now i will be trying some ugly solutions
