### ISSUE TITLE
record and playback of other player movements

### ISSUE THREAD

**Issue by beppe9000** [ORelio/Minecraft-Console-Client#302]
I think such a feature would be of great help to those who want to enter servers with complicated lobbies.
So two command should be needed: `/record playername` and a `/playback pathfile.txt`.

An idea for this could be to accurately measure the selected player entity updates and store them as a list of `/teleport` commands. The `/teleport` command should have 4 arguments like this: `/tp X Y Z SLEEP`.

The sleep argument is an optional delay in milliseconds to accurately reproduce the timing of the other player movements.

**Comment by ORelio** [comment]
Seems interesting. Meanwhile you can use `/move x y z` but of course it automatically computes a path which will not necessarily fit your needs. You can use a script with `/move <north|south|east|west>` and `/wait` instructions to mimick this behaviour.
