### ISSUE TITLE
Incorrect Password running CC on VPS

### ISSUE THREAD

**Issue by TheHeat361** [ORelio/Minecraft-Console-Client#303]
I am trying to run console client on a Ubuntu 14.04 vps and I am not able to login. I am to the part where I enter login info and it always says incorrect password. I have tried using the ini and typing it myself. I am running mono 5.0.1 since it will not let me install 4.0-4.2. I use virmach vps.

**Comment by TheHeat361** [comment]
Tried using debug messages but not seeing anything

**Comment by TheHeat361** [comment]
Also am able to login fine on regular console client, but the one on the VPS does not work. Could it be the VPS host?

**Comment by ORelio** [comment]
This is the same issue as in #279 so I'll close this one, please reply on the other issue :wink:
