### ISSUE TITLE
/move

### ISSUE THREAD

**Issue by BlueDemonic** [ORelio/Minecraft-Console-Client#304]
so i started on a new factions server and on this one you have to move to do a command and theres a hub so i was wounding if someone could help me make a script so it does /move whatever /server factions or will this not work

**Comment by ORelio** [comment]
See [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/blob/ffb1adeb4da93275e1432b30ba22b0c5228991f9/MinecraftClient/config/README.txt#L192) and [sample-tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/ffb1adeb4da93275e1432b30ba22b0c5228991f9/MinecraftClient/config/sample-tasks.ini).
The script can be a list of `/move` commands in a text file.

**Comment by TheSnoozer** [comment]
Since the question seems to be answered (and quite old) I'm closing this as part of an issue cleanup.
Feel free to reopen if you still have a problem with this specific issue. Alternatively please open a new issue.

**Comment by zzombiekiller** [comment]
Hello I was also wondering about this how do I get a /move command for the client?
