### ISSUE TITLE
How can you read server messages?

### ISSUE THREAD

**Issue by AppleCidar** [ORelio/Minecraft-Console-Client#310]
So I was wondering if it is possible to pickup a server message such as `Server restarting in 5 minutes` I wanna pick up that message then have it start another script.

**Comment by Barnehhh** [comment]
I've been using the GetText method within chatbots to pick up on things like this. Not specifically for telling the client to run a script, but I'm sure it's manageable.

**Comment by ORelio** [comment]
Seems like you're looking for [AutoRespond](https://github.com/ORelio/Minecraft-Console-Client/blob/ffb1adeb4da93275e1432b30ba22b0c5228991f9/MinecraftClient/config/README.txt#L225). See also: [sample-matches.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-matches.ini). :wink:

**Comment by TheSnoozer** [comment]
Since this question seems to be answered I'm closing this issue as part of an issue cleanup. Feel free to reopen if you still have problems in getting this setup.
