### ISSUE TITLE
Can't connect to a server

### ISSUE THREAD

**Issue by Siriusly** [ORelio/Minecraft-Console-Client#312]
I can connect to servers except for one, and I get this error : "System.Net.Sockets.SocketException: The requested name is valid, but no data of the requested type was found
Failed to ping this IP. 
Server Version : "
No matter what server version I put, even the correct one, it doesn't work. I've attempted to read up and see if anyone has had this problem, but I haven't had any luck.

**Comment by ORelio** [comment]
Seems like there is an issue with DNS SRV records.
Does setting `resolvesrvrecords=false` in your INI file resolve the issue?

**Comment by Siriusly** [comment]
There was no such option in the INI, and I tried putting what you put in, and there was no change. I even tried the dev release.

**Comment by ORelio** [comment]
Delete the INI file and launch the latest dev, it will generate a new one for you.

**Comment by TheSnoozer** [comment]
Since there wasn't any responses in this issue, I'm closing it as part of an issue cleanup.
Feel free to reopen it if you still have problems in getting this sorted.
