### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by Marsietis** [ORelio/Minecraft-Console-Client#315]
Hello can you say all guide how connect to vps?

FOr examle: what version use howt tu run and others 

Tx

**Comment by ORelio** [comment]
Just for reference: You can see #163 and #174 ([here](https://github.com/ORelio/Minecraft-Console-Client/issues/163#issuecomment-226483646) and [here](https://github.com/ORelio/Minecraft-Console-Client/issues/174#issuecomment-237163828)) :wink:
