### ISSUE TITLE
Zombie Pigmans dont stay aggressive

### ISSUE THREAD

**Issue by Ordust** [ORelio/Minecraft-Console-Client#316]
Hey :) 

i'm using MCC for afk-loading my Goldfarm on an Skyblock server. I really want the zombie pigmans to stay aggressive to be more productive. 

But with the MCC the Pigmans doesnt stay aggressive.. could you fix that ? 

Thank you :) 

Ordust

**Comment by ORelio** [comment]
Try enabling terrain and movements, that might help.

**Comment by Ordust** [comment]
How can i enable terrain and movements ? I'm sorry, i cant find any options with terrain and movements :(

Thank you ♥

Ordust

**Comment by Ordust** [comment]
Thank you very much ! 

♥♥♥
