### ISSUE TITLE
Disconnecting on Raspberry Pi

### ISSUE THREAD

**Issue by 5tanly** [ORelio/Minecraft-Console-Client#317]
I have 5 accounts that I am trying to run 24/7 on a Raspberry Pi 3 B and when I tried opening 5 MCC windows the thing overheats and has like 100% memory usage. So then I boot into CLI mode so the pi isn't rendering a GUI and when I open the first MCC it connects fine, second MCC however connects and then disconnects and keeps doing that until I shutdown the pi. It also starts getting hot when I run multiple instances.

Whats the best OS or settings to run 5 MCC on a pi without blowing it up. My laptop is dying from running this 24/7

**Comment by Mhowser** [comment]
Can you provide a log via pastebin? It can show us why it is disconnecting and reconnecting in a loop. As for the overheating issue, make sure the Terrain setting is set to "false".

**Comment by 5tanly** [comment]
i might be an idiot right now but i cant find any log files in the ConsoleClient folder

**Comment by 5tanly** [comment]
I ran it on the GUI mode of my rpi3 (startx) and it didnt loop around. But when I run it throught SSH using tmux it starts looping

*not always tho, right now as im trying it, it connects just fine

**Comment by 5tanly** [comment]
sorry for kinda spamming this thread but I managed to get all 5 accounts running but it was a struggle, sometimes the MCC keeps looping and then connects, and other times it just connects the first time

**Comment by Mhowser** [comment]
I forgot to mention that you need to set debugging to true in your settings file in order to generate a log file.

**Comment by 5tanly** [comment]
So playing around with it more and I figured out that spamming a couple commands keeps the MCC from disconnecting in a loop, maybe I'm just getting lucky but its working so far.

ill get your log tomorow

**Comment by 5tanly** [comment]
I updated to the newest version and its working fine
