### ISSUE TITLE
Can't support Chinese

### ISSUE THREAD

**Issue by hou0122** [ORelio/Minecraft-Console-Client#320]
Good RAM usage amount~ https://imgur.com/teDAmOf

Can't support Chinese ,some character Cut off https://imgur.com/Kc8rnmt

**Comment by ORelio** [comment]
MCC is only using `10MB` in your screenshot.
For Chinese characters, try the latest [dev build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), it has 1a2e86e684d7bd1aa491db914828e3b2ad12a6ce which fixes an encoding issue.

**Comment by hou0122** [comment]
Still the same some character Cut off https://imgur.com/iDLygv8
