### ISSUE TITLE
Crashing when opening multiple MCC

### ISSUE THREAD

**Issue by 5tanly** [ORelio/Minecraft-Console-Client#322]
I have a python script that runs 6 console clients all at once, and they always crash and cannot stay connected to the server, I have to go into each of these windows and type "/server witch" to connect to a server on the server..? :P Then sometimes it will connect and stay connected. I want to run a python script on boot to open all these but they keep crashing

**Comment by Barnehhh** [comment]
What do you mean by crashing, as in they don't connect to the server you want or the window simply closes?

If it's failing to connect to a server, I'd suggest going into MinecraftClient.ini under the version setting and change"auto" to the minecraft version the server you're connecting to is on.

Nowadays I find auto-detecting a server's version info on MCC failing 90% of the time and it requires the version input to be done in the config manually.

Although if it's a different issue I'd be interested about that too. :)
