### ISSUE TITLE
How to join a realm after reboot

### ISSUE THREAD

**Issue by iNucleaR9** [ORelio/Minecraft-Console-Client#324]
I join a server named SaiCoPvP and it has realms on it,I join the "skeleton" realm and my console client stays on that realm till the server reboots,when it reboots the console client keeps saying /server skeleton in chat but it doesnt join that realm,how do I fix that ?

**Comment by Pokechu22** [comment]
I'm going to assume that the server's using bungee or a derivative of it for multi-server support (it's the most common one).

What is the output of just `/server` at these times:

* When you first join the server and are on the hub
* When you're on the "skeleton" realm
* When you're back on the hub after the "skeleton" realm reboots

**Comment by iNucleaR9** [comment]
Hey,when I type /server a window pops up with realms,and I have to click
the skeleton realm to join
But I can do /server skeleton too

Dana 26. ruj 2017. 22:42 osoba "Pokechu22" <notifications@github.com>
napisala je:

**Comment by Pokechu22** [comment]
Ah, ok.  I was hoping that this was bungee's default implementation where `/server` by itself gives you the current server and a list of servers, in the chat.  But a GUI isn't usable here.

**Comment by Edieee** [comment]
Try enabling your auto afk, and put send /server skeleton every idk 10 mins... i also play Saico

**Comment by Edieee** [comment]
You can find AutoAfk in you MinecraftClient.ini

**Comment by Edieee** [comment]
Or smthg like that

**Comment by TheSnoozer** [comment]
I happen to know this specific server and never had an issue with the console client using the ``/server [realm] command``

e.g. try adding a `ScriptScheduler` or `AutoRespond` the following worked without any issues:
> 
> # via `ScriptScheduler`
> 
> MinecraftClient.ini
> 
> ```
> [ScriptScheduler]
> enabled=true
> tasksfile=tasks.ini
> ```
> 
> tasks.ini
> 
> ```
> ﻿[Task]
> triggerOnInterval=true
> triggerOnFirstLogin=true
> timeInterval=60
> script=joinyourserver.txt
> ```
> 
> joinyourserver.txt
> 
> ```
> send /server [REALM]
> ```
> 
> # via `AutoRespond`
> 
> MinecraftClient.ini
> 
> ```
> [AutoRespond]
> enabled=true
> matchesfile=matches.ini
> ```
> 
> matches.ini
> 
> ```
> [Match]
> match=--------------------[Hub]--------------------
> actionother=script joinyourserver
> # or simply actionother=send /server [REALM]
> ```

**Comment by TheSnoozer** [comment]
I'm closing this since a response was given. Feel free to reopen if you still have any questions of problems in getting this setup. Otherwise please open a new issue.
