### ISSUE TITLE
OVH VPS not working with MCC

### ISSUE THREAD

**Issue by MattPlaysYT** [ORelio/Minecraft-Console-Client#326]
Whenever I use screen and do `mono MinecraftClient.exe` this error pops up
https://gyazo.com/ea8653689f9d63e71f3b20bbc343b715

But I know 100% that is the right password because it works on desktop and I just copied paste it onto WinSCP onto my VPS
I'm using Debian 7 (Wheezy) (64 bits) and Debian 9 doesn't work either.

**Comment by Pokechu22** [comment]
Does your password contain any special characters?

**Comment by MattPlaysYT** [comment]
No it does not just letters and numbers

**Comment by MattPlaysYT** [comment]
But the email contains "@"

**Comment by Pokechu22** [comment]
All of those symbols are ASCII so that should be fine (for more complex special characters there can be issues with encoding, particularly with ssh).  So that's probably not the issue.

**Comment by MattPlaysYT** [comment]
Ah ok, but for some reason my friend is using the same vps and it's working for him but not for me

**Comment by MattPlaysYT** [comment]
Any ideas?

**Comment by Pokechu22** [comment]
Try updating to the [latest development build](https://ci.appveyor.com/api/buildjobs/x8g8qas8oeiydfmr/artifacts/MinecraftClient%2Fbin%2FRelease%2FMinecraftClient.exe).

**Comment by MattPlaysYT** [comment]
Do I just delete the .exe I already have and replace it with that one?

**Comment by Pokechu22** [comment]
Yes.

**Comment by MattPlaysYT** [comment]
Still the same thing

**Comment by ORelio** [comment]
Try enabling debugmessages in the INI file to show raw authentication request and response.

**Comment by MattPlaysYT** [comment]
I did it’s jig showing anything in console

**Comment by ORelio** [comment]
You're supposed to get json output for auth request and response, see #269

**Comment by MattPlaysYT** [comment]
Not showing anything just the same thing.

**Comment by Pokechu22** [comment]
Does the message at the top when you start MCC say "Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV", or is it still "Console Client for MC 1.4.6 to 1.9.0 - v1.9.0"?

**Comment by MattPlaysYT** [comment]
Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors

**Comment by MattPlaysYT** [comment]
I have no idea why it’s doing this

**Comment by MattPlaysYT** [comment]
Any help?

**Comment by Edieee** [comment]
I resolved the same problem like this:
When you log into your account on another IP (VPS), mojang automaticly blocks your account on half an hour, and sonce then you can't login, (it is shown as Login Failed). Try waiting half an hour, than run in the ssh  `mono MinecraftClient.exe` and it should work.

**Comment by Edieee** [comment]
Don't run any script, just type that command.

**Comment by MattPlaysYT** [comment]
I'm not running any script also @Edieee ssh?

**Comment by MattPlaysYT** [comment]
nvm and I've tried waiting nothing

**Comment by MattPlaysYT** [comment]
Also can you please help me download the mono I need I unistalled mono @Edieee

**Comment by Edieee** [comment]
http://www.mono-project.com/download/
You cam download ot from here^.
Just choose the right version according to your ubuntu version.

**Comment by MattPlaysYT** [comment]
I’m using Debian would that cause the problem?

**Comment by Pokechu22** [comment]
You'd want to chose the debian version then instead of Ubuntu.

**Comment by MattPlaysYT** [comment]
Alright, because they said to use a certain version or something

**Comment by Pokechu22** [comment]
Well, you'll want to chose the version matching your debian version, but it's pretty simple still.

**Comment by MattPlaysYT** [comment]
I've did that and I'm still getting the error

**Comment by Edieee** [comment]
I don't know than... I cant't say anything wihout having a SSH.

**Comment by MattPlaysYT** [comment]
Any help then? Like what vps exactly I’m supposed to have and all of it I need to type once I have it installed

**Comment by Edieee** [comment]
MattPlaysYT you play on saico?

**Comment by Edieee** [comment]
I use BisectHosting VPS.. the commands you have  here #163

**Comment by MattPlaysYT** [comment]
Yes @edieee

**Comment by MattPlaysYT** [comment]
Also for the vps you linked above how will I run console clients on that?

**Comment by Edieee** [comment]
Same as debian. Same commands etc.

**Comment by Edieee** [comment]
Yeah sure add me Edi4Playᴸʸᶠ#8321

**Comment by MattPlaysYT** [comment]
Sent

**Comment by MattPlaysYT** [comment]
@Edieee helped me set it up! Working now can be closed @ORelio

**Comment by D3cide** [comment]
Are you able to show how to fix this?
