### ISSUE TITLE
"you can't execute a command in a container!"

### ISSUE THREAD

**Issue by imallhacks** [ORelio/Minecraft-Console-Client#327]
how do i make it so my character press esc in a script

**Comment by ORelio** [comment]
I don't understand your question. The esc key is only used in MCC when you interactively type commands in the command prompt, so you don't need it in scripts. What are you trying to do?

**Comment by imallhacks** [comment]
When I join a certain server it has a chest popup advertising something and i'd like to be able to exit it while on console client. Which when in a container it doesnt allow you to execute commands, I am wondering if there is a way i can exit the chest by esc then executing a command. I've been looking for about an hour and a half and I have found 1 person saying you cannot do something like this.

**Comment by Pokechu22** [comment]
Inventories aren't currently supported.  That said, closing inventories isn't too hard (just a [single packet](http://wiki.vg/Protocol#Close_Window_.28serverbound.29), although that depends on listening to the [window that's been opened](http://wiki.vg/Protocol#Open_Window) too), so it wouldn't be as difficult to implement as actually handling items in an inventory.

**Comment by imallhacks** [comment]
I want to exit a chest

**Comment by ORelio** [comment]
Hi,
Inventories are handled in the newest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) thanks to @ReinforceZwei 's efforts.
Although the feature is not fully polished, you can now use `/inventory` to close windows.
