### ISSUE TITLE
Mono

### ISSUE THREAD

**Issue by Edieee** [ORelio/Minecraft-Console-Client#330]
Hello there,
when I try to install mono, I type a`apt-get install mono-complete` but it says then Unable to locate package mono-complete. how can I find it?
thanks in advance,
Edi

**Comment by Pokechu22** [comment]
You need to add the repository to your system.  Information on that is available on [the mono download page](http://www.mono-project.com/download/#download-lin) (make sure you select the correct distribution and version).

**Comment by Edieee** [comment]
ok thanks i installed my console client and everything but when i start my console it says 
`./Script.bat
Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>
`

**Comment by ORelio** [comment]
Please enable debugmessages, see #269

**Comment by Edieee** [comment]
I did and It doesnt say nothing

**Comment by ORelio** [comment]
Try using a screen with the "screen" package.

**Comment by Edieee** [comment]
I did everything works perfectly, thanks :)
