### ISSUE TITLE
Code question 

### ISSUE THREAD

**Issue by TrickyIrish** [ORelio/Minecraft-Console-Client#331]
So i play this faction server where they have outposts. If you type /outpost it gives you information about the 4 outposts. It displays the percentage of the cap,who owns it, if someone is attacking it etc.So what i need help with is i already have a task for the bot to do /outpost every 30 seconds or so but i was looking for a code/script that once it displays in information in chat another script activates and displays the information of the outpost in a ally chat to notify me if a faciton is taking the outpost. 

Also btw its for console client @ORelio

**Comment by ORelio** [comment]
Hello,

Depending on your needs you may use the AutoRespond bot to match single lines and perform a simple command on it, or, if you need something more advanced, you'll want to write a C# script.

(See README and sample files in [config](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config) directory)

**Comment by Barnehhh** [comment]
I believe I know what you are talking about @TrickyIrish! I would highly recommend a c# script for this as I happen to have one of these myself. Once I finalize it I may look to post it here as a possible sample script in the future!
