### ISSUE TITLE
How do I make the bot repeat what players said?

### ISSUE THREAD

**Issue by MasterZitron** [ORelio/Minecraft-Console-Client#332]
I know about the sample-matches.ini, but its not really helping. I want to make the bot repeat what players said, on the [Matches] section, I used:
match=+say ""
action=send ""
When someone says "+say """, the bot only says "", any help?

**Comment by MasterZitron** [comment]
I know about the /tell (Bot) send (Message), but I want to make it on public chat.

**Comment by Pokechu22** [comment]
Try just `/send (Message)`

**Comment by MasterZitron** [comment]
I want the bot repeat what players said, like:
+say Hello!
(Bot): Hello!

**Comment by ORelio** [comment]
Hello,

You may do this with AutoRespond bot

````ini
[Match]
regex=^.*$
action=send $1
````

**Comment by MasterZitron** [comment]
Thank you! It worked!

**Comment by MasterZitron** [comment]
Ok, I got a little problem, auto responds works fine, but the bot only repeats the first word, like:
+say Hello World!
Bot: Hello
Am I doing something wrong? Sorry for bad english.

**Comment by MasterZitron** [comment]
Ok i fixed it
