### ISSUE TITLE
Bot interacting with world 

### ISSUE THREAD

**Issue by Gamer745** [ORelio/Minecraft-Console-Client#333]
So adding onto the lamp script you made I was wondering if theres a way to modify that so instead of watching one block it watches a cuboid/region. any way to do this? 

( Kinda like the fill command in vanilla where you can do /fill x1 y1 z1 then x2 y2 z2  and it fills that area. )

**Comment by ORelio** [comment]
You can use a loop to check all the blocks, it's a C# script :)

**Comment by Gamer745** [comment]
hmm, wouldnt this decrease performance?

**Comment by Pokechu22** [comment]
Sure, there would be a small performance cost, but there exactly a way to do it faster (you need to check 100 blocks, so you do it by checking 100 blocks in a loop).  `/fill` in vanilla is the same - it's a large loop.

A potential change to MCC to listen to block changes could be possible in the future (but then you have to deal with firing a large number of them when a chunk section is first loaded, which would probably be slower).
