### ISSUE TITLE
Send commands after joining a server

### ISSUE THREAD

**Issue by MasterZitron** [ORelio/Minecraft-Console-Client#334]
I'm really, really, really bad with coding, how do I send a text when the bot joins a server?

**Comment by Edieee** [comment]
Command for what? Joining another server/realm or?

**Comment by MasterZitron** [comment]
When it joins the server, it automatically sends a text.
There's something called "AfterGameJoined()" in ChatBot, but, I don't know how to use it lol

**Comment by TheSnoozer** [comment]
Most likely way to late to respond...but you can send an command automatically with `ScriptScheduler` or `AutoRespond`

> # via `ScriptScheduler`
> 
> MinecraftClient.ini
> 
> ```
> [ScriptScheduler]
> enabled=true
> tasksfile=tasks.ini
> ```
> 
> tasks.ini
> 
> ```
> ﻿[Task]
> triggerOnInterval=true
> triggerOnFirstLogin=true
> timeInterval=60
> script=joinyourserver.txt
> ```
> 
> joinyourserver.txt
> 
> ```
> send /server [REALM]
> ```
> 
> # via `AutoRespond`
> 
> MinecraftClient.ini
> 
> ```
> [AutoRespond]
> enabled=true
> matchesfile=matches.ini
> ```
> 
> matches.ini
> 
> ```
> [Match]
> match=--------------------[Hub]--------------------
> actionother=script joinyourserver
> # or simply actionother=send /server [REALM]
> ```

**Comment by MasterZitron** [comment]
Yeah, It's so late I don't even remember what this is for, but thanks
anyways

**Comment by Edieee** [comment]
Lol this was 1 year ago, i forgot everything. What is even minecraft? :P
