### ISSUE TITLE
Move

### ISSUE THREAD

**Issue by ZapphireYT** [ORelio/Minecraft-Console-Client#336]
in script scheduler, i did this 
_send /server prison2
wait 20
send /crates
wait 20
move 432 15 112_
When I do this manually in the console it works. Why not in script scheduler?

**Comment by TheSnoozer** [comment]
Sorry for the very late response, but I would assume that the script scheduler is not being triggered.

As per Readme https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config:
```
The script scheduler allows you to perform scripts on various events.
Simply enable the ScriptScheduler bot and specify a tasks file in your INI file.
Please read sample-tasks.ini for learning how to make your own task file.
```

See https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini

**Comment by ORelio** [comment]
Closing this question as it is quite old and an answer has been given.
