### ISSUE TITLE
ArrayIndexOutOfBoundsEsception: 3

### ISSUE THREAD

**Issue by kittymjau** [ORelio/Minecraft-Console-Client#338]
**MCC log:**
You chose to run in offline mode.
Success. (session ID: )
Retrieving Server Info...
Server version : Spigot 1.12.2 (protocol v340).
Translations file loaded.
Version is supported.
Logging in...
Server is in offline mode.
Server was succwessfully joined.
Type '/quit' to leave the server.
Username logged in
Connection has been lost.

**Server log:**
Username logged in
Username lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexoutofBoundsException: 3
Username logged out

**Comment by Pokechu22** [comment]
I _think_ I've seen this before when chatting before fully logged in - it
sends a chat packet while the connection is still in the login phase.  Did
you send a chat message almost immediately after joining the server?

**Comment by kittymjau** [comment]
No

**Comment by kittymjau** [comment]
Error is because server using resource pack in server.properties

resource-pack=<URL HERE>

**Comment by Pokechu22** [comment]
That's interesting... MCC is supposed to automatically respond to the
server with a resource pack packet.  I'll check.

**Comment by Pokechu22** [comment]
Confirmed (just set resource-pack=http\://example.com).  Should probably be
a simple fix, probably just a packet format change that was missed.

**Comment by Pokechu22** [comment]
Yep, figured it out.  Just need @ORelio to merge that pull request (#340).

**Comment by ORelio** [comment]
Thanks for your report @kittymjau and thanks for the fix, @Pokechu22 :smiley:
You can grab the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) to try it out.

**Comment by oyylumo** [comment]
My server also has a custom resource pack, when the bot joins I get 
```
[MCC] Disconnected by Server :
[MCC] Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException
``` 
I'm running `MinecraftClient-20230409-213-linux-x64`
