### ISSUE TITLE
Stuck at "logging in" upon reboot of server

### ISSUE THREAD

**Issue by MeWoody** [ORelio/Minecraft-Console-Client#339]
I'm AFKing alts on a server, but sometimes when the server does its scheduled reboot, the accounts will simply stay at the "logging in" part. They won't crash, won't login either. Is there any way to set a timeout for logging in, so it reloads the console client whenever it takes longer than 30 seconds to log in?

**Comment by 5tanly** [comment]
hi MeWoody, how Oki?
😝
