### ISSUE TITLE
knockback

### ISSUE THREAD

**Issue by 5tanly** [ORelio/Minecraft-Console-Client#341]
I am afking with this but I dont take knockback when hit, how do I enable knockback

**Comment by Pokechu22** [comment]
MCC doesn't handle damage, which means that it doesn't attempt to process knockback.

**Comment by 5tanly** [comment]
even terrain movements doesn't give you kb?

**Comment by Pokechu22** [comment]
Not at this time, no.  It's just not implemented yet.
