### ISSUE TITLE
"Connection throttled"

### ISSUE THREAD

**Issue by Kirvis111** [ORelio/Minecraft-Console-Client#342]
Hey, i have a issue with "Connection throttlerd" message, after getting this message, my console client dont autorelog, my kick messages:
Connection has been lost
Server is restarting
Server is full
too many people
Connection has been lost
Server is restarting
Server is full
too many people
Disconnected by server:
kicked
afk
Server is shutting down!
You have been kicked for idling for more than 15 minutes.
Server is restarting! Come back in 1 minute
connection throttled please wait before reconnecting
Connection throttled! Please wait before reconnecting.
Not connected to any server. Use /help for help.
Connection throttled! Please wait before reconnecting
Connection has been lost
An error occured while attempting to connect to this IP.
Failed to ping this IP.
Login failed:
Serveris yra pilnas!
Failed to ping this IP.
Not connected to any server. Use '/help' for help.
Version is supported.
Logging in...
Login failed :
Connection throttled! Please wait before reconnecting.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client
Failed to ping this IP
Login failed.
Connection throttled Please wait before reconnecting

**Comment by Kirvis111** [comment]
I have always much accounts online with console client, and after server restart, they all autorelog in same time, thats why connection throttled message shows up.

**Comment by ORelio** [comment]
You can define a delay before reconnecting, use that to spread reconnection attempts so that they don't happen at the same time?

**Comment by Barnehhh** [comment]
I believe he/she is referring to having multiple Console client windows open. With this, when a server restarts they all get disconnected at the same time, attempt to reconnect at the same time.

The only current ways I can think of getting around that is through using different proxies or different MCC folders with different autorelog reconnect delays.

One potential suggestion for now as I do this myself, if you use a .bat file to open the MCC windows, you can have that bat script relog the alts every x minutes or hours. This can't detect a server reboot and would relog them based on time passed, but it was something I used in-case something went wrong with the alts on console client.

Ex: Looping a .bat script every 3 hours closing and re-opening all the alt windows. For me, I found this better than having people wait 8+ hours while I sleep for the accounts to reconnect.

^ This is not a solution to the problem though, don't take it like that. :p Just a tip.
