### ISSUE TITLE
Alts disconnect during server reboots

### ISSUE THREAD

**Issue by MattPlaysYT** [ORelio/Minecraft-Console-Client#343]
Sometimes when using a vps screen the Alts will log off during reboot and won’t come back. And I think this is being sometimes when the server reboots it kicks you from the server. Anyway to fix this?

**Comment by ORelio** [comment]
So you're already using AutoRelog? If so, could you provide some output showing the issue? Thanks.

**Comment by MattPlaysYT** [comment]
When this happens, it never comes back on

https://gyazo.com/83cbd94f58ee7ffd853ed01b8822c93a

**Comment by MattPlaysYT** [comment]
[AutoRelog]
enabled=true
delay=2
retries=-1 #-1 = unlimited
kickmessagesfile=kickmessages.txt

**Comment by MattPlaysYT** [comment]
thats my auto relog

**Comment by ORelio** [comment]
Does kickmessages.txt contains "Server closed"? Seems like the bot is enabled but not triggered.

**Comment by MattPlaysYT** [comment]
No it does not. If I add that will it fix it?

**Comment by ORelio** [comment]
Yes it should, as it's the kick message shown in your screenshot.

**Comment by MattPlaysYT** [comment]
This also happens https://gyazo.com/5c22199d276fbff765c49d3622a673da

**Comment by MattPlaysYT** [comment]
Connection has been lost is also in my kick messages already

**Comment by MattPlaysYT** [comment]
Also I added "Server closed" to kick messages and they still don't come back online.

**Comment by ORelio** [comment]
Strange. Could you post a screenshot of your kick messages file and MCC not reconnecting?

**Comment by MattPlaysYT** [comment]
It seems to be going crazy when server shuts down for reboot, I’ll send screenshot

**Comment by ORelio** [comment]
Configure a delay before reconnecting, e.g. 30 seconds, to wait for server reboot.

**Comment by MattPlaysYT** [comment]
How would I do that?

**Comment by MattPlaysYT** [comment]
Reboot NOW!
Disconnected by Server :
Kicked from server.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>[MCC] [AntiAFK] Sending '/ping'
[MCC] [AntiAFK] Sending '/ping'
Connection has been lost.
[MCC] [AutoRelog] Waiting 10 seconds before reconnecting...
Restarting Minecraft Console Client...
Cached session is still valid for WeGotInsided.
Using Minecraft version 1.8.9 (protocol v47)
Version is supported.
Logging in...
Login failed :
Connection throttled! Please wait before reconnecting.
Not connected to any server. Use '/help' for help.

**Comment by Barnehhh** [comment]
Connection throttled occurs when there are too many logins from the same IP within the server's specified amount of time. I'm assuming you're trying to autorelog more than one account?

**Comment by MattPlaysYT** [comment]
Yes

**Comment by ORelio** [comment]
Configure a delay and retry count in the [AutoRelog] section of MinecraftClient.ini and add "Connection throttled" to kickmessages.txt if the bot does not retry to relog. Clients will eventually manage to relog, one by one.

**Comment by MattPlaysYT** [comment]
Alright can you send me like the code I have to post for the delay and retry?

**Comment by ORelio** [comment]
What? "posting code"??
It's directly in the config file `MinecraftClient.ini`:
````ini
[AutoRelog]
enabled=false
delay=30 # <- Here is the delay
retries=10 # <- Here is the retry count
kickmessagesfile=kickmessages.txt
````

**Comment by TheSnoozer** [comment]
Since this issue is now inactive for quite some time and the questions have been answered I'm closing this issue as part of an issue cleanup.

Feel free to reopen if you still have an issue in getting this sorted.
