### ISSUE TITLE
Beeping with alerts disabled.

### ISSUE THREAD

**Issue by DDivitto** [ORelio/Minecraft-Console-Client#344]
I have alerts disabled in the Minecraft Client configuration settings but for some reason it is still beeping continuously at random things why is it still doing this with it being disabled.

**Comment by ORelio** [comment]
Maybe some unusual characters from chat are misinterpreted by the console and confused with the escape sequence for producing a beep. Are you using the latest development build? Is there some strange output? Which OS and version?

**Comment by DDivitto** [comment]
I believe I fixed it I was using an older version I had on my computer that I used to use that only went up to 1.8.9 and I think it was the ~ key and a few other keys. I updated to the most recent version, and have not had any other issues with it. Thanks anyway!
