### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by 5tanly** [ORelio/Minecraft-Console-Client#347]
https://imgur.com/a/5BFng

This happens to all my accounts quite often, then they just sit there like that while my cpu eats itself
Im not sure what is causing the problem

I am using mono on a raspberry pi 3 model b

**Comment by 5tanly** [comment]
Would there be anyway to just terminate all running MCC instances and just rerun them, like every 2 hours?

**Comment by ORelio** [comment]
To do that, use a shell script that runs MCC in a loop eg "while true; do sleep 5 && mono MinecraftClient.exe; done". Then use the script scheduler to run the "exit" command every 120 minutes.

**Comment by 5tanly** [comment]
Unfortunately I can't do that because as you see in the picture the console clients crash and are sitting in a weird state where MCC is running but the account is not online, its unable to send any commands

**Comment by ORelio** [comment]
Try exitonfailure=true in the config file. If that does not work, check your mono version, v4.0-4.2 is the recommended range.

**Comment by ORelio** [comment]
Also, to run headless, you may pass "BasicIO" as last argument, this will disable the interactive chat prompt and chat colors.

**Comment by K3yX** [comment]
Any solution brought? I have the Same Problem on the same device as the author.

**Comment by K3yX** [comment]
Any solution brought? I have the Same Problem on the same device as the author.

**Comment by K3yX** [comment]
Someone posted a solution at #569 (at least it worked for me)

Hope this helped y'all
