### ISSUE TITLE
You can’t open the application “MinecraftClient.exe” because Microsoft Windows applications are not supported on macOS

### ISSUE THREAD

**Issue by Umbraged** [ORelio/Minecraft-Console-Client#348]
#i tried opening it and it gave me this error "You can’t open the application “MinecraftClient.exe” because Microsoft Windows applications are not supported on macOS" Someone please help it also says i don't have an application that can open it. Could someone recommend an application for me to download to run this file? i Use a Mac OSX if you couldn't tell. i downloaded the "mono framework" thing as it said too. Please help and thx for your time!

**Comment by Pokechu22** [comment]
You need to install [Mono](http://www.mono-project.com/download/), and then use `mono MinecraftClient.exe`; read the README and the forum post for more information.

**Comment by Umbraged** [comment]
i need an application to run the file but i don't have one which is the problem can u recommend 1 ?

**Comment by Pokechu22** [comment]
Mono is the app you use to run it.

**Comment by 5tanly** [comment]
open terminal and type `mono MinecraftClient.exe` as said above

**Comment by PrismaticYT** [comment]
Stop using a Crapintosh.

**Comment by ORelio** [comment]
@PrismaticYT MCC should work on MacOS through Mono.

**Comment by PrismaticYT** [comment]
no, I was saying that mac is shit.

**Comment by ORelio** [comment]
In that case, your comment is not useful.

**Comment by TheSnoozer** [comment]
Since this seems to be answered and seems to be inactive for quite some time, I'm closing this issue as part of an issue cleanup. Feel free to reopen if you still have any issues getting this sorted. Otherwise please open a new issue.
