### ISSUE TITLE
Don't execute commands on VPS

### ISSUE THREAD

**Issue by Marsietis** [ORelio/Minecraft-Console-Client#350]
Then i turn it on vps it don't execute commands, but then its running on PC its work perfectly fine.
Pls help me. Thanks

**Comment by ORelio** [comment]
Please elaborate the "don't execute commands" part.

**Comment by Marsietis** [comment]
The its run on pc its execute AntiAFK commands ,but then i turn on vps its just stay and dont execute any commands

**Comment by ORelio** [comment]
Ok, make sure that you invoke MCC from the directory containing the `MinecraftClient.ini` file with AntiAFK enabled, and also try using a mono version between 4.0 and 4.2 (inclusive) because these versions seems more reliable with MCC.

**Comment by Marsietis** [comment]
Yes, im done that you say. But it still dont send AntiAFK commands or Scripts.Then im run on PC its work.

**Comment by ORelio** [comment]
Apart from script/antiAFK triggering, does MCC seems to work fine on your VPS? I mean, are you still able to send and receive chat messages after ~10 minutes of Boeing idle? You can send a /tell to yourself to verify that everything ils fine.

**Comment by Marsietis** [comment]
no, its take time to send commands. and chat is a litle bit slow ;)

**Comment by ORelio** [comment]
Timings expressed in MCC ticks will not be accurate if MCC is slowed down that much. Please check CPU/RAM usage, just in case, as well as mono --version. You may try very short delays since the bots are probably working, but slowed down.

**Comment by Marsietis** [comment]
Everiting is okey. Im using this

RAM | 1024 MB
-- | --
 
CPU | 2 Ghz
 
SSD | 10 GB

**Comment by ORelio** [comment]
I was rather asking for you to check e.g. `top` or `htop` and see if Mono is eating too much RAM/CPU. Also, what is the output for `mono --version`?

**Comment by TheSnoozer** [comment]
I'm closing this as part of an issue cleanup. if this is still an issue, please provide further information.
