### ISSUE TITLE
Check Lamp Script

### ISSUE THREAD

**Issue by corkyslurp** [ORelio/Minecraft-Console-Client#351]
The checklamp script you have on here as a sample does not work.. If you could help explain what im doing wrong

**Comment by ORelio** [comment]
Set `terrainandmovements=true` in your INI file. And triple check coordinates for the lamp.

**Comment by corkyslurp** [comment]
May I ask how the coords work? is it like if I set schematica to it, those coords? or the ones of me standing on it?

**Comment by corkyslurp** [comment]
and is there anyway to setup it detecting explosions? and set it up to send skype/discord alerts?

**Comment by Pokechu22** [comment]
It checks the raw coordinates you put into the script, by default 0 64 0.  But you can change the script to behave however you need it.

For explosions: no, not builtin.  It would require adding a new packet handler, which is not possible from scripts but wouldn't be super hard to implement ([protocol doc](http://wiki.vg/Protocol#Explosion)).

Skype/discord alerts: you'd need to find a library or API to do it; it's not builtin.  Discord does have an API for that purpose, but I don't know the details of it.

**Comment by corkyslurp** [comment]
how do I know what the coords are though?

**Comment by corkyslurp** [comment]
http://prntscr.com/hbuwpb the red spot in the lamps is the lamp, the coords I have put in are the ones schematica says is the red point, the person you can see in the back is the acc running it.

**Comment by Pokechu22** [comment]
You don't need schematica to find it.  Just press F3, look at the block, and then use the "Looking At" value in F3.

**Comment by corkyslurp** [comment]
I have it set to that same coord, its just saying that its not a lamp, that its air.

**Comment by Pokechu22** [comment]
Make sure terrain and movements is enabled.  Also, it might be that the y value is too high (though that seems unlikely).

**Comment by corkyslurp** [comment]
it is. Ill check the Y level and move it down 1, and up one

**Comment by corkyslurp** [comment]
with checking and changing Y level, it still doesnt work. Rather it spams saying its not a lamp.

**Comment by Pokechu22** [comment]
If you set y to 0, does it say it's bedrock, or air?

Also: Which Minecraft version?

**Comment by corkyslurp** [comment]
1.8.8 and the Y 0 does not say bedrock.

**Comment by Pokechu22** [comment]
It's possible that the terrain and movements code is broken (and thus everything is the default block, air) on 1.8.8, due to how old that version is.  I'll check.

**Comment by Pokechu22** [comment]
Nope, works fine on my machine.

Make sure you are running the latest build.

**Comment by TheSnoozer** [comment]
I#m closing this as part of an issue cleanup. The script in general seems to work fine. Feel free to reopen if still relevant.
