### ISSUE TITLE
console client trouble logging in

### ISSUE THREAD

**Issue by FMRG8** [ORelio/Minecraft-Console-Client#352]
hi guys,
when i use my console client it doenst work. What happens when i put down my emaillogin and password in minecraftclient.ini and the server i wanna join it says the password is wrong but its not. After that i get this message on minecraft, the minecraft website and majong if i try to login there. Whenever i try to reset my password its says u succesfully changed ur password but when i try to login again it still doesnt work. A couple hours later i tried it again and it worked but still not on my console client. im kinda new in console client so any1 can help me out here.
thnksss

**Comment by Pokechu22** [comment]
Too many failed logins can lead to your account temporarily disallowing all logins ([mojang ref](https://help.mojang.com/customer/en/portal/articles/781529-login-failed)) &mdash; that's probably what happened the first time.

Double-check that your login information is correct in minecraftclient.ini, and also consider enabling session caching (which decreases how often MCC tries to log in).

**Comment by FMRG8** [comment]
thnks man! it works now
