### ISSUE TITLE
Issue with logging in using SOCKS5 proxies

### ISSUE THREAD

**Issue by plaincamron666** [ORelio/Minecraft-Console-Client#353]
Hey,

I'm trying to login using working SOCKS5 proxies, I've checked the proxies work with mojang authentication however then don't seem to work with MCC.

In the config I input the proxy as: 177.142.109.67:12287, and set the type to SOCKS5.

The proxy connects, however I always get the "Invalid credentials" message. I've checked this across hundreds of SOCKS5 proxies and accounts, however the login rarely works. I know all the proxies are working with Mojang authentication, and all the accounts are working.

**Comment by ORelio** [comment]
Try enabling debugmessages in INI file to show authentication request and response in console output.

If that does not help, you can post a screenshot of that but don't forget to redact email, password and tokens.

**Comment by plaincamron666** [comment]
Hey,
https://gyazo.com/9822d4fcdb0b738173976526545929ae

The auth request seems to be fine, I'm unsure why it's happening.

Also, a bit off topic but I don't suppose you have somewhere I can privately contact you. I have a custom request for MCC.

**Comment by plaincamron666** [comment]
Orelio?

**Comment by ORelio** [comment]
Seems like the proxy does not transmit the request, that may be caused either by the proxy or by the library I included with MCC to add proxy support. Not sure how to debug this. Does it require credentials?

You can use the sessioncache feature to store and reuse tokens, see INI file.

**Comment by plaincamron666** [comment]
No, the proxy doesn't require credentials. I've checked the request that's being sent, and it does get the correct invalid login response from Mojang. I've also tried updating the proxy library that you're using, which didn't change anything.

I've also played around with the response being sent because I've found Mojang sometimes blocks requests and shows an invalid login if there is content in the request they don't like, for example the user agents and such, but couldn't find a working solution.

I'm able to get a working login response using this payload with python:
{
    "agent": {                             
        "name": "Minecraft",               
        "version": 1                       
                                           
    },
    "username": email,     
                                           
    "password": password,
    "clientToken": "client identifier",    
    "requestUser": True                 
}

I'm out of ideas for logging in with proxies.

Also, I was looking for a way for me to be able to input an access token, and then MCC log in with it. However now I've coded my own into the program, so no worries there.

**Comment by ORelio** [comment]
In that case, maybe the proxy is not allowed to perform more login requests? The login servers are applying a rather low rate limit on them. Or as you hinted, the request from MCC might have a slight difference that may trigger something. But in that case, why would it work most of the time and not on some proxies? I don't know. :confused:

Regarding access tokens, indeed, they are stored in a db file but cannot be set directly. If you added a feature for that, feel free to send a pull request, this might help other people. :slightly_smiling_face:

**Comment by plaincamron666** [comment]
Yeah, the proxy thing really confused me to I'm just leaving it for now haha.

I managed to code the access token authentication, however it's pretty shitly coded as I'm not the best with c#. I'll try to tidy it up and send a pull request. Thanks for the help though!
