### ISSUE TITLE
Coding issue

### ISSUE THREAD

**Issue by GLadithon** [ORelio/Minecraft-Console-Client#354]
Hey, I trying to add a discord api to the client, I was wondering why my variables keep being changed to null if they are left for anytime at all.

Thanks

**Comment by ORelio** [comment]
Please show a code sample? Note that even static variables are reset on script launch. You may use the script API to store/load global variables across script loading, if required, or use a ChatBot.

**Comment by GLadithon** [comment]
I have this run when the client first opens up to make the discord bot come online
       private DiscordSocketClient _discordclient;

        public async Task StartAsync(string token)
        {

            _discordclient = new DiscordSocketClient();

            await _discordclient.LoginAsync(TokenType.Bot, token);
            await _discordclient.StartAsync();

            await Task.Delay(500);

        }

and this to send messages


        public virtual async Task SendMessageAsync(string message, string channelId)
        {

            if (ulong.TryParse(channelId, out var channelIdLong))
            {
                var channel = _discordclient.GetChannel(channelIdLong);

                if (channel != null)
                {
                    await ((SocketTextChannel)channel).SendMessageAsync(message);
                }
                else
                {
                    Console.WriteLine("Guild not found");
                }
            }
        }

but the _discordclient variable gets nulled after a while, Is there a way to prevent this?

**Comment by GLadithon** [comment]
I use a script that contains DiscordSend("Test"). In the CSharpRunner.cs and the Chatbot.cs I have added this 
        new public void SendDiscord(string text)
        {

            new DiscordMainClass().SendMessageAsync("Test123", "382259701741518861").GetAwaiter();

        }

**Comment by ORelio** [comment]
That's cool you could get your bot working. I'm pretty sure there are people out there who would be interested by a Discord bot, so if you're okay to share it I'd gladly add it to the repository :wink:
