### ISSUE TITLE
Tasks suggestion/issue

### ISSUE THREAD

**Issue by TNTUP** [ORelio/Minecraft-Console-Client#355]
Hey, I wanted to have a bot when I execute it, it prints the "send" message and the send command and it works. But when if the server reboots, or my internet crashing, it relogs itself but does not execute commands as I typed "triggerOnLogin" I guess it means when I execute it but I couldn't find the "triggerOnReconnect" or like that. 

I have the autorelog enabled so it reconnects automatically but I want him to do commands if the client losses internet, server restarting... I don't want to setup antiafk because the server where I use it does not permit that, though its a Bungeecord command :/

Sorry my english sucks so I don't know how to explain it properly

**Comment by ORelio** [comment]
Well, that should work since TriggerOnLogin should trigger on reconnect, maybe there is an issue with your ScriptScheduler config? Also make sure you have the latest dev build?

**Comment by TNTUP** [comment]
When it reconnects it doesn't re-execute the task I have configured. As a workaround I did set up timers like at 02:12 or 05:12 and it works.

I will try the dev build one. 

Also how I can change the encoding to 850 (OEM - Multilingue I) instead of 65001 (UTF-8)? Getting some weird characters like accents being weird and other stuff.
