### ISSUE TITLE
Need to move before running cmd

### ISSUE THREAD

**Issue by jimmybenoit** [ORelio/Minecraft-Console-Client#358]
On this server I'm trying to run this console client on it says, "You cannot use commands before you move!" if there is any way to make it so it jumps or something on join please tell me.
https://gyazo.com/8a4ec503a98e386085e905805fd52e31

**Comment by ORelio** [comment]
1) `terrainandmovements=true`
2) `/move`

See [README](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt) for full user manual.

**Comment by jimmybenoit** [comment]
@ORelio just wondering where i need to put this?

**Comment by ORelio** [comment]
1. In the configuration file `MinecraftClient.ini`
2. In the client, it's an internal command.

**Comment by jimmybenoit** [comment]
@ORelio is there some special way to run internal cmds and is this right here correct
[](https://gyazo.com/ed239e60131f2addb88c0103576266dd)

**Comment by jimmybenoit** [comment]
also do internal commands work inside the scripts like this
https://gyazo.com/79a48cfb4ccd0c292c1111618014e10a

**Comment by jimmybenoit** [comment]
Now whenever I try this it doesn't count it as a actual command
https://gyazo.com/a9eacd4f1ea297325d835fd11e8ebf18

**Comment by jimmybenoit** [comment]
Ok never mind i found out that I was on a really outdated version
