### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by hehoqmfe** [ORelio/Minecraft-Console-Client#359]
I bought a vps located in germany(host1plus) which is running ubuntu 16.04. Also downgraded to mono 4.0.5.1.. Now i'm having trouble logging in. I run the mcc using 'mono MinecraftClient.exe' but It says wrong password everytime although it works fine outside the vps(windows laptop). Tried putting account details into the .ini file, filling it in manually or using a script. Nothing seems to work. I've also waited multiple hours between logging in because of mojang possible temp blocking accounts but that doesn't seem to be the problem.

**Comment by ORelio** [comment]
Maybe your VPS provider's IP range is blacklisted by Mojang login servers. So it will respond invalid password even though the login request is valid. Try using logging in using a non-blacklisted proxy with MCC's built-in proxy feature?

**Comment by hehoqmfe** [comment]
That seems to be the problem but for some reason every  free proxy I've tried, stops working after a couple minutes giving the same password problem for different accounts. Is it mojang blocking those ip's really quick or is it something else?

**Comment by Pokechu22** [comment]
They [blacklist IPs temporarily](https://help.mojang.com/customer/en/portal/articles/781529) after several failed logins in quick succession (might even be just several logins in quick succession regardless of success).

**Comment by ORelio** [comment]
I can confirm than even successful logins count in blacklist triggering. Also, blank passwords will trigger it instantly, fortunately MCC switch to offline mode so it does not attempt to login with a blank password.

**Comment by hehoqmfe** [comment]
Could someone link me a proxy service that still works with mojang. I don't have any luck with the free ones I found on the net.

**Comment by ORelio** [comment]
Don't have a proxy to suggest, you might want to run MCC or proxy from a Raspberry Pi (or similar) at home, if you have one.
