### ISSUE TITLE
Request for auto sell signs (sign click)

### ISSUE THREAD

**Issue by nouimette25** [ORelio/Minecraft-Console-Client#360]
Hi there! I am by no means any longer a coder, I used to be a coder years ago, but that skill has escaped me. That said, please excuse my lack of correct terminology. 

I currently play on a skyblock server, and although being able to afk 24/7 is splendid, I would like to ask if someone could help me with a sign auto click. Let me explain:

On this server, you sit in a minecart and it goes back and forth among the chests. Each chest has a sign on it, when you click it, the entire contents of the chest gets sold. 

If there is already a mod for this, great! I am however assuming if a auto clicker exists, it doesn’t force you to look at the signs. I am hoping someone can help me by making something that not only looks at the signs, but actually clicks them so you get money while afking.

Thank you!

**Comment by ORelio** [comment]
Unfortunately, clicking on entities/blocks is currently not handled.
Only terrain reading & movement.

**Comment by TheSnoozer** [comment]
Hi, since I think this would be tracked within #205 / #183 I'm closing this as 'duplicate'.
Feel free to subscribe to the other issue or subscribe to the other one for any updates. besides that feel free to open a new issue, with any other problem/issue you encounter.
