### ISSUE TITLE
Still logging in??

### ISSUE THREAD

**Issue by Pedro9700** [ORelio/Minecraft-Console-Client#361]
I just realised that my acc is getting online when im not. When i try to log in, it kicks me in about 2-3 mins for the acc connecting to the server. thats something with auto-relog maybe, but even tho if my pc is down, it still being connected to the server
I guess this is  the console client problem because it only started when i downloded it

**Comment by ORelio** [comment]
MCC cannot magically keep you online, you must have an instance running somewhere. Or maybe someone ils doing it for you. If you are 100% sure you are not running any MCC instance anywhere, try changing your password. And make sure you downloaded MCC from a reliable source, adding some malicious code in MCC before releasing it is so easy...

**Comment by Pedro9700** [comment]
I dont know how it is doing it.. im using the console downloaded from ur Minecraft forums post

**Comment by Pedro9700** [comment]
IF you know anything that can help....

**Comment by ORelio** [comment]
If the MCC executable is trusted then either you have an instance of the program running somewhere or someone else is doing it for you.

**Comment by Pedro9700** [comment]
I guess its a console client issue, it doesnt take any knoc back or moved by water... and yes, i dowloaded all from you minc«ecraft server post

**Comment by Barnehhh** [comment]
That's because terrain and movement in MinecraftClient.ini is disabled. If you enable that, it should move and take knockback.

**Comment by ORelio** [comment]
It's a bit more complicated, knockback / water flows need to be handled client-side, and MCC does not implement that.
