### ISSUE TITLE
Some Features not working

### ISSUE THREAD

**Issue by 5tanly** [ORelio/Minecraft-Console-Client#362]
[Remote Control] does not work on rapsberry pi, I enabled all the settings in it and nothing happend
[Auto Respond] is not working on raspberry pi.

I tried both on my mac also using mono, but the remove control didnt work, but the auto respond worked flawlessly and very fast. Its just not working on raspbian jesse for some reason.
Also the script scheduler doesnt work, i wanted my accounts to auto connect to a sub server on join but it doesnt work at all on my pi, worked great on my mac though.

**Comment by ORelio** [comment]
Get [latest version](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and make sure your configuration files are actually read by invoking MCC from the correct folder, i.e. not `mono /full/path/to/MinecraftClient.exe` but `mono MinecraftClient.exe` from the right folder.

**Comment by 5tanly** [comment]
@ORelio do you know if theres a 4.2 for raspbian jesse?
I read this https://stackoverflow.com/questions/33763177/install-older-version-of-mono and i found a link of all older mono versions but i cant find a 4.0-4.2 release on raspbian jesse
http://download.mono-project.com/repo/debian/dists/

**Comment by ORelio** [comment]
It should exist, but never had to install it manually on Raspbian, sorry.
