### ISSUE TITLE
Support for regular and colored obfuscated text

### ISSUE THREAD

**Issue by Mhowser** [ORelio/Minecraft-Console-Client#363]
this code is for parsing minecraft formatting codes into html, but can it be applied to terminals?

https://stackoverflow.com/questions/30312601/translating-minecraft-color-codes-into-html/30313558#30313558 
updated version of this: http://jsfiddle.net/fku9gsax/12/

**Comment by ORelio** [comment]
HTML is much richer than terminals. Most of them don't handle random/obfuscated text. You'd have to simulate it by tracking text position in terminal window and updating frequently with random text. Not only this is curently not feasible as MCC does not know where is previously outputted text, but that would likely cause glitches in the terminal.
