### ISSUE TITLE
Log /near

### ISSUE THREAD

**Issue by supertat** [ORelio/Minecraft-Console-Client#365]
So I afk my spawners in a faction sever and I want the console client to do /near every 2 mins and log it to a file called nearby.txt or something and also I want to have a separate one that shows my whole chat as well as I am staff and I have social spy so I would like any message that says : in it, I'd like it in socialspy.txt please help I tried getting the log stuff to work but I'm confused. I'm kind of a big noob so if you could do your best I'd really appreciate it!
Happy new year!

**Comment by ORelio** [comment]
Seems like your issue never got answered, sorry about that. You would have needed to write a ChatBot in order to do this.
