### ISSUE TITLE
Login failing

### ISSUE THREAD

**Issue by PrismaticYT** [ORelio/Minecraft-Console-Client#366]
It just says invalid password.

Debug data:

Debug: Login Request: {"agent": { "name": "Minecraft", "version": 1 }, "username": "HellToTheFuckNo", "password": "FuckYouYou'reNotGettingMyPassword", "clientToken": "FuckOffMateYouAren'tGettingThisEither" }

**Comment by ORelio** [comment]
VPS blacklist? See #359

**Comment by PrismaticYT** [comment]
I'm not using a VPS..

**Comment by ORelio** [comment]
In that case, please include the `Debug: Login Response:` line. Also make sure you can login using the regular Minecraft game (too many logins will also cause this error).

**Comment by PrismaticYT** [comment]
I can login with the normal game, and there is no login response line.

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue, I would suggest to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) and try if the problem is still present.

**Comment by ORelio** [comment]
Closing this report as it is quite old and does not contain enough info.
