### ISSUE TITLE
[Suggestion] Have Hangman not be case-sensitive

### ISSUE THREAD

**Issue by PrismaticYT** [ORelio/Minecraft-Console-Client#369]
There are quite a few times where I've said "O" and it said there wasn't an O in the word, but at the end there is an O in the word, just lowercase. An option to make it not case sensitive would be nice.

**Comment by ORelio** [comment]
Letter should already be converted in uppercase: https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/HangmanGame.cs#L80
``C#
char letter = message.ToUpper()[0];
if (letter >= 'A' && letter <= 'Z')
{
    //...
``

**Comment by PrismaticYT** [comment]
It doesn't work though, some of my letters in the words are lowercase.
