### ISSUE TITLE
"Connection Lost" only when alt is in certain places

### ISSUE THREAD

**Issue by x3MK** [ORelio/Minecraft-Console-Client#372]
I used Console Client for months now and I have never gotten this error before.
Console client keeps losing connection when I Place my alt in the middle of my base in Factions.
but whenever he is below an exact Y axis value that issue doesn't occur. After more testing I found out that the loss of connection only happens when My alt is within the reach of Iron Golem spawners. 
I tried this on Windows 10 and Linux (also across 3 different accounts) and the issue is still happening. I figured it was something with Console client.

PS. Not sure if you are familiar with Minecraft Factions but the server that I was playing is Cosmicpvp.com 
Also whenever The account logs in to the server in a different place then I teleport the alt back to the place where the connection lost issue happens it fixes it self but the issue is that whenever the server restarts and the alt spawns directly to the place where the issue occurs it keeps crashing again and again until I get on and teleport my alt out of that location and back in. So this basically removes the ability of being able to afk. 

Please feel free to ask me for any more information or logs from the console client. 

Thanks

**Comment by x3MK** [comment]
pls?

**Comment by ORelio** [comment]
Honestly I'm not sure what is causing this.
You may want to try the AutoRelog bot to at least relog when the issue occurs?

**Comment by x3MK** [comment]
I tried. Its just not worth afking with 
Since the issue occurs like after 5 seconds of the alt getting on. And overall the alt’s afk time is pretty much useless.

PS. I use exactly the same files and scripts for console client to afk another alt that is setting in a different spot and its absolutely fine.

**Comment by ORelio** [comment]
Is `terrainandmovements` enabled?

**Comment by x3MK** [comment]
Nope but I did try to login with it on but I still got the same issue

**Comment by ORelio** [comment]
Ok that's weird because by default MCC simply discards terrain and entity information and mostly focuses on chat (there is still handling for additional things such as keepalives but that's minimal). So being in a different place should not affect MCC's behavior :confused:

**Comment by x3MK** [comment]
Not quite sure if its just in different places.
Because the first place has 6 IG spawners that the alt is afking (This works fine) but the place that I’m getting the issues on has at least 400 IG spawner that are within the 16x16 chunk range

**Comment by x3MK** [comment]
Also what you linked isn’t what I’m talking about although that happens and I got around it by writing a script that restarts Console client every hour

**Comment by ORelio** [comment]
The link was created because I mentioned this issue from another issue (no really useful for you).
