### ISSUE TITLE
Crash after starting

### ISSUE THREAD

**Issue by DateNogg** [ORelio/Minecraft-Console-Client#375]
I have been using this for months without a problem and today i get this everytime i start: https://i.imgur.com/mnncOP5.png

thx in advance for help

**Comment by ORelio** [comment]
Make sure you are using the latest version (see link on repo main page)

**Comment by DateNogg** [comment]
nevermind, it magically works again after i moved the account a few meters to the side. im sorry to have bothered you.

**Comment by ORelio** [comment]
Well that still should not have happened, but that's good news you could solve your issue.
