### ISSUE TITLE
how to make it auto log a file when a keyword shows?

### ISSUE THREAD

**Issue by yangciouou** [ORelio/Minecraft-Console-Client#378]
How do you make it where the commandline auto logs a line when there is a keyword? I want to AFK on a server, and I want to make it so it auto logs the line of message. 

Ex : Keyword : The theme is

Minecraft Console Client : 
"The theme is Whale!"

I want to make it auto log that when it receives the key word "the theme is.." I don't know how to.

**Comment by ORelio** [comment]
Define a chatbotlogfile in settings, then use the AutoRespond bot to match that line and perform a "log" command on it.

**Comment by yangciouou** [comment]
Yes, but if how would I make it so it logs the line down? I know you have to do "match=---", but there are a lot of words in the game that I want to afk in. The lines might be, "The theme is Gingerbread," "The theme is Whale," ''The Theme is Airplane," etc. When the keyboard shows up, how would I make it that the autorespond bot logs that specfic line with the keyboard in it?

**Comment by ORelio** [comment]
I'd say:
regex=The theme is .*
action=log $0
When using a regex you can access the whole match as $0

**Comment by yangciouou** [comment]
I don't know why it doesn't work, can you please help me. I showed all of my config in this video and in the console client. https://youtu.be/6SwYJNwLwxo
