### ISSUE TITLE
Raspberry pi 3 Minecraft Console Client

### ISSUE THREAD

**Issue by Arnoq** [ORelio/Minecraft-Console-Client#380]
Somebady can help me out with a minecraft console client that I can run on the raspberry pi? Im willing to pay for it.

**Comment by Arnoq** [comment]
I can't find how it works what I need to install to let it run.

**Comment by ORelio** [comment]
Did you read the [README}(https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt#L19) file?

**Comment by Arnoq** [comment]
Yes but cant find it on the raspberry po?

Op 8 feb. 2018 6:44 p.m. schreef "ORelio" <notifications@github.com>:

**Comment by ORelio** [comment]
I'm not sure what you do not understand about the instructions.
If you do not know how to use a command prompt, see [Terminal](https://www.raspberrypi.org/documentation/usage/terminal/).

**Comment by Barrythebae** [comment]
i have tried to install it on my raspberrypi also. but it says minecraftconsoleclient.exe doesnt exist. and i have all the files on the raspberry pi

**Comment by TheSnoozer** [comment]
You need to install ``mono`` (https://www.mono-project.com/download/stable/#download-lin) to run a windows application on a linux system.

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue and has been answered I'm assuming you got the client installed and thus go ahead and close this. if you still got an issue with the installation feel free to reopen. If you got any other question or problem please open a new issue.
