### ISSUE TITLE
Can't type or paste } or ]

### ISSUE THREAD

**Issue by Aidoboy** [ORelio/Minecraft-Console-Client#382]
Nothing happens. What's going on?

**Comment by Pokechu22** [comment]
What keyboard layout are you using?

**Comment by Aidoboy** [comment]
It's a standard US keyboard. I can't even paste the characters in though.

**Comment by Pokechu22** [comment]
Huh, looks like #137 actually wasn't ever fixed (I've also seen #47).  However I can type it myself.

Can you launch MCC with `--keyboard-debug`?

**Comment by Aidoboy** [comment]
```
.\MinecraftClient.exe --keyboard-debug
Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors
Keyboard debug mode: Press any key to display info
Key: F  Char: f Modifiers: 0
Key: K  Char: k Modifiers: 0
Key: G  Char: g Modifiers: 0
Key: Oem4       Char: [ Modifiers: 0
Key: Oem6       Char: ] Modifiers: 0
Key: Oem4       Char: [ Modifiers: 0
Key: Oem6       Char: ] Modifiers: 0
Key: Oem4       Char: [ Modifiers: 0
Key: Oem6       Char: ] Modifiers: 0
Key: Oem4       Char: [ Modifiers: 0
Key: Oem6       Char: ] Modifiers: 0
Key: Oem4       Char: { Modifiers: Shift
Key: Oem6       Char: } Modifiers: Shift
Key: Oem4       Char: { Modifiers: Shift
Key: Oem6       Char: } Modifiers: Shift
Key: Oem4       Char: { Modifiers: Shift
Key: Oem6       Char: } Modifiers: Shift
Key: Oem4       Char: { Modifiers: Shift
Key: Oem6       Char: } Modifiers: Shift
```

Still can't type after launch though.

**Comment by ORelio** [comment]
Not sure why `Oem4` does not work but indeed, `Oem6` keypress [are ignored](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ConsoleIO.cs#L145):
````C#
case ConsoleKey.Oem6:
    break;
````

**Comment by ORelio** [comment]
Please retry with the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), this should at least fix `]` and `}` 🙂

**Comment by Aidoboy** [comment]
Seems to work now! Thanks!
