### ISSUE TITLE
Remote Control error for a specific server?

### ISSUE THREAD

**Issue by Erixen** [ORelio/Minecraft-Console-Client#383]
![github_example](https://user-images.githubusercontent.com/6850795/36025773-8d4ea156-0d94-11e8-9ee0-0706b37fabac.PNG)
(In this example I sent a message to myself, ofc added as botowner)

So I recently joined a new server, and booted up my Console Client and tried to launch a script via Remote Control. However, every private message sent from and to the client gets a "?" before it (like shown in the picture), preventing it from executing the command. Is there any fix to this problem?

Note: This problem only occurs on one of the servers I play on.

**Comment by ORelio** [comment]
That is probably because of this server's unusual chat format. See [Detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt#L164).
