### ISSUE TITLE
Join message

### ISSUE THREAD

**Issue by 615283** [ORelio/Minecraft-Console-Client#384]
Any chance you could create a join message like minechat does that automatically sends upon join to server.

**Comment by ORelio** [comment]
You can schedule a [`send`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt#L66) command on login using the [Script Scheduler](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt#L192).
Useful files: [sample-tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini), [sample-script.txt](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.txt).

**Comment by 615283** [comment]
Thanks that helps alot!
