### ISSUE TITLE
Question about logging an entire line or using $0

### ISSUE THREAD

**Issue by yangciouou** [ORelio/Minecraft-Console-Client#386]
Hello,

I want to automatically log down the entire line when a few key words appear. The key word for my thing is "The theme was: --!" 

My matches file is : 

[Match]
regex=The theme was: *
actionOther=log $0

But when I go in game and the key words appear, it doesn't log the entire line, it just logs "$0." If I tried just using action=log $0, then it wouldn't log anything at all. This is what it looks like when it logs : http://prntscr.com/icv4ia 

Any other way or fixes to log the entire line that the key word appeared in?

**Comment by ORelio** [comment]
Ok my bad, `$0` is not supported, you can try this instead:
````ini
[Match]
regex=The theme was: (.*)
actionOther=log The theme was: $1
````
The parentheses are for delimiting matches in the regex and `$1` is for selecting the first match.
So alternatively you can log only the part between parentheses with `log $1`.

**Comment by yangciou** [comment]
Thank you! It works now.
