### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by MattoBois** [ORelio/Minecraft-Console-Client#387]
So I can join the server mc.good-gaming.com but i cannot warp to any of the game modes because it would give me a bunch of text and crash me. 
![image](https://user-images.githubusercontent.com/36364858/36072720-49a21cbc-0f74-11e8-9ca3-31d6a64e52cd.png)

**Comment by ORelio** [comment]
Seems related to #379, unfortunately the root cause for this has not been identified yet.

**Comment by TheSnoozer** [comment]
I'm closing this, since it seems to be a duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/379
