### ISSUE TITLE
Failed to ping ip

### ISSUE THREAD

**Issue by Destroyed768** [ORelio/Minecraft-Console-Client#392]
Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors
Resolving cosmicpvp.com...
Found server anonproxy011.ddns.net:50006 for domain cosmicpvp.com
Connecting to Minecraft.net...
Retrieving Server Info...
A timeout occured while attempting to connect to this IP.
Failed to ping this IP.
Server version : System.Threading.ThreadAbortException: Thread was being aborted.

This is what it tells me when i try and log in. Any reason why?

**Comment by Barnehhh** [comment]
Try specifying the actual server version in MinecraftClient.ini.(1.7.10 - 1.8.9 for cosmic)  It looks like right now your mcversion is set to auto. 

Haven't tested very thoroughly with the auto feature for detecting server versions, but I find the fast option for resolving srv records times out too quickly for a majority of servers before it even gets to attempting the Protocol18 lookup.

For your specific case though involving cosmicpvp, it seems that attempting to resolve it's server version fails regardless, you need to specify the version of the server manually.

Throws this when resolvesrvrecords is set to true. 

Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors
Resolving cosmicpvp.com...
Found server anonproxy011.ddns.net:50006 for domain cosmicpvp.com
Connecting to Minecraft.net...
Retrieving Server Info...
System.OverflowException: Value was either too large or too small for an Int32.
Failed to ping this IP.
Server version :

**Comment by TheSnoozer** [comment]
see also https://github.com/ORelio/Minecraft-Console-Client/issues/489#issuecomment-439757113

As described in most cases this seems to be a problem when `mcversion=auto` is in place. Try to set it to a specific version like ```mcversion=1.8.0``` inside the ```MinecraftClient.ini```

Closing this as part of an Issue Cleanup. Feel free to reopen if you still have a problem with this specific problem. Otherwise I would recommend to open a new issue.

**Comment by Klaxx0** [comment]
![Screenshot_20230424-020929](https://user-images.githubusercontent.com/131625148/233871384-84c93e31-a26f-4ce6-9e68-5bb9fcbf60df.png)
I still can't solve the problem, can you help me?

**Comment by Klaxx0** [comment]
Everything is fine server active server version correct experience not all changed but

**Comment by milutinke** [comment]
> Everything is fine server active server version correct experience not all changed but

Does it work now ?
If it doesn't, use a Proxy

**Comment by Klaxx0** [comment]
Everything is working and when I open the application on my own computer, it works, but when I open it on a virtual computer, it does not work. The virtual pc also uses the same file.

**Comment by milutinke** [comment]
> Everything is working and when I open the application on my own computer, it works, but when I open it on a virtual computer, it does not work. The virtual pc also uses the same file.

Your server ip seems to be blacklisted, use a proxy
