### ISSUE TITLE
public or private message.

### ISSUE THREAD

**Issue by Carlosca1998** [ORelio/Minecraft-Console-Client#393]
Someone helps me and tries in many ways but I can not find the chat format when it is a public or private message.

I would like to know if you could help me solve it.

Here is a picture of the chat the arriva is the private and the below the public.
https://i.imgur.com/d6VTrA7.png

Here is another photo but taken from the console client.
https://i.imgur.com/6PvYmk8.png
https://i.imgur.com/p96BxbO.png

**Comment by ORelio** [comment]
Hi,

That chat format is quite unusual, I'd suggest the following regexes in `MinecraftClient.ini`:

```ini
[ChatFormat]
builtins=false
public=^\[\] \[[^]]+\] ([A-Za-z0-9_]+) > (.+)$
private=^\[\] >Mensaje< \[(?:\[[^]]+\] )([A-Za-z0-9]+) -> yo\] (.+)$
```

You can try them here:

https://regex101.com/r/s23cPS/1
https://regex101.com/r/RciH1X/1

**Comment by TheSnoozer** [comment]
Since it seems the question was solved, I'm closing this as part of an issue cleanup.
if you still have a specific problem in getting this setup, feel free to reopen this issue. Otherwise please open a new issue.
