### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by BigZe14** [ORelio/Minecraft-Console-Client#394]
Right, I have been trying to get my accounts signed on, however, when I passwords are entered automatically through a .bat it turns out that they won't log on with this issue; 
Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password

Now, of course, all the passwords are correct, because I used them on a server, then when I logged off with them and 5 minutes later, I tried logging on with all of them again, none of them worked and gave me this message. 

I am using this client; Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors

I have looked at previous issues regarding this matter and none of them have seemed to fix it.
Thanks

**Comment by Barnehhh** [comment]
Do your passwords contain special symbols?  Some symbols can't be used in the password string for a batch file unless it's handled properly with escape sequences.

**Comment by BigZe14** [comment]
Nope, there are no special symbols used at all.
Its weird, because now it wont let me log onto my accounts using a normal minecraft client, I don't know whats happening.

**Comment by Barnehhh** [comment]
If you fail too many logins Mojang temporarily locks you out from logging into any accounts at all. I would wait about 10-20 minutes, make sure the password in your bat script is correct, then try logging in again.

**Comment by BigZe14** [comment]
I have realised that there was a hand selected accounts that I tried alot with. However, most of my accounts weren't logged into before this had happened.

**Comment by BigZe14** [comment]
And after many minutes, they still don't work and posses the same error.

**Comment by Barnehhh** [comment]
If the logins don't contain special characters, and you're certain that the login information is correct, it's still possible the formatting of the .bat script could be passing something it shouldn't for your password field. (If this is true, after enough failed attempts Mojang locks out your account from logging in at all.)

Maybe worth double checking, this is the way that I log my accounts in using batch.

START /MIN MinecraftClient.exe usernameoremail password serverip

**Comment by BigZe14** [comment]
Im certain all the login details are correct, and all the accounts must be unlocked by now.

I try and test them specifically in the Minecraft Console Client, they give me the error, however, they work in the normal Minecraft client.

**Comment by Barnehhh** [comment]
One thing you can try, is going into MinecraftClient.ini, setting debugmessages to true then running the client again. At the top of the window when it opens it will print the email your logging in with, the password. You should check to see if what MCC prints there, matches up with the login details you use in a normal launcher window as when going from batch -> Console Client something as simple as a space could cause it to be an invalid password.

**Comment by BigZe14** [comment]
Everything is correct, its just deciding not to work, some alts work, and like 80% of them don't.
Around a month ago, at least 90% of my alts was working completely fine, most are giving me incorrect password now, it can only be down to the client. Unless if you can video call me, and perhaps see what is happening.

**Comment by ORelio** [comment]
Hi, for your information, Mojang applies a severe rate limiting on how many logins you can perform in a short amount of time from the same IP address, regardless of whether they succeed or not. If you have more than a few account, I'd suggest enabling disk session cache in config that will retain session tokens and use them instead of logging in whenever possible. By default, session tokens are retained in memory only and not shared across multiple MCC instances.

**Comment by BigZe14** [comment]
Seems like only certain accounts are logging on now, and the rest aren't working. Thanks so much, at least I have some working if there is any more information or troubleshooting techniques you can comment before I can close the case, thanks!
