### ISSUE TITLE
I found a script and need help

### ISSUE THREAD

**Issue by corkyslurp** [ORelio/Minecraft-Console-Client#395]
`//MCCScript 1.0
int op = MCC.GetVarAsInt("op");
int cac = MCC.GetVarAsInt("cac");

for (int i = 0; i < 1; i++)
{   
    if (cac > 0)
    {
        if (op == 1)
        {
        int math2 = MCC.GetVarAsInt("math2");
        int math1 = MCC.GetVarAsInt("math1") + math2;
        int math3 = MCC.GetVarAsInt("math3") + math1 - math2;
        MCC.SendText("Solution: " + math3 + " + " + math2 + " = " + math1);
        }
        if (op == 2)
        {
        int math2 = MCC.GetVarAsInt("math2");
        int math1 = MCC.GetVarAsInt("math1") - math2;
        int math3 = MCC.GetVarAsInt("math3") + math1 + math2;
        MCC.SendText("Solution: " + math3 + " - " + math2 + " = " + math1);
        }
        if (op == 3)
        {
        int math2 = MCC.GetVarAsInt("math2");
        int math1 = MCC.GetVarAsInt("math1") * math2;
        int math3 = MCC.GetVarAsInt("math3") + math1 / math2;
        MCC.SendText("Solution: " + math3 + " * " + math2 + " = " + math1);
        }
        if (op == 4)
        {
        int math2 = MCC.GetVarAsInt("math2");
        int math1 = MCC.GetVarAsInt("math1") / math2;
        int math3 = MCC.GetVarAsInt("math3") + math1 * math2;
        MCC.SendText("Solution: " + math3 + " % " + math2 + " = " + math1);
        }
    }
    if (cac < 1)
    {
        MCC.SendText("Caculator is currently toggled off.");
        return null;
    }
}
return null;`

it tells us Caculator isnt on, how do I turn it on? Help xD

**Comment by ORelio** [comment]
Try "/set cac=1" inside MCC.

**Comment by TheSnoozer** [comment]
I'm assuming the original problem is solved by now. If not feel free to reopen it with more specific questions. If you have any other questions or problems, please open a new issue.
