### ISSUE TITLE
AutoRelog

### ISSUE THREAD

**Issue by DarkCobra18** [ORelio/Minecraft-Console-Client#396]
Hi, I have a question.

how can I make the autorelog when it reconnects execute a script to put the / login

**Comment by ORelio** [comment]
Use the ScriptScheduler, it has an onlogin event :)

**Comment by SpikeVanHellsing** [comment]
I have been wondering this too. I have the re log set to 10 I think. But it doesn't do anything when I get kicked.

**Comment by ORelio** [comment]
You need to configure kick messages.

**Comment by SpikeVanHellsing** [comment]
I did, by looking up some of the common ones and it still didn't reconnect. Does it only work for full vanilla servers?

**Comment by ORelio** [comment]
It should work for any server. Note that messages like "moved to hub" are not kick messages but regular messages. Use AutoRespond for them.

**Comment by TheSnoozer** [comment]
I'm closing this issue as part of an old issue cleanup.
Please open a new ticket if you still have problems in getting this to work.
