### ISSUE TITLE
Using a Proxy Server to connect accounts

### ISSUE THREAD

**Issue by Parted** [ORelio/Minecraft-Console-Client#399]
Hello,
I am trying to use a private proxy server to connect accounts to minecraft servers using console client, however I am getting a "Network Failed" message along with an error code 520.
https://puu.sh/zCxEk/34c4bee259.png
I have entered the proxy ip, port, proxy type, along with "enabled=True" in the .ini folder.
https://puu.sh/zCxSc/507ffaf19f.png
I have also tried entering "enabled=login" but I still get the same error.
This proxy works on my browser if I enter it into my Network Settings, I'm only getting an error when I try to use console client.

**Comment by Parted** [comment]
I have now figured out that the proxy is blocked by mojang. This is resolved.

**Comment by ORelio** [comment]
Mojang has gotten more and more strict about logins and unfortunately there is not much that can be done about it. At least you found out what was going on. Closing, then :)
