### ISSUE TITLE
How do I enable the message delay for autorespond?

### ISSUE THREAD

**Issue by PrismaticYT** [ORelio/Minecraft-Console-Client#402]

**Comment by ORelio** [comment]
Which message delay? If it runs a script, you can put a "wait" command as first command of the script.

**Comment by PrismaticYT** [comment]
It's not a script -- It's standard AutoRespond.

**Comment by ORelio** [comment]
There is no delay in standard AutoRespond.

**Comment by ORelio** [comment]
Example of how to put a delay:
https://github.com/ORelio/Minecraft-Console-Client/issues/1169#issuecomment-667726831
