### ISSUE TITLE
RemoteControl bot isn't working for me

### ISSUE THREAD

**Issue by jaycondale** [ORelio/Minecraft-Console-Client#403]
So, I've been using Console Client for about a year now, and I'm still trying to get the RemoteControl bot to work, I've tried to use the issues page on here but I can't seem to find an answer.

Can anyone help me?

CONFIG: 

````C#
botowners=jaycondale

[ChatFormat]
builtins=false #support for handling vanilla and common message formats
public=\d . [A-Z] . [a-zA-Z0-9_]+ [a-zA-Z0-9_]+ . (.+)$ #uncomment and adapt if necessary
private=^\[(?:[^\]]+)?~?([0-9a-zA-Z_]+) -> me\] (.+)$ #vanilla example
#tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

[RemoteControl]
enabled=true
autotpaccept=true
tpaccepteveryone=false
````
Chat format ingame is: http://prntscr.com/irkf3m
`[PREFIX USERNAME -> me] TEXT`

So what I'm trying to do, is let my bot try to do commands with /t, ex: /t Hallo send hi and the bot will send hi in chat.

Can anyone make me the correct chat format and or script if needed? 

Thanks in advice,
JayCondale

**Comment by ORelio** [comment]
Make sure your regex works by trying it out on regex101.com<http://regex101.com>. Specify the regex in the upper field and a PM sample on the field below, and see how the regex performs on the example.
