### ISSUE TITLE
a few bots in one time

### ISSUE THREAD

**Issue by FastJoe0** [ORelio/Minecraft-Console-Client#404]
How to make a few bots join the server and be on it at one time?

I used the script like this:

```
connect server1 bot1
send /login pass
wait 50
connect server1 bot2
send /login pass
wait 50
connect server1 bot3
send /login pass
wait 50
connect server1 bot4
send /login pass
```
but when the second bot was joined, first bot was kicked and so on.

**Comment by ORelio** [comment]
Launch multiple instances of the program, one per account.

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue and has been answered I'm going ahead and close this as part of an issue cleanup. Feel free to open a new issue if you still got a question or problem.
