### ISSUE TITLE
Problems running Console via Proxy or VPS

### ISSUE THREAD

**Issue by Considious** [ORelio/Minecraft-Console-Client#406]
I have attempted running the console via Proxy (A free one just to test) and came up with incorrect passwords. They work fine if i log in. they work if i login normally. So i attempted a VPS server, thinking that an actual real IP might help things, but i come up to the same problem. Mincraft Login Failed: Incorrect Password. I get nothing in debug messages either, and they are enabled. I have tried several times apart and had zero luck. is there something else i can try?

**Comment by Considious** [comment]
i read through some other similar issues. and there is not any special characters in the password, just simple numbers and letters. and i have it input via the config. 

its ubuntu 14 linux, and i tried running it with right click and mono terminal, and also mono MinecraftClient.exe

And mono MinecraftClient.exe /path to config

**Comment by ORelio** [comment]
If you are sure your password is correct, then the proxy IP is blacklisted by Mojang and nothing can be done about it (except trying another proxy).

**Comment by Considious** [comment]
It was free proxies for testing so thats possible. but i also ran it via VPS servers, what are the odds of a vps server being blacklisted? That had no proxy on it.

**Comment by ORelio** [comment]
I think Mojang may blacklist whole VPS providers. Try running the proxy locally with your home IP address to make sure the issue is not somewhere else in your configuration.
