### ISSUE TITLE
I Can't Use Time Interval Script Task

### ISSUE THREAD

**Issue by DoganayB** [ORelio/Minecraft-Console-Client#407]
**I wrote a basic script:**

###  test.txt
- send
- /hub
- wait 5 seconds
- send /login password
- wait 5 seconds
- send /sv skyblock

**then I wrote it inside the tasks.ini:**

[Task]
- triggerOnInterval=true
- timeInterval=20
- script=test.txt
**But it doesn't work. it didn't even detect the script. I can use my script in console but in that case, it doesn't be automatic.**
I want to reconnect to the server every 20 seconds.
**Note: Of course, I didn't use "-" or any pointing in script files.**

_How to I can do it? Can someone help me?_

**Comment by ORelio** [comment]
Just in case, make sure the `[ScriptScheduler]` section in your configuration file has `enabled=true`?

**Comment by TheSnoozer** [comment]
Assuming this was solved. if you still have an issue in getting this setup, feel free to reopen.
