### ISSUE TITLE
problem with /move

### ISSUE THREAD

**Issue by Neyreus** [ORelio/Minecraft-Console-Client#408]
after setting terrainandmovements to true and login in I get:

Unbehandelte Ausnahme: System.ArgumentException: Offset und Länge für das Array liegen außerhalb des gültigen Bereichs, oder die Anzahl ist größer als die Anzahl der Elemente vom Index bis zum Ende der Quellsammlung.
   bei System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   bei System.Collections.Generic.List`1.RemoveRange(Int32 index, Int32 count)
   bei MinecraftClient.Protocol.Handlers.Protocol18Handler.ProcessChunkColumnData(Int32 chunkX, Int32 chunkZ, UInt16 chunkMask, Boolean hasSkyLight, Boolean chunksContinuous, List`1 cache)
   bei MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   bei MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   bei MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

**Comment by ORelio** [comment]
Please upgrade to the latest version. See download link on the project's main page.

**Comment by Neyreus** [comment]
sorry for not searching properly
thank you for taking the time to answere anyways
