### ISSUE TITLE
Hoppers not activating near a MCC player

### ISSUE THREAD

**Issue by Kirvis111** [ORelio/Minecraft-Console-Client#409]
I dont know why, but when im online using console client, my hoppers don`t work.I have another alt on, on the same grinder, and it is able to spawn mobs, but when monsters die, they should drop their drops in hoppers, but the hoppers dont work.

**Comment by ORelio** [comment]
Some terrain interaction will not work if the client does not send accurate location data. You can enable that feature in the INI file by setting `terrainandmovements=true`. Also, make sure you have the [latest version](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
