### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by ridgewell** [ORelio/Minecraft-Console-Client#41]
For some reason, the following bots do not work on Linux with Mono (Debian Stable: 2.10.8.1) :

* AntiAFK
* ScriptScheduler

Is this a known issue? Are there any work-arounds?

The startup script does not initiate and the AntiAFK does not properly submit it's commands as necessitated. 

Is there a debug log I can look towards? 

I also note I am running an older version of Mono in the Stable Debian Repository. I'll be trying again with a newer version of Mono.

**Comment by ORelio** [comment]
Since both Mono and MCC were improved since then, the mono-related issues should hopefully be fixed by now. Closing, but feel free to reopen in case of issues involving both latest development builds and recent versions of Mono ;)
