### ISSUE TITLE
C# API access through python

### ISSUE THREAD

**Issue by NoHaxJustProgram** [ORelio/Minecraft-Console-Client#410]
I don't know if this is possible through this API or not.
Will I be able to access the C# API to interact with the world through a python script/file?

Edit:
I've only worked with 1 language and not multiple languages (Or 1 language + another API written in a different language) so this may seem like a stupid question to some but will really help out me and maybe others.

**Comment by Pokechu22** [comment]
I don't think there is anything currently implemented to use python scripts.  There is [IronPython](http://ironpython.net/) (python for the .NET framework), but I don't think there is a current way to use it with Minecraft Console Client.

**Comment by NoHaxJustProgram** [comment]
@Pokechu22 okay. Do you know if that will ever be available?

**Comment by ORelio** [comment]
That would be very complicated due to the way MCC compiles and loads C# scripts dynamically. The easiest way would be writing a C# script that runs your Python program.

**Comment by CarbonNeuron** [comment]
This was a very complicated approach to this, but what I set up on my console client was a websocket connection to a websocket server written in python.
