### ISSUE TITLE
Getting the colors of chat messages

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#414]
I am editing the code to help me use this program better, I would like it to do commands and the response from commands have colors assigned to them. I would like to know if it is possible to get the color of a chat message in the program, and how to do so.

**Comment by ORelio** [comment]
In C# scripts, GetText() will include classic color codes.

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue and has been answered I'm going ahead and close this as part of an issue cleanup. Feel free to open a new issue if you still got a question or problem.
