### ISSUE TITLE
Proxy/VPN detected

### ISSUE THREAD

**Issue by zusby** [ORelio/Minecraft-Console-Client#415]
Hello there, recently i bought a VPS to host 24/7 multiple console clients the problem is that, as the title says, it detects the vps as a vpn/proxy user the server we're talking about is cosmicpvp.com, i can't even browse into their forum because of this and it's the second vps i buy.
Is there a way to bypass the vpn detection?

**Comment by ORelio** [comment]
No, this is most likely based on the IP address of your VPS. You could invest in a Raspberry Pi (or similar) to have a mini server from your home IP address, for instance.

**Comment by zusby** [comment]
I literally just bought it, the Raspberry Pi 3 b which works fine but i'd like to have nearby 0 problems which my connection could have anytime.
I have something like 9-10 alts to log in and it is a pain to re-log one of them

**Comment by ORelio** [comment]
Mojang also rate-limit how many logins you can do, try enabling disk session cache to store and reuse session tokens.

**Comment by zusby** [comment]
That's not a problem, mojang limits the logins you can do in a certain period of time not the amount of logins you can do.
The main problem for me is that my internet service uses to reboot/crash usually once each 2 days

**Comment by ORelio** [comment]
If you have no further questions, I'll close this issue. Feel free to reopen if needed :wink:
