### ISSUE TITLE
Segmentation Fault Error

### ISSUE THREAD

**Issue by zGolden** [ORelio/Minecraft-Console-Client#417]
Hello.. Today I've opened the console client as everyday and went away. When I came back home, on the console the client crashed (I was not online anymore) and on the console there was a red "Segmentation fault" line.. Then I restarted the client and everything was ok.
I'm using the client on the raspberry pi with raspbian Jessie.
I connected to the raspberry trough JuiceSSH from phone.

**Comment by ORelio** [comment]
Seems like the Mono framework crashed. See mono --version, issues were reported for versions lower than 4.0. If this does not happen often, you may wrap it inside a shell script that would restart MCC if it exits.

#!/bin/sh
while true; do
mono MinecraftClient.exe
echo Restarting...
sleep 5
done

The sleep allows you to abort restart with CTRL+C

**Comment by zGolden** [comment]
Many thanks !

2018-04-11 8:04 GMT+02:00 ORelio <notifications@github.com>:

**Comment by TheSnoozer** [comment]
Even though I doubt that the underlying issue is solved, I'm closing this as part of an issue cleanup.

**Comment by ramdan1523** [comment]
My script doesn't work
