### ISSUE TITLE
Executing through cmd, interact with NodeJS

### ISSUE THREAD

**Issue by KOoRnFLaKes** [ORelio/Minecraft-Console-Client#419]
Hello i'm developing this discord bot witch runs an alt depending on the name for example ">Alt run *name*" and the bot.js needed to the bot would execute a different cmd oppening the minecraftclient of that alt, but whenever i execute minecraftclient with cmd it opens and ignores the account on mincraftclient.ini

**Comment by ORelio** [comment]
Invoke it from the correct "Working directory".

**Comment by KOoRnFLaKes** [comment]
thx i already made it work, ty for the help, now im having a "problem" cause idk if theres a way with node js if i can see if there's an alt running or not

**Comment by ORelio** [comment]
I don't know NodeJS but according to the documentation you need to listen for the "exit" event of your child process. See https://nodejs.org/api/child_process.html#child_process_event_exit

**Comment by ORelio** [comment]
If you have no further questions, I'll close this issue. Feel free to reopen if needed.
