### ISSUE TITLE
sometimes get "already logged in" when using reco

### ISSUE THREAD

**Issue by sparkkey** [ORelio/Minecraft-Console-Client#420]
I currently have an alt that I "reconnect" (RECO) once an hour.  This is the most successful way I have found to re-log on to a particular server and keep the account logged in.  

Sometimes the RECO command disconnects and reconnects the account faster than the server can detect that account disconnected, so it generates an  "account already logged in error"  and sits there wasting an hour until the next attempt.

Is there a "script" way to disconnect from a server, wait 20 seconds and then reconnect?
The EXIT and QUIT commands close the window down.

**Comment by ORelio** [comment]
Set the kick message in AutoRelog, it can try several times with a delay.

Alternatively, you can use the exit command and a wrapping script as shown in #417
