### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by MAnoDew** [ORelio/Minecraft-Console-Client#421]
My antivirus found out that the new dev version is a rare virus.
Is this true?

**Comment by ORelio** [comment]
Some Antivirus will flag unknown programs as malicious. I'd suggest to make sure your Antivirus is not relying solely on file reputation for this detection because MCC development builds are not very widespread and likely to be unknown to your Antivirus software.

**Comment by ORelio** [comment]
Closing this issue if you have no further questions. Feel free to reopen if needed.
