### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by daz5552** [ORelio/Minecraft-Console-Client#425]
Can u give me a last compile version for minecraft 1.10-1.12

**Comment by daz5552** [comment]
Oh thank u. And i join on server and now i stay on HUB how can i join to minigame?

**Comment by Pokechu22** [comment]
The `/server` command if the server is using bungeecord and it's enabled.  Otherwise you'll need to ask the server staff if there's a way to enter a game using just chat.

**Comment by daz5552** [comment]
i dont have permissions for this command if i can join to minigame i can stay the bot digger?afk digger on cobble generator?

**Comment by ORelio** [comment]
You can move around (to use portals...) or input commands. No inventory handling at the moment.

**Comment by ORelio** [comment]
Closing this issue if you have no further questions, See #205 for more details about inventories.
