### ISSUE TITLE
TriggerOnLogin doesn't work when /reco

### ISSUE THREAD

**Issue by MysticCoss** [ORelio/Minecraft-Console-Client#427]
I use your lastest build (http://yobuilder.com/32bE)
Scripts are excuted when i open the console but  not excuted when i use /reco command

[loginscript.txt](https://github.com/ORelio/Minecraft-Console-Client/files/1959092/loginscript.txt)
[loginscript.ini] 
[Task]
TriggerOnLogin=true
script=loginscript.txt

**Comment by ORelio** [comment]
Thanks for your report, I'll try to reproduce.

**Comment by drcheap** [comment]
I am also experiencing this issue using latest build.
Happens both when using a manual /reco as well as when auto relog bot reconnects me.

**Comment by TheSnoozer** [comment]
This should be fixed with the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client). Please download the latest version and try again. if the issue is still present, please free to reopen. For any other questions or issues please open a new issue.
