### ISSUE TITLE
Unknown Server Version - Send command on login to server / Failed to ping IP

### ISSUE THREAD

**Issue by GingeyBook** [ORelio/Minecraft-Console-Client#428]
I'm trying to connect to the ip Minesaga.org, however that Ip always times out for me. I don't have this problem when connecting to other servers. But this is the server that I wanted to use this for. Any fixes?

**Comment by ORelio** [comment]
Make sure you are using the latest version & please provide output

**Comment by GingeyBook** [comment]
I assume I have the latest version. Downloaded from here. 

Is this the output you need? https://i.imgur.com/lSwPuzi.png

**Comment by ORelio** [comment]
Ok, it is likely that the server version is not sent in response to a "server list" ping. As such, MCC cannot determine the server version and shows a prompt to input that manually. Try "1.12.2", for instance.

**Comment by GingeyBook** [comment]
Perfect, thanks. Now is there any way to automate things once I join the server? The ip just takes me to the server hub and then you have to use a command to join

**Comment by ORelio** [comment]
Yes, you can input the server version in configuration file to avoid typing it. Regarding commands, I'd suggest using the script scheduler. See README and sample files [here](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config).

**Comment by GingeyBook** [comment]
Sorry to be annoying, but is there a way to run a command every x minutes? I'm not well versed in c#

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini#L35

**Comment by GingeyBook** [comment]
I assume I put that in the tasks I want in the config file correct? It's not working for me
https://i.imgur.com/zRrHeEx.png

**Comment by GingeyBook** [comment]
I'm confused on where to put that. I tried putting it in the config file and in a file called tasks.ini. However, neither run my script when I log in. 
https://i.imgur.com/mWFQ4qu.png
https://i.imgur.com/FkUQhMM.png

**Comment by ORelio** [comment]
**MinecraftClient.ini**
````INI
[ScriptScheduler]
enabled=true
tasksfile=tasks.ini
````
**tasks.ini**
````INI
[Task]
triggeronlogin=true
script=join.txt
````
**join.txt**
````
send /joinqueue jurrasic
````

**Comment by SeichiSenpai** [comment]
im having the kind of problem
![image](https://user-images.githubusercontent.com/49830039/56467035-d3c4fe80-6443-11e9-993b-9bd622318801.png
when ever i put a server version like 1.13.2 its still not supported even though the server is indeed 1.13.2

**Comment by ORelio** [comment]
You are not using the [latest version](
