### ISSUE TITLE
Console Client Login Fail

### ISSUE THREAD

**Issue by duckkliss** [ORelio/Minecraft-Console-Client#430]
I've recently downloaded mc console client and it have been working fine for me but yesterday when i tried to log in on it i got this msg
Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors
Resolving pvpwars.net...
Found server play.pvpwars.net:25565 for domain pvpwars.net
Connecting to Minecraft.net...
Debug: Login Request: {"agent": { "name": "Minecraft", "version": 1 }, "username": "nope\u0040gmail\u002ecom", "password": "nope", "clientToken": "3c722e3ea46d4b4899ca3ccdc30e4b46" }
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
I'm not using a vpn of any sort. someone know how i can fix this?
It have been like this for 2 days now and I can log in on the normal client

**Comment by ORelio** [comment]
The login servers are refusing to process your login request, although it is perfectly valid, because of rate limiting. I think this could be worked around either by enabling disk session cache in configuration file & performing 1 successful login from another IP address (you might use a temporary access point with your smartphone for instance) or by reusing session from your Minecraft folder, but this is not implemented yet.

**Comment by duckkliss** [comment]
Thanks I enabled disk session cache and loged in on another IP address so now it's working again

**Comment by ORelio** [comment]
Glad to hear it. Just implemented the second option, MCC can now reuse session from your Minecraft folder as per the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).  Feel free to check it out and report any issue with it :slightly_smiling_face:

**Comment by dmnchild** [comment]
I hate to bump this after so long, but I am not finding anything on how to resolve this. Ive tried the suggestions here and keep getting that same error.

With the MinecraftClient.exe from the above link, I was able to login 1 alt 1 time. Server restarted I couldnt get back. I tried doing a second alt while that one was running, and no luck.

I can however use my vps this is on, vpn into it, and login just fine using the real game over vpn with the ip. So it doesnt seem like its an ip block.

**Comment by TheSnoozer** [comment]
This error usually pops up when the authentication failed too many times from a certain IP. If this happens Mojang will put your IP on the blacklist, that essentially will disallow any further authentication. Such blacklist is usually temporary and can last 1-4h. Based on your comment the login into the account works from a different place just fine, so I'd guess your local IP is currently blacklisted. Just try again, without authenticating in the meantime.
