### ISSUE TITLE
Tasks file not working?

### ISSUE THREAD

**Issue by GingeyBook** [ORelio/Minecraft-Console-Client#431]
I am trying to set up a few tasks so that when I log in it automatically takes me to a certain server from the hub. I am also trying to make it so that once I am on a server it will run a command every few minutes. I feel like I'm doing it right but I can't seem to make it work 

`[ScriptScheduler]
enabled=true
tasksfile=tasks.ini
`

That is in the config file

`[Task]
triggerOnLogin=true
script=Join.txt
`
`
[Task]
triggerOnInterval=true
timeInterval=600
script=Sell.txt
`

This is my tasks file

**Comment by ORelio** [comment]
Everything seems right.

[ScriptScheduler] enabled=true

Make sure there is a proper line break so it reads:

[ScriptScheduler]
enabled=true

**Comment by GingeyBook** [comment]
https://i.imgur.com/EhctfE2.png
https://i.imgur.com/v3MesfQ.png

**Comment by ORelio** [comment]
That's indeed the way to do it.
How is MCC invoked? By double-clicking on it? All the files are in the same folder, including the scripts?

**Comment by GingeyBook** [comment]
Yes and yes

**Comment by ORelio** [comment]
I'm out of suggestions. I'll try to add more debug messages to help nailing the issue.

**Comment by ORelio** [comment]
Please try this [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/189/artifacts) with `debugmessages=true` in `MinecraftClient.ini`.

**Comment by GingeyBook** [comment]
The other day it just started working, don't know what the issue was but it's fixed. Thanks.manc

On Tue, May 8, 2018, 1:30 PM ORelio <notifications@github.com<mailto:notifications@github.com>> wrote:

Please try this development build<https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/189/artifacts> with debugmessages=true in MinecraftClient.ini.

**Comment by ORelio** [comment]
Well... at least this should help other people having trouble with the ScriptScheduler. Redacting your email history and closing the issue. Feel free to reopen if needed.

**Comment by Latestion** [comment]
Not working for me either
