### ISSUE TITLE
Console Client crashing upon logging into a server

### ISSUE THREAD

**Issue by iArcane** [ORelio/Minecraft-Console-Client#435]
So i've been using the Client for a week now but recently i've had a problem where the client just crashes when joining a server. It shows that i join the server for a split second and then the console crashes/closes. Running it as an adminstrator didn't help as well. Using the latest build.

**Comment by ORelio** [comment]
I think this may be related to #432 -- could you post a screenshot of the error message? If running Windows, open a command prompt in the same directory as MinecraftClient.exe and type `MinecraftClient.exe` to launch it. Once it crash, you'll get back to the command prompt so you'll be able to take a screenshot.
