### ISSUE TITLE
Is it possible to use it with cracked usernames?

### ISSUE THREAD

**Issue by Sapu98** [ORelio/Minecraft-Console-Client#436]
The title, says it, I need to use it without a premium account, is it possible?

**Comment by Pokechu22** [comment]
Purchase the game.  I will not assist you with piracy.

**Comment by Sapu98** [comment]
I bought the game 2 years ago lol, just need to login with several accounts, the probleim is that i dont want to pay 3 more accounts.

**Comment by TheSnoozer** [comment]
Closing as part of an issue cleanup.
