### ISSUE TITLE
ConsoleIO has compatibility issues with CJK characters

### ISSUE THREAD

**Issue by tobiichiamane** [ORelio/Minecraft-Console-Client#437]
CJK characters consume 2 blocks in buffer instead of 1. When trying to use this console in Chinese (Simplified Chinese, but Japanese, Traditional Chinese and Korean will cause same issues), if you try to delete your input, you'll get results like this (CJK characters can only be erased half at a time): 
![image](https://user-images.githubusercontent.com/14824064/39846097-72956e92-542c-11e8-94f9-12579409a5b2.png)
And, if a new line is written while you're inputting, you'll get results like this (the output is a chaos, your unfinished input will be repeated for a lot of times, and the real output is all mixed up with those repeated characters):
![image](https://user-images.githubusercontent.com/14824064/39846219-0f832fbe-542d-11e8-8342-ae0952e76718.png)

**Comment by ORelio** [comment]
Thanks for your report. If I understand correctly, you can type but need to hit backspace twice to erase a character and output happening while you are in the process of typing one charecter would be messed up? I'm not familiar at all with inputing CJK characters but I assume I would be able to reproduce by setting my input method to `Chinese (Simplified)` on Windows?

**Comment by TobiichiAmane** [comment]
Indeed. Just try to input (or even copy and paste) some CJK characters into the console, and try to erase them by hitting backspace, you'll notice the issue. 
Here are some test patterns for you to copy and paste: 

简体中文测试
(6 CJK characters, meaning "Simplified Chinese test")

繁體中文測試
(6 CJK characters, meaning "Traditional Chinese test")

And also, if you receive a new message while having some CJK characters already inputted but not sent away, the output will be a chaos.

**Comment by ORelio** [comment]
Thread continued in #941
