### ISSUE TITLE
Raspberry Pi Debian 9 installation logs in but doesn't display updates, disconnects

### ISSUE THREAD

**Issue by Triple7Factor** [ORelio/Minecraft-Console-Client#438]
I am using a Raspberry Pi model B with a Debian 9 Raspbian installation, and have installed the latest version of mono and the minecraft console client. When launching, it logs in and connects to a minecraft server without issue, and commands/chat sent from the client show up on the server instantly. The client seems to take a really long time - from 30 seconds to several minutes, however, to display any output after "Type '/quit' to leave the server." appears. Eventually, it'll display the first line of the chat log ("Player joined the game"), and after several minutes it might display another line or two. At some point, the client disconnects (you'll see the player log out of the server). Finally after another short wait, the client says the connection has been lost. The client works normally on other non rasp-pi installations with the same server/account.

**Comment by Triple7Factor** [comment]
Thought it might help to see what is happening rather than trying to describe it. I recorded a video to demonstrate here: [https://vimeo.com/270122964](url)

Top window is MCC via ssh on the rasp pi, bottom is local on a Debian 9 desktop. You can see that messages sent via the rasp pi client come through instantly, however the pi client lags behind in receiving anything for far too long. Eventually you'll notice that the top client (player Lucky7Charm) disconnects, though in the console window there is no change. Eventually, if I were to leave it another 5 minutes or so, the rasp pi client would say that the connection has been lost.

**Comment by ORelio** [comment]
I think the issue is located in the framework running MCC, I experienced that in the past because of issues in the CFB-8 AES encryption in Mono and replaced that part with CFB-8 AES encryption from BouncyCastle.

Check you `mono --version` on both machines, I'd be very interested to know what mono versions work and do not work.

**Comment by Triple7Factor** [comment]
The desktop version is 4.6.2 while the rasp pi is running version 5.12.0.226. I'll try downgrading to a previous version, but are there any that I should avoid or that should definitely work to your knowledge?

**Comment by ORelio** [comment]
I don't have enough data on this, I only know there are more problems with the ARM version used on the PI regardless of the version and that Mono < 4.0 is not working properly.
