### ISSUE TITLE
MCC crashes on unloading of chatbot

### ISSUE THREAD

**Issue by drcheap** [ORelio/Minecraft-Console-Client#441]
I have a custom chatbot that overrides GetText(string text) from ChatBot.cs

If a certain trigger text is received, the bot calls the ChatBot.UnloadBot() method.  This in turn calls McTcpClient.BotUnLoad(ChatBot b), which removes the bot from the bots List.  At this point, program flow returns back to the McTcpClient.OnTextReceived(string text, bool isJson) and it then attempts to run the next line:
https://github.com/ORelio/Minecraft-Console-Client/blob/79aaa0477551b252fb9681ffbf677fbaba7e3731/MinecraftClient/McTcpClient.cs#L462

Of course, since the bot was just removed, bots[i] throws an ArgumentOutOfRangeException, which is unhandled, and the entire MCC process crashes.  This should be easily avoidable by just adding that type of exception to the catch block just after that https://github.com/ORelio/Minecraft-Console-Client/blob/79aaa0477551b252fb9681ffbf677fbaba7e3731/MinecraftClient/McTcpClient.cs#L464

Perhaps just logging a "Bot has disappeared" or something to the console is sufficient for handling this.

**Comment by ORelio** [comment]
Thanks for your report with detailed explanations. I changed the iteration process to work on a copy of the bot list, and avoid calling the second GetText variant if the bot unloaded itself when calling the first variant. Please try the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and tell me if that worked for you :slightly_smiling_face:

**Comment by drcheap** [comment]
Yup, works great.  Thanks!!
