### ISSUE TITLE
VPS is not displaying any commands

### ISSUE THREAD

**Issue by Raos1337** [ORelio/Minecraft-Console-Client#442]
Hey im completly new to all this stuff so pls dont go all in on me :D 
So i have done everything what has to be done to afk ( i think) but now when i join on a server first of all it tells me ''Server was successfully joined'' but than when i try to do ''/queue Mars'' (Im playing on Decimate) nothing happens
I tried several commands and its not working.
Next to that i cant find my Alt in the Lobby even though it said ''Server was successfully joined''

And i have a second question: What if we say everything works fine for me. Can i just close all the vps/putty stuff and it will keep on running even when my comp is off?

Regards!

**Comment by ORelio** [comment]
Try enabling terrainandmovements, maybe the server requires that you move before you can send commands, or there is a network issue with Mono, make sure you have Mono v4.0-4.2.

You can run MCC in background with the "screen" command, look at the docs for more info.

**Comment by Raos1337** [comment]
Do u mean by ''running it in the backround'' running it while my comp is on or off?
