### ISSUE TITLE
see list of people connected? like tab in-game

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#445]

**Comment by Pokechu22** [comment]
`/list` (vanilla has this command, but MCC provides its own version that works the same way as tab -- i.e. even if you don't have permission to do `/list` normally)

**Comment by Pokechu22** [comment]
Ah.  Yeah, looks like there's a `GetOnlinePlayers` method you can use.

**Comment by TheSnoozer** [comment]
Since this question is quite old and was answered, I'm closing this as part of an issue cleanup. if you still have any question regarding to this feel free to reopen. If you have any other question, please open a new issue.
