### ISSUE TITLE
command line input to chatbot

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#446]
How can I pass input (either command-line arguments or as stdin) to the ChatBot?

**Comment by ORelio** [comment]
You can set appvars in config before launch or with /set, or directly in the script file, you can also send PMs to your bot and handle them in GetText().

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue and has been answered I'm going ahead and close this as part of an issue cleanup. Feel free to open a new issue if you still got a question or problem.
