### ISSUE TITLE
Error after it's left running for a while

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#447]
```
Connection has been lost.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>>030;3R
```

**Comment by ORelio** [comment]
Mono is known to cause random disconnections, either make sure you have Mono 4.0-4.2 or enable the AutoRelog mechanism.

**Comment by theonlygusti** [comment]
I'm on mono 4.4.2, should I downgrade to mono 4.2?

**Comment by theonlygusti** [comment]
@ORelio

**Comment by ORelio** [comment]
Not sure, but please do, just in case, I have not nailed down on which Mono version they introduced the regression, plus it seems to depend on the operating system too (see also: #438 and #442)

**Comment by theonlygusti** [comment]
@ORelio how do I enable autorelog?

**Comment by TheSnoozer** [comment]
https://github.com/ORelio/Minecraft-Console-Client/issues/543 seems related

**Comment by theonlygusti** [comment]
on:macOS

**Comment by ORelio** [comment]
Unfortunately we could not reproduce this issue.
