### ISSUE TITLE
Enable Terrain and Movement?

### ISSUE THREAD

**Issue by Raos1337** [ORelio/Minecraft-Console-Client#448]
So ORelio told me that i can maybe solve my problem by ''activating'' terrain and movements in the .ini
but i cant find anything that says terrainandmovement=false that i can make =true

where can i find that?

EDIT: Since i couldnt find it i just put it in myself to the advanced setting ''terrainandmovements=true''
but still nothing happens. I typed in /move but i still couldnt connect
EDIT2: So it looks like the ''terrainandmovements'' thingy is only in the 1.9 .ini file, i downloaded a 'newer' version of that and found it in there, but still didnt work with that.

Does anyone have a setup MCC with everyone done already where i just have to put in my details and put it into my vps for a download for me?

**Comment by ORelio** [comment]
Download the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and launch it in an empty folder, it will generate a new configuration file for you that will have the setting.

**Comment by TheSnoozer** [comment]
Since the question was answered quite a while ago I'm closing this issue as part of an issue cleanup.
Feel free to reopen if you still have a problem in getting this setup. Otherwise please open a new issue.
