### ISSUE TITLE
Task.ini onlogin work just once

### ISSUE THREAD

**Issue by meciless** [ORelio/Minecraft-Console-Client#449]
Offline mode use:
First time onlogin is working but if server disconnect and autorelog working onlogin does not work like the first time.

**Comment by ORelio** [comment]
Well, that's the intended behavior, since you're logging in for the second time. You probably want to use `TriggerOnLogin` instead of `TriggerOnFirstLogin`?

**Comment by meciless** [comment]
[Task]
triggerOnLogin=true
script=skyblock.txt

First, login script work but after autorecconect, script does not working.

**Comment by ORelio** [comment]
OK so that is an issue, I'll look into this.

**Comment by Barnehhh** [comment]
I can second this, runs the first time with triggerOnLogin but anytime after with reconnect there's nothing.

**Comment by meciless** [comment]
How is the situation this problem? is it solved ?

**Comment by ORelio** [comment]
Not enough time to handle all the issues. Contributions are welcome!

**Comment by drcheap** [comment]
This is the same as #427

**Comment by madl-ash** [comment]
+1

**Comment by TheSnoozer** [comment]
This was most likely fixed by https://github.com/ORelio/Minecraft-Console-Client/pull/809 could you perhaps download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) and try again?
