### ISSUE TITLE
Failed To Check Session

### ISSUE THREAD

**Issue by iAlreadyExist** [ORelio/Minecraft-Console-Client#450]
After today mojang update to their login system the client doesnt want to work anymore
it says 
`Login failed :
Failed to check session.`

**Comment by CryptoIsTheFuture** [comment]
Having the same issue here. Hope you can fix it ASAP

**Comment by TNTUP** [comment]
Same issue aswell :(

**Comment by raiin2032** [comment]
Same here

**Comment by TNTUP** [comment]
Edited my message, read MojangStatus Tweet if its MCC case, I hope so..

**Comment by raiin2032** [comment]
Just wait for him at this point (rip my skyrealm afk h24)

**Comment by TNTUP** [comment]
@raiin2032 Yeah same (for my case iron farm h24 xDD) but since he lives in Europe (meaning its midnight at his home) guessing an update later or tomorrow :( For the time being, vanilla/magic launcher works thats ill do^^

**Comment by raiin2032** [comment]
Same I live in EU 👍 
@TNTUP skyrealms.games?

**Comment by TNTUP** [comment]
@raiin2032 Nah, on my server. I've got lucky the MCC was logged in when the server reboots at 4am EST x)

**Comment by TNTUP** [comment]
Fixed on my side now. Was a Mojang issue

**Comment by ORelio** [comment]
Well, I was away during the downtime but good idea @TNTUP, just added full debug output for any HTTPS request performed by MCC.

**Comment by TNTUP** [comment]
Thanks @ORelio !^^ Expected the same error message as others on MojangSupport' twitter saying "Invalid IP" but I will try that one and it should be the same as yesterday^^

**Comment by ORelio** [comment]
This should be resolved as per #451 :)
