### ISSUE TITLE
Failed to Check Session at Login

### ISSUE THREAD

**Issue by JacksonWillford** [ORelio/Minecraft-Console-Client#451]
Hi, I did some basic Googling. I play on a server where a couple of my accounts are frequently online and nothing has changed since they have stopped working. The accounts are legitimate and the server is in online mode (this has been the culprit in some of the other similar Github issues according to Google).

https://i.imgur.com/cTbevM7.png

I'm at a little bit of a loss here and I'm not sure what to do. Can someone please advise me on any action to take?

**Comment by Cobaye** [comment]
Mojang's having some trouble atm with the authentication servers. Only thing you can do is just wait...

**Comment by ORelio** [comment]
Seems related to #450, Mojang session server experiencing downtime. Just added full debug output for any HTTPS request performed by MCC, this way you can see all requests by setting `debugmessages=true`.

**Comment by iAlreadyExist** [comment]
i can log in with minecraft launcher i dont have problem there
when i try log in it doesnt allow me 
failed to check session

**Comment by sparkkey** [comment]
Same here.  I can log in normally but cannot log in the console clients.  I hope Mojang is not proactively detecting and filtering out console client log ins.  :(

**Comment by ORelio** [comment]
Mojang probably deployed new security measures to prevent malicious logins or server joins. Probably some kind of heuristic filter, as the requests issued by MCC are compliant with the protocol. That would explain why a "downtime" affected people using the official client as well, last night. I don't think they are targeting MCC specifically, but it has false positives.

**Comment by Parted** [comment]
I'm having the same issue. Does anyone know when this might be fixed?

**Comment by ORelio** [comment]
Hard to answer. It probably won't fix by itself. Just tried, I can login using the official game but not using MCC. MCC sets a `User-Agent` string, tried a Java user agent instead, no change. I'd need the exact sequence of all HTTPS requests and responses (including HTTP headers) between a vanilla Minecraft client and the auth servers in order to compare with MCC, but the vanilla launcher/authlib implements certificate pinning so that's not straightforward to intercept. Any help for that would be appreciated.

**Comment by ExplodingTacos** [comment]
Sane issue. I use console client to afk. IS console client useless now?

**Comment by sparkkey** [comment]
The Big O will save us.  He is on it combing through the binary with his TI hexadecimal calculator.  He will deliver us to MCC land!

**Comment by Pokechu22** [comment]
One possible option would be to launch MCC via the launcher... but I don't know enough about version JSONs to implement that.

Anyways, one thing that I see that's wrong: MCC isn't sending a value for the `selectedProfile` field.  I'm pretty sure that's what's wrong.

> IS console client useless now?
It's still an implementation of the protocol; only authentication is broken.

**Comment by ExplodingTacos** [comment]
How do i fix it?

**Comment by Pokechu22** [comment]
I was going to say wait for orelio to fix it, but it looks like there is a simple workaround: if you've got session caching enabled, you can edit `SessionCache.ini` and fill in the missing UUID field (there should be a `,,`; put the UUID in between the two commas).  Then when MCC loads it, it seems like it's loading the UUID correctly.

**Comment by ExplodingTacos** [comment]
uuid of what?

**Comment by ORelio** [comment]
Thanks @Pokechu22 for the hint! So indeed, Mojang made some changes yesterday but this wasn't a mysterious security measure, actually they changed the order of some fields in login response, and the (crappy) parsing code handling that response in MCC wasn't retrieving the account's UUID correctly anymore, leading to invalid validation request on server join. Just rewrote that part properly, it should be possible to join servers again using the last [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) :slightly_smiling_face:

On a side note, thanks for your humor @sparkkey, laughed very hard :joy:

**Comment by TNTUP** [comment]
@sparkkey Thats why my TNT has gone fisson... Anyways this is solved, big thanks to you Orelio! XD

**Comment by sparkkey** [comment]
its the least I can do... other than present more issues....

I tried the new build you posted and everything was good up to "retrieving Servo info...", and then it generated a "timeout occured while attempting to connect to this IP"
.... and then "Failed to ping this IP"
Server version: System.Threading.ThreadAbortException: Thread was being aborted.

It could be the server, however I never experienced this before with the previous version.
I will try again in a bit.   any thoughts?

**Comment by theonlygusti** [comment]
This is a problem I just noticed.

I can log in with the minecraft launcher, but MCC no longer logs me in.

```Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors
Resolving *...
Cached session is invalid or expired.
Connecting to Minecraft.net...
Retrieving Server Info...
Server version : *.
Version is supported.
Logging in...
Checking Session...
Login failed :
Failed to check session.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>```

**Comment by Gopal050** [comment]
I've been having the same problem sparkkey is having. 
"Retriving Server Info...
A timeout occured while attempting to connect to this IP
Failed to ping this IP
Server version : System.Threading.ThreadAbortException: Thread was being aborted."
I like everyone else wasn't able to connect to the server due to the problem which you patched. However, once I downloaded the patch I started getting this error when attempting to join. I've tried on a Laptop and a PC and both give me the same results. Any ideas on what to do would be appreciated.

**Comment by Zacatero** [comment]
I've also been having the "Failed to check session" issue

**Comment by sparkkey** [comment]
update.  I went ahead and used the default created ini file (ver 1.12.2), added a user, PW and server and still it does not connect.

hopefully pic shows:

![capture](https://user-images.githubusercontent.com/1351572/40463119-29c18d58-5ec8-11e8-99f7-864ff22160f3.JPG)

**Comment by ORelio** [comment]
@theonlygusti Are you sure you downloaded the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)?
@sparkkey @Gopal050 That seems unrelated to the session problem described in this thread. When the server does not respond to the [server ling ping](http://wiki.vg/Server_List_Ping#Response) request, MCC does not know the Minecraft version to use and prompts you. If you know the version to use, e.g. 1.12.2, just type `1.12.2` and press Enter.

**Comment by sparkkey** [comment]
Big O! you are a genius!
I forced the mcversion to the version of the server:
mcversion=1.8.1
and at try that seemed to fix it.
"auto" was fine for the previous version I was using (1.9.1) but I guess I had to force this version to a specific version.
Thanks!

**Comment by EaglePopes** [comment]
@ORelio i have latest dev build and i tried to force it to load mcversions from 1.7 to 1.8.9 and i get the 
"Loggin failed :Failed to check session" error

**Comment by ORelio** [comment]
@EaglePopes Try launching the latest dev build in an empty folder and re-authenticate from scratch. If that does not help, try setting `debugmessages=true` and take a look at the session check request on server join. All the fields should be properly set. If you still have trouble or don't understand the debug messages you can post a screenshot but you'll have to properly redact email/password/session tokens before posting it.

**Comment by robbbak** [comment]
@ORelio 
I have the same problem: Login failed : Failed to check session.
But it works when when i use it on my pc but it doesnt work when use it on my vps.

I use the latest build.

**Comment by TheSnoozer** [comment]
For now it seems that the issue was solved and thus I'm going ahead and close this as part of an issue cleanup. Feel free to reopen if you don't get it to work and also make sure to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) before you try again ;)

**Comment by Damian-vanden-Haak** [comment]
Hey i see this is "Resolved" But how do i fix it?
My console client map looks nothing like this original yet it still worked until recently. Now when i relog it says :SSL error.
I already tried to manually add the 2 new updated files but idk why it doesn't work.

Screenshot:
![image](https://user-images.githubusercontent.com/70750916/136071609-4ddabab5-05bf-4227-b65f-2929c5e4e8ac.png)
