### ISSUE TITLE
Failed to check session

### ISSUE THREAD

**Issue by ExplodingTacos** [ORelio/Minecraft-Console-Client#452]
Issue 451 has not really said any fixes for this or they were talking in code or something.  Is MCC useless now? Is there a way to resolve it? When will it be fixed?

Thank you

Tacos

**Comment by Pokechu22** [comment]
It should be fixed if you update.

**Comment by ExplodingTacos** [comment]
when?

**Comment by Pokechu22** [comment]
As of commit a75710b.  You can get the latest build [here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by HexedHero** [comment]
Use the newest version, there was a fix today!

**Comment by ORelio** [comment]
Seems like a duplicate of #451. So yes, the issue _is_ resolved, just update your console client :wink:
