### ISSUE TITLE
Does not automatically reconnect me to a server?

### ISSUE THREAD

**Issue by Dogg16** [ORelio/Minecraft-Console-Client#453]
so i was recently using an older version of the console client and just within the last 2 hours downloaded and started using the newest development build, but as a result of this when i have been kicked from the server the client does not automatically reconnect me to the server.

**Comment by ORelio** [comment]
You can relog automatically by configuring the AutoRelog feature in your config file.

**Comment by ORelio** [comment]
For usage details and sample files, see [here](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)

**Comment by TheSnoozer** [comment]
Since this question seems quite old and has been answered, I'm closing this as part of an issue cleanup. if you still have a problem with this specific issue, feel free to reopen. Otherwise I would recommend to open a new issue.
