### ISSUE TITLE
Console Client Wont Work

### ISSUE THREAD

**Issue by MeowMan123456789000** [ORelio/Minecraft-Console-Client#454]
I made a github account to post this:

I am trying to  use your software but this error keeps popping up:
http://prntscr.com/jly70e

Help!

**Comment by MeowMan123456789000** [comment]
Please respond!

**Comment by HexedHero** [comment]
Use the newest version, there was a fix today!

**Comment by ORelio** [comment]
I'll close the issue as the answer has been given, feel free to reopen if you still need help :wink:
