### ISSUE TITLE
Console client i need help!

### ISSUE THREAD

**Issue by duckkliss** [ORelio/Minecraft-Console-Client#455]
I have recently gotten this msg:
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Login failed :
Failed to check session.
[MCC] [AutoRelog] Waiting 10 seconds before reconnecting...
Restarting Minecraft Console Client...
Cached session is still valid for duckkliss.
Success. (session ID: 1c0f552a789f47ad84636d21b2613e6c)
Retrieving Server Info...
Server version : PW-Proxy 1.7.x-1.12.x (protocol v340).
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Login failed :
Failed to check session.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

I am not very good at this stuff so is there a way to fix it and if there is can somoene explain it in a easy way thank you :D

**Comment by HexedHero** [comment]
Use the newest version, there was a fix today!

**Comment by duckkliss** [comment]
Where can i find the new version?

**Comment by duckkliss** [comment]
the problem is fixed thank you all

**Comment by ORelio** [comment]
(Just for keeping the record: this is a duplicate of #451)
