### ISSUE TITLE
Suggestion: add some kind of auto-generated build number

### ISSUE THREAD

**Issue by Pokechu22** [ORelio/Minecraft-Console-Client#456]
It would be useful to include the build number in the generated artifacts.  That way, rather than saying "Update to the latest version", one can say "Make sure you've updated to build 192 or later" (and also easily check what version someone is on).  Possibly, it would make sense to also include the git SHA in it (but since those aren't incremental, it would be less useful for some).

I don't actually know how to do this, but according to [CircleCI's docs](https://circleci.com/docs/2.0/env-vars/#circleci-built-in-environment-variables) there are `CIRCLE_SHA1` and `CIRCLE_BUILD_NUM` environment variables set during the build process.

Of course those are only set during the build process, and not when building locally; I'm not entirely sure what should be done in that case (perhaps just say "unknown" or "local").

**Comment by ORelio** [comment]
Don't know how to do this either but AppVeyor also has [environment variables](https://www.appveyor.com/docs/environment-variables/) so that should be possible. Will look into this.

**Comment by Pokechu22** [comment]
:facepalm: not sure why I thought you were using circleci, since I checked and tried to find the right documentation before.  But, yeah, hopefully this shouldn't be too hard...

**Comment by ORelio** [comment]
That's fine, no problem ^^

**Comment by TheSnoozer** [comment]
Thanks for the great suggestion :-)

Since this was implemented it seems that can now be closed :-)

PS: even works great on a local environment:
```
git checkout HEAD ./MinecraftClient/Properties/AssemblyInfo.cs

DATE=`date +%Y-%m-%d`
COMMIT=`git rev-parse --short HEAD`
echo -e "\n[assembly: AssemblyConfiguration(\"Built on $DATE from commit $COMMIT\")]" >> ./MinecraftClient/Properties/AssemblyInfo.cs


msbuild MinecraftClient.sln /t:build /p:Configuration=Debug /p:Platform="x86" /p:TargetFrameworkVersion="v4.0" /verbosity:minimal
msbuild MinecraftClient.sln /t:build /p:Configuration=Release /p:Platform="x86" /p:TargetFrameworkVersion="v4.0" /verbosity:minimal

git checkout HEAD ./MinecraftClient/Properties/AssemblyInfo.cs
```

**Comment by ORelio** [comment]
Actually this should print the commit number in AppVeyor builds but did not worked even after following the AppVeyor documentation. However it works fine when adding it manually. For some reason, AppVeyor does not add it. I'm using the following build script:
```cmd
pwd
echo [assembly: AssemblyConfiguration("AppVeyor build %APPVEYOR_BUILD_NUMBER%, built on %DATE% from commit %APPVEYOR_REPO_COMMIT:~0,7%")] >> C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs
```
As you can see in https://ci.appveyor.com/project/ORelio/minecraft-console-client the script runs but the line does not seems to be added to the file :thinking:

**Comment by TheSnoozer** [comment]
Sorry for closing this too early :-/
Mhh I have no way to view the original sources. Could you potentially output the file? On windows that should work with `type  C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs`.
it seems that the native windows `echo` adds a new line. That might not be the case for the linux `echo` that just appends the content. In this specific case the last line in the [AssemblyInfo.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Properties/AssemblyInfo.cs#L42) is actually a comment and thus the newly added version is actually commented out. I bumped into this as well and realized that the line I was adding was essentially commented out....as a result I added a ``echo -e "\n.....`` not sure what AppVeyor does here, but would be worth to check the actual contents of the file.

**Comment by TheSnoozer** [comment]
Since I don't have access to the build....did you had the time to check this?
Another alternative should be just adding a new empty line at the end of `AssemblyInfo.cs`. In that case all echo's should work and the echo certainly wouldn't end up after a comment...

**Comment by ORelio** [comment]
Hi @TheSnoozer
Here is the current build script:
```batch
pwd
echo [assembly: AssemblyConfiguration("AppVeyor build %APPVEYOR_BUILD_NUMBER%, built on %DATE% from commit %APPVEYOR_REPO_COMMIT:~0,7%")] >> C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs
````
Using pwd I could check the file location on AppVeyor build VM, then use absolute path. Unfortunately, this still does not work. Just added:
````batch
type C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs
````
for future builds, might help understanding why it does not work. You may want to try setting up your own temporary AppVeyor account for testing out?

**Comment by TheSnoozer** [comment]
After some debugging I think my newline theory seems to be right :-)
I have used two echo's (see [here](https://ci.appveyor.com/project/TheSnoozer/minecraft-console-client/builds/24149693)) whereby the first one ended up at the end of the line (essentially commented out) and the second echo in the next line. Unfortunately the `echo -e '\n'` doesn't seem to work (even as sh) since this results in an unwanted `-n` in the resulting file.

After some debugging I came up with the following `Before Build-Script (CMD)`:
```
echo. >> C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs

echo [assembly: AssemblyConfiguration("AppVeyor build %APPVEYOR_BUILD_NUMBER%, built on %DATE% from commit %APPVEYOR_REPO_COMMIT:~0,7%")] >> C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs
```

that results in https://ci.appveyor.com/project/TheSnoozer/minecraft-console-client/builds/24149783

When being downloaded the version is also being displayed:
![Selection_2019-04-27_22-31-47](https://user-images.githubusercontent.com/6849390/56857587-7518ec80-693d-11e9-85e1-24c22ee7b4bd.png)

Let me know if you need more info - I certainly have more debugging info in my build (e.g. `cat C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs`) :-)

**Comment by ORelio** [comment]
Good job 😮
Just updated the before build script to the following value:
```batch
echo. >> C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs
echo [assembly: AssemblyConfiguration("AppVeyor build %APPVEYOR_BUILD_NUMBER%, built on %DATE% from commit %APPVEYOR_REPO_COMMIT:~0,7%")] >> C:\projects\minecraft-console-client\MinecraftClient\Properties\AssemblyInfo.cs
```

**Comment by ORelio** [comment]
It works 👍
