### ISSUE TITLE
Disconnect from your VPN??

### ISSUE THREAD

**Issue by Raos1337** [ORelio/Minecraft-Console-Client#457]
Everytime i join the Server i play on i get kicked for using a VPN?
I dont have any vpn's activated rn, is it cuz of the vps? how can i fix that?
Regards

**Comment by ORelio** [comment]
You can't bypass this because it is based on the IP address you use to connect. So either try to find another proxy/vps or run it at home on a Raspberry Pi (for instance).

**Comment by TheSnoozer** [comment]
This seems to be a server plugin that checks if you are using a VPN/VPS. Contact the server staff to verify that.

Since the question is quite old and seems to answered, I'm closing this as part of an issue cleanup.
