### ISSUE TITLE
OverflowException: VarInt too big

### ISSUE THREAD

**Issue by irfatftw** [ORelio/Minecraft-Console-Client#458]
Getting the following error when trying to connect to a server with only one account.  Connects to the hub fine but crashes when choosing a server to go to:
https://gyazo.com/7fb37abd3a56409152d202e4bd371255

**Comment by meciless** [comment]
I got the same problem first time i login and read other issues my problem solved.
Solution:
MinecraftClient.ini
# Advanced settings
(terrainandmovements=true ) instead of terrainandmovements=false.

**Comment by ORelio** [comment]
There was a report for this in #432 but I was not able to reproduce. Would you mind giving the server IP so that I could try it out and see what's wrong when terrain and movement is disabled?

**Comment by TheSnoozer** [comment]
Closing as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/379
