### ISSUE TITLE
Console Clients keep Reconnecting

### ISSUE THREAD

**Issue by Superbicz** [ORelio/Minecraft-Console-Client#459]
Hi i am using the version you updated and i keep on getting these issue with console clients and it wont stop

https://gyazo.com/22abc7b0e7cfecee614a02dc9b8b6534

and this goes in cycle and wont join back to the server.

**Comment by ORelio** [comment]
Weird. Would you mind to:
 - Triple check you have [this development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - Try in a clean folder without previous files
 - Specify system version and framework version (Mono...) if applicable
 - Set `debugmessages=true` and provide full output (redact personal data and session tokens)
Thanks :slightly_smiling_face:

**Comment by Superbicz** [comment]
Done it and also is there way to make it so every 2 hours all of my cmds gets closed and the same onces get relaunched in a loop?

**Comment by Superbicz** [comment]
https://gyazo.com/f04f827139d36eba208ff4008d35d05f

**Comment by Superbicz** [comment]
Update 

https://gyazo.com/e31e2d108970480e238911adeb1ef0bc

**Comment by Superbicz** [comment]
https://gyazo.com/e5a6846dd7f1ccf3df4ffc80786422c5

https://gyazo.com/78ce0e4f077c3159aaca1d604e8a5de2
