### ISSUE TITLE
A way to write the session.db file in python?

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#460]
I have a script that validates an account is real before putting it into the config for the mine craft client, However, the way I currently do this means I get the authentication token stuff 2 times! However, If i were able to write the session cache from my python script, it would make me get "Too many password attempts" less, Because of the lower amount of requests for mojang, When I do the request, I get back a json object with all the attributes you would need to sign in if you saved it to session cache. However, I dont know how I would go about writing the file so the client could read it.

**Comment by Pokechu22** [comment]
Why do you have so many accounts, and why do you need to check your own authentication data to verify it?  If you've got a username and password and it's your account, you should be fairly certain it's correct...

In any case, SessionCache.db is written using C#'s [BinaryFormatter](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.formatters.binary.binaryformatter(v=vs.110).aspx) system.  It looks like that format is specific to the .NET framework and can't be easily modified, but there are [possible ways](https://stackoverflow.com/questions/14251765/is-there-a-way-to-read-c-sharp-serialized-objects-into-python) of using it from python.

There's also a newer SessionCache.ini, but I don't know the details of it.

**Comment by CarbonNeuron** [comment]
I run about 84 Accounts using this stuff. I wrote a bunch of bots and new commands. I need to verify it so I can build off a template. Thank you.

**Comment by CarbonNeuron** [comment]
Would there be anyway to modify the console client source to allow unserialized ini files? like parse it out to an INI file?

**Comment by Pokechu22** [comment]
84 accounts &times; ≈$25/account ≈ $2000, that's a fair bit o.o

Anyways, it does look like there already is INI support as of 18fd24d2d50c27e41472cf87462da9f1b3afb080, if you sign in once.  I think... haven't messed with it much.

**Comment by CarbonNeuron** [comment]
I'm dedicated. I will try this

**Comment by CarbonNeuron** [comment]
Awesome! I got it to work! Thank you for your fast responses

**Comment by ORelio** [comment]
I felt the DB format was indeed too restrictive so I replaced it recently with a simple INI format similar to all the other configuration files used by MCC.

FYI @Pokechu22 its format is loginlowercase=sessionid,username,uuid,clientid and you can totally add new lines in the file using an external tool :)

**Comment by CarbonNeuron** [comment]
Yeah, I was gonna ask what the format was. It's supposed to be lowercase? Does it matter?

**Comment by ORelio** [comment]
It matters because the internal dictionary/hashmap lookup is case-sensitive. However, MCC will automatically [convert the key to lowercase](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/SessionCache/SessionCache.cs#L222) when loading the INI file so you _should_ write the line with a lowercase login but it _won't_ break the thing if you do not.
