### ISSUE TITLE
How to make the bot press left or right mouse button?

### ISSUE THREAD

**Issue by SiVoo11** [ORelio/Minecraft-Console-Client#465]
How can i make script to my bot press left or right mouse button? I need to he press village to join serwer :C

**Comment by ORelio** [comment]
Currently you can't do that. Not implemented.

**Comment by SiVoo11** [comment]
Then when i join server nssv.pl how can i join "RealLife"?
Can i do it?
Please help me its very important for me ;(

**Comment by CarbonNeuron** [comment]
Try and do /server reallife or /reallife.... See if that server has any documentation for using minechat?

**Comment by SiVoo11** [comment]
this command in not allowed on hub ;/

**Comment by ORelio** [comment]
If there is a portal, try /move to go to the portal

**Comment by TheSnoozer** [comment]
Hi, since I think this would be tracked within #205 / #183 I'm closing this as 'duplicate'.
Feel free to subscribe to the other issue or subscribe to the other one for any updates. besides that feel free to open a new issue, with any other problem/issue you encounter.
