### ISSUE TITLE
Bad state: unknown compression method 0x22 (client keeps crashing randomly)

### ISSUE THREAD

**Issue by TeeJayy1006** [ORelio/Minecraft-Console-Client#471]
![download](https://user-images.githubusercontent.com/39682110/40591736-a3166826-61e4-11e8-9bdb-2644d83d25f9.png)

Having issues with this on cosmicpvp, i'm using the new .exe and am using 1.8.0

**Comment by ORelio** [comment]
Never managed to reproduce this, sorry.
