### ISSUE TITLE
triggering a .bat file

### ISSUE THREAD

**Issue by bamaman3** [ORelio/Minecraft-Console-Client#473]
is there any command which could be used to trigger a .bat file without having to click on it in the file itself?
The problem here is that i have over 30 alts afk'ing and when the server restarts, they all get kicked. Auto-relog tries to relog them after 1 minute, but since they all got kicked at the same time, they all try to rejoin at the same time, and hence minecraft locks the IP for logging in too fast. I was looking for a way to automatically trigger the .bat file when the server restarts, but if anyone knows of another way to fix this problem it would be greatly appreciated. Thanks.

**Comment by TheSnoozer** [comment]
see https://github.com/ORelio/Minecraft-Console-Client/issues/571

Closing as duplicate. Feel free to reopen if you still have any questions with this specific problem. otherwise please open a new issue.
