### ISSUE TITLE
Console client not connecting to server ip

### ISSUE THREAD

**Issue by AsianSimon** [ORelio/Minecraft-Console-Client#477]
Hi, I just found out my console client don't work as it displays failed to check session. So, I looked up on google and found out I need to download the new one you put out and I did. And this happened. I tried to connect to several servers and it displayed the same message.

Thank you.

![image](https://user-images.githubusercontent.com/39761082/40709699-ad214bf4-63ee-11e8-94da-e4003cfa918f.png)

**Comment by Icy-Zach** [comment]
in the "MinecraftClient.ini" file set the "mcversion=auto" to a version you know works on the server say "mcversion=1.12..=2" see how that goes

**Comment by AsianSimon** [comment]
Thanks, ill close this ty!
