### ISSUE TITLE
Not sure what's going on.

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#478]
Hi. I recently tried installing the console client onto a VPS I purchased. However, after I finished cloning the git repository and downloading the MinecraftClient exe (I did all this via command line, and it was my first time doing that so maybe I screwed up?) it returned this:
:/home/minecraft/Minecraft-Console-Client# mono MinecraftClient.exe
Can't find custom attr constructor image: /home/minecraft/Minecraft-Console-Client/MinecraftClient.exe mtoken: 0x0a000001 due to: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. assembly:System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:(null) signature:<none>

```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
root@vps187061:/home/minecraft/Minecraft-Console-Client#
```
Not sure what's going on. Maybe I installed it incorrectly. I didn't install via FTP (which i have done in the past, literally just transferring the files from my computer to the old server I used for hosting) but instead I installed via command line. My thought process is I screwed that up or there's a missing dependency (idk). For reference I'm running Ubuntu.

**Comment by TheSnoozer** [comment]
Hi,
sorry for the late response.

This indicates that mono tried to load a file/library/assembly, but could not find it.

I would refer to https://www.mono-project.com/download/stable/#download-lin
> The package mono-complete should be installed to install everything - this should cover most cases of "assembly not found" errors.

As a result try installing ``mono-complete`` via
```
sudo apt install mono-complete
```

**Comment by ORelio** [comment]
Seems like the mono version used to run MCC in this issue does not support at least .NET 4.0 (too old).

**Comment by TheSnoozer** [comment]
Since this seems to be an old issue and due to a broken mono installation I'd suggest to retry to install mono with the instructions provided on https://www.mono-project.com/download/stable/#download-lin. Also make sure to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) before you try again.

For now I would be assuming that the reinstallation of mono fixes your issue and thus I'm going ahead and close this.
