### ISSUE TITLE
Can not determine server version. (Forge)

### ISSUE THREAD

**Issue by seadog007** [ORelio/Minecraft-Console-Client#48]
Retrieving Server Info...
Server version : Forge BungeeCord 1.8 (protocol v0)
Failed to determineserver version.
![2014-10-10 8 21 55](https://cloud.githubusercontent.com/assets/5138409/4592181/61e153ba-5078-11e4-89a5-899a46179513.png)

**Comment by JamieSinn** [comment]
#59 should help

**Comment by ORelio** [comment]
You're right, Forge is not supported but this server was actually not running Forge.
