### ISSUE TITLE
Not letting me log in. 

### ISSUE THREAD

**Issue by Oshking25** [ORelio/Minecraft-Console-Client#480]
Connecting to Minecraft.net...
Using Minecraft version 1.8.9 (protocol v47)
Downloading 'en_GB.lang' from Mojang servers...
Done. File saved as 'lang\en_GB.lang'
Version is supported.
Logging in...
Checking Session...
Login failed :
Failed to check session.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by ORelio** [comment]
This issue seems related to not using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). Feel free to reopen if needed.
