### ISSUE TITLE
A way to move to a player?

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#484]
Is there a way to either force move to a block, Like I know that itll encounter half slabs, can I force it to move 0.5 blocks down? Or can I have it move to a player?

**Comment by Icy-Zach** [comment]
Try using these settings in the "MinecraftClient.ini" 

botowners=Your Player Name  # Use name list or myfile.txt with one name per line 
terrainandmovements=True          # Uses more ram, cpu, bandwidth



[RemoteControl]
enabled=true
autotpaccept=false (use this if you like or just type /tpa accept in the console client)
tpaccepteveryone=false

ps. Personally i havent use this setting but i  belive it should do what your trying to do with the move to a player

**Comment by CarbonNeuron** [comment]
You completely misinterpreted me. I'm trying to make my clients do the conga together

**Comment by ORelio** [comment]
Not possible unless implementing entities in MCC. Or maybe, as a workaround, try using `/move get` and sending the coordinates to the other bot using a PM, then retrieving coordinates on the other bot and moving to them.

**Comment by TheSnoozer** [comment]
The the issue with movements involved with slabs is tracked inside
https://github.com/ORelio/Minecraft-Console-Client/issues/300. If you still have a problem or a question with any other movement please open a new issue. I'm closing this as a duplicate (feel free to monitor the other issue).
