### ISSUE TITLE
Error when logging into server

### ISSUE THREAD

**Issue by Kingofweirdos01** [ORelio/Minecraft-Console-Client#485]
![sendhelp3](https://user-images.githubusercontent.com/32146052/40889153-ad4bfd2e-6716-11e8-9a5f-a6e325df3971.PNG)

**Comment by Kingofweirdos01** [comment]
this happened multiple times on multiple servers

**Comment by Pokechu22** [comment]
You're using an extremely outdated version.  Please update to the [latest development build].

**Comment by Kingofweirdos01** [comment]
Alright thanks lol

**Comment by Pokechu22** [comment]
Opps, didn't link to it; the link is https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by Kingofweirdos01** [comment]
I got a newer one just after I sent this issue in

**Comment by TheSnoozer** [comment]
Since the original problem seems to have been answered, I'm closing this as part of an issue cleanup.
Feel free to open a new issue, if you still have a problem.
