### ISSUE TITLE
Connection has been lost

### ISSUE THREAD

**Issue by Kingofweirdos01** [ORelio/Minecraft-Console-Client#486]
![connectionlost](https://user-images.githubusercontent.com/32146052/40890218-71a6c8f6-6727-11e8-8a7b-e2f2fd774c03.PNG)

**Comment by TheSnoozer** [comment]
Make sure that the kickmessages.txt contains the ``Connection has been lost`` entry.

E.g.
```
Attempting to attack an invalid entity
Bad login
Connection has been lost
Connection lost.
Disconnected
disconnect.spam
End Of Stream
Flying is not enabled on this server
Game over, man, it's game over!
Illegal characters in chat
Illegal position
Illegal stance
Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host.
Internal exception: java.io.IOException: Received string length longer than maximum allowed (105>100)
Internal Server Error
Internal Server Error:java.net.Minecraft
Kicked by an operator.
Outdated Client
Outdated server
Out of memory!
Read timed out
Server is full
Server is restarting
too many people
Too Many people
You have been idle for too long!
You have died. 
You seem to be logged in already.
```

Also ensure that AutoRelog is enabled in your ``MinecraftClient.ini`` e.g.
```
[AutoRelog]
enabled=true
delay=10
retries=-1 #-1 = unlimited
kickmessagesfile=kickmessages.txt
```
to ensure that the client is reconnecting.

**Comment by CollinVortex** [comment]
what do i do if my server doesnt allow auto relog

**Comment by Mhowser** [comment]
Your server as in the one you join or as one you own?

**Comment by CollinVortex** [comment]
One I join

**Comment by Mhowser** [comment]
Change the auto relog delay to a longer time, maybe 30 seconds.

**Comment by CollinVortex** [comment]
Will I still get banned.that way?

**Comment by Mhowser** [comment]
I don't know the rules of the server, I guess the best thing to do is to
not make it obvious that you are relogging automatically, by increasing the
delay.

**Comment by CollinVortex** [comment]
Alright, yeah auto relog isn't allowed. Maybe I'll take to some of the mods to get me whitelisted as it's a console client side issue

**Comment by CollinVortex** [comment]
well that didnt work it still loses connection.

anyone know the issue?

**Comment by ORelio** [comment]
You can enable AutoRelog but only use it when an error occurs in Minecraft Console Client, and not when the server restarts or you get kicked.

E.g. only put the following in `kickmessages.txt`
````
Connection has been lost.
````

**Comment by CollinVortex** [comment]
Yes, I have tried this. But it doesn't relog me still

**Comment by Mhowser** [comment]
Do you use your email address? or your username to sign in to your account?

**Comment by CollinVortex** [comment]
Email

**Comment by CollinVortex** [comment]
![image](https://user-images.githubusercontent.com/38381811/63227383-659f0700-c1ab-11e9-8ba1-389c2ee5f125.png)

**Comment by ORelio** [comment]
Weird. Is `enabled=true` set next to `[AutoRelog]` in config file?

**Comment by CollinVortex** [comment]
yes

**Comment by ORelio** [comment]
Ok, then retry with `debugmessages=true`?

**Comment by CollinVortex** [comment]
ok

**Comment by CollinVortex** [comment]
after 2 days of testing, its better. but i still lose connection i want to put a console client on my ras pi and never touch it

**Comment by ORelio** [comment]
As a workaround you may use the following script `autorelaunch.sh`
````bash
#!/bin/bash
while true; do
    mono MinecraftClient.exe
    echo "Restarting Minecraft Console Client..."
    sleep 5
done
````
And use `exitonfailure=true` in `MinecraftClient.ini`.

**Comment by CollinVortex** [comment]
im like really confused on how to do this ? can you help me out
