### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by Jodmc** [ORelio/Minecraft-Console-Client#487]
I have multiple accounts running off the same console client on my VPS to afk 24/7 on a server, however whenever the server restarts/crashes, whenever it turns back on one of the alts will always join and the other will fail to login because they have to wait 4 seconds between login attempts. I tried putting the message in the kickmessages.txt but no matter what I do it always refuses to AutoRelog. Anyone know how to fix this?

**Comment by ORelio** [comment]
Try using a different delay for each account?

**Comment by Winninq** [comment]
They're running off the same folder, off the same file, with the same config.
