### ISSUE TITLE
How to automate the commands to afk over night

### ISSUE THREAD

**Issue by Lobbiez** [ORelio/Minecraft-Console-Client#492]
I need this to AFK my stuff overnight but when it rejoins the game it cant reconnect to the skyblock realm because it needs to move and i found a fix by using /move east or up to rejoin but i need to be at my pc, is there a way to make this where i dont need to be at my pc and make it a script so that i can AFK over night while i sleep? (im a noob at programming)

**Comment by Lobbiez** [comment]
I have also looked at the task file and the task schedule file but i dont understand how they work sadly.

**Comment by TheSnoozer** [comment]
You can perform commands like joining a realm with the following:

> Try adding a `ScriptScheduler` or `AutoRespond`
> # via `ScriptScheduler`
> 
> MinecraftClient.ini
> 
> ```
> [ScriptScheduler]
> enabled=true
> tasksfile=tasks.ini
> ```
> 
> tasks.ini
> 
> ```
> ﻿[Task]
> triggerOnInterval=true
> triggerOnFirstLogin=true
> timeInterval=60
> script=joinyourserver.txt
> ```
> 
> joinyourserver.txt
> 
> ```
> send /server [REALM]
> ```
> 
> # via `AutoRespond`
> 
> MinecraftClient.ini
> 
> ```
> [AutoRespond]
> enabled=true
> matchesfile=matches.ini
> ```
> 
> matches.ini
> 
> ```
> [Match]
> match=--------------------[Hub]--------------------
> actionother=script joinyourserver
> # or simply actionother=send /server [REALM]
> ```

To afk 24/7 the client needs to run somewhere 24/7.
Possible ways to achieve that:
- get a VPS (Virtual Private Server) that usually runns 24/7 and where you run the client
- get a secondary computer like a raspberry pi where you can run the client on the computer 24/7


Closing as answered. Feel free to reopen if you have any further questions regarding this specific question.
