### ISSUE TITLE
UUID not properly storing due to GUID conversion.

### ISSUE THREAD

**Issue by Barnehhh** [ORelio/Minecraft-Console-Client#493]
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#L1185

https://i.imgur.com/kOkYfJp.png

UUID on top is what MCC by default currently gets for each online player, bottom is what that player's actual UUID is.

GUID's byte order for the first 3 fields differs from UUID causing it to scramble.

**Comment by TheSnoozer** [comment]
Sorry for the delay, you are right the conversion is broken.

This is due Java's UUID being represented as big-endian Guid, while C# tries to interpret it as little-endian.

For a fix I used [the following conversion](https://stackoverflow.com/a/10149822/7890667)

There are various different options on how the conversion could happen (e.g. https://gist.github.com/MrZoidberg/9bac07cf3f5aa5896f75 or something along the lines of https://stackoverflow.com/a/18023109/7890667)

Example on how this is being broken:
```
before: 
[MCC] [ExampleBot] UUID: b69849b7-196e-3648-b23f-7b38464cf5ec / username: d4gobert 

after (correct UUID):
[MCC] [ExampleBot] UUID: b74998b6-6e19-4836-b23f-7b38464cf5ec / username: d4gobert 
```

**Comment by ORelio** [comment]
@TheSnoozer Reviewed your coomit, seems all good! Feel free to add it to the main codebase using a pull request 😉

**Comment by ORelio** [comment]
Fix is now included in latest development build thanks to @TheSnoozer :wink:
Feel free to reopen if it still does not work as expected.
