### ISSUE TITLE
cannot connect to server ip

### ISSUE THREAD

**Issue by sugarnsalt** [ORelio/Minecraft-Console-Client#495]
after i attempted to conncect, i got the following error:
A connection attempt failed because the connected party did not properly respond after a period of time. or established connection failed because connected host has failed to respond 
what is going on?

**Comment by TheSnoozer** [comment]
can you connect with a normal client?

**Comment by ORelio** [comment]
Sometimes, server IP is not properly resolved e.g. when server use SRV records. Try playing with `resolvesrvrecords` in config.

**Comment by ORelio** [comment]
As a response has been given, I'll close the issue. Feel free to reopen if needed.
