### ISSUE TITLE
Blacklisted IP

### ISSUE THREAD

**Issue by Gew00nNiels** [ORelio/Minecraft-Console-Client#498]
I bought a VPS (Linux) to run alts with ConsoleClient but whenever I try to start it says IP Blacklisted

> Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors
Resolving play.pvpwars.net...
Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by Gew00nNiels** [comment]
Nobody uses this?

**Comment by Barnehhh** [comment]
Mojang is known to block proxies, this can include VPN providers, VPS providers, public proxies, etc. If you're typing your password correctly, unfortunately that is most likely the case. It is not an issue with MCC.

**Comment by ORelio** [comment]
As a response has been given, I'll close the issue. Feel free to reopen if needed.
