### ISSUE TITLE
Hypixel issue

### ISSUE THREAD

**Issue by PollefeysC** [ORelio/Minecraft-Console-Client#499]
The matches file doesn't work for partychat and guildchat messages on Hypixel. Could this be resolved, and if so, how

**Comment by ORelio** [comment]
This is related to chat format not being recognized. You'll need to tinker with the ChatFormat section of your configuration file. See also #579.

**Comment by TheSnoozer** [comment]
I'm closing this as part of an Issue Cleanup. if you still have problems to get this sorted with the referenced Ticket, feel free to open a new issue.
