### ISSUE TITLE
Help with Regular Expressions

### ISSUE THREAD

**Issue by AceTheGmodGeek** [ORelio/Minecraft-Console-Client#503]
Hi! I need help on making a regular expression for chat formats.

The chat format is [Zombie Realm] [FishyPanda -> me] send hi

I have `^\[[A-Za-z0-9_+ [A-Za-z0-9_]+\] (\[[A-Za-z0-9_]+ -> [A-Za-z0-9_]+\]) send (.+)$` but it doesn't seem to be doing anything when I put it in the config
https://gyazo.com/ed814f35ffa100abcef5f78f880e5f91

[ChatFormat]
# Do not forget to uncomment (remove '#') these settings if modifying them
builtins=false                      # MCC built-in support for common message formats
 public=^<([a-zA-Z0-9_]+)> (.+)$
# private=^\[[A-Za-z0-9_+ [A-Za-z0-9_]+\] (\[[A-Za-z0-9_]+ -> [A-Za-z0-9_]+\]) send (.+)$
# tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

I tried builtins to true and false, but it did nothing.

If you have time, can you help me with the public chat and tprequest too?

Public chat is [#1] [+Stussy] FishyPanda: message here
https://i.gyazo.com/cb645175ccb01f3fb7a82029ef1cd7aa.png
[#1] is the f top, sometimes it won't be there
[Stussy] is the faction name, sometimes won't be there
The + in Stussy could be nothing, -, +, *, or **.

and for TP requests, it shows as 
*AFK CodeRedemption has requested to teleport to you!
* To accept this request, type /tpaccept
* To deny this request, type /tpdeny
* This request will expire in 120 seconds
https://gyazo.com/debf3a046367fd6c2f5eaa697556a5dc

The * in AFK is a faction rank, again can be a -, +, *, or **, may or may not be there
AFK is the faction name, may or may not be there.
CodeRedemption is the player name, which would change.

Please let me know what I am doing wrong, so I can do it next time. Thanks!

**Comment by ORelio** [comment]
Try this one:
```
(?:\[[A-Za-z0-9 ]+\] )\[([A-Za-z0-9_]+) -> me\] (.+)
```
See here for more details of how it works: https://regex101.com/r/1j7Kdb/1 ; see also #579
