### ISSUE TITLE
Lost Connection

### ISSUE THREAD

**Issue by KinkiSamurai** [ORelio/Minecraft-Console-Client#504]
Happens Quite Often
![help](https://user-images.githubusercontent.com/40380419/41582103-542aaf52-73a9-11e8-9f79-d0fe94dfe4c6.png)

**Comment by ORelio** [comment]
Not sure why it happens, but you may use AutoRelog and add `Connection has been lost` as kick message. Feel free to reopen the issue if you still need help. See #581 for silent disconnections.
