### ISSUE TITLE
Unhandled Exception: System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by Winninq** [ORelio/Minecraft-Console-Client#505]
I get this error whenever I try to connect to a server ip. Any help?

![smh](https://user-images.githubusercontent.com/33239325/41616283-da62b644-73ba-11e8-9c5b-e09e7ea47287.png)

**Comment by ORelio** [comment]
Seems related to #527 , we still did not find how to reproduce and fix this, but closing this issue to keep only one of them open.
