### ISSUE TITLE
how to use auto-respond

### ISSUE THREAD

**Issue by adrielalfeus03** [ORelio/Minecraft-Console-Client#506]
the console client already detect the auto respond
and already type it
but it says uknown command '/respawn'. use '/help' for help.

[Match]
match=good
actionother=/respawn

**Comment by 0sdrawkcaB** [comment]
I think it should be this
[Match]
match=good
action=/respawn

**Comment by yangciou** [comment]
You have to do "actionother=send /respawn".
For all server commands, you have to write "send" before the command. For internal commands, such as "/reco", you do  not need.

**Comment by ORelio** [comment]
As a response has been given, I'll close the issue. Feel free to reopen if you still need help.
