### ISSUE TITLE
New Windows 10 console has IO messed up

### ISSUE THREAD

**Issue by FoxSGR** [ORelio/Minecraft-Console-Client#508]
My chat format gets very buggy when I'm not using windows's legacy console. (it used to work correctly before, but at some point it stopped)
When a color changes in the chat it deletes the previous character to the color identifier (before &c for example) and when I'm typing something and some message appears in the chat it gets really buggy (those  e   a a a e e   v a a a e e   d v a a a e e    v a a a e e things, which are sentences in which every other letter is replaced with a space).

 I attached my console properties because I messed with them quite a lot to try to figure out how to fix it but I failed. This is how it looks (also attaching a screenshot):

>00:32:30KabCraf]Junta-te a nós noDiscor para te manteres em contacto com a comunidade, obter ajuda, partilhar prints, fa
zer sugestões, denúncias, ouvir música e muito mais -discord.gg/WWjH73
00:32:30                                                                                 T u r v l d v a a a e e   e e
>devia aparecer pelo menos no chat quando alguem vota :P e   a a a e e   v a a a e e   d v a a a e e    v a a a e e
00:32:47[Admin] RaposSGDevia aparecer pelo menos no chat quando alguem vota :P e e   d v a a a e e   d v a a a e e   v
00:32:51[Lagdão]yh
00:33:00[Lagdão]E ganhar algum tipo de recompensa D
00:33:04[Dono] NoChancrival em votos só se for
00:33:05[Lagdão]Assi motiva eles a votarem
00:33:06[Dono] NoChancxD
00:33:10[Lagdão]Assim*
00:33:47[Dono] NoChance aqui nem tem motivaçao para votar
00:33:54[Dono] NoChance votaram 8 pessoas diferentes
00:33:57[Dono] NoChanc=0
00:33:59[Lagdão]pois
00:34:06[Lagdão]Eu voto quase todo dia
00:34:12[Lagdão]As vezes o voto vai em branco =(
00:34:28[Dono] NoChancem branco da?
00:34:31[Lagdão]dá
00:34:33[Lagdão]=(
00:34:41[Dono] NoChanchm
00:34:57[Dono] NoChancmetia-te com tag votador
00:35:01[Dono] NoChancmas ja tens tag
00:35:03[Lagdão]D                                                                                    s   u s r s e   u
>nc vou criar 1 issue no repo de alguepela 1ª vez no githubm n  c v u c i r 1 i s e n   e o d   l u m n    o   r a
00:35:40[Admin] RaposSGNc vou criar 1 issue no repo de alguem pela 1ª vez no github  d   l u m n r a     s u   o r p
>im excitedv u c i r 1 i s e n   e o d   l u m n  c v u c i r 1 i s e n   e o d   l u m n    o   r a     s u   o r p
00:35:41[Admin] RaposSGIm excited  o d   l u m n  c v u c i r 1 i s e n   e o d   l u m n    o   r a     s u   o r p
00:35:51[Dono] NoChancxDD parabens  u m n
>obrigado
00:36:00[Admin] RaposSGObrigado
00:36:11[Dono] NoChanctmb criei um no coiso da chestshop ontem`

![properties](https://user-images.githubusercontent.com/12991607/41825025-e4fef670-7811-11e8-838a-71d5e965ef20.PNG)

![console](https://user-images.githubusercontent.com/12991607/41825022-dba2232c-7811-11e8-8abe-b3c422c561fb.PNG)

**Comment by ORelio** [comment]
To anyone wanting to investigate this: this is likely an issue with [ConsoleIO](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ConsoleIO.cs)
(Dont' have time to work on this myself, unfortunately)
