### ISSUE TITLE
MCC Parrot / Repeat messages

### ISSUE THREAD

**Issue by 0sdrawkcaB** [ORelio/Minecraft-Console-Client#509]
Is there a way to make multiple accounts say exactly what i say no matter what it is?

**Comment by ORelio** [comment]
Yes using AutoRespond.
```
[Match]
regex=(.*)
action=send $1
ownersonly=true
``
However I'm not sure how this could be useful.

**Comment by TheSnoozer** [comment]
Since the question was answered, I'm closing this as part of an issue cleanup. Feel free to reopen this issue if you still have an issue in getting this specific problem sorted. Otherwise please open a new issue.
