### ISSUE TITLE
Username isn't working.

### ISSUE THREAD

**Issue by Chubbyduck1** [ORelio/Minecraft-Console-Client#513]
Hello, so I am trying to make it so when they say "Who is DucklingBot." it messages them saying "I am cool." but I can't get the player's username, like it doesn't tell me the username.
Please help
My Code: https://hastebin.com/ulecutuwip.ini

**Comment by repository** [comment]
You have to capture the username with the regex first, it isn't automagically defined.

Example:
`<(.{1,16})> .+`

The parentheses capture the first group, which can be used as `$1`

**Comment by ORelio** [comment]
You can't use `$u` in `actionother` since `other` means messages not sent by a player.

**Comment by ORelio** [comment]
Since a response was given, I'll close the issue. Feel free to reopen if you still need help.
