### ISSUE TITLE
tasks.ini > triggerOnLogin (and first) doesn't work after MCC reconnects to the server.

### ISSUE THREAD

**Issue by fuzzypixelz** [ORelio/Minecraft-Console-Client#514]
As the title suggests, my login script becomes useless once MCC reconnects to the server for any reason.
Which makes it quite unusable since I rely on it to Afk for long periods of time. This is a new issue and it only happened because I switched from MCC 1.9 to the latest builds as I began playing on an online-mode server and couldn't login without the recent changes.
If you're having the same issue as me of course you can use the AntiAFK bot over a short time interval, but that would mean a lot of messages for me and a mess in the chat each time the server notices I'm afk or no longer afk.

**Comment by biohazza** [comment]
The same problem is happening to me.

**Comment by ORelio** [comment]
Fixed as per #629
