### ISSUE TITLE
tasks.ini file not working

### ISSUE THREAD

**Issue by biohazza** [ORelio/Minecraft-Console-Client#515]
I have created a config file that when it has joined the server, it will connect to a subserver via a command, and send out some other commands. It will also trigger at a specific time. It seems like it should work, but doesn't. Here is the code

**Config**
`[Task]
triggerOnLogin=true
triggerOnTime=true
timeValue=20:34
script=prisonreconnect.txt
`

**Script**
`send /prison
send /p h
send /p middle`

**Comment by meciless** [comment]
i have the same problem i think program see the triggeronlogin/on time and start the script.
