### ISSUE TITLE
Being kicked off the server/Cannot send message

### ISSUE THREAD

**Issue by GrindToWin** [ORelio/Minecraft-Console-Client#517]
So I'm having this problem where my alt randomly either tps to spawn or dies(I never saw a loss of power so I think he tps idk) and in chat it says cannot send message for my anti afk. When ever a internet issue happends, internet cuts out for 0.5s alts get disconnected and it says reconnecting, and then it connects to the server and instantly connects says connection lost.

**Comment by GrindToWin** [comment]
yea it doesnt die cuz armor stays on it and the other 6/7 alts dont go to spawn at all

**Comment by ORelio** [comment]
Unfortunately I'm not sure what causes your issue. MCC never automatically sends commands unless you enable some command-sending features such as AntiAFK, AutoRespond, Scripts and so on, so it should not send commands such as /spawn.
