### ISSUE TITLE
System.OverflowException: VarInt too big 

### ISSUE THREAD

**Issue by FurowZ** [ORelio/Minecraft-Console-Client#518]
Hello, i tried to lauch 6 console clients each another account on it to afk on a server but when the 6th console lauches it makes me this problem 
![dsd](https://user-images.githubusercontent.com/41435585/42944094-041786f6-8b65-11e8-8b62-780a748a681d.PNG)
I really don't understand anything can you please help me this would be very appreciated.

**Comment by ORelio** [comment]
Seems related to #379 , we still did not find how to reproduce and fix this, but closing this issue to keep only one issue open.
