### ISSUE TITLE
Match Does not work for some special character ?

### ISSUE THREAD

**Issue by adrielalfeus03** [ORelio/Minecraft-Console-Client#523]
this character       »    
does not work for match command 
i dont know why 
any solution ?

**Comment by ORelio** [comment]
Maybe an encoding issue, the file is loaded by with default system encoding, typically ANSI on Windows and UTF-8 on Linux. The encoding of your match INI file must match the default encoding of your system.

**Comment by ORelio** [comment]
Since a response was given, I'll close the issue. Feel free to reopen if you still need help.
