### ISSUE TITLE
Roadmap for 1.13 support (v393 protocol)

### ISSUE THREAD

**Issue by Dids** [ORelio/Minecraft-Console-Client#525]
Any word on when (if ever) we could expect to see initial support for 1.13?

I primarly use an alt account as a chunk loader, so as long as the account is logged in and stays that way, that's all the functionality I'd need.

**Comment by ORelio** [comment]
Unfortunately I have less and less time available to upgrade MCC for each Minecraft version. Any contribution is welcome!

Thankos for your offer. Usually, upgrading MCC for a new Minecraft version involves the following step:
 - Figuring out what packets changed by performing a diff on http://wiki.vg/Protocol
 - Implementing the changes in [Protocol18.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs) while staying backward-compatible
 - Marking the MC version as supported in [ProtocolHandler.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs)

I can provide more in-depth explanations if someone is willing to contribute :wink:

**Comment by gandiber** [comment]
@ORelio I have 6 years of experience with C# and actually have been working on a private version of your program for my own needs. I replaced your old proxy library with a solution that seems to work better. I'd definitely be willing to help, but I need more information. Do you have a better way of contact?

Thanks!

**Comment by ORelio** [comment]
Thanks for your offer. I emailed some contact information to your Git email. Let me know if you didnt receive.

**Comment by TheSnoozer** [comment]
I have a local version prepared that almost is finished for 1.13.

However I ran currently into some weird issues when I have ``terrainandmovements=true``. Haven't had the time yet to fully troubleshoot it yet.

**Comment by iSolarNZ** [comment]
> I have a local version prepared that almost is finished for 1.13.
> 
> However I ran currently into some weird issues when I have `terrainandmovements=true`. Haven't had the time yet to fully troubleshoot it yet.

Awesome! Would it be possible for you to share it with me once you've fully completed the update?

**Comment by TheSnoozer** [comment]
I will create a merge request once I have finished it and then hopefully will end up in this repository (but that would be out of my control).

**Comment by iSolarNZ** [comment]
> I will create a merge request once I have finished it and then hopefully will end up in this repository (but that would be out of my control).

Alright, cool. Thank you 👍

**Comment by Pokechu22** [comment]
> However I ran currently into some weird issues when I have `terrainandmovements=true`. Haven't had the time yet to fully troubleshoot it yet.

Terrain and movements is going to be the hard part; block state It's have been completely changed (no more metadata so no more restriction of _exactly_ 16 states; things jump about).  Check wiki.vg for more info, particularly the (new) data generators article.  The packet also had a few changes to it's structure.  At least for the moment I'd recommend disabling terrain and movements and just implementing chat.

**Comment by BlinkSun** [comment]
How can I get 1.13.1 work for chat only ? Is there a quick way ?

**Comment by TheSnoozer** [comment]
I created a MR with my changes, I would address all code review concerns/comments, but won't have time for now to take care of the potential broken `terrainandmovements=true`. At least it's not crashing the client when enabled.

**Comment by iSolarNZ** [comment]
Some of us don't really need terrainandmovements, so hopefully they accept the MR and make like a 1.13.1 pre release or something of MCC

**Comment by iSolarNZ** [comment]
Any updates on the Merge Request @ORelio?

**Comment by ORelio** [comment]
Sorry about the delay, I just reviewed and merged your contribution. Thanks :+1:

**Comment by iSolarNZ** [comment]
Thank you!

**Comment by BamaJoe411** [comment]
I just want to say thank you to every one who helped get this client updated to 1.13.1! I have been watching this issue like a hound waiting for it to be updated and it finally is! :D THANK YOU SO MUCH!

**Comment by BamaJoe411** [comment]
any news about protocol v404?

**Comment by iSolarNZ** [comment]
Yeah, I'd love to see this updated to 1.13.2 as well :)

**Comment by Mhowser** [comment]
What we really need is to get TerrainMovements up and running again for
current and future versions, should be first priority.

**Comment by BamaJoe411** [comment]
I would like to help but I don't know how to compile the exe. Would someone be willing to show me how to load this into Visual Studio Code? (also I'm on Ubuntu if that makes a difference. I don't know if you can compile exe on Linux or not.)

**Comment by ORelio** [comment]
You should be able to open it in Visual Studio by clicking on the `.sln` file, after cloning the repository or downloading as Zip. However some C# knowledge will also be needed, as well as Minecraft protocol knowledge (see https://wiki.vg/Main_Page).

**Comment by TheSnoozer** [comment]
Since the general support for 1.13 is integrated I close this in favor of https://github.com/ORelio/Minecraft-Console-Client/issues/576 that deals with the missing 'terrain and movements'
