### ISSUE TITLE
CS script doesnt work

### ISSUE THREAD

**Issue by zCri** [ORelio/Minecraft-Console-Client#526]
`//MCCScript 1.0

MCC.SendText("/joinqueue Space");
Console.WriteLine("Joined queue");
Thread.Sleep(15000);
Console.WriteLine("Should have joined the server");
MCC.SendText("/tpa zCri");
Console.WriteLine("Tpa sended");
Thread.Sleep(10000);
farmIron();

void farmIron() {
    Thread.Sleep(20000);
    Console.WriteLine("Sending farm command");
    MCC.SendText("/sell all");
    farmIron();
}` yes ik this is not a place to get support for a code but i need help.
 [MCC] [Script] System.InvalidOperationException: Needed the } symbol is the error roughly translated from italian :D ty for help

**Comment by repository** [comment]
I'm no C# expert, but, I believe using your functions after they're defined would help.

**Comment by ORelio** [comment]
I'd say something like this:

```C#
//MCCScript 1.0

MCC.SendText("/joinqueue Space");
Console.WriteLine("Joined queue");
Thread.Sleep(15000);
Console.WriteLine("Should have joined the server");
MCC.SendText("/tpa zCri");
Console.WriteLine("Tpa sended");

while (true) {
    Thread.Sleep(20000);
    Console.WriteLine("Sending farm command");
    MCC.SendText("/sell all");
    farmIron();
}
```
Haven't tested it, though.

**Comment by ORelio** [comment]
As a response has been given, I'll close the issue. Feel free to reopen if needed.
