### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by Nikovmir** [ORelio/Minecraft-Console-Client#527]
So the server i play for some time now had to rollback a couple hours last night, i have 2 acc and been using CC for some time no problem, but after the rollback only 1 acc works with CC the other i get this error....and CC crashes after, how can i fix this?

Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 - By ORelio & Contributors
Resolving play.minesaga.org...
Found server xp7hujxkmfkvfzeub4bgxsfs.ddns.net:25565 for domain play.minesaga.org
Cached session is invalid or expired.
Connecting to Minecraft.net...
Retrieving Server Info...
Server version : BungeeCord 1.8.x-1.12.x (protocol v340).
Version is supported.
Logging in...
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server.
[SPECIAL OFFER] BUY ONE GET ONE FREE MONTHLY CRATE, CRATE BUNDLE, MEGA CHARGE, TREASURE CHEST AND DRAGON EGG!
[MCC] [Script] send /joinqueue space
You are now queuing for Space.

>
Unhandled Exception: System.OverflowException: VarInt too big
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextVarInt(List`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ORelio** [comment]
Unfortunately the stack trace does not give enough context. Is there a deterministic way to reproduce the issue or was it random?

**Comment by TheSnoozer** [comment]
Seems to be related with https://github.com/ORelio/Minecraft-Console-Client/issues/505, https://github.com/ORelio/Minecraft-Console-Client/issues/379, https://github.com/ORelio/Minecraft-Console-Client/issues/518

However connecting to the server doesn't yield an exception for me...

**Comment by ORelio** [comment]
The problem with this issue is that I wasn't able to reproduce it yet, and the error message is not sufficient to make a fix without reproducing the issue.

**Comment by CantGoBack** [comment]
I have this exact same issue. but it only happens in one server of the server I play on. I can go to SMP, factions, creative, and skyblock-e with zero issues, but as soon as I try to go to skyblock-g, the errors occur. I have tried being disguised, undisguised, armor equiped, armor unequiped, holding something, not holding something...

**Comment by TheSnoozer** [comment]
Could you set ``debugmessages=true`` inside ``MinecraftClient.ini``?

Also what is the server ip?
What is the server version message that will be shown by the client after connecting (interested in the ``Server version : BungeeCord 1.8.x-1.12.x (protocol v340).``?
What is the configuration of ``mcversion``  inside ``MinecraftClient.ini``?
What is the configuration of ``brandinfo``  inside ``MinecraftClient.ini``?

**Comment by CantGoBack** [comment]
what would you like me to copy/paste from the debug message?
I'm on play.skycade.net   skyblock-g is the only gamemode i get this error on.
the server version was set to 1.12.2, then I tried auto but our server now support 1.13 and your client says "Server version : BungeeCord 1.8.x-1.13.x (protocol v393)."
brand info is set to MCC. i don't know what this means so I left it the same as when my friend shared it with me.

**Comment by CantGoBack** [comment]
I have noticed that I get the error message if I'm standing directly next to a wall. If I'm standing in the middle of a blank 4 block square, I don't get the error.
