### ISSUE TITLE
Minecraft Console Client: /move

### ISSUE THREAD

**Issue by agentcru** [ORelio/Minecraft-Console-Client#529]
When I use the /move command I get the message "Please enable terrainandmovements in config to use this command." although I have activated this! Please tell me how to fix it

**Comment by Mhowser** [comment]
Can you show us your config file? *Be sure to remove your account details
first before sharing!*

**Comment by agentcru** [comment]
i have convertet it to a txt should work so too
only rename to .cs
[Settings.txt](https://github.com/ORelio/Minecraft-Console-Client/files/2235508/Settings.txt)

**Comment by agentcru** [comment]
Ok i have fixed it
