### ISSUE TITLE
Matches.ini

### ISSUE THREAD

**Issue by BenHall-1** [ORelio/Minecraft-Console-Client#533]
Hey there,
I have AutoRespond enabled in my config but it's not working at all.

Any idea? 
[AutoRespond]
enabled=true
matchesfile=matches.ini

[Match]
match=Test
action=send hi
actionprivate=send /msg Ben________ Hello!
actionother=log detected "test" message

**Comment by ORelio** [comment]
Check your chat format settings, I guess your server uses a custom chat format and MCC cannot parse chat messages from your server.

**Comment by ORelio** [comment]
As a response has been given, I'll close the issue. Feel free to reopen if needed.
