### ISSUE TITLE
How Do Connect A Script To This Console Client?

### ISSUE THREAD

**Issue by TarazG** [ORelio/Minecraft-Console-Client#534]
I have this script to AutoTip on the Minecraft Hypixel server. I could do it on the old version of this client but I stopped using it for a bit and then I came back and it didn't work anymore. So I went back on and downloaded the new version but it is very different. The old one had a script folder and I just put the script in. But now it is different. Could anyone help me?

Thank you!

**Comment by TarazG** [comment]
ANSWER NOW PLZ? What takes so long? I have a client waiting! Please help me A.S.A.P!

**Comment by ORelio** [comment]
Given the constant flow of new issues, I just dont have enough time to reply to everyone... the script mechanism hasnt changed for many years, the only change being the addition of C# script support. By default, MCC checks for script in its working directory and in a `Scripts` subfolded, that you can create if it does not exist.

**Comment by ORelio** [comment]
As a response has been given, I'll close the issue. Feel free to reopen, but remember the MCC community is unfortunately not a paid hotline.
