### ISSUE TITLE
Implement aliases in login prompt

### ISSUE THREAD

**Issue by kikawet** [ORelio/Minecraft-Console-Client#535]
When you run the .exe without an entry in login in the .ini

![imagen](https://user-images.githubusercontent.com/28111220/43541654-3a9f8bb8-95cb-11e8-8137-5e4faf505eb6.png)

The console asks you for a login, even when you input an alias from the accounts.txt it asks you for a password
![imagen](https://user-images.githubusercontent.com/28111220/43542193-a9a6c5a2-95cc-11e8-91c9-4ee97b7d642f.png)

If I put the same allias in the .ini works fine, even if the password entry is empty, also that alias works fine with the `/connect` comand

PD: In the top of the windows shows the ip instead of the alias of the server, I don't plan to make an issue for that

**Comment by ORelio** [comment]
Indeed, aliases are used in internal `/reco` and `/connect` commands for instance, but not in login prompt.

**Comment by ORelio** [comment]
Should be implemented now.
