### ISSUE TITLE
Batch File Scripting?

### ISSUE THREAD

**Issue by Lvnvceo** [ORelio/Minecraft-Console-Client#539]
I am more familiar batch file scripting. Is there any way for me to run the program from batch file but also automatically login from a txt that the batch file can read off of? In summary I am trying to login from a batch file. START /MIN MinecraftClient.exe usernameoremail password serverip does not work.

**Comment by TheSnoozer** [comment]
The following works fine:
```
start /min MinecraftClient.exe USERNAME PASSWORD SERVER-IP
timeout 5

start /min MinecraftClient.exe USERNAME PASSWORD SERVER-IP
timeout 5

start /min MinecraftClient.exe USERNAME PASSWORD SERVER-IP
timeout 5
```

converting it to a csv should work fine too.

Example:
Sample CSV (accounts.csv)
```
USERNAME,PASSWORD,SERVER-IP
USERNAME,PASSWORD,SERVER-IP
```
for /f "tokens=1-3 delims=," %%a in ("accounts.csv") do (
      :: %%a == USERNAME
      :: %%b == PASSWORD
      :: %%c == SERVER-IP
      start /min MinecraftClient.exe %%a %%b %%c
      timeout 5
)

just google "how to read a csv with batch".

If it "doesn't" work, post your error message or explain what is happening.

**Comment by ORelio** [comment]
One thing to take into account is that login servers will implement a cooldown so too many logins in a short amount of time will be rejected. Make use of the session cache - which is by default enabled and saved to disk - to avoid the cooldown.

**Comment by Lvnvceo** [comment]
How can I develop a way to make a batch file run multiple instances of this application? When I try to stack the command it only loads one. I am trying to make a bot spammer for cracked servers.

**Comment by ORelio** [comment]
@TheSnoozer already answered that question: `start /min` will do.

**Comment by ORelio** [comment]
As a response has been given, I'll close the issue. Feel free to reopen if needed.
