### ISSUE TITLE
Chatbot Error

### ISSUE THREAD

**Issue by xSidewinderx** [ORelio/Minecraft-Console-Client#541]
[MCC] [Script] System.IO.InvalidDataException: The provided script does not have a valid MCCScript header 
code
`using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace MinecraftClient.ChatBots
{
    /// <summary>
    /// Example of message receiving.
    /// </summary>

    class Join : ChatBot
    {
        private HashSet<string> SeenPlayers = new HashSet<string>();
        public override void GetText(string text)
        {
            string message = "";
            string username = "";
            text = GetVerbatim(text);
            File.WriteAllLines("seenplayers.txt", SeenPlayers.ToArray());
            if (message.StartsWith("Join>"))
            {
                LogToConsole("test");
                SeenPlayers.Add(username);
                File.WriteAllLines("seenplayers.txt", SeenPlayers.ToArray());
                SendText("Welcome to the server for the first time " + username);
            }
        }
    }
}`

**Comment by TheSnoozer** [comment]
In your first line you need to have ``//MCCScript 1.0``
Do not put anything else in that line.
That check is strict for a reason (mainly to allow to handle future versions differently).

Full-Example:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.cs
