### ISSUE TITLE
Matches.ini Support/Questions

### ISSUE THREAD

**Issue by xSidewinderx** [ORelio/Minecraft-Console-Client#544]
I have my matches file setup as followed.
`[Match]
match=hi
action=send hi, $u!
actionprivate=send /tell $u Hello, $u

[Match]
match=gohome
actionprivate=send /home
ownersonly=true

[Match]
match=lotto
action=script lotto.txt
ownersonly=true

[welcome]
match=to Skyblock 8.0
action=send Welcome, $u!
ownersonly=false
actionother=log $u joined the game.`

Also on the match for welcome, it detects the user joined, but needs send the welcome in chat, and $u does not seem to work for actionother.
Noted in sample match,
# You can use $u for username of the player triggering the match
https://gyazo.com/2abfe1073c1cb5c3be9215d73ae89fe2
Also having trouble with with script running using match.
running the script with /script name works just fine but trying through matches.ini yelds no results

**Comment by ORelio** [comment]
Dont rename a `[Match]` section to something else such as `[welcome]` or it will be ignored.
Also, if the server uses an unusual chat format, you'll need to configure that in `MinecraftClient.ini`

**Comment by xSidewinderx** [comment]
It still showed it being loaded with no issues, but its changed now. Same results
also heres the chat for the welcome message being detected.
https://gyazo.com/d9995c1555dc256638ea9277cd60f8c1
The normal chat follows this format

island lvl > * OptionalPrefixes > Username > OptionalTag : Text
https://gyazo.com/e613ac0dd32e3fb78277a585e82b2ace

**Comment by ORelio** [comment]
Your Welcome message is *not* a chat message, as such MCC will not detect any username:
````ini
[welcome]                               # Wrong section name
match=to Skyblock 8.0
action=send Welcome, $u!                # Happens if someone says "to Skyblock 8.0" in chat
ownersonly=false                        # This line is not required if set to false
actionother=log $u joined the game.     # $u is set for chat messages only (obviously)
````
I'd suggest using a regex for retrieving a username from this message:
````ini
[Match]
regex=^Welcome ([A-Za-z0-9_]+) to Skyblock 8.0$
actionother=log $1 joined the game.
````

**Comment by ORelio** [comment]
As a response has been given, I'll close the issue. Feel free to reopen if needed.
