### ISSUE TITLE
Stuck at Logging in 

### ISSUE THREAD

**Issue by QQKachoo2085** [ORelio/Minecraft-Console-Client#545]
I am trying to use the console client on a Mac to log into the Cosmic Prisons serve.  I have added my username and password and it starts to Log in but the terminal freezes.  I don't know what would be the next step. I am attaching an image for you to see where it is stopped.

<img width="357" alt="screen shot 2018-08-12 at 4 29 59 am" src="https://user-images.githubusercontent.com/42314383/44000588-6a443e16-9de8-11e8-8ffd-a7c7e0a1582c.png">

**Comment by ORelio** [comment]
This issue seems related to not using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). Closing the thread, but feel free to reopen if needed.
