### ISSUE TITLE
CC Login Malfunction (Mac)

### ISSUE THREAD

**Issue by Ireallywantcc** [ORelio/Minecraft-Console-Client#547]
Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
Login : ********************
Password : <******>                                                                                                                                                                  Connecting to Minecraft.net...
Server IP : ********.***
Retrieving Server Info...
Server version : BungeeCord 1.8.x-1.13.x (protocol v393).
Cannot connect to the server : This version is not supported !
Server version : 1.8.8
Restarting Minecraft Console Client...
Cached session is still valid for ***********.   
Using Minecraft version 1.8.8 (protocol v47)
Version is supported.
Logging in...
Checking Session...
Login failed :
Failed to check session.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

Why can't I go into my session? I'm not good at CC. Btw this is on a mac.

**Comment by Pokechu22** [comment]
You are running an outdated version.  Please download the latest build from [appveyor](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts); it fixes this issue (#451).

**Comment by Ireallywantcc** [comment]
Oh ok.
