### ISSUE TITLE
how to join a specific server within a server?

### ISSUE THREAD

**Issue by Kalkushy** [ORelio/Minecraft-Console-Client#550]
hi, i don't really understand a lot of things in here so sorry if this is a dumb question

so theres a skyblock server which i want my alt to AFK in, but its a realm within a server, so i need to type in the chat /server [name] to join it
but the server restarts twice a day, and i want my alt all the time in it, is there a way which i can make it reconnect automaticlly and type the command automaticlly? thanks :)

**Comment by ORelio** [comment]
Try [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/blob/758bfad501bad8fd61a7441c8e29967869d2e3ef/MinecraftClient/config/README.txt#L192). See [sample-tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini).

**Comment by ORelio** [comment]
As a response has been given, I'll close this thread. Feel free to reopen if you still need help.
