### ISSUE TITLE
Remote Control Commands

### ISSUE THREAD

**Issue by ogbuddy** [ORelio/Minecraft-Console-Client#551]
I'm having issues with my bots executing commands that I send them through the In-game message system, I found this part in the readme.txt "However, for unusual chat formats, so you may need to tinker with the ChatFormat section of the config file." The server I want to use message commands on use an odd private messaging format but I am unable to locate a "ChatFormat" section in the MinecraftClient.ini file. Which config file is this referring to?

**Comment by ORelio** [comment]
This section is located in MinecraftClient.ini, but if you are using an old version of the file, you may need to delete it so that MCC regenerates a new one with the section included.
