### ISSUE TITLE
Crash on Linux?

### ISSUE THREAD

**Issue by Slimerblue22** [ORelio/Minecraft-Console-Client#554]
Ok so I try to run it on Linux mint 19 and it just closes without any error (that I can find) after password you can put put random stuff or real user info and it crashes/closes. So erm, what do I do?

**Comment by TheSnoozer** [comment]
What version of mono do you have? (run ``mono --version`` to find out)
have you set ``debugmessages=true`` inside ``MinecraftClient.ini``?

**Comment by Slimerblue22** [comment]
Odd, it works fine now. Hmm well closed I guess?
