### ISSUE TITLE
Really need some help. With CC on mac.

### ISSUE THREAD

**Issue by Ireallywantcc** [ORelio/Minecraft-Console-Client#556]
Okay, so my school has started. But I want to afk during that. My server that I play on. Has a reboot every 12 PM EST. Which is through my school hours. So I cant reach my mac at home while im at school. Whenever the server reboots. It sends me to the hub. But there is a command to get back to the server. I just want to know if I can spam it every 2 minutes or so. So I don't have to do it manually. And I don't have to worry about my account being rebooted to the hub. What i'm trying to say is. How do I make a script to have 2 alts online on one terminal. As well with both alts to spam the command to go back to my afking area. (Spam every 2 minutes on both alts. So it doesn't send me to the hub.)

Please help.
Thank you.

**Comment by TheSnoozer** [comment]
What you can use is a ScriptScheduler

 ``MinecraftClient.ini``:
```
[ScriptScheduler]
enabled=true
tasksfile=tasks.ini
```

``tasks.ini``:
```
﻿[Task]
triggerOnInterval=true
triggerOnFirstLogin=true
timeInterval=60
script=joinyourserver.txt
```

```joinyourserver.txt```
```
send /server [REALM]
```

**Comment by Ireallywantcc** [comment]
Yeah, but you see I have done the first two. It's just do I put my first alt, then wait 30 then put my second one; then use the command? Im just confused. Btw I play on minesaga.org it has realms. So yeah.
I just don't understand scripts.
