### ISSUE TITLE
Console client keeps disconnecting me

### ISSUE THREAD

**Issue by Ophornal** [ORelio/Minecraft-Console-Client#558]
Ive been using this client for a while but somehow my alts disconnect by themselves. I have some normal minecraft clients open at all times too and they dont timeout? Is there anyone that can help me with this?

**Comment by Ophornal** [comment]
(some more info)
It does it randomly after being online for a bit. its not an afk kick thing because i have afk kick exempt

**Comment by TheMonDon** [comment]
I am also having this issue.

**Comment by ORelio** [comment]
Not sure why it happens. I'm closing this thread, leaving #581 open with details of a possible workaround.
