### ISSUE TITLE
tasks.ini timeValue doesnt read time ?

### ISSUE THREAD

**Issue by Deathnight7976** [ORelio/Minecraft-Console-Client#559]
Tasks.ini:
[Task]
triggerOnTime=true
timeValue=00:00:00 (previously tried 00:00)
script=leaving.txt

[Task]
triggerOnTime=true
timeValue=00:30:00  (previously tried 00:30)
script=joining.txt

Debug output:
17:24:20 [MCC] [ScriptScheduler] This task will never trigger:
 triggeronfirstlogin = False
 triggeronlogin = False
 triggerontime = True
 triggeroninterval = False
 timevalue =
 timeinterval = 0
 script = leaving.txt
17:24:20 [MCC] [ScriptScheduler] This task will never trigger:
 triggeronfirstlogin = False
 triggeronlogin = False
 triggerontime = True
 triggeroninterval = False
 timevalue =
 timeinterval = 0
 script = joining.txt

**Comment by TheSnoozer** [comment]
see https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini

```
# Time is HH:mm format, several different hours can be provided

[Task]
triggerOnFirstLogin=false
triggerOnLogin=false
triggerOnTime=true
triggerOnInterval=false
timeValue=19:30
timeValue=08:10
timeInterval=0
script=event.txt
```

**Comment by Deathnight7976** [comment]
What about it:
>(previously tried 00:30)  
>(previously tried 00:00)
only reason i attempted it with HH:mm:ss was because that's how the client sees timestamps when you enable them.

**Comment by ORelio** [comment]
The expected format is [HH:mm](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/ScriptScheduler.cs#L78). Make sure no additional characters such as whitespaces are present.
