### ISSUE TITLE
Implement multiple ChatLog files

### ISSUE THREAD

**Issue by xSidewinderx** [ORelio/Minecraft-Console-Client#560]
I was told there was a way to have the chatlog be split into multiple files to avoid one huge one, but I can seem to find the setting?

**Comment by ORelio** [comment]
Currently, the ChatLog bot only handles one log file.

**Comment by xSidewinderx** [comment]
Would this be something you could look into adding?

**Comment by TheSnoozer** [comment]
I can remember that there was once an issue that asked for the ability to have timestamps in the log and have them rotating (e.g. a new log every hour or whatever is configured).

**Comment by ORelio** [comment]
Should be implemented now as per #1426.
