### ISSUE TITLE
Question: Can we send commands trough an exe?

### ISSUE THREAD

**Issue by Ophornal** [ORelio/Minecraft-Console-Client#561]
I was wondering if we could run command with a batch file
Like you can start your accounts with like start /min MinecraftClient.exe Mail Passw Server
But is there a way for it to automatically do /server survival and /home?
Thanks!

**Comment by TheSnoozer** [comment]
yes.

> Try adding a `ScriptScheduler` or `AutoRespond`
> # via `ScriptScheduler`
> 
> MinecraftClient.ini
> 
> ```
> [ScriptScheduler]
> enabled=true
> tasksfile=tasks.ini
> ```
> 
> tasks.ini
> 
> ```
> ﻿[Task]
> triggerOnInterval=true
> triggerOnFirstLogin=true
> timeInterval=60
> script=joinyourserver.txt
> ```
> 
> joinyourserver.txt
> 
> ```
> send /server [REALM]
> ```
> 
> # via `AutoRespond`
> 
> MinecraftClient.ini
> 
> ```
> [AutoRespond]
> enabled=true
> matchesfile=matches.ini
> ```
> 
> matches.ini
> 
> ```
> [Match]
> match=--------------------[Hub]--------------------
> actionother=script joinyourserver
> # or simply actionother=send /server [REALM]
> ```

**Comment by Ophornal** [comment]
Thank you so much!

**Comment by ORelio** [comment]
As the issue is resolved I'm closing the thread. Feel free to reopen if needed.
