### ISSUE TITLE
Question: Using different Auth servers for alts

### ISSUE THREAD

**Issue by Pr0Pancakes** [ORelio/Minecraft-Console-Client#565]
Is it possible to perhaps use Alt Dispensers auth servers so that the console client could still be used with those alts.

EDIT: i've looked around and noticed the MC leaks API that alt dispenser also uses. Would I be able to write a script for the console client to use different auth servers or is that more internal.

**Comment by ORelio** [comment]
Although that should be possible as they offer an API, I'm not sure there is a legitimate use case for this. Since you don't own the account, you can't really take part of a community and chat with MCC, so most of the time these accounts are used for spamming, circumventing bans, etc.

**Comment by Pr0Pancakes** [comment]
Hi ORelio and you are correct. Most of the time when others are using alts it's most likely to circumvent a ban or a mute. However my use for these alts (that don't take up 1gb per memory per client) would be to farm my grinders on a skyblock server. I currently have too many so when they don't have a player standing by them they aren't doing anything at all! I have checked with the server I am on and they currently have no limit on alts.

I started looking at the API for the authentication it looks to be C#  I was definitely going to attempt myself however I have no idea what a Server hash is "-1ja8s98dhj92h9aasd8",

My intentions are pure with the API and the console client.


PS: Not sure why I was thumbsdowned by @Pokechu22  @ TheSnoozer but get a life or fight me bitches, i'm just trying to get some help and the fact you have time to go through ANOTHER users github and thumbs down comments and issues? 
What because you don't think it's an issue or too easy of an issue?
Thumbs down to you too @Pokechu22  & @TheSnoozer your lifes are probably going nowhere thats why you had to come and thumbsdown my thread. Might as well waste some more time and thumbs down this one too.

**Comment by Pr0Pancakes** [comment]
nvm actually this client it trash i see why nobody uses it.

thanks for all the *******HELP****** that would of probably took two seconds to answer but i've found someone else that will help with the problem and not beat around the bush.

**Comment by Pokechu22** [comment]
The thumbsdown was because you are requesting something that is in violation of the MC EULA (piracy, more or less), and as such is an invalid suggestion.  I watch this repo since I've contributed to it frequently in the past although I'm not as active of a contributor nowadays; I'm emailed of all new issues as such.
