### ISSUE TITLE
Blacklisted ip?

### ISSUE THREAD

**Issue by Ophornal** [ORelio/Minecraft-Console-Client#567]
Sorry i messed up my other issue.
Im getting this when loading an account? is it something im doing wrong?
![image](https://user-images.githubusercontent.com/43205788/46583891-6cbe9a00-ca5d-11e8-93bc-b511973b11e8.png)

**Comment by ORelio** [comment]
Make sure `sessioncache` is set to `disk` in config to avoid making too many logins. There is a rate limit.

Feel free to reopen the issue if you still need help.
