### ISSUE TITLE
(Help) Consle client on raspberry pi

### ISSUE THREAD

**Issue by SoundWreaking** [ORelio/Minecraft-Console-Client#569]
I got a raspberry pi and wanted to afk with it i got everything setup.
My problem is that the bot is going to a hub every now and then like 1min and my scripts are not working im very confused because everything works on my windows 7 computer. I dont know if its the mono version i got 4.6.2 i read that 4.0-4.2 is working but idk how to downgrade. And im not sure if the mono thingi is the only problem.

**Comment by TheSnoozer** [comment]
there should be no difference in running the client on a windows VS on a linux / raspberry computer.
Double check with (WinSCP) if you have transferred all files to the right places (in particular the configuration files).

**Comment by SoundWreaking** [comment]
Ye i did its not doing the .ini tasks and stuff and its somehow not showing the chat right i tested with my main and msged my alt and it showed up like 1min after i send it

**Comment by ORelio** [comment]
Make sure your file names have the same case because `File.txt` is not `file.txt` on Linux.

**Comment by SoundWreaking** [comment]
Its still "lagging" like i connect i get a message from the server and then i type /server and its saying connecting to server and after that i wait 1min and then i see chat. I tried to msg but its showing like 30sec after i sent and then its just disconnecting

**Comment by SoundWreaking** [comment]
idk if its something with the mono version i use

**Comment by ORelio** [comment]
This may be linked to Mono because network hangs/silent disconnects happens frequently with Mono while everything works well using .NET framework on Windows. As a workaround, try adding a useless AntiAFK command such as `/ping` every minute, it should help detecting when connection is lost. Then you can use AutoRelog to automatically relog.

**Comment by lansraad** [comment]
Iv had loads of problems with the raspberry pi, im using an old windows PC instead..
When I run mono MinecraftClient.exe it runs but when it connects to the server it freezes up and gives a crazy long error

**Comment by SoundWreaking** [comment]
> This may be linked to Mono because network hangs/silent disconnects happens frequently with Mono while everything works well using .NET framework on Windows. As a workaround, try adding a useless AntiAFK command such as `/ping` every minute, it should help detecting when connection is lost. Then you can use AutoRelog to automatically relog.

Okay ill try it later today thanks for your help btw

**Comment by SoundWreaking** [comment]
Okay so i tried stuff and if i do mono MinecraftClient.exe then its just freezing at some point i cant type anything or its stuck at the connecting to minecraft.net part
I added the afk thingi and stuff

**Comment by SoundWreaking** [comment]
I tried it. And its keep freezing like when im typing email/password or its staying on "connecting to Minecraft.net"

**Comment by Sharpen-Up** [comment]
Had similar issues when I first tried. But found it was an issue with the pre installed mono. After searching for a bit on the net I figured out how to remove all of mono and npm from my pi. Then followed tutorial to install latest version. As trying to update it/download latest mono my pi still wanted to use the original mono that comes pre set up. If you have successfully uninstalled mono and npm you shouldn't get a version response when requesting through terminal. If your still trying to sort this let me know and I can see if I can find what I did to fix.

**Comment by SoundWreaking** [comment]
If you got discord add me plz Soundz__#9288 if it doesnt work try Sound_Wreaking#9288

**Comment by Sharpen-Up** [comment]
To remove mono from Pi:

sudo apt-get purge libmono* cli-common mono-runtime

sudo apt-get autoremove

This lot downloads the latest mono & preps it for install:

sudo apt install apt-transport-https dirmngr

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

echo "deb https://download.mono-project.com/repo/debian stable-raspbianstretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list

sudo apt update

Main install Command:

sudo apt install mono-devel

Check all went well with these commands:

mono --version

Should output "Mono JIT compiler version 5.18.0.225..."
then cd to your file location containing Minecraft.exe and mono Minecraft.exe you will be up and running.
eg."cd Desktop" then "mono Minecraft.exe" mine is located on my Pi's desktop. 

This is the solution I worked through with SoundWreaking, he is up and running with no more mono related issues on his Pi 3 B+

**Comment by AGuyNamedJens** [comment]
> To remove mono from Pi:
> sudo apt-get purge libmono* cli-common mono-runtime
> sudo apt-get autoremove
> This lot downloads the latest mono & preps it for install:
> sudo apt install apt-transport-https dirmngr
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
> echo "deb https://download.mono-project.com/repo/debian stable-raspbianstretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
> sudo apt update
> Main install Command:
> sudo apt install mono-devel
> Check all went well with these commands:
> mono --version
> Should output "Mono JIT compiler version 5.18.0.225..."
> then cd to your file location containing Minecraft.exe and mono Minecraft.exe you will be up and running.
> eg."cd Desktop" then "mono Minecraft.exe" mine is located on my Pi's desktop.
> This is the solution I worked through with SoundWreaking, he is up and running with no more mono related issues on his Pi 3 B+
> CLOSED

Nice that made my mono version go to 5.18.0.225 too. Sadly it didn't fix my issue that my console doesnt run my "onJoin" commands so i can automaticly connect to a skyblock server after logging in to hub..

**Comment by AGuyNamedJens** [comment]
It only executes the script after i manually enter /server skyblock, which is pretty much useless as i just want it to login to skyblock itself

**Comment by K3yX** [comment]
I have 

> To remove mono from Pi:
> 
> sudo apt-get purge libmono* cli-common mono-runtime
> 
> sudo apt-get autoremove
> 
> This lot downloads the latest mono & preps it for install:
> 
> sudo apt install apt-transport-https dirmngr
> 
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
> 
> echo "deb https://download.mono-project.com/repo/debian stable-raspbianstretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
> 
> sudo apt update
> 
> Main install Command:
> 
> sudo apt install mono-devel
> 
> Check all went well with these commands:
> 
> mono --version
> 
> Should output "Mono JIT compiler version 5.18.0.225..."
> then cd to your file location containing Minecraft.exe and mono Minecraft.exe you will be up and running.
> eg."cd Desktop" then "mono Minecraft.exe" mine is located on my Pi's desktop.
> 
> This is the solution I worked through with SoundWreaking, he is up and running with no more mono related issues on his Pi 3 B+
> 
> CLOSED

I tried this, but I fail at " echo "deb https://download.mono-project.com/repo/debian stable-raspbianstretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list" 

Should I excute this in two commands? The first one is working fine, but when using the second one my console just gets stucked.

Thanks for any answers.

**Comment by ORelio** [comment]
Silent disconnect should be fixed as per #1219.
