### ISSUE TITLE
Run .bat file from matches.ini

### ISSUE THREAD

**Issue by JacobBathead** [ORelio/Minecraft-Console-Client#571]
Hi,
I'm trying to run a .bat file that moves a .txt file for a shop refresh in a server. I am currently using this script in the maches file:

[Match]
match=<skyworld,14393,181,4718>
actionother=script products\wool\0blackwoolrun.bat

The match searches for a server command that displays the coordinates of a chest that is empty, however when checked, the bat file is not run as a batch file, but as a normal MCC text file. I tehre any way to run this as a batch file?

**Comment by JacobBathead** [comment]
(if needed, would this have to run though a C# script that would then run the .bat file?)

**Comment by TheSnoozer** [comment]
Not sure if you could that with `actionother` (doubt you can), I guess what you need is to write your own script.

I would recommend the following to start off:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs

Then extend it with with match logic (e.g. https://stackoverflow.com/a/2566355) and if you encounter a match 'simply' call the batch file (e.g. https://stackoverflow.com/a/16823732)

Hope that helps.

**Comment by ORelio** [comment]
If you really need to launch an external program, you could use a C# script.
````C#
//MCCScript 1.0
System.Diagnostics.Process.Start("myfile.bat")
````
For more info, see [How do I start a process from C#](https://stackoverflow.com/questions/181719/how-do-i-start-a-process-from-c).

**Comment by TheSnoozer** [comment]
Closing as answered.
Feel free to reopen if you still have a question with this specific problem.
Otherwise please open a new issue.
