### ISSUE TITLE
TriggerOnInterval doesn't work

### ISSUE THREAD

**Issue by UnioDex** [ORelio/Minecraft-Console-Client#574]
I'm using the latest dev version of MCC. 
ScriptScheduler is enabled in MinecraftClient.ini and triggerOnFirstLogin task is working as expected. But triggerOnInterval tasks doesn't working.

My tasks.ini:
```
[Task]
triggerOnInterval=true
timeInterval=5
script=sellall.txt

[Task]
triggerOnInterval=true
triggerOnFirstLogin=true
timeInterval=60
script=join.txt
```
sellall.txt:
```
send /sell all
```

join.txt:
```
send /server Skyblock
```

**Comment by ORelio** [comment]
You may need to create 2 separate tasks with only 1 trigger per task. Try enabling `debugmessages` to see how you tasks are loaded.

**Comment by UnioDex** [comment]
Problem solved when i remove the second trigger.
