### ISSUE TITLE
is there anyway to check if the player in the console client has an certain item in there inventory?

### ISSUE THREAD

**Issue by Twi5TeD** [ORelio/Minecraft-Console-Client#575]
is there anyway to check if the player in the console client has an certain item in there inventory? 
i wanted a script to sell if a block goes into the players inventory is there anyway of doing that

**Comment by ORelio** [comment]
Sorry, inventory is not implemented.

**Comment by Twi5TeD** [comment]
would this ever be added?

**Comment by ORelio** [comment]
Unfortunately I have no time to work on it myself at the moment. However a contributor could pick up this feature request and implement it.

**Comment by TheSnoozer** [comment]
Closing as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/205
