### ISSUE TITLE
Cant understand regex and stuff after going through most of the threads :/

### ISSUE THREAD

**Issue by Devan99** [ORelio/Minecraft-Console-Client#579]
i tried and i failed welp!
want to coop myself with a private message sent to alt but it dont recognize i think maybe error in regex or something...
also tried doing botowners=botowners.txt and writing all island mates name(one in each line) i think it can work like that
![regex](https://user-images.githubusercontent.com/39348991/47165234-36173800-d317-11e8-8141-b1b0836ccb2e.png)
![botowners](https://user-images.githubusercontent.com/39348991/47165233-36173800-d317-11e8-8915-e9b68a53b0c0.png)
![matches](https://user-images.githubusercontent.com/39348991/47165235-36afce80-d317-11e8-83b6-76d75f0e977c.png)
![chatformat](https://user-images.githubusercontent.com/39348991/47165238-36afce80-d317-11e8-8bef-1a1ac36d982c.png)

**Comment by TheSnoozer** [comment]
I would recommend:
https://www.regular-expressions.info/tutorial.html

The default pattern looks like this:
``private=^([a-zA-Z0-9_]+) whispers to you: (.+)$``

Essentially what you are doing here is the `(...)` is creating two regex groups, each pair of braces is one group. The first group contains the funny `[a-zA-Z0-9_]+`.
In regex that means match a single character present in the list of ``a-zA-Z0-9_``. The `+` is a quantifier Quantifier that tries to apply the of the character group one and unlimited times, as many times as possible. In normal words what it says is 'try to extract everything that matched the characters until the next item would be `whispers to you`. The assumption here is that the message would be constructed like `XYZ whispers to you: hello`. The frist group would extract XYZ that would represent the minecraft username that wispered to you. The second part of the regex (.+) is essentially meaning that you want everything else until the end of the string. In regex terminology the `^` is the start and `$` the end of a string.


For your problem try the following
https://regex101.com/r/VOQslA/1

The rest is really on you to learn and understand over time.

**Comment by Devan99** [comment]
Thx for explaining like that just made tpaccept regex....took 1hr but atleast it works still dunno how to make owners only thingy i made:
botowners=owners.txt in minecraft ini then put name of owners one in each line like
Name1
Name2
Name3
still whenever i do ownersonly=true in matches ini it dont recognize the message.

Doing anything wrong?

**Comment by ORelio** [comment]
Problem resolved, closing the issue. Feel free to reopen if needed.
