### ISSUE TITLE
Failed to connect to this IP

### ISSUE THREAD

**Issue by Shadow3097** [ORelio/Minecraft-Console-Client#58]
everytime i log on to a server the client says: "Failed to connect to this IP"
Here is the Console Output:

Console Client for MC 1.4.6 to 1.8.1 - v1.8.0 - By ORelio & Contributors
Connecting to Minecraft.net...
Success. (session ID: 0436003ea380405086e66ee9558c5ba3)
Using Minecraft version 1.8.0 (protocol v47)
Failed to connect to this IP.

Pls help

**Comment by ORelio** [comment]
Hello,
Seems like the server is not reachable.
I you can connect with the main Minecraft game, I don't know why MCC would not be able to connect.
