### ISSUE TITLE
Regex Captcha Solver..

### ISSUE THREAD

**Issue by Withheldbyuser** [ORelio/Minecraft-Console-Client#580]
So the current regex is:

[Match]
regex=^You can't speak yet! You need to move, or say this short captcha in chat: (.*)
action=send $1
actionother=send $1

And this works perfectly for what i need it to do, except.. The server has an anti spam filter and outputs this:

Please wait at least 0.5 seconds between messages.

Leaving the captcha unsolved and the bot unable to speak.
Any solutions?

**Comment by TheSnoozer** [comment]
I would guess that both action and actionother will cause to send a message and thus most likely the server will receive two messages.

if this still doesn't help maybe just call a script like so:
```
[Match]
regex=^You can't speak yet! You need to move, or say this short captcha in chat: (.*)
actionother=script solvecaptcha
```

and inside ```solvecaptcha```:
```
wait 50
send $1
```

not tested, but should work

**Comment by monkeysaww** [comment]
Witheldbyuser, how were you able to get past the "You must move before chatting or using commands" thing? I'm assuming you play on pvpwars because most people doing this do. Whenever I try to /move, my alt moves but it still doesn't let me use commands.

**Comment by Withheldbyuser** [comment]
Nope completely different server,

**Comment by Twi5TeD** [comment]
thats because you need the alt to turn its head

**Comment by Withheldbyuser** [comment]
So i found the solution to my own issue,
Instead of the initial:
[Match]
regex=^You can't speak yet! You need to move, or say this short captcha in chat: (.*)
action=send $1
actionother=send $1

I changed it to

[Match]
regex=^You can't speak yet! You need to move, or say this short captcha in chat: (.*)
action=set  captcha=$1
actionother=set  captcha=$1

This set the variable %captcha% to the solution to the captcha.. I also added another match to matches.ini:

[Match]
match=You can't speak yet!
action=script captchasolver
actionother=script captchasolver

Captchasolver:

wait 10
send %captcha%
