### ISSUE TITLE
feature: movement does not support player rotation / spinning

### ISSUE THREAD

**Issue by Twi5TeD** [ORelio/Minecraft-Console-Client#584]
does anyone know how i could bypass You must move around before typing a command or chatting ive tried using /move but the player must spin in order to bypass this message could anyone help me

**Comment by ORelio** [comment]
Unfortunately, spinning is not implemented.

**Comment by repository** [comment]
#697 allows for player rotation

**Comment by ORelio** [comment]
Thanks for your contribution!
