### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by Guyplay** [ORelio/Minecraft-Console-Client#585]
Exception non gérée : System.OverflowException: VarInt too big
   à MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextVarInt(List`1 cache)
   à MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, List`1 packetData)
   à MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   à MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()

**Comment by ORelio** [comment]
Make sure you use the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
