### ISSUE TITLE
Cannot Connect to Bungeecord 1.8 Servers.

### ISSUE THREAD

**Issue by JamieSinn** [ORelio/Minecraft-Console-Client#59]
http://prntscr.com/5ugx9y

**Comment by ORelio** [comment]
![manual-version](https://cloud.githubusercontent.com/assets/1128206/5822012/b18d6f68-a0d0-11e4-8f32-894a39e4ba99.png)

**Comment by JamieSinn** [comment]
Ah, that's a lot easier.

Thanks

**Comment by ORelio** [comment]
An automatic check will be added in next version.
Basically if server version is 0 but description contains " 1.8 " it will automatially switch to 1.8 :)
