### ISSUE TITLE
Can't connect to server with VPN

### ISSUE THREAD

**Issue by Nate278** [ORelio/Minecraft-Console-Client#590]
I play Saico. VPN's are allowed and I am using one as we speak. I'm connected and online right now but whenever I use a VPN whilst having console client open, it seems that it doesn't like me having a VPN. Everything works fine when the VPN is disabled but as soon as my VPN is enabled it says "Blacklisted IP or too many logins". But again, works fine when the VPN is disabled. Any suggestions?

**Comment by ObscenityIB** [comment]
Use something like Gather Proxy and scrape for SOCKS5 proxies, then test them against https://whatsmyip.com/proxy-check/ for the string `No Proxy Detected`

If that string is in the page, your proxy will work on Minecraft

**Comment by alicenchains** [comment]
Don’t use a VPN, I’d use a proxy. Just copy and paste it into the MinecraftClient.ini file and remember to enable proxy. If you’re using a lot of accounts on the same IP and logging them in quickly, your IP will temporarily be banned by Mojang (5 minutes-ish) and it will say Login failed or blacklisted. It also does this if you buy a lot of alts and some of their info is wrong, they’ll temp ban to prevent brute force attacks. 

After verifying all of your account info is correct, go to the MinecraftClient.ini file and change sessioncache to disk.

**Comment by TheSnoozer** [comment]
As described above this is not a problem with the client, rather that mojang 'temporarily' blacklisted your IP. In most cases the reason for this message is that the authentication failed too many times in a row. Usually your IP will be unblacklisted within 1 hour. If you are using a VPN turn it off and try again (after waiting one hour).

If the problem persists contact Mojang.

Feel free to reopen if you have any further questions regarding this particular issue.
