### ISSUE TITLE
Issue Cleanup

### ISSUE THREAD

**Issue by hashdashme** [ORelio/Minecraft-Console-Client#592]
Hey!

I've started to notice a massive pileup of inactive issues, it's hard for me to know which are relevant and what is not...

So I was wondering if you could implement some sort of bot to clean this up.

~Thanks in Advance!

**Comment by ZizzyDizzyMC** [comment]
I've actually been planning to come back and help ORelio with these
issues.  Inactive doesn't mean they don't still exist.  Updates may have
incidentally fixed them etc.  Lots of "issues" are more of a kind of
support request as well.

**Comment by TheSnoozer** [comment]
I would be happy to help on that front too.

I guess what could also be helpful to establish a label system that gives an indicator where the issue belongs to.

E.g.
![selection_2018-11-12_18-59-51](https://user-images.githubusercontent.com/6849390/48382070-5683a980-e6ad-11e8-81dc-37cf75aab1fe.png)

**Comment by ORelio** [comment]
Just reviewed around 2 pages of them but they are too numerous. :sweat:

I'm glad to hear that you are offering your help for this. Is there any way to delegate issue management on GitHub? I know there is a "Reporter" role on GitLab but I can't find something similar here.

**Comment by TheSnoozer** [comment]
AFAIK there are two different ways to grant users access.

1. Granting users [`Collaborator` role](https://help.github.com/articles/permission-levels-for-a-user-account-repository/)
This is IMHO a too broad permission and would allow us to:
- Push to (write), pull from (read), and fork (copy) the repository
- Create, apply, and delete labels and milestones
- Open, close, re-open, and assign issues
- Edit and delete comments on commits, pull requests, and issues
- Mark an issue or pull request as a duplicate.
- Open, merge and close pull requests
- Apply suggested changes to pull requests they authored or are assigned to.
- Send pull requests from forks of the repository
- Create and edit Wikis
- Create and edit Releases
- Remove themselves as collaborators on the repository
- Submit a review on a pull request that will affect its mergeability

2. Treat ORelio as `Organization` account, or create a new account and fork the repository as  `Organization`
This would give you the ability to grant more fain grained permissions (https://help.github.com/articles/repository-permission-levels-for-an-organization/)

You can find and read about them in more detail here:
https://help.github.com/articles/access-permissions-on-github/

I'm not aware of any other alternatives.

**Comment by ORelio** [comment]
Thanks for your research, it seems to confirm that GitHub does not offer fine-gained permissions.  For organizations, the "read" permission is similar to access for a public repository: clone, fork, open issues.... the "write access" is similar to the "Collaborator" role for a personal repository: it allows to push code and manage Wiki & issues.

Given the lack of permission settings and your involvement into the project, I'm adding you as a collaborator. Feel free to continue opening pull requests if you need me to review your contributions :wink:

**Comment by TheSnoozer** [comment]
Thanks :-)
Highly appreciate it and I promise I won't abuse the permissions ;-)
And yeah its somewhat sad that github doesn't allow more fain grain permission control :-/

**Comment by TheSnoozer** [comment]
Closing as part of the cleanup :-P

**Comment by TheSnoozer** [comment]
Thanks :-)
To be fair I'm not sure if all labels turn out to be so useful...feel free to add/delete or modify them in any shape or form. Also feel free to raise any feedback on how to improve them. In the end of the day I'm just thinking they might help...in most cases users who file issues won't apply them. I think its mainly helpful to see in what category existing issues fall. If they turn out to be an utterly waste of time, you (or me) still can get rid of them.
