### ISSUE TITLE
Implement cooldown for an AutoRespond match

### ISSUE THREAD

**Issue by Pure8eat** [ORelio/Minecraft-Console-Client#593]
Hey. My bot currently displays a large, split up message when the matches detects the correct word. However, some players abuse this and spam the account extremely quickly, causing my bot to get kicked for spamming. Is there any way to add some kind of cooldown either during or after a script has executed, so that it cannot be re-triggered whilst it is in the middle of processing? Or, is there a way to add some form of delay, so that my bot will not talk after the command for a certain amount of time?

**Comment by ORelio** [comment]
The AutoRespond bot do not handle cooldown, however, you can implement a delay in your script or chatbot, provided it is written in C# (sample scripts [here](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)).

**Comment by ORelio** [comment]
You can now add a cooldown on AutoRespond matches using an additional `cooldown` field expressed in seconds:
```ini
[Match]
match=hello
action=send hello!
cooldown=60
```
In the example above, the bot will not respond "hello!" more than once per minute.
