### ISSUE TITLE
New Version 1.13.2 does not work on WIndows Server

### ISSUE THREAD

**Issue by Krippi** [ORelio/Minecraft-Console-Client#594]
I am using the Console client on a Windows 2016 server. This has always worked, but only with the 1.12.2 version of the program. Since it has been updated to 1.13.2, the program does not even start. The window does not appear too. If I change the older version it works though.

**Comment by ORelio** [comment]
Try opening a console in the same folder as MCC and invoking it from the command line. It should display an error message that you can't see when launching it standalone.

**Comment by Krippi** [comment]
Oke, I got it started on another console and it worked. It does not work if I run the exe myself

**Comment by ORelio** [comment]
This is weird. Just checked on AppVeyor, builds for the past 6 months were all made by AppVeyor using MSBuild version 14.0.25420.1. Anyway, as a workaround, you could try creating a `MinecraftClient.bat` file with the following content:
````batch
@echo off
MinecraftClient.exe
````
This should allow loading MCC by clicking on the batch file. Hopefully. If it does not, add `pause` at third line in the batch file to see the error.

**Comment by Krippi** [comment]
Yeah thanks, but I have already made it ^ ^ But thank u for your answere.

**Comment by ORelio** [comment]
OK, I'll close the issue, but feel free to reopen if you manage to get an error message or anything else that would help determining whether it is linked to MCC or your system configuration. :wink:
