### ISSUE TITLE
How do I install it? 

### ISSUE THREAD

**Issue by Jumpyy123** [ORelio/Minecraft-Console-Client#595]
Hey, I'm sorry about this but i'm really confused. I don't know how to do anything. I think I'm having a similar problem, I've got MinecraftClient installed, on my Desktop and im trying to run it on a VPS, but I've installed a lot of "Mono" stuff and all that, but I still can't seem to get it working, can you please help?

**Comment by ORelio** [comment]
Have you tried [these steps](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt#L19)?
1. `sudo apt-get install mono-runtime libmono-reflection-cil`
2. `mozroots --import --ask-remove`
3. `mono MinecraftClient.exe`
