### ISSUE TITLE
Auto reply

### ISSUE THREAD

**Issue by lansraad** [ORelio/Minecraft-Console-Client#596]
Hiya, i'm just wondering how to make my Console Client reply to a specific word or phrase and run an internal command like /respawn or a server command like /feed. Any info at all would be helpful :D

**Comment by TheSnoozer** [comment]
Since this issue is open for quite a while and has been answered, I'd assume you could get the suggested solution working. If you still have a problem with this, please feel free to reopen, otherwise please open a new issue.
