### ISSUE TITLE
"Cannot send chat message"

### ISSUE THREAD

**Issue by SigmaticsX** [ORelio/Minecraft-Console-Client#597]
Whenever I try to send a message, command etc. it says "Can not send chat message" in red text. What does this mean and how do I fix it?

**Comment by Mhowser** [comment]
Did your player die? Type /respawn

**Comment by TheSnoozer** [comment]
Does the server has an anti-cheat that disallows to write chat messages before moving?

**Comment by Vbielgb123** [comment]
I'm having the same problem, could anyone do this?

**Comment by ipadalert** [comment]
You might have chat mode disabled or commands only in `MCSettings`, when that is disabled you aren't allowed to send messages depending on the mode.

**Comment by Govindass** [comment]
this message normally appears to me when I die unnormally, so it must be something death related

**Comment by Mhowser** [comment]
Did you try /respawn?

**Comment by TheSnoozer** [comment]
Can you use chat after `/respawn`?

**Comment by SigmaticsX** [comment]
Turns out I was dead. Sorry for not responding and thank you!

**Comment by TheSnoozer** [comment]
Thanks for the response :-)
Glad you could figure this out.
