### ISSUE TITLE
AFK'ing does not work for farms.

### ISSUE THREAD

**Issue by iiLearner** [ORelio/Minecraft-Console-Client#602]
Hello, 

Great bot overall, thank you for the development.
I wanted to use the bot to afk at my sugarcane farm however I noticed crops do not grow even when the bot is very close, if and how can I solve it? thank you.

**Comment by TheSnoozer** [comment]
From what I know there could be two reasons why this is happening and I would recommend to check the following:
In some cases the server would not allow you to afk, if you have the terrain disabled.
Try to set ``terrainandmovements=true`` inside your ``MinecraftClient.ini``.

Also in some cases this might be related to the brandinfo inside``MinecraftClient.ini``
Try to set it to ``brandinfo=vanilla`` (which is the brand the is sent by the default client - see https://wiki.vg/Plugin_channels#minecraft:brand)

**Comment by iiLearner** [comment]
@TheSnoozer Ive already tried that, doesn't work.

**Comment by ORelio** [comment]
Also on `1.13` there is no `terrainandmovements` at the moment. The setting does nothing because it is not implemented. A warning message should display upon joining a server if terain and movements are enabled but not enabled for that server version.

**Comment by iiLearner** [comment]
I have also enabled the options stated by @TheSnoozer and tried moving.
