### ISSUE TITLE
AutoRespond issues

### ISSUE THREAD

**Issue by OrelioIsAGod** [ORelio/Minecraft-Console-Client#605]
Hello community, I have recently be using the auto respond feature with matches.ini  I want to set up an auto join feature and set home feature for all my alts doing /f join [faction] and /sethome when i say j8123 in the public chat. I have already tried to do something but is still not working.

This is the situation:

**MinecraftClient.ini**
```
[ChatFormat]
# Do not forget to uncomment (remove '#') these settings if modifying them
builtins=false                      # MCC built-in support for common message formats
public=^\[(.+)\] \[([a-zA-Z0-9_]+)\] ([a-zA-Z0-9_]+): (.+)$
#  private=(?:\[[A-Za-z0-9 ]+\] )\[([a-zA-Z0-9_]+) -> me\] (.+)
#  tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to `(?:you|them)\.$
```

**Matches.ini**
```
[Match]
match=[***BlitzKrieg] [Predator] MARCO3029: j8123
actionprivate=send /f join MARCO3029

```
and nothing is working...

**Chat log**
```
SHOP No items in your inventory could be sold. 
Koth Alpha will be captured by KingSchaffy in 4 minutes 
[***BlitzKrieg] [Predator] MARCO3029: j8123 
[MCC] [Script] send /sellall 
SHOP No items in your inventory could be sold. 

```

**Comment by ORelio** [comment]
If you disable `builtins`, then you are expected to specify `public`, `private` and `tprequest` regexes otherwise all chat lines will be categorized as `other` and only `actionother` will work.

**Comment by OrelioIsAGod** [comment]
Ok, so if I want the public chat messages to be classified, what should I do?

**Comment by ORelio** [comment]
If public messages are using the following format:
```
[***BlitzKrieg] [Predator] MARCO3029: j8123
```
... Then your `public` regex is almost correct. You need to remove parenthesis for the faction and user class in order not to capture them. See the difference here:

https://regex101.com/r/l9Qlrz/1
https://regex101.com/r/l9Qlrz/2

Fixed regex is `^\[.+\] \[[a-zA-Z0-9_]+\] ([a-zA-Z0-9_]+): (.+)$`
Besides, if specifiying a `private` and `tprequest` regex, do not forget to uncomment them (remove `#`).

**Comment by OrelioIsAGod** [comment]
I have tried to change the regex and to add the # on MinecraftClient.ini but is not working .

```
 [ChatFormat]
# Do not forget to uncomment (remove '#') these settings if modifying them
builtins=false                      # MCC built-in support for common message formats
public= ^\[.+\] \[[a-zA-Z0-9_]+\] ([a-zA-Z0-9_]+): (.+)$
#  private=(?:\[[A-Za-z0-9 ]+\] )\[([a-zA-Z0-9_]+) -> me\] (.+)
#  tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$
```

**Comment by OrelioIsAGod** [comment]
what should i have to do?

**Comment by ipadalert** [comment]
You need to get rid of the comments (#) in front of the chat format for the action to work.

**Comment by ipadalert** [comment]
You need to get rid of the comment(#) in front of private on chat format for the auto respond to work.

**Comment by OrelioIsAGod** [comment]
Is not working

```
[Match]
match=[***BlitzKrieg] [Predator] MARCO3029: j8123
action=send /f join MARCO3029

```

**Comment by ipadalert** [comment]
You cannot have `[***BlitzKrieg] [Predator] MARCO3029: ` within your `[Match]` you just need j8123 and it should work then, to make it just respond to you set the regex for your `public` to `^\[[^]]+\] \[[a-zA-Z0-9_]+\] ([MARCO3029]+): (.+)$` with your `[Match]` being 

[Match] 
match=j8123
action=send /f join MARCO3029

**Comment by OrelioIsAGod** [comment]
uh now is working pretty good, thanks for the help

**Comment by OrelioIsAGod** [comment]
Uh finnally.. Now work pretty good

**Matches.ini**
```
[Match]
match=j8123
action=send /f join MARCO3029

[Match]
match=sethome
actionprivate=send /sethome afk

[RemoteControl]
enabled=true
autotpaccept=true
tpaccepteveryone=false

```

**MinecraftClient.ini**

```
[ChatFormat]
# Do not forget to uncomment (remove '#') these settings if modifying them
builtins=false                     # MCC built-in support for common message formats
public=^\[[^]]+\] \[[a-zA-Z0-9_]+\] ([MARCO3029]+): (.+)$
private=(?:\[[a-zA-Z0-9_]+\] )\[([a-zA-Z0-9_]+) ➡ me\] (.+)$
tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them).
```

I thank Orelio and Ipadalert for their help and I apologize for the time I have made you lose <3

**Comment by TheSnoozer** [comment]
Glad you could get this sorted.
Closing as solved. Feel free to open a new issue, if you have any other problem(s).
