### ISSUE TITLE
Forge support for Minecraft 1.12.2

### ISSUE THREAD

**Issue by g33builder** [ORelio/Minecraft-Console-Client#607]
Retrieving Server Info...
Server version : Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x (protocol v340).
Version is supported.
Logging in...
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server.
You have been kicked back to the hub! Reason:  This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.

I closed this post at first because I made it on accident but after doing a bit of digging to try and solve the issue I could not find anything. But yeah, I don't know if this is a bug, if its not supported, or if I'm just doing it wrong.

**Comment by shadowmaster526** [comment]
You just need to put the launch files into your modded game folder

**Comment by g33builder** [comment]
> You just need to put the launch files into your modded game folder

They are :(

**Comment by ORelio** [comment]
Try setting debugmessages=true in config, you might get more help because MCC should detect the mod list to fake and send it back to the server. Also try specifying a fixed Minecraft version in config (mcversion=1.X.X), maybe MCC is misdetecting an incorrect MC version.

**Comment by BTOptimizer** [comment]
I tried both suggestions (setting **debugmessages** to true, and setting **mcversion** to 1.12.2) and couldn't get through either. Just the same old "This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details." error message. I'm trying to connect to a Stoneblock 2 server.

**Comment by ORelio** [comment]
MCC should support FML/Forge. What debug messages are being printed to the console when joining?

**Comment by BTOptimizer** [comment]
Server IP : Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Ignoring session token string 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMzNmMWVjNDZjMjA0Y2M3YWY3MzVhMzVkNWNlODEwYSIsInlnZ3QiOiJhNzYyNTBiMTZlZGI0ZTRmOWZiNWU3MDQ0NjFjMjljMCIsInNwciI6IjIyMGI5ODA5Y2IxMjQxODFiNmYwMzdkMGFkOTQ1ZTRiIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODY5MjY0NzYsImlhdCI6MTU4Njc1MzY3Nn0.6q2xVMIcMC7E2H5hICwYH8thOunzad2HSQ_SUMTpHXA,HeLiX_iS_BeTa,220b9809cb124181b6f037d0ad945e4b,d8d87560d5154b44a9d64e792b7e3f2a': Invalid session ID
//**(This line has the server IP)**
Resolving //**(Server IP again)**...
Using Minecraft version 1.12.2 (protocol v340)
Translations file loaded.
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Performing request to sessionserver.mojang.com
> POST /session/minecraft/join HTTP/1.1
> Host: sessionserver.mojang.com
> User-Agent: MCC/1.14.4
> Content-Type: application/json
> Content-Length: 434
> Connection: close
>
> {"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMzNmMWVjNDZjMjA0Y2M3YWY3MzVhMzVkNWNlODEwYSIsInlnZ3QiOiJhNzYyNTBiMTZlZGI0ZTRmOWZiNWU3MDQ0NjFjMjljMCIsInNwciI6IjIyMGI5ODA5Y2IxMjQxODFiNmYwMzdkMGFkOTQ1ZTRiIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODY5MjY0NzYsImlhdCI6MTU4Njc1MzY3Nn0.6q2xVMIcMC7E2H5hICwYH8thOunzad2HSQ_SUMTpHXA","selectedProfile":"220b9809cb124181b6f037d0ad945e4b","serverId":"-5146a0fd708e91579f8e83519097f3d6a0276b11"}

< HTTP/1.1 204 No Content
< Connection: close
< Accept-Ranges: bytes
< Date: Mon, 13 Apr 2020 04:54:45 GMT
< Server: Restlet-Framework/2.3.12
< X-Cache: Miss from cloudfront
< Via: 1.1 6c378f62253fc1e443ac0b930892a0d4.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: BOS50-C1
< X-Amz-Cf-Id: eEyrdpn1lUMf9a18oRR0KNd1ik30SKSCqOBZbG5suRKbiKKq483X9Q==
<
<
Server was successfully joined.
Type '/quit' to leave the server.
Disconnected by Server :
Kicked whilst connecting to sb2: This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by BTOptimizer** [comment]
Resending because I'm not sure if any of the session cache details are best left hidden, so I'll start at the section where the IP is entered:

/**(Hidden but the server IP is right here)**/
Resolving **/(Server IP again)/**...
Using Minecraft version 1.12.2 (protocol v340)
Translations file loaded.
Version is supported.
Logging in...
Crypto keys & hash generated.
Checking Session...
Performing request to sessionserver.mojang.com
> POST /session/minecraft/join HTTP/1.1
> Host: sessionserver.mojang.com
> User-Agent: MCC/1.14.4
> Content-Type: application/json
> Content-Length: 434
> Connection: close
>
> /**(Not sure if this section is important but it includes "accessToken", "selectedProfile", and "serverId")**/

< HTTP/1.1 204 No Content
< Connection: close
< Accept-Ranges: bytes
< Date: Mon, 13 Apr 2020 05:10:25 GMT
< Server: Restlet-Framework/2.3.12
< X-Cache: Miss from cloudfront
< Via: 1.1 55816cf05e8d81696f2f421e217d6205.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: BOS50-C1
< X-Amz-Cf-Id: RUdDhllppsa9FX7v49stB5oPvO8ZpJjqnkavWJoZwrhmmxNz1OtR1w==
<
<
Server was successfully joined.
Type '/quit' to leave the server.
Disconnected by Server :
Kicked whilst connecting to sb2: This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by ORelio** [comment]
Seems like Forge is not detected at all by MCC, it tries to login in vanilla mode. Maybe Forge support no longer works for recent Minecraft versions such as 1.12.2. Adding this to the todo list.

**Comment by minidude2012** [comment]
was this fixed just want to report that i was able to connect to a enigmatica 2 expert server using mcc without issues

**Comment by ORelio** [comment]
Thanks. Closing this as resolved.
