### ISSUE TITLE
Ability to mod console client and add Forge Mod loader

### ISSUE THREAD

**Issue by friendlytherapist** [ORelio/Minecraft-Console-Client#609]
This is a big one. Im looking to figure out a way to install forge mod loader into console client so I can then install a mod called Replay mod which records everything that happens around the player. This would work as a 24/7 Minecraft security camera. The reason im looking to console client is that it can reconnect when kicked and is generally way more friendly to automation than the standalone Minecraft client. Any hope for this?

**Comment by Pokechu22** [comment]
No.  MCC is written in C#, and forge (and normal Minecraft) use java.  To support forge, it'd need to support every single part of normal minecraft, at which point it basically is normal minecraft, even ignoring the different programming languages issue.

**Comment by friendlytherapist** [comment]
worth a shot. Thanks

**Comment by TheSnoozer** [comment]
Thanks for the idea, but as outlined above that sounds not really feasonable
