### ISSUE TITLE
How to move to a new location

### ISSUE THREAD

**Issue by friendlytherapist** [ORelio/Minecraft-Console-Client#611]
Im using c# to write my script when I come to this problem. I would like to set a location as my current location. This is what im using but it doesn't work. I know using `blockLoc = new Location(br1X, br1Y, br1Z)` would work but how do I set these values to my current location.

```
Location current1 = GetCurrentLocation();
LogToConsole("Current location: " + current1);          
blockLoc = new Location(current1);
LogToConsole("Checking block at: " + blockLoc);          
Material blockType = GetWorld().GetBlock(blockLoc).Type;
```

**Comment by friendlytherapist** [comment]
solved last question with PerformInternalCommand but still need first question answered

**Comment by TheSnoozer** [comment]
Try the in-build `move` command
```
/move
MCC: move <get|up|down|east|west|north|south|x y z>: walk or start walking.

e.g.
/move 1 127 0
```
