### ISSUE TITLE
how to loop two commands infinitely at fixed interval from each other

### ISSUE THREAD

**Issue by Devan99** [ORelio/Minecraft-Console-Client#614]
want cc to loop to commands at fixed interval from each other like difference of about an hour in between each other always....tried two tasks one on 1hour and other on two hour but every other hour they overlap any idea if we can make use of wait & loop in a script.txt file and call that from tasks.ini

**Comment by Honeth** [comment]
there are several ways of solving your issue if you haven't found any already.

1 would be using TaskScheduler to trigger the commands at set hours would require you to type a bit more then you'd possible like to but it'd work.
`
[Task]
triggerOnTime=true
timeValue=00:01
timeValue=02:01
timeValue=04:01
timeValue=06:01
timeValue=08:01
timeValue=10:01
timeValue=12:01
timeValue=14:01
timeValue=16:01
timeValue=18:01
timeValue=20:01
timeValue=22:01
script=script.txt
`
this will trigger script.txt every 2 hours
which means you'd make your script.txt look like this
`
send /command 1
wait 3600
send /command 2
`
or you'd make another task but on the other hours with another script.

**Comment by TheSnoozer** [comment]
Alternatively you could write your own MCC Script.
However that would become slightly more complicated.

**Comment by ORelio** [comment]
Using appropriate time values in ScriptScheduler seem an appropriate way.
Here is another one:
**loop.txt**
> send /command1
> sleep 36000
> send /command2
> sleep 36000
> script loop

Then launch the loop on first login by calling the script once.

**Comment by TheSnoozer** [comment]
I believe we have now enough different examples to consider this question as answered. Feel free to reopen, if you still have a problem in getting it sorted. If you bump into any other issue, please open a new issue.

**Comment by CallMeVorex** [comment]
My script works manually when typing "/script skyblock" into the console but when i enable taskscheduler and configure it to re-run the script on an interval of 50 the .ini decides not to work and doesn't even run the script on login.

.ini file for taskrescheudler
`[Task]
triggerOnInterval=true
timeInterval=50
skyblock.txt`

script file
`send /server skyblock2
wait 50
send /server skyblock2`
