### ISSUE TITLE
Regex stopped working.

### ISSUE THREAD

**Issue by Deathnight7976** [ORelio/Minecraft-Console-Client#615]
So, Essentially the server i played on recently redid their balance system.. I used to have my alts check there balances and deposit it all to a faction bank. Recently this stopped working, i figured all i needed to do was change the wording as thats all it seemed the server had did. However this didnt work, infact now my matches/regex completely ignore the servers response to /bal:

The few regex/matches lines i use to make this work:

```
#Deposits:
`[Match]`
match=Balance: $
action=script Deposit
actionother=script Deposit
[Match]
regex=^\[Neme\] Balance: \$(\d+),(\d+),(\d+)
action=set CurrentBalance=$1$2$3
actionother=set CurrentBalance=$1$2$3
[Match]
regex=^\[Neme\] Balance: \$(\d+),(\d+)
action=set CurrentBalance=$1$2
actionother=set CurrentBalance=$1$2
[Match]
regex=^\[Neme\] Balance: \$(\d+),(\d+)\.(\d+)
action=set CurrentBalance=$1$2.$3
actionother=set CurrentBalance=$1$2.$3
[Match]
regex=^\[Neme\] Balance: \$(\d+),(\d+),(\d+)\.(\d+)
action=set CurrentBalance=$1$2$3.$4
actionother=set CurrentBalance=$1$2$3.$4
```

(I have to have it set its current balance as a variable because the server requires 0.5 secs between each message so an immediate response doesnt work.)

An example output from /bal
[Neme] Balance: $4,136,626

using https://regex101.com/ this should be a perfect match however it doesnt trigger at all
Also script deposit:
wait 10
send /f money deposit %CurrentBalance%

**Comment by TheSnoozer** [comment]
Interesting.

Have you by any changes configured the `ChatFormat` section inside the `MinecraftClient.ini`? E.g. does this section look like this:
```
[ChatFormat]
builtins=true #support for handling vanilla and common message formats
#public=^<([a-zA-Z0-9_]+)> (.+)$ #uncomment and adapt if necessary
#private=^([a-zA-Z0-9_]+) whispers to you: (.+)$ #vanilla example
#tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$
```
?

I would start to try to trouble shoot if the console client detects the messages properly and how the client detects the message. Afaik the client can treat the message as public, private or `other` and based on that might fire a different action if the message is matching.

E.g. could you try the following:
```
[Match]
regex=^\[Neme\] Balance: \$(\d+),(\d+),(\d+)
action=log detected "action" message balance $1$2$3
actionpublic=log detected "actionpublic" message balance $1$2$3
actionprivate=log detected "actionprivate" message balance $1$2$3
actionother=log detected "actionother" message balance $1$2$3
```
?

Also I would not be so sure if the actions have a specific order. in other words, I would not be sure, if you can have one action rely on the fact that a different action ran first.

**Comment by Deathnight7976** [comment]
I have not changed Chatformat at all, and the match did absolutely nothing.

**Comment by ORelio** [comment]
Better late than never: try troubleshooting using http://regex101.com/
Type the regex and chat message line to check the match result.
Also make sure chat messages are properly detected by MCC by testing simple matches. If they don't, specify regexes in the [ChatFormat] section of your INI file to tell MCC how to parse chat messages.

**Comment by Deathnight7976** [comment]
I tested in regex101 before i made the post, It matches correctly there and all my other simple matches also work on the client. Its just this one that has stopped working, seems the client doesn't even register that the servers response to /balance exists.

**Comment by ORelio** [comment]
Try enabling ChatLog and see what's logged. ChatLog is a MCC bot just like AutoRespond.
