### ISSUE TITLE
Mass message

### ISSUE THREAD

**Issue by Some1Random** [ORelio/Minecraft-Console-Client#616]
is there a way to add a gui based "plugin" to do some functions e.g send a message to everything with a delay between each message

e.g /tpa {name}
delay: 30000
instead of having to make a script to run the command on logon an relog?

if so how
and what else can it do

**Comment by TheSnoozer** [comment]
I'm not sure what you try to achieve here, but for me this sounds like advertising....

In general you could either try using matches and scripts that message certain users (e.g. https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini#L15) and as action put a script like `action=script test``that contains the messages you want to sent to the people (you know) like ```
wait 50
send /m UserName1 hello
wait 50
send /m UserName2 hello
....
```
or try to implement some custom MCCScript logic. MCCScripts contain C# code that allow you to extend the client. As an example see https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-pm-forwarder.cs

**Comment by Some1Random** [comment]
its usefull for factions

so you can do e.g /f join RandomName

or mass tpyes or tpa

**Comment by TheSnoozer** [comment]
Based on the broad question I believe I provided sufficient guidance on how this could go.

Feel free to open a new issue if you have a more specific problem.
