### ISSUE TITLE
Connection lost all the time 

### ISSUE THREAD

**Issue by tempn** [ORelio/Minecraft-Console-Client#617]
I keep getting this when using proxies.

Connection has been lost.
[MCC] [AutoRelog] Waiting 100 seconds before reconnecting...
Restarting Minecraft Console Client...
Performing request to authserver.mojang.com
> POST /validate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.12.2
> Content-Type: application/json
> Content-Length: 103
> Connection: close
>
> {"accessToken": "f4e58a285b894ead811aece50f6498c1", "clientToken": "354c1b0fb5834cf2952711792deeae1a" }

< HTTP/1.1 204 No Content
< Connection: close
< Accept-Ranges: bytes
< Date: Wed, 26 Dec 2018 21:04:54 GMT
< Server: Restlet-Framework/2.3.12
< X-Cache: Miss from cloudfront
< Via: 1.1 9beef7f4d5d93ab1724fe013eb38c198.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: V9uZq_WCxkPMztdUyF6OOk31bIFaEtkcCaPUYw6ucL48CpLjcOf2Lw==

**Comment by tempn** [comment]
> Have you tested that the proxy itself works?

Yes the proxies work but randomly drop connection like that after a little while.

**Comment by ORelio** [comment]
I think the proxy is the culprit. It probably has a timeout set by the owner. This cannot be fixed on MCC but rather on the proxy itself.
