### ISSUE TITLE
Can't detect console text in a regex

### ISSUE THREAD

**Issue by Yugnat2412** [ORelio/Minecraft-Console-Client#619]
I'm coding a !whoson command. The code is the following

#WHOSON
[Match]
regex=^.*!whoson.*$
action=list
[Match]
regex=^[MCC] [AutoRespond] PlayerList: (.*? ,)$
actionprivate=send $1

The first regex works and [MCC] [AutoRespond] Player1, Player2 etc shows in chat, but the second one fails. Is there a mistake in my code, or is it that you can't get console text with regexes ?
Thanks !

**Comment by ORelio** [comment]
Cannot match MCC output from AutoRespond. Only text from the server.
