### ISSUE TITLE
Unable to run in non-interactive shell mode

### ISSUE THREAD

**Issue by rlittlefield** [ORelio/Minecraft-Console-Client#62]
I'm trying to use the console client by wrapping it in a python script, redirecting stdin and stdout through the script so I can programmatically read chat and write to chat. When the console client runs with its stdin redirected, it throws an exception.

Some investigation shows that the culprit is Console.KeyAvailable and Console.ReadKey. I found a stackoverflow question where someone solves a similar problem :
http://stackoverflow.com/questions/3961542/checking-standard-input-in-c-sharp

Perhaps this could be solved by adapting the read functions to operate in a similar fashion. I'm happy to help in any way. I can attempt to fix it myself, but I'm not well versed in C# so it may take a while. Any direction in that area would be appreciated.

**Comment by ORelio** [comment]
Simply provide this exact string as last argument to disable interactive shell features : `BasicIO`
This will disable interactive command prompt and only write and read lines to/from standard IO.
Good luck, have fun in writing your application wrapper :)

**Comment by rlittlefield** [comment]
Oh, I saw that there and didn't realize what it would do. Thank you!

**Comment by ORelio** [comment]
Note: In basic IO chat will be written with `§c` [formatting codes](http://minecraft.gamepedia.com/Formatting_codes) so that you can handle colors in your GUI. Just strip them if you are not interested in chat colors ;)
