### ISSUE TITLE
Console Client closes after launching.

### ISSUE THREAD

**Issue by 8loodyHell** [ORelio/Minecraft-Console-Client#621]
So recently I have joined Minecraft again and I am trying to get my console clients running again. It used to work fine but now I am running into a problem. When using the recent version of the console client when it is opened it just opens up for maybe 2 seconds and then closes but nothing happens. When I try to use how I used to have it set up when I first played I get the error that says "Login Failed : Failed to check session". I don't know why that's why I am here looking for a fix.

**Comment by Sharpen-Up** [comment]
Can you post your Minecraft.ini for settings minus your login details xD.
Probs your server validation setting. Try changing it from fast to true :)

**Comment by Sharpen-Up** [comment]
`resolvesrvrecords=fast`             # Use 'false', 'fast' (5s timeout), or 'true'. Required for joining some servers.``

**Comment by 8loodyHell** [comment]
It worked. I just changed it to true. Thanks so much. It was just weird because I know multiple other people logging in with a console client into the same server without that settings on. Thanks!

**Comment by Sharpen-Up** [comment]
Yea I've not gotten around to seeing why that is. Fast worked for me as well until I ran into your issue and found swapping out that resolve record setting did the trick. Enjoy :)

**Comment by TheSnoozer** [comment]
Thanks for helping out here :-)

The underlying issue seems to be resolved and thus I'll close it.

Related to https://github.com/ORelio/Minecraft-Console-Client/issues/270
