### ISSUE TITLE
Console client bot

### ISSUE THREAD

**Issue by GraveyardLikesORelio** [ORelio/Minecraft-Console-Client#622]
So basically i was thinking if this was possible, making a host account, and whitelist permissions on it.
this "Host" account you would do /msg "HostAccount"  script tpa (Example) and when it recognizes that message it finds script tpa in your console client folder, and then it would do the command with other alts, as example with 25 alts.

**Comment by ipadalert** [comment]
Yes, this is possible, using the `[Auto Respond]` feature in the MinecraftClient.ini document. You want to enable first then move on to your Matches.ini document to detect and run commands. For your particular example running a script tpa it would look something a little like this

[Match]
match=script tpa
actionprivate=script tpa

With action private, depending on your server, you may need to tweak them in the `[Chat Format]` part of the MinecraftClient.ini document to fit the format of the private messages on the server. 

Example for a server I tried it on:
Chat Format Used:
`private=(?:\[[A-Za-z0-9 ]+\]) \[(ipadalert+) -> me\] (.+)`
AutoRespond Working:
![screen shot 2019-01-13 at 1 07 56 am](https://user-images.githubusercontent.com/45241936/51082157-bdced180-16cf-11e9-95b7-ff7a5f356651.png)

**Comment by TheSnoozer** [comment]
Thanks you for taking the time and answering the question :-)

I believe the response answered the question, so I'm closing this issue.

Feel free to open a new issue, if you have further (more) specific questions/problems.

PS: I'd also like to point to https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config where all the different options are outlined, along with sample configurations.
