### ISSUE TITLE
Unsupported protocol

### ISSUE THREAD

**Issue by adriagudayol1** [ORelio/Minecraft-Console-Client#623]
When i conect to a server (pvpwars) it say:
Logging in...
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server.
Disconnected by Server :
Unsupported protocol version 404
Not connected to any server. Use '/help' for help.

how can i fix this?

**Comment by Sharpen-Up** [comment]
Try go through these first then explain in more detail afterwards if you still cant connect.
Refer to issue below.

#621

**Comment by TheSnoozer** [comment]
Could you get this sorted?

**Comment by ORelio** [comment]
Force the correct Minecraft version with `mcversion=1.X.X` in your INI file.
