### ISSUE TITLE
Getting a Player's UUID

### ISSUE THREAD

**Issue by FoamyTheFag** [ORelio/Minecraft-Console-Client#625]
I would like to create a ChatBot where it gets a user's UUID and stores it. I have already figured out everything else, besides how to actually get a player's UUID from their in game name.

I tried making my own string in McTcpClient with a parameter for ign, however it always returns null and I can't think of another way to get a player's UUID.

**Comment by TheSnoozer** [comment]
Mhh interesting.
Inside a MCC-Script you currently could use the [MCC.GetOnlinePlayers()](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L655) method to get all the player names, but it does not return the UUIDs.
We currently maintain a dict of UUID <-> playerName relation inside the ``onlinePlayers`` variable, so I guess there is currently no such thing where you get the data from.

However it should be an easy extension to get the information you need.

**Comment by ORelio** [comment]
Now implemented thanks to @TheSnoozer contribution. Check it out :wink:
