### ISSUE TITLE
Connection lost every time I load something on start

### ISSUE THREAD

**Issue by FallenSuperr** [ORelio/Minecraft-Console-Client#628]
Hi ORelio

I've been having this issue where every time I try to load in any type of script I get the following error.
https://imgur.com/a/wwwiQPX

This doesn't happen when I load the script manually when I'm already succesfully logged in, only when I force it to load like this:
start /min MinecraftClient.exe USERNAME PASSWORD eu.hypixel.net "/script sstartup.txt"

This is the content of sstartup.txt right now. 
https://imgur.com/a/ZoNXJf5

Any idea? Thanks in advance.

**Comment by ORelio** [comment]
That is because you are using single command mode, which connects to the server, sends text, then closes. You'll want to use ScriptScheduler to load a script on startup and stay logged in.

**Comment by FallenSuperr** [comment]
Hold up, could you explain how this would work? I'm sorry not too familiar with MCC.

**Comment by MarcusDDS1609** [comment]
> Hold up, could you explain how this would work? I'm sorry not too familiar with MCC.

Here add me on Discord MarcusDDS#1764 and I'll explain :)

**Comment by TheSnoozer** [comment]
Checkout this example: https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini

**Comment by TheSnoozer** [comment]
Glad you could get it sorted :-)
