### ISSUE TITLE
My script doesn't run everytime.

### ISSUE THREAD

**Issue by MarcusDDS1609** [ORelio/Minecraft-Console-Client#629]
So my scripts in my ScriptScheduler run perfectly everytime. But when I lose connection and I successfully auto-relog, my script doesn't run. Is there a way around this?

**Comment by MarcusDDS1609** [comment]
`[Task]
triggerOnLogin=true
script=joinqueue.txt`

So basically, my joinqueue.txt is
`send /joinqueue jurassic
wait 60
send /home villagers
`
and it works fine, but if I autorelog back, it won't work.

**Comment by Nafana** [comment]
`serverlogin_done` is never reset to false in ScriptScheduler after a player is disconnected. A proposed solution is to override `OnDisconnect()` and set the value back to false.

```cs
public class ScriptScheduler : ChatBot 
{
    ...
    public override bool OnDisconnect(DisconnectReason reason, string message)
    {
        serverlogin_done = false;
        return false;
    }

...
```

**Comment by ORelio** [comment]
Thanks @Nafana for finding that. Indeed, initially ChatBots were not suspended on server relog, so resetting the value on disconnect was not needed. Added your change in the Bot 👍
@MarcusDDS1609 Please confirm that it works on your side 🙂
