### ISSUE TITLE
unusual chat formats problem

### ISSUE THREAD

**Issue by Gieraaa** [ORelio/Minecraft-Console-Client#633]
Hello,
I am playing on the server with private messages format: 
(@ Player » ja)
The problem is, that I can't "code" '(' and ')' characters. Can anyone help me with that, or give the line with that case, Please?

**Comment by ORelio** [comment]
Use \( to match the parenthesis character.

**Comment by TheSnoozer** [comment]
Since this question was answered I'm assuming you got this to work. As a result I'm going ahead and close this issue. If you still got a problem with this, please reopen this issue. If you got any other question or problem please open a new issue.
