### ISSUE TITLE
Login issues. 

### ISSUE THREAD

**Issue by dmnchild** [ORelio/Minecraft-Console-Client#634]
So this is my first time trying this out. I was able to find the new exe and actually login an alt on a vps. 

I tried to login a second, and I got the "Minecraft Login failed : Incorrect password, blacklisted IP or too many logins."

I searched and searched since yesterday trying many things, but there isnt much to go on. I tried doing the login from another IP (worked fine on home IP) and then tried again (on vps), no dice. I figured maybe they just banned that IP from logging in, but when I did a vpn to the server the MCC is hosted on, and logged in using my game, it worked fine. 

Any help, or tutorial im missing on the setup would be greatly appreciated.

Edit: I forgot to mention that the server reboot, and I was unable to login with the one i had working first try. Same error. That one was cached in the SessionCache.ini.

I tried on new vps/IP, same right out the gate.

**Comment by ORelio** [comment]
Mojang limits login attempts per IP addresses and providers. See #590 and #567.

**Comment by dmnchild** [comment]
Looking at those it seems I should be login after some time. It also seems to imply its an account or at least IP ban from logging in. As ive said, I can login if I vpn to the server and use its IP. On the new VPS I cant login with the app, but can with VPN. Nothing has been logged in from that IP except the vpn method. 

I get that this is a common issue that seems to have been fixed, but nothing i do seems to allow me to use the MCC to get in. Ive spent since yesterday reading other peoples with same problems and what they did to fix, none of which are working.

**Comment by ORelio** [comment]
Do not confuse login and session refresh. If you are already signed in in your Minecraft client, you can more easily "login" because the launcher will reuse your cached session, thus only needing a session token refresh. You can login using the client on your PC, then upload `SessionCache.ini` to your VPN. Mojang is usually more lenient on session token refreshes so you VPS should be able to use an already cached session.

**Comment by dmnchild** [comment]
Ohh, I see. I shall try that. That being said, there wa a session added to the sessioncache.ini when i logged in the first time, and then was unable to log back in. I will try to play around with getting it running locally and uploading. hoping to get this working as it seems great when it works! :P

**Comment by dmnchild** [comment]
Seems weird how it blacklists. Is there files i need to delete to get the existing folder to reconnect? I was able to run the mcc from my local ip, upload the session id, soon as i logged in from vpn they connected fine. I disconnected one to try something, and it got blacklisted.  I tried again from mcc on local, and it was blacklisted. But, i can login fine using the actual minecraft game, and via vpn on the same IP that the mcc got blacklisted on. Sorry if this is 101, but having not used this before just trying to get how to use it effectively.

**Comment by dmnchild** [comment]
Is there any information in how it blocks? I logged in locally but using vpn to the server i have the MCC running on. It worked fine with real minecraft game. When i went to log back in to mcc on the vps, it was blacklisted. till connected to the vpn, i was able to login using the client. I was unable to login using MCC locally using vpn, or on home isp. (but both fine using actual minecraft game. 

Im just trying to figure out the easiest/fastest way to reset and get them back online again.
