### ISSUE TITLE
Wait doesn't work

### ISSUE THREAD

**Issue by FallenSuperr** [ORelio/Minecraft-Console-Client#635]
Hi,

Wait doens't seem to be working properly.
I want to do:

wait 5
/command
wait 5
/command
wait 5 
/command

etc.. but the problem is that it only counts the "wait" at the start and just ignores it in the rest of the file.

Any idea?

**Comment by TheSnoozer** [comment]
When you want to send commands you'd need to say ``/send /command``
```
wait 50
send /command
```

Example:
```
wait 50
send /server servername
```

See also https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config
```
- send <text> : send a message or a command to the server
- wait <time> : wait X ticks (10 ticks = ~1 second. Only for scripts)
```

**Comment by FallenSuperr** [comment]
Thanks a lot man, didn't know it counted in ticks :/

**Comment by TheSnoozer** [comment]
No worries, glad you could get it working :-)
If you still have an issue with this particular problem, please feel free to reopen this issue. If you bumb into any other problem, please open a new issue :-)
