### ISSUE TITLE
Relogging with AutoRelog ignores triggerOnLogin flag

### ISSUE THREAD

**Issue by hub23** [ORelio/Minecraft-Console-Client#636]
After reconnecting with the AutoRelog feature, tasks with triggerOnLogin flag are not executed.

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting your issue.
As of now, this is an already known issue https://github.com/ORelio/Minecraft-Console-Client/issues/427 / https://github.com/ORelio/Minecraft-Console-Client/issues/629 and hence I'll close this as duplicate. If you have any other issues, please feel free to open a new one.
