### ISSUE TITLE
Script Issues on PI

### ISSUE THREAD

**Issue by SoundWreaking** [ORelio/Minecraft-Console-Client#637]
Hello everyone, 
I had some hard time getting the right mono version, but someone helped me. Im not sure how to describe my problem, Script dont work thats one thing, the second thing is that the bot is not reconnecting after getting kicked for being afk (5min). I have a kickmessages.txt I checked the names and file endings, but its still not working. I hope that @ORelio  ## can help because hes the creator of this and knows the most I would guess. 

(That guy that helped me lives -9h from my time, so we cant chat a lot) # #

**Comment by ORelio** [comment]
Make sure you are invoking MCC from the correct folder, i.e:
````bash
cd /dir/containing/mcc
mono MinecraftClient.exe
````
instead of:
````bash
mono /full/path/to/MinecraftClient.exe
````
Also do not hesitate to set `debugmessages=true` in your main INI file, that may give you some hints.

**Comment by SoundWreaking** [comment]
I always start it with the first option (because I only know it that way). Okay I turned on debugmessages. Could you maybe add me on Discord so I can just screen share the problem? (Soundz__#9288)

**Comment by AGuyNamedJens** [comment]
Can you tell me how to get mono 4.2? Im stuck on mono 6.4 and after trying alot of stuff i cant even sudo apt-update anymore..

**Comment by r3spawned** [comment]
> 
> 
> Hello everyone,
> I had some hard time getting the right mono version, but someone helped me. Im not sure how to describe my problem, Script dont work thats one thing, the second thing is that the bot is not reconnecting after getting kicked for being afk (5min). I have a kickmessages.txt I checked the names and file endings, but its still not working. I hope that @ORelio ## can help because hes the creator of this and knows the most I would guess.
> 
> (That guy that helped me lives -9h from my time, so we cant chat a lot) # #

Hi,

Which mono version did you use in them end?  I've tried my best to install version 4 - 4.2, and it keeps on installing 4.6, even If i point the repo to earlier versions.
