### ISSUE TITLE
>Bot isn't replying to me.

### ISSUE THREAD

**Issue by xNinurtax** [ORelio/Minecraft-Console-Client#639]
Hello, 
 my bot isn't respondng with the matches in private chat and also not in global chat.
This is how my global and private chat looks like.

Global: http://prntscr.com/miwj1d
Private: http://prntscr.com/miwixx

Note: I am xNinurtax.

() <- means, that there is nothing around it.
Global chat would be : [Level] [Faction\ or no faction(empty]  (Rank\or No rank) (My Name): (Message)
Private chat would be: [Server] (name) -> [Server] (name):(message)

I hope you can help me

**Comment by ORelio** [comment]
Your server use custom chat format that MCC cannot understand. See #579 on how to define custom chat formats in your configuration file.

**Comment by TheSnoozer** [comment]
Closing as answered. Feel free to reopen if you still have an issue with this specific problem. Otherwise please open a new issue.
