### ISSUE TITLE
tasks file and script check command not working

### ISSUE THREAD

**Issue by odinmartini** [ORelio/Minecraft-Console-Client#640]
https://gyazo.com/e2f08d799a460d3ee0a9447ee11d1432

It also doesn't detect a tasks.ini file so it never queues the script check command. Even when it does it says script check isn't a command.

**Comment by ORelio** [comment]
You are using AntiAFK which only sends text to the server. There is no "/script" server-side. Use ScriptScheduler instead if you wish to run scripts inside MCC.
