### ISSUE TITLE
Match.ini and auto tp not working

### ISSUE THREAD

**Issue by HTMLfan22** [ORelio/Minecraft-Console-Client#641]
Hello,

I am having troubles with my bots not auto accepting my tp request and they also are not executing any actions from matches.ini, i used the example where it replies to you saying hi and it logged the message hi but never completed the action of replying with hello user. I have double and triple checked my regex so at this point i have no clue what the problem may be.

https://regex101.com/r/CMNzCC/1
https://regex101.com/r/e7Ph7I/1
https://imgur.com/a/YImEtst

**Comment by ORelio** [comment]
Your regexes should only producs 2 matches:
 - Match 1: Username
 - Match 2: Message

... or at least, put the correct data in matches 1 and 2.

https://regex101.com/r/CMNzCC/2
https://regex101.com/r/e7Ph7I/2

**Comment by HTMLfan22** [comment]
I added the new regex but im still having the issue of it not completing any action other than actionother.

`[Match]
match=hi
action=send hi, $u!
actionprivate=send /tell $u Hello!
actionother=log detected "hi" message

[Match]
match=tpyes
action=send /tpyes
actionother=log detected "tpyes" message

[Match]
match=coop
action=send /is coop $u
actionother=log detected "coop" message

[Match]
match=accept
action=send /is accept
actionother=log detected "accept" message`

Also, it is still not auto accepting tp requests even tho i have it enabled and my name is in the botowners list.

**Comment by ORelio** [comment]
Maybe an issue with the test string, try using ChatLog to dump some chat lines then copy and paste into regex101 test string field instead of typing manually.

**Comment by HTMLfan22** [comment]
I have figured out that it was not an issue with the regex but an issue with the fact that I had builtins enabled, now the auto tp accept is working and I just have to fine tune the match commands.

Thank you for your help.
