### ISSUE TITLE
How to implement packets

### ISSUE THREAD

**Issue by 97sN** [ORelio/Minecraft-Console-Client#642]
I've been scrolling through the repository, and I've seen a lot of answers concerning the implementation of packets. I've been scrolling through the Mapping and TcpClient class, but so far haven't found a good example of how to do it. Any assistance would be great, thanks!

**Comment by TheSnoozer** [comment]
Not sure what you are looking for exactly.

But the implementation for 'newer' protocols can be found in https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#L562. There is also a Protocol Handler for older versions (e.g. 1.6 and below) and the deciding logic can be found in https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs#L104.

If you ask in general how we know how Packets look like, I'd refer to https://wiki.vg/Protocol. At least that's the place I get my info's from.

**Comment by Mhowser** [comment]
I think he wants a way to implement the sending of various packets such as
opening inventory or opening a chest, taking or dropping items, etc.
