### ISSUE TITLE
AutoRespond custom delay with script

### ISSUE THREAD

**Issue by material234** [ORelio/Minecraft-Console-Client#643]
Hello, 
Is it possible to make smth like that:
Matches.ini:
[Match]
regex=^.*Please welcome ([a-zA-Z0-9_]+).*$
action=script sayhello

And put cooldown in script before responding to this player? I mean, i know this is possible but main thing i want to put in this script is that regex to say hello to this player.

Thank you in advance for your reply, best regards.

**Comment by ORelio** [comment]
Hi,
Better late than never: You can't put a delay in AutoRespond itself, but you can add it as a first line in your script, e.g. `wait 10`.

**Comment by ORelio** [comment]
Example of delay: https://github.com/ORelio/Minecraft-Console-Client/issues/1169#issuecomment-667726831
