### ISSUE TITLE
The client can't find my kickmessages file

### ISSUE THREAD

**Issue by duckkliss** [ORelio/Minecraft-Console-Client#645]
Resolving play.breachpvp.com...
Connecting to Minecraft.net...
Retrieving Server Info...
Server version : 1.8-1.13 (protocol v404).
[MCC] [AutoRelog] File not found: kickmessages
Version is supported.
Logging in...
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server.

I get this and my text file name is kickmessages why doesn't it find that file? I also have the document in the same folder as the client and the script

**Comment by TheSnoozer** [comment]
Are you sure the file is just called `kickmessages` and not `kickmessages.txt`?

You would need to provide the full file name including the extension:
```
kickmessagesfile=kickmessages.txt
```

**Comment by duckkliss** [comment]
This is a sreenshoot of everything in folder

![skarmbild 6](https://user-images.githubusercontent.com/38917258/52928862-1da93f80-3342-11e9-9c10-a56fd2a3fa44.png)

**Comment by duckkliss** [comment]
Thank you my text file was named kickmessages.txt and by removing the .txt it worked
