### ISSUE TITLE
update files at /releases

### ISSUE THREAD

**Issue by iiLearner** [ORelio/Minecraft-Console-Client#646]
Hello,

the source code at Minecraft-Console-Client/releases is quite old, think you should update it to latest?

**Comment by Pokechu22** [comment]
I'm pretty sure the releases page isn't used nowadays; instead builds are provided on [appveyor](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and the corresponding source code is on the master branch (appveyor includes the exact commit, but it builds off of master); if you don't have git set up then you can download it as a zip [here](https://github.com/ORelio/Minecraft-Console-Client/archive/master.zip) (from the "clone or download" button on the github ui)
