### ISSUE TITLE
GUI: Add the ability to manage multiple alts within one Window

### ISSUE THREAD

**Issue by GraveyardLikesORelio** [ORelio/Minecraft-Console-Client#647]
So basically i was thinking if you could do same thing as OQ Minebot like it has one GUI opened where you see all the things you can do, and it logs all the alts and just lists them. so it doesnt open crap ton of tabs where is 1 alt, but opens 1 tab where is all the alts.
Would this be possible?

**Comment by TheSnoozer** [comment]
Yes it would be possible, but the GUI isn't a priority for this client.
