### ISSUE TITLE
Not sending command to chat.

### ISSUE THREAD

**Issue by JimmyBoyy** [ORelio/Minecraft-Console-Client#648]
So basically I figured out the whole regex thing where it detects message's from certain people.

The problem I can't seem to solve is that my console client is sending certain command to the server, but the server is not executing these commands. Is this server based?

**Comment by ipadalert** [comment]
Make sure you are respawned with /respawn or sending commands will not work.

**Comment by JimmyBoyy** [comment]
@ipadalert The alt is respawned...

**Comment by TheSnoozer** [comment]
Can you provide the set of commands that are not being executed?

Just for full context you'd need to say ``send /command``.

Example:
```
send /joinqueue jurassic
wait 60
send /home villagers
```
Should work fine. if the server still does not execute the command it could well be related that the server has an  "anti-cheat" that checks what client you use.
By default the console client tells the server it is a console client (the option `brandinfo` inside your `MinecraftClient.ini`).

set it to
```
brandinfo=vanilla
```
and try again (that's the brand the is sent by the default client - see https://wiki.vg/Plugin_channels#minecraft:brand)

**Comment by TheSnoozer** [comment]
I'm closing this since it was answered and I'm assuming it could be resolved. if you are still stuck with this, feel free to reopen. If you get stuck with any other issue, please open a new one.
