### ISSUE TITLE
I Can't Find The Right Config File to Allow Movement.

### ISSUE THREAD

**Issue by xTealdragonx** [ORelio/Minecraft-Console-Client#649]
Whenever I try to use /move it says "Please enable terrainandmovements in config to use this command." I don't know how/where to do this.

**Comment by TheSnoozer** [comment]
Either in the folder where you launch the consoleclient from, or directly inside where the exe is stored there should be a `MinecraftClient.ini`.


This file should have a line like `terrainandmovements=false`. Set this to `terrainandmovements=true` and save the file, to enable terrainandmovements.

**Comment by xTealdragonx** [comment]
Ty! it works.
