### ISSUE TITLE
222;3R error

### ISSUE THREAD

**Issue by xNightmare** [ORelio/Minecraft-Console-Client#650]
This server im playing on restarts quite often so I use the auto reconnect feature. Although every time it restarts my Ubuntu terminal displays 222;3R. By pressing enter I have to manually start the client again, sorry for lack of screenshots etc (my first post)

**Comment by TheSnoozer** [comment]
Hi,
thanks for reporting. Seems to be related to https://github.com/ORelio/Minecraft-Console-Client/issues/543 and essentially boils down to the way Mono is handling input. Not sure how to troubleshoot/fix this :/

**Comment by ORelio** [comment]
Closing this issue in favor of #543
