### ISSUE TITLE
Console client Raspberry PI 3

### ISSUE THREAD

**Issue by AGuyNamedJens** [ORelio/Minecraft-Console-Client#651]
This client doesnt work on my raspberry PI, Whenever its in the hub of the server it wont do any bots..

No auto connect to skyblock, no auto messages...
Only does this in the skyblock server but when the skyblock reboots/client reconnects to the server, it won't work because its in the HUB again.. Any fix?

Everything is on, tasks, anti afk etc.. It just doesnt work in the server's HUB..  Any bypass to make my alt auto join to skyblock WHENEVER it joins the hub? Theres no chat messages either

Only XP Bar shows "Click with your compass to select a server!" And i haven't seen a feature to make my alt join skyblock if that xp bar message pops up..

**Comment by TheSnoozer** [comment]
``Click the compass`` - sounds like you need to right click a compass and interact with something? How do you join a server?

If you can't join via command (e.g. ``/send /server skyblock``) I guess you need to wait for #205 / #183

**Comment by AGuyNamedJens** [comment]
No. You get it wrong

On my PC those commands work fine

Its just the entire anti afk, autorespond, tasks wont work on the hub

So i decided to throw the same files on my vps and it does work there...


I still want to host it on my pi tho..

**Comment by CarbonNeuron** [comment]
I've ran console client on pi before. And while it's possible, it's not very ... Efficient. Usually running 1-2 alts is enough to make the raspberry pi overheat.

**Comment by AGuyNamedJens** [comment]
> I've ran console client on pi before. And while it's possible, it's not very ... Efficient. Usually running 1-2 alts is enough to make the raspberry pi overheat.

lol. im running it on a VPS now anyways

the fact that i only own 1 minecraft account, which literally didnt work on my pi is just sad
