### ISSUE TITLE
Frequent connection loss lately

### ISSUE THREAD

**Issue by xthrane** [ORelio/Minecraft-Console-Client#652]
Hello.
I have been running the CC for a while now, and everything went pretty smoothly.
However, lately the silent disconnects has been occurring more often.
I'm running about 5 alts on a Virtual Machine at Microsoft Azure.
The way I run the alts is through a batch file that opens 5 instances, logging in on different alts. After only a couple of minutes, some of the alts loses connection.
I can also see when I remote control the VM, that the server's chat is rendering extremely slowly. 

Is there anything I can do?
The Virtual Machine has 1 GB of ram, so I do not believe that should be the problem?

The alts are all AFK'ing at a Pig Spawner-grinder each, so could the heavy amount of spawners be the problem?

**Comment by AGuyNamedJens** [comment]
lol same issue is with mine .-.
but instead its just my only minecraft account on a minecraft server, and the console doesn't reconnect to the server either. it restarts but does NOT do /server skyblock by itself.. (not even after starting MCC for the first time) no one responded to my issue yet ;/

**Comment by ORelio** [comment]
Silent disconnections should be resolved as per #802. Please try out the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
