### ISSUE TITLE
Multiple Matches?

### ISSUE THREAD

**Issue by harvo900** [ORelio/Minecraft-Console-Client#655]
Im messing around with the matches.ini but I noticed I could only make 1 match, If I make 2 or more the bot doesn't reply to anything, is there any way I can have more than one matches in the same config? So it could look like this?
https://i.nodemc.co.uk/Dujtie.png

**Comment by TheSnoozer** [comment]
Hi,
you can configure multiple matches.
Each match needs to start with `[Match]`.

For a full example see https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini

**Comment by harvo900** [comment]
Ty so much <3

**Comment by TheSnoozer** [comment]
No problem. Feel free to reopen if you have any other question related to this. Otherwise please open a new issue.
