### ISSUE TITLE
Water not pushing player. 

### ISSUE THREAD

**Issue by Zxpphire** [ORelio/Minecraft-Console-Client#656]
I have terrain and movements on and I make the bot move down towards my afk pool. When it’s inside, the water won’t push it. I am assuming this is because fly on the server is enabled and you can’t be pushed while you are flying. Is there a way for me to turn off flying such as how you do in a normal game, by double tapping space bar.

**Comment by Mhowser** [comment]
Did you try typing /fly or /send /fly?

**Comment by Zxpphire** [comment]
Yes, the water still won’t push me

**Comment by Mhowser** [comment]
What version is the server? If it's 1.13+ terrainmovements is effectively
disabled due to the world format not being "understandable" to the console
client.

**Comment by Zxpphire** [comment]
Version runs on 1.8.9, i can do /move perfectly fine

**Comment by TheSnoozer** [comment]
Duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/206

**Comment by CADonAFK** [comment]
I need help I have a afk bot but it does not move

**Comment by ORelio** [comment]
@CADonAFK: See https://github.com/MCCTeam/Minecraft-Console-Client/issues/206#issuecomment-251961828

**Comment by CADonAFK** [comment]
Huh can you just tell me the answer pls

**Comment by CADonAFK** [comment]
Oh I still can’t type /move in chat it won’t let me it has a error

**Comment by ORelio** [comment]
Water will not move the player. Use another AFK mechanism. Please open your own issue if you have a different error.

**Comment by CADonAFK** [comment]
What anothe afk thing should I use for the afk boy
