### ISSUE TITLE
Failed to ping this ip

### ISSUE THREAD

**Issue by iiLearner** [ORelio/Minecraft-Console-Client#657]
https://i.imgur.com/w4PlfiY.png

Hello, since yesterday I'm having this issue where the client fails to ping an IP and stops working, the server is actually up and working so I can't figure the reason.

**Comment by iiLearner** [comment]
Update: It works fine if I set the right version into the configuration file (but I dont want to...)

**Comment by TheSnoozer** [comment]
Hi, thanks for reporting your issue.
I have experienced this a couple of times and would blame it on the servers (https://github.com/ORelio/Minecraft-Console-Client/issues/489#issuecomment-439757113). Essentially from my understanding the server claims to support versions which are in fact not supported. This will render the `mcversion=auto` useless and results in the `Failed to ping this ip` problems.

I would claim it's not a client issue and hence I'll close it. if you have any questions feel free to reopen this issue.
