### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by GLENNSCHWEI** [ORelio/Minecraft-Console-Client#659]
Hi! I'm new to coding and I was wondering if there was anyone that could help me figure out how to write a script to make it so that it would /sell all every minute if anyone could help me that would be wonderful!

**Comment by GLENNSCHWEI** [comment]
I figured out how to make it so that it will pick up the items but I can't get it to auto sell for me

**Comment by TheSnoozer** [comment]
Can you autosell with a commend or need to right click a sign (or similar)?

What about sharing the script you came up? Pretty confident a lot of people bump into the same problem...

**Comment by TheSnoozer** [comment]
Just for reference:
You can send an command automatically with `ScriptScheduler` or `AutoRespond`

> # via `ScriptScheduler`
> 
> MinecraftClient.ini
> 
> ```
> [ScriptScheduler]
> enabled=true
> tasksfile=tasks.ini
> ```
> 
> tasks.ini
> 
> ```
> ﻿[Task]
> triggerOnInterval=true
> triggerOnFirstLogin=true
> timeInterval=60
> script=joinyourserver.txt
> ```
> 
> joinyourserver.txt
> 
> ```
> send /server [REALM]
> ```
> 
> # via `AutoRespond`
> 
> MinecraftClient.ini
> 
> ```
> [AutoRespond]
> enabled=true
> matchesfile=matches.ini
> ```
> 
> matches.ini
> 
> ```
> [Match]
> match=--------------------[Hub]--------------------
> actionother=script joinyourserver
> # or simply actionother=send /server [REALM]
> ```

Since there was no follow up, I'm assuming that this provides enough guidance to get this working. If you still get stuck, feel free to reopen this. if you have any other issue, feel free to open a new one.
