### ISSUE TITLE
Spam Protection - How to prevent incoming spam from causing my bot to get kicked?

### ISSUE THREAD

**Issue by Pure8eat** [ORelio/Minecraft-Console-Client#661]
My bot uses the matches.ini file to reply to private messages with a script containing 3 /r lines every time a person types in a certain phrase I've programmed it to recognise. If someone spams my bot with this phrase, however, the bot will reply every time, and will retrigger until it eventually gets kicked from the server for spam. Is there any way of adding a cooldown/interrupt, so that the /r script is only seen once, or after a certain time delay by the spammer?

**Comment by ipadalert** [comment]
Put `wait [time]` before you make it send whatever you want it to send. The time goes by ticks, 10 ticks = 1 second.

**Comment by Pure8eat** [comment]
I do have a wait before the script initially starts, however if the match is received multiple times within a short time span, such as a player spamming the account, the script repeats every single time. So while there will be an initial delay, it will still run the script the same amount of times as the spammer send their message. I'm trying to find a solution that will work to send it once, either after the first message and then after a cooldown, or after the very last message is sent, such as the script has to wait like 5 seconds with no repeats in order to run the script.

**Comment by ipadalert** [comment]
In your Minecraft.ini there is a section to have message delay. You can put that to however long to prevent spam.

**Comment by CarbonNeuron** [comment]
Get better friends who won't spam your bot.

**Comment by ORelio** [comment]
Currently, no builtin MCC feature can help you, however, you can maintain in your script or ChatBot a Dictionary object with UUID or Username as key, and DateTime as value, to keep track of last response per player and ignore a message if the cooldown for that player was not reached. If doing so in a script, you will need to save the dictionary using SetVar and load it back using GetVar.

**Comment by xXjojaXx** [comment]
Pls add this function. Its very important to me and other players

**Comment by ORelio** [comment]
Actually there was already a cooldown mechanism for bots but not properly handled everywhere. Should be the case now.
