### ISSUE TITLE
Unable to run in anything other than offline mode.

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#662]
Hi.

So upon starting MCC for 1.13.2, I'm only able to run the client in offline mode. I haven't been able to find what settings I need to change in order to fix this. I've tried inputting my login info in the settings.cs file, adding my old accounts.txt and MinecraftClient.ini files to the working directory, and none of that has seemed to work. I'm not sure what I'm missing here. 

Also, upon starting the client, it automatically tries to connect to a server hosted on localhost, but I don't have a server running on my network. 

Any help would be much appreciated, thanks.

**Comment by Pokechu22** [comment]
The default arguments given to the program when launching in debug mode are `TestBot` `-` `localhost`:

https://github.com/ORelio/Minecraft-Console-Client/blob/950fc42118c3e877668f79b9b30fc7aacb5c3c2e/MinecraftClient/MinecraftClient.csproj.user#L4

You'll need to change that in your IDE configuration (it should be _somewhere_ in visual studio, but I don't recall exactly where); just setting it to nothing will give you the default behavior.  (If you compile it, then manually run it, the arguments in VS don't apply).

**Comment by EchoesNetwork** [comment]
Hey thanks so much! That helped a lot. It's actually working now.
