### ISSUE TITLE
Running on Ubuntu 18.04

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#664]
Hi,

I recently compiled the latest version of MCC from Visual Studio and it worked fine on my main computer, which runs Windows 10. Now, after moving it to a VPS running Ubuntu 18.04, I'm running into an error every time I try to execute setup.exe or MinecraftClient.application with mono or wine:

`Cannot open assembly 'setup.exe': File does not contain a valid CIL image.`]

The same error is produced for the file MinecraftClient.assembly. 

A quick google search said this is usually a problem with programs that haven't been compiled. So I tried to compile it with mcs, and I received this error:

`MinecraftClient.application(1,0): error CS1525: Unexpected symbol <'
MinecraftClient.application(11,76): error CS1009: Unrecognized escape sequence\M'
MinecraftClient.application(11,100): error CS1009: Unrecognized escape sequence \M'
MinecraftClient.application(22,39): error CS1009: Unrecognized escape sequence\s'
MinecraftClient.application(22,255+): error CS1009: Unrecognized escape sequence `\s'Compilation failed: 5 error(s), 0 warnings`

(this happens when I try to compile MinecraftClient.application, when I attempt to compile setup.exe, this error is produced):

`error CS2015: Source file 'setup.exe' is a binary file and not a text file`

Any help would be much appreciated, thanks a lot!

**Comment by TheSnoozer** [comment]
As far as I can recall `SHIFT+CTRL+B` should recompile the solution in visual studio and produce an exe-file. If you don't have any modifications you can also grab the latest build (exe-file) from https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts. The detailed build instructions (via command-line) can be obtained from the log residing in https://ci.appveyor.com/project/ORelio/minecraft-console-client.

In all honesty I'm actually not sure if `mcs` is the right compiler to use (I'm certainly not a C# expert). Based on https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reference?view=vs-2019 uses MSBuild. Furthermore the current automated build system (https://ci.appveyor.com/project/ORelio/minecraft-console-client) uses msbuild. So I would recommend using msbuild.

Note that msbuild should also work on linux (mono-devel needs to be installed AFAIK).
Use roughly the following to build:
```
msbuild MinecraftClient.sln /t:build /p:Configuration=Release /p:Platform="x86" /p:TargetFrameworkVersion="v4.0" /verbosity:minimal

mono ./MinecraftClient/bin/Release/MinecraftClient.exe
```
or for debug:
```
msbuild MinecraftClient.sln /t:build /p:Configuration=Debug /p:Platform="x86" /p:TargetFrameworkVersion="v4.0" /verbosity:minimal

mono ./MinecraftClient/bin/Debug/MinecraftClient.exe
```

**Comment by TheSnoozer** [comment]
Closing as answered. Feel free to reopen if you still have any questions.
