### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by SummaryUSSS** [ORelio/Minecraft-Console-Client#665]
Anytime I log in on my console client 3/5 windows close and when ever the auto relog comes around they all close. Ive reinstalled console client many times, ive gone through this website trying to find a fix many times but I dont understand anything. Please help @ORelio

**Comment by TheSnoozer** [comment]
Any error messages?

**Comment by SummaryUSSS** [comment]
nope, just closes the windows

**Comment by TheSnoozer** [comment]
The ` ERROR: The process "MinecraftClient.exe" not found.` sounds like an general issue in launching the client and is not specifically related to the client itself.

How are you trying to launch the client?

**Comment by SummaryUSSS** [comment]
I click on the .bat file i made

**Comment by TheSnoozer** [comment]
How do you attempt to launch the client from the batch file?
This doesn't sound like a problem in the client itself. It sounds that something performing in the batch file is not working (it can not even find the `MinecraftClient.exe`).

Maybe try
```
start /min MinecraftClient.exe USERNAME PASSWORD SERVER-IP
timeout 5

start /min MinecraftClient.exe USERNAME PASSWORD SERVER-IP
timeout 5

start /min MinecraftClient.exe USERNAME PASSWORD SERVER-IP
timeout 5
```
as bat file and place it in the same folder where the `MinecraftClient.exe``is residing.

**Comment by SummaryUSSS** [comment]
@TheSnoozer do you have a discord I could talk to you on? Because on here it takes the both of us days to answer and I would love to get this all situated now

**Comment by SummaryUSSS** [comment]
also your solution didnt work, 4/6 windows closed

**Comment by SummaryUSSS** [comment]
![image](https://user-images.githubusercontent.com/48393647/55033234-a752c980-4fe0-11e9-9ed0-9ed5e5b83316.png)
