### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [ORelio/Minecraft-Console-Client#666]
The crash is Dutch. http://prntscr.com/mwgxk5

I'm able to join the other server but when I do /factions it just throws that error and closes the program

**Comment by TheSnoozer** [comment]
I'm closing this as duplicate of https://github.com/ORelio/Minecraft-Console-Client/issues/379 since I'm actually not sure if there is any benefit of keeping the same set of issues around. Sadly not sure what causes it :/
