### ISSUE TITLE
Is there a way to make console clients print sand?

### ISSUE THREAD

**Issue by Alexandra321** [ORelio/Minecraft-Console-Client#668]
Hey, so i was wondering if there's any way to make the console client alts print sand for example cannons?

**Comment by RacistTim** [comment]
Would be nice if they could place a block, I don't know if ORelio's Console Client can do it though.

**Comment by TheSnoozer** [comment]
Technically it is possible, but it is currently not implemented.

Related to https://github.com/ORelio/Minecraft-Console-Client/issues/397

**Comment by Tavisboeh** [comment]
There is away and it have been done by multiple factions

**Comment by CarbonNeuron** [comment]
They are most likely using a program called OQ.Minebot. that has the ability to print sand, full movement. It has plugin support available.

**Comment by ORelio** [comment]
Well, it is likely that a paid program with a dedicated dev will have more support and features. Here we're far from placing blocks 😅

**Comment by CarbonNeuron** [comment]
It is. But it is also illegal on most servers, meaning it'll get you banned.

**Comment by ORelio** [comment]
As long as it is no MCC code improved disregarding CDDL licence requirements, it's fine :wink:

**Comment by CarbonNeuron** [comment]
Ya know. I don't know. It may be a coincidence that both projects are written in c#. Sometimes I wonder if it is based off console client, but can't really look at the source cuz of obfuscation. Maybe you could talk to qubes, the dev of minebot, yourself

**Comment by Tavisboeh** [comment]
> They are most likely using a program called OQ.Minebot. that has the ability to print sand, full movement. It has plugin support available.

Naa they aren't. with my knowledge with mineflayer recoded you are able to make controllable sand alt client I have code for that ;F if you are good enough coder cuz I got one xd

**Comment by vkorn** [comment]
Ok, I was working towards turning on my farms without me flying there, or logging in into bot to eat, so I did a simple inventory management/block placing (interaction with levers, buttons etc included). 

Everything is exposed through single helper https://github.com/vkorn/Minecraft-Console-Client/blob/70a12dab64c139f290b914623e1299d539cc031c/MinecraftClient/Character/Player.cs 

So far very dirty, but you can adjust to master quite easily, I think.  

```
>/inspect -1806 21 1147
04:45:56 MCC: Material: air
>/place -1806 21 1147
04:45:59 Can't place block at -1806:21:1147 : empty handed
04:45:59 MCC: Done
>/status
Health: 20
Food:   20
Quick bar:
1 (36): x02 sand
3 (38): x01 stone
*9 (44): x19 potato
Inventory:
9: x01 redstone_ore
20: x09 cooked_beef
35: x02 stone
Equipped:
>/hold 1
04:46:17 MCC: Done
>/place -1806 21 1147
04:46:20 MCC: Done
>/inspect -1806 21 1147
04:46:30 MCC: Material: sand
```

**Comment by CarbonNeuron** [comment]
Holy cow. Vkorn is a god. He did the one thing that was requested since day one. Amazing work, vkorn.

**Comment by ORelio** [comment]
Thanks @vkorn, seems great! Feel free to send this as a PR once you feel comfortable with it 👍

**Comment by vkorn** [comment]
@ORelio we have slightly different approach right now for handling things, I believe @TheSnoozer should be able to easily back-merge everything since he is familiar with the baseline you're using and was looking into my changes before.

**Comment by TheSnoozer** [comment]
Sadly I don't think it's not so easily back-mergeable. In a nutshell I would say that we all three took a different approach in changing around things. IMHO my changes essentially kicked off the idea of vkorn which meant to split up everything into separated class. Even though it was based on my initial idea it took a different approach and rendered my commits irrelevant (thus I ditched my idea in the second merge commit).

**Comment by ORelio** [comment]
@TheSnoozer : Now that 1.14 is handled, would it make your job easier if we freeze the `master` branch for a few days or even a few weeks so that you have all the needed time to add @vkorn's additions?

**Comment by ORelio** [comment]
Should be possible now as placing block is handled now.
