### ISSUE TITLE
Can't login with BungeeCord

### ISSUE THREAD

**Issue by CGsama** [ORelio/Minecraft-Console-Client#669]
Hi,

I have a spigot server running in 1.13, and a BungeeCord proxy using latest BC.
When I try to connect to my BC server, it returns a error as follow:

`Console Client for MC 1.4.6 to 1.13.2 - v1.13.2 - By ORelio & Contributors
Login : <******>
Password : <******>                                                                                                     You chose to run in offline mode.
Server IP : <******>
Resolving <******>...
Retrieving Server Info...
Server version : BungeeCord 1.8.x-1.13.x (protocol v404).
Version is supported.
Logging in...
Server is in offline mode.
Server was successfully joined.
Type '/quit' to leave the server.
Disconnected by Server :
Kicked whilst connecting to lobby: Outdated server! I'm still on 1.13
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
`

And on BC side it gives this message:

`disconnected with: §cKicked whilst connecting to lobby: §fOutdated server! I'm still on 1.13`

Thanks

**Comment by CGsama** [comment]
The issue can be resolved by using an older version of BungeeCord server.
I think maybe can add a cmd argument to specify the protocol version.

**Comment by CarbonNeuron** [comment]
Are you talking about a way to bypass for the bungeecord server? Or the Minecraft console client?

**Comment by ORelio** [comment]
This cannot be fixed, as both BungeeCord and MCC can handle multiple Minecraft versions. MCC does not declare its own version, so BungeeCord defaults to the highest version it can handle. The only workaround is forcing a version in MCC, or using a BungeeCord version with the correct highest Minecraft version.
