### ISSUE TITLE
[Question] How do I get multiple bots on a server at the same time and make them all send a command?

### ISSUE THREAD

**Issue by ARandomSqueaker** [ORelio/Minecraft-Console-Client#673]
How do I get multiple bots on a server at the same time and make them all send a command?

I'm tryna get a bunch of bots on a server and make them all pay me.

**Comment by TheSnoozer** [comment]
Launch a client for each bot.

You can send an command automatically with `ScriptScheduler` or `AutoRespond`

> # via `ScriptScheduler`
> 
> MinecraftClient.ini
> 
> ```
> [ScriptScheduler]
> enabled=true
> tasksfile=tasks.ini
> ```
> 
> tasks.ini
> 
> ```
> ﻿[Task]
> triggerOnInterval=true
> triggerOnFirstLogin=true
> timeInterval=60
> script=joinyourserver.txt
> ```
> 
> joinyourserver.txt
> 
> ```
> send /server [REALM]
> ```
> 
> # via `AutoRespond`
> 
> MinecraftClient.ini
> 
> ```
> [AutoRespond]
> enabled=true
> matchesfile=matches.ini
> ```
> 
> matches.ini
> 
> ```
> [Match]
> match=--------------------[Hub]--------------------
> actionother=script joinyourserver
> # or simply actionother=send /server [REALM]
> ```

**Comment by ARandomSqueaker** [comment]
how do i make the bot drop something?

**Comment by TheSnoozer** [comment]
Inventory is currently not implemented (see https://github.com/ORelio/Minecraft-Console-Client/issues/205)
