### ISSUE TITLE
System.OverflowException: VarInt too big

### ISSUE THREAD

**Issue by SweepingLoutus** [ORelio/Minecraft-Console-Client#674]
When my console starts and connects to the server and on join does the command /server skyblock  as it does so it gives out this error that I don't know how to fix. https://gyazo.com/dd3b72210e339255dcdb1ad8f0a1d720

**Comment by TheSnoozer** [comment]
hi thanks for reporting your issue.
There are some issues that are related to that (e.g. https://github.com/ORelio/Minecraft-Console-Client/issues/379).

Sadly so far I never was able to reproduce this specific problem.
To what server are you connecting?

**Comment by SweepingLoutus** [comment]
The server was skycade. I have two different accounts which arent related but have the exact same files and it was happening on one of them for sometime. But it just happened to both of them. One of them has fixed its self. Any questions please ask.

**Comment by SweepingLoutus** [comment]
Here is a pastebin of all the error and starting of it with debug messages on https://pastebin.com/Hag68LkB

**Comment by TheSnoozer** [comment]
Please change the password for your accounts immediately

**Comment by SweepingLoutus** [comment]
Erm why

**Comment by TheSnoozer** [comment]
Nevermind should be good, the log contained session information which looked like your credentials ;-)

BTW, so far i was not able to reproduce the issue. What OS are you using? Windows 10?

**Comment by SweepingLoutus** [comment]
Yep, windows 10

**Comment by SweepingLoutus** [comment]
ok so i have just tried to log an account on a vps and got this https://gyazo.com/61cedf397eaab09a19d2d254834868d2
https://pastebin.com/LHF3f9aT
This leads me to believe that it is a problem with my set up of the client.

**Comment by TheSnoozer** [comment]
Can you perhaps share your MinecraftClient.ini? Make sure to remove all credentials before :-)

**Comment by Insyder28** [comment]
Hi, I'm not really good with code and stuff, but your issue seems similar to mine, and I fixed it by logging in using the actual minecraft client and moving the character to a different position. I don't know why it worked, but it did, and maybe it will for you.

**Comment by SweepingLoutus** [comment]
Sorry for not responding for a while my internet has been playing up over the last couple of days there is my MinecraftClient.ini file https://pastebin.com/hcSFh0VB

**Comment by TNTUP** [comment]
In some areas of my server I'm getting VarInt errors https://i.qcfb.ca/20190621154838.png @ORelio

TerrainMovement is disabled and if I specify manual version, I don't know if it would solve it

**Comment by TheSnoozer** [comment]
Thanks for the report and this finally seems to give an indicator what might be wrong.

Based on the stacktrace the the client attempts to read the teleport id even if terrain is not enabled.
See:
https://github.com/ORelio/Minecraft-Console-Client/blob/e7c664648e5535a8aeae47ceadf4bb2efaffb7d5/MinecraftClient/Protocol/Handlers/Protocol18.cs#L247
