### ISSUE TITLE
Is there any way to detect who is executing a bot command?

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#676]
Hi!

Sorry if my title is misleading. I found it hard to explain what I meant in a succinct manner.
So what I'm curious about is if there's a way to see who's triggering a bot command, and if I can store that information as a variable.

Let's say in my matches.ini file I have it set so that when the bot sees someone say `!tp`, the bot will teleport itself to the player through the command `send /tp <player name>`. Sort of like how if you execute a normal Minecraft command with the selector @s, it only affects the executor of the command. 

Thanks for your help.

**Comment by TheSnoozer** [comment]
I have not tested this, so this might not work first try and needs further adjustment.

In general you could use AutoRespond with a regex and capturing groups just as shown in [sample-matches.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-matches.ini). In your case for your custom RemoteControl command you would want something like this:
````ini
[Match]
regex=^([a-zA-Z0-9]+) has requested to teleport to you$
actionprivate=send /tp $1 # ...the bot will perform /tp IGN
ownersonly=true # Set this to ensure only bot owners can get paid from your bot - needs to be configured too!
````
Not sure if you need `actionprivate` is the right action to perform, there would also be `actionPublic` and `actionOther`. Just FYI MCC can also parse the username from the chatformat. For that you must make sure that ChatFormat is properly set in your INI fileand then you could use `$u` for the username.

**Comment by EchoesNetwork** [comment]
Hey thanks so much! I'll test this out and report back with how it goes.

**Comment by TheSnoozer** [comment]
tr
