### ISSUE TITLE
How to place blocks

### ISSUE THREAD

**Issue by corkyslurp** [ORelio/Minecraft-Console-Client#677]
I am looking to have a chat-triggered block placement. As in, you msg it something, probably a randomized key, and it starts placing sand in the X Y and Z square's you tell it, I.E. "Key" P1 P2
P1 being an XYZ, and P2 being another, and it places block inbetween the 2, and as fast as it can. I would like it to be something like this: https://www.youtube.com/watch?v=PjOTToWxhzY . I would purchase his, but I want to be able to have more than 3 open at once, and his has that limit coded into it.

**Comment by TheSnoozer** [comment]
Placing blocks is currently not implemented.

See https://github.com/ORelio/Minecraft-Console-Client/issues/205 and https://github.com/ORelio/Minecraft-Console-Client/issues/183

Besides that 20$ seems to be a rip-off for that client.

Closing as duplicate.
