### ISSUE TITLE
RemoteControl with Prefix

### ISSUE THREAD

**Issue by Jadkinsa1** [ORelio/Minecraft-Console-Client#678]
Hi there, so I've been looking into this for like a week now and I still can't seem to figure out why it's not working. It works for my other alts that are also on the botowners list and they do not have prefixes. http://prntscr.com/mzs1g2
Here's my formats
private=^\[(?:\[[^ ]+\] )?([a-zA-Z0-9_]+) -> me\] (.+)$
tprequest=^(?:\[[^ ]+\] )?([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$
Here's the regex test for private: https://regex101.com/r/dBoQHF/13
and the test for tprequest: https://regex101.com/r/Nf06g6/1
Please help

**Comment by TheSnoozer** [comment]
`It works for my other alts that are also on the botowners list and they do not have prefixes. `

I'm not sure if I understand that correctly, but that sounds like that the RemoteControl works for some accounts that are part of the botowners. However for accounts that are not part of the botowners it doesn't work? Is that right, or did I misunderstood this?

**Comment by Jadkinsa1** [comment]
That's correct. On the server I use this on, only my main account has a rank, which has the prefix, and my alts do not, that's how I'm testing it.

**Comment by TheSnoozer** [comment]
For private try https://regex101.com/r/IeKkJp/1

Can you provide a screenshot when someone tps to you? Preferably one tp request from an alt with prefix and one request from an alt without prefix.

**Comment by Jadkinsa1** [comment]
https://prnt.sc/n2vph6 without
http://prntscr.com/n2wdz9 with

**Comment by Jadkinsa1** [comment]
http://prntscr.com/n2weno
http://prntscr.com/n2wezv
also two more showing some errors

**Comment by ORelio** [comment]
Did you set `builtins=false` in settings?

**Comment by 69Gamerss** [comment]
is there a way to convert names to the correct format to use names with prefixes, i have no idea how to convert it, https://gyazo.com/52a3a31dbe3d6e82e23326d58c927ed5
also there is some weird characters like ➥ instead of ? 
Thanks in general
