### ISSUE TITLE
1.13 Support

### ISSUE THREAD

**Issue by ItsYaboiiZac** [ORelio/Minecraft-Console-Client#679]
Hey i know you probobly wont reply but you're the only person who makes console clients and it would be great if there could be 1,13 support for the console client, that would be awesome

**Comment by TheSnoozer** [comment]
What exactly is not working with 1.13?
As far as I know only the terrain handling is not fully implemented. You should be able to join a server though. See https://github.com/ORelio/Minecraft-Console-Client/issues/599 and https://github.com/ORelio/Minecraft-Console-Client/issues/576

**Comment by ORelio** [comment]
1.13 should now be fully implemented in latest dev builds.
