### ISSUE TITLE
I have lots of problems

### ISSUE THREAD

**Issue by SummaryUSSS** [ORelio/Minecraft-Console-Client#680]
I just have way too many problems with this. I would love to just set up a time with someone who knows what they're doing on discord and just to run me through the process. I had it running just fine before I stopped playing minecraft and now that im playing again I just run into problem after problem. If someone would just comment their discord tag so I could talk to you about console client that would be greatly appreciated.

**Comment by Deathnight7976** [comment]
Hmm, Im not exactly an expert but Id atleast claim to know what im doing, Deathnight#2604

**Comment by TheSnoozer** [comment]
If you explain your problems in more specific I would provide further help. Just saying 'broken' doesn't want me to help.....

**Comment by TheSnoozer** [comment]
I'm closing this as part of an issue cleanup. if you can point out specific issues, feel free to open a new issue. I would further recommend that you create one issue for each of the issues you have.
