### ISSUE TITLE
/move

### ISSUE THREAD

**Issue by GDSHoopFam** [ORelio/Minecraft-Console-Client#681]
Recently been using the client console for MC on my Mac. Can't seem to use /move though to be able to move to access all my other commands I get after I move. 

here's my config: #Minecraft Console Client v1.9.0
#Startup Config File

[Main]

#General settings
#leave blank to prompt user on startup
#Use "-" as password for offline mode

login=
password=
serverip=

#Advanced settings

language=en_GB
botowners=Player1,Player2,Player3
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash #use 'none', 'slash' or 'backslash'
splitmessagedelay=2 #seconds between each part of a long message
botmessagedelay=2 #seconds to delay between message a bot makes to avoid accidental spam
mcversion=auto #use 'auto' or '1.X.X' values
brandinfo=mcc #use 'mcc','vanilla', or 'none'
chatbotlogfile= #leave empty for no logfile
privatemsgscmdname=tell #used by RemoteControl bot
showsystemmessages=true #system messages for server ops
showxpbarmessages=true #messages displayed above xp bar
terrainandmovements=true #uses more ram, cpu, bandwidth
sessioncache=memory #use 'none', 'memory' or 'disk'
accountlist=accounts.txt
serverlist=servers.txt
playerheadicon=true
exitonfailure=false
debugmessages=false
scriptcache=true
timestamps=false

[AppVars]
#yourvar=yourvalue
#can be used in some other fields as %yourvar%
#%username% and %serverip% are reserved variables.

[Proxy]
enabled=false #use 'false', 'true', or 'login' for login only
type=HTTP #Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=0.0.0.0:0000
username=
password=

[ChatFormat]
builtins=true #support for handling vanilla and common message formats
#public=^<([a-zA-Z0-9_]+)> (.+)$ #uncomment and adapt if necessary
#private=^([a-zA-Z0-9_]+) whispers to you: (.+)$ #vanilla example
#tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

#Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=false
delay=600 #10 = 1s
command=/ping

[AutoRelog]
enabled=false
delay=10
retries=3 #-1 = unlimited
kickmessagesfile=kickmessages.txt

[ChatLog]
enabled=false
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=false
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=false
tasksfile=tasks.ini

[RemoteControl]
enabled=false
autotpaccept=true
tpaccepteveryone=false

[AutoRespond]
enabled=false
matchesfile=matches.ini

**Comment by TheSnoozer** [comment]
what version is running on the server you are trying to connect to?

**Comment by GDSHoopFam** [comment]
BungeeCord 1.7.x, 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x

**Comment by TheSnoozer** [comment]
If you join with 1.13.X you'll suffer from https://github.com/ORelio/Minecraft-Console-Client/issues/576

Try set `mcversion=1.12.2` or something else, not just  `mcversion=auto` which will use the latest `1.13.X` version.

**Comment by ORelio** [comment]
All MC versions up to 1.13.2 can now use /move ; just make sure you use recent [dev builds](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). Feel free to reopen if still having issues.
