### ISSUE TITLE
Regex help.

### ISSUE THREAD

**Issue by Pure8eat** [ORelio/Minecraft-Console-Client#682]
So.
Trying to write a regex format that will match private messages from both ranked and non-ranked players.
Current formats are, non-ranked:
[playername -> me] text
Ranked:
[[Rankname] playername -> me] text

The current regex is:
private=^\[([a-zA-Z0-9_\[\]\ ]+) -> me\] (.+)$

Am I doing this right?

**Comment by Mhowser** [comment]
Your pattern wasn't made correctly.

I think I fixed it `^([[a-zA-Z0-9_[]\ ] -> me]) (.+)$`

Test it here https://regex101.com/r/ycV54B/1/

**Comment by TheSnoozer** [comment]
I'm assuming this is answered. If you can't get it to work, feel free to reopen the issue.
