### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by Final12344321** [ORelio/Minecraft-Console-Client#685]
Dear,

I downloaded the latest version so I can use it in 1.13, but I can't find the launch file anywhere. How am I able to launch the Console Client now?

Regards

**Comment by TheSnoozer** [comment]
'Can't launch' is a very broad problem. Any error log?

**Comment by Final12344321** [comment]
Well, when I donwload the files I don't even see a program I have to click to launch it. Do I have to download some other software to be able to launch the program? I've read the READ ME, but couldn't find anything.

**Comment by TheSnoozer** [comment]
This client is only one exe file and the only thing you need to get started. If you 'don't see a program' I'm not sure what you have downloaded, but I would recommend to grab the latest build from https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts. As the name of this project suggests it's a console client. On windows launch the command prompt (or cmd) and navigate in the folder where you had downloaded the client.


Note: There are plenty of youtube videos that outline on how to that.

**Comment by TheSnoozer** [comment]
I'm assuming that my response clarified things and you had been able to launch/use the client. If you still have some trouble, feel free to reopen this issue.
