### ISSUE TITLE
Auto Respond Not Detecting Private Messages

### ISSUE THREAD

**Issue by ipadalert** [ORelio/Minecraft-Console-Client#686]
Recently I have been using autorespond in private messages and it has been working fine but when switching to a new server and therefore needing a new regex in Chat Format it just stopped working. I tried to go back to the old regex I had and go back onto the other server but it still hasn't worked. I know my regexs are correct but it still will not work at all. 
Here is my chat format, match and ingame chat:
![Screen Shot 2019-03-23 at 11 49 04 AM](https://user-images.githubusercontent.com/45241936/54868318-ad874280-4d61-11e9-84ad-e519b7b256d4.png)
![Screen Shot 2019-03-23 at 11 48 47 AM](https://user-images.githubusercontent.com/45241936/54868322-aeb86f80-4d61-11e9-96e3-936e32d5693c.png)
![Screen Shot 2019-03-23 at 11 49 52 AM](https://user-images.githubusercontent.com/45241936/54868344-eaebd000-4d61-11e9-8b78-b36c2b63e0c4.png)

**Comment by TheSnoozer** [comment]
Maybe try https://regex101.com/r/l4AakA ?

**Comment by ipadalert** [comment]
It didn't work still, I think there is something with my actually console client but I don't know what.

**Comment by TheSnoozer** [comment]
my bad, the username needs to be captured as well.

either
```
private=^\[(?:\[[^\]]+\] )(ipadalert) -> me\] (.+)$
```
or
```
private=^\[\[[^\]]+\] (ipadalert) -> me\] (.*)$
```

works with
```
[Match]
regex=^(.+)$
actionprivate=log $1
```
...this time I tested it :P

**Comment by ipadalert** [comment]
I think there is something wrong with my console client because I tried both of those and they both didn't work. I guess I'll just redownload and hope for the best. Thanks for your help anyways.

**Comment by ipadalert** [comment]
Um, really weird, so it wasn't working at first I put in both formats and both didn't work. So I went into my matches document deleted it and repasted it at the top and now it works. I'm very confused on why it fixed itself but whatever its working. Thanks for your help as well.

**Comment by ipadalert** [comment]
Okay so this was entirely my fault, I'm so sorry for not noticing sooner but I have a match under it and it wasn't completed being that it was Match] regex= and so on and so it wasn't catching anything from the match before and that was the whole reason why it wasn't working. Thanks for your help in the first place and I am extremely sorry for wasting your time.

**Comment by TheSnoozer** [comment]
Not an issue, glad we could get it working :-)
