### ISSUE TITLE
Magic 8ball script not working.

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#687]
Hello! I got the idea to incorporate a magic 8 ball script into my bot, so I copy-pasted this script from somewhere on the internet and adapted it to send text into chat instead of printing the answers in the console. Whenever i attempt to run this script, however, I'm met with the error 
`System.InvalidOperationException: Unexpected symbol 'system', expecting '('.`

I'm totally new to C# so I have no idea what could be causing this. Below is the script I use, copy-pasted. 

```
//MCCScript 1.0

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace SoloLearn
{
    class Program
    {
        static void Main(string[] args)
        {
            Random num = new Random ();
            int a = num.Next(3);
            
            switch(a)
            {
                case 0:
                MCC.SendText("Yes.");
                break; 
                
                case 1:
                MCC.SendText("No.");
                break;
                
                case 2:
                MCC.SendText("Ask again later.");
                break;
            }
            
        }
    }
}
```

**Comment by TheSnoozer** [comment]
Copy and pasting random snippets from the internet might put you at risk. I'd suggest to try to understand them before simply using copy and paste....

Regardless the MCC-Scripts require a custom format and don't have a main-method.
As a starting point I'd refer to the existing examples ([here](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs), [here](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-pm-forwarder.cs)). If you need to do something more complex (let's say more besides the chat feature maybe [this](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-world-access.cs) would be  a better starting point).

**Comment by TheSnoozer** [comment]
Since an answer and some guidance was given I'm closing this as part of an issue cleanup. If you still struggle to figure this out feel free to reopen.
