### ISSUE TITLE
How would I get the bot to write a chat message to a file?

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#693]
Hi. I've been tinkering with the sample chatbot script and I'm wondering how I'd go about writing a chat message to a separate file that isn't a general log file. I had a look around the API and didn't see anything like this, but perhaps I just missed it. Any help would be appreciated. Thanks!

**Comment by TheSnoozer** [comment]
You could either use the `ChatLog` inside your `MinecraftClient.ini`.

In case you want something really sophisticated you could write a MCCScript and extend based on https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs.

Sample (untested):

```
//MCCScript 1.0

MCC.LoadBot(new ExampleBot());

//MCCScript Extensions

public class ExampleBot : ChatBot
{
    string path = "C:\YourFolderName\";
    string filename = "messages.txt"; 

    public override void Initialize()
    {
        LogToConsole("Sucessfully Initialized!");
    }

    public override void GetText(string text)
    {
        string message = "";
        string username = "";
        text = GetVerbatim(text);

       string message = String.Format("{0:yyyy-MM-dd_hh-mm-ss} {1} {2}", DateTime.Now, text, Environment.NewLine);
       File.AppendAllText(path + filename, message);

        if (IsChatMessage(text, ref message, ref username))
        {
            LogToConsole("Public message from " + username + ": " + message);
        }
        else if (IsPrivateMessage(text, ref message, ref username))
        {
            LogToConsole("Private message from " + username + ": " + message);
        }
    }
}
```

**Comment by EchoesNetwork** [comment]
With a small modification I got this to work. Thanks so much for the help. Below is a modified version of the script that MCC launched successfully, for anyone curious:

`//MCCScript 1.0

MCC.LoadBot(new ExampleBot());

//MCCScript Extensions

public class ExampleBot : ChatBot
{
    string path = "/root/bots/logs/";
    string filename = "messages.txt"; 

    public override void Initialize()
    {
        LogToConsole("Sucessfully Initialized!");
    }

    public override void GetText(string text)
    {
        string username = "";
        text = GetVerbatim(text);

       string message = String.Format("{0:yyyy-MM-dd_hh-mm-ss} {1} {2}", DateTime.Now, text, Environment.NewLine);
       File.AppendAllText(path + filename, message);

        if (IsChatMessage(text, ref message, ref username))
        {
            LogToConsole("Public message from " + username + ": " + message);
        }
        else if (IsPrivateMessage(text, ref message, ref username))
        {
            LogToConsole("Private message from " + username + ": " + message);
        }
    }
}`

**Comment by TheSnoozer** [comment]
Awesome, glad you could get it working :-)
