### ISSUE TITLE
Some accounts just crash

### ISSUE THREAD

**Issue by xNinurtax** [ORelio/Minecraft-Console-Client#695]
Hello,

i use 7 accounts to afk on a server.
Some accounts crash after this message:
http://prntscr.com/n8922h

Do they use too much ram or what?
Also, is there a way to make an Account file, and let multiple alts connect trough one Console Client?

Thanks in regards

**Comment by TheSnoozer** [comment]
Does the crash produce any kind of error message? What are the specs in regard to CPU/RAM of the computer where the accounts are running?

What is the utilization of the computer (check with `top` or `htop` for CPU utilization and/or `free -m` for RAM utilization).
