### ISSUE TITLE
System.BadImageFormatException on login

### ISSUE THREAD

**Issue by CCoenC** [ORelio/Minecraft-Console-Client#696]
When I log in on the client it immediately says this, it all started randomly one day, iv tried reinstalling everything and have reinstalled it multiple times.

Any comments are appreciated
\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
Minecraft Login failed : Network error.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by TheSnoozer** [comment]
1. Are you using the exe file from the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)?
2. Does your general network connectivity works with mojang?
Try
````
curl https://authserver.mojang.com
````
To check session server works properly.
3. Have you configured any proxies in your `MinecraftClient.ini`?

**Comment by CCoenC** [comment]
Yes I am using the latest build, i have not configured anything in the .ini file except the first time i was using the client. When I went to the link it said:
{"Status":"OK","Runtime-Mode":"productionMode","Application-Author":"Mojang Web Force","Application-Description":"Mojang Authentication Server.","Specification-Version":"4.5.19","Application-Name":"yggdrasil.auth.restlet.server","Implementation-Version":"4.5.19_build158","Application-Owner":"Mojang"}

I think that is good, not sure though

**Comment by ORelio** [comment]
Maybe you cannot directly connect to the login service because you are behind a proxy. If you can access it with your web browser, check proxy settings in your browser and copy them in MCC settings.

**Comment by CCoenC** [comment]
> Maybe you cannot directly connect to the login service because you are behind a proxy. If you can access it with your web browser, check proxy settings in your browser and copy them in MCC settings.

I dont use a proxy for my browser, I also dont use in the mcc as of right now.

**Comment by ORelio** [comment]
Does setting `debugmessages=true` in config gives you more detail?

**Comment by CCoenC** [comment]
It still says this:

Connecting to Minecraft.net...
Performing request to authserver.mojang.com
Minecraft Login failed : Network error.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by ORelio** [comment]
Please retry using latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts), just added some debug messages for you.

**Comment by CCoenC** [comment]
It now says this:

**Comment by CCoenC** [comment]
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
System.BadImageFormatException: Could not load file or assembly 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The file or directory is corrupted and unreadable. (Exception from HRESULT: 0x80070570)
File name: 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSRequest(List`1 headers, String host, String& result)
   at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSPost(String host, String endpoint, String request, String& result)
   at MinecraftClient.Protocol.ProtocolHandler.GetLogin(String user, String pass, SessionToken& session)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Minecraft Login failed : Network error.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by ORelio** [comment]
`Could not load file or assembly System.Configuration`: Seems like one of your .NET framework DLLs is corrupt. Try uninstalling & reinstalling? 🤔

**Comment by CCoenC** [comment]
I reinstalled it but I still get this message:

Connecting to Minecraft.net...
Performing request to authserver.mojang.com
System.BadImageFormatException: Could not load file or assembly 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The file or directory is corrupted and unreadable. (Exception from HRESULT: 0x80070570)
File name: 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSRequest(List`1 headers, String host, String& result)
   at MinecraftClient.Protocol.ProtocolHandler.DoHTTPSPost(String host, String endpoint, String request, String& result)
   at MinecraftClient.Protocol.ProtocolHandler.GetLogin(String user, String pass, SessionToken& session)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Minecraft Login failed : Network error.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>

**Comment by ORelio** [comment]
You can try to resolve filesystem issues by running `chkdsk /F C:` in an administrator console, and corrupt windows files using `sfc /scannow`. Hope this helps...

**Comment by CCoenC** [comment]
Sorry I haven’t responded. I had gone on vacation the same day. Will post a new reply once I do it. Thanks.

**Comment by CCoenC** [comment]
Ty so much. Everything is working now

**Comment by ORelio** [comment]
Glad to hear! Closing the thread.
