### ISSUE TITLE
mozroots --import --ask-remove (NOT WORKING)

### ISSUE THREAD

**Issue by Dextario** [ORelio/Minecraft-Console-Client#698]
Hello,
I am looking to use MCC on my VPS which is running Ubuntu 18.04 .

When I try to run the program it tells me: 

It appears that you are using Mono to run this program.
The first time, you have to import HTTPS certificates using:
mozroots --import --ask-remove

Then, when I exit my screen and type that in, it tells me this:

Mozilla Roots Importer - version 4.6.2.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

WARNING: mozroots is deprecated, please move to cert-sync instead.

Downloading from 'https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt'...

The error then cycles, I cannot launch MCC.

Thank you!

**Comment by TheSnoozer** [comment]
Thanks for reporting this.

When reading the [installation instructions](https://www.mono-project.com/download/stable/) it appears that the entire mozroot has been replaced by the *ca-certificates-mono* package:
``
The package ca-certificates-mono should be installed to get SSL certificates for HTTPS connections. Install this package if you run into trouble making HTTPS connections.
``


As a result I would first suggest to install that package on your system via: 
`sudo apt-get install ca-certificates-mono`

If this still does not work, please try the instructions outlined in https://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync

**Comment by TheSnoozer** [comment]
I assume you could the problem fixed. feel free to reopen if you still have an issue.
