### ISSUE TITLE
VPN w/ MCC not working

### ISSUE THREAD

**Issue by Dextario** [ORelio/Minecraft-Console-Client#699]
Hello,

I have enabled OpenVPN on my VPS and whenever I try to connect it tells me this:

No sessions could be loaded from disk
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
Minecraft Login failed : Network error.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

Any work around?

I am connecting to NordVPN.

**Comment by Mhowser** [comment]
Mojang is cracking down on the use of VPNs, you would have to authenticate
without it, then you could connect to a server with VPN once you have a
valid session token on your local machine. Unless the server itself refuses
connections from known VPN services.

**Comment by ORelio** [comment]
See #719 and #731
