### ISSUE TITLE
Enable/Disable TerrainAndMovements while logged in

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#705]
I don't know how completely possible this is, but I feel most world data(if you're running multiple alts) is just duplicates. Saying that, it takes up a lot of ram. I am wondering if it could be possible to serialize this data and either store it on a local file that all the alts could access, or if they could each access an in memory dictionary that is shared to decrease duplicate data.

**Comment by CarbonNeuron** [comment]
And, yes, it is about 50mb of memory, but it does get cumbersum with ~100 accounts running.

**Comment by ORelio** [comment]
Hi,

I must admit that running 100 accounts on the same box is a pretty unusual case.

Sharing terrain data between MCC process could be doable for sure, but would likely be hard to implement and almost certainly incur a significant performance hit.

Depending on your use case, maybe the terrain could be unloaded after the bot has done its init actions (go through a portal for instance) and stay idle in chat-only mode. That would be way easier to implement.

**Comment by CarbonNeuron** [comment]
To make world handling togglable, all that needs to be done is flip settings.terrainAndMovement to false or true, right?

**Comment by ORelio** [comment]
Exactly, you can flip the setting to false and clear the dictionary. Of course, you cannot switch back to true since world data has been erased and cannot be requested again without reconnecting.

Not sure about the other windows/.NET optimizations, sorry.

**Comment by CarbonNeuron** [comment]
I wonder if it would be possible to serialize it to disk when I flip it to false, then load it back when I flip it to true.

**Comment by ORelio** [comment]
You'd miss block and chunk updates sent in between, so that your serialized snapshot of the world would be outdated :/

**Comment by CarbonNeuron** [comment]
If the client were to go-to a hub, because it's a bungeecord server, and then back into the normal server would it resend the chunks that it needs?

**Comment by CarbonNeuron** [comment]
Obviously I'm trying to find a way around relogging. Its a difficult task.

**Comment by ORelio** [comment]
Chunks would be resent if you switch worlds, yes. Going to the Nether using teleport and back to the overworld would also resend the chunks.

**Comment by ORelio** [comment]
Just added changes so that you can enable or disable terrain handling while logged in. When re-enabling, the setting will take effect on next respawn, which happens when you login, respawn after death, or move to another world.

**Comment by CarbonNeuron** [comment]
Awesome. Thank you. Hopefully this will help keep memory under control.
