### ISSUE TITLE
Issues with Matches

### ISSUE THREAD

**Issue by PukingUnicornZ** [ORelio/Minecraft-Console-Client#706]
Hello im trying to make a bot for a faction server i play on but i am having issues.
whenever i try to make it read this
![screenie](https://user-images.githubusercontent.com/36401329/56696421-085ae380-66ec-11e9-9838-2061d2d0efca.PNG)
out of chat it wont work it will work if i type it in chat exactly like that.
here is my regex.
https://regex101.com/r/dBoQHF/17
i dont understand why it doesnt work am i missing something or should this just work.

**Comment by CarbonNeuron** [comment]
In your matches.ini is it set to do it in actionother=[regex]?
