### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by xTryer** [ORelio/Minecraft-Console-Client#708]
Hello everyone. I have a problem with Console Client.
I recently installed it on a Ubuntu VPS and it worked good. But today, is not working.

It tell me:
Resolving cosmicprisons.com...

Connecting to Minecraft.net...

Minecraft Login failed : Network error 
Not connected to any server. Use '/help' for help
Or ress Enter to exit the MC console Client
>___

I start it with a script (script.bat)
Script text: mono MinecraftClient.exe (my email) (My password) cosmicprisons.com

Can any1 help me pliz thansìks!!

**Comment by ORelio** [comment]
Please set `debugmessages=true` in config. Also, make sure to redact email, password and session IDs if posting any output here.

**Comment by xTryer** [comment]
Hello
Where I can find the config? (What file)
Thanks in advance

**Comment by TheSnoozer** [comment]
There should be a `MinecraftClient.ini` in the folder where you started the client (usually where the exe is residing).

**Comment by xTryer** [comment]
Yes!
This is the text in in:

#Minecraft Console Client v1.8.2
#Startup Config File

[Main]

#General settings
#leave blank to prompt user on startup
#Use "-" as password for offline mode

login=
password=
serverip=

#Advanced settings

language=en_GB
botowners=Player1,Player2,Player3
consoletitle=%username% - Minecraft Console Client
internalcmdchar=slash #use 'none', 'slash' or 'backslash'
mcversion=auto #use 'auto' or '1.X.X' values
chatbotlogfile= #leave empty for no logfile
accountlist=accounts.txt
serverlist=servers.txt
playerheadicon=true
exitonfailure=false
timestamps=false

[AppVars]
#yourvar=yourvalue
#can be used in some other fields as %yourvar%
#%username% and %serverip% are reserved variables.

[Proxy]
enabled=false
type=HTTP #Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=0.0.0.0:0000
username=
password=

#Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=true
delay=60 #10 = 1s
command=/server sovereign

[AutoRelog]
enabled=true
delay=10
retries=3 #-1 = unlimited
kickmessagesfile=kickmessages.txt

[ChatLog]
enabled=false
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=false
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=false
tasksfile=tasks.ini

[RemoteControl]
enabled=false
autotpaccept=true
tpaccepteveryone=false

**Comment by ORelio** [comment]
Your config file is old and does not have all the newer settings.
You can manually add it right after `timestamps=false`

**Comment by PapaMatu** [comment]
Heyo, I have the exact same issue with a aws VPS, running, exact same issue could anyone please help with this?

**Comment by ORelio** [comment]
@PapaMatu It is likely that your VPS is blacklisted from the login servers. Set debugmessages=true in config. Also, make sure to redact email, password and session IDs if posting any output here.

**Comment by PapaMatu** [comment]
https://gyazo.com/3f92c0b01be35fee390461b91550816b , I have debugmessages enabled and it changed nothing.

**Comment by PapaMatu** [comment]
And also, is there a way to bypass the blacklist?

**Comment by Mhowser** [comment]
Switch vps provider or install openvpn on your current vps

**Comment by CrypticPacl** [comment]
Every time I try to launch the Minecraft console client I get this message after the code.

Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 DEV - By ORelio & Contributors
Resolving pvpwars.net...
Found server pvpwars4.ddns.net:25565 for domain pvpwars.net
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Ignoring session token string 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NmMxNzcwNWRmZjQ2MmIzOWMzNjUwZDBjYTU1ZjYzMCIsInlnZ3QiOiI5OWY2NTc1M2QwMjA0OTJlYTFmNTY3MzQxNDE4NzE1MCIsInNwciI6IjRjNGQzODAwMzUzZTRiMDc5OTQ0MzlhNmJmYTJmYThhIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MDUyODE0NTUsImlhdCI6MTYwNTEwODY1NX0.TNkt4LS7hjYy0_c7VULiT6-u1Lc0IL2b5Txx3XphrpI,Oldanora,4c4d3800353e4b07994439a6bfa2fa8a,e70183f224074683879240493d40bca2': Invalid session ID
No sessions could be loaded from disk
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
> POST /authenticate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.12.2 DEV
> Content-Type: application/json
> Content-Length: 177
> Connection: close
>
> {"agent": { "name": "Minecraft", "version": 1 }, "username": "A\u002etindangen\u0040me\u002ecom", "password": "Wachtwoord01", "clientToken": "8e2bf481d38f4c769b93144515c583e4" }
Minecraft Login failed : Network error.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.



how can I fix this pls help.

**Comment by ORelio** [comment]
@CrypticPacl Please open a new issue if this persists.
