### ISSUE TITLE
No support for changing use of ANSI colors.

### ISSUE THREAD

**Issue by drXor** [ORelio/Minecraft-Console-Client#71]
This is a nice client, but it suffers from an annoying issue: there is an ANSI background I can't remove, which looks terrible on my terminal. I have attempted all sorts of witchery to remove it, to no avail, while keeping the rest of the colors intact. This just looks really bad on my terminal because ANSI "black" is actually white in my emulator theme.

A configuration option for at least disabling background colors would be appreciated. I would fork and fix it myself, but I don't into C#.

**Comment by ORelio** [comment]
No problem for adding a setting, but stay aware that Minecraft chat is mostly white text and would be non-readable on a white background ^^

**Comment by ORelio** [comment]
After a quick look, background color can be saved and restored, and useless changes were performed.
This is now fixed, thanks for your report. Checked on a linux terminal before commiting.
