### ISSUE TITLE
How to setup Prefix, if this include or line?

### ISSUE THREAD

**Issue by SandwichBM** [ORelio/Minecraft-Console-Client#714]
Hi there,

I was on good way to make an asystant for me (Currently MOD on one server), so that bot could auto answer for some weird and stupid question... But here I have the problem for now.

Owner of server set up an "|" on prefix ranks, what I saw on mcc settings, that this | is for "or" instructions? How Can I set this up, to be recognise as text and not as or?

![image](https://user-images.githubusercontent.com/50140122/56958980-402eb480-6b4c-11e9-81e6-7092fe7a57fd.png)
![image](https://user-images.githubusercontent.com/50140122/56958997-4e7cd080-6b4c-11e9-9b45-261b20bba454.png)

I know, that Issues are not for this, but I try better in here.

**Comment by ORelio** [comment]
`|` has a special meaning in regex, so you'll need to prepend it with `\`
Do not hesitate to test your regex on https://regex101.com/

**Comment by SandwichBM** [comment]
Thank you for explaination. I try this ^^
