### ISSUE TITLE
What would it take to support Bedrock edition versions

### ISSUE THREAD

**Issue by Mhowser** [ORelio/Minecraft-Console-Client#717]
Is there any documentation on what kind of packets are required?

**Comment by ORelio** [comment]
Seems like the protocol is completely different:
https://wiki.vg/Pocket_Edition_Protocol_Documentation

**Comment by RobertKlohr** [comment]
It seems like the protocol and documentation have both been updated.  Any chance we can look at starting work to support Bedrock?

**Comment by ReinforceZwei** [comment]
I don't think it is possible to support Bedrock version since we are lacking contributors already.

**Comment by ATXLtheAxolotl** [comment]
Hello something like you described is currently be developed, it is near completion as they are just finishing their pluginAPI and polishing a few things up, the program is called BeRP (Bedrock Edition Realm Protocol [I have to say funny name eh]) there discord can be found here: https://discord.gg/98QHF4MB9t

**Comment by ATXLtheAxolotl** [comment]
> Hello something like you described is currently be developed, it is near completion as they are just finishing their pluginAPI and polishing a few things up, the program is called BeRP (Bedrock Edition Realm Protocol [I have to say funny name eh]) there discord can be found here: https://discord.gg/98QHF4MB9t

BeRP has been discontinued, use https://github.com/PrismarineJS/bedrock-protocol

**Comment by milutinke** [comment]
When I start doing the protocol library, I'll see if I can add the support for bedrock.
Also, the version supported by the wiki is quite old.

**Comment by milutinke** [comment]
> If you’re looking for a more updated version of protocol documentation I recommend: https://minecraft-data.prismarine.js.org/?v=bedrock_1.19.50&d=protocol

That is awesome.
Although, the amount of work required to make this from scratch 😄
