### ISSUE TITLE
'Already connecting to this server'

### ISSUE THREAD

**Issue by AzenorisGOOD** [ORelio/Minecraft-Console-Client#718]
Whenever I try to login with Console Client it says 'Already connecting to this server' and then 'connection has been lost'
![Screenshot_5](https://user-images.githubusercontent.com/50318537/57213829-e4e34300-6fdf-11e9-8aec-c4f3c1623a48.png)

**Comment by ORelio** [comment]
Hi,
Do you have `terrainandmovements=true` in config? Try with and without.
Does your server runs 1.14? 1.13.2? Try with `mcversion=1.13.2` in config.

**Comment by ORelio** [comment]
Closing as not enough info provided.
