### ISSUE TITLE
[Question] Spam Right Click

### ISSUE THREAD

**Issue by IcyTower1337** [ORelio/Minecraft-Console-Client#720]
Bot works great, currently using 3 alts in different slime chunks to keep slimes spawning.

I also read a couple of the issues opened where people asked a similar question,

I wanted to have a fishing farm at all those chunks and keep the alts at them spamming right click on it, but in the issues i researched (#570 & #397 ) the feature wasn't implemented.

I was wondering if there was no way to just spam inputs to a server through a csharp script or a task, no need to interact with any blocks, just literally send right click events to the server.

All good if there's no way to do so at this moment, just wanted to ask either way to make sure.

**Comment by Pokechu22** [comment]
Pretty sure that this isn't implemented, unless I missed something in the recent changes.  And of course, the challenge is "what's a right click?".  Interacting with blocks is moderately complicated (there's several different packets for it that depend on what's there in the world) so it's not trivial to just do that.

**Comment by IcyTower1337** [comment]
Oh absolutely, I wouldn't even begin to imagine the amount of work that goes into implementing something as complicated as interacting with every block and the sub interactions that it might bring.

But I  because in my case and in many others, you just need to send the event and not bother about the outcome because you know what it is, I thought there might have been a way to do that.
 
Thanks for the info though, I'll keep using the no focus autoclicker in a normal client for the farms that need interaction and this program for the ones that just need a player loaded in the chunk/area.
