### ISSUE TITLE
Using other libraries in Script

### ISSUE THREAD

**Issue by Emperio** [ORelio/Minecraft-Console-Client#723]
I need to add new imports/"using" for other c# libraries, I was thinking about cloning the repo and checking CSharpRunner, in there I saw the part of "string code = an array of strings", should I just add the import I want, and build a new exe?

**Comment by ORelio** [comment]
Hi,
If needed, you can use the fully qualified name of the .NET class without recompiling, for instance `System.Diagnostics.Process.Start()` instead of `Process.Start()`.
If you need to include a third party library, however, you'll indeed need to include it with MCC and recompile.

**Comment by ORelio** [comment]
I'll assume the answer did solve your issue. Feel free to reopen if that wasn't the case.
