### ISSUE TITLE
PlayerListUpdate Packet Issues

### ISSUE THREAD

**Issue by xPenguinx** [ORelio/Minecraft-Console-Client#726]
The playerlistupdate packet is not working as planned. https://gyazo.com/4227b8899be2c7b8580ff022cb297c8d on line 787 it checks if the player has a custom display name and it returns false when it should be true because the tab list has 
[Rank] PlayerName [FactionName]

**Comment by ORelio** [comment]
Display names are ignored by MCC, which only retains the actual player name.

**Comment by xPenguinx** [comment]
Is there anyway to change that?

**Comment by xPenguinx** [comment]
> Display names are ignored by MCC, which only retains the actual player name.

I don't understand because shouldn't the data be somewhere? Like the packet should have that data?

**Comment by Mhowser** [comment]
I wonder if it could read from the TAB player list, which often has the
custom prefixes and suffixes.

**Comment by ORelio** [comment]
Display name is read on line 788 on your screenshot, but not used.
https://wiki.vg/Protocol#Player_Info

**Comment by xPenguinx** [comment]
> I wonder if it could read from the TAB player list, which often has the custom prefixes and suffixes.
> […](#)

That is what i'm trying to do

**Comment by xPenguinx** [comment]
> Display name is read on line 788 on your screenshot, but not used.
> https://wiki.vg/Protocol#Player_Info

Yes, but it is not being detected meaning that it has to be passed by the boolean first and it isn't. It thinks that it doesn't have a custom name

**Comment by Pokechu22** [comment]
There is also the team prefix/suffix (in [Teams](https://wiki.vg/Protocol#Teams)) which is also a way that the server might be implementing it.

**Comment by xPenguinx** [comment]
> There is also the team prefix/suffix (in [Teams](https://wiki.vg/Protocol#Teams)) which is also a way that the server might be implementing it.

Yes, it is the way they are doing it now, but its really toxic trying to organize this based on the players
