### ISSUE TITLE
Created a LMGTFY bot with MCC

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#730]
Hi,
this isn't a bug report, just a script I came up with earlier today that I thought some MCC users may find useful! It allows you to search google via LMGTFY and output the search URL in chat. With some small modifications, you can make the links clickable, but it requires operator permissions. The script is below:

```
//MCCScript 1.0

MCC.LoadBot(new LMGTFYBot());

//MCCScript Extensions

public class LMGTFYBot : ChatBot
{
    public override void Initialize()
    {
        LogToConsole("LMGTFYBot sucessfully initialized!");
    }

    public override void GetText(string text)
    {
        string message = "";
		string username = "";
        text = GetVerbatim(text);
 if (IsChatMessage(text, ref message, ref username))
    { 
	 if (message.StartsWith("!lmgtfy "))
	 { 
        {
            SendText("https://lmgtfy.com/?q=" + message.Replace("\\", "⧵").Replace("'", "ꞌ").Replace("!lmgtfy ","").Replace(";", ":").Replace(" ", "+").Replace("`", "")");
        }
	 }	
    }
}
}
```
Hopefully someone finds this useful! Since it doesn't require any external programs, I was wondering if it'd be possible to include this as a feature in MCC.

**Comment by xPenguinx** [comment]
I think you might be able to use System.WebClient

**Comment by xPenguinx** [comment]
Sounds cool

**Comment by EchoesNetwork** [comment]
Had no idea `System.WebClient` was even a thing! I’ll look into changing the script to use it. This just follows the formula LMGTFY uses to construct its URLs. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheSnoozer** [comment]
Looks nice :)

i'll close this though :-P
