### ISSUE TITLE
OVH Vps don't let Mcc launch

### ISSUE THREAD

**Issue by Christo4g** [ORelio/Minecraft-Console-Client#731]
Hey, I have tried to launch several times MCC on a OVH's vps but it don't seem to work. I get the same error everytime.
`Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.`

 I have tryed to uninstall and reinstall mono but it didn't seem to work. I upgraded all the package but this didn't work to. Are they any other solutions I can do for it to work?

**Comment by Mhowser** [comment]
It's most likely Mojang preventing you from authenticating from that IP
address. Probably too many login attempts in a short time span.

Look in your config file and check to see if sessioncache is set to memory
(ram) or disk.

**Comment by Christo4g** [comment]
Is it set to memory.

**Comment by Mhowser** [comment]
At this point you just need to wait a while before you try to login. If it
still doesn't work, change sessioncache to disk.

**Comment by Christo4g** [comment]
Ok Imma try to wait before launching an account back on this ip.

**Comment by Mhowser** [comment]
Additionally, you could sign out/in to your Minecraft launcher then try to
authenticate within MCC. That worked for me.

**Comment by Christo4g** [comment]
Didn't work for both. I'll change sessioncache to disk

**Comment by Christo4g** [comment]
Don't seem to work either.

**Comment by xPenguinx** [comment]
That VPS might be Mojang banned try downloading Minecraft on that VPS and see if logging in to your account works.

**Comment by TheSnoozer** [comment]
Based on https://github.com/ORelio/Minecraft-Console-Client/issues/719#issuecomment-491410001 it appears that some OHV servers are blacklisted by Mojang. Usually if you tried to authenticate too many times Mojang will temporary lock out your account. Try again from your local computer with a normal vanilla minecraft installation.

**Comment by Christo4g** [comment]
It work every time when I login on my pc. Even using real Minecraft or Mcc. The problem might be that the ip got blacklisted

**Comment by Christo4g** [comment]
> That VPS might be Mojang banned try downloading Minecraft on that VPS and see if logging in to your account works.

There isn't enough place in the vps to install it

**Comment by Christo4g** [comment]
> Based on [#719 (comment)](https://github.com/ORelio/Minecraft-Console-Client/issues/719#issuecomment-491410001) it appears that some OHV servers are blacklisted by Mojang. Usually if you tried to authenticate too many times Mojang will temporary lock out your account. Try again from your local computer with a normal vanilla minecraft installation.

It's not possible to change the location so you got anymore things I can check?

**Comment by TheSnoozer** [comment]
> It's not possible to change the location so you got anymore things I can check?

I don't know.

**Comment by ORelio** [comment]
1) Use MCC on your PC with `sessioncache=disk` set in config, login to your account(s)
2) Put `sessioncache.ini` on your VPS for use with MCC with `sessioncache=disk` set in config
3) MCC should be able to join servers using cached session information

**Comment by Christo4g** [comment]
Still that same error:
`Resolving play.minesaga.org...
Initializing disk session cache using FileSystemWatcher
Loading session cache from disk: SessionCache.ini
Loaded session: christoo4g@gmail.com:dcc2a62dd1364b0f86c9b05db981c9df
Session data has been successfully loaded from disk.
Performing request to authserver.mojang.com
> POST /validate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.14.1
> Content-Type: application/json
> Content-Length: 103
> Connection: close
>
> {"accessToken": "dcc2a62dd1364b0f86c9b05db981c9df", "clientToken": "5ee424b446c947b9b4bbf0614e6c60dc" }

< HTTP/1.1 403 Forbidden
< Server: CloudFront
< Date: Fri, 24 May 2019 21:30:08 GMT
< Content-Type: text/html
< Content-Length: 560
< Connection: close
< X-Cache: Error from cloudfront
< Via: 1.1 b91a04ebd793cc7fb1ab1792430f664a.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: 3jiW9j1XXZwnj6Yi8UYy2zTfsPitrDMsEWsED2UyHAldefvHcVueNQ==
<
< <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
< <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
< <TITLE>ERROR: The request could not be satisfied</TITLE>
< </HEAD><BODY>
< <H1>403 ERROR</H1>
< <H2>The request could not be satisfied.</H2>
< <HR noshade size="1px">
< Request blocked.
<
< <BR clear="all">
< <HR noshade size="1px">
< <PRE>
< Generated by cloudfront (CloudFront)
< Request ID: 3jiW9j1XXZwnj6Yi8UYy2zTfsPitrDMsEWsED2UyHAldefvHcVueNQ==
< </PRE>
< <ADDRESS>
< </ADDRESS>
< </BODY></HTML>
Cached session is invalid or expired.
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
> POST /authenticate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.14.1
> Content-Type: application/json
> Content-Length: 175
> Connection: close
>
> {"agent": { "name": "Minecraft", "version": 1 }, "username": "", "password": "", "clientToken": "" }

< HTTP/1.1 403 Forbidden
< Server: CloudFront
< Date: Fri, 24 May 2019 21:30:08 GMT
< Content-Type: text/html
< Content-Length: 560
< Connection: close
< X-Cache: Error from cloudfront
< Via: 1.1 689b4d0503d43d5df99a927d67e778fe.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: nk9hyIzEZcqfvrIE_wHiZMi-YjWmnd9d690gdbeqdu7kS9ifbgw4sg==
<
< <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
< <HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
< <TITLE>ERROR: The request could not be satisfied</TITLE>
< </HEAD><BODY>
< <H1>403 ERROR</H1>
< <H2>The request could not be satisfied.</H2>
< <HR noshade size="1px">
< Request blocked.
<
< <BR clear="all">
< <HR noshade size="1px">
< <PRE>
< Generated by cloudfront (CloudFront)
< Request ID: nk9hyIzEZcqfvrIE_wHiZMi-YjWmnd9d690gdbeqdu7kS9ifbgw4sg==
< </PRE>
< <ADDRESS>
< </ADDRESS>
< </BODY></HTML>
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
`

**Comment by Mhowser** [comment]
Uh don't post your session ID publicly, someone can use that to play on
your account.

**Comment by Christo4g** [comment]
> Uh don't post your session ID publicly, someone can use that to play on your account.
Deleted it. There was to much thing I didn't pay attention to everything. Well, ty for saying it and the error is the Black Listed thing again.

**Comment by Mhowser** [comment]
You can edit comments btw don't have to delete it

**Comment by Christo4g** [comment]
I didn't know what was the session ID.

**Comment by Mhowser** [comment]
If you look at the JSON payload it tells you

**Comment by ORelio** [comment]
@Christo4g Seems like the session servers also block `/validate` endpoint used to relog using an existing session ID. This cannot be circumvented unless you have an HTTP proxy that is not blacklisted. In this case, you can enter your proxy details in config and set it to `enabled=login`.
@Mhowser When replying via email, don't include the previous email, or else you repost @Christo4g 's session ID. Redacting your messages 😜

**Comment by Mhowser** [comment]
Ah I forgot about that, thanks!

**Comment by nickiu** [comment]
> 1. Use MCC on your PC with `sessioncache=disk` set in config, login to your account(s)
> 2. Put `sessioncache.ini` on your VPS for use with MCC with `sessioncache=disk` set in config
> 3. MCC should be able to join servers using cached session information

how do u set it in the config do u need to set in in the config of mcc or what?

**Comment by ORelio** [comment]
sessioncache=disk inside MinecraftClient.ini

**Comment by nickiu** [comment]
does it matter where i set it in minecraftclient.ini
and what do u mean with Put sessioncache.ini on your VPS
