### ISSUE TITLE
failed to check session the first time connecting to server

### ISSUE THREAD

**Issue by chaos511** [ORelio/Minecraft-Console-Client#732]
when i try to connect to a server in offline mode it says login failed : failed to check session but if i use a different launcher in offline mode and connect with the same name first then console client works is there any to fix this?

the server has a plugin so before you can move you need to do /register <password>

**Comment by ORelio** [comment]
This is weird, because the session check happens only if the server request to do so. Maybe the server owner did some modding and introduced some non-standard behavior in the login procedure.
