### ISSUE TITLE
i get auto disconnected ?

### ISSUE THREAD

**Issue by mocha0** [ORelio/Minecraft-Console-Client#733]
So when I login everything is fine and I log into a server and I can chat and everything is fine, but then like 5 minute later i try chatting and my text just pops up as a plain white text, I get disconnected from the server automatically for no reason without any error messages, and its not my internet because I can go into the actual minecraft without any problems or disconnections.

**Comment by Mhowser** [comment]
What's your environment? If it's Linux there are some issues with mono.

**Comment by TheSnoozer** [comment]
Have you downloaded the latest version? What server version are you trying to join?

**Comment by mocha0** [comment]
I'm on Windows 10 and yes im using the latest version and the server is 1.13.2

**Comment by ORelio** [comment]
Maybe the server owner has set some anti-AFK measures?

**Comment by mocha0** [comment]
Nope, i've been on this server for years and im good friends with the owner, i can afk for hours without any problems in the actual game.
