### ISSUE TITLE
 How do i have multiple accounts connect

### ISSUE THREAD

**Issue by darcypastie** [ORelio/Minecraft-Console-Client#734]
how would i have multiple accounts connect? please help

**Comment by TheSnoozer** [comment]
Run multiple instances of the bot.
One instance = one account.

**Comment by ORelio** [comment]
Currently, you can only have one account at a time, but you can launch as many MinecraftClient.exe as you want at the same time, thus having as many accounts as you want. Closing as answered, feel free to reopen if still unclear.

**Comment by MxrrayVII** [comment]
Hey @ORelio. Really liking MCC, but I'm having a bit of a hard time... Apologies if I'm not allowed to do this here, but I can't find any other info relating to the multiple account question above. I've got my first alts login details in the .ini file so they load up straight away right... But I'm not sure how to do the same thing but for another alt account? I'd like to have them both running at once, I just don't know how to make it happen unfortunately.

**Comment by ReinforceZwei** [comment]
@MxrrayVII You may use `MinecraftClient.exe <email> <password> <server-ip>` syntax to log your alt account(s).

**Comment by MxrrayVII** [comment]
> @MxrrayVII You may use `MinecraftClient.exe <email> <password> <server-ip>` syntax to log your alt account(s).

I'm really sorry lol but I have no idea what that means. It's taken me a few days just to actually get my alt on the server and stay on there for a while lol. If you wouldn't mind explaining a lil bit for me, it'd be greatly appreciated man!

**Comment by ReinforceZwei** [comment]
@MxrrayVII First you need to open a command prompt. You can do this by pressing `windows+R`, type `cmd` and press `enter`. A black window with white text will show up.
Then, you need to `cd` into the folder that contain your `MinecraftClient.exe` file, assume that it is in your Desktop. In the command prompt, type `cd Desktop`. Last, run `MinecraftClient.exe <email> <password> <server-ip>`.

Actually there is one easy way you can do. First, remove login details in your `.ini` file. Next, open MCC and it will ask you for login information. Then you can input your login details manually. Repeat the steps for any other alts.

**Comment by MxrrayVII** [comment]
@ReinforceZwei Think I might try the easier one so I don't delete everything on my computer or something lol. Thankyou SO MUCH!
