### ISSUE TITLE
How to setup the Script Scheduler?

### ISSUE THREAD

**Issue by MeowchChan** [ORelio/Minecraft-Console-Client#735]
Hello  i saw the scriptScheduler  and i want to know how to set it up to use a script 
if that is possible

**Comment by TheSnoozer** [comment]
From https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config:
> ============================
 Using the Script Scheduler
============================
The script scheduler allows you to perform scripts on various events.
Simply enable the ScriptScheduler bot and specify a tasks file in your INI file.
Please read sample-tasks.ini for learning how to make your own task file.

see https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini

**Comment by ORelio** [comment]
Closing as resolved. Feel free to reopen if you still have questions.
