### ISSUE TITLE
How does one download this to vps

### ISSUE THREAD

**Issue by ChipotleOP** [ORelio/Minecraft-Console-Client#737]
Title basically sums it up

**Comment by Mhowser** [comment]
Well it depends on what OS your vps is, if it is Linux based you can use
wget or curl -o .

**Comment by ChipotleOP** [comment]
@Mhowser pardon would i just wget and then the github link?

**Comment by ChipotleOP** [comment]
like how do i get it to download something from a certain link (Sorry i'm new to this)

**Comment by Mhowser** [comment]
I'll assume your vps is running Ubuntu Linux so it would be:

wget
https://ci.appveyor.com/api/buildjobs/iu2va9p0qxf7d4cp/artifacts/MinecraftClient%2Fbin%2FRelease%2FMinecraftClient.exe

Or

curl -o
https://ci.appveyor.com/api/buildjobs/iu2va9p0qxf7d4cp/artifacts/MinecraftClient%2Fbin%2FRelease%2FMinecraftClient.exe

You will need mono to run MCC.
https://www.mono-project.com/download/stable/

Follow the instructions for your Ubuntu version.

**Comment by TheSnoozer** [comment]
As addition to the suggested you could also "download" the client to your local windows file system as usual and upload it the vps using WinScp: https://winscp.net/eng/download.php

There are plenty of tutorials available (e.g. search for `how to upload files to a linux VPS from windows`) so I'm going ahead and close this as answered. Feel free to open a new issue if you still got any questions or problems.
