### ISSUE TITLE
Connection Throttled Issue

### ISSUE THREAD

**Issue by Daryking1903** [ORelio/Minecraft-Console-Client#740]
Hello i keep having an issue with connection throttled on a server that i play on. I have 30 second difference in connection time to make it so it should not be an issue and i have added connection throttled to my kick messages folder but after the connection throttled message on the console client it does not even attempt to reconnect the alts.

**Comment by ORelio** [comment]
Hi, could you provide a screenshot of your kickmessages file and the message inside the console? Also, do other kind of kick messages work properly?

**Comment by Daryking1903** [comment]
I will take a screenshot tonight when it shows the message again. All other kick messages work and the connection throttled works all the time except immediately after reboot.

**Comment by ORelio** [comment]
If you have many accounts, maybe they will try to reconnect all at once, so only one will connect and the others will be throttled. If you retry count is low, it may be reached before being able to connect, and will give up.

**Comment by Daryking1903** [comment]
![Connection Issue](https://user-images.githubusercontent.com/51068739/58613237-62624200-8272-11e9-979e-8602ac2d480a.PNG)

I have a 20 second wait between each account reconnecting but i still get the issue

**Comment by Daryking1903** [comment]
Connection has been lost
Server is restarting
Server is full
too many people
End Of Stream
Internal Server Error: java.net.Minecraft
Internal exception: java.io.IOException: Received string length longer than maximum allowed (105>100)
Internal Server Error
Disconnected
Illegal characters in chat
disconnect.spam
Read timed out
Bad login
Flying is not enabled on this server
Attempting to attack an invalid entity
Illegal stance
Illegal position
You have been idle for too long!
You have connected too fast. You must wait at least 4 seconds between connections.
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.
Connection throttled! Please wait before reconnecting.

**Comment by ORelio** [comment]
Ok, still does not help. Please retry with `debugmessages=true` set in config using [latest dev build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by ORelio** [comment]
If you have many accounts to reconnect, you may now set `delay=10-60` or any other ranges so that each client randomly chooses a different delay and avoid all accounts to reconnect at once.
