### ISSUE TITLE
Tasks file not found

### ISSUE THREAD

**Issue by Latestion** [ORelio/Minecraft-Console-Client#742]
Im trying to make task for my console client and for any certain problem its not taking it. It says that it cant find the file called tasks.ini and simply dosent run any of My scripts.

**Comment by ORelio** [comment]
See #431.

**Comment by Latestion** [comment]
I already saw #431 it didn’t help. Windows is my operating system and i use 1.8.9

**Comment by ORelio** [comment]
1) Make sure `debugmessages=true` is set in config
2) Open folder containing `MinecraftClient.exe`
3) Right click on folder background (a blank area) while maintaining Shift key pressed
4) Click "Open Command Prompt here" or "Open PowerShell here"
5) type `dir` and press Enter to list files
6) type `MinecraftClient.exe` and press Enter to launch MCC
7) Please provide output of both commands from the Command Prompt/PowerShell window
8) Before posting, please redact any email, password, and session identifiers (random hexadecimal strings)

**Comment by aaryamannchallani** [comment]
@ORelio 
I too have a similar error,

Server version : Paper 1.15.2 (protocol v578).
[MCC] [AutoRelog] Launching with 3 reconnection attempts
[MCC] [AutoRelog] File not found: E:\random\Console client\newheroku\kickmessages.txt
[MCC] [AutoRelog]   Current directory was: E:\random\Console client\newheroku
[MCC] [ScriptScheduler] Loading tasks from 'E:\random\Console client\newheroku\tasks.ini'
[MCC] [ScriptScheduler] No action for task:
 triggeronfirstlogin = False
 triggeronlogin = False
 triggerontime = False
 triggeroninterval = False
 timevalue =
 timeinterval = 0
 action =
Translations file loaded.
Version is supported.
Logging in...


Even though, my tasks.ini file has an action
[Task]
triggerOnFirstLogin = true
action =send hello

**Comment by ORelio** [comment]
Seems like your INI file is not properly formatted. Remove the spaces around the `=` sign.
