### ISSUE TITLE
add disconnect command for server restarts?

### ISSUE THREAD

**Issue by ITCMD** [ORelio/Minecraft-Console-Client#745]
I want to be able to automatically reconnect on server restarts. When the message `server restarting in 1 minute.` is read, I would like to disconnect, wait two minutes, and reconnect. However, there is no command that lets me disconnect without quitting the app.

**Comment by ORelio** [comment]
If you are disconnected, you can use AutoRelog
If you are kicked to hub, you can use AutoRespond
For more details: [README.txt](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt).
