### ISSUE TITLE
Matches.ini

### ISSUE THREAD

**Issue by DiscordPug** [ORelio/Minecraft-Console-Client#747]
Auto Respond $u not working for me 

[Match]
match=hi
action=send $u hi

[ChatFormat]
builtins=true #support for handling vanilla and common message formats
#public=^<([a-zA-Z0-9_]+)> (.+)$ #uncomment and adapt if necessary
#private=^([a-zA-Z0-9_]+) whispers to you: (.+)$ #vanilla example
#tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

Please someone can help me ?

**Comment by Mhowser** [comment]
What does the chat format look like on your server?

**Comment by DiscordPug** [comment]
![image](https://user-images.githubusercontent.com/51095848/58799205-604f0900-860d-11e9-8373-83b322569606.png)
like a this but im mod

**Comment by DiscordPug** [comment]
![image](https://user-images.githubusercontent.com/51095848/58799410-f420d500-860d-11e9-978d-a8c9e68ac8d9.png)
Members like this

**Comment by ORelio** [comment]
I'd say something like this:
```
public=^\[[^]]+\] ([a-zA-Z0-9_]+) » (.+)$
```
See it here: https://regex101.com/r/jMZBBJ/1

**Comment by TheSnoozer** [comment]
Since this question was answered I'm assuming you got this to work. As a result i#m going ahead and close this issue. If you still got a problem with this, please reopen this issue. If you got any other question or problem please open a new issue.
