### ISSUE TITLE
Add support for translating MCC

### ISSUE THREAD

**Issue by danielmosselman** [ORelio/Minecraft-Console-Client#750]
where can i download a other language for the minecraft console.
and do u have the dutch language for the minecraft console. yes?, where can i download

**Comment by ORelio** [comment]
Currently, all messages in MCC are hardcoded in English only so there is no Duch version. Translation support might be added at a later time.

**Comment by TheSnoozer** [comment]
If you are interested in 'only' the chat messages from minecraft I believe you could get any language.
When reading the chat message parsing code from https://github.com/ORelio/Minecraft-Console-Client/blob/e7c664648e5535a8aeae47ceadf4bb2efaffb7d5/MinecraftClient/Protocol/ChatParser.cs#L93 it checks if you have a `lang`-Folder. If you don't takes the language setting (e.g.  `language=en_GB`) from your `MinecraftClient.ini` and checks inside [here](https://s3.amazonaws.com/Minecraft.Download/indexes/1.13.json) where to get the right language file.
The actual file for `en_GB` can be found [here](http://resources.download.minecraft.net/ea/eaa9d3e91e8bf5f6178ddc2fd92727a8f6ab5ec1), for `da-DK` (danish) [here](resources.download.minecraft.net/54/545b9c0696d4febe5a2b8db3d336ed23f38bfbde). See [here](https://wiki.vg/Game_files#Assets) how assets are handled for any other files.

So maybe what does half of the job, is to delete the `lang`-Folder, set `language=da_DK` inside  your `MinecraftClient.ini` and try how it looks.

The internal messages from MCC are indeed only hardcoded in English.

**Comment by ReinforceZwei** [comment]
Added in https://github.com/ORelio/Minecraft-Console-Client/pull/1273
