### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by DiscordPug** [ORelio/Minecraft-Console-Client#751]
ORelio, Do you have discord? I need ask you Something

**Comment by TheSnoozer** [comment]
Ask here?

**Comment by ORelio** [comment]
I do not have enough time to handle individual requests on Discord.

**Comment by TheSnoozer** [comment]
Closing as answered.

**Comment by Xevier1** [comment]
> I do not have enough time to handle individual requests on Discord.

ORelio i help coordinate the team at OQMineBot (if you know what that is) and i was wondering if you had the time to talk about some prospective opportunities? I know you've just said you don't handle individual requests but there is some collaboration opportunities i'd like to talk about if you're interested

**Comment by ORelio** [comment]
@Xevier1 I assume this is one of the various commercial products making profit from MCC's free codebase without contributing back (by helping to implement new protocol versions, new protocol packets, etc.) If your offer involves some benefit for the community then sure, I'm open for discussion. I'll send you PM.
