### ISSUE TITLE
MATCH problem

### ISSUE THREAD

**Issue by xdNiBoR** [ORelio/Minecraft-Console-Client#754]
My match doesn't respond, this is my match file:
[Match]
match=hi
action=send hi, $u
actionprivate=send hallo
ownersonly=false

I think its because server chat is different, but I dont now how to code so I cant figure it out.
Console client does not detect player messages, it does detect server messages.
![image](https://user-images.githubusercontent.com/51537026/59161882-55521800-8ae8-11e9-87a2-d4d3c6c03060.png)

And I just found out that messages from console client do appear in the chat? maybe thats the issue?

**Comment by Mhowser** [comment]
You need regex for player chat.

https://regex101.com

**Comment by ORelio** [comment]
See also #579 and #712
