### ISSUE TITLE
Python Script

### ISSUE THREAD

**Issue by Christo4g** [ORelio/Minecraft-Console-Client#757]
Hi, 
I am currently learning how to script in Python. Can the cc run the Python script or I need to put it in C#?

Thanks, 
Christo4g

**Comment by TheSnoozer** [comment]
yes, that can be achieved by MCCScript:
See https://github.com/ORelio/Minecraft-Console-Client/issues/694#issuecomment-490627086 or https://github.com/ORelio/Minecraft-Console-Client/issues/715#issuecomment-489442588

**Comment by Christo4g** [comment]
Ok will take a look soon ty.

**Comment by Christo4g** [comment]
Looked at it and this is for Linux. Is it possible to do this on Windows? Tested by changing the location for Windows Locations but doesn't seem to work.

**Comment by ORelio** [comment]
Just updated my comment on https://github.com/ORelio/Minecraft-Console-Client/issues/694#issuecomment-490627086 to include an example for Windows.

**Comment by Christo4g** [comment]
Resolved. Ty.
