### ISSUE TITLE
The Watchlamp script after 1.13

### ISSUE THREAD

**Issue by Erixen** [ORelio/Minecraft-Console-Client#763]
In the recent updates of ConsoleClient, I have noticed that the [Watchlamp ](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-world-access.cs)script no longer works, instead the following error message is returned:

`System.InvalidOperationException: MinecraftClient.Mapping.Material does not contain a definition for RedstoneLampOn`

This I assume is due to the changes made to BlockIDs in [1.13](https://minecraft.gamepedia.com/Java_Edition_1.13/Flattening). But how would one get this script to work again now after the changes?

Thanks!

**Comment by ORelio** [comment]
Currently, block states are not reachable from the MCC API due to the large amount of block states that would need to be implemented, With the 1.13 flatenning, Redstone lamps now have the same Material type, thus breaking this script. See #599 for more details.
