### ISSUE TITLE
Figuring out what chatformat to use

### ISSUE THREAD

**Issue by Anspdoijs** [ORelio/Minecraft-Console-Client#764]
Hello,

I was wondering what the proper way to find out what chat format the server I play on uses. I've read a bunch of threads on here which made me conclude that my matches scripts (all using actionother) do not work properly as mentioned in [608](https://github.com/ORelio/Minecraft-Console-Client/issues/608). I have very little experience in regex and the likes so I would very much appreciate some help here! 

There's several combinations possible for general chat:

$rank $nick $team

Where both $rank and $team are optional. How would I combine this into a single regex?

In these formats $rank is always [text], so I think ([[a-zA-Z0-9]+]) should work. $nick follows usual minecraft nicks so ([a-zA-Z0-9_]+) would be correct. $team can be anything ASCII so my best bet would be (.+). 

([[a-zA-Z0-9]+]) ([a-zA-Z0-9_]+) (.+) is what I came up with, but I have no idea how to make it so that both the first and last part are optional. Any help would be greatly appreciated!

The private and tprequest formats are default, so they don't require any changing.

**Comment by ORelio** [comment]
Reading #579 is a good starting point. Some further regex issues are detailed in #712

Optional groups can be done using `(?:RANKREGEX )NICKNAMEREGEX(?: TEAM REGEX)`. Also notice the spaces that are likely added betweek rank, nick and team. They are placed inside the optional groups.

**Comment by TheSnoozer** [comment]
For now it seems that the issue was answered and thus I'm going ahead and close this as part of an issue cleanup. Feel free to reopen if you don't get it to work and also make sure to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client)
