### ISSUE TITLE
wont run commands

### ISSUE THREAD

**Issue by SummaryUSSS** [ORelio/Minecraft-Console-Client#766]
Im trying to help out my friend with console client, I tried to send him the link to the old website with the guide but that link just doesnt work anymore. We are having issues when it comes to sending commands with anti afk. I took him through the set up step by step, our setups are almost exactaly the same besides the email & password & such but his command wont send & mine will. I'd love a fix for this issue.

**Comment by Nafana** [comment]
Would you be able to provide more information? For instance showing us your friend's configuration file (MinecraftClient.ini) might be a good start.  Please remove all sensitive information such as the login details before submitting. Thanks.
