### ISSUE TITLE
Does $u work inside a referenced script file?

### ISSUE THREAD

**Issue by Pure8eat** [ORelio/Minecraft-Console-Client#770]
So I really want to be able to reply to a player Pm'ing my bot on a vanilla server, but I want to respond using a separate script file. I was just wondering if having the $u will work if it's not in the [Match] section, but within a script that is called upon with actionother.

Example:
[Match]
match=hi
actionother=script reply.txt

reply.txt:
send /msg $u Hi there, $u!
wait 20

**Comment by yunusemregul** [comment]
I fixed it on my fork and made a pull request, you can use my fork if you want.

**Comment by ORelio** [comment]
Hi,
This feature is now implemented: you can use `%match_u%` for player name from within your script.
See [this comment](https://github.com/ORelio/Minecraft-Console-Client/pull/772#issuecomment-605308154) for more information about how to use it.
