### ISSUE TITLE
How to open SLN files

### ISSUE THREAD

**Issue by MeowchChan** [ORelio/Minecraft-Console-Client#771]
For some reason .sin and .user fils arent opening for me
I tried using multiple programs to open it but all didn't work

**Comment by TheSnoozer** [comment]
see https://fileinfo.com/extension/sln

Programs that open SLN files:
```
Microsoft Visual Studio
VSoft Technologies FinalBuilder
MonoDevelop
```

I personally use MonoDevelop

**Comment by MeowchChan** [comment]
Thanks!
