### ISSUE TITLE
Client unable to connect to 1.14.3 servers due to "VarInt too big"

### ISSUE THREAD

**Issue by Pure8eat** [ORelio/Minecraft-Console-Client#774]
Hey there.

Just trying to log into a 1.14.3 server using the updated launcher and with TerrainAndMovements disabled. Unfortunately my bot logs in, but then I get [this screen](https://imgur.com/PW7M1ML) and the bot just shuts itself down. Any help on what I can do to solve this?

**Comment by r3spawned** [comment]
Im getting the same in Mc central

**Comment by razorrider7** [comment]
I am getting this error on 1.14.4 as well. Is there anywhere that states 1.14 isn't supported, or is it supposed to be?
