### ISSUE TITLE
Im new and could use some help with my code.

### ISSUE THREAD

**Issue by CatC3r** [ORelio/Minecraft-Console-Client#775]
Hi, I am not a good programmer and don't understand things easily. I have issues that I don't know how to solve! 
My issues are:

- How can I do an OnEventChat (When something gets said in chat)
- How can I execute a command or say a message?
- My MCC.Loadbot(new ExampleBot()); shows as an error in visual studio
- How can I write and read .txt files?

Here is the code: 

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

//MCCScript 1.0

/* This is a sample script that will load a ChatBot into Minecraft Console Client
 * Simply execute the script once with /script or the script scheduler to load the bot */

MCC.Loadbot(new ExampleBot());

//MCCScript Extensions

/* The ChatBot class must be defined as an extension of the script in the Extensions section
 * The class can override common methods from ChatBot.cs, take a look at MCC's source code */

public class ExampleBot : ChatBot
{
    public override void Initialize()
    {
        LogToConsole("Sucessfully Initialized!");
    }

    public override void GetText(string text)
    {
        string message = "";
        string username = "";
        text = GetVerbatim(text);

        if (IsChatMessage(text, ref message, ref username))
        {
            return;
        }
        else if (IsPrivateMessage(text, ref message, ref username))
        {
            if (message == "1")
            {
                MCC.Sendtext("/w " + username + " Tested");
            }
        }
    }
}
```
Thanks in advance!

**Comment by Pure8eat** [comment]
Hey there CatC3r, I'm also no where near an expert at coding, but I might be able to answer a couple of your questions. I'm gonna try and answer them within the context of .txt and .ini files, so if you are looking for .cs code help then I'll promptly remove my answer.

(If any of this isn't possible, or is not what you meant in your question, then I apologise in advance. I'm just throwing in some ideas I've learnt from experience.)

Firstly, to get an OnEventChat feature implemented, I'd actually recommend using the AutoRespond bot, which can be set to "true" inside your MinecraftClient.ini folder. Once you've done this, create a file called "matches.ini" in the client's folder; details on how to utilise this can be found [here.](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini)

To say a message through your bot, you can either speak directly through the console as if it were the Minecraft text chat, or if you want to cue your bot to say certain things at different times of the day, you can use the ScriptScheduler bot, by also enabling it inside your MinecraftClient.ini folder and creating a "mainscript.ini" folder. To learn more about this, look [here](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini) for examples on what to put into it. 

I'm not too sure how to answer your third question myself, but your fourth question; are you referring to writing a piece of code that is able to access .txt files and change its contents? Or are you more referring to how to do that in general?

I hope I could help. Again, if I've made an wrong assumptions please let me know!

**Comment by CatC3r** [comment]
I was referring to the .cs file but thanks anyways! Tho if you could help me make a regex that would solve almost all of my current issues. When I privately message someone on his screen they see 

> (From USERNAME) MESSAGE

I have not used regex and I cannot understand how to use it so if you could help me with that, it would be great.
Thanks for posting

**Comment by 0Jumpero** [comment]
This might help you: https://minecraft.gamepedia.com/Commands/tellraw
