### ISSUE TITLE
Can't run mono scripts, Can't login to alts in console client... [HELP ASAP PLEASE]

### ISSUE THREAD

**Issue by Shuaib08** [ORelio/Minecraft-Console-Client#777]
Hello, I've seen quite a few other issues and read answers similar to this issue but I've tried all the possible methods to resolve this but still can't get it to work..

I followed this tutorial : [https://youtu.be/I3OAYEe7Rlw](https://youtu.be/I3OAYEe7Rlw)

Everything was going well until I tried to execute `./Script1.bat` and then i started to get the error message "cannot open assembly 'MinecraftClient.exe' : file does not contain a valid CIL image".

I then proceeded to try the answers given to other people with this issue but none of the methods worked..

I also tried to use `mcs MinecraftClient.exe` but that also had an error saying "error CS2015: Source file `MinecraftClient.exe' is a binary file and not a text file".

Please help me as nothing is working..

Extra Note : I'm using a VPS running on Ubuntu 18.04
Extra Note : In the screenshot below you will see 51 scripts which I am trying to run, containing a different alt in each, in the format `mono MinecraftClient.exe (email address) (password) (server ip)`

![Screenshot_93](https://user-images.githubusercontent.com/53378457/61997796-fac44980-b09e-11e9-9d13-7a9f79249c8d.png)

**Comment by Shuaib08** [comment]
Okay I just tried to install the latest version of the console client and i got this..
![image](https://user-images.githubusercontent.com/53378457/61998070-44626380-b0a2-11e9-8555-7172233b2a20.png)

The files in the while boxes are the the key files here. Basically `MinecraftClientFix.exe` is the latest version of CC, and `Script1F.exe` is the script but inside I changed it to `mono MinecraftClientFix.exe (email address) (password) (server ip)`.

Seems to work but now I get the error message "Incorrect password, blacklisted IP or too many logins" even though i have literally no instances of minecraft open in client nor console client..

Any suggestions?

**Comment by Shuaib08** [comment]
Update : About 20 out of 51 Alts work but they crash after a few hours and spit out some random code.. The others just come up with the error "Incorrect password, blacklisted IP or too many logins" but I know the passwords are right, something to do with the VPS or the console client? Someone help me please and thanks.

**Comment by JordanAuthxr** [comment]
After logging in around 20 accounts mojang temp block logins from your IP, I'd suggest just waiting 1hr or so to start loading more. Your VPS might not have enough RAM for this many accounts (Causing the crashes)

**Comment by Shuaib08** [comment]
Oh thank you so much

**Comment by TheSnoozer** [comment]
Unfortunately there is not much from the perspective of the client we could do against the a `Incorrect  password, blacklisted IP or too many logins` which indeed usually indicates that Mojang temporary blacklisted the account/IP you used to authenticate after several authentication failures.

I'm closing this issue as answered. Feel free to open a new issue if you still got a question.
