### ISSUE TITLE
Console Client is not using config file. Linux. 

### ISSUE THREAD

**Issue by DustyDust1543** [ORelio/Minecraft-Console-Client#778]
Alright so I got a rasberry pi and when I open MinecraftClient.exe(using mono) it doesn't use the MinecraftClient.ini file. So it doesn't automatically log in and connects to a server. Also doesn't auto relog and auto reconnects. It runs fine when i use it on windows 10.

**Comment by ORelio** [comment]
Make sure you are invoking MCC from the directory containing Minecraft Console Client.
````bash
$ ls
MinecraftClient.exe MinecraftClient.ini
$ Mono MinecraftClient.exe
````
And **not**
````bash
$ ls
Music Pictures Downloads MCC
$ mono MCC/MinecraftClient.exe
````
In the second example, MCC will look for files in your home directory, and won't find the config file.

**Comment by TheSnoozer** [comment]
Please download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) that now also contains a message where the config is read from when starting the bot.

that should give some clarity what is going on.

**Comment by TheSnoozer** [comment]
Closing as part of an issue cleanup. Please download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) which should make the situation clearer. if you still got a problem feel free to reopen. For any other question please open a new issue.
