### ISSUE TITLE
Unable to log in alts on raspberry pi in a location near many mob spawners

### ISSUE THREAD

**Issue by PhantomJackfruit** [ORelio/Minecraft-Console-Client#780]
I am playing on a skyblock server, and I have access to grinders with 8,000+ spawners in each of them within a 16 block radius in every direction. The alts I use to AFK are in the center of all the spawners. When I try to /server skyblock, the alt that spawns into the spawners disconnects after 30 seconds without sending any scripted commands or kickmessage. I am currently running 16 alts on the pi with 2 alts AFKing 8,000+ spawner grinders. Every other alt can connect fine with fully functioning scripts and kickmessages except for the alts that AFK grinders with 8,000+ spawners. If I teleport the alts that AFK the grinders to a location without spawners (spawn) it can connect without any issues. If I constantly type any message into chat every few seconds, it forces the alt that AFKs near 8,000+ spawners to join. The alts that AFK the grinders connect fine on my windows 10 laptop, and the issue only happens on my raspberry pi 3B+. The raspberry pi connects with ethernet, and only uses 30% of its memory running 16 alts. I've used mono version 6.0.0.313 and 4.6.2 which both don't work. Terrainandmovements=false, AntiAFK has /ping set to every 60 seconds, exitonfailure=false, and every file in my console client folder is named or scripted correctly. The alts can connect and /server skyblock fine into grinders with 2,000 or less spawners, but the problem persists when grinders have 3,000 or more spawners. Below are some images of the issues described.
Disconnects if I have the alts /server skyblock into the mass of 8,000+ spawners after 30 seconds without sending any kickmessages/commands by scripts
![Git2](https://user-images.githubusercontent.com/50208027/62019927-92e92e00-b186-11e9-83eb-1fd7e4c0a29b.PNG)
Forcibly connects if I type a message (in this case 't') into chat every few seconds
![Git3](https://user-images.githubusercontent.com/50208027/62019930-94b2f180-b186-11e9-996c-58733c1fbc61.PNG)

**Comment by ORelio** [comment]
I suspect this is caused by too many entities slowing down the packet processing, but I must admit that I'm unsure about it. A new connection timeout detection was added as per #802. This might help detecting that connection has been lost although it may cause frequent reconnections in your case. You might want to try the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by PhantomJackfruit** [comment]
> I suspect this is caused by too many entities slowing down the packet processing, but I must admit that I'm unsure about it. A new connection timeout detection was added as per #802. This might help detecting that connection has been lost although it may cause frequent reconnections in your case. You might want to try the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

Yeah, it reconnects but is still unable to successfully connect to the game and disconnects again.

**Comment by ORelio** [comment]
How is the CPU of your Pi when you connect using the affected alts? I guess that when connecting, there is so much data to process that it takes more than 30 seconds and the server will disconnect MCC for not responding fast enough.

**Comment by PhantomJackfruit** [comment]
It goes from 6% to 30% as if starting up a normal console client terminal, though it stays at 30% despite disconnecting and goes back to 6% after I close the terminal.

**Comment by ORelio** [comment]
Ok 30% globally but does any core goes to 100%?
