### ISSUE TITLE
Auto Relog

### ISSUE THREAD

**Issue by D3rpCookies** [ORelio/Minecraft-Console-Client#781]
I download the new console client and its working fine but how would you be able to insert the autorelog system, because it says kickmessage.txt not found, how would i make it so that they can find a file that is the kickmessage.txt?

**Comment by TheSnoozer** [comment]
this is mine `kickmessages.txt` which works find with 1.8:
```
Attempting to attack an invalid entity
Bad login
Connection has been lost
Connection lost.
Disconnected
disconnect.spam
End Of Stream
Flying is not enabled on this server
Game over, man, it's game over!
Illegal characters in chat
Illegal position
Illegal stance
Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host.
Internal exception: java.io.IOException: Received string length longer than maximum allowed (105>100)
Internal Server Error
Internal Server Error:java.net.Minecraft
Kicked by an operator.
Outdated Client
Outdated server
Out of memory!
Read timed out
Server is full
Server is restarting
too many people
Too Many people
You have been idle for too long!
You have died. 
You seem to be logged in already.
```
When you play a different version just add things that pop up in console chat that you got kicked by....

**Comment by Mhowser** [comment]
Wouldn't it be simpler to detect the disconnect packet instead of matching kick messages?

**Comment by D3rpCookies** [comment]
> Wouldn't it be simpler to detect the disconnect packet instead of matching kick messages?

Agree so much, if it were able to detect disconnect packet, we wouldn't even need to worry about trying the find the disconnect/kick messages

**Comment by ORelio** [comment]
There is no disconnect packet besides the kick packet, so disconnections are treated internally by MCC as a `Connection has been lost` kick message. You can handle it in AutoRelog as explained by @TheSnoozer

As an answer was given, I'll close the issue, but you can reopen it if this is still unclear.
