### ISSUE TITLE
Error trying to join a server on Windows with build 228 (VarInt too big)

### ISSUE THREAD

**Issue by PaaBliiTo** [ORelio/Minecraft-Console-Client#782]
Hello,

Trying to connect to a server on Windows and getting error right after connecting to the server. See the attached picture for the error details : 

![Screenshot_3](https://user-images.githubusercontent.com/23000106/62387727-b4b62c80-b55b-11e9-826f-9360899f3dcd.png)

Any idea on how to fix this ?
Thanks :)

**Comment by ORelio** [comment]
Not sure whether terrain handling was fully tested for 1.14 (#773). Will have a look.

**Comment by Miwwe** [comment]
I have same error

**Comment by TheSnoozer** [comment]
I just tired this with the latest development build and everything seems to be working fine. I also verified all the Packet ID which seems to be fine.

Could you perhaps
1) share the server IP
2) share your `MinecraftClient.ini` without any credentials and any needed files like tasks.ini or whatever is enabled?

**Comment by TNTUP** [comment]
Happens again https://i.qcfb.ca/20191213170853.png. I'll try setting version to 1.12.2 maybe that will solve the crash

**Comment by ORelio** [comment]
@TNTUP You are not using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by ORelio** [comment]
Shoud be fixed as per #811 and #819
