### ISSUE TITLE
Logging into server disconnects minecraft console client

### ISSUE THREAD

**Issue by JimmyBringus** [ORelio/Minecraft-Console-Client#783]
Hello!

I'm using my minecraft account to login to the server with the Minecraft Server Client. 

However, when I attempt to connect to that server to play, it kicks the Minecraft Server Client that was connected. 

How do I fix?

**Comment by JimmyBringus** [comment]
![image](https://user-images.githubusercontent.com/8877150/62415667-943daf00-b5fb-11e9-9632-be90e088c4bc.png)

This is the code I get when I try to login to play

**Comment by ORelio** [comment]
You cannot login from multiple locations at once. Try running Minecraft on 2 different PCs and login to the same servers. The second client will disconnect the first one.

**Comment by JimmyBringus** [comment]
@ORelio - could an alternative solution be that I buy another copy of minecraft with an alt account and use it to run the server?

**Comment by ORelio** [comment]
Yes, you can do that.
