### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by mccoder5** [ORelio/Minecraft-Console-Client#784]
Looks like they are bundling trojans again suddenly detected a virus -- about to build from source to see if that helps this is pretty sketchy...

**Comment by ORelio** [comment]
Currently I have nothing with both Windows Defender and VirusTotal https://www.virustotal.com/gui/file/e361e3298e168622185bcadd0fac88bf6801f0330dfb78daa51c94c022317db4/detection ... could you provide more details about the detection?
