### ISSUE TITLE
Forward a specific message from an alt

### ISSUE THREAD

**Issue by KevinDenys** [ORelio/Minecraft-Console-Client#785]
![image](https://user-images.githubusercontent.com/17174443/62495531-74161780-b7d6-11e9-8e8f-7475e651a110.png)

I would like to forward these kind of messages from my alt to my real account

**Comment by TheSnoozer** [comment]
Better late than never:
As a starting point I would suggest to use https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-pm-forwarder.cs

as logic for the `GetText`:
```
public override void GetText(string text)
    {
        string pmRecipient = "putYourIgnHere";
        text = GetVerbatim(text);
        if (System.Text.RegularExpressions.Regex.Match(text, @"^.*Your sell chests have made \$[0-9]+ over the last.*$").Success) {
            LogToConsole("Forwarding Message to " + pmRecipient);
            SendPrivateMessage(recipient, text);
        }
    }
```

Untested.
