### ISSUE TITLE
It keeps staying like this might be bc of Ethernet connection idk

### ISSUE THREAD

**Issue by Soulsyt28** [ORelio/Minecraft-Console-Client#786]
Hey, can you try to help me please?

So i get this: 

https://imgur.com/a/Zou8EEx

thank you.
Souls

**Comment by porkiedev** [comment]
If I had to guess it has something to do with the way Hypixel's domain is set up, not sure though.
Also, cached session, haven't looked into it but maybe you have another account or MCC setup somewhere? I wish I could be of more help but I haven't looked into the part of the code where it says that so I can only give basic advice.

Also, isn't it hypixel.net? maybe mc-hypixel.net works too.

**Comment by ORelio** [comment]
Seems like the same issue as #858 ; try my response there and see if it helps.
