### ISSUE TITLE
Custom Tpaccept command

### ISSUE THREAD

**Issue by Nerivox** [ORelio/Minecraft-Console-Client#787]
Hello!

I really like your Project and i havent had many problems, except for one thing.
On the server my bot is running on i want it to autoaccept tpas. It technically works but the server has a custom /tpaccept command. The command is /tpy [Name]. Is there a way to change the autotpaccept command, if so please reply.
Thanks!!!

**Comment by ORelio** [comment]
Currently, no, but you can craft your own using AutoRespond:

````ini
[Match]
regex=^(Nerivox|Owner2|Owner3) has requested to teleport to you\.$
actionother=/tpy $1
````
The only issue is that it cannot detect bot owners on that kind of messages, you need to put them.

**Comment by Nerivox** [comment]
Thanks!!!

**Comment by Ansh51** [comment]
Hey what do i use if i want everyone to be able to use the mcc autorespond i mean like not only owner everyone

**Comment by ORelio** [comment]
By default, AutoRespond matches will trigger for anyone, that is unless you set `ownersonly=true` in your match. See [sample-matches.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini#L25).

**Comment by Ansh51** [comment]
> By default, AutoRespond matches will trigger for anyone, that is unless you set `ownersonly=true` in your match. See [sample-matches.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini#L25).

Its not responding idk why
