### ISSUE TITLE
Auto Respawn help

### ISSUE THREAD

**Issue by naf154** [ORelio/Minecraft-Console-Client#790]
Hello there,

I am currently trying to figure out a way to make it so when my alts die they automatically run the command /respawn (in console client not ingame), I've looked at some other posts about this but i dont really understand since im quite new to this stuff. Can someone please reply to this and tell me what to do. Thanks

**Comment by Spangonagornomb** [comment]
Has to do something with PerformInternalCommand()

But I cant get it work 

(You need to recompile the whole thing and have your own binary)

**Comment by ORelio** [comment]
I'd suggest AutoRespond with `match=<text that appears when you die>` and `actionother=respawn`. See also [sample configuration files](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config).

**Comment by naf154** [comment]
So do I make a file called Autorespawn.ini and put what you wrote above? Also the server I play on has auto respawn but my alts do not respawn automatically do you know why?

**Comment by ORelio** [comment]
Start off from [sample-matches.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini) and set it in the `[AutoRespond]` section of `MinecraftClient.ini`. You can name the file `autorespawn.ini` instead of `matches.ini` if you want.

**Comment by naf154** [comment]
Thank you I'm going to try that now, but can you tell me why my alts don't respawn automatically even though the server has auto respawn? Or is that just because the alts are on console client

**Comment by ORelio** [comment]
Not sure why the server is not respawning automatically, seems like this is a plugin. You may want to try enabling `terrainandmovements` in config, that would help if the plugin acts depending on your location.

**Comment by naf154** [comment]
kk quick update this is what i done on the respawn.ini
match = was slain by D_wil02
actionother=respawn

also can you tell me whether my match would work because this is what it actually says (alts ign) was slain by D_wil02 but i have multiple alts so would this just work instead? Ty

**Comment by ORelio** [comment]
That would trigger the `respawn` command whenever someone is slain by D_wil02, not necessarily yourself. However, if the console request a respawn when not dead, the server should just ignore the request so it does not seems a big issue.

**Comment by naf154** [comment]
k so in my minecraftcleint.ini i have this

[AutoRespond]
enabled=true
matchesfile=respawn.ini


and in my respawn.ini i have this:

match= was slain by D_wil02
actionother=respawn

however after i kill my alt nothing happenes do u know why? i sitll have to write /respawn

**Comment by ORelio** [comment]
Seems good. Make sure you don't have any unwanted spaces e.g. `match= was` is different than `match=was`. Also make sure you have `[Match]` before these two lines.

**Comment by naf154** [comment]
ahhh thanks i will reply in a bit saying if that worked ty<3

**Comment by naf154** [comment]
[Match]
match=was slain by D_wil02
actionother=respawn

this is what it is now, so whenever i kill my alts will it auto respawn or would i need to execute a command?

**Comment by ORelio** [comment]
If everything worlks, it should attempt to respawn automatically as soon as it sees the message.

**Comment by naf154** [comment]
it doesnt work :'(
but do am i able to do 2 matches so like this

[Match]
match=was slain by D_wil02
actionother=respawn

[Match]
match=was slain by Another ign
actionother=respawn

??

**Comment by naf154** [comment]
edit IT WOORKEEED TY SOOO FRICKING MUCH

also can u tell me why sometimes when i use the afk.bat file to log on loads of alts like 3 log in rest are New window, i put a 10 sec delay between each login but still doesnt work ( alll alts work btw)

**Comment by Spangonagornomb** [comment]
I solved it by doing /respawn every 3 seconds

**Comment by Spangonagornomb** [comment]
First you got to enable ScriptScheduler in "MinecraftClient.ini"
```
[ScriptScheduler]
enabled=true
tasksfile=tasks.ini
```

at tasks.ini
```
[Task]
triggerOnInterval=true
timeInterval=3
script=advanced-anti-afk.txt
```

at advanced-anti-afk.txt
```
move east
move south
respawn
```

That should do the trick make sure its moving sometimes and respawn's on a prv server :)

**Comment by naf154** [comment]
Thank you so much <3

Problem is fixed nowwww
