### ISSUE TITLE
Send a Specific Packet

### ISSUE THREAD

**Issue by FoamyTheFag** [ORelio/Minecraft-Console-Client#792]
As per [this](https://wiki.vg/index.php?title=Protocol&oldid=7368#Player_Block_Placement), I went into Protocol18PacketTypes.cs, and added `case PacketOutgoingType.BlockPlace: return 0x08;`

I tried to look around the files, but I could not find an example of a packet being sent.

**Comment by TheSnoozer** [comment]
There are not a lot of packets the client sends. Search for SendPacket.
E.g.:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#L253
where the client sends a `TeleportConfirm` packet.
