### ISSUE TITLE
Terrain & Movements currently not handled for that MC version.

### ISSUE THREAD

**Issue by AdrianKhorany** [ORelio/Minecraft-Console-Client#794]
When i am opening the client it would say Terrain & Movements currently not handled for that MC version and when i am writing in my other account move [x] [y] [z] it would say turn on terrain and movements but its already on

**Comment by Meka4756** [comment]
Terrain and Movements works only some minecraft versions. Its worked me on 1.12.2

**Comment by Patchuu** [comment]
Any update on this for 1.14.4?

**Comment by cobrasrock** [comment]
It's there for 1.14.3 I don't know why it's not for 1.14.4 yet

**Comment by cobrasrock** [comment]
I updated it myself. I am not sure about the stability. I only changed 2 values. I can send you the file if you want.

**Comment by Patchuu** [comment]
@cobrasrock  yes, please.

**Comment by cobrasrock** [comment]
Yeah. Here is the download.
http://www.mediafire.com/file/8amo9wd2kxxtyrt/MinecraftClient.exe/file

**Comment by ORelio** [comment]
Marked version as supported in the main repository, but I'll let you test if everything works.
Reminder: I'm still looking for maintainers! MCC is slow to update due to a lack of maintainers.

**Comment by colhaydutu** [comment]
> Yeah. Here is the download. http://www.mediafire.com/file/8amo9wd2kxxtyrt/MinecraftClient.exe/file

hello do you have for 1.18.1 ?
