### ISSUE TITLE
Connection lost. when interacting with MCC

### ISSUE THREAD

**Issue by DanSC11111** [ORelio/Minecraft-Console-Client#796]
Whenever I open the mcc everything runs fine, but sometimes when i try to type something in the server or to run a command in the server the mcc disconnects without a message and sends Connection lost. Only when I try to interact with it again, so neither autorelog helps and antiafk doesn't work too for some reason. Pleaee help me.
Anti afk runs every 1 minute /server opsb
And i have connection lost. Message in the kickmessages.txt, but it doesn't help because it only sends the message when I interact with the mcc again. This probelm makes me lose full nights of afk just because i wanted to check my balance in the server

**Comment by ORelio** [comment]
Should be resolved as per #802. Please try out the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
