### ISSUE TITLE
Auto-Reconnect

### ISSUE THREAD

**Issue by Liric95** [ORelio/Minecraft-Console-Client#797]
Been using console client for over a year now and recently my internet has been cutting out overnight and it's very annoying when afking spawners. I can reconnect most of the time, with a server restart and things like that. But when my internet goes out and it completely disconnects, it just sit theres. I was wondering if there is a way to automatically reconnect after you get this message. https://prnt.sc/ozgqnr

**Comment by ORelio** [comment]
Silent disconnect without `Connection has been lost` message should be resolved as per #802. Please try out the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). You can reconnect using AutoRelog and putting `Connection has been lost` inside `kickmessages.txt`. Feel free to reopen if this is still unclear.
