### ISSUE TITLE
Need Right Click to Npc

### ISSUE THREAD

**Issue by Meka4756** [ORelio/Minecraft-Console-Client#798]
Hello. Needed right click to a NPC (creative , minigames , survival..) to connect some servers. I didnt found a way to right clicking.

**Comment by AggroMC** [comment]
Mei pech host hoid khod, mia kinans a ned ändern.

**Comment by Meka4756** [comment]
> Mei pech host hoid khod, mia kinans a ned ändern.

Can you write in English?

**Comment by ORelio** [comment]
This is currently not implemented. Closing as duplicate of #183
