### ISSUE TITLE
Console Client VPS Network error.

### ISSUE THREAD

**Issue by KickLouis** [ORelio/Minecraft-Console-Client#799]
Hello, Before opening this I have looked at many issues nothing seems to really fix mine. I am using a ubuntu VPS on vulture with an MCC.

I have installed mono.

My startup script reads as follows:
mono MinecraftClient.exe myemail mypassword play.skycade.net

When starting up this script which is saved as a .bat file I get this:
https://gyazo.com/d46a96316ed88cef7f490d4a7ec68f3c

As I said I have already tried many things from other people's issue's nothing seems to work!

My config:
[Myconfig.txt](https://github.com/ORelio/Minecraft-Console-Client/files/3585399/Myconfig.txt)

I hope you guys can help me out!
Thanks in advance

**Comment by ORelio** [comment]
Your VPS is likely blacklisted by Mojang. Try `debugmessages=true` to gain more details but make sure to redact anything looking like an email, password or random hexadecimal string.
