### ISSUE TITLE
MCC not detecting connection timeout

### ISSUE THREAD

**Issue by UnseenElements** [ORelio/Minecraft-Console-Client#802]
I use console client like most to keep alts online. Recently I have started to see that the client's chat will stop and they will disconnect without anything getting put into the chat like a boot message. I have to type something and then it will finally say connection lost in the chat but sometimes I have to do a full relaunch. Can provide what is needed.

**Comment by ORelio** [comment]
We have so many issues and so few maintainers 😰

**Comment by Mhowser** [comment]
Is it getting to the point where this project needs to be rebuilt from the ground up?

**Comment by ORelio** [comment]
I don't think so, eg. for this issue we would need to implement some kind of connection timeout. The vanilla client times out after 30 seconds.

**Comment by Liric95** [comment]
Do whatever you have to do, I beg.

**Comment by UnseenElements** [comment]
Yea, it makes my alts very unreliable

**Comment by ORelio** [comment]
Implemented as per latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). Issues are individually not very hard to tacle, but we're lacking contributors for that and I'm lacking time to work on them myself.

**Comment by SkittyChips** [comment]
Good idea doesn't work.

**Comment by ORelio** [comment]
> Good idea doesn't work.

@SkittyChips: Should be fixed as per #1219 thanks to @ReinforceZwei's findings 🙏
