### ISSUE TITLE
Login Failed Security Questions?

### ISSUE THREAD

**Issue by Culup** [ORelio/Minecraft-Console-Client#803]
Whenever I try to log in I get this:

Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.
Not connected to any server. Use '/help' for help.

I believe this is due to my minecraft.net security questions. Is it? And if so how do I get rid of them.

**Comment by ORelio** [comment]
MCC does not implement security questions. You may want to login using Minecraft vanilla and let MCC import your session data. Set debugmessages=true to see more login info and copy the session ID for your account into sessioncache.ini, then move it along MCC to any other system.

**Comment by Pokechu22** [comment]
I don't think security questions are ever needed to log in to play the game; they're only needed to change settings (e.g. skins).  Unless mojang changed something recently, that is.

**Comment by ORelio** [comment]
Yep, this can also be caused by your IP being blacklisted if you use a VPN or VPS.
See issues mentioned in a37e340613031e61a464b7fc9c77b02bcd361e6b

**Comment by KTownMonkey** [comment]
I am having this same issue, but its with any server IP i enter in. All was running fine today, i lost my internet in my house and had to restart my router after this i couldn't log any of my accounts into any server. Anything that can help? 

> MCC does not implement security questions. You may want to login using Minecraft vanilla and let MCC import your session data. Set debugmessages=true to see more login info and copy the session ID for your account into sessioncache.ini, then move it along MCC to any other system.

I dont understand fully on what to do here, i set debugmessages=true but how do i let MCC import my session data and where do i copy my session ID? then move sessioncache.ini to any other program?? for what editing?? i dont get this xD

**Comment by KTownMonkey** [comment]
.
