### ISSUE TITLE
mc console client missing kick messenges

### ISSUE THREAD

**Issue by IAmToxicAf** [ORelio/Minecraft-Console-Client#804]
i have everyting setup and i get this but when i downloaded it is was not in the file
![Knipsel](https://user-images.githubusercontent.com/55550633/65259976-e718ea80-db05-11e9-8849-f9f20634a419.PNG)

**Comment by IAmToxicAf** [comment]
![Knipsel](https://user-images.githubusercontent.com/55550633/65260031-ff890500-db05-11e9-8b6c-18ee0daa9cf5.PNG)

**Comment by ORelio** [comment]
As stated in [Readme.md](https://github.com/ORelio/Minecraft-Console-Client/blob/master/README.md), see [sample configuration files](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config).
You can also create your own from scratch, one message per line.
