### ISSUE TITLE
RemoteControl not working to detect chat

### ISSUE THREAD

**Issue by Yertled** [ORelio/Minecraft-Console-Client#807]
I tried the past few hours to configure this regex code thingy magic that I still don't know how works, but here is my code for private messaging:

private=(^.+[a-zA-Z]]) (.+)$

what the chat looks like:
https://i.imgur.com/RktAfDX.png

works according to regex:
https://i.imgur.com/QJlNRjY.png

[RemoteControl]
enabled=true
autotpaccept=false
tpaccepteveryone=false

ChatFormat:
https://i.imgur.com/9WLzgFG.png

Help?

**Comment by ORelio** [comment]
You are almost there: The first group should only contain the username of the sender, also add `^` on beginning to match beginning of line.

I'd suggest the following regex:
```
^\[(?:[^ ]+ )?([a-zA-Z]+) -> me\] (.+)$
```
`^` and `$` match beginning and end of line, respectively
`\[` and `\]` match the brackets without being considered as regex characters
`(?:TEXT)?` makes an optional non-matching group
`[^ ]` matches any amount of characters except space
so `(?:[^ ] )?` allows to skip the `Owner ` tag when present
`([a-zA-Z]+)` is the group for the username
`(.+)` is the group for message contents
See more details at https://regex101.com/r/NuTTgR/3 😉
