### ISSUE TITLE
Bandwidth and power usage on a raspberry pi 4?

### ISSUE THREAD

**Issue by tailis** [ORelio/Minecraft-Console-Client#810]
I plan on running about 10 - 30 Minecraft accounts on mine saga on islands to afk. I plan to do this on a raspberry pi 4. Would anyone like to give me an estimate as to how much bandwidth ( in mb) and power (in kWh) it would use in a day? Thanks a lot.

**Comment by ORelio** [comment]
Hello, on Raspberry Pi, I heard of various issues related to the Mono framework so MCC might not work very well but you can try it out. Using text only (ie terrainandmovements=false), the amount of data sent by MCC is almost zero, however the server sends terrain data initially, then entity data, chat messages and so on, so it depends of activity on your server and is the same as regular Minecraft. You can consider that it's less than 100kib/s for one Idle client. Cant say for power consumption, but MCC does not use much CPU in text-only mode.
