### ISSUE TITLE
Movement as Anti AFK

### ISSUE THREAD

**Issue by Batx** [ORelio/Minecraft-Console-Client#814]
Hey, i love the MCC it works great, but i enabled movement and the player moves if i send him somewhere but i placed him in an AFK machine with water and he doesn't move automatically he seems somehow immune...

**Comment by ORelio** [comment]
MCC does not implement water (the server does not push you, it's your minecraft game that detects water and automatically moves the player). If you wish to AFK, you can make a simple script:
```
move west
sleep 10
move east
````
And schedule it every few minutes using script sheduler.

**Comment by Batx** [comment]
Thank you!
