### ISSUE TITLE
Enhancing Reusability

### ISSUE THREAD

**Issue by beppe9000** [ORelio/Minecraft-Console-Client#82]
My 2 cents...

I have seen how the GUI is implemented and I think that a better way could be having a common library that is referenced from both CLI and GUI: this would enable other developers (like myself) to make use of the chat system in bigger (or smaller :) ) projects by directly including the code for the library (and no "shell redirection").

So far everything is strictly tied to console features, which make it hard using the code from non-console programs.

I'm not so proficient in C# as I am in VB so I'd rather not venture into this personally (altought I may in future).

**Comment by ORelio** [comment]
Hello,
You can disable advanced pronpt by supplying `BasicIO` as the very last argument.
Then you can properly redirect input and output and do whatever you want with MCC.
Plus, color codes will be given in raw `§c` format so that you can handle them... or strip them.

**Comment by ORelio** [comment]
As currently no library is planned and the `BasicIO` feature seems to have worked for you, I'm closing the issue for now. Feel free to reopen if needed ;)
