### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by TimBilliet** [ORelio/Minecraft-Console-Client#821]
I'm running the console client on a raspberry pi with raspbian
when i start it with the command mono minecraftclient.exe it gives a network error even though i'm connected through ethernet

**Comment by TheSnoozer** [comment]
Error Message?

**Comment by TimBilliet** [comment]
so my problem changed, first it said network error now it says unsupported protocol version 498, i changed some stuff
https://imgur.com/fjS595k

**Comment by TheSnoozer** [comment]
For me this sounds that the server does not support protocol version 498.

Could you perhaps try to set a fixed version inside your MinecraftClient.ini like `mcversion=1.8.0`?

**Comment by TimBilliet** [comment]
thanks, that worked

**Comment by TheSnoozer** [comment]
Thanks for confirming. I'm going ahead and close. if you got any other issues or questions feel free to open a new issue.
