### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by KTownMonkey** [ORelio/Minecraft-Console-Client#824]
Whenever I try to log in I get this:

Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.

Its with any server IP i enter in. All was running fine today, i lost my internet in my house and had to restart my router after this i couldn't log any of my accounts into any server. Anything that can help?

This is quoted off another post on site that the original poster closed, (MCC does not implement security questions. You may want to login using Minecraft vanilla and let MCC import your session data. Set debugmessages=true to see more login info and copy the session ID for your account into sessioncache.ini, then move it along MCC to any other system.)

I dont understand fully on what to do here, i set debugmessages=true but how do i let MCC import my session data and where do i copy my session ID? then move sessioncache.ini to any other program?? for what editing?? i don't get this xD

**Comment by ORelio** [comment]
Hello,

Setting `debugmessages=true` allows you to see the login request and login response, so it helps determining why the login attempt fails.

When logged in in Minecraft, your session information is stored by the Minecraft game, and MCC can go into the Minecraft folder and load what's stored inside. `debugmessages=true` will show where MCC loads stored session information.

You can copy the session ID shown in console and paste it into `sessioncache.ini` by putting the appropriate comma-separated values (a comment inside the file shows how to put the values). This way, MCC does not need to access your Minecraft folder anymore.
