### ISSUE TITLE
UnauthorizedAccessException on SessionCache.ini

### ISSUE THREAD

**Issue by UnseenElements** [ORelio/Minecraft-Console-Client#825]
![image](https://user-images.githubusercontent.com/48160812/68032482-cc509e80-fc8b-11e9-9aba-764812996b53.png)
This is what happens to every alt I try to log onto this server. No idea how to fix and would love some help <3.

**Comment by ORelio** [comment]
Seems like MCC cannot create `SessionCache.ini` due to permission on the `Alts` folder. Is it read-only?

**Comment by UnseenElements** [comment]
I don't believe so as it was working fine yesterday.

**Comment by UnseenElements** [comment]
Im sorry
It was read-only for some reason.

**Comment by ORelio** [comment]
At least it's resolved 😉
