### ISSUE TITLE
Client version not supported

### ISSUE THREAD

**Issue by Badbird-5907** [ORelio/Minecraft-Console-Client#826]
Hi there,
I play on saicopvp but how can i switch minecraft versions?
I would like to play on 1.12.2 as it is supported.
Thanks in advance.

**Comment by Mhowser** [comment]
Mcc should automatically detect that it's 1.12.2, if it doesn't, open
Minecraftclient.ini and change the version setting to 1.12.2

**Comment by Badbird-5907** [comment]
k thanks
