### ISSUE TITLE
Velocity not handled?

### ISSUE THREAD

**Issue by Keagel** [ORelio/Minecraft-Console-Client#827]
I have an AFK pool with the player standing in the water and it doesn't move at all.

**Comment by Mhowser** [comment]
You need to enable terrain movements in the config file.

Terrainmovements=true in mincraftclient.ini

**Comment by Keagel** [comment]
I just did that and it doesn't seem to do anything, player still isn't moving.

**Comment by Keagel** [comment]
Nevermind, just saw in previous issues that this isn't implemented with water.

**Comment by Mhowser** [comment]
What game version is the server on?
