### ISSUE TITLE
Auto Respond Issue with regex

### ISSUE THREAD

**Issue by MrDietPeppsi** [ORelio/Minecraft-Console-Client#829]
So trying to get an account to automatically /f invite $u, 
Chat format is ((Cloud) MrDietPeppsi -> me) invite

My regex currently is `\(\([^]]+\)? ([a-zA-Z0-9_]+) -> me\) (.+)$`

```ini
#Do not forget to uncomment (remove '#') these settings if modifying them
builtins=true                      # MCC built-in support for common message formats
# public=^<([a-zA-Z0-9_]+)> (.+)$
private=^\(\([^]]+\)? ([a-zA-Z0-9_]+) -> me\) (.+)$
# tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$
```

Sorry for the trash format, not sure how to change it was tinkering around but couldnt figure it out

Auto respond on and matches-

```ini
[Match]
match=invite
actionprivate=send /f invite $u
ownersonly=false

[Match]
match=coleader
actionprivate=send /f coleader $u
ownersonly=false
```

**Comment by ORelio** [comment]
Hello,

Just edited your post to use INI formatting, you can edit it again to have a look on how to do it ;)

You regex looks good, but `builtins=true` might conflict with it. You may want to also add a regex for public messages and set `builtins=false`. Additionally, I'd suggest this regex to handle cases where the username has no title e.g. not the `(Cloud) ` part in front of it:

```
^\((?:\([^]]+\) )?([a-zA-Z0-9_]+) -> me\) (.+)$
```

Try it out: https://regex101.com/r/2sMw4i/1
