### ISSUE TITLE
Console client /tpaccept

### ISSUE THREAD

**Issue by Bleedtill** [ORelio/Minecraft-Console-Client#832]
can you do a youtube video showing how to make the bot accepting botowner ..

**Comment by ORelio** [comment]
No, unless a video maker wishes to make MCC tutorials. As per [README](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config) you need:
1) Make sure chat messages are properly detected. Use [sample-script-with-chatbot](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) to test.
2) Define `botowners=YourAccountName` in `MinecraftClient.ini`
3) Enable RemoteControl in `MinecraftClient.ini`
