### ISSUE TITLE
Acc's keep getting reset

### ISSUE THREAD

**Issue by EpicRoot** [ORelio/Minecraft-Console-Client#835]
Hi, Whenever i load up console client my password keeps getting reset by Mojang.

I get the email "Due to recent suspicious activity in your account we suspect that your Mojang account email and password may have been compromised."
I change the password then try to relog console client and it happens again.
An issue with CC or not?

**Comment by ORelio** [comment]
Haven't heard of that before, but it may be due to using a VPN or a VPS in a different contry?
