### ISSUE TITLE
1.15.1 Version Support

### ISSUE THREAD

**Issue by DiscordPug** [ORelio/Minecraft-Console-Client#836]
Hello, can you add 1.15.1 version support? My Friend's server Version is 1.15.1 and cannot join with 1.15.0.

**Comment by Redstone-ray** [comment]
Confirmed that the client only work up to 1.15.0

**Comment by Bas950** [comment]
Same doesnt work for 1.15.1

**Comment by jermsmit** [comment]
Sam, 1.15 was updated to 1.15.1 we need to have this protocol support added.  Thanks

**Comment by Mhowser** [comment]
It's quite simple to do actually, look at [ProtocolHandler.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs) line 114. Just add the protocol version for 1.15.1 (look on wiki.vg) and add it at the end. Then after line 216 add 1.15.1 and the protocol number, use the same format as the previous versions.

**Comment by Mhowser** [comment]
^ I'll just make a pull request once I get home in an hour or so.

**Comment by Mhowser** [comment]
Done https://github.com/ORelio/Minecraft-Console-Client/pull/837/commits/5104c5f3b564ba18b8de96800bb59cb4d9f0b78f

Just need @ORelio to merge it.

**Comment by ORelio** [comment]
1.15.1 is now added to the main branch. Thanks @Mhowser for contributing. Merry Christmas!
