### ISSUE TITLE
Baritone integration

### ISSUE THREAD

**Issue by mrphax0r** [ORelio/Minecraft-Console-Client#840]
The current pathfinding is good, but there's [Baritone](http://github.com/cabaletta/baritone).
It's functionality is outstanding, and it's under the LGPLv3. It also doesn't fail on half blocks. You might consider integrating it.

**Comment by Mhowser** [comment]
I remember asking for this, the problem is that baritone is Java and MCC is C#, 2 different codes.

**Comment by mrphax0r** [comment]
Yeah, Theoretically one could rewrite Baritone in CSharp, but that's not going to happen.
