### ISSUE TITLE
Avira issue

### ISSUE THREAD

**Issue by Govindass** [ORelio/Minecraft-Console-Client#841]
my antivirus (Avira) keeps constantly deleting Minecraft console client .exe files saying that it is a virus, I am aware that it is false alert, but this is really annoying - I keep needing to re-download it constantly, it would be nice if fixed.

**Comment by skyrawr** [comment]
delete avira, it's trash.

**Comment by ORelio** [comment]
It seems like it is a false positive. You should submit the exe file to your Antivirus provider or use another Antivirus software. For your information Windows 10 comes with Windows Defender for free.
![image](https://user-images.githubusercontent.com/1128206/73020954-ecc16c80-3e26-11ea-8bbe-40e59f89e30e.png)
https://www.virustotal.com/gui/url/4a79e6b90d5cac8f285a19a44551aeecf7b06d57350827e871281f4c4335b8c4/detection

**Comment by Govindass** [comment]
windows defender doesn't work for me, I don't know why, I tried a lot of google ways to fix it, that is why I got avira
