### ISSUE TITLE
/send or any submitted /send command works only once

### ISSUE THREAD

**Issue by AkaCrafterCZ** [ORelio/Minecraft-Console-Client#843]
Hi, I'm mainly using MCC to afk at our spawners on a factions server. The server reboots every 3 hours and when it does, all current players are put on the lobby. I made a script that runs every 3 hours and does /server factions. 
If the bot stays there for two reboots, it successfully runs the script, but nothing happens and the command is sent but not executed. Using /send to say a message to the chat still works. 
What can I do?

**Comment by ORelio** [comment]
Command not sent on relog was fixed in issue #427, make sure you have the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
