### ISSUE TITLE
Client gets disconnected for no reason without message

### ISSUE THREAD

**Issue by BlexMC** [ORelio/Minecraft-Console-Client#844]
Hello,
as already stated above, the Client, which I run on a VPS, keep disconnecting for no reason. Sometimes it works for hours fine but then, the Client gets disconnected for no reason. Only when I try to write something the AutoRelog starts working and connects me back to the server.
Is there any solution to prevent this?

Thanks

**Comment by sket0714** [comment]
i tried to enable antiafk and keep sending random /help command to the server every 1 min, and it work for me

**Comment by BlexMC** [comment]
> i tried to enable antiafk and keep sending random /help command to the server every 1 min, and it work for me

Hmm, I'll try that, thanks.

**Comment by BlexMC** [comment]
It definitely worked better but the issue still happens!

**Comment by ORelio** [comment]
Hi, `libmono-reflection-cil` should be necessary for proper operation of MCC, it comes as a separate package not included in `mono-runtime`, hence the longer command. However, if you do not have `libmono-reflection-cil`, MCC should crash, not disconnect silently.
