### ISSUE TITLE
new to console client, read a bunch of issues including #579 which is very similar but i still dont know what is wrong with this match code.

### ISSUE THREAD

**Issue by EpicSpoon** [ORelio/Minecraft-Console-Client#846]
im new to console client and i just learned about matches was trying to do some for my cc but i cant figure whats not working this is the match.ini file 
![code1](https://user-images.githubusercontent.com/60121785/72769816-f0b97880-3bf3-11ea-9b38-9a6c666d9fcb.PNG)
as you can see i ve tried multiple things and the only thing that seems to work is the second one the one reacting to the balance which i tested by just manually doing /bal on the cc since the first match wasnt working 

at this point i was so lost i started tryng to do some other things like this 
![image](https://user-images.githubusercontent.com/60121785/72769923-455cf380-3bf4-11ea-8a21-c4228c971706.png)
but still nothing i really dont understand why the matches are not working

this is the chat the cc is receiving btw 
![code3](https://user-images.githubusercontent.com/60121785/72769990-750bfb80-3bf4-11ea-885e-ea9de3a7c835.PNG) 
im currently nicked to Epic and using a color code so the name "Epic" is red
my unnicked username normally is EpicSpoon_ but i still tried both of these on the match and none of them worked so im lost

**Comment by ORelio** [comment]
`actionother` is for anything but public and private messages.
For private messages you can simply use the built-in private message match.
This will remove the `[Epic -> me] ` header and run the match against the message alone.

MinecraftClient.ini
```ini
botowners=Epic
```ini
Matches.ini
```
[Match]
match=bal
ownersonly=true
action=send /bal
```

**Comment by EpicSpoon** [comment]
Thank you orelio it worked
