### ISSUE TITLE
Enable "terrainandmovements"

### ISSUE THREAD

**Issue by BlexMC** [ORelio/Minecraft-Console-Client#848]
Hello,
for some reason the feature "terrainandmovements" isn't working for me. I've set it to 'true' but the account still doesn't gets knockback, picks items up, moves in AFK pools etc. I've restarted the Client and even the whole VPS multiple times.
 Or do I have to do anything else?
Thanks!

**Comment by Chtholly** [comment]
Knockback and afking in Water is currently not handled.
Pickup Items should work normal, when the inventory is empty

**Comment by BlexMC** [comment]
> Knockback and afking in Water is currently not handled.
> Pickup Items should work normal, when the inventory is empty
Oh okay, didn't knew these 2 features wont work. Even though, pickup doesn't works even he has a empty inventory.
