### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by Baeguls** [ORelio/Minecraft-Console-Client#849]
Hello! I play on a server with a strict alt/ip limit. The max is 10, and I'd like to bypass that number whilst on the same computer. I figured the best way to go about this was to use a proxy, and after testing nearly 40 none of them work. Changing the game version from 1.13 to 1.8.9 made a difference, however the furthest I've gotten into connecting to the server is logging in to Mojang's authentication server; below I've posted my proxy settings and a few of the error messages. I have set sessioncache to disk and have experimented with login. 

> [Proxy]
> enabled=true                         # Use 'false', 'true', or 'login' for login only
> type=HTTP	                           # Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
> server=70.91.117.165:8080	   # Proxy server must allow HTTPS for login, and non-443 ports > > for playing
> username=                              # Only required for password-protected proxies
> password=                               # Only required for password-protected proxies

A few frequent errors:
Minecraft login failed : Network error
Blacklisted Ip, too many logins, or incorrect password
Will login, but can't connect to server from there.

So I guess this boils down to two questions:
1. Is there any glaring mistake I'm making? If not, is there a place where I can get reliable proxies, preferably free?
2. Does anyone have any advice on bypassing the alt/ip limit? I'm open to anything

Thanks in advance!

**Comment by ORelio** [comment]
Everything is correct, but many public proxies will enforce limits on whether you are allowed to connect to port 25565 (minecraft) and may also enforce a time limit (e.g. disconnect after 30 seconds) so it won't work using every proxy. Finally, Blacklisted IP may denote that your proxy is banned from using the login servers.

**Comment by Baeguls** [comment]
Ahh got it, thanks so much. I have one last question: any advice on where I can get a few proxies with all of the qualifications you mentioned? I don't mind paying.

**Comment by ORelio** [comment]
Unfortunately not, that feature was added upon user request, I barely used it myself.

**Comment by Baeguls** [comment]
Ok, thanks for your help. I will continue on my search for a functional proxy :I
