### ISSUE TITLE
1.15.2 and higher version support?

### ISSUE THREAD

**Issue by RacistTim** [ORelio/Minecraft-Console-Client#850]
Can there be a new release of Console Client for 1.15.2 or higher, kinda annoying, I wish servers didn't specify their exact version like 1.15.x should just be supported but than again 1.11.2 made changes from 1.11.1 or 1.11 but it's annoying but if this could be added that would be great.

**Comment by Mhowser** [comment]
Look at this pull request #837, its so easy you can do it yourself.

**Comment by rrvk** [comment]
I have made a pull request #855  for 1.15.2 so if that one is looked at and merged, you can use it for 1.15.2

**Comment by ORelio** [comment]
Implemented by @rrvk 👍
