### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by KyanG7** [ORelio/Minecraft-Console-Client#851]
I am attempting to use my bot in an AFK Pool but the bot just stands there in the water doing nothing. Sometimes the bot also gets kicked for flying because it doesn't fall. Is there a way to fix it or just make the bot free move? /move works just fine its just standing still in water is the problem.

**Comment by Mhowser** [comment]
MCC does not handle liquid mechanics yet, you can just make an afk script
to do /move every X minutes back and forth.

**Comment by Tiebe** [comment]
When will liquid mechanics get implemented? This is not really an solution, since I would like to use water in my bot design.
