### ISSUE TITLE
How to build the project into an exe file?

### ISSUE THREAD

**Issue by Krabapel** [ORelio/Minecraft-Console-Client#853]
I've already seen that it's pretty simple to implement newer versions. 

https://github.com/ORelio/Minecraft-Console-Client/commit/aba2ec79d1666e2d777811691d00dc843d97b562

But I have no idea how to compile the files into an .exe-file, to use it like the developlent build. And besides me there might be several others with the same Lack of knowledge. :smile: 

Would it be possible to add a line like "version" and "protocol version" into the MinecraftClient.ini in which the user could write like "1.15.2" and "578"?

Thanks!

**Comment by Mhowser** [comment]
All you need to do is make a pull request. Once it is merged, it will be
built into an EXE automatically.

**Comment by rrvk** [comment]
I already made a pull request #855  for 1.15.2 with the new protocol version ;)

**Comment by ORelio** [comment]
In order to compile the project, the command is `msbuild MinecraftClient.sln`. I think this command is part of .NET framework but may not be directly available in command-line `PATH`. Another way is opening the solution in Visual Studio and compiling from there.

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client#building-from-source
