### ISSUE TITLE
Relog Issue

### ISSUE THREAD

**Issue by AshCantCannon** [ORelio/Minecraft-Console-Client#854]
So i’m currently using MCC on an ubuntu vps. everything’s all good until reboots for the server happens. (https://imgur.com/a/azsNzdC) that’s a screenshot of it. basically reboot happens, MCC goes to restart and it gets login failed message with CosmicProxy being the reason, MCC doesn’t restart itself after that and fails to connect to server. I’ve tried adding all lines to kickmessages. Anyone know what’s going on. or what i could do to fix it. Thanks! (PS i have no clue how to make a script)

**Comment by ORelio** [comment]
Are you using a recent development build? A connection timeout detector was added in #802

**Comment by AshCantCannon** [comment]
I was running 1.12.2, I just updates. Will update on if it fixes issue or not.  Thanks for response!

**Comment by AshCantCannon** [comment]
Update
I updated to versions 1.15.2 and the same thing is still happening.

**Comment by ORelio** [comment]
What is CosmicProxy?

**Comment by AshCantCannon** [comment]
I honestly don’t know, it’s just one of the kick messages you get.

**Comment by xthrane** [comment]
Hi AshCantCannon.
I have an autorelog issue too; however, when mine says "Connection has been lost" my console client doesn't restart like yours.
How did you manage to do that?

**Comment by SkittyChips** [comment]
> Hi AshCantCannon.
> I have an autorelog issue too; however, when mine says "Connection has been lost" my console client doesn't restart like yours.
> How did you manage to do that?

Exactly how do I get the relog to work? The silent reconnect patch doesn't work.
