### ISSUE TITLE
Failed to connect to IP / DNS SRV Record

### ISSUE THREAD

**Issue by H4mm1** [ORelio/Minecraft-Console-Client#858]
I have MCC running fine on my primary computer now I'm trying to get it on my back up and im not having the same success. I have already gotten past a few other messages but I cant do anything about this failed to connect to this IP message. I have specified the version and everything is the same as my other computer.

Resolving mythcraftpvp.com...
Connecting to Minecraft.net...
Using Minecraft version 1.15.2 (protocol v578)
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 104.31.94.84:25565
Failed to connect to this IP.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by ORelio** [comment]
That's because this server has a SRV domain name record but you have `resolvesrvrecords` disabled.
```
Resolving mythcraftpvp.com...
Found server mythcraftpvp1.ddns.net:25565 for domain mythcraftpvp.com
```
You need `resolvesrvrecords=true` (or `=fast`) in your `MinecraftClient.ini` to resolve this domain.

**Comment by H4mm1** [comment]
Thanks for the quick response! I already had `resolvesrvrecords=true` anything else that could be the problem?

**Comment by ORelio** [comment]
Sorry but I cannot reproduce your issue:
```
> MinecraftClient.exe
Console Client for MC 1.4.6 to 1.15.2 - v1.15.2 - By ORelio & Contributors
AppVeyor build 249, built on Tue 02/11/2020 from commit 9b9d402
Login : <redacted@email.com>
Password : <******>
Connecting to Minecraft.net...
Server IP : mythcraftpvp.com
Resolving mythcraftpvp.com...
Found server mythcraftpvp1.ddns.net:25565 for domain mythcraftpvp.com
Retrieving Server Info...
Server version : 1.15.2 (protocol v578).
Downloading 'en_GB.lang' from Mojang servers...
Done. File saved as 'lang\en_GB.lang'
Version is supported.
Logging in...
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server.
--------------------------------------------------

 -[---[-< Mythcraft >-]---]-
 Discover mythical creatures only spoken about in legends

 STORE: buy.mythcraftpvp.com ❤ 75% SALE ❤
MCC: Link: http://buy.mythcraftpvp.com
 FORUMS: mythcraftpvp.com
MCC: Link: http://mythcraftpvp.com
 DISCORD: mythcraftpvp.com/discord
MCC: Link: http://mythcraftpvp.com/discord

--------------------------------------------------
(!) Welcome <Redacted> to Mythcraft! Will you stand among the gods? (#3,430)
>
```
