### ISSUE TITLE
Custom Server-side menu

### ISSUE THREAD

**Issue by beppe9000** [ORelio/Minecraft-Console-Client#86]
I suppose this is not implemented.. but ... 
How can we use an interactive inventory-based menu? Some servers use these in their hub to let people select sub-servers.like this: http://www.curse.com/bukkit-plugins/minecraft/createyourownmenus

**Comment by ORelio** [comment]
Currently inventories are not handled at all. However most hubs are based on BungeeCord and the `/server [servername]` command is usually not disabled so that you should be able to do `/server` to list servers, then `/server <name>` to go to the desired server.

**Comment by beppe9000** [comment]
looks like it is disabled :(

**Comment by ORelio** [comment]
Oh, snap. Handling inventories would be quite time consuming, so I'm leaving your issue open, maybe inventories will be handled in the future, but currently this is not planned :/

**Comment by ZizzyDizzyMC** [comment]
This will be my next issue to tackle if I can get the time and find the knowledge.  Commenting here for reference later and to show that this is being actively thought about if not being worked on at the moment.

**Comment by ORelio** [comment]
In the process of sorting the issues sections, I'll close this one and leave #205 open instead.
