### ISSUE TITLE
.exe takes wrong path for the .ini on rasbian buster

### ISSUE THREAD

**Issue by JesperKuipers** [ORelio/Minecraft-Console-Client#862]
The executable always takes his settings from MinecraftClient.ini in /home/pi instead of his real path which is /home/pi/Desktop/MineCraftConsoleClient.
I tested it on windows where it takes the real path, so looks like a linux issue?

**Comment by ORelio** [comment]
You are launching it from your home directory.
Use
```
~$ cd /home/pi/Desktop/MineCraftConsoleClient
~/Desktop/MineCraftConsoleClient$ mono MinecraftClient.exe
```
instead of
```
~$ mono /home/pi/Desktop/MineCraftConsoleClient/MinecraftClient
```

**Comment by JesperKuipers** [comment]
Sorry for seeing this so late, but I'm using buster desktop. I double click the .exe from /home/pi/Desktop/MineCraftConsoleClient and it still creates an new .ini in/home/pi

**Comment by ORelio** [comment]
Your desktop UI is not launching the exe from the correct folder. You'd need to create a custom desktop shortcut that does something like launching a command in a terminal:
```
bash -c "cd /correct/folder && mono MinecraftClient.exe"
```
