### ISSUE TITLE
Possible to relog without specifying kickmessages? or regex support?

### ISSUE THREAD

**Issue by hykilpikonna** [ORelio/Minecraft-Console-Client#863]
So the server I connect to has an anti-afk plugin that kicks players with different kick messages every time. Are there any workarounds? For example an option to relog without checking kick messages, or does kick messages support regex?

**Comment by JesperKuipers** [comment]
did u try the anti afk option?

**Comment by porkiedev** [comment]
Check out my repo, Just pushed it today!

Adds a configuration option to ignore the kickmessages.txt file and relog anyway, regardless of the kick reason.

[https://github.com/porkiedev/Minecraft-Console-Client](url)

**Comment by Mhowser** [comment]
Ignoring the kick message and relogging regardless makes so much more sense, I think kick messages should be used to stop reconnecting, e,g "you have been banned" will stop the automatic reconnecting.

**Comment by ORelio** [comment]
Is your kick message perfectly random? Can you provide some samples?
Indeed, the AutoRelog built-in bot is working with a white-list approach.

**Comment by hykilpikonna** [comment]
> Is your kick message perfectly random? Can you provide some samples?
> Indeed, the AutoRelog built-in bot is working with a white-list approach.

The actual kick messages that I'm getting shouldn't be relevant to this topic since server admins can make plugins to kick afk players with any kick message format they want. Whitelisting would be a better solution, or else you can just implement regex support so that players can adapt their kickmessages with regex expressions that matches their corresponding format.

The kick message I'm getting: 

> *[random string of length 8]* :: AFK is not allowed :: *[random string of length 8]*

Example:

![image](https://user-images.githubusercontent.com/22280294/75191113-ba55a880-571f-11ea-9c49-dca077350df6.png)
![image](https://user-images.githubusercontent.com/22280294/75191359-2c2df200-5720-11ea-9789-bb7dc3e53005.png)

**Comment by ORelio** [comment]
Simply put `AFK is not allowed` into `kickmessages.txt`.
As long as the specified pattern is present, it will match.

**Comment by hykilpikonna** [comment]
> Simply put `AFK is not allowed` into `kickmessages.txt`.
> As long as the specified pattern is present, it will match.
> Also consider using AntiAFK and/or scheduling `/move` commands.

Ok, I didn't know it's testing `Contains()` instead of `Equals()`, so ignoring kickmessages can be achieved by listing every character in the alphabet and numbers in kickmessages.
