### ISSUE TITLE
Minecraft consol client logic

### ISSUE THREAD

**Issue by LidForr** [ORelio/Minecraft-Console-Client#864]
I want to make improvements on how you can explain the logic of this. 
Thank you

**Comment by ORelio** [comment]
Hi,
As a quick summary:
 - Program.cs : Load user arguments and start a Minecraft client
 - McTcpClient.cs : The Minecraft client, receives events from server and commands in console
 - Protocol Handlers (Protocol16 and Protocol18) : Implements network packets for interacting with the Minecraft Server. The McTcpClient will request a protocol implementation and get a protocol Handler, either Protocol16 or Protocol18. Inside Protocol you'll also find implementation for Mojang API (server login...).
 - ChatBot.cs : API for chatBots that are loaded inside McTcpClient.cs for extending MCC capabilities
 - CSharpRunner.cs : API for C# scripts loaded trough the ScriptRunner ChatBot.
