### ISSUE TITLE
Proxy Issue (Pt. 2)

### ISSUE THREAD

**Issue by Baeguls** [ORelio/Minecraft-Console-Client#865]
![Capture11](https://user-images.githubusercontent.com/60494784/74611432-a58a6c80-50b0-11ea-9179-dff2ad8c6149.PNG)

Filed an issue ~1 week ago, trying to bypass alt/ip limit on my server. I get this error message regularly, and every other proxy is blocked on minecraft. Anyone have any advice on a functional proxy/any way to bypass the limit, or insight on the error?

**Comment by ORelio** [comment]
Cannot provide help on finding a good proxy, however regarding the error, are you getting this using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)? I'd need line numbers in the stack trace to identify the exact location of the error.
