### ISSUE TITLE
Unable to log on with raspberry pi

### ISSUE THREAD

**Issue by ghost** [ORelio/Minecraft-Console-Client#868]
Hi,

I'm using Raspbian Buster version 10 with mono version 5.18.0.240 on my raspberry pi 2 B+ using the later version of minecraft console client.
Whenever I log onto any minecraft server, I receive a message that the server was successfully joined. However, I am unable to talk in chat or use commands. The following screen is stuck and nothing from the server would load. I used turned on anti-afk with the auto-reconnect enabled but it had no effect on the issue. #438 illustrates my issue very well.

Retrieving Server Info...
Version is supported.
Logging in...
Checking Session...
Server was successfully joined.
Type '/quit' to leave the server
>

Update: Also, I am able to log on with the same account to the same server while having the console client turned on, meaning that the console client in fact did not successfully connect to the server. 

Mono works on my mac perfectly but does not work on my raspberry pi. Is there any solution to downgrading mono to 4.2 or making it work on 5.18?

**Comment by JesperKuipers** [comment]
I use 2 accounts and I get the problem with the first console I open. But my second console can see what I type in the chat with the first console. So it seems like all messages get delayed for a few minutes from my experience.

**Comment by ORelio** [comment]
Seems like yet another issue with Mono for ARM that I cannot figure out. Not sure if downgrading to some old Mono version will help that much. Hopefully it may be solved using .NET 5 that should release with Linux support later this year https://devblogs.microsoft.com/dotnet/introducing-net-5/
