### ISSUE TITLE
Does not relog on network error?

### ISSUE THREAD

**Issue by hlprimm** [ORelio/Minecraft-Console-Client#87]
My internet occassionally drops. Wondering how to get it to reconnect after I get this message:

```
Connection failed: Network error.
```

Screenshot: http://i.imgur.com/sDanaRc.png

ini file is: 

```
[AutoRelog]
enabled=true
delay=10
retries=-1 #-1 = unlimited
kickmessagesfile=kickmessages.txt
```

My kickmessages.txt is:

```
Connection has been lost
Server is restarting
Server is full
too many people
Connection failed
Network
error
restarting
```

**Comment by ORelio** [comment]
Please retry with latest [dev build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/) because if I remember well "Network error" kick message has been added in dev builds but isn't yet in stable version :)

**Comment by hlprimm** [comment]
Darn, I get a socket exception! Do you know which dev build it was included in? I am testing by turning off my wifi connection, BTW. 

http://i.imgur.com/W3fzbzI.png

**Comment by ORelio** [comment]
Are you sure Minecraft Console Client is allowed to access the Internet?

**Comment by hlprimm** [comment]
Maybe that might have been it - seems to work now. Thanks!
