### ISSUE TITLE
how to dynamically stop and start a bot through console command

### ISSUE THREAD

**Issue by michael040990** [ORelio/Minecraft-Console-Client#870]
hello i am trying to implement anti afk to enable or disable though the console similarly how you can enable and disable logs i see there is a function to unload bots but i am not having luck to unload a bot once its loaded i can make a variable that will just read each time before it sends the afk commands to the server and decide if you want to send it but i rather have a way to unload the bot so it doesn't waste any threads or memory

**Comment by ORelio** [comment]
Your bot can unload itself once done working. Simply call [`Unload()`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L557) from your bot.
