### ISSUE TITLE
How do I log in multiple accounts using a bat file and then redirect to another script?

### ISSUE THREAD

**Issue by SkittyChips** [ORelio/Minecraft-Console-Client#873]
Altlogin.bat:
start /min MinecraftClient.exe email1 password2 IP
timeout 5
start /min MinecraftClient.exe email2 password2 IP
timeout 5

Mainscript config:
[Task]
triggerOnFirstLogin=true
triggerOnLogin=true
triggerOnInterval=true
timeInterval=30
script=mainscript.txt

Mainscrpt.txt:
wait 32
send /server xeon

How come whenever I launch altlogin.bat the mainscript.txt doesn't run? It's supposed to run a command but nothing happens. Both accounts aren't running the command to join. How do I make altlogin.bat trigger the script?

**Comment by ORelio** [comment]
Try `debugmessages=true` in config, this may help finding out what's wrong.
