### ISSUE TITLE
How do I make a loop that goes infinitely?

### ISSUE THREAD

**Issue by SkittyChips** [ORelio/Minecraft-Console-Client#874]
I don't want to copy and paste the same line 10000 times and hope it doesn't run out.
For exampel:
Log in alt 1
Log in alt 2
Log in alt 3
Every 20 seconds until stopped:
Run command for all 3 alts

bat file?

**Comment by ORelio** [comment]
If your script is `myscript.txt`, add `script myscript.txt` at the end of your script to load it again. You may also want to use the ScriptScheduler to launch it from time to time.
