### ISSUE TITLE
Failed to check session on some clients

### ISSUE THREAD

**Issue by SkittyChips** [ORelio/Minecraft-Console-Client#877]
Fifth issue in 1 hour...
Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
Connecting to Minecraft.net...
Using Minecraft version 1.8.9 (protocol v47)
Version is supported.
Logging in...
Checking Session...
Login failed :
Failed to check session.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>

On my other client it logs in, but doesn't run the damn script.

**Comment by ORelio** [comment]
` Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors`
All version released prior to May 2018 will fail to check session, as per #451
➡️ Download the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
