### ISSUE TITLE
Does nothing?

### ISSUE THREAD

**Issue by SkittyChips** [ORelio/Minecraft-Console-Client#878]
I started the files, but nothing happened. I double clicked the exe file. My player logs in, BUT they don't run the startup command.
[Nieuwe map (4) - Copy.zip](https://github.com/ORelio/Minecraft-Console-Client/files/4271198/Nieuwe.map.4.-.Copy.zip)

(private details omitted)
Why won't the mainscript.txt run? It is ONE COMMAND. The taks is correct asafik

**Comment by SkittyChips** [comment]
I'm tired of making these reports. I mean this entire program is worthless if I can't even start it.

**Comment by TiredSysOp** [comment]
Works fine for me, you haven't provided your batch script. Have you read https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config ?

**Comment by ORelio** [comment]
Are you using a pre-configured client with some settings provided by someone? If so, just ask that person for support? Also, **avoid posting SessionCache.ini** as it contains session information for the account(s) you logged in in MCC.
