### ISSUE TITLE
Reconnect on any message

### ISSUE THREAD

**Issue by SkittyChips** [ORelio/Minecraft-Console-Client#880]
How do I make it so the client automatically reconnects, regardless of the disconnect message given if any. So basically it does not check the kick messages and instantly relogs.

**Comment by TiredSysOp** [comment]
Read the documentation https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot

**Comment by ORelio** [comment]
Implemented in commit c5b0f447c93587331c4f2d9441228a39426192f0.
