### ISSUE TITLE
VPS Help mono

### ISSUE THREAD

**Issue by TechnicTSS** [ORelio/Minecraft-Console-Client#882]
Im trying to run minecraft alts 24/7 through bluehost vps with Putty but I cant I have tried doing what you guys said in the other cases, but I cant figure out how.

**Comment by SpikeThatMike** [comment]
1. install mono
2. mono (consoleclient name)

E.G
mono MinecraftClient.exe

**Comment by ORelio** [comment]
Have you seen Linux instructions in [config#how-to-use](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-use)?
