### ISSUE TITLE
Another bug at dataTypes.ReadNextNbt (maybe)

### ISSUE THREAD

**Issue by OMG-link** [ORelio/Minecraft-Console-Client#883]
It should be like this to process an item with no nbt data.
```cs
if (root)
{
    byte type = ReadNextByte(cache);
    if (type == 0) //No NBT data
        return null;
    if (type != 10) // TAG_Compound
        throw new System.IO.InvalidDataException("Failed to decode NBT: Does not start with TAG_Compound");
    ReadData(ReadNextUShort(cache), cache); // NBT root name
}
```

**Comment by ORelio** [comment]
Hi,

According to https://wiki.vg/NBT#Specification:


Type ID | Type Name | Payload Size (Bytes) | Description
-- | -- | -- | --
0 | TAG_End | 0 | Signifies the end of a TAG_Compound. It is only ever used _**inside**_ a  TAG_Compound, and is not named despite being in a TAG_Compound

Which means that an empty tag should contain TAG_Compound, then TAG_End. Are you sure that you encountered NBT sent by MC server that only contains a single null byte (TAG_End)?

**Comment by Pokechu22** [comment]
It's not an empty tag compound, but instead a special value MC uses when the entire tag is `null`.  It's mentioned on the [slot data](https://wiki.vg/Slot_Data) page.

**Comment by OMG-link** [comment]
I received the following packet. (Packet type is Window Item)
```bin
00 
00 2E 
FF FF ( 9 times )
00 0C 03 00 00 00 
01 04 01 00 00 00 
FF FF 
01 18 02 00 00 00 
00 03 40 00 00 00 
FF FF FF FF FF FF FF FF FF ... ( a lot of FF )
```
And it throws an Invalid Data Exception because of the NBT data.

**Comment by ORelio** [comment]
Thank you @OMG-link for reporting and @Pokechu22 for clarifying. To my understanding, using a single `TAG_END` (`0x00`) is not valid NBT but a way of saying that the field do not contain NBT data. Just changed `ReadNextNBT()` so that it treats `0x00` as a valid (but empty) NBT tag.
