### ISSUE TITLE
How do I add digging ?   Как добавить копание ?

### ISSUE THREAD

**Issue by goncharov5606** [ORelio/Minecraft-Console-Client#884]
Как можно добавить копание ?
Можно что-то на подобии документации ?
How can I add digging ?
Can I do something similar to the documentation ?

**Comment by J3rrysama** [comment]
I think you can find something related in #808 . By the way, I know gnembon's carpet mod has the similar function as 'attack' (left click) and 'use' (right click) by controlling bot player spawned in game . I wonder if we could learn from that to achieve clicking in MCC.

**Comment by goncharov5606** [comment]
> Я думаю, что вы можете найти что-то связанное в [# 808](https://github.com/ORelio/Minecraft-Console-Client/issues/808) . Кстати, я знаю, что ковровый мод gnembon имеет аналогичную функцию: «атака» (щелчок левой кнопкой мыши) и «использование» (щелчок правой кнопкой мыши), контролируя бота, появляющегося в игре. Интересно, могли бы мы извлечь уроки из этого, чтобы добиться щелчка в MCC.

**Comment by goncharov5606** [comment]
can read more about "gnembon" ?
