### ISSUE TITLE
how do I add my own commands?

### ISSUE THREAD

**Issue by goncharov5606** [ORelio/Minecraft-Console-Client#885]
how can I add my own commands?

**Comment by ORelio** [comment]
I'd suggest using the scripting engine. See [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config).

**Comment by ORelio** [comment]
Registering a new command from a ChatBot: https://github.com/ORelio/Minecraft-Console-Client/pull/1108#issuecomment-663166660
