### ISSUE TITLE
How do I set a delay between "send" messages?

### ISSUE THREAD

**Issue by stilwall** [ORelio/Minecraft-Console-Client#886]
Currently I have a .txt file that sends a /join message and then I want it to send /move north, but 5 seconds later. Currently, they're sending nearly instantaneously after one another. I tried timeout /t (time) but it didn't work.

**Comment by BlexMC** [comment]
Hello,
you're able to add delays between each command. To do so, simpy add `wait` between the commands.
For you, it would look like this:

```
/join
wait 5
/move north
```

**Comment by stilwall** [comment]
> Hello,
> you're able to add delays between each command. To do so, simpy add `wait` between the commands.
> For you, it would look like this:
> 
> ```
> send /join
> wait 5
> send /move north
> ```

Thanks, I'll close this now
