### ISSUE TITLE
Make HTTP Request from a Script / Show COVID-19 status in chat

### ISSUE THREAD

**Issue by AlexDoesMemes** [ORelio/Minecraft-Console-Client#887]
this might sound weird but ill explain. There is a website (i dont own) called https://corona.lmao.ninja/. it gives you info about coronavirus. i was wondering if it was possible to use autorespond (or something else) to make a bot where if you pm it something. it responds with info from that site. Thanks in advance.

**Comment by ORelio** [comment]
You could make a C# script like this:

**covid.cs**
````csharp
//MCCScript 1.0

string cases = PerformHttpRequest("https://corona.lmao.ninja/");
string firstline = cases.Split(new []{ "<br>" }, StringSplitOptions.None)[0];
MCC.SendText(firstline);

//MCCScript Extensions

string PerformHttpRequest(string uri)
{
    var request = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(uri);
    var response = (System.Net.HttpWebResponse)request.GetResponse();
    string responseString;
    using (var stream = response.GetResponseStream())
        using (var reader = new StreamReader(stream))
            responseString = reader.ReadToEnd();
    return responseString;
}
````

Then launch the script using AutoRespond or ScriptScheduler at your convenience.

**Comment by AlexDoesMemes** [comment]
Hey! Thanks. Just wondering is it possible to PM the user who triggered the autoresponse the info instead of public chat?

**Comment by AlexDoesMemes** [comment]
> You could make a C# script like this:
> 
> **covid.cs**
> 
> ```cs
> //MCCScript 1.0
> 
> string cases = PerformHttpRequest("https://corona.lmao.ninja/");
> string firstline = cases.Split(new []{ "<br>" }, StringSplitOptions.None)[0];
> MCC.SendText(firstline);
> 
> //MCCScript Extensions
> 
> string PerformHttpRequest(string uri)
> {
>     var request = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(uri);
>     var response = (System.Net.HttpWebResponse)request.GetResponse();
>     string responseString;
>     using (var stream = response.GetResponseStream())
>         using (var reader = new StreamReader(stream))
>             responseString = reader.ReadToEnd();
>     return responseString;
> }
> ```
> 
> Then launch the script using AutoRespond or ScriptScheduler at your convenience.

Hey! Thanks for this. This seems to work. But is it possible to PM it to whoever sent the autorespond message?

**Comment by ORelio** [comment]
Yes, simply embed it in a ChatBot, as shown in [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs):

**covidbot.cs**
```csharp
//MCCScript 1.0

MCC.LoadBot(new CovidBot());

//MCCScript Extensions

public class CovidBot : ChatBot
{
    public override void Initialize()
    {
        LogToConsole("Sucessfully Initialized!");
    }

    public override void GetText(string text)
    {
        string message = "";
        string username = "";
        text = GetVerbatim(text);

        if (IsPrivateMessage(text, ref message, ref username) && message == "!covid")
        {
            string cases = PerformHttpRequest("https://corona.lmao.ninja/");
            string firstline = cases.Split(new []{ "<br>" }, StringSplitOptions.None)[0];
            SendText("/tell " + username + " " + firstline);
        }
    }

    private static string PerformHttpRequest(string uri)
    {
        var request = (System.Net.HttpWebRequest)System.Net.WebRequest.Create(uri);
        var response = (System.Net.HttpWebResponse)request.GetResponse();
        string responseString;
        using (var stream = response.GetResponseStream())
            using (var reader = new StreamReader(stream))
                responseString = reader.ReadToEnd();
        return responseString;
    }
}
```
Run it once to load the bot (can use ScriptScheduler with `triggerOnFirstLogin=true` event), then it will respond to anyone sending them `!covid` as PM (e.g. `/tell bot !covid`).

**Comment by ORelio** [comment]
Seems like this issue is resolved.
