### ISSUE TITLE
Connection/network error

### ISSUE THREAD

**Issue by HacksAndSlash** [ORelio/Minecraft-Console-Client#889]
this is the debug stuff (minus username & password)

Console Client for MC 1.4.6 to 1.15.2 - v1.15.2 - By ORelio & Contributors
AppVeyor build 254, built on Mon 03/16/2020 from commit 758bc2a
[MCC] [Settings] Loading Settings from C:\Users\robbi\Desktop\MCC\MinecraftClient.ini
Resolving echoes.fun...
Initializing disk session cache using FileSystemWatcher
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Loaded session: trenthancock@yahoo.com:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzZTExOWY1MmZkOTE0ZGQzOThkYjEyNTg3YmFhNDgxNyIsInlnZ3QiOiIzOWMyOWRlYmI5NTE0ZTQ0YTc5ZGQ4M2MzMThlZTRiNSIsInNwciI6Ijk4OGZjYjZkODg2MjRmZDJhMTA4NzdjY2FkM2I1MjAwIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODQ1NzIwMzMsImlhdCI6MTU4NDM5OTIzM30.QkjgOXPhzWFJMpkcCkhobIdyO51XZ849oBUedc5-3jw
Session data has been successfully loaded from disk.
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
> POST /authenticate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.15.2
> Content-Type: application/json
> Content-Length: 216
> Connection: close
>
> {"agent": { "name": "Minecraft", "version": 1 }, "username": 
Got error code from server: 520
Minecraft Login failed : Network error.
[MCC] [AutoRelog] Launching with 2147483647 reconnection attempts
[MCC] [AutoRelog] Loading messages from file: C:\Users\robbi\Desktop\MCC\kickmessages.txt
[MCC] [AutoRelog]   Loaded message:
[MCC] [AutoRelog] Got disconnected with message: Minecraft Login failed : Network error.
[MCC] [AutoRelog] Message contains ''. Reconnecting.
[MCC] [AutoRelog] Waiting 100 seconds before reconnecting...

**Comment by ORelio** [comment]
Please change your password as you did not redact it on your post above.

Regarding your issue: Try from an IP address you are sure you can login from using the vanilla game. Maybe there is IP blacklisting if using VPN or Server IP address.

**Comment by HacksAndSlash** [comment]
> Please change your password as you did not redact it on your post above.
> 
> Regarding your issue: Try from an IP address you are sure you can login from using the vanilla game. Maybe there is IP blacklisting if using VPN or Server IP address.

Im not using a vpn and can connect normally with regular minecraft
