### ISSUE TITLE
Proxy Issues

### ISSUE THREAD

**Issue by DigitalSniperz** [ORelio/Minecraft-Console-Client#89]
I have my own setup proxy, it allows ALL ports and HTTPS/SSL. When I connect the client to it, after the connecting to minecraft.net it shows this error, any clue what this could mean?

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at MinecraftClient.Protocol.ProtocolHandler+<>c__DisplayClass4.<doHTTPSPost>b__3 () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at MinecraftClient.Protocol.ProtocolHandler+<>c__DisplayClass4.<doHTTPSPost>b__3 () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

**Comment by DigitalSniperz** [comment]
I am using the latest beta version, I have tried other version but they consist of the same error. 

Version:
https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/34

**Comment by DigitalSniperz** [comment]
Proof that the proxies can connect to the authserver:

[01:32] Starting: Test 2: Connection through the Proxy Server
[01:32] Connection to https://authserver.mojang.com:443 established through the proxy server.
[01:34] A default web page was successfuly loaded.
[01:34] Test passed.

**Comment by ORelio** [comment]
Hello,
Are you sure that the issue happens while logging in?
Not all proxies are supported, and I did not write the proxy handling part.
See issue #80 for full explanation.

**Comment by DigitalSniperz** [comment]
The error occurs after the "connected to <proxyip>", the proxy is hosted on a VPS and it has all ports unblocked. I've tried it with a proxy checker to check if https authserver/login server works on the proxy and both do. When I use the proxy on minecraft it lets me log in. I don't understand why its not working on your minecraft linux client.

**Comment by ORelio** [comment]
Proxy support is not made by me. It's a free and open source C# library called [Biko Library](https://github.com/bentonstark/starksoft-aspen). This is the only one I could find that is free and open source, and if some proxies are not supported, I can't really know why since I'm not the author of this part of the code... What proxy software are you using?

**Comment by ZizzyDizzyMC** [comment]
Came accross this issue myself again. Working now to find a work around to let the proxy be used to authenticate but not play.

**Comment by ORelio** [comment]
That could be implemented by disabling proxy between login phase and server join phase, using an additional setting in configuration file.

**Comment by ORelio** [comment]
Noting new since then, closing, feel free to reopen if needed ;)
