### ISSUE TITLE
Mcc for Termux

### ISSUE THREAD

**Issue by Mhowser** [ORelio/Minecraft-Console-Client#893]
I was wondering if its possible to get MCC working on Termux for Android. I found a version of mono that should work with Termux https://github.com/cydhaselton/mono-android

I know about Minechat and other similar apps existing, but none of them has the capabilities/configuration that MCC does.

**Comment by ORelio** [comment]
What happens when you launch MCC under Termux?

**Comment by Mhowser** [comment]
I'm having difficulty compiling mono-android 
![Screenshot_20200329-213720](https://user-images.githubusercontent.com/24195572/77875641-8d585200-7205-11ea-96bd-48aa523ea642.png)

**Comment by ORelio** [comment]
Oh. Well, I'm not aware of good .NET implementations for Android.
