### ISSUE TITLE
How using internal commands like /respawn in .cs files ?

### ISSUE THREAD

**Issue by Chtholly** [ORelio/Minecraft-Console-Client#898]
How using internal commands like /respawn in .cs files ?

**Comment by ORelio** [comment]
This way:
```csharp
MCC.PerformInternalCommand("respawn");
```
See [CSharpRunner.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/CSharpRunner.cs#L244) for all the API methods you can access.
