### ISSUE TITLE
Throws server at /inventory 0 click itemslot

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#903]
enableentityhandling=true         # Toggle entities handling
terrainandmovements=true          # Uses more ram, cpu, bandwidth
inventoryhandling=true            # Toggle inventory handling (experimental, enable only for development)

![image](https://user-images.githubusercontent.com/35975332/77865215-acc39f00-7246-11ea-8832-1661cceaa166.png)

**Comment by Mhowser** [comment]
Can't read Cryllic, what's wrong?

**Comment by ORelio** [comment]
He is disconnected upon sending a Click Window packet using the new Inventory feature, which means the packet is either malformed or some plugin was not happy with it. Protocol 578 is 1.15.2 and I mainly tested this feature using that Minecraft version, but not with inventories going as far as slot 80 (is it even valid?)

**Comment by ORelio** [comment]
Unfortunately we could not reproduce this issue.
