### ISSUE TITLE
Auto Relog

### ISSUE THREAD

**Issue by RealTerror** [ORelio/Minecraft-Console-Client#909]
I've installed the most recent files of console client. I'm unable to use auto relog properly. I've enabled auto relog in the config file and set it to true. I've added a text document 'kickmessages" in the Release folder. When I get kicked from the server it doesn't auto reconnect. I waited 30 seconds, and still nothing. When I type 'reco' into the console it will say: 
Connection has been lost.
[MCC] [AutoRelog] Waiting 10 seconds before reconnecting...
I have the message 'Connection has been lost.' in the kickmessages text document already.

**Comment by ORelio** [comment]
Are you 100% sure you are using this exe: [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)?

**Comment by RealTerror** [comment]
I re-downloaded the exe and put the config and the dev build in there, I still get the same error:

Disconnected by Server :
Kicked from server.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
>>f
f
>f
Connection has been lost.
[MCC] [AutoRelog] Waiting 10 seconds before reconnecting...
Yes, I've reneabled autorelog and added these kick messages.

**Comment by ORelio** [comment]
OK, will have a look.

**Comment by ORelio** [comment]
I cannot reproduce this. Please retry with `debugmessages=true`, do you get any additional message?

**Comment by RealTerror** [comment]
After, setting debug messages to true, it works. I don't understand what was going on, but it works now. I apologize for the time taken. Thanks for the assistance.

**Comment by ORelio** [comment]
Weird. Well, at least it works now 😅

**Comment by aimea984** [comment]
Hello ORelio, i need help, how to make the /move work and how to make auto relog work i can't do this

**Comment by aimea984** [comment]
> Hello ORelio, i need help, how to make the /move work and how to make auto relog work i can't do this

Just need help how to config the kickmessages.text file to my kick messages

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot

**Comment by aimea984** [comment]
> https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot

But where do I put this kickmessages.txt file?

**Comment by aimea984** [comment]
> > https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot
> 
> But where do I put this kickmessages.txt file?

and in the file just write the kick message that you will receive example Rebooting?

**Comment by ReinforceZwei** [comment]
> But where do I put this kickmessages.txt file?

In the same folder of your `MinecraftClient.exe`.


> and in the file just write the kick message that you will receive example Rebooting?

Yes.
