### ISSUE TITLE
Add "fake" resources pack

### ISSUE THREAD

**Issue by Yoann166** [ORelio/Minecraft-Console-Client#91]
Hello,

It is possible to put a "fake resources pack" for servers where this is required?

Thanks,
Yoann

**Comment by ORelio** [comment]
Done! Now for every "resource pack send" packet, MCC will respond with a "successfully loaded" status. I did not test it, please try out the [associated development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/37) :)

**Comment by Yoann166** [comment]
I tested this version but I'm again kicked when I try to join the server.

**Comment by ORelio** [comment]
Okay, maybe the plugin is expecting both "accepted" and "successfully loaded" responses, so let's send both, like a vanilla client does when the resource pack has already been downloaded once. Please try again with the newer development build!

**Comment by ORelio** [comment]
The issue should be fixed, but feel free to reopen if needed ;)

**Comment by Muharrem652** [comment]
> The issue should be fixed, but feel free to reopen if needed ;)

I don't understand how we do it

**Comment by sl4475** [comment]
im unable to join a server that requires a resource pack. "The resource pack download failed. Please reconnect and try again." I was able to join once, but after that, i wasnt able to. for context, you can join the server, but you cant connect to the sub-server(e.g. skyblock, factions,etc.)
