### ISSUE TITLE
Custom item names not shown in inventory

### ISSUE THREAD

**Issue by tgwecho** [ORelio/Minecraft-Console-Client#910]
I can open the inventory and see all the items. But I am supposed to find "the correct item" which can only be found by hovering over an item and it says "correct item" in green at the bottom. How would I find this correct item

**Comment by Mhowser** [comment]
I think a feature where one could inspect an item in the inventory would be very helpful.

**Comment by ReinforceZwei** [comment]
Maybe need to read the item NBT for getting the correct item which is currently not handled.

**Comment by ORelio** [comment]
When outputting `/inventory list`, we need to also retrieve custom item names from NBT and display them besides the item type.

**Comment by ORelio** [comment]
Support added in commit dbe02c063c12fe88930d86a98f823a6875ecbc4b, custom item names are now shown in `/inventory list`.
