### ISSUE TITLE
Inventory handling disconnects from server

### ISSUE THREAD

**Issue by lolitsmebarry** [ORelio/Minecraft-Console-Client#911]
Whenever i try to click an item in inventory with "/inventory 1 click 15" it disconnects me from the hub.

![bug](https://user-images.githubusercontent.com/22051319/77984658-7e12fa80-7312-11ea-9151-d8b5515891d5.PNG)

Edit:
im trying to join a server from the hub with compass inventory.

**Comment by ORelio** [comment]
Please retry with the newest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)?

**Comment by ORelio** [comment]
Should be fixed as per #913, feel free to reopen if it isnt.
