### ISSUE TITLE
Auto Relog

### ISSUE THREAD

**Issue by supertrio17** [ORelio/Minecraft-Console-Client#921]
Is there any way to relog without kick messages. Just to relog without them. For example if I was kicked for '1' It would get me reloged without me having 1 in kickmessages?

**Comment by ReinforceZwei** [comment]
Currently you can’t do that.
We are still waiting for contributors to implement those features.

**Comment by ORelio** [comment]
Implemented in commit c5b0f447c93587331c4f2d9441228a39426192f0.
