### ISSUE TITLE
Implement auto eating on low health

### ISSUE THREAD

**Issue by Chtholly** [ORelio/Minecraft-Console-Client#923]
Is it now possible to implement eat Food while using 

> if (health <= 5)

switch to food which is in hotbar or 2nd hand and hold it ?

**Comment by ReinforceZwei** [comment]
It is possible, but we need all item mapped with their type, like `apple.type` is food so that we don't accidentally eat something like a sword.

**Comment by ReinforceZwei** [comment]
Implemented in https://github.com/ORelio/Minecraft-Console-Client/pull/930
