### ISSUE TITLE
Incorrect password error when password is correct

### ISSUE THREAD

**Issue by Mikie** [ORelio/Minecraft-Console-Client#925]
So, I recently updated both of my alts minecraft password and when i put the new password in my afk.bat file it says that the password is incorrect and take the last 3 letters of my password and says its not recognized and my alt passwords both are 30-40 characters long, so I'm confused what happening cause earlier it worked fine  until i updated both of my passwords

**Comment by Mikie** [comment]
so it seems like it works with the new development build

**Comment by ORelio** [comment]
OK, I'll close the issue then.
