### ISSUE TITLE
minecraft login failed: Network error

### ISSUE THREAD

**Issue by lackofcreativename** [ORelio/Minecraft-Console-Client#927]
debug output:
Console Client for MC 1.4.6 to 1.15.2 - v1.15.2 - By ORelio & Contributors
AppVeyor build 273, built on Sat 04/04/2020 from commit bf86259
[MCC] [Settings] Loading Settings from C:\Users\Paox2\Downloads\MinecraftClient.ini
Resolving play.manacube.net...
Initializing disk session cache using FileSystemWatcher
Loading Minecraft profiles: launcher_profiles.json
No sessions could be loaded from disk
Connecting to Minecraft.net...
Performing request to authserver.mojang.com
> POST /authenticate HTTP/1.1
> Host: authserver.mojang.com
> User-Agent: MCC/1.15.2
> Content-Type: application/json
> Content-Length: 170
> Connection: close
>
> {"agent": { "name": "Minecraft", "version": 1 }, "username": "<username>", "password": "<password>", "clientToken": "ca06d433a0c14c8896822d4659f6b139" }
Got error code from server: 520
Minecraft Login failed : Network error.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

**Comment by ORelio** [comment]
From https://en.wikipedia.org/wiki/List_of_HTTP_status_codes:
> 520 Web Server Returned an Unknown Error
>     The origin server returned an empty, unknown, or unexplained response to Cloudflare.
Seems like the issue is on the side of the login servers.
