### ISSUE TITLE
Sending chat messages via python script

### ISSUE THREAD

**Issue by SpikeThatMike** [ORelio/Minecraft-Console-Client#931]
I'm trying to make the Console Client send messages in the chat via a python script. I've tried various method's of trying to do this but cannot figure it out. Has anyone else done this or knows how to do this? Would be appreciated.

**Comment by ORelio** [comment]
Easiest way would be to start MCC from your Python and specifying `BasicIO` as last command-line argument. Then you can read and write from standard input/output, which includes sending commands.

**Comment by SpikeThatMike** [comment]
i tried this but i was unsuccessful. Is there another way?

**Comment by ORelio** [comment]
No, scripting is done in C#. But the GUI provided with MCC is interfaced using stdin and stdout, so I see no reason while it would not work using Python. See https://stackoverflow.com/questions/37560427/sending-to-the-stdin-of-a-program-in-python3 for example. You need to launch `MinecraftClient.exe "login" "password" "serverip"` then wait for message saying that server is joined in stdout, and write commands in stdin.

**Comment by SpikeThatMike** [comment]
Ive done this but when it connects to the server, i get this error

b'Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.\r\n'
b'   at System.Console.ReadKey(Boolean intercept)\r\n'
b'   at MinecraftClient.ConsoleIO.ReadLine()\r\n'
b'   at MinecraftClient.McTcpClient.CommandPrompt()\r\n'
b'   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)\r\n'
b'   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n'
b'   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n'
b'   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n'
b'   at System.Threading.ThreadHelper.ThreadStart()\n'

**Comment by ORelio** [comment]
This means Basic IO is not enabled. [`MinecraftClient.ConsoleIO.ReadLine()`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ConsoleIO.cs#L116) does not use `ReadKey()` in Basic IO mode. You need to put `BasicIO` (case sensitive) as last argument when invoking MCC.

**Comment by SpikeThatMike** [comment]
Ive done this now, it works now, but after it now joins the server the chat looks like this 
![image](https://user-images.githubusercontent.com/37084002/79116829-62cbd480-7d81-11ea-814b-30e73c02a019.png)

**Comment by ORelio** [comment]
In BasicIO mode, [formatting codes](https://minecraft.gamepedia.com/Formatting_codes#Color_codes) are used to represent colors since MCC cannot access the terminal to set the correct color. You can strip them if you don't need them.

Do not forget to put a newline (`\n`) when sending input to MCC.
```python
MCC.stdin.write(b"test\n")
MCC.stdin.flush()
```
Flush might happen automatically when writing a newline, but I'm unsure about this.

**Comment by SpikeThatMike** [comment]
Is there an easier way to get rid of all the format codes in one go instead of using .replace()?

**Comment by ORelio** [comment]
You'll probably want to write some function like [`GetVerbatim()`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L232) in Python.

**Comment by ReinforceZwei** [comment]
@SpikeThatMike For Python, you can follow [the answers](https://stackoverflow.com/questions/14693701/how-can-i-remove-the-ansi-escape-sequences-from-a-string-in-python) from stackoverflow

**Comment by ORelio** [comment]
@ReinforceZwei please note that Minecraft formatting codes are not ANSI escape sequences

**Comment by ReinforceZwei** [comment]
@ORelio I see. I thought MCC would convert those Minecraft formatting codes to ANSI escape sequences before outputting them.

**Comment by ORelio** [comment]
@ReinforceZwei Yey, it does by default, but not in Basic IO mode for non-interactive use.

**Comment by SpikeThatMike** [comment]
In the end i used 
space = b'' 
.replace(b'(format code)', space)

Also ive found out that when chat isnt active and no messages are sent, MCC which was lauched in the python file stops working

**Comment by ORelio** [comment]
This is silent disconnection on Linux with Mono: #879 mysterious bug that could not be fixed reliably.

**Comment by SpikeThatMike** [comment]
Do you think there is a way of temp fixing it? Like making the MCC send / for 20seconds once lauched, so it doesnt disconnect randomly? Also use the client.stdin,write(b'\n'), is there another possible solution to add vairbles so like client.stdin.write(b'{welcome}') so it would send the welcome varible. Ive tested many different methods but havent found one to work yet

**Comment by ReinforceZwei** [comment]
Actually we have tried different things to solve it but none was success. If you found a working solution, feel free to share it with us.

**Comment by SpikeThatMike** [comment]
I tried many different things to try make this work but i was successful.
Because i only need the bot to send/recieve chat messages ive looked into mineflayer, spockbot etc to do this

**Comment by ORelio** [comment]
The silent disconnect issue should be fixed as per #1219 thanks to @ReinforceZwei's findings.
