### ISSUE TITLE
ChatBot Reconnect error

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#932]
![image](https://user-images.githubusercontent.com/35975332/78731555-79c18f80-7959-11ea-861d-50834f3c99d2.png)
public void TeleportToDuels(){
		ReconnectToTheServer();
	}

**Comment by ORelio** [comment]
`ThreadAbortException`. Maybe your bot is using threads? You should call ChatBot APIs only from the main thread because MCC is not fully thread safe.

**Comment by Nekiplay** [comment]
No, my script did not use new threads

**Comment by ORelio** [comment]
Closing this issue as it's more than a year old and we could not find out the exact cause.
