### ISSUE TITLE
AutoAttack stop working with AutoEat enabled and no food on hotbar

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#934]
The reason is `Eating` was set to `true` even no food on the hotbar and never set back to false, so that it didn't pass the `if (!AutoEat.Eating)` condition.
I made some fix attempt but still not working
```cs
public override void OnHealthUpdate(float health, int food)
{
    if (food <= HungerThreshold || (food < 20 && health < 20))
    {
        if (FindFoodAndEat())
        {
            Eating = true;
        }
        else
        {
            Eating = false;
        }
    }
    // keep eating until full
    if (food < 20 && Eating)
    {
        if (!FindFoodAndEat())
        {
            // ran out of food :(
            Eating = false;
        }
    }
    if (food >= 20 && Eating)
    {
        Eating = false;
        ChangeSlot(LastSlot);
    }
}
```
I have no idea how to fix it :cry:

**Comment by ORelio** [comment]
Seems like in `OnHealthUpdate()`, `FindFoodAndEat()` is called twice. Is it necessary? If `FindFoodAndEat()` returns `true` in the first `if`, then you are already eating, no need to execute the "keep eating" part, right?

**Comment by ReinforceZwei** [comment]
Actually it is necessary. After eating the first food, hunger may exceed the threshold but not at the full hunger. The second call handled that and make player keep eating more food until full.

**Comment by ReinforceZwei** [comment]
I made some improvement for AutoEat in [51f5497](https://github.com/ReinforceZwei/Minecraft-Console-Client/commit/51f54979daf9c71ff073034e16de2684fd9e92f1) but still cannot solve the issue.
I think the cause of the problem is inventory update delay. If the player ate the last food in the hotbar and the hunger bar is not filled up, the next `FindFoodAndEat()` call will return true even no food in the hobar. But if I "make" a HealthUpdate by punching the player later, the `FindFoodAndEat()` work properly and AutoAttack resumed.
So should I add a delay before calling the `FindFoodAndEat()` method?

**Comment by ReinforceZwei** [comment]
It works after adding a bit delay before calling the `FindFoodAndEat()` method.
