### ISSUE TITLE
AutoAttack error

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#936]
![image](https://user-images.githubusercontent.com/35975332/79029680-d7024e80-7bae-11ea-9a2e-da58fefb1ea4.png)

**Comment by ReinforceZwei** [comment]
Could you copy and paste the whole error message to here? I need to translate the message so that I could know what is going on.

**Comment by ORelio** [comment]
Same here, cannot read exceptions in russian, sorry 😄
