### ISSUE TITLE
Add Logging for Internal Commands and Stuff

### ISSUE THREAD

**Issue by Chtholly** [ORelio/Minecraft-Console-Client#938]
Please implement Logging to file for all used Commands and output like eg. Inventory
and i need a .cs for logging playerjoins/lefts to file and send me a message but theres no notification in chat

**Comment by Nekiplay** [comment]
![image](https://user-images.githubusercontent.com/35975332/79060729-165d9780-7ca2-11ea-862a-0cb0c5f39da4.png)
i am use my code

**Comment by ORelio** [comment]
Could be interesting indeed. To my understanding, this would be similar to the existing ChatLog bot, but for logging commands entered in MCC and output of internal commands. Adding this to the TODO list.

**Comment by CarbonNeuron** [comment]
Think this can be closed now due to #984 getting merged.
