### ISSUE TITLE
AutoAttack keeps sending too many packets.

### ISSUE THREAD

**Issue by RedSeal9** [ORelio/Minecraft-Console-Client#942]
When I enable AutoAttack, it keeps kicking me because it sends too many packets.

`00:40:19 [MCC] OnEntitySpawn: Got error from MinecraftClient.ChatBots.AutoAttack: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MinecraftClient.ChatBots.AutoAttack.OnEntitySpawn(Entity entity)
   at MinecraftClient.McTcpClient.OnSpawnLivingEntity(Int32 EntityID, Int32 TypeID, Guid UUID, Location location)

**Comment by ReinforceZwei** [comment]
Are you playing in the vanilla server?
Which Minecraft version is it?

**Comment by RedSeal9** [comment]
It is a spigot server running on 1.12.2.

**Comment by ReinforceZwei** [comment]
Entity handling is not supported in 1.12.2 or lower. It should be automatically disabled when version is unsupported. Not sure why it didn’t.

**Comment by RedSeal9** [comment]
Sorry for such a late comment, but it also supports up to 1.15.

**Comment by ReinforceZwei** [comment]
So it is a multi-version non-vanilla server. Unfortunately, I can only test MCC in vanilla/spigot server with no plugins. Those new features may not guarantee work on some server with special plugins installed. But sure I will take a look at the problem.
