### ISSUE TITLE
 Spawn bot makes the processor heavily loaded

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#943]
![image](https://user-images.githubusercontent.com/35975332/79201098-f15b5700-7e50-11ea-8971-c486e9b61b18.png)
language=ru_RU
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash              # Use 'none', 'slash' or 'backslash'
splitmessagedelay=2                # Seconds between each part of a long message
botowners=Player1,Player2,Player3  # Use name list or myfile.txt with one name per line
botmessagedelay=2                  # Seconds to delay between message a bot makes to avoid accidental spam
mcversion=auto                     # Use 'auto' or '1.X.X' values
brandinfo=mcc                      # Use 'mcc','vanilla', or 'none'
chatbotlogfile=                    # Leave empty for no logfile
privatemsgscmdname=tell            # Used by RemoteControl bot
showsystemmessages=true            # System messages for server ops
showxpbarmessages=true             # Messages displayed above xp bar
showchatlinks=true                 # Show links embedded in chat messages
terrainandmovements=true          # Uses more ram, cpu, bandwidth
inventoryhandling=true            # Toggle inventory handling (beta)
entityhandling=false               # Toggle entity handling (beta)
sessioncache=disk                  # How to retain session tokens. Use 'none', 'memory' or 'disk'
resolvesrvrecords=fast             # Use 'false', 'fast' (5s timeout), or 'true'. Required for joining some servers.
accountlist=accounts.txt           # See README > 'Servers and Accounts file' for more info about this file
serverlist=servers.txt             # See README > 'Servers and Accounts file' for more info about this file
playerheadicon=false                # Only works on Windows XP-8 or Windows 10 with old console
exitonfailure=false                # Disable pauses on error, for using MCC in non-interactive scripts
debugmessages=false                # Please enable this before submitting bug reports. Thanks!
scriptcache=true                   # Cache compiled scripts for faster load on low-end devices
timestamps=true                   # Prepend timestamps to chat messages
autorespawn=true                  # Toggle auto respawn if client player was dead (make sure your spawn point is safe)

**Comment by ORelio** [comment]
If you are talking about [AutoRespawn](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/McTcpClient.cs#L993) this is only a simple `if(` condition in code to tell wether to send a respawn packet automatically or not. You high CPU usage is likely somewhere else 🤔

**Comment by CarbonNeuron** [comment]
Could this be server specific? Perhaps the server is resending the world to the bot when it dies?
