### ISSUE TITLE
AFK standing still

### ISSUE THREAD

**Issue by Skills-mills** [ORelio/Minecraft-Console-Client#945]
So when I afk i get disconnected because I stand still. I found a script but im not sure if i should use it all or just a part of it. Here it is

```ini
# Minecraft Console Client
# ScriptScheduler Tasks
# Example config file

# Structure of a task: [Task] Followed by triggers and other settings.
# The example below contains all the possible fields for a task
# Time is HH:mm format, several different hours can be provided
# Action command can be "script" or any other internal command

[Task]
triggerOnFirstLogin=false
triggerOnLogin=false
triggerOnTime=true
triggerOnInterval=false
timeValue=19:30
timeValue=08:10
timeInterval=0
action=script event.txt

# Another minimal example: some properties may be omitted
# This is highly recommended for improving task readability

[Task]
triggerOnFirstLogin=true
action=script startup.txt

# Of course, the tasks file can contain as much tasks as you want.
# Another example triggered on logging in and every night at midnight:

[Task]
triggerOnLogin=true
triggerOnTime=true
timeValue=00:00
action=log It's midnight!
# Example of task occuring every 30 seconds
# Could be used for jumping as antiAFK method
[Task]
triggerOnInterval=true
timeInterval=30
action=move up
# Enjoy!
# - ORelio
```

**Comment by Skills-mills** [comment]
Ummm dunno why it looks like that but hope you understand it.

**Comment by ORelio** [comment]
You need to use Markdown:
````
```ini
<your content here>
```
````
Edited your post to reformat it correctly 😉

------
Regarding your question, everything you need to configure MCC is in the [config](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config) page. You need to use ScriptScheduler and schedule `move` commands. Here is an example to jump on a regular basis:

**MinecraftClient.ini**
```ini
[Main]
terrainandmovements=true

[ScriptScheduler]
enabled=true
tasksfile=tasks.ini
```

**tasks.ini**
```
[Task]
triggerOnInterval=true
timeInterval=30
action=move up
```


```

**Comment by Skills-mills** [comment]
But i do not really understand. Should i put it all into the config or just some of it?

**Comment by ORelio** [comment]
You need to edit _MinecraftClient.ini_ to set the lines stated above, then create _tasks.ini_ or download _sample_tasks.ini_ from [config](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config) and rename it _tasks.ini_, then perform the edits. You may need to [display file extensions](https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/) for ensuring the file name is correct.

**Comment by Skills-mills** [comment]
I got it now. Thank you very much! :)
