### ISSUE TITLE
Minecraft Console Client vps Script

### ISSUE THREAD

**Issue by James312123** [ORelio/Minecraft-Console-Client#946]
so i need to log in multiple accounts to the same server, and at the moment i am creating new screens and launching

mono MinecraftClient.exe

then logging into the account and server. But every day or so they disconnect so i have to relog them in. so i wondering if it is possible to create a script to log into multiple accounts.

I had been using windows to afk them but upgraded to a vps running ubuntu. here is the script i use on windows if this helps.

start /min MinecraftClient.exe (username) (password) (server) timeout 2

start /min MinecraftClient.exe (username) (password) (server) timeout 2 etc.....

Thank you for your help in advanced

**Comment by ORelio** [comment]
Example with the [`screen`](https://ss64.com/bash/screen.html) command:
https://serverfault.com/a/104670

**Comment by James312123** [comment]
thank you Orelio. Should it be a bat file or .sh?

**Comment by ReinforceZwei** [comment]
It should be a .sh file

**Comment by Mario-Pet** [comment]
> Example with the [`screen`](https://ss64.com/bash/screen.html) command:
> https://serverfault.com/a/104670
> 
> ```
> screen -d -m mono MinecraftClient.exe username password server
> sleep 2
> # ... and so on
> ```

Is there any way to have the screen session the names of the player accounts? So when i do screen -ls, the name of the account will be displayed as a session?

**Comment by ReinforceZwei** [comment]
@Mario-Pet See https://unix.stackexchange.com/questions/12227/setting-a-name-for-a-screen-session/27294

**Comment by ORelio** [comment]
```
screen -S <name> -d -m <your command>
```

**Comment by Mario-Pet** [comment]
> ```
> screen -S <name> -d -m <your command>
> ```

thank you!
