### ISSUE TITLE
Server capatcha

### ISSUE THREAD

**Issue by tgwecho** [ORelio/Minecraft-Console-Client#948]
The server I am trying to use this on has a gui capatacha. It is one of the "find the correct item" The only way to find this correct item in game is to hover over the items in the inventory and it gives in the description of that item either correct item in green or incorrect item in red. When i say description its like when you hover over a water bottle it says in grey "no effect". Is their away to solve these capatchas?

**Comment by ORelio** [comment]
Use `/inventory`. See #894. Please note that inventory handling is still unfinished.
