### ISSUE TITLE
minecraft login failed : Network error

### ISSUE THREAD

**Issue by tobimus** [ORelio/Minecraft-Console-Client#949]
hey, my client saying that there is a minecraft login failed : Network error.
How can i fix this i really love to use this console client and needed it fixed
![Udklip](https://user-images.githubusercontent.com/63739100/79363328-0d8def80-7f48-11ea-9264-9ec3320fd882.PNG)

**Comment by ReinforceZwei** [comment]
Code 520 is internal server error, which means the problem is on the Mojang side. We couldn’t do anything :(

**Comment by tobimus** [comment]
but it work on my other computer why is that then?

**Comment by ReinforceZwei** [comment]
Please set `debugmessage` in the .ini file to true and try again, then paste the new message here so that we can see more information about what is going on.

**Comment by tobimus** [comment]
i cant find the debugmessage, where is it?

**Comment by tobimus** [comment]
now itss says this and i dont know what to do, i didnt do that debugmessage yet but it says this now 
![Udklip](https://user-images.githubusercontent.com/63739100/79378612-e7734a00-7f5d-11ea-9629-58c767da73cd.PNG)

**Comment by tobimus** [comment]
will u guys pls help me? :( i need this to work

**Comment by Mhowser** [comment]
Your IP might be blacklisted by mojang, try connecting with out a VPN if you have one

**Comment by tobimus** [comment]
ok i will try an vpn on, do u have any good free vpn's?

**Comment by tobimus** [comment]
it still doesnt work with an vpn on but my folder is like this
![Udklip](https://user-images.githubusercontent.com/63739100/79488393-f3244680-8019-11ea-9ccd-bce659095332.PNG)

**Comment by Mhowser** [comment]
The folder looks normal, try deleting the sessioncache file and reconnect. BTW there is no free VPN that is also good. I recommend Mullvad VPN. https://mullvad.net

**Comment by tobimus** [comment]
so i can justt delete it and it would be fine

**Comment by tobimus** [comment]
but it says when i try to reconnect (file not found : kickmessages.txt)

**Comment by tobimus** [comment]
hmm?

**Comment by tobimus** [comment]
what can i do so it work?

**Comment by ORelio** [comment]
create `kickmessages.txt` and write `Failed to connect to this IP` inside.

**Comment by tobimus** [comment]
i cant get it to work, is there any there can help me delete it and download it again?

**Comment by ORelio** [comment]
Create an empty folder and download the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) inside it.
