### ISSUE TITLE
i have a crash problem

### ISSUE THREAD

**Issue by kendir35** [ORelio/Minecraft-Console-Client#950]
![unknown](https://user-images.githubusercontent.com/63727203/79439471-8c813780-7fdd-11ea-9957-d044bf35aa39.png)
![unknown (1)](https://user-images.githubusercontent.com/63727203/79439497-930faf00-7fdd-11ea-8ff2-666182297fbf.png)
after logging in to the server, i encounter such a problem. pls help

**Comment by ORelio** [comment]
Never managed to reproduce, sorry. Related: #471
