### ISSUE TITLE
Failed to check session

### ISSUE THREAD

**Issue by Atarka2** [ORelio/Minecraft-Console-Client#951]
recently i have been getting failed to check session messages even though i am using the latest version, on some occasions immediatly when i launch it i get a failed to check session error message, and on some occasions when it attempts to reconnect i get the message. this is extremely annoying since it renders the client useless

**Comment by IchUseKomplexe** [comment]
Same for me

**Comment by slutfarm** [comment]
Same.

**Comment by CarbonNeuron** [comment]
Same!

**Comment by CarbonNeuron** [comment]
`Performing request to sessionserver.mojang.com
> POST /session/minecraft/join HTTP/1.1
> Host: sessionserver.mojang.com
> User-Agent: MCC/1.12.2 DEV
> Content-Type: application/json
> Content-Length: 433
> Connection: close
> 
> {"accessToken":"REDACTED","selectedProfile":"REDACTED","serverId":"REDACTED"}

< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Connection: close
< Date: Sat, 18 Apr 2020 00:56:26 GMT
< x-minecraft-request-id: d13103463d9c9511
< X-Cache: Miss from cloudfront
< Via: 1.1 010086e284fd9714db3b3e3d1d295b60.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: ORD51-C1
< X-Amz-Cf-Id: 5y7CUO40WJbRR47GIwe9_x-KQQm4P7THoskbpYOQPPwfTloyAVqCjA==
< 
< 0
< 
< 
`
This is with debug messages on. Is the connection supposed to be closed?

**Comment by ORelio** [comment]
Thanks for raising the issue, should be fixed in latest dev build including @CarbonNeuron's fix 👍
