### ISSUE TITLE
Failed to check session

### ISSUE THREAD

**Issue by techboy41** [ORelio/Minecraft-Console-Client#953]
https://gyazo.com/93e2a8c13f12e2bfdb96ab50fe7ee971

I've been looking this issue up for a while and can't figure out the issue. I don't know a lot of code if any. Thanks.

**Comment by ORelio** [comment]
Beware not to put unredacted access tokens into your screenshots, someone might be able to use it to log on a server as you. Closing as duplicate of #951.
