### ISSUE TITLE
Need Help! AutoRespond don't work.

### ISSUE THREAD

**Issue by MatrixSystemPVP** [ORelio/Minecraft-Console-Client#956]
Hey,
my AutoRespond doesn't work.
I want that when i get kicked to hub it should send a command to join again.

Here is my matches.ini: 
[Match]
regex=^.*[[:space:]]*Type /server to join a server.*$
action=script startup

[Match]
regex=^.*▪ Welcome to MineSuperior ▪.*$
action=script startup

I want that either the first match works or the second idc.
I didn't got both to work but at https://regex101.com it says "Full match"

Here is also how the messages looks like in the console: 
![Anmerkung 2020-04-21 092824](https://user-images.githubusercontent.com/39440609/79838186-e6557900-83b2-11ea-9808-53d143e6309b.png)

**Comment by Chtholly** [comment]
use tasks.ini

[Task]
triggerOnLogin=true
script=startup.ini

**Comment by MatrixSystemPVP** [comment]
Yea i have this also, but the problem is that it that the auto reconect doesnt work.
I putted all letters from a-z in a seperat line in the kickmessages.txt. so normaly it should reconnect on every kick message.

**Comment by snc-bat** [comment]
Hi Matrix, we play on the same server! :D

Try actionother= instead of action=

**Comment by MatrixSystemPVP** [comment]
@snc-bat oh wow. Ok now the matches work :)
Can i ask you what your In game name is? mine is MatrixSystemPVP :D

**Comment by snc-bat** [comment]
@MatrixSystemPVP I messaged you in-game.

**Comment by ORelio** [comment]
Closing as resolved 😉

Also FYI `match=Type /server to join a server` should work, regex seems overkill here.
