### ISSUE TITLE
Failed to check session 

### ISSUE THREAD

**Issue by Forssmark** [ORelio/Minecraft-Console-Client#957]
Hi 
I have been trying to get the console client to work on cosmic prisons. I keep running into the same problem were the login fails after a few kicks. I have the latest build of the client but still, run into the same problem.

**Comment by Voltikenzi** [comment]
same

**Comment by r3spawned** [comment]
Try this build :

https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by Forssmark** [comment]
Orelio im using that build it still dosent work for me...

**Comment by ORelio** [comment]
You are not using the latest build, your issue was fixed in commit 52248d1abaf9b03047f90caa465f5f0b466f7c56. Duplicate of #951.

**Comment by Forssmark** [comment]
Orelio the build im using is the one you liked... it doesn't work.

**Comment by TNTUP** [comment]
I can confirm this **fix** works fine! Been a week like that I was using outdated builds, something Mojang changed like always :/
