### ISSUE TITLE
20w16a support

### ISSUE THREAD

**Issue by LaineZ** [ORelio/Minecraft-Console-Client#958]
Hello how about adding 20w16a snapshot version? i tried add snaphot protocol support (712) but i got unknown exception from server side i don't know how debug this: client connecting, but after 2-3 seconds server kicks with reason: ```Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)```
also, i tried run server in debug mode but does not any addtional information for me 
Debug-mode server log:
[latest.log](https://github.com/ORelio/Minecraft-Console-Client/files/4511347/latest.log)

**Comment by ORelio** [comment]
Snapshots will not be handled, because this simply requires too much work.

**Comment by ORelio** [comment]
Of course if you want to implement it for your own tests, see [Pre-release protocol](https://wiki.vg/Pre-release_protocol).

**Comment by LaineZ** [comment]
thanks for this wiki - i aready fixed that problem :)
