### ISSUE TITLE
Ability to sneak/crouch?

### ISSUE THREAD

**Issue by Voltikenzi** [ORelio/Minecraft-Console-Client#959]
Looking for an ability to get the console to hold down sneak animation/button. Simply move down does not work.  Not very skilled in Csharp coding either.

**Comment by ReinforceZwei** [comment]
I am just curious, why do you want to sneak?

**Comment by Voltikenzi** [comment]
Just because, aside from the fact some servers use custom elevator pads now where you sneak to go down, and jump to go up

**Comment by ORelio** [comment]
You'd need to implement [Entity Action](https://wiki.vg/Protocol#Entity_Action) for that.

**Comment by Voltikenzi** [comment]
what about walking onto pressure pads?

**Comment by ORelio** [comment]
Should work with `/move`.

**Comment by ReinforceZwei** [comment]
Implemented in https://github.com/ORelio/Minecraft-Console-Client/pull/984
