### ISSUE TITLE
Can't input end square and curly brackets in non-GUI

### ISSUE THREAD

**Issue by 1b8** [ORelio/Minecraft-Console-Client#96]
When I use the non-GUI version, I can't put in `}`s or `]`s, but I can put in `{`, `[`, `(`, and `)`.

**Comment by ORelio** [comment]
Did you try [latest development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/) ? This issue should [already be fixed](https://github.com/ORelio/Minecraft-Console-Client/commit/546119a33457b84cb16e1e48b003e8a2aef19f88) in development version.
