### ISSUE TITLE
Give a line if there is an error in a C# script.

### ISSUE THREAD

**Issue by Daenges** [ORelio/Minecraft-Console-Client#961]
It is very frustrating if you write a script, which doesn't work. Luckily the console gives you an error, so you can see what went wrong. The problem I have, is that I get the error, sometimes with a method, if some error was created while running, but if the error was created while compiling, I just get the plain text on what went wrong, which is better than nothing, but it is very tidious to search through many lines to find possible places, where the error could have occured.

My sollution for this would be a line number in the error message, so you find the error faster in your script.

**Comment by ORelio** [comment]
If you take a look at [CSharpRunner.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/CSharpRunner.cs) you'll see that your code is taken to generate a C# class. As a result, line numbers would not match line numbers in your script file.

If you need to develop a ChatBot, I'd recommend to load the MCC project into Visual Studio (or other development environment) and add your bot in the ChatBots directory. Then load it by adding a call for it in [McTcpClient.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/McTcpClient.cs#L173), and try compiling MCC. You'll benefit from all the debugging capabilities of your development environment.

Once you are done developing, wrap your bot into a script so you can load it into MCC development builds without rebuilding MCC yourself every time you want to upgrade to a newer version 😉

**Comment by Daenges** [comment]
> 
> 
> If you take a look at [CSharpRunner.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/CSharpRunner.cs) you'll see that your code is taken to generate a C# class. As a result, line numbers would not match line numbers in your script file.
> 
> If you need to develop a ChatBot, I'd recommend to load the MCC project into Visual Studio (or other development environment) and add your bot in the ChatBots directory. Then load it by adding a call for it in [McTcpClient.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/McTcpClient.cs#L173), and try compiling MCC. You'll benefit from all the debugging capabilities of your development environment.
> 
> Once you are done developing, wrap your bot into a script so you can load it into MCC development builds without rebuilding MCC yourself every time you want to upgrade to a newer version 😉

Thanks for your reply!
Apparently I'm a bit confused. If I try to open "MinecraftClient.sln" with Visual Studios I get an empty file. The same goes with "MinecraftClient.csproj".  Am I openinge the wrong files?

Second question:
Is there a way to attach own "using" parameters to my script? I made a mail function and want to temporary save the mails to a json file. The problem is, that the "json.cs" can only read json code and convert it to an object. It may be the case that I interpreted some things wrong in "json.cs" please correct me if I'm wrong there. :)

**Comment by ORelio** [comment]
When opening a solution or project for the first time, no source code file is open. By default, you should have a "Solution Explorer" panel allowing you to open a source code file, e.g. Program.cs:

![Microsoft Visual Studio](https://visualstudio.microsoft.com/wp-content/uploads/2019/03/lightbulb-dark-Still-1200.jpg)

On the example above, the Solution Explorer panel is on the right side.

Regarding your second question, you can use `//using` comments

```C#
//MCCScript 1.0
//using System.Text.RegularExpressions;

Regex rx = new Regex("hello");
```

External libraries are not handled by CSharpRunner.cs
You may use `System.Runtime.Serialization` to serialize to a binary file. Json.cs can only read JSON.

**Comment by Daenges** [comment]
> 
> 
> When opening a solution or project for the first time, no source code file is open. By default, you should have a "Solution Explorer" panel allowing you to open a source code file, e.g. Program.cs:
> 
> ![Microsoft Visual Studio](https://camo.githubusercontent.com/78d12b56d36ba81f481dba7804997178cacfa9bf/68747470733a2f2f76697375616c73747564696f2e6d6963726f736f66742e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031392f30332f6c6967687462756c622d6461726b2d5374696c6c2d313230302e6a7067)
> 
> On the example above, the Solution Explorer panel is on the right side.
> 
> Regarding your second question, you can use `//using` comments
> 
> ```cs
> //MCCScript 1.0
> //using System.Text.RegularExpressions;
> 
> Regex rx = new Regex("hello");
> ```
> 
> External libraries are not handled by CSharpRunner.cs
> You may use `System.Runtime.Serialization` to serialize to a binary file. Json.cs can only read JSON.

Okay, I got it to work! Apparently I deactivated the Solution explorer panel. -_- 
(thanks for your pations with me! ;D )
I'm already working on the Serialization and it looks very good atm. So again thanks for your help and your patience! :)
