### ISSUE TITLE
I want to make a script that sends the same message every few minutes

### ISSUE THREAD

**Issue by TaranArora** [ORelio/Minecraft-Console-Client#962]
I've enabled script scheduler and created a tasks.txt file with this :

[Task]
triggerOnInterval=true
timeInterval=600
script=tasks.txt

send [Message]

------------------
i want this to be sent in chat every 5 mins,as of now it sends the message when i join the server and when the alt is in hub,after that this doesn't send any more.Any help would be appreciated:)

**Comment by snc-bat** [comment]
I think it should be `action=script tasks.txt` instead of `script=tasks.txt`

**Comment by ORelio** [comment]
I'd suggest `action=send (YOUR MESSAGE HERE)` if you want to send a single message.
