### ISSUE TITLE
Project File Does not Exist Error

### ISSUE THREAD

**Issue by IceyPoop** [ORelio/Minecraft-Console-Client#965]
<img width="377" alt="Screen Shot 2020-04-22 at 11 19 29 PM" src="https://user-images.githubusercontent.com/64187568/80066011-fd4db580-84ef-11ea-8227-35e6167e040e.png">
Hi, I tried downloading this console client today on a Mac OS, but after downloading the mono framework, then typing "msbuild MinecraftClient.csproj" into terminal, the error that the "Project file does not exist" then pops up. Does anyone know how to fix this?
Please let me know! Thanks

**Comment by ORelio** [comment]
You need to move to the correct folder.
* `pwd`: show current folder path
* `cd <folder>`: move to the desired folder
