### ISSUE TITLE
Sometimes "server version" says a player's name

### ISSUE THREAD

**Issue by 1b8** [ORelio/Minecraft-Console-Client#97]
Sometimes, when a server is loading, it says an online player's name as the server version. For example:
```
Server version : SomeOnlineGuy62 (protocol v47).
```

**Comment by ORelio** [comment]
Did you try [latest development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/) ? This issue should [already be fixed](https://github.com/ORelio/Minecraft-Console-Client/commit/67affc62702a6e3f6bc37c8abaf148b0ad32c4d8#diff-1fbdfd3211d0ba74aa742d4f2249b9e5R590) in development version.
