### ISSUE TITLE
Pathfinding algorithm is very slow

### ISSUE THREAD

**Issue by LaineZ** [ORelio/Minecraft-Console-Client#970]
/move command and move player function tooks too much time to compute path in 20+ blocks

**Comment by ORelio** [comment]
Indeed, the current pathfinding algorithm is not very fast. It is based on a single-threaded implementation of the A* algorithm ([Movement.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Movement.cs#L130)) and might benefit from threading.
Any contribution in that field would be welcomed.

**Comment by CarbonNeuron** [comment]
I am looking into this and I am wondering if we need 3D pathfinding if the clients can't really move up blocks. Maybe for moving down blocks?

**Comment by ORelio** [comment]
@CarbonNeuron This is necessary to climb up steps of 1 block (jumping to reach a higher block) and jumping cliffs of up to 2 blocks (falling intentionally to reach the indented location).

**Comment by ORelio** [comment]
Closing this in favour of #219
