### ISSUE TITLE
Using local Vars in Script

### ISSUE THREAD

**Issue by Chtholly** [ORelio/Minecraft-Console-Client#971]
Ive tryed and seared over hours, but it wont works

I play on a server wheres an event when 100 players sold a specific item.
Theres a command to see how much have sold,

My regex works to set a local var
action=set Event=$2
$2 could be 15/100

But how can i use this var in a .cs script ?
Settings.GetVarAsString(Event);
ConsoleIO.WriteLineFormatted("§5[EventListener] " Already + Event + " Items have been sold.");

**Comment by ORelio** [comment]
Try ` Settings.GetVarAsString("Event");`. Also, since you are using the C# API, maybe, you can make a C# ChatBot which would process the OnChatMessage event instead of relying on the AutoRespond bot?

**Comment by Chtholly** [comment]
Already tryed string Event = Settings.GetVarAsString("Event");
Error:  System.InvalidOperationException , theres no difinition for GetVarAsString

**Comment by ORelio** [comment]
Indeed, it's `string Event = MCC.GetVarAsString("Event");`.

**Comment by Chtholly** [comment]
Works now without Errors, but the var Event replaced by a space char
ConsoleIO.WriteLineFormatted("§5[EventListener] " Already + Event + " Items have been sold.");
output:
[EventListener] Already   Items have been sold.

**Comment by ORelio** [comment]
The variable is empty (i.e. not set yet).

**Comment by Chtholly** [comment]
The variable wasnt empty.
action=set Event=$2
$2 could be 15/100
& tryed with command /set Event=unknown
still whitespace

**Comment by Chtholly** [comment]
So what i need to change to detect server-messages ?

    public override void GetText(string text)
    {
        string message = "";
		string username = "";
        text = GetVerbatim(text);
 if (IsChatMessage(text, ref message, ref username))
    {

**Comment by ORelio** [comment]
Example of applying a regex on server messages in a ChatBot:
```C#
public override void GetText(string text)
{
    string message = "";
    string username = "";
    text = GetVerbatim(text);

    if (!IsChatMessage(text, ref message, ref username)
        && !IsPrivateMessage(text, ref message, ref username))
    {
        //Not a chat/private message
        Regex regex = new Regex("REGEX GOES HERE (GROUP1)");
        Match regexMatch = regex.Match(text);
        if (regexMatch.Success)
        {
            // Regex is matching, lets process the result
            string capturedData = regexMatch.Groups[1].Value;
            // ...
        }
    }
}
```
Remark: The full ChatBot API can be found in [ChatBot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs).
