### ISSUE TITLE
Want to send random commands

### ISSUE THREAD

**Issue by TaranArora** [ORelio/Minecraft-Console-Client#972]
So basically there's a coinflip plugin on a server i play on.i want the alt to either type /cf new [amount] heads or /cf new [amount] tails.i want this t be randomized so that some times it opts for heads and sometimes it opts for tails.is there a way to do this?

my current task:
[Task]
#cf bet
triggerOnInterval=true
timeInterval=5
action=send /cf new [amount] heads

**Comment by ORelio** [comment]
You'd need to make a C# script. Here is an example:

**random.cs**
```C#
string[] commands = new[] {
    "send command1",
    "send command2",
    "send command3"
};

int randomIndex = new Random().Next(0, commands.Length);
string randomCommand = commands[randomIndex];
MCC.PerformInternalCommand(randomCommand);
```

**Comment by TaranArora** [comment]
> You'd need to make a C# script. Here is an example:
> 
> **random.cs**
> 
> ```cs
> string[] commands = new[] {
>     "send command1",
>     "send command2",
>     "send command3"
> };
> 
> int randomIndex = new Random().Next(0, commands.Length);
> string randomCommand = commands[randomIndex];
> MCC.PerformInternalCommand(randomCommand);
> ```

can i just copy this and make a new file and how do i call this file?how do i use it?

**Comment by ORelio** [comment]
directly: `/script random.cs`
via scriptscheduler: ` action=script random.cs`

**Comment by TaranArora** [comment]
i tried it but it give me this error:
[MCC] [Script] Script 'random.cs' failed to run (InvalidScript).
[MCC] [Script] System.IO.InvalidDataException: The provided script does not have a valid MCCScript header

**Comment by ORelio** [comment]
Indeed.
```
//MCCScript 1.0

string[] commands = new[] {
    "send command1",
    "send command2",
    "send command3"
};

int randomIndex = new Random().Next(0, commands.Length);
string randomCommand = commands[randomIndex];
MCC.PerformInternalCommand(randomCommand);
````

**Comment by TaranArora** [comment]
Wow thanks a lot,this worked perfectly.
