### ISSUE TITLE
Create script which runs command every 2 seconds for 2 minutes then stops

### ISSUE THREAD

**Issue by swaggyjj** [ORelio/Minecraft-Console-Client#973]
I want to create a script which I can manually trigger after I have connected to a server which sends "/world join" every 2 seconds for only 2 minutes. After 2 minutes, the script ends until I manually trigger it again. 

I know this seems super basic, I've researched online and no one seems to have done something similar.

**Comment by swaggyjj** [comment]
Ok so for future reference for anyone
Change the `[ScriptScheduler]` to true in the `minecraftclient.ini` file. 

> [ScriptScheduler]
enabled=true
tasksfile=tasks.ini

Create a new ini file called `tasks.ini`, with the code below. (You can copy and paste minecraftclient.ini file and delete everything then copy and paste the code below, just remember to change the name)

> [Task]
triggerOnInterval=true
triggerOnFirstLogin=true
triggerOnInterval=false
script=serverjoin.txt

Create a new text file called `serverjoin.txt`. In this text file you put the command you want to run. In my case, I want to run 
> /world join 

every 2 seconds. So the code inside the `serverjoin.txt` is as follows

> send /world join
wait 10

where `10` is the duration to wait in between sending commands. I am not sure what unit this is so you might have to use trial and error to get the timings correct for the commands to be sent.

In order to run this for 2 minutes, simply copy and paste this below as many times as you want to run the command like this. 

> send /world join
wait 10
send /world join
wait 10
send /world join
wait 10
send /world join
wait 10
send /world join
wait 10

Again, trial and error is required in order to run it for a certain duration you want. Copy and paste as many times as you need. I have next to no coding level lol

Hope this helps :)

**Comment by ORelio** [comment]
I can confirm this is the easiest way, so without writing a C# script 😉
