### ISSUE TITLE
AutoRelog: Sequentially reconnect clients with delay

### ISSUE THREAD

**Issue by MattiasMoenster2019** [ORelio/Minecraft-Console-Client#975]
Would like to see a feature that allows Multiple proxy connections for logging on a LOT of accounts at once 
Am playing on a server where it's necessary to have a shit ton of alts so would like to see this implemented honestly have no idea how it would work but oh well

**Comment by ORelio** [comment]
I cannot see a legitimate use case for using lots of proxies. Looks like a feature that would benefit spammers trying to circumvent IP bans put by server staff rather than a feature that would help users to login when the official session server is blacklisted on your hotel, university or your VPN is blacklisted by Mojang; since in that case you would only need one proxy.
Related issue: #748

**Comment by MattiasMoenster2019** [comment]
The case is that I got my IP on my VPS blacklisted from Mojang so I can't log in and if I use a proxy to log them all in that proxy gets banned after 2-4 times of doing that

**Comment by ORelio** [comment]
In that case maybe you should enable session cache on disk and put a delay between logins.

**Comment by MattiasMoenster2019** [comment]
I already have disk cache thingy on my pc but whenever i log the alts on and there is a server reboot then when it tries to reconnect it will reconnect Them All at the same time and then mojang blacklists for “too many logins”

**Comment by CarbonNeuron** [comment]
Maybe an improvement to AutoRelog would be a random delay.

**Comment by MattiasMoenster2019** [comment]
Maybe not a random delay but a reconnect delay between open clients would be epic

**Comment by ORelio** [comment]
Totally approve this. That would be even better than trying to use multiple proxies. The clients would need to synchronize between each other, in a similar fashion than with the session handling database. Adding this to the TODO list. 😉

**Comment by MattiasMoenster2019** [comment]
Looking forward to see this implemented :)

**Comment by ORelio** [comment]
If you have many accounts to reconnect, you may now set `delay=10-60` or any other ranges so that each client randomly chooses a different delay and avoid all accounts to reconnect at once.
