### ISSUE TITLE
Unable to connect to a server: Connection refused

### ISSUE THREAD

**Issue by daboihonza** [ORelio/Minecraft-Console-Client#976]
System.Net.Sockets.SocketException: Connection refused
I get this error when I connect to my server. I specify version 1.12.2, which I believe that is supported (if possible, I'd like 1.15.2). The app just gives me this error whenever I try to run it.
I'm running on MacOS Mojave with Mono, all newest versions

**Comment by ORelio** [comment]
This may be related to DNS name resolution leading MCC to connect to an incorrect IP address, hence the "connection refused" error message. See #858 for how to enable DNS SRV records.

**Comment by daboihonza** [comment]
I was not able to find that setting in MinecraftClient.ini, so I opted for the option of giving the IP of the server (e.g. 1.1.1.1:26556). It didn't give me the same error, rather none. I ran it, it logged in, checked the session and quit.
![Screenshot 2020-04-28 at 07 42 48](https://user-images.githubusercontent.com/23482862/80451423-23c28500-8924-11ea-8365-d5e90f2dc038.png)

**Comment by ORelio** [comment]
You are using a very old build of Minecraft Console Client...
Get the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by daboihonza** [comment]
Now, it gives a different error - I set resolvervrecords to true and it gave me a longer output, but it still ended at Checking Sesson.
![Screenshot 2020-04-29 at 07 16 46](https://user-images.githubusercontent.com/23482862/80562926-8df12d80-89e9-11ea-825f-b505b7e22a0d.png)

**Comment by ORelio** [comment]
This is weird that nothing is printed between "Checking Session" and program exit 🤔
Try with `debugmessages=true` in config?

**Comment by daboihonza** [comment]
https://pastebin.com/vkHa9KY9
That is the whole output of the program. I checked for passwords, but I couldn't find any, so I replaced my clientToken (which I found important) with [clientToken] and email with [email]

**Comment by ORelio** [comment]
I was able to reproduce your issue by attempting to join your server. Apparently, the server is running Minecraft 1.15.2 but reports protocol v61 which is Minecraft 1.5.2. MCC tries to join using 1.5.2 protocol compatibility but the server does not properly implement this protocol and responds with an invalid message to the handshake attempt. Just added more error messages to help diagnose future issues like this one, you can try in in the newest development build.

Regarding your initial issue: I think you can join your server by forcing `mcversion=1.15.2` in config.

**Comment by daboihonza** [comment]
Thanks! I just realized that I have ProtocolSupport installed, so I got rid of that and it works!
