### ISSUE TITLE
Question (Combined consoles)

### ISSUE THREAD

**Issue by MattiasMoenster2019** [ORelio/Minecraft-Console-Client#978]
Just a quick question are there anyway to send a command to every client open without having to run a script something like a shared console?

**Comment by ORelio** [comment]
No as consoles won't interact with each other. Some workarounds:
 - though the RemoteControl feature by sending your command to all clients using a script
 - or using ScriptSheduler eg. by running command.txt every minute, then put your command there

**Comment by MattiasMoenster2019** [comment]
If i use the script scheduler will i be able to change the script without closing the clients?

**Comment by ORelio** [comment]
The trick here would be to schedule the script then manually edit it using a notepad application. The clients would reload and execute the script on a regular basis, so editing the file would change the command being executed without having to relaunch the clients. The only downside to this would be that clients may run your script twice.

**Comment by MattiasMoenster2019** [comment]
Yeah that was kinda what i Got from the last MSG too just had to make sure and ty for all the replies :)

**Comment by ORelio** [comment]
Glad it helped. Closing as resolved.
