### ISSUE TITLE
How would I utilize chatbots to make the bot look at the closest person?

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#979]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Your question may contain the following items:
I have been trying to make a chatbot that can look at the closest entity, and to exclude certain people, like other bots. Is there a way for me to look up the UUID or the playername of the entity?

**Comment by CarbonNeuron** [comment]
Looking at `/// <summary>
        /// Called when a player was spawned/in the render distance
        /// </summary>
        /// <param name="EntityID"></param>
        /// <param name="UUID"></param>
        /// <param name="location"></param>
        /// <param name="Yaw"></param>
        /// <param name="Pitch"></param>
        public void OnSpawnPlayer(int EntityID, Guid UUID, Location location, byte Yaw, byte Pitch)
        {
            if (entities.ContainsKey(EntityID)) return;
            Entity entity = new Entity(EntityID, EntityType.Player, location);
            entities.Add(EntityID, entity);
            foreach (ChatBot bot in bots.ToArray())
            {
                try
                {
                    bot.OnEntitySpawn(entity);
                }
                catch (Exception e)
                {
                    if (!(e is ThreadAbortException))
                    {
                        ConsoleIO.WriteLogLine("OnEntitySpawn: Got error from " + bot.ToString() + ": " + e.ToString());
                    }
                    else throw; //ThreadAbortException should not be caught
                }
            }
        }`
It seems like it is possible, just not implemented. I'll go ahead and add a pull request to fix this.

**Comment by CarbonNeuron** [comment]
Fixed in #980

**Comment by ORelio** [comment]
Thanks for your PR, merged it. Regarding your question: There is some code [here](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/McTcpClient.cs#L709) to look at a location, so maybe you could adjust the ChatBot API to allow looking at a location 🙂

**Comment by CarbonNeuron** [comment]
I did actually complete this. If you'd like I can post it as a pull request.

**Comment by ORelio** [comment]
Sure, that would be helpful for other people wanting to look at a location in their ChatBot 👍

**Comment by CarbonNeuron** [comment]
Added in #982 Which implements both of these.

**Comment by ReinforceZwei** [comment]
How about implementing another similar function, instead of just looking at the player, but follow the player and move?
I think it would be easy to implement, base on the looking at player implementation.

**Comment by ORelio** [comment]
Implemented as per #982. @ReinforceZwei Sure, do not hesitate to write ChatBot that does this, would be quite useful. However, pathfinding is currently quite slow (#970), so it might considerably hinder the ability to properly follow a player.
