### ISSUE TITLE
Add support for UTC in ScriptScheduler

### ISSUE THREAD

**Issue by Grewfisk** [ORelio/Minecraft-Console-Client#98]
I use your program every day. It's been a great resource.

I've been distributing a script to members of a server that keeps them logged in through server restarts. The use of local time in the script scheduler means that every user of the script has to manually edit the restart times, adding a layer of complexity.

It would be awesome if you added a way to use UTC time instead of local time. Something like useUTC=true where it defaults to local unless that is specified.

Thanks for your consideration.

Sample of relevant script:
[Task]
triggerOnTime=true
timeValue=00:18
timeValue=02:18
timeValue=04:18
timeValue=06:18
timeValue=08:18
timeValue=10:18
timeValue=12:18
timeValue=14:18
timeValue=16:18
timeValue=18:18
timeValue=20:18
timeValue=22:18
timeValue=24:18
script=nerdnu_pve_joinserver.txt

The full script: http://pastebin.com/y5LAJJMp

**Comment by ORelio** [comment]
Hello,
And thanks for your appreciation!
Why not using `AutoRelog` with `Server is restating!` kick message configured?
This would automatically relog without the need of manually defining restart times, isnt't it?

**Comment by Grewfisk** [comment]
That's the first thing I tried.

For some reason it doesn't act on any message that I put in the kickmessages file. Is the kickmessages looking at the chat? Or something else?

Another problem if the relog actually worked: The server dumps everyone to a lobby, so the autorelog would login to the lobby instead of the target server (since the target is down it sends you to the lobby). It takes about a minute for the server to come back online after a restart.

**Comment by ORelio** [comment]
Hello,
It's based on the text that appears on screen when you are kicked from the server, eg, if you see `Server is restating!` just put the word `restarting` in your kick messages file. Then, you may specify that the AutoRelog bot is enabled, where is the kick messages file, and what is the _delay before reconnecting_ in the main INI file.

**Comment by ORelio** [comment]
The issue should be fixed, but feel free to reopen if needed ;)
