### ISSUE TITLE
Create a inventory script with variable

### ISSUE THREAD

**Issue by Stymix** [ORelio/Minecraft-Console-Client#981]
Hi, i use your console client since 1 week, and I have a question.

I have a server where there is a /invest, but there is a Inventory
So I use /inventory (id) click 24

But I need to write every hour /invest (to open the gui) and that's create a new GUI, so the number of the ID change.

Do u know how to make a script who use a variable at every utilisation ? 
And who's in charge the inventory ?

Thanks !

**Comment by ORelio** [comment]
I think that you cannot have more than 2 inventories open concurrently (player and container), so maybe we could improve the Inventory command to better designate inventories. Currently, the inventory ID is given by the server. 0 is player inventory, greater numbers are for any other inventory.

Relevant contributors for Inventory are @ReinforceZwei and myself.

**Comment by ORelio** [comment]
@ReinforceZwei I'll handle this request 😉

**Comment by Stymix** [comment]
Yes yes that's not the problem 
My only one problem right now is
How to add the command Inventoryi in a script ?

**Comment by Stymix** [comment]
Est il possible que tu viennes me contacter via Discord stp ? Pour que ce soit plus facile ? 
Stymix#5540

**Comment by ORelio** [comment]
Unfortunately, I cannot handle individual requests on Discord. The requested change has been implemented in the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). You can now use `/inventory container` and the command will automatically determine the container ID for you.

**Comment by Stymix** [comment]
Yes but how to use it in a script ?

**Comment by ORelio** [comment]
Any command can be used directly in a script, simply remove the leading `/` 🙂
