### ISSUE TITLE
How to use Inventory command in a script

### ISSUE THREAD

**Issue by Stymix** [ORelio/Minecraft-Console-Client#985]
Hi, someone can help me ? 

I need to make a script who help me by using the command of Inventory 
(inventory (variable set in parameters when I use /script programme 5) click 20

But I don't know how I can use Inventory in a script.

Best regards,
Thanks

**Comment by Chtholly** [comment]
MCC.PerformInternalCommand("inventory container click 20");

**Comment by Stymix** [comment]
Can u help me to make a .cs script pls ?

**Comment by ORelio** [comment]
You do not need to use a C# script if you just want to perform a few internal commands.
Just use a text script with the command directly into it:

**inventoryclick.txt**
```
inventory container click 20
```

**Comment by Stymix** [comment]
Inventory container doesn't work

**Comment by ORelio** [comment]
Please provide output with `debugmessages=true` in config. "doesn't work" is not a bug report 😄

**Comment by Stymix** [comment]
There is no message 
They said "inventory <ID> (list | close | click id)

**Comment by ReinforceZwei** [comment]
Are you using the newest version of MCC?

**Comment by Stymix** [comment]
I think yes, i'm download again the latest to try.
I will tell you that in 30 minutes

**Comment by Stymix** [comment]
Ok fine it work thanks man !
