### ISSUE TITLE
All accounts in one window

### ISSUE THREAD

**Issue by Geographs** [ORelio/Minecraft-Console-Client#986]
Hi, I an wondering if there is a way I can get all my accounts in 1 window of MCC

**Comment by ORelio** [comment]
MCC does not handle multiple accounts at the same time. The only way currently would be using a tabbed terminal such as [GNOME terminal](https://en.wikipedia.org/wiki/GNOME_Terminal) or [Cmder](https://cmder.net/) then open one account in each tab.
