### ISSUE TITLE
Question coding using inventory

### ISSUE THREAD

**Issue by lilobject** [ORelio/Minecraft-Console-Client#987]
Is it possible to code it so I can right click on a certain space in my inventory a set number minutes apart from each other? I'm sorry if this is easy or unable to work, it would help me out immensely if someone would be able to help me figure out how to do this or add a piece of code to it! Thanks!

**Comment by CarbonNeuron** [comment]
Pretty sure you could use the Script schedular to call the inventory command at a set interval.

**Comment by Stymix** [comment]
> Pretty sure you could use the Script schedular to call the inventory command at a set interval.

Do u know how to call the inventory command in script ? 

If yes, can u make an example ?

**Comment by lilobject** [comment]
> > Pretty sure you could use the Script schedular to call the inventory command at a set interval.
> 
> Do u know how to call the inventory command in script ?
> 
> If yes, can u make an example ?

Please ^^

**Comment by ORelio** [comment]
Currently, MCC only implements left click in inventory. You cannot move items or perform other operations at the moment, but contributions are welcome.

**Comment by ORelio** [comment]
**Remark:** Left click in a container is done this way: `/inventory container click <slot>`

**Comment by ORelio** [comment]
I'll close this issue in favor of #988.
