### ISSUE TITLE
Problème avec l'Anti AFK

### ISSUE THREAD

**Issue by Grimotte** [ORelio/Minecraft-Console-Client#989]
Bonjour,
Tout d'abord j'ai un problème avec l'Anti AFK quand je demande à la console d’exécuter le /script check, cette commande s'effectue sur le serveur et non dans la console donc le script ne se lance pas :(.
Auriez-vous une solution pour m'aider ?

**Comment by ORelio** [comment]
The AntiAFK bot is not designed to perform internal commands. You are looking for the ScriptScheduler.

**Comment by Grimotte** [comment]
Pour exécuterle script anti afk je dois utiliser ScriptScheduler si j'ai bien compris ?

**Comment by ORelio** [comment]
Seems like you did not read the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)? See [sample-tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini).
```ini
[Task]
triggerOnInterval=true
timeInterval=30
action=script check
```
