### ISSUE TITLE
Inventory Handling

### ISSUE THREAD

**Issue by lilobject** [ORelio/Minecraft-Console-Client#991]
I was having trouble with my config.ini so I deleted it and redownloaded it again to start over fresh. This new one that I had downloaded doesn't contain the option to turn on Inventory or InventoryHandling like the previous one that I had. Is this a bug or did I do something wrong that messed it up? Thanks!

**Comment by ORelio** [comment]
[develoment builds are here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).
