### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by mrxbox98** [ORelio/Minecraft-Console-Client#993]
**Prerequisites**
 - [ X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [X ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [X ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**

```cs
//MCCScript 1.0

/* This is a sample script for Minecraft Console Client
 * The code provided in this file will be compiled at runtime and executed
 * Allowed instructions: Any C# code AND methods provided by the MCC API */


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;



MCC.Loadbot(new ExampleBot());

//MCCScript Extensions

/* The ChatBot class must be defined as an extension of the script in the Extensions section
 * The class can override common methods from ChatBot.cs, take a look at MCC's source code */

string ign1 = "Mrxbox98";
string ign2 = "9HW";
string ign3 = "InfoDrop";
string ign4 = "Quizzix";



public class ExampleBot : ChatBot
{

    public override void GetText(string text)
    {
        string message = "";
        string username = "";
		
		while (true)
		{
			if (IsChatMessage(text, ref message, ref username)) 
			{
				if (message.Contains(ign1) || message.Contains(ign2) || message.Contains(ign3)  || message.Contains(ign4))
				{
					MCC.SendText("/tpyes");
				}
			}
		}
    }
}```

**Comment by mrxbox98** [comment]
it says 
[MCC] [Script] Script 'factions.cs' failed to run (LoadError).
[MCC] [Script] System.InvalidOperationException: Syntax error, '(' expected

**Comment by OverHash** [comment]
Can you please re-format your code so that it's all in the code block? Should look something like this:
\`\`\`cs
// your code here
\`\`\`

**Comment by mrxbox98** [comment]
> Can you please re-format your code so that it's all in the code block? Should look something like this:
> ```cs
> // your code here
> ```

fixed it

**Comment by mrxbox98** [comment]
So basicly what I am trying to do is when someone tries to tp to me using /tpa from that list of igns, it will accept.

**Comment by OverHash** [comment]
You should refer to RemoteControl in the ini file. It should do what you want.

**Comment by ORelio** [comment]
Hello,
As @OverHash stated, you can use RemoteControl to automatically accept teleport requests.
If you want to implement it as a script for personal experiments, here are some remarks about your script:
 - Do not use `while (true)` in an event, you'll hang the console, every message will call GetText()
 - IsChatMessage will not work here, you'll want to use IsTeleportRequest instead
 - The username is contained in the username variable, not in the message variable
