### ISSUE TITLE
How to join custom version RiseClient_1.8.9

### ISSUE THREAD

**Issue by umutergene** [ORelio/Minecraft-Console-Client#996]
Hi, i'm playing at craftrise server and ip play.craftrise.tc.
this server using their own version as RiseClient_1.8.9
How can i use Minecraft Console Client?

**Comment by ORelio** [comment]
Depends, if this is a standard modded Forge server MCC should handle it, if the modding is too custom i'll likely not work. Please look at the exact verbose messages shown by MCC when attempting to login, mainly protocol version vXX and exact error message shown when attempting to login. You can enable `debugmessages` in config to show more info.

**Comment by uploadRISE** [comment]
**bruh**

**Comment by ORelio** [comment]
> 
> 
> **bruh**

What? Anyway, I'll close this as resolved.
