### ISSUE TITLE
Inventory handling, not working with 1.8

### ISSUE THREAD

**Issue by jonysr** [ORelio/Minecraft-Console-Client#997]
So basically using the latest version and everything provided, when attempting to use Inventory handling for version 1.8 it does not work and gives this message "[MCC] Please enable inventoryhandling in config to use this command." 

it does not work for 1.8, however it does work for 1.10+ 

can this be made compatible with 1.8?

**Comment by 5tanly** [comment]
Not a bug, its a feature. Pretty much every time there's an update to Minecrafts code, the packets change. See #929. Currently only 1.10-1.15.2 is supported. I tried looking into this yesterday for like 2 hours and I believe [Protocol18.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/0529eb5162e08dfa528401fd529763b95c199fc6/MinecraftClient/Protocol/Handlers/Protocol18.cs) is what would need some work

**Comment by ORelio** [comment]
To be exact, it's not a bug, not a feature, but a _lack_ of feature 😄
Inventory handling is pretty new and not implemented (yet?) for older versions.
@5tanly is right, protocol implementation need to be expanded in Protocol18.cs

**Comment by ORelio** [comment]
Closing this in favour of #929
